### PR TITLE
extensbility: fix GitLab merge request ID regex

### LINKED ISSUE #22418: Extension icon requires refresh in GitLab merge request diff section
- **Sourcegraph version:** 3.28
- **Platform information:** Sourcegraph extension on GitLab. Related to SG internal issue #392

#### Steps to reproduce:

1. With the Sourcegraph extension installed in your browser and in a GitLab project, navigate to the `Changes` tab in the Merge Requests section.
2. Observe the initial URL upon page load. Sourcegraph extension icon is not visible on the code display section.
3. Refresh the page and observe the new URL. Sourcegraph extension ins now visible.

#### Expected behavior:
The initial page load in a merge request diff section should bring up the extension automatically.
 
#### Actual behavior:
A page refresh is required on GitLab in order for `diffs` to be added onto the URL for the extension to appear.

### PR DESCRIPTION
**Pull request by tjkandala**
Closes #22418.

We originally expected that clicking on the "Changes" tab on a GitLab merge request would add `/diffs` to the path. This is inconsistent, and the regex we use to capture the merge request ID assumes that `/diffs` is always present. We can work around GitLab not consistently adding `/diffs` when clicking on the diffs tab by checking that it is the active tab and executing an alternative regex.

<details>
<summary>GIF of extension working despite bad routing</summary>

</details>

### CODE REVIEW

File: client/browser/src/shared/code-hosts/gitlab/scrape.ts [hunk 1]
```diff
@@ -95,7 +95,14 @@ export function getFilePageInfo(): GitLabFileInfo {
  * Finds the merge request ID from the URL.
  */
 export const getMergeRequestID = (): string => {
-    const matches = window.location.pathname.match(/merge_requests\/(.*?)\/diffs/)
+    let matches = window.location.pathname.match(/merge_requests\/(.*?)\/diffs/)
+
+    // If /diffs hasn't been added to the path as a result of clicking the "Changes" tab (a known GitLab bug),
+    // check if the "Changes" tab is active. If so, try to find the merge request ID again.
+    if (!matches && !!document.querySelector('.diffs-tab.active')) {
```
Comment (vovakulikov) [inline client/browser/src/shared/code-hosts/gitlab/scrape.ts:102]: Just out of curiosity, Do we have some enum or configuration file with all selectors that we use for code hosts elements like GitLab or GitHub in our code base? 

```ts
enum GITHUB_ELEMENTS  {
   DiffTab: '.diff-tab.active'
   ...
   ...
}
```

**Review by vovakulikov — APPROVED** [review]
Oh this GitLab) Nice gif

File: client/browser/src/shared/code-hosts/gitlab/scrape.ts (hunk 1 above)
Comment (tjkandala) [reply client/browser/src/shared/code-hosts/gitlab/scrape.ts:102]: We have the [`ViewResolver`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/shared/code-hosts/shared/views.ts?L28:18#tab=references) type for generic elements across that are (abstractly) shared between code hosts, but this diff tab is only queried to work around a GitLab bug. We could store all the selectors for elements specific to code hosts, but not sure if the indirection would be helpful when most of these selectors are only used in one place

Comment (vovakulikov) [reply client/browser/src/shared/code-hosts/gitlab/scrape.ts:102]: Got it. Thanks 👍

**Comment by lkknguyen** [comment]
MR still opens since 6 days and bug is not working in our company. Can you pls review and ship asap? @muratsu

**Comment by muratsu** [comment]
UI Review changes seem unrelated. Merging the change.
