### PR TITLE
batches: retain previous changeset error message to prevent UI flashing

### LINKED ISSUE #46651: batches: changeset error message shouldn’t disappear from the UI until a batch change retry actually succeeds
a customer is unhappy with what happens during the retry loop: [slack thread](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1674082705160849)

It can be hard to capture the error message as it flashes while a failed batch change continues to retry

This fix can go hand in hand with #46652 , which addresses the need to add a button or mechanism for stopping automatic retries on a given changeset that’s misbehaving.

### PR DESCRIPTION
**Pull request by adeola-ak**
closes #46651

added a new field previous_failure_message which will store the value of failure_message before its cleared for retry and prevent the error from flashing and then resurfacing again

https://user-images.githubusercontent.com/67931373/224161307-2731bd78-dca0-4607-85da-b43c9d04a210.mp4

## Test plan

Observed the error message no longer flash for retries

### CODE REVIEW

**Comment by courier-new** [comment]
Do you mind posting a GIF/loom of the change in action when a changeset operation errors out? 🙂

File: enterprise/cmd/frontend/internal/batches/resolvers/changeset.go [hunk 1]
```diff
@@ -355,7 +355,12 @@ func (r *changesetResolver) CheckState() *string {
 	return &checkState
 }
 
-func (r *changesetResolver) Error() *string { return r.changeset.FailureMessage }
+func (r *changesetResolver) Error() *string {
```
Comment (courier-new) [inline enterprise/cmd/frontend/internal/batches/resolvers/changeset.go:358]: I think it'd be useful to leave a pretty thorough note here about how we're resolving this field that gives some context about the issue we're fixing, something like:

```suggestion
// Normally, `FailureMessage` is set by the reconciler worker if it fails when processing
// a changeset job. However, for most reconciler operations, we automatically retry the
// operation a number of times. When the reconciler worker picks up a failed changeset job
// to restart processing, it clears out the `FailureMessage`, resulting in the error
// disappearing in the UI where we use this resolver field. To retain this context even as
// we retry to process the changeset, we copy over the error to `PreviousFailureMessage`
// when re-enqueueing a changeset and clearing its original `FailureMessage`. Only when a
// changeset is successfully processed will the `PreviousFailureMessage` be cleared.
//
// When resolving this field, we still prefer the latest `FailureMessage` we have, but if
// there's not a `FailureMessage` and there is a `Previous` one, we return that.
func (r *changesetResolver) Error() *string {
```

File: enterprise/internal/batches/reconciler/executor.go [hunk 2]
```diff
@@ -130,6 +130,7 @@ func (e *executor) Run(ctx context.Context, plan *Plan) (err error) {
 		if err != nil {
 			return err
 		}
+
```
Comment (courier-new) [inline enterprise/internal/batches/reconciler/executor.go:133]:
```suggestion
```

File: enterprise/internal/batches/reconciler/reconciler.go [hunk 3]
```diff
@@ -66,6 +66,7 @@ func (r *Reconciler) HandlerFunc() workerutil.HandlerFunc[*btypes.Changeset] {
 // errored and set its FailureMessage to the error.
 func (r *Reconciler) process(ctx context.Context, logger log.Logger, tx *store.Store, ch *btypes.Changeset) error {
 	// Reset the error message.
+	ch.PreviousFailureMessage = ch.FailureMessage
 	ch.FailureMessage = nil
```
Comment (courier-new) [inline enterprise/internal/batches/reconciler/reconciler.go:70]: I actually wonder if we should wrap this in a conditional like:

```suggestion
	if ch.FailureMessage != nil {
		ch.PreviousFailureMessage = ch.FailureMessage
		ch.FailureMessage = nil
	}
```

My reason for suggesting this is that I _think_ since `store.EnqueueChangeset()` also copies it over and sets `FailureMessage` to `nil`, we might be doing this twice for changesets enqueued that way, so this might happen:

1. We call `store.EnqueueChangeset(ctx, changeset_1, ...)` for a changeset that had an error
    - `changeset_1.PreviousFailureMessage` gets set to the error
    - `changeset_1.FailureMessage` gets set to `nil`
2. Reconciler worker picks up `changeset_1` and calls `process(ctx, logger, tx, changeset_1)` here
    - `changeset_1.FailureMessage` is already `nil`, so `changeset_1.PreviousFailureMessage` gets set to `nil`
    - (not that it matters) `changeset_1.FailureMessage` gets set to `nil` again

And thus we lose the `PreviousFailureMessage`.

With a check like this first, we could ensure we're not unintentionally clearing out the `PreviousFailureMessage` if we already did that whole copy + reset dance.

File: enterprise/cmd/frontend/internal/batches/resolvers/changeset.go [hunk 4]
```diff
@@ -355,7 +355,23 @@ func (r *changesetResolver) CheckState() *string {
 	return &checkState
 }
 
-func (r *changesetResolver) Error() *string { return r.changeset.FailureMessage }
+// Normally, `FailureMessage` is set by the reconciler worker if it fails when processing
```
Comment (Piszmog) [inline enterprise/cmd/frontend/internal/batches/resolvers/changeset.go:358]: For the sake of my IDE yelling at me, could you start the doc with `Error` (Go docs start with the name of the thing, expect package docs)

**Review by Piszmog — APPROVED** [review]

File: enterprise/cmd/frontend/internal/batches/resolvers/changeset.go (hunk 4 above)
Comment (courier-new) [reply enterprise/cmd/frontend/internal/batches/resolvers/changeset.go]: Is that just a thing in GoLand? I thought it was just a convention to start a comment with the name of the func, as there's nothing explicit about that in the [docs on Go comments](https://go.dev/doc/comment), and the VSCode Go extension doesn't seem to care. Genuinely just curious. I bet your IDE is unhappy a lot of the time, then, as I'm sure there's plenty of other offenders like [this one](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/batches/resolvers/changeset.go?L195-203) too. 😅

**Review by courier-new — APPROVED** [review]
Thanks for the video! 🙌

**Comment by courier-new** [comment]
I think there's just some format/linting errors on buildkite. You should be able to run `sg lint --fix go` to fix them. 🙂
