### PR TITLE
Fix filter selection in FilteredConnection

### LINKED ISSUE #16912: codeintel: Correct filter connection behavior
Not sure if this is a codeintel use bug or a filtered connection bug, but going between different radio button states will not always refresh the list of current items. Going from Errored to Queued will continue to show some Errored items until the user performs more component interactions or refreshes.

Not always consistently triggerable, but I've seen it multiple times.

### PR DESCRIPTION
**Pull request by eseliger**
On the first filter change, the same values as shown before would be displayed, albeit they are being fetched.

Because the map wasn't copied, the internal state of the previous value also changes. This fixes it.

Closes #16912

### CODE REVIEW

**Comment by efritz** [comment]
Fixes https://github.com/sourcegraph/sourcegraph/issues/16912.

**Review by efritz — APPROVED** [review]

**Review by limitedmage — APPROVED** [review]

File: client/web/src/components/FilteredConnection.tsx [hunk 1]
```diff
@@ -927,7 +927,7 @@ export class FilteredConnection<N, NP = {}, C extends Connection<N> = Connection
         if (this.props.filters === undefined) {
             return
         }
-        const values = this.state.activeValues
+        const values = new Map(this.state.activeValues)
```
Comment (felixfbecker) [inline client/web/src/components/FilteredConnection.tsx:930]: So this PR makes changes to both
- Break the reference
- and do a deep comparison

wouldn't only one of the two be needed?

Comment (eseliger) [reply client/web/src/components/FilteredConnection.tsx:930]: You're right, I somehow thought it would be invalidated each time. Removed and still works, thanks for being thorough :)
