### PR TITLE
search: Monaco query editor should not syntax highlight links or unknown filters

### LINKED ISSUE #10056: Recognize stable: parameter in smart search
Screen Shot 2020-04-20 at 1 57 47 PM

### LINKED ISSUE #12961: Monaco editor thinks search terms are a link
The new parser fixes some issues that allow search patterns with colons. Turns out when the pattern resembles a URL, a hover for a link will appear. Not strictly wrong, but probably not desired? Also, we should probably only highlight [recognized fields](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/query/fields.go), not all alpha characters that precede a `:`:

Screen Shot 2020-08-12 at 8 41 09 PM

CC @limitedmage since we chatted about some of this kind of thing :-)

### PR DESCRIPTION
**Pull request by limitedmage**
Fixes #12961 with two changes to the Monaco query input:
- URLs are no longer clickable
- Input that looks like a filter (eg. 'https:' or C++ namespaces) are no longer treated as unknown filters or syntax highlighted

Also fixes #10056

image

image

### CODE REVIEW

File: shared/src/search/interactive/util.ts [hunk 1]
```diff
@@ -41,9 +41,20 @@ export enum FilterType {
     index = 'index',
 }
 
+export enum AliasedFilterType {
+    r = FilterType.repo,
+    f = FilterType.file,
+    l = FilterType.lang,
+    patternType = FilterType.patterntype,
```
Comment (rvantonder) [inline shared/src/search/interactive/util.ts:48]: `patterntype` doesn't have an alias (unlike `file:`, which has alias `f:`), so do we need to add this variable here?

File: shared/src/search/interactive/util.ts [hunk 2]
```diff
@@ -41,9 +41,20 @@ export enum FilterType {
     index = 'index',
 }
 
+export enum AliasedFilterType {
+    r = FilterType.repo,
+    f = FilterType.file,
+    l = FilterType.lang,
```
Comment (rvantonder) [inline shared/src/search/interactive/util.ts:47]: Looks like we are missing some aliases. All of the strings here are aliases that we should cover: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Einternal/search/query/fields%5C.go+%22:%5Balias%5D%22&patternType=structural

File: shared/src/search/parser/parser.ts [hunk 3]
```diff
@@ -251,7 +252,7 @@ const operator = pattern(
     (input, { start, end }): Operator => ({ type: 'operator', value: input.slice(start, end) })
 )
 
-const filterKeyword = pattern(/-?[A-Za-z]+(?=:)/)
+const filterKeyword = pattern(new RegExp(`-?(${filterTypeKeysWithAliases.join('|')})+(?=:)`))
```
Comment (rvantonder) [inline shared/src/search/parser/parser.ts:255]: Note that the set of input patterns do not need to case match (we will accept `repo:`, `Repo:`, `REPO:`, in the backend--we normalize by converting the fields to lowercase. I think the regex `-?` modifier does that here, but I just skimmed the tests and didn't immediately see a test for this, so it's worth double checking.

File: shared/src/search/interactive/util.ts [hunk 4]
```diff
@@ -41,9 +41,20 @@ export enum FilterType {
     index = 'index',
```
Comment (rvantonder) [inline shared/src/search/interactive/util.ts:41]:
```suggestion
    index = 'index',
    stable = 'stable',
```
The `stable` one is missing from this list, I've been meaning to add it :-) https://github.com/sourcegraph/sourcegraph/issues/10056

File: shared/src/search/interactive/util.ts (hunk 1 above)
Comment (limitedmage) [reply shared/src/search/interactive/util.ts:48]: Ah I added this one because of the case sensitivity issues. Good to know that filters should be case insensitive. Fixed that instead.
