### PR TITLE
extensibility: use sideloaded settings schema over remote

### LINKED ISSUE #20679: Extension package.json changes don't propagate while side loading
When we make changes to "contributes" fields while side loading extensions, the user settings auto-complete will ignore the local copy and use the public package.json

#### Steps to reproduce:

1. Run local copy of SG
2. Make changes on a local extension package.json. Eg. for codecov, change "codecov.insight.icicle"s description to "wow it changed!".
3. Side load the codecov extension
4. Navigate to https://sourcegraph.test:3443/users/test/settings
5. Hover on "codecov.insight.icicle"

#### Expected behavior:
1. See "wow it changed!"

#### Actual behavior:
1. "Show an interactive coverage icicle graph on repository pages."

### PR DESCRIPTION
**Pull request by tjkandala**
Fix #20679.

It appears that Monaco uses the first occurrence of a key in an [`allOf`](https://json-schema.org/understanding-json-schema/reference/combining.html#id5) array.

#### Before

Screenshot from 2021-07-25 18-09-36

#### After

Screenshot from 2021-07-25 18-09-24

### CODE REVIEW

File: client/web/src/settings/SettingsArea.tsx [hunk 1]
```diff
@@ -203,7 +203,9 @@ export class SettingsArea extends React.Component<Props, State> {
             ),
         ]).pipe(
             map(([registryExtensions, sideloadedExtension]) =>
-                [...registryExtensions, sideloadedExtension].filter(isDefined)
+                // Ensure that sideloaded extension settings keys have precedence over
+                // the same keys from its registry extension counterpart
+                [sideloadedExtension, ...registryExtensions].filter(isDefined)
```
Comment (vovakulikov) [inline client/web/src/settings/SettingsArea.tsx:208]: Nice thanks for this fix. I've spent a lot of time debugging API schema in my extension to be sure that works correctly with our Monaco editor and other scheme definitions

**Review by vovakulikov — APPROVED** [review]
