### PR TITLE
repo-updater: Hard deletes and fixes for swapped repos

### LINKED ISSUE #3680: repo-updater duplicate repo issue
In some customer deployments we've observed a problem where duplicate repos somehow end up appearing after `NewDiff` and they prevent repo-updater from doing its job properly. See customer issue for further details.

### PR DESCRIPTION
**Pull request by tsenart**
Fixes #3680
Super-seeds #3709

### CODE REVIEW

**Comment by tsenart** [comment]
@keegancsmith: The only thing failing right now is a `Syncer.Sync` test running with `FakeStore`. This means we need to patch `FakeStore`. Tests with `DBStore` are passing.

File: cmd/repo-updater/repos/store.go [hunk 1]
```diff
@@ -597,47 +628,26 @@ inserted AS (
...
+  inserted.external_service_id,
+  inserted.external_id,
+  inserted.enabled,
+  inserted.archived,
+  inserted.fork,
+  inserted.sources,
+  inserted.metadata
+FROM inserted
+LEFT JOIN batch ON batch.name = inserted.name
 ORDER BY batch.ordinality
```
Comment (keegancsmith) [inline cmd/repo-updater/repos/store.go]: do we still need the returning and with statements? I would assume just simple delete / insert / update queries is all that is needed.

Edit: I experimented with this and got weird results. So lets just leave it as is.

File: migrations/1528395575_.up.sql [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+  REFERENCES repo(id)
+  ON DELETE CASCADE;
+
+-- Hard delete existing soft deleted rows.
+DELETE FROM repo WHERE deleted_at IS NOT NULL;
+
+-- Ensure we don't accidently soft delete going forward.
+ALTER TABLE repo ADD CONSTRAINT deleted_at_unused CHECK (deleted_at IS NULL);
+
+COMMIT;
```
Comment (keegancsmith) [inline migrations/1528395575_.up.sql]: @slimsag can you review this change. We hard delete existing soft deleted repositories. To allow that we also update all transitive foreign keys to cascade delete.

File: cmd/frontend/db/repos.go [hunk 3]
```diff
@@ -550,22 +550,8 @@ func (s *repos) Delete(ctx context.Context, repo api.RepoID) error {
...
-		_, err := DiscussionThreads.Update(ctx, thread.ID, &DiscussionThreadsUpdateOptions{hardDelete: true})
-		if err != nil {
-			return err
-		}
-	}
-
-	q := sqlf.Sprintf("UPDATE repo SET deleted_at = NOW() WHERE id=%d", repo)
-	_, err = dbconn.Global.ExecContext(ctx, q.Query(sqlf.PostgresBindVar), q.Args()...)
+	q := sqlf.Sprintf("DELETE FROM repo WHERE id=%d", repo)
+	_, err := dbconn.Global.ExecContext(ctx, q.Query(sqlf.PostgresBindVar), q.Args()...)
```
Comment (keegancsmith) [inline cmd/frontend/db/repos.go]: @slimsag can you review this change. Now that we cascade delete we don't need the application logic for hard deleting discussions.

Comment (slimsag) [reply cmd/frontend/db/repos.go]: We should remove the `hardDelete` field and associated logic from `DiscussionThreadsUpdateOptions` too

Comment (keegancsmith) [reply cmd/frontend/db/repos.go]: Can I follow up with that in another PR to minimize the amount of changes needed? Filed https://github.com/sourcegraph/sourcegraph/issues/3749

File: migrations/1528395575_.up.sql (hunk 2 above)
Comment (slimsag) [reply migrations/1528395575_.up.sql]: I think this needs to become cascade, too: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@2fd284c96f40e38c698cce4d00025efd3bf3353c/-/blob/cmd/frontend/db/schema.md?view=code#L102

And this: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@2fd284c96f40e38c698cce4d00025efd3bf3353c/-/blob/cmd/frontend/db/schema.md?view=code#L128

Comment (keegancsmith) [reply migrations/1528395575_.up.sql]: Will add it.

Weird how the test doesn't fail. I think that is due to having a cycle in your foreign constraints:
- `discussion_threads.target_repo_id `  depends on `discussion_threads_target_repo`
- `discussion_threads_target_repo.thread_id` depends on `discussion_threads`.

I guess postgres just realises it can solve the conflict by deleting on cascade. So this still works. But will update to make that cascade as well.

Comment (slimsag) [reply migrations/1528395575_.up.sql]: Correct. Providing further details / explanation: The cycle is intentional (they are objects linked to one another effectively, so that it is possible to look up one from the other) and is possible because the constraint is nullable. In the case of deletion though, we would want it to cascade instead of them being nullified and having them exist as detached objects.

**Comment by slimsag** [comment]
> Super-seeds #3709

btw @tsenart english is a 🗑🔥 so that word gets spelled supersedes

**Comment by slimsag** [comment]
Keegan said on Slack:

> Pushed the suggested change. I am happy with the state of that PR. I've reviewed Tomas's changes and they LGTM. You have reviewed the important change from me. I would say this PR is ready for merging. The only reason I am not doing it now is because I am going to bed so won't have time to react to it going wrong on dogfood (unlikely, but that is famous last words). If you can monitor it and feel comfortable please merge; check it out on dogfood; cherry-pick into a patch branch.

I am going to do just that. After merge I'll check logs on dogfood for any errors and confirm things there look generally sane, then do a patch inclusive of this change.

File: cmd/repo-updater/repos/testing.go [hunk 4]
```diff
@@ -281,10 +280,12 @@ var Assert = struct {
 }{
 	ReposEqual: func(rs ...*Repo) ReposAssertion {
 		want := append(Repos{}, rs...).With(Opt.RepoID(0))
+		sort.Sort(want)
```
Comment (tsenart) [inline cmd/repo-updater/repos/testing.go]: I'm afraid this change prevents us from testing order at call site, which we're doing in some places.

Comment (keegancsmith) [reply cmd/repo-updater/repos/testing.go]: What do you propose as a solution? This fixes our tests which do all permutations. Should we only opt into this behaviour for those tests? Also why is order important?

Comment (tsenart) [reply cmd/repo-updater/repos/testing.go]: > Should we only opt into this behaviour for those tests?

Yes.

>  Also why is order important?

It's important where it's specified. For instance, the repos returned by `Store.ListRepos` should be in ascending order by id. Here's an instance of a test for this property: https://github.com/sourcegraph/sourcegraph/blob/master/cmd/repo-updater/repos/store_test.go#L603

Comment (keegancsmith) [reply cmd/repo-updater/repos/testing.go]: Filed https://github.com/sourcegraph/sourcegraph/issues/3777
