### PR TITLE
Retry once if updating Bitbucket PR fails due to outdated version

### LINKED ISSUE #28962: Batch Changes and Bitbucket: 409 error when updating batch changes after they were published
- **Sourcegraph version:** 3.34.2 
- **Platform information:** docker-container 

#### Steps to reproduce:

1. Attempted to update some batch changes after they have been published
2. Most of those changes are now in an error state and failing with errors like:

```
Updating changeset: Bitbucket API HTTP error: code=409 url="<url example here>" body="{"errors":[{"context":null,"message":"You are attempting to modify a pull request based on out-of-date information.","exceptionName":"com.atlassian.bitbucket.pull.PullRequestOutOfDateException","currentVersion":2,"expectedVersion":1,"pullRequest":{"id":89,"version":2,...
```
3. Updated step: This looks like it could have been caused by changing the PR title and/or description in the batch change. Reverting the title/description changes appears to get sourcegraph back in a better state.

#### Expected behavior:

Batch change should succeed without error or not get stuck in a failed state.

#### Actual behavior:

Stuck in a failed state.

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

### PR DESCRIPTION
**Pull request by mrnugget**
This fixes #28962 by changing the `BitbucketServerSource` to retry the
`UpdatePullRequest` if it failed because the local copy of the
Sourcegraph pull request is outdated.

If we don't do that, we're trapped in a deadlock between the reconciler
and the syncer: the reconciler tries to update the PR and keeps failing
because the local copy is outdated and the syncer won't update the local
copy because the reconciler never sets the `changeset` to `completed`.

What the change here does is to "force" the update by using the newest
version that the server returns with its error and sending that along
with the update request.

That might sound questionable, but it's what we do for other code hosts
as well and is, essentially, how Batch Changes are supposed to work:
users describe the desired state in their batch spec and Sourcegraph
tries its best to make that happen. This is no different than how we
already overwrite commits that someone has pushed to a branch if a spec
is applied again.

### CODE REVIEW

**Review by eseliger — COMMENTED** [review]
Great catch and nice work :)

I think all write methods that are based on existing data suffer from this issue. So we should probably pull out that "retry on out of date error" logic and also use it in `CloseChangeset`, `ReopenChangeset`, `CreateComment`(not sure about that one), and `MergeChangeset`

**Comment by mrnugget** [comment]
@eseliger can you take a look? I added the retry for the other methods too

File: enterprise/internal/batches/sources/bitbucketserver.go [hunk 1]
```diff
@@ -262,12 +286,40 @@ func (s BitbucketServerSource) MergeChangeset(ctx context.Context, c *Changeset,
...
+	if !bitbucketserver.IsPullRequestOutOfDate(err) {
+		return nil, err
+	}
+
+	newestPR, err2 := bitbucketserver.ExtractPullRequest(err)
+	if err2 != nil {
+		return nil, errors.Wrap(err, "failed to extract pull request after receiving error")
+	}
+
+	log15.Info("Reopening Bitbucket Server PR failed because it's outdated. Retrying with newer version", "ID", pr.ID, "oldVersion", pr.Version, "newestVerssion", newestPR.Version)
```
Comment (eseliger) [inline enterprise/internal/batches/sources/bitbucketserver.go:317]: This log line seems wrong

File: enterprise/internal/batches/sources/bitbucketserver.go [hunk 2]
```diff
@@ -222,7 +222,26 @@ func (s BitbucketServerSource) UpdateChangeset(ctx context.Context, c *Changeset
...
+		log15.Info("Updating Bitbucket Server PR failed because it's outdated. Retrying with newer version", "ID", pr.ID, "oldVersion", pr.Version, "newestVerssion", newestPR.Version)
+
+		// ... and try again, but this time with the newest version
+		update.Version = newestPR.Version
+		updated, err = s.client.UpdatePullRequest(ctx, update)
+		if err != nil {
+			// If that didn't work, we bail out
+			return err
+		}
 	}
```
Comment (eseliger) [inline enterprise/internal/batches/sources/bitbucketserver.go:245]: can't we use the helper here too?

Comment (eseliger) [reply enterprise/internal/batches/sources/bitbucketserver.go:245]: I would also move the comments in here into the helper fn, they make it really easy to understand what's happening here :)

**Review by eseliger — APPROVED** [review]

File: enterprise/internal/batches/sources/bitbucketserver.go (hunk 2 above)
Comment (mrnugget) [reply enterprise/internal/batches/sources/bitbucketserver.go:245]: Not that easily, because the `UpdatePullRequest` method doesn't take a `*PullRequest` as input. I tried to make this work, but it's a lot of bending over backwards and I ended up thinking that a different-but-similar code here is easier to understand.

I can copy/move the comments, though

**Comment by mrnugget** [comment]
@eseliger I added tests for the other methods too. Merging if everything passes.
