### PR TITLE
Run paginated queries in SetClonedRepos

### LINKED ISSUE #14431: repo-updater: SetClonedRepos fails with temporary file size exceeds temp_file_limit error
Repo-updater [SetClonedRepos](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/cmd/repo-updater/repos/store.go?utm_source=VSCode-1.1.0#L897:24) function returns a PostgreSQL error ([logs](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22sourcegraph-dev%22%0Aresource.labels.container_name%3D%22repo-updater%22%0Aresource.labels.cluster_name%3D%22cloud%22%0Aresource.labels.namespace_name%3D%22prod%22%0Aseverity%3DERROR;summaryFields=:true:32:beginning?customFacets=&scrollTimestamp=2020-10-05T11:20:24.856581515Z&project=sourcegraph-dev)): `pq: temporary file size exceeds temp_file_limit`.

### PR DESCRIPTION
**Pull request by asdine**
This PR modifies the SetClonedRepos method to use the same query as before but on 400k repos pages.
On Cloud, this means running about 4 queries (~around 1.3M cloned repos). This should fix the `pq: temporary file size exceeds temp_file_limit` error by reducing the number of temporary files.

Fixes #14431

### CODE REVIEW

File: cmd/repo-updater/repos/store.go [hunk 1]
```diff
@@ -900,22 +905,52 @@ func (s DBStore) SetClonedRepos(ctx context.Context, repoNames ...string) error
...
 	}
 
-	names, err := json.Marshal(repoNames)
-	if err != nil {
-		return nil
+	tx, ok := s.db.(*sql.Tx)
+	if !ok {
+		txstore, err := s.Transact(ctx)
+		if err != nil {
+			return errors.Wrap(err, "scanRepo: failed to create a transaction")
```
Comment (ryanslade) [inline cmd/repo-updater/repos/store.go:912]:
```suggestion
			return errors.Wrap(err, "SetClonedRepos: failed to create a transaction")
```

**Review by ryanslade — APPROVED** [review]
LGTM, how did you decide on 400k?

**Comment by asdine** [comment]
> how did you decide on 400k

Totally arbitrary. I initially started with 100k but the logs show that on Cloud the number of cloned repos is about 1.3 M which would mean 13 network calls. I suppose 400k should be enough for most cases, but I'm open to suggestions.

**Comment by ryanslade** [comment]
> > how did you decide on 400k
> 
> Totally arbitrary. I initially started with 100k but the logs show that on Cloud the number of cloned repos is about 1.3 M which would mean 13 network calls. I suppose 400k should be enough for most cases, but I'm open to suggestions.

I'm a bit worried about how it may run on some customer instances with limited resources. I think I'd rather have it lower, maybe 100k is fine. I think we should also reduce how often this runs, it's currently every 10 seconds, maybe once every minute or even longer is enough? What are the downsides of this being out of sync for a couple of minutes?

https://github.com/sourcegraph/sourcegraph/blob/958cb4991452b13f258dbbd974e1e0ba1210568d/cmd/repo-updater/shared/main.go#L359

**Comment by asdine** [comment]
> I think I'd rather have it lower, maybe 100k is fine

I'm afraid it won't scale very well on Cloud. How about doing it on a percentage of the number of repos if it's above 100k, capped at 500k?
For example:

< 100k cloned repos: 1 query
< 2.5M cloned repos: 5 queries, each for 20% of the repos
\> 2.5M cloned repos: N queries of 500k each

**Comment by ryanslade** [comment]
How about starting with a safe default, say 100k and then make it configurable. On cloud we can set it to 500k

File: cmd/repo-updater/repos/store.go [hunk 2]
```diff
@@ -928,10 +963,14 @@ diff AS (
...
-      AND name IN (SELECT name::citext FROM cloned_repos)
-    OR cloned
-      AND name NOT IN (SELECT name::citext FROM cloned_repos)
+	  name BETWEEN %s AND %s
+	AND
+    (
+		NOT cloned
+		  AND name IN (SELECT name::citext FROM cloned_repos)
+		OR cloned
+		  AND name NOT IN (SELECT name::citext FROM cloned_repos)
```
Comment (tsenart) [inline cmd/repo-updater/repos/store.go:972]: I'm not 100% sure this logic works with as is. What happens if we inserted repos in the meantime and the page boundaries don't align?

Comment (asdine) [reply cmd/repo-updater/repos/store.go:968]: Since all of these calls are run in the same transaction I think the other repositories shouldn't be visible.
Even if we changed the isolation level I think it should be fine because these new repositories would most likely not be cloned yet, and if so they would be updated in the next call to SetClonedRepos.
SetClonedRepos is not strongly consistent by nature because it receives that latest complete cloned list from GitServer, and by the time this function is called, there might be some other repos that have been inserted/cloned.

Comment (tsenart) [reply cmd/repo-updater/repos/store.go:968]: I see. I'm still a bit hesitant, because this approach makes it quite harder to reason about correctness. One alternative I think we should (and I just thought of) is to create a temporary table that gets deleted at the end of the transaction which contains all the names of cloned repos we receive from git-server. We write to this table in batches, but then, once that's done, would use the previous query we had.

Comment (asdine) [reply cmd/repo-updater/repos/store.go:968]: The problem I see with this approach is that we are writing more than necessary which is what we are trying to avoid by writing a query this complex in the first place.
For example, let's say we have 4M repos, and 2 of them are cloned, writing to a temporary table would initiate N writes with 2M <= N <= 4M, every time we run this query.
With the current approach, we'd have 0 <= N <= 2M, with N being 0 or close to 0 most of the time.
Of course, the temporary table would be lock-free because no other process is supposed to be using it, but it's still a lot of disk access.

Also, I think transaction isolation is there to prevent any bad surprise, whether we write to a temporary table or directly in the repo table, the isolation remains the same. In our case it means that even if another transaction adds another repo to that table, it wouldn't be visible here and the query would work as if nothing happened.

The only problem I see with the current approach is that updated rows might be locked longer than before because we are waiting for the batch to complete to commit the transaction.
However it shouldn't be an issue since we are only locking rows that have changed recently.

Comment (asdine) [reply cmd/repo-updater/repos/store.go:968]: After discussion with @tsenart, we decided that while the proposed query seems correct it is not easy to understand. Compared to it, writing to a temp table would actually make things simpler. I'll update the PR with the new query

**Comment by tsenart** [comment]
How does the query plan look?

**Comment by tsenart** [comment]
In any case, we should test it in production and see how long it takes via monitoring / tracing.

**Review by tsenart — APPROVED** [review]

**Comment by asdine** [comment]
> How does the query plan look?

On my computer I can't see much because I don't have that much relevant data:

Capture
