### PR TITLE
search pagination: add more tests & fix bugs

### LINKED ISSUE #5999: Search pagination: add tests that guarantee searchFilesInRepos ordering
After https://github.com/sourcegraph/sourcegraph/pull/4796 is merged, we rely on the order of searchFilesInRepos being sorted in some ways. Tests should be added that verify it works as expected to reduce the risk of regressing the pagination API.

### LINKED ISSUE #6286: Search pagination: API can omit one repository at end of result set

### LINKED ISSUE #6287: Search pagination: low `first` count gets stuck
[this query](https://sourcegraph.com/api/console#%7B%22variables%22%3A%22%7B%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22repogroup%3Asample%20type%3Afile%20implements%20a%5C%22%2C%5Cn%20%20%5C%22perPage%5C%22%3A%205%2C%5Cn%20%20%5C%22after%5C%22%3A%20%5C%22U2VhcmNoQ3Vyc29yOnsiUmVwb3NpdG9yeU9mZnNldCI6NCwiUmVzdWx0T2Zmc2V0Ijo1LCJGaW5pc2hlZCI6ZmFsc2V9%5C%22%5Cn%7D%22%2C%22query%22%3A%22query%20PaginatedSearch(%24query%3A%20String!%2C%20%24perPage%3A%20Int!%2C%20%24after%3A%20String)%20%7B%5Cn%20%20search(query%3A%20%24query%2C%20first%3A%20%24perPage%2C%20after%3A%20%24after)%20%7B%5Cn%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20%20%20...%20on%20FileMatch%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20repository%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20file%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20path%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20pageInfo%20%7B%5Cn%20%20%20%20%20%20%20%20endCursor%5Cn%20%20%20%20%20%20%20%20hasNextPage%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%7D) returns the same `endCursor` as the input `after` -- i.e. pagination is broken here entirely.

### PR DESCRIPTION
**Pull request by slimsag**
After this PR, all of the complex logic in the search pagination API (planning and slicing) is covered by tests extensively. The addition of the tests in this PR caught one off-by-one issue #6286 which is also fixed by this PR.

Fixes #5999
Fixes #6286
Fixes #6287

### CODE REVIEW

File: cmd/frontend/internal/pkg/search/repo_revs.go [hunk 1]
```diff
@@ -64,6 +65,10 @@ type RepositoryRevisions struct {
 	indexedHEADCommit api.CommitID
 }
 
+func (r *RepositoryRevisions) Equal(other *RepositoryRevisions) bool {
+	return reflect.DeepEqual(r, other)
```
Comment (keegancsmith) [inline cmd/frontend/internal/pkg/search/repo_revs.go]: this doesn't work, since you are testing if the unexported fields are also equal. You only want to check if Repo and Revs are equal.

https://golang.org/pkg/reflect/#DeepEqual

> Struct values are deeply equal if their corresponding fields, both exported and unexported, are deeply equal.
