### PR TITLE
JetBrains: Cody: Allow manual autocomplete to be triggered even when implicit completions are disabled 

### LINKED ISSUE #56345: JetBrains: allow explicit autocomplete with alt-backslash even when autocomplete is disabled
To reproduce:

* Disable autocomplete in settings
* Trigger autocomplete with alt-backslash

The current behavior is that nothing happens. I expect autocomplete to trigger with alt-backslash even if it's disabled in the settings. The setting should only disable *automatic* or *implicit* autocomplete.

### PR DESCRIPTION
**Pull request by Gedochao**
Fixes #56345 

- manual autocomplete should now be able to bypass implicit autocomplete configuration
- some util classes were cleaned up, moved or translated to Kotlin
- some dead code was removed

## Test plan
- check if manual autocomplete (alt + backslash) can be triggered when implicit autocomplete is disabled in settings
- check if manual autocomplete can be triggered when implicit autocomplete is disabled for a particular language in settings
- check if autocomplete inlays are cleared correctly in the scenarios mentioned above
- check if other autocomplete uses work as expected

### CODE REVIEW

File: client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java [hunk 1]
```diff
@@ -370,7 +353,7 @@ public static List<String> characterList(String value) {
       String indentation =
           item.insertText.substring(
               0, item.insertText.length() - withoutLeadingWhitespace.length());
-      String newIndentation = EditorUtils.tabsToSpaces(indentation, indentOptions);
+      String newIndentation = CodyEditorUtil.tabsToSpaces(indentation, indentOptions);
```
Comment (olafurpg) [inline client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java:356]: FYI, the enclosing `normalizeIndentation` method is unused and can be removed

**Review by olafurpg — APPROVED** [review]
LGTM 👍🏻 I just tried this locally and it works as expected.
