### PR TITLE
Browser extension GSuite deployment fixes

### LINKED ISSUE #3604: Remove unused StorageItems from browser extensions
There are a lot of StorageItems that are not _written_ to anywhere in the code base (they are _read_ though).

https://github.com/sourcegraph/sourcegraph/blob/68b73cac8a1fd9a9f2ad221ee12d53bd53b84d15/client/browser/src/browser/types.ts#L55-L79

@KattMingMing @sqs can we remove them or are they set through GCloud Admin and used by customers? If they are, which of them, and who did we document them to?

### PR DESCRIPTION
**Pull request by lguychard**
Rel #5604
Closes #3604

Removes unused storage items, adds the ability to set the Sourcegraph URL through managed storage, and cleans up storage access.

- Remove unused storage items `repoLocations` (never read) and `enterpriseUrls`. The only consequence of having `enterpriseURLs` present in storage was to set the browser action to open the options page instead of the popup. In the options page, nothing specific is done when enterpriseURLs were present. They were otherwise unused in the browser extension.
- Handle reading the `sourcegraphURL` from managed storage.
- Split StorageItems by storage area: there are now different storage item types for local, sync and managed storage items. The typings of `observeStorageKey` and `storage` reflect this. Rather than copying all items from managed storage to sync storage upon installation, relevant storage items (for instance `phabricatorMappings`) are directly observed from managed storage.

### CODE REVIEW

File: browser/src/browser/storage.ts [hunk 1]
```diff
@@ -1,33 +1,52 @@
...
-export const observeStorageKey = <K extends keyof StorageItems>(
-    areaName: browser.storage.AreaName,
+export const observeStorageKey = <A extends browser.storage.AreaName, K extends keyof ExtensionStorageItems[A]>(
+    areaName: A,
     key: K
-): Observable<StorageItems[K] | undefined> =>
-    concat(
+): Observable<ExtensionStorageItems[A][K] | undefined> => {
+    if (getPlatformName() !== 'chrome-extension' && areaName === 'managed') {
+        // Accessing managed storage throws an error on Firefox.
```
Comment (felixfbecker) [inline browser/src/browser/storage.ts]: What happens in the Chromium-based Edge?

File: browser/src/browser/storage.ts [hunk 2]
```diff
@@ -1,33 +1,52 @@
...
+        return of(undefined)
+    }
+    return concat(
         // Start with current value of the item
-        from(storage[areaName].get(key)).pipe(map(items => items[key])),
+        from((storage[areaName] as browser.storage.StorageArea<ExtensionStorageItems[A]>).get(key)).pipe(
```
Comment (felixfbecker) [inline browser/src/browser/storage.ts]: Why is this cast needed? Shouldn't the declaration of `storage` above define the type correctly?

File: browser/src/browser/storage.ts [hunk 3]
```diff
@@ -1,33 +1,52 @@
...
+        ),
         // Emit every new value from change events that affect that item
         fromBrowserEvent(storage.onChanged).pipe(
             filter(([, name]) => areaName === name),
             map(([changes]) => changes),
-            filter((changes): changes is { [k in K]: browser.storage.StorageChange<StorageItems[k]> } =>
-                Object.prototype.hasOwnProperty.call(changes, key)
-            ),
+            filter((changes): changes is {
+                [K in keyof ExtensionStorageItems[A]]: browser.storage.StorageChange<ExtensionStorageItems[A][K]>
```
Comment (felixfbecker) [inline browser/src/browser/storage.ts]: This function only checks if `key` exists as a key, but according to the new signature it checks that all keys of the storage area exist. That doesn't seem right

Comment (lguychard) [reply browser/src/browser/storage.ts]: You're right, fixed.

File: browser/src/browser/storage.ts (hunk 2 above)
Comment (lguychard) [reply browser/src/browser/storage.ts]: Without this cast:

```typescript
({
    sync: browser.storage.StorageArea<SyncStorageItems>;
    local: browser.storage.StorageArea<LocalStorageItems>;
    managed: browser.storage.StorageArea<ManagedStorageItems>;
} & {
    onChanged: browser.CallbackEventEmitter<(changes: browser.storage.ChangeDict<SyncStorageItems> | browser.storage.ChangeDict<LocalStorageItems> | browser.storage.ChangeDict<ManagedStorageItems>, areaName: browser.storage.AreaName) => void>;
})[A]
```
- `storage[areaName].get()` gets (correctly) inferred as:
```typescript
get(): Promise<Partial<SyncStorageItems>> | Promise<Partial<LocalStorageItems>> | Promise<Partial<ManagedStorageItems>>
```
- Note that this overload accepts no argument, since `keyof  Partial<LocalStorageItems> | Partial<SyncStorageItems> | Partial<ManagedStorageItems>` is `never`.
- As a result, `storage[areaName].get(key)` doesn't compile: `Expected 0 arguments, but got 1.`
- With the cast, `storage[areaName].get()` is inferred as:

```typescript
get<K>(keys: K | K[]): Promise<{ [k in K]?: ExtensionStorageItems[A][k] | undefined; }> (+1 overload)
```

I wrestled with this a little bit, and eventually decided that the cast was an acceptable solution.

File: browser/src/browser/storage.ts (hunk 1 above)
Comment (lguychard) [reply browser/src/browser/storage.ts]: No issues (eg accessing `storage.managed.get()` returns a Promise that resolves to `undefined`).

**Comment by lguychard** [comment]
@felixfbecker this would close https://github.com/sourcegraph/sourcegraph/issues/3604.
