### PR TITLE
Ensure to incorporate all changesets in burndown chart

### LINKED ISSUE #10802: Burndown chart is off
- **Sourcegraph version:** master
- **Platform information:** macOS 10.15.4, Chrome 81

#### Steps to reproduce:

1. Sadly don't really know. I have a campaign with quite a few published changesets.

#### Expected behavior:
The count of changesets is equal to the count of changesets shown in the burndown chart.

#### Actual behavior:
It almost feels like 50 is a query limit interally? 
image

### PR DESCRIPTION
**Pull request by eseliger**
Closes #10802

### CODE REVIEW

File: enterprise/internal/campaigns/resolvers/campaigns.go [hunk 1]
```diff
@@ -214,7 +214,7 @@ func (r *campaignResolver) ChangesetCountsOverTime(
 
 	resolvers := []graphqlbackend.ChangesetCountsResolver{}
 
-	opts := ee.ListChangesetsOpts{CampaignID: r.Campaign.ID}
+	opts := ee.ListChangesetsOpts{CampaignID: r.Campaign.ID, Limit: -1}
```
Comment (mrnugget) [inline enterprise/internal/campaigns/resolvers/campaigns.go:217]: 🤦

Comment (ryanslade) [reply enterprise/internal/campaigns/resolvers/campaigns.go:217]: I was just staring at this code for ages, wondering how it could possibly work if limit is -1 since you can't set a negative cap on a slice:
https://github.com/sourcegraph/sourcegraph/blob/60d51e2e3f1f90094cebc38ca0af822a6c7b0bf5/enterprise/internal/campaigns/store.go#L670-L673

But then I remembered that we mutate opts.Limit inside the query above
