### PR TITLE
server: Redis persistence optimizations

### LINKED ISSUE #3300: Redis AOF file grows unbounded due to frequent container restarts
_Issue description written by @tsenart and copied here from another private issue._

### Background

$CUSTOMER had a P0 incident due to the Redis AOF file not getting compacted as it should. It seems that the reason this happened is due to frequent container restarts.

The default Redis configuration for when the AOF file should get compacted is:

```
# Automatic rewrite of the append only file.
# Redis is able to automatically rewrite the log file implicitly calling
# BGREWRITEAOF when the AOF log size grows by the specified percentage.
#
# This is how it works: Redis remembers the size of the AOF file after the
# latest rewrite (if no rewrite has happened since the restart, the size of
# the AOF at startup is used).
#
# This base size is compared to the current size. If the current size is
# bigger than the specified percentage, the rewrite is triggered. Also
# you need to specify a minimal size for the AOF file to be rewritten, this
# is useful to avoid rewriting the AOF file even if the percentage increase
# is reached but it is still pretty small.
#
# Specify a percentage of zero in order to disable the automatic AOF
# rewrite feature.

auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
```

In particular, `if no rewrite has happened since the restart, the size of the AOF at startup is used` is of particular concern and would explain what we're seeing. If the Docker container restarts frequently enough, redis won't have the chance to reach 100% of the previous AOF base size, so the next time around it starts up, it takes the AOF file size *at that point* as the new base over which it needs to double again. This can go ad-nauseum, theoretically.

### Remediation

$CUSTOMER is setting up monitoring of disk space usage and has a working playbook for manually triggering AOF file compaction.

### Resolution

As far as I understand it, this seems like a design issue in Redis and it should only affect our Docker image deployment because of all the restarts that other processes can trigger.

#### Action Items:

1. [ ] **Create a work-around on our side**: Instead of relying on automatic background compaction, we can trigger it every-time after redis comes up. This can be done via the sourcegraph-frontend, or through a redis run script in `sourcegraph/server`.

3. [ ] Open an issue (or find one) in Redis upstream.
2. [ ] Figure out why the Docker container is restarting so often. See Relevant Logs section for a possible hint.

### Incident Log
https://sourcegraph.slack.com/archives/GDS3PJ8GK/p1554732996001200

### Relevant Logs

[Similarly to what $CUSTOMER is seeing](https://console.cloud.google.com/logs/viewer?authuser=1&organizationId=1006954638239&project=sourcegraph-dev&resource=container%2Fcluster_name%2Fdogfood%2Fnamespace_id%2Fdefault&minLogLevel=0&expandAll=false&timestamp=2019-04-08T17%3A13%3A40.800000000Z&customFacets&limitCustomFacetWidth=true&interval=NO_LIMIT&scrollTimestamp=2019-03-23T07%3A17%3A40.000000000Z&pinnedLogId=jzf1w8f880bcc&pinnedLogTimestamp=2019-03-23T07%3A17%3A03Z&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22dogfood%22%0Aresource.labels.container_name%3D%22sourcegraph-server%22%0Aresource.labels.namespace_id%3D%22default%22%0Aresource.labels.instance_id%3D%22355508537060902802%22%0Aresource.labels.zone%3D%22us-central1-a%22%0Aresource.labels.project_id%3D%22sourcegraph-dev%22%0Atimestamp%3E%3D%222019-03-23T07%3A13%3A00.000000000Z%22), our Dogfood docker deployment has seen occurrences where the container crashes for no apparent reason, followed by Redis errors on startup.

### PR DESCRIPTION
**Pull request by tsenart**
This PR introduces Redis persistence optimizations that address long `server` start up times that customers were experiencing.

Please review commit by commit.

Fixes #3300 and #2904

### CODE REVIEW

**Comment by tsenart** [comment]
@unknwon: Since I was working on Redis issues, I took a stab at this even though it was in your planned work.

File: internal/redispool/sysreq.go [hunk 1]
```diff
@@ -23,9 +23,16 @@ func redisCheck(name, addr string, timeout time.Duration, pool *redis.Pool) sysr
...
 		for time.Now().Before(deadline) {
+			// Instead of just a PING, we also use this hook point to force a rewrite of
+			// the AOF file on startup of the frontend as a way to ensure it doesn't
+			// grow out of bounds which slows down future startups.
+			// See https://github.com/sourcegraph/sourcegraph/issues/3300 for more context
 			c := pool.Get()
-			_, err = c.Do("PING")
-			c.Close()
+			c.Send("PING")
+			c.Send("BGREWRITEAOF")
```
Comment (unknwon) [inline internal/redispool/sysreq.go]: https://buildkite.com/sourcegraph/sourcegraph/builds/54900#c30c1d98-3723-49c3-a6fb-76ef8a0e32b6/870-873

**Comment by unknwon** [comment]
Looks like we have flaky in DB back-compatibly check script, retry worked.

**Comment by keegancsmith** [comment]
> Looks like we have flaky in DB back-compatibly check script, retry worked.

this has been fixed in master I believe by #8120

File: internal/redispool/sysreq.go [hunk 2]
```diff
@@ -20,14 +20,36 @@ func init() {
...
-			_, err = c.Do("PING")
-			c.Close()
+			defer func() { _ = c.Close() }()
+
+			if err = c.Send("PING"); err != nil {
+				return err
+			}
 
-			if err == nil {
+			if err = c.Send("BGREWRITEAOF"); err != nil {
```
Comment (keegancsmith) [inline internal/redispool/sysreq.go]: can we do this in a background goroutine rather? No need to prevent the starting of sourcegraph on this command. Maybe move it to to after we reach success on line 53 below, rather than mixing it in with the "check" logic. I see you document it as async, but still think it would be clearer to not mix it up in the check function.

**Comment by keegancsmith** [comment]
Some questions:
- Should we trigger this rewrite in the background periodically?
- Are there any unexpected repercussions for installations on there own hosted redis?
- What should we do if the command fails? Right now we fail startup, but we should probably log an error message?

**Comment by unknwon** [comment]
> * Should we trigger this rewrite in the background periodically?

According to https://redis.io/commands/bgrewriteaof, Redis is already doing this automatically:

>Since Redis 2.4 the AOF rewrite is automatically triggered by Redis, however the BGREWRITEAOF command can be used to trigger a rewrite at any time.
>...
>The rewrite will be only triggered by Redis if there is not already a background process doing persistence.

So aggressively trigger this in the background periodically seems fine other than possible I/O cost.

---

> * What should we do if the command fails? Right now we fail startup, but we should probably log an error message?

I think log an error message might be better? We could get an error because Redis is already doing it:

> _https://redis.io/commands/bgrewriteaof_
>If an AOF rewrite is already in progress the command returns an error and no AOF rewrite will be scheduled for a later time.
If the AOF rewrite could start, but the attempt at starting it fails (for instance because of an error in creating the child process), an error is returned to the caller.

File: internal/redispool/sysreq.go (hunk 2 above)
Comment (tsenart) [reply internal/redispool/sysreq.go]: > No need to prevent the starting of sourcegraph on this command

The error here is not from the execution of the command, but rather only an error that may happen when writing to the in-memory buffer, or a previous error that happened in the connection. We explicitly ignore any error or result from this command, because never call `Receive` for it (as written in a comment).

Given that, would you still want this changed?

**Comment by tsenart** [comment]
> Should we trigger this rewrite in the background periodically?

Redis already does that when there aren't frequent restarts which is the case this PR addresses.

> Are there any unexpected repercussions for installations on there own hosted redis?

After thinking about this further, I'm concerned with the potential I/O impact of running `BGREWRITEAOF` on every restart when restarts are frequent. Not that this would block Sourcegraph from coming up, but it could create unintended contention with other processes (i.e. like `zoekt-index-server`, `git-server`, `postgres`).

But, while re-searching this further, I discovered that there's a promising new setting `aof-use-rdb-preamble yes` that uses the RDB snapshot as the preamble for the AOF file, which ought to massively speed-up both the process of `BGREWRITEAOF` and of starting Redis up.

- https://github.com/antirez/redis-doc/issues/908
- https://github.com/antirez/redis/commit/28d28ef3cf0fbbc1cf1caf379ed3ae2af0ac6c27

With that, there'd be additional work to be done here:

- Upgrading our shipped version of Redis in all environments
- Document that version as the minimum supported version
- Write migration documentation for customers (if necessary)

File: internal/redispool/sysreq.go (hunk 2 above)
Comment (keegancsmith) [reply internal/redispool/sysreq.go]: so will it block at all? If not it should be fine.

**Comment by keegancsmith** [comment]
Taking a step back: We don't have that much data in `redis-store`, and everything in `redis-cache` is ephemeral. Maybe we don't do any disk writes/reads for `redis-cache`, only for `redis-store`. That should also resolve this?

Note: before repo-updater syncer we heavily relied on `redis-cache` to reduce requests to codehosts. But I think that isn't as important now? (Maybe there are some auth ramifications from making redis-cache volatile?)

**Comment by unknwon** [comment]
Can't believe GitHub starts spamming almost everyone when there is a conflict with base branch :\

File: internal/redispool/sysreq.go (hunk 2 above)
Comment (tsenart) [reply internal/redispool/sysreq.go]: It will not block.

File: cmd/server/shared/assets/redis-cache.conf.tmpl [hunk 3]
```diff
@@ -7,10 +7,8 @@ protected-mode no
 maxmemory 1gb
 maxmemory-policy allkeys-lru
 
-# live commit log to disk, additionally snapshots every 10 minutes
-dir {{ .Dir }}
-appendonly yes
-save 600 1
+# redis-cache is ephemeral
+appendonly no
```
Comment (keegancsmith) [inline cmd/server/shared/assets/redis-cache.conf.tmpl]: do we update the redis conf? If I am not mistaken we will only do that if the file doesn't already exist. Is there maybe some heuristic we can do to update the config / know we can overwrite it.

File: internal/redispool/sysreq.go (hunk 2 above)
Comment (keegancsmith) [reply internal/redispool/sysreq.go]: do we still need this now with the other changes made?

File: cmd/server/shared/assets/redis-cache.conf.tmpl (hunk 3 above)
Comment (tsenart) [reply cmd/server/shared/assets/redis-cache.conf.tmpl]: Ah, good to know, thanks! I don't think we support externally mounted Redis configs, so this would be a matter of checking a sha256sum of the files?

File: internal/redispool/sysreq.go (hunk 2 above)
Comment (tsenart) [reply internal/redispool/sysreq.go]: Yes, because server still has frequent restarts and that means the BGREWRITEAOF operation isn't triggered enough. With the new setting, that'd mean we'd never actually write the RDB preamble, so it'd have no effect otherwise.

**Comment by tsenart** [comment]
@keegancsmith: I will follow up with version changes in other deployments and CI, although they aren't strictly necessary. Can you please take a look at my last commits which address your feedback?

**Comment by tsenart** [comment]
@keegancsmith, @sourcegraph/distribution: I opened PRs in our infrastructure repo as well as deploy-sourcegraph. Are there any other places we need changes?

File: cmd/server/shared/assets/redis-cache.conf.tmpl (hunk 3 above)
Comment (keegancsmith) [reply cmd/server/shared/assets/redis-cache.conf.tmpl]: The redis config is on the data volume, so is external. Yeah sha256sum sounds good to me.

File: CHANGELOG.md [hunk 4]
```diff
@@ -22,6 +22,7 @@ All notable changes to Sourcegraph are documented in this file.
 
 - experimentalFeatures.splitSearchModes was removed as a site configuration option. It should be set in global/org/user settings.
 - Sourcegraph now waits for `90s` instead of `5s` for Redis to be available before quitting. This duration is configurable with the new `SRC_REDIS_WAIT_FOR` environment variable.
+- The Sourcegraph Docker image optimized its use of Redis to make start-up significantly faster in certain scenarios (e.g when container restarts were frequent).
```
Comment (keegancsmith) [inline CHANGELOG.md]: link to issue?

File: cmd/server/shared/assets/redis-cache.conf.tmpl (hunk 3 above)
Comment (tsenart) [reply cmd/server/shared/assets/redis-cache.conf.tmpl]: It's external, but we don't document or ask admins to customize this file. So I don't think we need to check anything? What would the shasum give us? Right now we always over-write.

Comment (keegancsmith) [reply cmd/server/shared/assets/redis-cache.conf.tmpl]: oh we always overwrite? Sorry I was mistaken. Safe to continue always overwriting then.

Comment (tsenart) [reply cmd/server/shared/assets/redis-cache.conf.tmpl]: > oh we always overwrite? Sorry I was mistaken. Safe to continue always overwriting then.

I changed it to always overwrite, but it wasn't so before.

**Comment by tsenart** [comment]
I'll be monitoring sourcegraph.sgdev.org after it gets deployed the new insiders build to be triple sure nothing broke.
