### PR TITLE
globals: Keep ExternalURL up to date

### LINKED ISSUE #4056: Cannot use Google GSuite OIDC auth
- **Sourcegraph version:** Docker image 3.4.0-rc.2
- **Platform information:** 

#### Steps to reproduce:

1. Spin up a Sourcegraph cluster following the docs on deploying to Google Cloud VM following https://docs.sourcegraph.com/admin/install/docker/google_cloud.
2. Set an external URL for your instance
3. Access the management console and set up Google OIDC auth following https://docs.sourcegraph.com/admin/auth#g-suite-google-accounts
4. Go back to your instance, and sign out. You'll see this error page
image

5. Following the URL takes you back to your OAuth credential, and see that it had the correct redirect URL:
image

#### Expected behavior:

- Can log out properly.

#### Actual behavior:

- Failed log out.

### PR DESCRIPTION
**Pull request by tsenart**
This commit makes the globals package keep up to date with changes to
the configured ExternalURL in the management console (critical config).

Before this change, updates to the external URL were not reflected in
many places in the app before it got restarted.

Fixes #4056

Test plan: Reproduction steps in #4056

### CODE REVIEW

File: cmd/frontend/globals/globals.go [hunk 1]
```diff
@@ -3,12 +3,64 @@ package globals
...
 
 	"github.com/sourcegraph/sourcegraph/pkg/conf"
+	"gopkg.in/inconshreveable/log15.v2"
 )
 
-// ExternalURL is the fully-resolved, externally accessible frontend URL.
-var ExternalURL = &url.URL{Scheme: "http", Host: "example.com"}
+var (
+	externalURLWatch sync.Once
+	externalURLMutex sync.RWMutex
```
Comment (keegancsmith) [inline cmd/frontend/globals/globals.go]: nit: personally I find these sort of usecases much clearer to use an `atomic.Value`. Less code and faster.

File: cmd/frontend/globals/globals.go [hunk 2]
```diff
@@ -3,12 +3,64 @@ package globals
...
+
+			before := *externalURL
+			if !reflect.DeepEqual(&before, after) {
+				externalURL = after
+				log15.Info(
+					"globals.ExternalURL",
+					"updated", true,
+					"before", &before,
+					"after", after,
+				)
```
Comment (keegancsmith) [inline cmd/frontend/globals/globals.go]: this will be a bit of logspam on startup since it will always change from the example URL.

File: cmd/frontend/globals/globals.go [hunk 3]
```diff
@@ -3,12 +3,64 @@ package globals
...
+)
+
+// WatchExternalURL watches for changes in the ExternalURL critical config
+// so that changes are reflected in what is returned by the ExternalURL function.
+// In case the setting is not set, defaultURL is used.
+func WatchExternalURL(defaultURL *url.URL) {
+	externalURLWatch.Do(func() {
+		conf.Watch(func() {
+			after := defaultURL
+			if val := conf.Get().Critical.ExternalURL; val != "" {
```
Comment (keegancsmith) [inline cmd/frontend/globals/globals.go]: should we look into a stricter schema for externalURL than string? Either way that should be a separate PR since its probably riskier.

File: cmd/frontend/globals/globals.go [hunk 4]
```diff
@@ -3,12 +3,64 @@ package globals
...
+// ExternalURL returns the fully-resolved, externally accessible frontend URL.
+func ExternalURL() *url.URL {
+	externalURLMutex.RLock()
+	defer externalURLMutex.RUnlock()
+
+	u := *externalURL
+	if u.User != nil {
+		user := *(u.User)
+		u.User = &user
+	}
```
Comment (keegancsmith) [inline cmd/frontend/globals/globals.go]: you don't need to copy User, it is immutable (all fields private, no methods that mutate)

**Comment by tsenart** [comment]
> So the feature worked if you restarted your container (or frontend pod)?

Yep!

File: cmd/frontend/registry/extensions.go [hunk 5]
```diff
@@ -126,7 +126,7 @@ func GetExtensionByExtensionID(ctx context.Context, extensionID string) (local g
 func getLocalRegistryName() string {
 	u, err := url.Parse(conf.Get().Critical.ExternalURL)
 	if err != nil || u == nil || u.Host == "" {
-		return registry.Name(globals.ExternalURL)
+		return registry.Name(globals.ExternalURL())
```
[the remark this answers is not in the document]
Comment (tsenart) [reply cmd/frontend/registry/extensions.go]: Good catch. All of these was just an automated refactoring. Thanks for the deeper review.

File: cmd/frontend/globals/globals.go [hunk 6]
```diff
@@ -3,12 +3,64 @@ package globals
...
+	"sync"
 
 	"github.com/sourcegraph/sourcegraph/pkg/conf"
+	"gopkg.in/inconshreveable/log15.v2"
 )
 
-// ExternalURL is the fully-resolved, externally accessible frontend URL.
-var ExternalURL = &url.URL{Scheme: "http", Host: "example.com"}
+var (
+	externalURLWatch sync.Once
```
[the remark this answers is not in the document]
Comment (tsenart) [reply cmd/frontend/globals/globals.go]: > Additionally I'd suspect calling it more than once is a logic bug.

Yeah, this is why I added the `sync.Once`. But I think a panic makes more sense indeed.

File: cmd/frontend/globals/globals.go (hunk 3 above)
Comment (tsenart) [reply cmd/frontend/globals/globals.go]: Yeah, I'd do that in a follow up PR.

File: cmd/frontend/globals/globals.go (hunk 4 above)
Comment (tsenart) [reply cmd/frontend/globals/globals.go]: Nice, thanks.

**Comment by tsenart** [comment]
@keegancsmith: Addressed your comments. Please take another look!

File: cmd/frontend/internal/session/session.go [hunk 7]
```diff
@@ -63,16 +63,48 @@ func SetSessionStore(s sessions.Store) {
 	sessionStore = s
 }
 
+// sessionsStore wraps another sessions.Store to dynamically set the value
+// of a session.Options.Secure field to what is returned by the secure
+// closure at invocation time.
```
Comment (keegancsmith) [inline cmd/frontend/internal/session/session.go]: neat

File: cmd/frontend/globals/globals.go [hunk 8]
```diff
@@ -3,12 +3,64 @@ package globals
...
+	})
+}
+
+// ExternalURL returns the fully-resolved, externally accessible frontend URL.
+// Callers must not mutate the returned pointer.
+func ExternalURL() *url.URL {
+	return externalURL.Load().(*url.URL)
+}
+
+// SetExternalURL sets the fully-resolved, externally accessible frontend URL.
```
Comment (slimsag) [inline cmd/frontend/globals/globals.go]: You may want to document that this should only be called externally in tests
