### PR TITLE
graphqlbackend: Optimize repo query for lang suggestions

### LINKED ISSUE #6760: Search auto-suggestions are very slow on sourcegraph.com
Selection_058

Repro:
* Go to https://sourcegraph.com/github.com/sourcegraph/sourcegraph@master/-/blob/web/src/regression/search.test.ts
* Type `repo:^github\.com/sourcegraph/sourcegraph$@master src/regression/search.test.ts` into the search query box
* Observe the loading indicator hanging for a long time

Let me know if the fix for this should go out in the 3.10.1 patch release.

### PR DESCRIPTION
**Pull request by tsenart**
This commit optimizes the SQL query used to find a repo for language
suggestions.

- It removes everything from the last `@` in the repo name,
since it prevented Postgres from using its trigram index on the name column
of the repo table.
- It changes the operator we use to perform regex matching on the name
column from `~*` (case insenstive) to `~` case senstive.

Fixes #6760

### CODE REVIEW

**Comment by tsenart** [comment]
This is incomplete. We need to change the comparison operator to `~` instead of `~*`, as per @mrnugget's findings.

**Comment by tsenart** [comment]
For context, these findings by @mrnugget is what has driven these changes:

```
 -- original
EXPLAIN ANALYZE SELECT id,name,external_id,external_service_type,external_service_id FROM repo
WHERE deleted_at IS NULL AND enabled = true AND deleted_at IS NULL AND
lower(name) ~* '^github\.com/sourcegraph/sourcegraph$@master' AND enabled ORDER BY id ASC LIMIT 1 OFFSET 0;

-- with ~ instead of ~*
EXPLAIN ANALYZE SELECT id,name,external_id,external_service_type,external_service_id FROM repo
WHERE deleted_at IS NULL AND enabled = true AND deleted_at IS NULL AND
lower(name) ~ '^github\.com/sourcegraph/sourcegraph$@master' AND enabled ORDER BY id ASC LIMIT 1 OFFSET 0;
-- > 10s
-- in addition: without `@master`
EXPLAIN ANALYZE SELECT id,name,external_id,external_service_type,external_service_id FROM repo
WHERE deleted_at IS NULL AND enabled = true AND deleted_at IS NULL AND
lower(name) ~ '^github\.com/sourcegraph/sourcegraph$' AND enabled ORDER BY id ASC LIMIT 1 OFFSET 0;
-- > Execution Time: 1666.472 ms

-- same query with nonexisting repo:
EXPLAIN ANALYZE SELECT id,name,external_id,external_service_type,external_service_id FROM repo
WHERE deleted_at IS NULL AND enabled = true AND deleted_at IS NULL AND
lower(name) ~ '^github\.com/foobar/barfoo$' AND enabled ORDER BY id ASC LIMIT 1 OFFSET 0;
-- > 1.5s
```

File: cmd/frontend/db/repos.go [hunk 1]
```diff
@@ -367,7 +367,7 @@ func parsePattern(p string) ([]*sqlf.Query, error) {
 		conds = append(conds, sqlf.Sprintf("(%s)", sqlf.Join(likeConds, " OR ")))
 	}
 	if pattern != "" {
-		conds = append(conds, sqlf.Sprintf("lower(name) ~* %s", pattern))
+		conds = append(conds, sqlf.Sprintf("lower(name) ~ %s", pattern))
```
Comment (mrnugget) [inline cmd/frontend/db/repos.go]: I think we also need to lowercase the pattern, since we're switching from `~*` (case insensitive) to `~` (case sensitive)

Comment (tsenart) [reply cmd/frontend/db/repos.go]: You're right. Will push a fix.

**Comment by nicksnyder** [comment]
Performance improvement worth mentioning in the changelog?

**Comment by tsenart** [comment]
> Performance improvement worth mentioning in the changelog?

Too late, sorry!
