### PR TITLE
Batches: fix accessibility issues

### LINKED ISSUE #34669: [Accessibility]: Batches: Batch change label isn't descriptive
### Audit type

Screen reader navigation

### User journey audit issue

https://github.com/sourcegraph/sourcegraph/issues/34069

### Problem description

When navigating through the list of batch changes, the label indicating the status of the batch change isn't descriptive.
It currently reads `DRAFT` / `OPEN` e.t.c

Screenshot 2022-04-28 at 21 30 33

### Expected behavior

The status text should read `Draft Batch Change` or whatever status the batch change is in.

### Additional details

_No response_

### Assigning labels

- [X] Please give this issue an estimate by applying a label like `estimate/Xd`, where X is the estimated number of days it will take to complete.
- [X] If this issue is specific to a specific Sourcegraph product, please assign the appropriate team label to this issue.
- [X] If this issue will require input from designers in order to complete, please assign the label `needs-design`.
- [X] If you are confident that this issue should be fixed by GitStart, please assign the label `gitstart`.

### Owner

This issue will be fixed by my team, I have assigned a relevant member to it, or I will do so in the near future.

### PR DESCRIPTION
**Pull request by BolajiOlajide**
## Test plan

Tested with screen reader to make sure the page is now more accessible.

Closes #34669, #34666

## App preview:

- [Web](https://sg-web-bo-fix-accessibility-issues.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-klwluksenr.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

File: client/web/src/enterprise/batches/list/BatchChangeListPage.tsx [hunk 1]
```diff
@@ -168,10 +168,7 @@ export const BatchChangeListPage: React.FunctionComponent<BatchChangeListPagePro
                             />
                         </div>
                         {error && <ConnectionError errors={[error.message]} />}
-                        <ConnectionList
-                            as="div"
-                            className={classNames(styles.grid, isExecutionEnabled ? styles.wide : styles.narrow)}
-                        >
+                        <ConnectionList as="ul">
```
Comment (courier-new) [inline client/web/src/enterprise/batches/list/BatchChangeListPage.tsx:171]: Ugh, amazing, why was this *ever* a `<div />`!! 😂

File: client/web/src/enterprise/batches/list/BatchChangeNode.tsx [hunk 2]
```diff
@@ -164,19 +164,34 @@ export const BatchChangeNode: React.FunctionComponent<BatchChangeNodeProps> = ({
             {node.state !== BatchChangeState.DRAFT && (
                 <>
                     <ChangesetStatusOpen
+                        aria-label={`${node.changesetsStats.open} open changesets`}
                         className="d-block d-sm-flex"
-                        label={<span className="text-muted">{node.changesetsStats.open} open</span>}
+                        label={
+                            <span className="text-muted" aria-hidden="true">{`${node.changesetsStats.open} open`}</span>
+                        }
```
Comment (courier-new) [inline client/web/src/enterprise/batches/list/BatchChangeNode.tsx:171]: It's a bit rough here that we kinda have to duplicate the label text with slightly different wording for `aria` and hide the real one. I'm wondering if we ought to encapsulate all of these changesets stats in a `<div role="region" />` and `aria-label` that as "Changeset stats" instead. It makes it a bit more fluid to navigate, allows us to drop "changesets" from the screen-read labels, and in turn allows us to then use `aria-labelledby` for each specific status KPIs with the actual DOM labels, instead of kinda duplicating them:

```tsx
<div role="region" aria-label="Changeset stats">
    <ChangesetStatusOpen
        aria-labelledby="changesets-open-label"
        className="d-block d-sm-flex"
        label={
            <span className="text-muted" id="changesets-open-label">{`${node.changesetsStats.open} open`}</span>
        }
    />
```

(Disclaimer: haven't actually tested that code, just a suggestion 😅)

File: client/web/src/batches/icons.tsx [hunk 3]
```diff
@@ -35,6 +35,8 @@ const BaseBatchChangesIcon: BaseIcon = React.memo(function BaseBatchChangesIcon(
             viewBox={viewBox}
             {...props}
             xmlns="http://www.w3.org/2000/svg"
+            // this icon is used in a decorative manner, and as such should be hidden from screen readers
+            aria-hidden={true}
```
Comment (courier-new) [inline client/web/src/batches/icons.tsx:39]: ❤️

**Review by courier-new — APPROVED** [review]
Looks great!! Made 1 suggestion for a potentially different take on screen-reading the changeset stats, otherwise 🚢!!

**Comment by courier-new** [comment]
Oh one other comment, I just noticed on the Storybook story and UI review check on Chromatic, it looks like the connection list gained some extra top padding that we might not want:

image

File: client/web/src/enterprise/batches/list/BatchChangeListPage.tsx (hunk 1 above)
Comment (eseliger) [reply client/web/src/enterprise/batches/list/BatchChangeListPage.tsx:171]: because a `<ul>` doesn't support css grid 😬 Now the grid lives on the line items, which behaves like flex containers, but not the initial grid anymore:

On this branch:
CleanShot 2022-05-03 at 12 14 53@2x

On main:
CleanShot 2022-05-03 at 12 18 48@2x

File: client/web/src/enterprise/batches/list/BatchChangeNode.tsx (hunk 2 above)
Comment (eseliger) [reply client/web/src/enterprise/batches/list/BatchChangeNode.tsx:171]: since this is a list node, the ID would not be unique, but otherwise this could work :)

File: client/web/src/enterprise/batches/list/BatchChangeListPage.tsx [hunk 4]
```diff
@@ -153,8 +153,8 @@ export const BatchChangeListPage: React.FunctionComponent<BatchChangeListPagePro
                     <ConnectionContainer>
                         <div className={styles.filtersRow}>
                             {(licenseAndUsageInfo?.allBatchChanges.totalCount || 0) > 0 && (
-                                <H3 as={H2} className="align-self-end flex-1">
-                                    {lastTotalCount} batch changes
+                                <H3 as={H2} className="align-self-end flex-1" aria-live="assertive" aria-atomic="true">
```
Comment (eseliger) [inline client/web/src/enterprise/batches/list/BatchChangeListPage.tsx:156]: Are you sure we want to be assertive here? What's our bar to set that property 🤔

File: client/web/src/enterprise/batches/list/BatchChangeStatePill.tsx [hunk 5]
```diff
@@ -72,20 +73,20 @@ const StatePill: React.FunctionComponent<Pick<BatchChangeStatePillProps, 'state'
     switch (state) {
         case BatchChangeState.OPEN:
             return (
-                <Badge variant="success" className={styles.statePill}>
+                <Badge variant="success" className={styles.statePill} aria-hidden={true}>
```
Comment (eseliger) [inline client/web/src/enterprise/batches/list/BatchChangeStatePill.tsx:76]: Do we want this to be hidden? It's the only indicator we got for the open/closed/draft status.

**Review by eseliger — CHANGES_REQUESTED** [review]
This breaks the grid, so requesting changes. Added two more small inline comments but those aren't as critical to me.

File: client/web/src/enterprise/batches/list/BatchChangeListPage.tsx (hunk 1 above)
Comment (courier-new) [reply client/web/src/enterprise/batches/list/BatchChangeListPage.tsx:171]: NOOOOO darn it CSS grid. 😭

File: client/web/src/enterprise/batches/list/BatchChangeListPage.tsx (hunk 4 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/list/BatchChangeListPage.tsx:156]: Oh! That's an artifact I should've removed - i was testing something and I forgot to remove that. Ideally, we want it to be `polite` instead of it being `assertive`, however it doesn't work either way because the components from the design system don't forward HTML props so that never gets forwarded. 

I'll need to refactor for this to work. Thanks

File: client/web/src/enterprise/batches/list/BatchChangeListPage.tsx (hunk 1 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/list/BatchChangeListPage.tsx:171]: Unfortunately, Erik is right lol. Struggled with that part a bit and I should have added a comment about why that regression might exist.

Another option (a bit hacky sort of) is to set a fixed width on the individual changeset icon + text. Haven't tried that but I'll see how much of that gets fixed.

Comment (eseliger) [reply client/web/src/enterprise/batches/list/BatchChangeListPage.tsx:171]: why do we need to switch away from css-grid here? we use that pattern in quite a few places :(

Comment (eseliger) [reply client/web/src/enterprise/batches/list/BatchChangeListPage.tsx:171]: oh lord, in that case I think we should table it and look for a general working solution first. This pattern is adopted across multiple pages and lists.. It feels like it's a non-trivial effort to get it to work again somewhat similarly.

File: client/web/src/enterprise/batches/list/BatchChangeListPage.tsx (hunk 4 above)
Comment (courier-new) [reply client/web/src/enterprise/batches/list/BatchChangeListPage.tsx:156]: Ah! If you need another way to announce the total count change, FPT also recently introduced the super lightweight [`screenReaderAnnounce`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/wildcard/src/utils/screenReaderAnnounce.ts?L10%3A45=), which you could potentially use instead.

File: client/web/src/enterprise/batches/list/BatchChangeStatePill.tsx (hunk 5 above)
Comment (courier-new) [reply client/web/src/enterprise/batches/list/BatchChangeStatePill.tsx:76]: I think it's okay since Bolaji put an `aria-label` on the parent up at line 64, instead.

File: client/web/src/enterprise/batches/list/BatchChangeNode.tsx (hunk 2 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/list/BatchChangeNode.tsx:171]: Yes this works. Made some minor change to Kelli's suggestion but it works. :)

File: client/web/src/enterprise/batches/list/BatchChangeListPage.tsx (hunk 1 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/list/BatchChangeListPage.tsx:171]: What's the best way to get this sorted? @eseliger @courier-new 

I've done a bit of digging today and couldn't find a way around maintaining the grid and changing the pattern to fix this accessibility issue.

**Comment by BolajiOlajide** [comment]
> Oh one other comment, I just noticed on the Storybook story and UI review check on Chromatic, it looks like the connection list gained some extra top padding that we might not want:
> 
> image

Fixed.

File: client/web/src/enterprise/batches/list/BatchChangeListPage.tsx (hunk 1 above)
Comment (courier-new) [reply client/web/src/enterprise/batches/list/BatchChangeListPage.tsx:171]: We're likely not to be the only team displaying a `FilteredConnection` that needs to function as a grid. I think it's okay to revert this part of your PR and, if there isn't a dedicated issue already, file one specifically for supporting a grid layout in the `ConnectionList` component for FPT to own.

Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/list/BatchChangeListPage.tsx:171]: Got it. Thanks.

Comment (courier-new) [reply client/web/src/enterprise/batches/list/BatchChangeListPage.tsx:171]: (Bonus points if you throw in a comment by this line to explain why we can't use `ul` right now)

File: client/web/src/enterprise/batches/list/BatchChangeListPage.tsx (hunk 4 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/list/BatchChangeListPage.tsx]: Done

File: client/web/src/enterprise/batches/list/BatchChangeListPage.tsx (hunk 1 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/list/BatchChangeListPage.tsx]: I've created an issue for the `ConnectionList` [here](https://github.com/sourcegraph/sourcegraph/issues/35034)

@eseliger @courier-new Can you review this PR one last time? Thanks.

File: client/web/src/enterprise/batches/list/BatchChangeNode.module.scss [hunk 6]
```diff
@@ -39,9 +39,6 @@
         // Make it full width in the current row.
         grid-column: 1 / -1;
         border-top: 1px solid var(--border-color-2);
-        @media (--xs-breakpoint-down) {
-            margin-top: 1rem;
-            padding-bottom: 1rem;
-        }
```
Comment (eseliger) [inline client/web/src/enterprise/batches/list/BatchChangeNode.module.scss:45]: was this style not needed anymore?

**Review by eseliger — APPROVED** [review]

File: client/web/src/enterprise/batches/list/BatchChangeNode.module.scss (hunk 6 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/list/BatchChangeNode.module.scss]: Yes we do. It was part of the last group of commits I `un-did` and I forgot to push.
I just did now.

File: client/web/src/enterprise/batches/list/BatchChangeNode.tsx [hunk 7]
```diff
@@ -164,16 +164,37 @@ export const BatchChangeNode: React.FunctionComponent<React.PropsWithChildren<Ba
...
                 <>
                     <ChangesetStatusOpen
+                        aria-labelledby="changesets-open-label"
                         className="d-block d-sm-flex"
-                        label={<span className="text-muted">{node.changesetsStats.open} open</span>}
+                        label={
+                            <span
+                                className="text-muted"
+                                id="changesets-open-label"
+                                aria-hidden={true}
```
Comment (courier-new) [inline client/web/src/enterprise/batches/list/BatchChangeNode.tsx:173]: TIL `aria-labelledby` can still use content from an element that's `aria-hidden`. 😮  Just curious, does it read it off twice if you don't `aria-hide` it? I admit it was a bit unexpected to see this at first (wait, but the label is... hidden?), until I read the docs explaining that still works.

Comment (courier-new) [reply client/web/src/enterprise/batches/list/BatchChangeNode.tsx:173]: (Do you think it's worth including any comment here about the interaction between `aria-labelledby` and `aria-hidden`?)

**Review by courier-new — APPROVED** [review]
💯  Thanks for working through these Bolaji!! Just had one question of sorts.

File: client/web/src/enterprise/batches/list/BatchChangeNode.tsx (hunk 7 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/list/BatchChangeNode.tsx:173]: Yes. 
The screen readers reads the content twice if aria-hidden isn't true, i found that odd myself but I recently learnt it's because in the event there's more than one content in a group and only one acts a the description for the group then it makes sense that the screen reader doesn't automatically assume the other contents of the group shouldn't be read unless it's explicitly specified.

I'm out for dinner but I'll add a comment as soon as I'm back.

Comment (courier-new) [reply client/web/src/enterprise/batches/list/BatchChangeNode.tsx:173]: Got it! Thanks for explaining, Bolaji, that does seem reasonable. Good to know! 🙂

**Review by LawnGnome — APPROVED** [review]
Nice work!
