### PR TITLE
streaming search: fixing minor bugs related to progress count

### LINKED ISSUE #17561: Streaming search: "check your internet" message on long-running searches
On some long-running searches like [`foo bar count:10000 timeout:20s`](https://sourcegraph.com/search?q=foo+bar+count:10000+timeout:20s&patternType=regexp) I get an error state in the "Skipped" UI element, with the following message:

image

But my internet is working fine.

Inspecting the `stream` SSE request, it shows up as 200 with 4 events (matches, progress, matches, progress):

image
image

cc @limitedmage

### LINKED ISSUE #17562: Streaming search tells me it found many results but I see 30 at most, can't show more
For [`repo:^github\.com/sourcegraph/sourcegraph$ stream`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+stream&patternType=literal), the results indicator tells me 366 results were found:

image

Unfortunately, only 30 results are ever streamed to the frontend, and I am unable to display more results (no "show more" button, or infinite scrolling on additional results):

image

I have to specify a `count:` > 30 to get more than 30 matches streamed to the client, but this isn't made obvious to me anywhere in the UI. This feels like a bad experience.

cc @limitedmage @keegancsmith @stefanhengl

### PR DESCRIPTION
**Pull request by limitedmage**
- Remove count from bottom of search results (fixes #17562)
- Update closed connection error message (fixes #17561)
- Abbreviates result counts in the progress indicator (eg. `1234` becomes `1.2k+`; related to #17560)

image

### CODE REVIEW

**Review by rrhyne — APPROVED** [review]
LGTM!

File: client/web/src/search/results/streaming/progress/StreamingProgressCount.tsx [hunk 1]
```diff
@@ -4,6 +4,19 @@ import * as React from 'react'
...
+    }
+    if (number >= 1e3 && number < 1e6) {
+        return (number / 1e3).toFixed(1) + 'k+'
+    }
+    if (number >= 1e6 && number < 1e9) {
+        return (number / 1e6).toFixed(1) + 'm+'
+    }
+    return (number / 1e9).toFixed(1) + 'b+'
+}
+
```
Comment (lguychard) [inline client/web/src/search/results/streaming/progress/StreamingProgressCount.tsx:19]: I believe this would accomplish a similar outcome without having to do manual bounds-checking:

```suggestion
const abbreviateNumber = (number: number): string =>
    new Intl.NumberFormat('en-US', { notation: 'compact' }).format(number) + '+'
```

**Review by lguychard — APPROVED** [review]

File: client/web/src/search/results/streaming/progress/StreamingProgressCount.tsx (hunk 1 above)
Comment (limitedmage) [reply client/web/src/search/results/streaming/progress/StreamingProgressCount.tsx:19]: Unfortunately `notation: 'compact'` does not work in Safari :(

**Comment by rrhyne** [comment]
@limitedmage how often with the from n+ repositories text show? I was under the impression this was not going to be possible.

File: client/web/src/search/stream.ts [hunk 2]
```diff
@@ -439,11 +439,7 @@ const messageHandlers: {
                 // The EventSource API can return a DOM event that is not an Error object
                 // (e.g. doesn't have the message property), so we need to construct our own here.
                 // See https://developer.mozilla.org/en-US/docs/Web/API/EventSource/error_event
-                observer.error(
-                    new Error(
-                        'There was a network error retrieving search results. Check your Internet connection and try again.'
-                    )
-                )
+                observer.error(new Error('The connection was closed before the search was completed.'))
```
Comment (rrhyne) [inline client/web/src/search/stream.ts:442]:
```suggestion
                observer.error(new Error('The connection was closed before your search was completed. This may be due to a problem with a firewall, VPN or proxy, or a failure with the Sourcegraph server.'))
```

Comment (rrhyne) [reply client/web/src/search/stream.ts:442]: @limitedmage @lguychard I've updated this a bit to be more explicit on how to review the issue. Hopefully, it generically matches the uncertainty behind the issue well enough.

**Comment by limitedmage** [comment]
> @limitedmage how often with the from n+ repositories text show? I was under the impression this was not going to be possible.

I'm seeing this with streaming turned on. We know from which repos we have results from. The number that we don't know is how many repos we still have left to search. Example: https://sourcegraph.com/search?q=RouteHandler+timeout:20s+count:1000&patternType=literal
