### PR TITLE
In browser extension, make all GraphQL api requests from background page

### LINKED ISSUE #1945: User configured extensions do not work on private code host if using public Sourcegraph instance
Discovered this while screensharing with Bas from Codecov.

Steps to reproduce:
- Make sure you're logged in to sourcegraph.com, and your browser extension is pointing to sourcegraph.com
- Enable codecov extension in your sourcegraph.com account
- Visit a repo on a private code host (eg gitlab.sgdev.org, ghe.sgdev.org or `docker run -p 8000:80 gitlab/gitlab-ce`)
- Witness codecov extension is not activated

A further look will reveal that only default extensions IDs are returned, as if you were in a logged out state: 
image

This is normal: through the [corsOrigin](https://docs.sourcegraph.com/admin/site_config/all#corsorigin-string) setting, sourcegraph.com is set up to only accept requests from github.com, bitbucket.org and gitlab.com, and while the browser extension uses access tokens to bypass cors, it [doesn't do it for sourcegraph.com](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/shared/backend/headers.tsx#L29-).

While expected, this defeats the goal of being able to use extensions on private code even without a private Sourcegraph instance (in the way Codecov currently works on private Github repositories, for instance).

This limitation could potentially be overcome by making all requests from the background page of the extension.

### PR DESCRIPTION
**Pull request by lguychard**
Fixes #1945

Makes sure all GraphQL API requests are sent from the background page, so as to bypass CORS restrictions when running on private code hosts with the public Sourcegraph instance. This allows us to run extensions on private code hosts without needing a private Sourcegraph instance.

### CODE REVIEW

**Comment by lguychard** [comment]
- [ ] TODO: just fixed to make sure private repo check is done in the content script and not the background page, now needs DRYing

File: client/browser/src/shared/backend/graphql.tsx [hunk 1]
```diff
@@ -44,15 +45,65 @@ export function requestGraphQL<T extends GQL.IGraphQLResponseRoot>({
...
-}: GraphQLRequestArgs): Observable<T> {
-    const nameMatch = request.match(/^\s*(?:query|mutation)\s+(\w+)/)
-    const queryName = nameMatch ? '?' + nameMatch[1] : ''
+}: GraphQLRequestArgs) => {
+    // #1945: make sure all GraphQL API requests are sent
+    // from the background page, so as to bypass CORS restrictions
+    // when running on private code hosts with the public Sourcegraph instance.
+    // This allows us to run extensions on private code hosts without
+    // needing a private Sourcegraph instance.
+    if (isBackground) {
```
Comment (ijsnow) [inline client/browser/src/shared/backend/graphql.tsx]: `|| isInPage`

File: client/browser/src/shared/backend/graphql.tsx [hunk 2]
```diff
@@ -44,15 +45,65 @@ export function requestGraphQL<T extends GQL.IGraphQLResponseRoot>({
     useAccessToken = true,
     authError,
     requestMightContainPrivateInfo = true,
-}: GraphQLRequestArgs): Observable<T> {
-    const nameMatch = request.match(/^\s*(?:query|mutation)\s+(\w+)/)
-    const queryName = nameMatch ? '?' + nameMatch[1] : ''
+}: GraphQLRequestArgs) => {
+    // #1945: make sure all GraphQL API requests are sent
```
Comment (chrismwendt) [inline client/browser/src/shared/backend/graphql.tsx]: Personal preference: I'd expand this to a full link

**Comment by ijsnow** [comment]
> does this mean admins will not need to set corsOrigin?

They technically haven't had to do that since we switched to using access tokens as long as they didn't disable them. But this will probably even remove the need for access tokens. Will have to confirm on FF.
