### PR TITLE
search contexts: do not show CTA if non global context has been used

### LINKED ISSUE #25463: Unable to change the context once set on sourcegraph.com
- **Sourcegraph version:** sourcegraph.com on 28-September-2021

#### Steps to reproduce:

1. Change the context using a query.  Example: [`context:stanford test`](https://sourcegraph.com/search?q=context:stanford+test&patternType=literal) 
2. Click on the context and attempt to change the context
3. Go back to the sourcegraph.com site and click on context and attempt to change the context

#### Expected behavior:

A drop down appears with the list of available contexts.

#### Actual behavior:

The "Search the code you care about ..." popup shows up and the context popup does not:

image

### PR DESCRIPTION
**Pull request by novoselrok**
Fixes #25463

### CODE REVIEW

File: client/web/src/search/input/SearchContextDropdown.tsx [hunk 1]
```diff
@@ -97,6 +98,13 @@ export const SearchContextDropdown: React.FunctionComponent<SearchContextDropdow
         })
     )
 
+    const [hasUsedNonGlobalContext, setHasUsedNonGlobalContext] = useTemporarySetting('search.usedNonGlobalContext')
+    useEffect(() => {
+        if (selectedSearchContextSpec && selectedSearchContextSpec !== 'global' && !hasUsedNonGlobalContext) {
+            setHasUsedNonGlobalContext(true)
+        }
```
Comment (limitedmage) [inline client/web/src/search/input/SearchContextDropdown.tsx:105]: Will this trigger if the user visits a context page like https://sourcegraph.com/cncf ? If yes, is this intentional/desired? It might be the first entry point into Sourcegraph for some.

**Review by limitedmage — APPROVED** [review]

File: client/web/src/search/input/SearchContextDropdown.tsx (hunk 1 above)
Comment (novoselrok) [reply client/web/src/search/input/SearchContextDropdown.tsx]: Good point, I moved the code around a bit to avoid this.
