### PR TITLE
Present search timeouts in a reasonable and consistent way; bump default Zoekt 1.5s timeout -> 3s

### LINKED ISSUE #6754: When search hits unindexed repositories, a poor timeout UX / error is returned
A user ran a search query that hit a few unindexed repositories and just got this error back:

```
1 error occurred: * text search failed: no results found before timeout in index search (try timeout:3s)
```

This is a poor UX and does not match other cases where we return timeouts and provide the user with a clear description of what happened and button/link to add `timeout:3s` to their query.

Reported by a user @ HS:407948923 (https://app.hubspot.com/contacts/2762526/company/407948923)

### PR DESCRIPTION
**Pull request by slimsag**
### Before this change: a literal UX disaster

Sometimes, you would just get a timeout error without any clear action:

image

Sometimes, you would get a completely different timeout UI with a clear action:

image

And other times you would get yet again a completely different UI with different styling and messaging:

image

### After this change: a more pleasant experience

There is only **one UI**, it is **always consistent**, and it **always has a clear action button to wait longer** and **recommendations are shown consistently and appropriately**.

image

Additionally, instead of the default Zoekt timeout of 1.5s we now use 3s. The reasoning for this is that no user would reasonably want to get an error instead of waiting an extra 1.5s. There is a clear argument for not going higher than this, of course, because once you start getting into 4-5s territory users may not want to wait that long. This is a stop-gap solution and signals the need for better search timeout monitoring: #6756

Fixes #6754

Test plan: Manual, this code is unfortunately very difficult to test currently.

### CODE REVIEW

**Comment by slimsag** [comment]
Best reviewed commit-by-commit

File: cmd/frontend/graphqlbackend/zoekt.go [hunk 1]
```diff
@@ -49,7 +49,7 @@ func zoektResultCountFactor(numRepos int, query *search.PatternInfo) int {
 
 func zoektSearchOpts(k int, query *search.PatternInfo) zoekt.SearchOptions {
 	searchOpts := zoekt.SearchOptions{
-		MaxWallTime:            1500 * time.Millisecond,
+		MaxWallTime:            1500 * time.Second,
```
Comment (slimsag) [inline cmd/frontend/graphqlbackend/zoekt.go]: Fixed in subsequent commit

File: cmd/frontend/graphqlbackend/zoekt.go [hunk 2]
```diff
@@ -74,6 +74,13 @@ func zoektSearchOpts(k int, query *search.PatternInfo) zoekt.SearchOptions {
 	return searchOpts
 }
 
+var errNoResultsInTimeout = errors.New("no results found in specified timeout:")
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/zoekt.go]: nit: error message ends with `:` seems unusual?

File: cmd/frontend/graphqlbackend/zoekt.go [hunk 3]
```diff
@@ -74,6 +74,13 @@ func zoektSearchOpts(k int, query *search.PatternInfo) zoekt.SearchOptions {
...
+
+// zoektSearchHEAD searches repositories using zoekt.
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/zoekt.go]: nit:
```diff
-	// zoektSearchHEAD searches repositories using zoekt.
+	// zoektSearchHEAD searches HEAD of repositories using zoekt.
```

Thanks for adding godoc ❤️

File: cmd/frontend/graphqlbackend/search_results.go [hunk 4]
```diff
@@ -479,25 +479,27 @@ func (r *searchResolver) Results(ctx context.Context) (*SearchResultsResolver, e
...
+	if err == nil && len(rr.searchResultsCommon.timedout) == len(rr.searchResultsCommon.repos) {
+		allReposTimedout = true
+	}
+	if allReposTimedout {
+		dt := time.Since(start)
+		dt2 := longer(2, dt)
+		rr = &SearchResultsResolver{
+			alert: &searchAlert{
+				title:       "Timed out while searching",
+				description: fmt.Sprintf("We weren't able to find any results in %s.", roundStr(dt.String())),
```
Comment (rvantonder) [inline cmd/frontend/graphqlbackend/search_results.go]: Small thing: it'd be nice if we could make something like `results in 2s` be human readable like `2 seconds`. I had a brief look at the standard library functions but it looks like this doesn't exist.

File: cmd/frontend/graphqlbackend/search_results.go [hunk 5]
```diff
@@ -479,25 +479,27 @@ func (r *searchResolver) Results(ctx context.Context) (*SearchResultsResolver, e
...
-					proposedQueries: []*searchQueryDescription{
-						{
-							description: "query with longer timeout",
-							query:       fmt.Sprintf("timeout:%v %s", dt2, omitQueryFields(r, query.FieldTimeout)),
-						},
+
+	allReposTimedout := err == context.DeadlineExceeded
+	if err == nil && len(rr.searchResultsCommon.timedout) == len(rr.searchResultsCommon.repos) {
+		allReposTimedout = true
+	}
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/search_results.go]: WDYT about this?

```go
	allReposTimedout := err == context.DeadlineExceeded || 
		len(rr.searchResultsCommon.timedout) == len(rr.searchResultsCommon.repos)
```

File: cmd/frontend/graphqlbackend/search_results.go [hunk 6]
```diff
@@ -479,25 +479,27 @@ func (r *searchResolver) Results(ctx context.Context) (*SearchResultsResolver, e
...
+	if allReposTimedout {
```
Comment (rvantonder) [inline cmd/frontend/graphqlbackend/search_results.go]: Is it possible that the logic here can go as follows:

> allReposTimedout := err == context.DeadlineExceeded

Evaluates true.

> 	if err == nil && len(rr.searchResultsCommon.timedout) == len(rr.searchResultsCommon.repos)

Evaluates false.

Then

> if allReposTimedout {

evaluates true, but does not imply 
`len(rr.searchResultsCommon.timedout) == len(rr.searchResultsCommon.repos)`, and executes the branch body. Is this intended? Because my understanding is that `"all repos timed out"` implies `len(rr.searchResultsCommon.timedout) == len(rr.searchResultsCommon.repos)`. So either I misunderstand the variable name here (maybe `AllOrSomeReposTimedout`?), or the intent.

File: cmd/frontend/graphqlbackend/search_results.go (hunk 5 above)
Comment (slimsag) [reply cmd/frontend/graphqlbackend/search_results.go]: If written that way it would actually have to be:

```Go
allReposTimedout := err == context.DeadlineExceeded || 
		(err == nil && len(rr.searchResultsCommon.timedout) == len(rr.searchResultsCommon.repos))
```

This seemed too long / made the if statement more readable for me. Which do you prefer?

File: cmd/frontend/graphqlbackend/zoekt.go (hunk 2 above)
Comment (slimsag) [reply cmd/frontend/graphqlbackend/zoekt.go]: Whoops, typo, thanks for catching!

Comment (slimsag) [inline cmd/frontend/graphqlbackend/zoekt.go]:
```suggestion
var errNoResultsInTimeout = errors.New("no results found in specified timeout")
```

File: cmd/frontend/graphqlbackend/search_results.go (hunk 5 above)
Comment (unknwon) [reply cmd/frontend/graphqlbackend/search_results.go]: I see, `err` could have other values, got it!

File: cmd/frontend/graphqlbackend/search_results.go (hunk 4 above)
Comment (slimsag) [reply cmd/frontend/graphqlbackend/search_results.go]: I think this is a topic worth discussing separately because currently the wording `2s` does match what the `timeout:` filter requires

File: cmd/frontend/graphqlbackend/search_results.go (hunk 6 above)
Comment (slimsag) [reply cmd/frontend/graphqlbackend/search_results.go]: Go functions are assumed to (unless documented otherwise) return `value, nil` OR an `nil, error`.

So, if `err != nil` then it means we did not get a value (search results) and inherently we did not get results for any repository. If `err == context.DeadlineExceeded` then we did not get results for any repository because of a timeout.

In other words, either of these conditions (`err == context.DeadlineExceeded` OR `len() == len()`) implies that all repositories have timed out and showing the alert is appropriate.

Comment (slimsag) [reply cmd/frontend/graphqlbackend/search_results.go]: This would be much more clear if the search code wasn't so convoluted / complex and undocumented..

Comment (slimsag) [reply cmd/frontend/graphqlbackend/search_results.go]: And, of course, upon closer inspection my assumption is wrong 😝

Comment (slimsag) [reply cmd/frontend/graphqlbackend/search_results.go]: I've reworded the variable and added a bunch of docstrings to clarify what is going on here. It's not perfect, but it's a step in the right direction.

Comment (rvantonder) [reply cmd/frontend/graphqlbackend/search_results.go]: Thanks.

**Comment by mrnugget** [comment]
:clap: :clap: :clap: This is much clearer than before.

But I have to say, as someone who doesn't really know how our timeout system works, the fact that these two durations are different are still confusing as hell to me:

timeout

It's like I asked the system for X and it tells me "nope, couldn't find Y"

File: cmd/frontend/graphqlbackend/zoekt.go [hunk 7]
```diff
@@ -49,7 +49,7 @@ func zoektResultCountFactor(numRepos int, query *search.PatternInfo) int {
 
 func zoektSearchOpts(k int, query *search.PatternInfo) zoekt.SearchOptions {
 	searchOpts := zoekt.SearchOptions{
-		MaxWallTime:            1500 * time.Millisecond,
+		MaxWallTime:            3 * time.Second,
```
Comment (keegancsmith) [inline cmd/frontend/graphqlbackend/zoekt.go]: we should probably make this the `max(3s, timeout param - 100ms)`, but this is a clear improvement :)

File: web/src/search/backend.tsx [hunk 8]
```diff
@@ -63,6 +63,9 @@ export function search(
                                 cloning {
                                     name
                                 }
+                                repositories {
+                                    name
+                                }
```
Comment (keegancsmith) [inline web/src/search/backend.tsx]: why are you querying this list? It will nearly always be very large at large installations. I see later you are doing `length == timedout.length`. That is a lot of data just for that computation. I recommend somehow exposing this bit of state from the GraphQL API, rather than needing to return everything.

File: web/src/search/results/SearchResultsList.tsx [hunk 9]
```diff
@@ -432,22 +431,9 @@ export class SearchResultsList extends React.PureComponent<SearchResultsListProp
...
-                                                {this.renderRecommendations([
-                                                    <>
-                                                        Try narrowing your query, or specifying a longer "timeout:" in
-                                                        your query.
-                                                    </>,
-                                                    /* If running on non-cluster, give some smart advice */
-                                                    ...(!this.props.isSourcegraphDotCom &&
+                                            {results.timedout.length === results.repositories.length &&
+                                                /* All repositories timed out. */
+                                                this.renderRecommendations(
```
[the remark this answers is not in the document]
Comment (slimsag) [reply web/src/search/results/SearchResultsList.tsx]: I largely agree with what you have said here, but:

1. This does act as a forcing function to pressure admins to give Sourcegraph more resources
2. This does act as an indicator to explain to users that this is not a normal Sourcegraph experience
3. If these were only shown to a site admin, most likely the site admins would just not come across them unless an extremely serious problem was going on.
4. We do not have a way currently to surface if searches are regularly timing out. See #6756

**Comment by slimsag** [comment]
> But I have to say, as someone who doesn't really know how our timeout system works, the fact that these two durations are different are still confusing as hell to me:

In practice this doesn't happen, it was only the case in the screenshot you quoted because I threw in a sleep statement to reproduce this behavior.

File: cmd/frontend/graphqlbackend/zoekt.go (hunk 7 above)
Comment (slimsag) [reply cmd/frontend/graphqlbackend/zoekt.go]: We already do something smarter than what you are suggesting it seems, but the code is a bit convoluted / scattered across multiple locations unfortunately: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+MaxWallTime&patternType=literal

**Comment by slimsag** [comment]
Here is a corrected screenshot @mrnugget of what happens when actually running that query on this branch:

image

You may note the returned timeout is still somewhat larger than you specified, but within a very reasonable margin I would suggest :)

File: web/src/search/backend.tsx (hunk 8 above)
Comment (slimsag) [reply web/src/search/backend.tsx]: Thank you for calling this out, I agree this is a problem. I've exposed the count via GraphQL and am using that instead of fetching the entire list now.

File: web/src/search/results/SearchResultsList.tsx (hunk 9 above)
[the remark this answers is not in the document]
Comment (christinaforney) [reply web/src/search/results/SearchResultsList.tsx]: Makes sense. In that case can we change this to communicate a slightly different message? Rather than telling the user to upgrade the resources, can we encourage them to talk to the admins?:

> "It is not expected behavior for timeouts to happen regularly if your Sourcegraph instance is appropriately provisioned. Please let your Sourcegraph administrator know if you are seeing this warning frequently."

[the remark this answers is not in the document]
Comment (slimsag) [reply web/src/search/results/SearchResultsList.tsx]: I went with this which is a bit less verbose and still gets the point across:

> Contact your Sourcegraph administrator if you are seeing timeouts regularly, as more CPU, memory, or disk resources may need to be provisioned.

**Comment by slimsag** [comment]
@sourcegraph/code-intel LSIF failed on my build

File: cmd/frontend/graphqlbackend/search_results.go [hunk 10]
```diff
@@ -479,25 +483,33 @@ func (r *searchResolver) Results(ctx context.Context) (*SearchResultsResolver, e
...
+						description: "query with longer timeout",
+						query:       fmt.Sprintf("timeout:%v %s", dt2, omitQueryFields(r, query.FieldTimeout)),
 					},
 				},
-			}
-			return rr, nil
+			},
 		}
-		return nil, err
+		return rr, nil
```
Comment (slimsag) [inline cmd/frontend/graphqlbackend/search_results.go]: I messed up here and this would've introduced a regression where all search errors would not be returned to the client. Will fix in new PR.

**Comment by mrnugget** [comment]
> You may note the returned timeout is still somewhat larger than you specified, but within a very reasonable margin I would suggest :)

My problem was not the delta between the timeouts but the fact that there is a delta at all. As I user I don't get why when I say "do this in a maximum of N seconds" the system tells me "I couldn't do it in N+d seconds".

I assume it has to do with the precision of sub-second timeouts? But as a user it would be more reassuring if those numbers were the same.

**Comment by slimsag** [comment]
> My problem was not the delta between the timeouts but the fact that there is a delta at all. As I user I don't get why when I say "do this in a maximum of N seconds" the system tells me "I couldn't do it in N+d seconds".

Ah, I see your problem now.

The truth is we just can't always cancel and return the search with sub-second precision, as you guessed. So if you ask us to `timeout:2ms` we might take say 50ms. We could lie to you and tell you it took 2ms, but sometimes the difference could be substantial I think (could be on the order of several seconds for very large queries depending on which search code path you hit), and I think it would be worse for it to say "Couldn't find results in 2s"  and yet have the actual GraphQL query take 6s or something.

**Comment by mrnugget** [comment]
> So if you ask us to `timeout:2ms` we might take say 50ms. We could lie to you and tell you it took 2ms, but sometimes the difference could be substantial I think (could be on the order of several seconds for very large queries depending on which search code path you hit), and I think it would be worse for it to say "Couldn't find results in 2s" and yet have the actual GraphQL query take 6s or something.

In that case I think we have two options:
1. Make it clearer that `timeout` is only a best-effort option (your message would be a great place to communicate that)
2. Try to avoid substantial deltas 😄 

(Just for clarification: I don't expect you to fix this now, it's just something that I noticed)
