### PR TITLE
search: Migrate search console page to use CodeMirror

### LINKED ISSUE #20636: Autocomplete / hovers are broken in the editor
Steps to reproduce

Use the repo selecter on a new line. No autocomplete or hover appears.

### PR DESCRIPTION
**Pull request by fkling**
This PR replaces the Monaco query editor used on the search console page with the CodeMirror version. I thought that directly replacing this instance (without a feature flag) is relatively safe to do because the multiline version is already different enough from the main query input, and it's probably a feature that is not widely used. This also fixes at least two problems with current implementation:

- Diagnostics are rendered at the correct position
- Query completion works everywhere, not just the first line (fixes #20636)

Besides replacing the editor I also made some style tweaks:

- Full column editor
- Scrollable result list (i.e. not scrolling the whole page)

Before: 

https://user-images.githubusercontent.com/179026/175657358-e82b14c2-f152-4376-9f4e-afaca2ef8f9f.mp4

After: 

https://user-images.githubusercontent.com/179026/175657370-a07ab8a0-2076-4e3f-838a-ae9f600ca442.mp4

## Test plan

- Enable search console via the experimental feature flag `"showMultilineSearchConsole: true"`.
- Go to https://sourcegraph.test:3443/search/console
- Clicking on the editor div should focus the editor
- Type search query -> filter/symbol suggestions should appear
- Press `Enter` -> line break is inserted, search query is not submitted
- Press `CTRL/CMD + Enter` to submit query -> URL should update and result list should update
- Enter as many line breaks as necessary to cause the editor to scroll -> it should not overflow and show a scrollbar.
- Typing an invalid query (e.g. `test\n\nauthor:`) should show diagnostic information at the correct position.

## App preview:

- [Web](https://sg-web-fkling-search-console-page.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-azcfduagia.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

File: client/search-ui/src/index.ts [hunk 1]
```diff
@@ -1,14 +1,16 @@
...
 export * from './results/StreamingSearchResultsList'
 export * from './results/progress/StreamingProgress'
 export * from './results/progress/StreamingProgressCount'
-export * from './results/sidebar/revisions'
 export * from './results/sidebar/FilterLink'
 export * from './results/sidebar/SearchSidebar'
-export * from './input/LazyMonacoQueryInput'
-export * from './input/MonacoQueryInput'
+export * from './results/sidebar/revisions'
 export * from './util'
```
Comment (fkling) [inline client/search-ui/src/index.ts:16]: Two new entries, the rest was sorted alphabetically.

File: client/web/src/search/SearchConsolePage.tsx [hunk 2]
```diff
@@ -174,7 +131,7 @@ export const SearchConsolePage: React.FunctionComponent<React.PropsWithChildren<
                                 {...props}
                                 allExpanded={false}
                                 results={results}
-                                showSearchContext={showSearchContext}
+                                showSearchContext={false}
```
Comment (fkling) [inline client/web/src/search/SearchConsolePage.tsx:134]: This is OK because it is only used to inform the "no results page" how to render the query input examples. (this should be refactored somehow)

Comment (limitedmage) [reply client/web/src/search/SearchConsolePage.tsx:134]: At this point this experimental flag should be removed entirely, it's been I think a year since we added search contexts.

**Review by limitedmage — APPROVED** [review]
