### PR TITLE
Show warnings when sync failed after External Service creation/update was successful

### LINKED ISSUE #4052: Error when adding GitHub external service
image

```
Error saving invalid configuration:

warning: external service created, but sync request failed: syncer.sync.sourced: 1 error occurred:
* failed to list GitHub repositories for search: page='\x02', searchString="org:sourcegraph",: github repository search returned incomplete results. This is an ephemeral error: query="org:sourcegraph" page=2 total=272
```

This is the commented-out example query.

I also think the "Error saving invalid configuration" is weird. If you knew it was invalid, why did you try to save it instead of telling me what is invalid?

### PR DESCRIPTION
**Pull request by mrnugget**
This fixes #4052 by

* changing the actual error message to make it easier to understand
* treating every error after the successful creation/update of an external service as a *warning*
* displaying the warnings in the UI in an `alert-warning` with an added explanation

Notes to reviewers:
1. I haven't done any TypeScript/React programming at Sourcegraph, so let me know if I'm missing something
2. I'm still not sure if this is the best message for the user, since it's not actionable and just a note that says that _something_ they have no clue about didn't work as expected.

Should we maybe add "try updating the service" note to the warning?

@sqs: Maybe you have some suggestions here

---

When *creating* an external service succeeds but syncing the config to `repo-updater` fails with a warning, it looks like this:

add_external_service_warning
(This is a GIF)

(Note: clicking on the `ExternalServiceCard` above the warning redirects the user to the edit-page for the just-created external service)

---

When *updating* an external service succeeds but syncing fails for the same reason:

update_external_service_warning
(This is a GIF)

---

(*Important*: if this needs to be cherry-picked into a 3.4 release, it depends on https://github.com/sourcegraph/sourcegraph/commit/a348d5c995529bbfc9082c58cc9c815196377471 and https://github.com/sourcegraph/sourcegraph/commit/25226c3c1b539f82aada22de8aacc5dc2758d999)

Test plan: manual testing in the browser, creating & updating services and producing the error in the background

### CODE REVIEW

**Comment by mrnugget** [comment]
The original ticket (https://github.com/sourcegraph/sourcegraph/issues/4052) is tagged as a release-blocker, so I have a question: should I add this to the changelog? And if yes, add it to 3.4 or `Unreleased`?

**Comment by keegancsmith** [comment]
> The original ticket (#4052) is tagged as a release-blocker, so I have a question: should I add this to the changelog? And if yes, add it to 3.4 or `Unreleased`?

Yes it deserves a changelog. Maybe add a new section `3.4.1 (Unreleased)`.

**Comment by mrnugget** [comment]
> Yes it deserves a changelog. Maybe add a new section `3.4.1 (Unreleased)`.

I added something to the `Unreleased` section under `Changed`. Maybe @beyang can give concrete instructions here?

File: cmd/repo-updater/repoupdater/server.go [hunk 1]
```diff
@@ -277,6 +277,13 @@ func (s *Server) handleExternalServiceSync(w http.ResponseWriter, r *http.Reques
 		respond(w, http.StatusOK, &protocol.ExternalServiceSyncResult{
 			ExternalService: req.ExternalService,
 		})
+	case err == github.ErrIncompleteResults:
+		log15.Info("server.external-service-sync", "kind", req.ExternalService.Kind, "error", err)
+		syncResult := &protocol.ExternalServiceSyncResult{
+			ExternalService: req.ExternalService,
+			Error:           err.Error(),
+		}
+		respond(w, http.StatusOK, syncResult)
```
[the remark this answers is not in the document]
Comment (mrnugget) [reply cmd/repo-updater/repoupdater/server.go]: Yeah, I wasn't sure about this due to these two comments:

https://github.com/sourcegraph/sourcegraph/blob/191e9213d39cc4d6de0051b553a8b5816d63bcbc/pkg/repoupdater/client.go#L190-L201

Is it now save to switch to the new response type? If so, I'd like to tackle this in a separate PR/branch so we don't mix two changes here

File: cmd/frontend/graphqlbackend/external_services.go [hunk 2]
```diff
@@ -102,7 +104,11 @@ func syncExternalService(ctx context.Context, svc *types.ExternalService) error
 		return err
 	}
 
-	return res.Error
+	if res.Error != "" {
+		return errors.New(res.Error)
+	}
```
[the remark this answers is not in the document]
Comment (mrnugget) [reply cmd/frontend/graphqlbackend/external_services.go]: Done

**Comment by beyang** [comment]
@mrnugget I just added sections to CHANGELOG.md for "3.5.0 (unreleased)" and "3.4.1 (unreleased)". Please add it to just one. If the latter, please cherry-pick onto the `3.4` branch before 5pm PT 5/22.

File: cmd/repo-updater/repoupdater/server.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (keegancsmith) [reply cmd/repo-updater/repoupdater/server.go]: oh I see the problem. leave this as is and we can tackle it in another PR.

File: CHANGELOG.md [hunk 3]
```diff
@@ -16,6 +16,7 @@ All notable changes to Sourcegraph are documented in this file.
 ### Changed
 
 - The saved searches UI has changed. There is now a Saved searches page in the user and organizations settings area. A saved search appears in the settings area of the user or organization it is associated with.
+- Site admins will now see a warning if creating or updating an external service was successful but the process could not complete entirely due to an ephemeral error (such as the GitHub API shedding load and returning incomplete results).
```
Comment (sqs) [inline CHANGELOG.md]:
```suggestion
- Site admins will now see a warning if creating or updating an external service was successful but the process could not complete entirely due to an ephemeral error (such as when the code host's API is unreachable due to an outage).
```

I'm not sure what "shedding load" means in this case, so I reworded it to something that makes sense to me. Let me know if "shedding load" means something specific.

File: web/src/site-admin/SiteAdminAddExternalServicePage.tsx [hunk 4]
```diff
@@ -88,26 +98,48 @@ export class SiteAdminAddExternalServicePage extends React.Component<Props, Stat
...
+                        <div className="mb-3" key={createdExternalService.id}>
+                            <ExternalServiceCard
+                                {...kindMetadata}
+                                title={createdExternalService.displayName}
+                                shortDescription="Update this external service configuration to manage repository mirroring."
+                                to={`/site-admin/external-services/${createdExternalService.id}`}
+                            />
+                        </div>
+                        <div className="alert alert-warning">
+                            <p>
```
Comment (sqs) [inline web/src/site-admin/SiteAdminAddExternalServicePage.tsx]: Replace the `<p><b>Warning</b></p>` with a `<h4>Warning</h4>` or something. It is semantically a header (not just any other paragraph), so h4 makes sense.

File: web/src/site-admin/SiteAdminAddExternalServicePage.tsx [hunk 5]
```diff
@@ -88,26 +98,48 @@ export class SiteAdminAddExternalServicePage extends React.Component<Props, Stat
...
-                    loading={this.state.loading}
-                />
+                {createdExternalService && createdExternalService.warning ? (
+                    <div>
+                        <div className="mb-3" key={createdExternalService.id}>
+                            <ExternalServiceCard
+                                {...kindMetadata}
+                                title={createdExternalService.displayName}
+                                shortDescription="Update this external service configuration to manage repository mirroring."
+                                to={`/site-admin/external-services/${createdExternalService.id}`}
```
Comment (sqs) [inline web/src/site-admin/SiteAdminAddExternalServicePage.tsx]: GraphQL type *should* contain `url` fields so their values know their own URL and it comes from the backend in one source of truth, instead of constructing URLs in many places on the frontend. `ExternalService` does not (and it's not high priority to add that field), so what you did here is correct, but I just wanted to note that for your knowledge.

File: web/src/site-admin/SiteAdminAddExternalServicePage.tsx [hunk 6]
```diff
@@ -88,26 +98,48 @@ export class SiteAdminAddExternalServicePage extends React.Component<Props, Stat
...
-                    editorActions={externalService.editorActions}
-                    jsonSchema={externalService.jsonSchema}
-                    mode="create"
-                    onSubmit={this.onSubmit}
-                    onChange={this.onChange}
-                    loading={this.state.loading}
-                />
+                {createdExternalService && createdExternalService.warning ? (
+                    <div>
+                        <div className="mb-3" key={createdExternalService.id}>
```
Comment (sqs) [inline web/src/site-admin/SiteAdminAddExternalServicePage.tsx]: The `key` attribute is not necessary because this is not in an array

File: web/src/site-admin/SiteAdminExternalServiceForm.tsx [hunk 7]
```diff
@@ -33,6 +34,12 @@ export class SiteAdminExternalServiceForm extends React.Component<Props, {}> {
                         <Markdown dangerousInnerHTML={renderMarkdown(this.props.error.message)} />
                     </div>
                 )}
+                {this.props.warning && (
+                    <div className="alert alert-warning">
+                        <p>Warning:</p>
```
Comment (sqs) [inline web/src/site-admin/SiteAdminExternalServiceForm.tsx]: same note about using `<h4>` here not `<p>` (and omit the colon because you omitted it in the other place, too).

File: CHANGELOG.md (hunk 3 above)
Comment (mrnugget) [reply CHANGELOG.md]: Specifically, it's about this: https://developer.github.com/v3/search/#timeouts-and-incomplete-results and https://developer.github.com/changes/2014-04-07-understanding-search-results-and-potential-timeouts/

> For queries that exceed the time limit, the API returns the matches that were already found prior to the timeout, and the response has the incomplete_results property set to true.

My original changelog entry was... a guess, because I didn't know what to write, but I now think this would be better:

```
(such as GitHub API search queries running into timeouts and returning incomplete results)
```

File: web/src/site-admin/SiteAdminAddExternalServicePage.tsx (hunk 5 above)
Comment (mrnugget) [reply web/src/site-admin/SiteAdminAddExternalServicePage.tsx]: Thanks! Good to know!

File: CHANGELOG.md (hunk 3 above)
Comment (sqs) [reply CHANGELOG.md]: 👍 looks good

File: web/src/site-admin/SiteAdminExternalServicePage.tsx [hunk 8]
```diff
@@ -64,16 +66,17 @@ export class SiteAdminExternalServicePage extends React.Component<Props, State>
...
                             updateExternalService(input).pipe(
-                                mapTo(null),
-                                mergeMap(() =>
-                                    concat(
-                                        // Flash "updated" text
-                                        of({ updatedOrError: true }),
-                                        // Hide "updated" text again after 1s
-                                        of({ updatedOrError: null }).pipe(delay(1000))
-                                    )
+                                mergeMap(val =>
```
Comment (felixfbecker) [inline web/src/site-admin/SiteAdminExternalServicePage.tsx]: Suggestion: use destructuring `mergeMap(({ warning }) =>`
"val" doesn't add any explanation, and this is shorter and easier to read.

File: web/src/site-admin/SiteAdminExternalServiceForm.tsx [hunk 9]
```diff
@@ -33,6 +34,12 @@ export class SiteAdminExternalServiceForm extends React.Component<Props, {}> {
                         <Markdown dangerousInnerHTML={renderMarkdown(this.props.error.message)} />
                     </div>
                 )}
+                {this.props.warning && (
+                    <div className="alert alert-warning">
+                        <h4>Warning</h4>
+                        <Markdown dangerousInnerHTML={renderMarkdown(this.props.warning)} />
+                    </div>
+                )}
```
Comment (felixfbecker) [inline web/src/site-admin/SiteAdminExternalServiceForm.tsx]: I find it a bit weird that the "Updated!" is shown at the bottom but the warning is shown at the top (I'd go for everything at the top)

**Comment by mrnugget** [comment]
Cherry-picked  25226c3c1b539f82aada22de8aacc5dc2758d999, a348d5c995529bbfc9082c58cc9c815196377471, and 5048094b49506904998238c0f3a2ecdd63300806 into `3.4`

File: web/src/site-admin/SiteAdminExternalServiceForm.tsx (hunk 9 above)
Comment (mrnugget) [reply web/src/site-admin/SiteAdminExternalServiceForm.tsx]: I think the `Updated!` is shown at the bottom because it disappears after a second and thus causes the whole layout to move around:

update_jank
