### PR TITLE
fix(buildchecker-reports): split webhooks for history as well

### LINKED ISSUE #37807: buildchecker-history: slack reports not delivering
I think we're supposed to get buildchecker reports weekly in #ci-reports and #dev-experience, but right now it looks like neither are getting reports :( Relevant workflow: https://github.com/sourcegraph/sourcegraph/actions/workflows/buildchecker-history.yml

### PR DESCRIPTION
**Pull request by burmudar**
The webhooks were being split for `check` but not for `history` ... this fixes it

Closes #37807 
## Test plan
Tested it locally by posted to `william-buildchecker-webhook-test`

### CODE REVIEW

File: dev/buildchecker/main.go [hunk 1]
```diff
@@ -409,7 +409,8 @@ func cmdHistory(ctx context.Context, flags *Flags, historyFlags *cmdHistoryFlags
 
 		message := generateWeeklySummary(historyFlags.createdFromDate, historyFlags.createdToDate, totalBuilds, totalFlakes, avgFlakes, time.Duration(totalTime*int(time.Minute)))
 
-		if _, err := postSlackUpdate([]string{historyFlags.slackReportWebHook}, message); err != nil {
+		webhooks := strings.Split(historyFlags.slackReportWebHook, ",")
+		if _, err := postSlackUpdate(webhooks, message); err != nil {
 			log.Fatal("postSlackUpdate: ", err)
```
Comment (sanderginn) [inline dev/buildchecker/main.go:414]: What is the reason we don't use our shiny logging package here?

**Review by sanderginn — APPROVED** [review]
Nice 👍

File: dev/buildchecker/main.go (hunk 1 above)
Comment (jhchabran) [reply dev/buildchecker/main.go:414]: All of this is optional, so we could use it here :) But I agree with you that at rock bottom, we're just looking at the logs, nothing more, so that println is good enough :)

Comment (sanderginn) [reply dev/buildchecker/main.go:414]: Makes sense 👍
