### PR TITLE
license_expiration: Check all subscriptions

### LINKED ISSUE #15467: Fix the Sourcegraph.com license expiration bot
I built a bot that only functions on Sourcegraph.com that posts a note to our sales team whenever a customer license is about to expire. It _mostly_ doesn't work, but once in a while something will randomly appear (see the #licenses channel).

The bot is defined in https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/dotcom/productsubscription/license_expiration.go.

I've tested locally and it always seems to work just fine. Perhaps something is broken on dotcom due to having multiple frontends? Perhaps my date/time logic is off somehow? Perhaps the webhook env var sometimes isn't set? I'm quite lost.

### PR DESCRIPTION
**Pull request by tsenart**
The previous code would return in the for loop where all subscriptions
were checked. A common case for that to happen was when a subscription
had less than one license.

Instead, we extract the code for checking each subscription into a
separate function, and we call that for each subscription, even in the
face of errors in the previous one.

Fixes #15467

### CODE REVIEW

File: enterprise/cmd/frontend/internal/dotcom/productsubscription/license_expiration.go [hunk 1]
```diff
@@ -84,48 +84,52 @@ func checkForUpcomingLicenseExpirations(clock glock.Clock, client slackClient) {
...
 	for _, dbSubscription := range allDBSubscriptions {
-		// Get the active (i.e., latest created) license.
-		licenses, err := dbLicenses{}.List(ctx, dbLicensesListOptions{ProductSubscriptionID: dbSubscription.ID, LimitOffset: &db.LimitOffset{Limit: 1}})
-		if err != nil {
-			log15.Error("startCheckForUpcomingLicenseExpirations: error listing licenses", "error", err)
-			return
-		}
-		// Skip if subscription has no licenses.
-		if len(licenses) < 1 {
-			return
```
Comment (tsenart) [inline enterprise/cmd/frontend/internal/dotcom/productsubscription/license_expiration.go:95]: This return here was the problem @dadlerj.

Comment (dadlerj) [reply enterprise/cmd/frontend/internal/dotcom/productsubscription/license_expiration.go:95]: 🤦

Comment (tsenart) [reply enterprise/cmd/frontend/internal/dotcom/productsubscription/license_expiration.go:95]: Happens :D

Comment (dadlerj) [reply enterprise/cmd/frontend/internal/dotcom/productsubscription/license_expiration.go:95]: Just to check, replacing this with a `continue` would have also helped here right? (your update is more idiomatic I know)

Comment (tsenart) [reply enterprise/cmd/frontend/internal/dotcom/productsubscription/license_expiration.go:95]: Yes, it would have for that case, but there were a lot of other `return`s in the loop body, so now we're extra fault tolerant per-subscription.
