### PR TITLE
search: perform -repo exclusion for Sourcegraph.com

### LINKED ISSUE #10481: -repo doesn't work on Sourcegraph.com for indexed repositories
We use a list of indexed repos of Sourcegraph.com and if `-repo` is specified for these it's not honored. [Example query](https://sourcegraph.com/search?q=lang:go+foo+-repo:ElasticHD%24+-repo:matterbridge%24+-repo:gqlgen%24+-repo:v2rayNG%24+index:only&patternType=regexp), one or more of those excluded repos will show up. Another [example](https://sourcegraph.com/search?q=-repo:%5Egithub%5C.com/aQuaYi/LeetCode-in-Go%24+lang:go+type%5Cs%5Cw*%5Cs%3D+&patternType=regexp).

~I recall someone mentioning this somewhere, but don't think it's tracked in issues.~ It was mentioned in slack.

### PR DESCRIPTION
**Pull request by fedealconada**
Hey @rvantonder, here's the PR to fixes #10481 

Basically, the problem was what you pointed out: you are not applying `excludePatterns`. I thought a bit where the exclusion should take place and I've came to the conclusion that either we could do it after [this](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@457f09b4c52ccde2bdf114f44f9ce77cca2efd63/-/blob/cmd/frontend/graphqlbackend/search.go#L637) line or, we could change the signature of `defaultRepositories` (I checked it's only called from one and only one place) to receive also the `excludePatterns` and do the filtering inside there. And I went for the latter option (I also thought about instead of passing `excludePatterns`to `defaultRepositories` function,  to pass a function that filters elements but then I though it could be of overthinking).

For the tests, I've just added more cases on [search_test.go](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@60d51e2e3f1f90094cebc38ca0af822a6c7b0bf5/-/blob/cmd/frontend/graphqlbackend/search_test.go#L256)

What do you think about this approach? I have anyways made the PR a draft one.

Fixes #10481

### CODE REVIEW

**Comment by rvantonder** [comment]
This looks great! I didn't realize we already have tests set up for this, so that should be enough. I'm putting it up for review and will kick off a build. Just a quick note: our team is at the point of releasing the next version of Sourcegraph, so I'll probably get a chance to merge this a bit later ~tomorrow.

File: cmd/frontend/graphqlbackend/search.go [hunk 1]
```diff
@@ -754,12 +754,25 @@ func resolveRepositories(ctx context.Context, op resolveRepoOp) (repoRevisions,
...
 	// Get the list of default repos from the db.
 	defaultRepos, err := getRawDefaultRepos(ctx)
 	if err != nil {
 		return nil, errors.Wrap(err, "querying db for default repos")
 	}
+
+	// Remove excluded repos
+	if excludePatterns != nil {
+		patterns := `(?i)` + unionRegExps(excludePatterns)
+		filteredRepos := defaultRepos[:0]
```
Comment (rvantonder) [inline cmd/frontend/graphqlbackend/search.go:767]: Stylistically, this might just be better as just a `var filteredRepos ...`. Deferring to our Go gurus on this (cc @unknwon)

File: cmd/frontend/graphqlbackend/search.go [hunk 2]
```diff
@@ -754,12 +754,25 @@ func resolveRepositories(ctx context.Context, op resolveRepoOp) (repoRevisions,
...
-func defaultRepositories(ctx context.Context, getRawDefaultRepos defaultReposFunc, getIndexedRepos indexedReposFunc) ([]*types.Repo, error) {
+func defaultRepositories(ctx context.Context, getRawDefaultRepos defaultReposFunc, getIndexedRepos indexedReposFunc, excludePatterns []string) ([]*types.Repo, error) {
 	// Get the list of default repos from the db.
 	defaultRepos, err := getRawDefaultRepos(ctx)
 	if err != nil {
 		return nil, errors.Wrap(err, "querying db for default repos")
 	}
+
+	// Remove excluded repos
+	if excludePatterns != nil {
```
Comment (rvantonder) [inline cmd/frontend/graphqlbackend/search.go:765]:
```suggestion
	if len(excludePatterns) > 0 {
```

I believe the preferred style is the above, as in https://sourcegraph.com/github.com/sourcegraph/sourcegraph@8f94e730c303ea607053cbe4775f77628b62f07b/-/blob/cmd/frontend/graphqlbackend/search_results.go#L1194. `nil` slices return len 0

File: cmd/frontend/graphqlbackend/search.go [hunk 3]
```diff
@@ -754,12 +754,25 @@ func resolveRepositories(ctx context.Context, op resolveRepoOp) (repoRevisions,
...
+		patterns := `(?i)` + unionRegExps(excludePatterns)
+		filteredRepos := defaultRepos[:0]
+		for _, repo := range defaultRepos {
+			if matched, _ := regexp.Match(patterns, []byte(strings.ToLower(string(repo.Name)))); false == matched {
```
Comment (rvantonder) [inline cmd/frontend/graphqlbackend/search.go:769]: No need to convert to a []byte I think, have a look at https://golang.org/pkg/regexp/#MatchString or other parts of the regexp lib. Also, with `?i` above I'm not sure we need to do `ToLower`, but maybe we are doing this in other places?

Comment (fedealconada) [reply cmd/frontend/graphqlbackend/search.go:769]: Haha, I think you're right. I kind of got "inspired" bye [this](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@457f09b4c52ccde2bdf114f44f9ce77cca2efd63/-/blob/cmd/frontend/db/repos.go#L426:39) line, because that's were you apply the exclusion when NOT on Sourcegraph.com mode, but makes sense what you say.

File: cmd/frontend/graphqlbackend/search.go (hunk 1 above)
Comment (fedealconada) [reply cmd/frontend/graphqlbackend/search.go:767]: Shall I proceed with this change or wait for @unknwon 's opinion?

Comment (unknwon) [reply cmd/frontend/graphqlbackend/search.go:767]: Sorry coming late :D In this case I think what's in here already is better because `filteredRepos` is a subset of `defaultRepos` if I'm not mistaken, and can legitimately reuse the underlying allocations.

Comment (keegancsmith) [reply cmd/frontend/graphqlbackend/search.go:767]: yeah the current version is good.

File: cmd/frontend/graphqlbackend/search.go [hunk 4]
```diff
@@ -754,12 +754,25 @@ func resolveRepositories(ctx context.Context, op resolveRepoOp) (repoRevisions,
...
+func defaultRepositories(ctx context.Context, getRawDefaultRepos defaultReposFunc, getIndexedRepos indexedReposFunc, excludePatterns []string) ([]*types.Repo, error) {
 	// Get the list of default repos from the db.
 	defaultRepos, err := getRawDefaultRepos(ctx)
 	if err != nil {
 		return nil, errors.Wrap(err, "querying db for default repos")
 	}
+
+	// Remove excluded repos
+	if len(excludePatterns) > 0 {
+		patterns := `(?i)` + unionRegExps(excludePatterns)
```
Comment (keegancsmith) [inline cmd/frontend/graphqlbackend/search.go:766]: compile the pattern so it doesn't need to be compiled each time we match against a repo.

**Comment by rvantonder** [comment]
Thank you @fedealconada! Both myself and @mrnugget wanted this to work on Sourcegraph.com. Looking forward to using it 😎 The change should be live in an hour or two.

**Comment by fedealconada** [comment]
Awesome! Glad to hear that @rvantonder :)

**Comment by mrnugget** [comment]
Nice! Thank you @fedealconada!
