### PR TITLE
extensibility: add query transformers to streaming search

### LINKED ISSUE #19237: registerQueryTransformer does not work with searchStreaming
When searchStreaming is enabled, the registerQueryTransformer stops working.

#### Steps to reproduce:

1. Enable an extension which uses `registerQueryTransformer` like `java-imports-search`
2. Enable `searchStreaming` by adding this to your user config `"experimentalFeatures": {"searchStreaming": true}`
3. Search for `java.imports:java.io.IOException`

#### Expected behavior:

- Search query to convert from `java.imports:[package name]` to `^import\\s(?:static\\s)?' + [package name] + '[^\\s]*;$ lang:java patternType:regexp`

#### Actual behavior:

- Search query doesn't change

### PR DESCRIPTION
**Pull request by tjkandala**
Closes #19237.

Adds support for [`QueryTransformer`](https://unpkg.com/sourcegraph@25.3.0/dist/docs/interfaces/_sourcegraph_.querytransformer.html)s (API: [`sourcegraph.search.registerQueryTransformer`](https://unpkg.com/sourcegraph@25.3.0/dist/docs/modules/_sourcegraph_.search.html)) to streaming search. They were integrated with "old" search, but not carried over to streaming search. We waited until extension loading performance improved to restore them in order to limit impact on initial search performance.

Notes: 
- Unlike the original implementation, search queries are not re-computed + executed when new query transformers are registered. In practice, this shouldn't matter as long we wait for the initial set of extensions to load (query transformer extensions should [always be active](https://docs.sourcegraph.com/extensions/authoring/activation#sourcegraph-extension-activation), not waiting for files of a language)
- Performance impact: initial search is blocked on extension activation, imperceptible cost for subsequent searches. The `graphql?Extensions` query is the bottleneck right now, but there are multiple PRs aiming to fix that: [caching](https://github.com/sourcegraph/sourcegraph/pull/24639), [speeding up request](https://github.com/sourcegraph/sourcegraph/pull/24632).

TODO 
- I've modernized our query transformer extensions, but they don't work by default with search V2 (?) since it defaults to literal search. Should we try to check `patternType` and add/replace `patternType` in each extension, or just tell users in READMEs that they should be in regexp mode?  I know that without using the query parser from the main repo, determining `patternType` will be tough/naive (e.g. `"patternType:regexp test" patternType:literal`)

Screenshot of go-imports-search working:
Screenshot from 2021-08-31 18-22-21

### CODE REVIEW

File: client/shared/src/api/client/search.ts [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+const TRANSFORM_QUERY_TIMEOUT = 3000
+
+/**
+ * Executes search query transformers contributed by Sourcegraph extensions.
+ *
+ * Runs one time before completing/yielding value to streaming search.
+ * i.e. extensions that contribute search query transformers that are activated during search
+ * will not cause the query to be re-computed.
+ */
+export function observeTransformedSearchQuery({
```
Comment (tjkandala) [inline client/shared/src/api/client/search.ts:20]: @limitedmage This _only_ works if it completes after one emission. I don't have a problem with this constraint, but I was curious as to why streaming search doesn't work if this doesn't complete

File: client/web/src/search/notebook/index.ts [hunk 2]
```diff
@@ -48,11 +50,15 @@ export interface BlockProps {
...
+export interface BlockDependencies {
+    extensionHostAPI: Promise<Remote<FlatExtensionHostAPI>>
+}
+
 export class Notebook {
     private blocks: Map<string, Block>
     private blockOrder: string[]
 
-    constructor(initializerBlocks: BlockInitializer[]) {
+    constructor(initializerBlocks: BlockInitializer[], private dependencies: BlockDependencies) {
```
Comment (tjkandala) [inline client/web/src/search/notebook/index.ts:61]: @novoselrok wasn't sure what the best way to pass `extensionHostAPI` to `Notebook` was, feel free to suggest/make changes!

File: client/web/src/integration/search.test.ts [hunk 3]
```diff
@@ -523,7 +523,7 @@ describe('Search', () => {
                 waitUntil: 'networkidle0',
             })
             await resetCreateCodeMonitorFeatureTour()
-            await driver.page.waitForSelector('.create-code-monitor-button', { visible: true })
+            await driver.page.waitForSelector('.search-result-match', { visible: true })
```
Comment (tjkandala) [inline client/web/src/integration/search.test.ts:526]: Query transformer call to the extension host added a small delay to the search. We should wait for search results, since that's what the code monitor feature tour depends on to render, rather than the create code monitor button

File: client/shared/src/api/client/search.ts (hunk 1 above)
Comment (limitedmage) [reply client/shared/src/api/client/search.ts:20]: If this is supposed to only emit one value, you should consider using `Promise` instead of `Observable` as the result type.
There's a lot of rxjs magic going on in streaming search processing :/  Maybe switchMap is not the right operator to use in `stream.ts`. If this observable emits multiple values, the HTTP call will be done multiple times.

Comment (tjkandala) [reply client/shared/src/api/client/search.ts:20]: Ideally it could emit multiple values since the initial search may occur before all extensions have registered their query transformers, so it would be good emit again. However, search results never appeared when this `Observable` didn't complete. 

> There's a lot of rxjs magic going on in streaming search processing :/ 

Taking this (and the bug mentioned above) into consideration, I agree that it's safest to use a `Promise` here. Thanks, will refactor!

File: client/shared/src/search/stream.ts [hunk 4]
```diff
@@ -424,41 +424,52 @@ function search({
...
-                        eventSource.close()
-                    }
-                })
-        )
-    )
+    return new Observable<SearchEvent>(observer => {
+        const subscriptions = new Subscription()
+
+        // Call extension-contributed search query transformers
+        transformSearchQuery({ query, extensionHostAPIPromise: extensionHostAPI })
```
Comment (tjkandala) [inline client/shared/src/search/stream.ts:431]: @limitedmage I changed this to a `Promise`. It's still a bit awkward, but it's better IMO than complicating the streaming RxJS logic

File: client/shared/src/api/client/search.ts [hunk 5]
```diff
@@ -12,43 +12,41 @@ const TRANSFORM_QUERY_TIMEOUT = 3000
...
+            // Wait up to 5 seconds and log to console for users to debug slow query transformer extensions
+            timeout(TRANSFORM_QUERY_TIMEOUT),
+            catchError(error => {
+                if (error instanceof TimeoutError) {
+                    console.error(`Extension query transformers took more than ${TRANSFORM_QUERY_TIMEOUT}ms`)
+                }
+                return of(query)
+            })
+        )
+        .toPromise()
```
Comment (tjkandala) [inline client/shared/src/api/client/search.ts:51]: Kept this logic RxJS-based and just called `toPromise()`. <akes most sense since most of the extension host API is as well

File: client/shared/src/search/stream.ts [hunk 6]
```diff
@@ -418,35 +422,52 @@ function search({
...
         const subscriptions = new Subscription()
-        for (const [eventType, handleMessages] of Object.entries(messageHandlers)) {
-            subscriptions.add(
-                (handleMessages as MessageHandler)(eventType as SearchEvent['type'], eventSource, observer)
-            )
-        }
+
+        // Call extension-contributed search query transformers
+        transformSearchQuery({ query, extensionHostAPIPromise: extensionHostAPI })
+            .then(transformedQuery => transformedQuery)
```
Comment (fkling) [inline client/shared/src/search/stream.ts:432]: This seems unnecessary? If not, then adding a comment why this is needed would be helpful.

File: client/shared/src/search/stream.ts [hunk 7]
```diff
@@ -418,35 +422,52 @@ function search({
...
+            .catch(error => {
```
Comment (vovakulikov) [inline client/shared/src/search/stream.ts:433]: Would it be used since `transformSearchQuery` also has `catchError` block? Does RX re-throw error in case if we cast it with `.toPromise ?

File: client/shared/src/api/client/search.ts [hunk 8]
```diff
@@ -0,0 +1,52 @@
...
+    return from(extensionHostAPIPromise)
+        .pipe(
+            switchMap(extensionHostAPI =>
+                // Since we won't re-compute on subsequent extension activation, ensure that
+                // at least the initial set of extensions, which should include always-activated
+                // query-transforming extensions, have been loaded to ensure that the initial
+                // search query is transformed
+                wrapRemoteObservable(extensionHostAPI.haveInitialExtensionsLoaded()).pipe(
+                    filter(haveLoaded => haveLoaded),
+                    first(), // Ensure that it only emits once
```
Comment (vovakulikov) [inline client/shared/src/api/client/search.ts:32]: I think it is true for the `extensionHostAPI.haveInitialExtensionsLoaded` without first operator since we have check for it in `activation.ts`

``` ts
if (state.haveInitialExtensionsLoaded.value === false) {
  state.haveInitialExtensionsLoaded.next(true)
}
```

But I don't mind have it here as well if we want to emphasize that this emits once is something crucial for consumers of that logic.

File: client/shared/src/search/stream.ts (hunk 6 above)
Comment (tjkandala) [reply client/shared/src/search/stream.ts:432]: Not necessary, I'll remove it. Thanks for catching!

File: client/shared/src/search/stream.ts (hunk 7 above)
Comment (tjkandala) [reply client/shared/src/search/stream.ts:433]: It won't with the way it's implemented now, but I didn't want to make assumptions about `transformSearchQuery` behavior from `search` since it could change

File: client/shared/src/api/client/search.ts (hunk 8 above)
Comment (tjkandala) [reply client/shared/src/api/client/search.ts:32]: Yeah, that's basically what it's for, as well as to ensure that the `Observable` completes.  The `Promise` returned by `toPromise` will only resolve when the `Observable` completes.

**Review by vovakulikov — APPROVED** [review]

**Comment by tjkandala** [comment]
@limitedmage Does this look good to merge without all the RxJS?

File: client/shared/src/search/stream.ts [hunk 9]
```diff
@@ -418,35 +422,51 @@ function search({
...
+                // Fallback: use original query
+                console.error('Extension query transformer error:', error)
+                return query
+            })
+            .then(transformedQuery => {
+                const parameters = [
+                    ['q', `${transformedQuery} ${caseSensitive ? 'case:yes' : ''}`],
+                    ['v', version],
+                    ['t', patternType as string],
+                    ['dl', '15'],
```
Comment (limitedmage) [inline client/shared/src/search/stream.ts:442]: What does this parameter do and why change it to 15?

**Review by limitedmage — APPROVED** [review]
LGTM, left one minor comment
