### PR TITLE
Overhaul browser extension styling

### LINKED ISSUE #3071: Bitbucket server hover buttons have inconsistent styling with other Bitbucket buttons
Note how the cursor is different, text is selectable and the focus outline is different.

It looks like instead of using the `aui-button` class, the buttons try to _replicate_ the style through CSS, but fail at it:

image

### LINKED ISSUE #3238: Command palette no longer injected on github.com
Still works on GHE. Looks like GitHub changed its DOM.

### PR DESCRIPTION
**Pull request by felixfbecker**
Overhauls the code-host-specific browser extension styling to not rely on style overrides, but use CSS classes the code host defines. Fixes #3071.
To accomplish this, a couple of shared components had to be changed (e.g. ActionItem) to receive more `className` props, not apply default class names from Bootstrap, support ARIA and change the DOM structure a bit.
The webapp wraps the shared components and applies Bootstrap classnames. 
The additional class props are settable through the CodeHost interface.
I also removed inline styles from the browser extension code.
The command palette now always matches the styling of the code host.

I also noticed GitHub Enterprise was not detected properly, fixed.
Furthermore there were other inconsistencies in code host detection in inject.tsx caused by code duplication.
I also noticed that GitHub command palette was broken, fixes #3238.
I also fixed the weird styling of the "configure sourcegraph" button by removing the inline styles #3067.

Test plan: 
I tested the looks of command palette, hovers, toolbar buttons (normal, pressed, loading states), "view repo" button work and look good in
- [x] Bitbucket
- [x] Gitlab
- [x] GitHub
- [x] GHE
- [x] Phabricator
- [x] Sourcegraph

### CODE REVIEW

File: web/src/components/shared.tsx [hunk 1]
```diff
@@ -0,0 +1,43 @@
+import classNames from 'classnames'
+import React from 'react'
+import { ActionsNavItems, ActionsNavItemsProps } from '../../../shared/src/actions/ActionsNavItems'
+import { CommandListPopoverButton, CommandListPopoverButtonProps } from '../../../shared/src/commandPalette/CommandList'
+import { HoverOverlay, HoverOverlayProps } from '../../../shared/src/hover/HoverOverlay'
+
+// Components from shared with web-styling class names applied
```
Comment (lguychard) [inline web/src/components/shared.tsx]: So should they be in `/shared`?

File: client/browser/src/libs/phabricator/code_intelligence.ts [hunk 2]
```diff
@@ -128,14 +106,22 @@ const diffCodeView: CodeViewSpecWithOutSelector = {
     dom: diffDomFunctions,
     resolveFileInfo: resolveDiffFileInfo,
     adjustPosition,
-    getToolbarMount: createMount(file => {
-        const actionLinks = file.querySelector('.differential-changeset-buttons')
-        if (!actionLinks) {
+    getToolbarMount: codeView => {
+        const className = 'sourcegraph-app-annotator'
+        const existingMount = codeView.querySelector<HTMLElement>('.' + className)
```
[the remark this answers is not in the document]
Comment (felixfbecker) [reply client/browser/src/libs/phabricator/code_intelligence.ts]: I did a code search and it looks like the selector was referenced in an old version of the browser extension but is no longer referenced anywhere.

https://sourcegraph.sgdev.org/search?q=sourcegraph-app-annotator-%28base%7Chead%29

File: web/src/components/shared.tsx (hunk 1 above)
Comment (felixfbecker) [reply web/src/components/shared.tsx]: No, because they _wrap_ components _from_ shared with web-app specific class names. These classes are guaranteed to exist in the webapp, but not in the browser extension, and therefor not in shared/

**Comment by felixfbecker** [comment]
@ryan-blunden this could make a before/after screenshot for the blog post maybe, showing the styling improvements on code hosts (see https://sourcegraph.slack.com/archives/C89KCDK5J/p1554340489010400)
