### PR TITLE
fixes issue where user settings cannot be changed

### LINKED ISSUE #10235: Updating user settings fails on sourcegraph.com
Updating settings, and any extension with toggles that update settings like the Codecov extension, are broken on dotcom with this error when toggling:

image

image

But the GraphQL request is updating user settings, not global settings:

image

image

I would guess this is a bug in the implementation of the new settings-from-file support?

### PR DESCRIPTION
**Pull request by davejrt**
fixes #10235 where users cannot make changes to user settings whilst _SITE_CONFIG env vars are set

### CODE REVIEW

File: cmd/frontend/graphqlbackend/settings.go [hunk 1]
```diff
@@ -58,7 +58,7 @@ var globalSettingsAllowEdits, _ = strconv.ParseBool(env.Get("GLOBAL_SETTINGS_ALL
 // like db.Settings.CreateIfUpToDate, except it handles notifying the
 // query-runner if any saved queries have changed.
 func settingsCreateIfUpToDate(ctx context.Context, subject *settingsSubject, lastID *int32, authorUserID int32, contents string) (latestSetting *api.Settings, err error) {
-	if os.Getenv("GLOBAL_SETTINGS_FILE") != "" && !globalSettingsAllowEdits {
+	if os.Getenv("GLOBAL_SETTINGS_FILE") != "" && subject.site != nil && !globalSettingsAllowEdits {
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/settings.go:61]: qq: Is the field "site" means exactly the _Global Settings_ or could also be something different? If it can only represent _Global Settings_, then should it be renamed to "global" because we also have _Site Configuration_ and this is confusing.

Comment (keegancsmith) [reply cmd/frontend/graphqlbackend/settings.go:61]:
```go
type settingsSubject struct {
	// Exactly 1 of these fields must be set.
	defaultSettings *defaultSettingsResolver
	site            *siteResolver
	org             *OrgResolver
	user            *UserResolver
}
```

checking site sounds correct. Is it possible that defaultSettings would be the subject here? If so, what does that mean and do we need to guard for that?

Comment (slimsag) [reply cmd/frontend/graphqlbackend/settings.go:61]: Yeah, “site” is actually “global settings” here and not “site settings” and is indeed an extremely confusing aspect of this code! It’s actually debt we never addressed from several years ago when we had “site (user) settings” and “site settings” (as it is today) exposes in the app to users — even more confusing!

In any case, something we should fix but not in this PR probably.

I agree defaultSettings is worth considering here, I am not sure about that field.

Comment (davejrt) [reply cmd/frontend/graphqlbackend/settings.go:61]: > I agree defaultSettings is worth considering here, I am not sure about that field.

Is this a change we want to consider in this PR, and if so would someone be willing to pair with me just to help me to understand a little better?

Comment (slimsag) [reply cmd/frontend/graphqlbackend/settings.go:61]: sorry for the delayed response on this; yes it's something we'll want to consider in this PR because I am not exactly sure what this field does. Since it says only one of the fields is present, and there are only three types of user settings in Sourcegraph (site/global -> org -> user) there is a question of "if none of those are present and just defaultSettings is present.. what does that mean?"

To figure out what this means in practice, I did the following (writing as I go):

1. Find references on the type: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ce8b53663352dcd17a842fa7d8a81f30c597a7b2/-/blob/cmd/frontend/graphqlbackend/settings_subject.go#L24:6&tab=references
2. Looking for any places where we generate a `settingsSubject` without one of `site`, `org`, or `user` present
3. I find only three locations: [1](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ce8b53663352dcd17a842fa7d8a81f30c597a7b2/-/blob/cmd/frontend/graphqlbackend/settings_cascade.go#L34:17) [2](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ce8b53663352dcd17a842fa7d8a81f30c597a7b2/-/blob/cmd/frontend/graphqlbackend/default_settings.go#L78:28) [3](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ce8b53663352dcd17a842fa7d8a81f30c597a7b2/-/blob/cmd/frontend/graphqlbackend/default_settings.go#L88:36)
4. Location 1 proves there are instances of this where only `defaultSettings` is present (non-nil) so my question becomes: do we want our code to apply in that situation, or not?
5. Since we are trying to prevent edits to the "site" (global) configuration here, I can't see any reason why we would want to prevent edits to the "default" configuration -- more importantly I don't believe it is possible to make edits to the 'default' configuration. Is it?
6. Not completely positive, so gonna look for the code that makes edits to the configuration which is.. hopefully in the same file? doh of course it is that's what this function we're modifying does :P Ok, so just find references on `settingsCreateIfUpToDate` -- which leads me [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ae53728ff31035fb4a7eabb4342c343dbc1788a2/-/blob/cmd/frontend/graphqlbackend/settings_mutation.go#L164)
7. The subject which *could* have `defaultSettings` seems to come from `r.subject` of `settingsMutation`, so gotta find where that is coming from using [find references again](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ae53728ff31035fb4a7eabb4342c343dbc1788a2/-/blob/cmd/frontend/graphqlbackend/settings_mutation.go#L39:6&tab=references)
8. Looks like we only create that type and pass in the `subject` of interest in a [single location](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ae53728ff31035fb4a7eabb4342c343dbc1788a2/-/blob/cmd/frontend/graphqlbackend/settings_mutation.go#L69-72) and it comes [from here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ae53728ff31035fb4a7eabb4342c343dbc1788a2/-/blob/cmd/frontend/graphqlbackend/settings_mutation.go#L53) and **[that function can only return](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ae53728ff31035fb4a7eabb4342c343dbc1788a2/-/blob/cmd/frontend/graphqlbackend/settings_subject.go#L34-56) setting subjects with `site`, `user`, or `org` present.

So we're good here :) And, conceptually, this does make sense: We have a cascade of settings in which user inherits from org which inherits from global ('site') and if all three of those don't have anything, we use `defaultSettings` -- which you can't edit.

Comment (slimsag) [reply cmd/frontend/graphqlbackend/settings.go:61]: & sorry I couldn't walk you through this live!

**Comment by slimsag** [comment]
You can land your other PR to use this on sourcegraph.com again now
