### PR TITLE
repo-updater: init encryption and decrypt external service on read

### LINKED ISSUE #14644: Impossible to sync repositories on new instance on latest insiders (external service id=1 config error: failed to parse JSON: [InvalidSymbol])
1. Run the latest `sourcegraph/server:insiders` image (make sure it is up to date and starting clean):

```
docker pull sourcegraph/server:insiders
rm -rf ~/.sourcegraph/
docker run --publish 7080:7080 --publish 127.0.0.1:3370:3370 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:insiders
```

2. Go to **Manage repositories** and add **GitHub.com** repositories with the very basic config:

```
{
  "url": "https://github.com",
  "token": "<your token with repo scope>",
  "orgs": []
}
```

3. Repositories do not clone, there is an error in the code host cloud icon indicator (impossible for me to copy the text due to issue #14643):

image

The server logs indicate:

```
23:38:12                          frontend | ✱ Sourcegraph is ready at: http://127.0.0.1:7080
23:55:04                      repo-updater | t=2020-10-12T23:55:04+0000 lvl=warn msg="Handling rate limiter sync" err="getting rate limit configuration: loading service configuration: failed to parse JSON: [InvalidSymbol]"
23:55:04                      repo-updater | t=2020-10-12T23:55:04+0000 lvl=eror msg="Getting normalised URL from service" err="parsing config: failed to parse JSON: [InvalidSymbol]"
23:55:08                      repo-updater | t=2020-10-12T23:55:08+0000 lvl=eror msg="Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe." seriousProblems="[Could not parse config of external service 1: failed to parse JSON: [InvalidSymbol]]"
23:55:13                      repo-updater | t=2020-10-12T23:55:13+0000 lvl=eror msg="Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe." seriousProblems="[Could not parse config of external service 1: failed to parse JSON: [InvalidSymbol]]"
23:55:13                      repo-updater | t=2020-10-12T23:55:13+0000 lvl=warn msg="Marked record as errored" name=repo_sync_worker id=1 err="syncer.sync.sourced: 1 error occurred:\n\t* external service id=1 config error: failed to parse JSON: [InvalidSymbol]\n\n"
23:55:18                      repo-updater | t=2020-10-12T23:55:18+0000 lvl=eror msg="Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe." seriousProblems="[Could not parse config of external service 1: failed to parse JSON: [InvalidSymbol]]"
23:55:23                      repo-updater | t=2020-10-12T23:55:23+0000 lvl=eror msg="Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe." seriousProblems="[Could not parse config of external service 1: failed to parse JSON: [InvalidSymbol]]"
...
```

Connecting to the psql DB shows the config is not the previously entered JSON (encrypted I assume?):

```
sourcegraph=# select kind,display_name,config from external_services;
  kind  | display_name |                                                                                         config                                                                                          
--------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 GITHUB | GitHub       | 98194a$QxF90bX560zokRVhWddUTOBcSLjKy+ZZ5D/1au6heihLLgUCtUVk4iEa7AlUaM0kdeU2sWz9oWtxUD+OV/zTFkparDwjWEtgTe+uouX8Nh9SAH8DHRM26/7OfXtpOu3NQedRqbW72OvhfWafm2SVWXtnM7F28hmgp59ujCRdyClI8Q==
(1 row)
```

### PR DESCRIPTION
**Pull request by unknwon**
Previously, we only init encryption on frontend (for read and write), which breaks all read paths for repo-updater.

Part of #14644

### CODE REVIEW

File: cmd/repo-updater/shared/main.go [hunk 1]
```diff
@@ -49,6 +50,11 @@ func Main(enterpriseInit EnterpriseInit) {
 	tracer.Init()
 	trace.Init(true)
 
+	err := secret.Init()
+	if err != nil {
+		log.Fatalf("Failed to initialize encryption: %v", err)
```
Comment (tsenart) [inline cmd/repo-updater/shared/main.go:55]:
```suggestion
		log.Fatalf("Failed to initialize secrets encryption: %v", err)
```

**Review by tsenart — APPROVED** [review]

**Comment by tsenart** [comment]
One comment: This sort of issue is avoidable if we don't use package level global state like we do here. It's easy to forget to call `$whatever.Init()`, as illustrated by this PR. On the flip side, it's not easy to ignore compiler messages telling you that you're not passing in one of the parameters your thing needs in its constructor — in this case, something like `secrets.Service` or `secrets.Encryptor`.

**Review by asdine — APPROVED** [review]

**Review by ryanslade — APPROVED** [review]

**Comment by unknwon** [comment]
> One comment: This sort of issue is avoidable if we don't use package level global state like we do here. It's easy to forget to call `$whatever.Init()`, as illustrated by this PR. On the flip side, it's not easy to ignore compiler messages telling you that you're not passing in one of the parameters your thing needs in its constructor — in this case, something like `secrets.Service` or `secrets.Encryptor`.

Totally agree with this in general. In this particular case for encryption/decryption, there is no direct call chain from our code because we implement certain interfaces and rely on `database/sql` to call relevant methods. To that end, we could also forget to add such parameters in the constructor without compile errors.

**Comment by tsenart** [comment]
>  there is no direct call chain from our code because we implement certain interfaces and rely on database/sql to call relevant methods

I know there's no direct call chain (i.e. explicit dependency injection) — *that* is the problem.

Imagine you have the `repos.DBStore` extended to take in a `secrets.Encrypter`.

```go
type DBStore struct {
   // other things
   enc *secrets.Encrypter
}

func NewDBStore(db dbutil.DB, enc *secrets.Encrypter) (*DBStore, error) { ... }
```

Then if you forget to initialize and pass in that parameter, your code won't compile.

```go
// In your main function, perhaps.

enc, err := secrets.NewEncrypter(secrets.DefaultKey()) // secrets.DefaultKey reads and returns the private key in the default SOURCEGRAPH_PRIVATE_KEY file path location
if err != nil {
   log.Fatal(err)
}

// Oops, forgot to pass in enc to NewDBStore! Code won't compile :(
store, err := repos.NewDBStore(db)
if err != nil {
   log.Fatal(err)
}
```
