### PR TITLE
authz: fix permissions metrics

### LINKED ISSUE #14894: Permissions Grafana alert should not include public repos
Once private, now public, but the metric gathering method is including it.

Ops log:
```
sg=# select repo_id, updated_at, synced_at  from repo_permissions  order by updated_at limit 10;
 repo_id |          updated_at           |           synced_at
---------+-------------------------------+-------------------------------
      14 | 2020-09-21 13:03:34.550124+00 | 2020-09-21 13:03:34.550124+00

sg=# select name,private from repo where id = 14;
                      name                       | private
-------------------------------------------------+---------
 github.com/sourcegraph/sourcegraph-custom-views | f
```

- Context: https://sourcegraph.slack.com/archives/CHPC7UX16/p1603177885325000?thread_ts=1602726272.261300&cid=CHPC7UX16
- Dashboard: https://k8s.sgdev.org/-/debug/grafana/d/repo-updater/repo-updater

### PR DESCRIPTION
**Pull request by unknwon**
This updates the `PermStore` metrics to take into account whether users and repos have been deleted, made private, etc. 

fixes #14894

### CODE REVIEW

File: enterprise/internal/db/perms_store.go [hunk 1]
```diff
@@ -1531,8 +1531,14 @@ func (s *PermsStore) Metrics(ctx context.Context, staleDur time.Duration) (*Perm
...
-SELECT COUNT(*) FROM user_permissions
-WHERE updated_at <= %s
+SELECT COUNT(*) FROM user_permissions AS perms
+WHERE
+	perms.user_id IN
+		(
+			SELECT users.id FROM users
+			WHERE users.deleted_at IS NULL
+		)
+AND	perms.updated_at <= %s
```
Comment (eseliger) [inline enterprise/internal/db/perms_store.go:1541]: having a tab in between here feels weird
```suggestion
AND perms.updated_at <= %s
```

**Review by eseliger — APPROVED** [review]

**Comment by unknwon** [comment]
Thanks @flying-robot and @eseliger, merging!
