### PR TITLE
search: Fix select for streaming search

### LINKED ISSUE #18291: `select:` on streamed results
`select` currently doesn't work on streamed results. E.g., with `streaming` on, we see content results with `select:file`

Screen Shot 2021-02-15 at 10 21 12 AM

 Some context:

Screen Shot 2021-02-15 at 10 19 17 AM

### PR DESCRIPTION
**Pull request by camdencheek**
This makes select function when streaming search is enabled.

Fixes #18291

### CODE REVIEW

File: cmd/frontend/graphqlbackend/result_deduper.go [hunk 1]
```diff
@@ -53,6 +53,25 @@ func (d *searchResultDeduper) Add(r SearchResultResolver) {
 	}
 }
 
+// Seen returns whether the given url exists for a file type in the deduper without
+// modifying the contents of the deduper
+func (d *searchResultDeduper) Seen(r SearchResultResolver) (ok bool) {
```
Comment (camdencheek) [inline cmd/frontend/graphqlbackend/result_deduper.go:58]: `Seen` makes a comeback!

File: cmd/frontend/graphqlbackend/search_stream.go [hunk 2]
```diff
@@ -67,6 +68,47 @@ func WithLimit(ctx context.Context, parent Streamer, limit int) (context.Context
...
+			default:
+				current = result
+			}
+
+			if current == nil {
+				continue
+			}
+
+			seen := dedup.Seen(current)
+			_, isFileMatch := current.(*FileMatchResolver)
```
Comment (camdencheek) [inline cmd/frontend/graphqlbackend/search_stream.go:97]: Currently sending all file results since currently, deduplication doesn't occur on the line match level.

File: cmd/frontend/graphqlbackend/result_deduper.go (hunk 1 above)
Comment (rvantonder) [reply cmd/frontend/graphqlbackend/result_deduper.go:58]: Well, it's side-effect free this time, so no objections :-) 

nit: I'm partial to returning `ok` rather than naked returns.

**Review by rvantonder — APPROVED** [review]
I shall overlook the lack of tests because we don't have any stream testing infrastructure :-) 

But when that's in place (i.e., before streaming is shippable) we should add tests for this. I suggest making an issue and labeling it as a blocker for shipping streaming.

File: cmd/frontend/graphqlbackend/search_stream.go (hunk 2 above)
Comment (rvantonder) [reply cmd/frontend/graphqlbackend/search_stream.go:97]: I am thinking, instead of doing the `seen && isFileMatch` check here after, we can just do the `Seen` check inside the `case` statement for `FileMatchResolver` above, and then `continue`. Because the check is specific to that branch being executed anyway. WDYT?

If you agree, this is also an argument generally in favor of avoiding the style of https://github.com/sourcegraph/sourcegraph/pull/18293 (even though that PR would still be OK since it doesn't have any result-kind-specific logic yet).

Comment (rvantonder) [reply cmd/frontend/graphqlbackend/search_stream.go:97]: The main reason for my suggestion is that, I had to convince myself that doing the above is OK when the result is just a `file`, and not a line match. I realize it's OK because you do the `seen` check first. Which is why I am suggesting we put the `seen` check inside the branch for the `isFileMatch` case.

Comment (camdencheek) [reply cmd/frontend/graphqlbackend/search_stream.go:97]: I also had that initial impression, but the issue is that we care about the type of `current`, not the type of `result`. So we need to check the type _after_ conversion, making it not possible to do inside the switch statement

**Comment by camdencheek** [comment]
Issue created: #18310

File: cmd/frontend/graphqlbackend/search_stream.go (hunk 2 above)
Comment (rvantonder) [reply cmd/frontend/graphqlbackend/search_stream.go:97]: Ah, yep, you're right, missed that this is `current` and not `result`. Guess there's no way around this... to help the passing reader, I think tacking on a comment somewhere around the code below would be conscientious, something like:

> if the selected value is a file match, add it to the dedupe set unconditionally to ensure that we add line matches for a file

File: cmd/frontend/graphqlbackend/search_stream.go [hunk 3]
```diff
@@ -67,6 +68,51 @@ func WithLimit(ctx context.Context, parent Streamer, limit int) (context.Context
...
+// WithSelect returns a child Stream of parent that runs the select operation
+// on each event, deduplicating where possible.
+func WithSelect(parent Streamer, s filter.SelectPath) Streamer {
+	var mux sync.Mutex
+	dedup := NewDeduper()
+
+	return StreamFunc(func(e SearchEvent) {
+		mux.Lock()
+
+		selected := make([]SearchResultResolver, 0, len(e.Results))
```
Comment (keegancsmith) [inline cmd/frontend/graphqlbackend/search_stream.go:80]: why the copy? Can't we just mutate e.Results? eg `selected := e.Results[:0]`. I suppose the extra memory is minor so we might as well copy?

**Review by keegancsmith — APPROVED** [review]

File: cmd/frontend/graphqlbackend/search_stream.go (hunk 3 above)
Comment (camdencheek) [reply cmd/frontend/graphqlbackend/search_stream.go:80]: So, my first go at it, I was modifying `e.Results` in place (e.g. `e.Results = append(e.Results[:i], e.Results[i+1:]...)`), but that added more complexity than I felt the allocation was worth. Plus, a ton of element copies. 

I honestly have never thought about just creating a new slice with the same backing array. It never occured to me that I could still use `e.Results` in that case. Making the change 👍

File: cmd/frontend/graphqlbackend/search_stream.go [hunk 4]
```diff
@@ -67,6 +68,53 @@ func WithLimit(ctx context.Context, parent Streamer, limit int) (context.Context
...
+				continue
+			}
+
+			dedup.Add(current)
+			selected = append(selected, current)
+		}
+		e.Results = selected
+
+		mux.Unlock()
+		if parent != nil {
```
Comment (camdencheek) [inline cmd/frontend/graphqlbackend/search_stream.go:112]: @keegancsmith Adding this nil check seemed to fix it, but I was getting segmentation faults during suggestions if I didn't have this check. I'd expected `parent` to always be callable -- is that not the case?

Comment (camdencheek) [reply cmd/frontend/graphqlbackend/search_stream.go:112]: (reproducible before this change by making a search query with no results)
