### PR TITLE
gitserver: fix changeset publication

### LINKED ISSUE #43821: batches: publishing changesets is broken by #43421
#43421 added Git command filtering to the Batch Changes code path that publishes changesets. Unfortunately, this PR did not add all the various commands that are used when publishing a changeset, and sends the commands to `isAllowedGitCmd` incorrectly, so `gitserver` is currently unable to initialise a repository, among other things.

### PR DESCRIPTION
**Pull request by LawnGnome**
This PR makes two fixes to allow changesets to be published once more after the changes in #43421 broke publication. The individual commit messages include more context on each change.

Fixes #43821.

## Test plan

Tested the full publication path locally; updated the `isAllowedGitCmd` tests to cover the commands Batch Changes requires (taken from a local log and mildly anonymised).

### CODE REVIEW

File: internal/gitserver/gitdomain/exec.go [hunk 1]
```diff
@@ -105,10 +112,15 @@ func isAllowedDiffArg(arg string) bool {
 func isAllowedGitArg(allowedArgs []string, arg string) bool {
 	// Split the arg at the first equal sign and check the LHS against the allowlist args.
 	splitArg := strings.Split(arg, "=")[0]
+
+	// We use -- to specify the end of command options.
+	// See: https://unix.stackexchange.com/a/11382/214756.
+	if splitArg == "--" {
+		return true
+	}
```
Comment (LawnGnome) [inline internal/gitserver/gitdomain/exec.go:120]: `--` wouldn't be special cased if there were no allowed arguments for a command.

**Review by eseliger — APPROVED** [review]
damn, good find!

**Review by BolajiOlajide — APPROVED** [review]

**Review by ryanslade — APPROVED** [review]

**Review by evict — APPROVED** [review]
