### PR TITLE
search: fix regression where search result highlighting is not bailed out after 3s

### LINKED ISSUE #4268: webapp regression: highlighted search result snippets are not bailed out after a few seconds as they should be
It used to be the case that if you ran a search and it hit very large files the syntax highlighter could not handle that we would bail out after a few seconds and display a plaintext version.

Instead, today, we appear to have a regression in which these files take as long as they please to highlight -- making some search result snippets not load for over 30s.

Reported by https://app.hubspot.com/contacts/2762526/company/407948923

### PR DESCRIPTION
**Pull request by slimsag**
Prior to this change there was a major regression in which we would disable the
syntax highlighting timeout outright. This is despite the fact that this should
only ever be done when the user has communicated an intent to wait longer for
search results.

This regression meant that when a search turned up files that the syntax highlighter could
not highlight quickly, we would just wait for them until it finished. In one customer
environment I observed search results taking 30s+ to load due to this because it had the
added negative consequence of us not canceling those poorly performing requests which led to
syntect_server trying to perform tons of CPU-intensive requests which harmed other requests
it was handling.

After this change, we are properly bailing out once again after the syntax highlighting
timeout.

This means that in this bad case you are waiting 3s then getting plaintext results instead of
waiting 30s+ for highlighting.

Fixes #4268

Test plan: Manually tested using #4364, in the future we will e2e test it.

### CODE REVIEW

File: shared/src/components/CodeExcerpt.tsx [hunk 1]
```diff
@@ -66,7 +66,7 @@ export class CodeExcerpt extends React.PureComponent<Props, State> {
                             commitID,
                             filePath,
                             isLightTheme,
-                            disableTimeout: true,
+                            disableTimeout: false,
```
Comment (felixfbecker) [inline shared/src/components/CodeExcerpt.tsx]: Please add a unit test assertion for this to prevent a regression - CodeExcerpt has unit tests, and this function is injected through props, so this function can be a sinon spy and be asserted to have been called with `disableTimeout: false`

Comment (slimsag) [reply shared/src/components/CodeExcerpt.tsx]: Will do tomorrow. Once I address that should I wait for your approval?

Comment (felixfbecker) [reply shared/src/components/CodeExcerpt.tsx]: Yes please

**Comment by slimsag** [comment]
@felixfbecker PTAL

File: shared/src/components/CodeExcerpt.test.tsx [hunk 2]
```diff
@@ -104,4 +107,24 @@ describe('CodeExcerpt', () => {
...
+        const fetchHighlightedFileLines = sinon.fake.returns(of(HIGHLIGHTED_FILE_LINES))
+        const highlightRange = [{ line: 12, character: 7, highlightLength: 4 }]
+        render(
+            <CodeExcerpt
+                {...defaultProps}
+                highlightRanges={highlightRange}
+                fetchHighlightedFileLines={fetchHighlightedFileLines}
+            />
+        )
+        expect(fetchHighlightedFileLines.calledOnce).toBe(true)
```
Comment (felixfbecker) [inline shared/src/components/CodeExcerpt.test.tsx]:
```suggestion
        sinon.assert.calledOnce(fetchHighlightedFileLines)
```

This gives a better assertion message:
"Expected function fetchHighlightedFileLines to be called once, but was called thrice"
vs
"Expected false to be true"

File: shared/src/components/CodeExcerpt.test.tsx [hunk 3]
```diff
@@ -104,4 +107,24 @@ describe('CodeExcerpt', () => {
...
     })
+
+    it('does not disable the highlighting timeout', () => {
+        /*
+            Because disabling the timeout should only ever be done in response
+            to the user asking us to do so, something that we do not do for
+            code excerpts because falling back to plaintext rendering is most
+            ideal.
+        */
+        const fetchHighlightedFileLines = sinon.fake.returns(of(HIGHLIGHTED_FILE_LINES))
```
Comment (felixfbecker) [inline shared/src/components/CodeExcerpt.test.tsx]:
```suggestion
        const fetchHighlightedFileLines = sinon.spy(() => of(HIGHLIGHTED_FILE_LINES))
```
This is more type safe (the spy actually encodes the parameter and return types, the fake API can't do that afaik)

File: shared/src/components/CodeExcerpt.test.tsx [hunk 4]
```diff
@@ -104,4 +107,24 @@ describe('CodeExcerpt', () => {
...
+        const highlightRange = [{ line: 12, character: 7, highlightLength: 4 }]
+        render(
+            <CodeExcerpt
+                {...defaultProps}
+                highlightRanges={highlightRange}
+                fetchHighlightedFileLines={fetchHighlightedFileLines}
+            />
+        )
+        expect(fetchHighlightedFileLines.calledOnce).toBe(true)
+        expect(fetchHighlightedFileLines.args[0][0].disableTimeout === false).toBe(true)
```
Comment (felixfbecker) [inline shared/src/components/CodeExcerpt.test.tsx]:
```suggestion
        sinon.assert.calledWithMatch(fetchHighlightedFileLines, { disableTimeout: false })
```

(OTTOMH, docs are here: https://sinonjs.org/releases/latest/assertions/)

**Comment by slimsag** [comment]
@felixfbecker thanks for the help! good to merge once I address changelog conflict and CI passes?
