### PR TITLE
Sync GitHub internal repos during user perms sync

### LINKED ISSUE #56648: Sourcegraph Doesn't Respect Repo Visibility Rules For GitHub Enterprise
- **Sourcegraph version:** 5.1.8
- **Platform information:** All Sourcegraph Platforms 

#### Steps to reproduce:

1. Generate a personal access token for a user in GitHub Enterprise Server that is an Enterprise Member as defined [here](https://docs.github.com/en/enterprise-cloud@latest/admin/managing-accounts-and-repositories/managing-users-in-your-enterprise/roles-in-an-enterprise#enterprise-members) 
2. Use the personal access token to create a code host connection in Sourcegraph. 
3. Choose the "affiliated" repositoryQuery to specify what repositories the user has access to.

#### Expected behavior:

The use of the personal access token of an Enterprise Member as well as using the `repositoryQuery` key and `affiliated` value would pull in _all_ of the public repositories in a GitHub Enterprise Server  instance (regardless if the user belonged to an organization) as well as _all_ of the internal repositories in addition to the private repositories it should have access to. This behavior is based on the repo visibility rules expressed by GitHub Enterprise [here](https://docs.github.com/en/enterprise-server@3.10/repositories/creating-and-managing-repositories/about-repositories#about-repository-visibility).

#### Actual behavior:
Sourcegraph currently only pulls in the public repos on the instance that do not belong to an organization, public repos that belong  to the organizations that the user is in and private repositories that the user has been given explicit access to.

/cc @sourcegraph/source

### PR DESCRIPTION
**Pull request by pjlast**
Closes #56648 

Sourcegraph now explicitly fetches internal repositories for organizations a user belongs to. This used to be only done when groups caching is enabled, but it leads to a lot of confusion for customers.

This may increase the number of requests made by user permission syncs. If that is the case, groups caching should be enabled.

As part of this work I decided the refactor the GitHub user permissions fetching code, which was very contrived. It's a lot easier to reason about what should be happening now.

## Test plan

VCR tests updated to account for extra API calls. Local validations done as well.

### CODE REVIEW

File: internal/authz/providers/github/github.go [hunk 1]
```diff
@@ -313,7 +321,60 @@ func (p *Provider) fetchUserPermsByToken(ctx context.Context, accountID extsvc.A
...
+	// If caching is enabled, then the internal repositories will be fetched as part of the group sync.
+	if p.groupsCache == nil {
+		internalRepos, err := getAllAuthenticatedUserInternalRepositories(ctx, cli)
+		for _, r := range internalRepos {
+			userRepos.Add(extsvc.RepoID(r.ID))
+		}
+		if err != nil {
+			return &authz.ExternalUserPermissions{Exacts: userRepos.Values()}, err
+		}
+	} else {
```
Comment (pjlast) [inline internal/authz/providers/github/github.go:366]: This is the part that is functionally different that we didn't do before.

**Review by unknwon — APPROVED** [review]
👍 (not an authoritative approval)

**Review by eseliger — APPROVED** [review]
By no means am I an expert in the authz stuff yet, but the code change makes logical sense to me .. hope that is enough 😆 

Approving, but as we talked about today, would be great to also have the toggle to disable this changed behavior.
