### PR TITLE
[a11y] notepad: screen reader fixes

### LINKED ISSUE #36510: [Accessibility]: Notepad screen reader issues
### Audit type

Screen reader navigation

### User journey audit issue

https://github.com/sourcegraph/sourcegraph/issues/34198

### Problem description

- On VoiceOver on macOS, When in the listbox in the notepad, can't use Ctrl+Opt+Left/right to move between components inside the listbox item. Only up/down arrow keys work and they move focus between the lines, but it's impossible to focus the buttons inside the listbox items.
- Confirmation message not read/focused when clicking on "Remove all notes" button.

### Expected behavior

VoiceOver navigation works as expected and confirmation message is read to users and confirm button is focused after clicking the remove button.

### Additional details

@fkling Let me know if you can help fix this. If you still don't have a Mac device where you can run voiceover, we can reassign.

### Assigning labels

- [X] Please give this issue an estimate by applying a label like `estimate/Xd`, where X is the estimated number of days it will take to complete.
- [X] If this issue is specific to a specific Sourcegraph product, please assign the appropriate team label to this issue.
- [ ] If this issue will require input from designers in order to complete, please assign the label `needs-design`.
- [ ] If you are confident that this issue should be fixed by GitStart, please assign the label `gitstart`.

### Owner

This issue will be fixed by my team, I have assigned a relevant member to it, or I will do so in the near future.

### PR DESCRIPTION
**Pull request by limitedmage**
Closes #36510

- Notepad's "delete all" confirmation is now read and focus is managed correctly when closing it.
- Notepad no longer uses the "listbox/option" roles for the list. Even though these roles makes sense, because of the nested buttons, this is not supported (you cannot have nested interactive roles; the screen reader will ignore the nested ones). I added some extra `sr-only` text and labels to tell users how the component works. I also changed the list from `ul` to `ol` since it is more semantic (the notepad items have an order to them that matters).
- Also changed the delete button inside a notepad entry to only delete that entry, instead of all selected entries, since I think this didn't make sense. (Maybe the delete button on the bottom should delete only selected entries instead of everything?)

https://user-images.githubusercontent.com/206864/196499407-1c580c8b-4cb6-4e44-8c88-2e5f8dc86d7b.mp4

## Test plan

- Updated existing unit tests 
- Manually tested

## App preview:

- [Web](https://sg-web-jp-notepadscreenreader.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-wssnzsdqgt.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.01% (+0.29 kb) | 0.00% (+0.29 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/jp/notepadscreenreader/compare-report.html;tab=live_object) for a full comparison between the commits c608122 and 1b18fbe or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

File: client/web/src/search/Notepad.tsx [hunk 1]
```diff
@@ -336,6 +336,22 @@ export const Notepad: React.FunctionComponent<React.PropsWithChildren<NotepadPro
         }
     }, [confirmRemoveAll])
 
+    // Focus the remove all button when the remove all confirmation box is hidden.
+    // If the remove all button is now diabled (because there are no entries left),
```
Comment (fkling) [inline client/web/src/search/Notepad.tsx:340]:
```suggestion
    // If the remove all button is now disabled (because there are no entries left),
```

File: client/web/src/search/Notepad.tsx [hunk 2]
```diff
@@ -594,6 +615,7 @@ const NotepadEntryComponent: React.FunctionComponent<React.PropsWithChildren<Not
     return (
         <div className={classNames(styles.entry, { [styles.selected]: selected })}>
             <div className="d-flex">
+                <span className="sr-only">{selected ? 'Selected, ' : ''}</span>
```
Comment (fkling) [inline client/web/src/search/Notepad.tsx:618]: Do we need this if the `aria-label` on the `li` parent already contains `"Selected, "` ?

File: package.json [hunk 3]
```diff
@@ -26,7 +26,7 @@
     "watch-web": "yarn workspace @sourcegraph/web run watch",
     "generate": "gulp generate",
     "watch-generate": "gulp watchGenerate",
-    "test": "jest --testPathIgnorePatterns end-to-end regression integration storybook \"/out/.*test.js\"",
+    "test": "jest --testPathIgnorePatterns end-to-end regression integration storybook \"/out/.*test.js\" \"/out/.*test.d.ts\"",
```
Comment (fkling) [inline package.json:29]: What's this for?

**Review by fkling — APPROVED** [review]

File: package.json (hunk 3 above)
Comment (limitedmage) [reply package.json:29]: This is because locally running `yarn test` after running `yarn build-web` fails because some observability files are created in an output directory.  So I'm excluding them from local test runs. This is not related to notepad, just fixing a constant annoyance for me 😅

image

File: client/web/src/search/Notepad.tsx (hunk 2 above)
Comment (limitedmage) [reply client/web/src/search/Notepad.tsx:618]: I think so, so that users that are navigating element-by-element can still know that it's selected.
