### PR TITLE
frontend: Enforce upgrade policy

### LINKED ISSUE #7702: Prevent upgrading more than one minor version at a time
I have seen two customers in the past day incorrectly upgrade more than two minor versions at one time, leading to migration failures taking down their instance.

This is a failure on our part, because nobody should have to be realizing this on their own (or through our (missing!) documentation #7699 ): If you upgrade Sourcegraph more than two minor versions at once and we require you don't, you should be getting an obvious error explaining you need to do it in increments.

### PR DESCRIPTION
**Pull request by tsenart**
This commit changes the frontend to enforce our upgrade policy on
startup. A `versions` table is introduced, where the latest seen version
of a service in the Sourcegraph architecture is stored.

For the frontend, this is done on startup, before database migrations
are run. If an admin violates our upgrade policy, the frontend will
shutdown with a descriptive error, pointing to our documentation.

In a future PR, we'll ensure our upgrade policy is respected by
other services. This will be done by sending the service's version
along to the frontend on calls to `api.InternalClient.WaitForFrontend`
during a service's startup procedure, and having the frontend respond
with an error if the upgrade is invalid, which the service should handle
by logging and shutting itself down.

Fixes #7702
Follow-up in #8382

### CODE REVIEW

File: cmd/frontend/internal/cli/serve_cmd.go [hunk 1]
```diff
@@ -79,15 +81,42 @@ func defaultExternalURL(nginxAddr, httpAddr string) *url.URL {
...
+// version of the frontend in our versions table.
+func InitDB() error {
+	if err := dbconn.ConnectToDB(""); err != nil {
+		return err
+	}
+
+	ctx := context.Background()
+	migrate := true
+
+	for {
```
Comment (tsenart) [inline cmd/frontend/internal/cli/serve_cmd.go]: We need this loop so that we handle the missing `versions` table, which would be added by running the migrations. Once we detect that it's missing, we run the migrations and try to update the version again.

File: cmd/frontend/backend/versions.go [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+		"https://docs.sourcegraph.com/#upgrading-sourcegraph",
+	)
+
+}
+
+// UpdateServiceVersion updates the latest version for the given Sourcegraph
+// service. It enforces our documented upgrade policy.
+// https://docs.sourcegraph.com/#upgrading-sourcegraph
+func UpdateServiceVersion(ctx context.Context, service, version string) error {
+	latest, err := semver.NewVersion(version)
```
Comment (unknwon) [inline cmd/frontend/backend/versions.go]: nit:
```suggestion
	current, err := semver.NewVersion(version)
```

It's not necessarily true that a customer is always performing upgrade to the latest version.

File: cmd/frontend/backend/versions_test.go [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+	},
+	} {
+		t.Run(tc.name, func(t *testing.T) {
+			previous, _ := semver.NewVersion(tc.previous)
+			latest, _ := semver.NewVersion(tc.latest)
+
+			if got := IsValidUpgrade(previous, latest); got != tc.want {
+				t.Errorf(
+					"IsValidUpgrade(previous: %s, latest: %s) = %t, want %t",
+					tc.latest,
```
Comment (unknwon) [inline cmd/frontend/backend/versions_test.go]: typo?
```suggestion
					tc.previous,
```

File: cmd/frontend/backend/versions_test.go [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+		name     string
+		previous string
+		latest   string
+		want     bool
+	}{{
+		name:     "no versions",
+		previous: "",
+		latest:   "",
+		want:     true,
+	}, {
```
Comment (unknwon) [inline cmd/frontend/backend/versions_test.go]: I like this style! It saves a lot of lines

File: internal/db/dbutil/dbutil.go [hunk 5]
```diff
@@ -12,6 +12,7 @@ import (
 	"time"
 
 	// Register driver
+	"github.com/lib/pq"
 	_ "github.com/lib/pq"
```
Comment (unknwon) [inline internal/db/dbutil/dbutil.go]: Looks like one of them should be removed.

File: cmd/frontend/internal/cli/serve_cmd.go (hunk 1 above)
Comment (unknwon) [reply cmd/frontend/internal/cli/serve_cmd.go]: Would be nice to put your comment in the code.

File: cmd/frontend/backend/versions.go [hunk 6]
```diff
@@ -0,0 +1,96 @@
...
+// IsValidUpgrade returns true if the given previous and
+// latest versions comply with our documented upgrade policy.
+//
+// https://docs.sourcegraph.com/#upgrading-sourcegraph
+func IsValidUpgrade(previous, latest *semver.Version) bool {
+	return previous == nil || previous.Equal(latest) ||
+		(previous.Major() == latest.Major() &&
+			previous.Minor() == latest.Minor()-1) ||
+		(latest.Major() == previous.Major()+1 &&
+			latest.Minor() == 0)
```
Comment (keegancsmith) [inline cmd/frontend/backend/versions.go]: this may be too strict? IE maybe we should allow old versions to be running. This would then allow us to rollback. Right now to rollback (not an uncommon thing admins do in the face of issues) would require updates to the version table as well.

File: cmd/frontend/backend/versions.go [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+UPDATE SET (version, updated_at) =
+	(excluded.version, excluded.updated_at)
+WHERE version = %s`
+
+// IsValidUpgrade returns true if the given previous and
+// latest versions comply with our documented upgrade policy.
+//
+// https://docs.sourcegraph.com/#upgrading-sourcegraph
+func IsValidUpgrade(previous, latest *semver.Version) bool {
+	return previous == nil || previous.Equal(latest) ||
```
Comment (keegancsmith) [inline cmd/frontend/backend/versions.go]: previous.Equal doesn't ignore patch versions. Which means this would fail when upgrading a patch version if I am not mistaken? Should be easy to extend your test cases for this.

**Comment by tsenart** [comment]
> One question: How do we deal with version roll back? Should we prevent that in hard way (i.e. fail to start as if it violates the upgrade policy) and make the admin contact us for support?

That's a great point! I think we should allow all roll-backs. Will make the change.

**Comment by tsenart** [comment]
> I'm still not 100% convinced that being strict on all services is the best thing, vs just enforcing that when there is an upgrade it only jumps 1 minor version.

This PR only affects frontend. I added support for all downgrades and roll-backs. Are your concerns addressed?

File: cmd/frontend/backend/versions.go [hunk 8]
```diff
@@ -0,0 +1,105 @@
...
+
+		if !IsValidUpgrade(previous, latest) {
+			return &UpgradeError{Service: service, Previous: previous, Latest: latest}
+		}
+
+		q = sqlf.Sprintf(
+			upsertVersionQuery,
+			service,
+			latest.String(),
+			previous.String(),
```
Comment (unknwon) [inline cmd/frontend/backend/versions.go]: This is causing panic when it is `nil` (i.e. no previous version): https://buildkite.com/sourcegraph/sourcegraph/builds/55986#9738a4dd-d544-4c1a-879f-0f31ff9fd8aa/72-85

**Comment by slimsag** [comment]
Apologies for the major delay in my review -- this looks great! In specific the described behavior LGTM, and the code also LGTM from a quick glance (but I didn't dive into it too deeply).

Was there an issue with the implementation given Keegan reverted above, or was that revert not from `master`?

**Comment by unknwon** [comment]
@slimsag I think the commit is not from `master` branch. FYI , this was the commit to fix the CI failure: https://github.com/sourcegraph/sourcegraph/commit/0adf4e2427224526f9cbed901327963752fc1981

**Comment by keegancsmith** [comment]
Yeah that revert was a PR that ended up not being merged. The revert was due to a flakey tests, not the functionality. However, the test was addressed before needing to merge the revert.
