### PR TITLE
Fix incorrect license expiration warning

### LINKED ISSUE #7350: License expiration shows incorrect warning
On an instance with a 2-month-expired license (just booted up an old laptop with an old `dev-private`), I see:

image

"will expire in 2 months" in the global alert, but the license component says "expires 2 months ago". The global alert is wrong.

### PR DESCRIPTION
**Pull request by lguychard**
Fixes #7350

Now displays a different wording depending on whether the license will expire soon, or is already expired:

image
image

### CODE REVIEW

File: web/src/site/LicenseExpirationAlert.tsx [hunk 1]
```diff
@@ -18,7 +19,12 @@ export const LicenseExpirationAlert: React.FunctionComponent<{
         className={`alert alert-warning align-items-center ${className}`}
     >
         <WarningIcon className="icon-inline mr-2 flex-shrink-0" />
-        Your Sourcegraph license will expire in {formatDistanceStrict(expiresAt, Date.now())}.&nbsp;
+        Your Sourcegraph license{' '}
```
Comment (sqs) [inline web/src/site/LicenseExpirationAlert.tsx]: This component is a great candidate for a new test

File: web/src/site/LicenseExpirationAlert.tsx [hunk 2]
```diff
@@ -18,7 +19,12 @@ export const LicenseExpirationAlert: React.FunctionComponent<{
...
+        {isProductLicenseExpired(expiresAt)
+            ? 'expired ' + formatRelativeExpirationDate(expiresAt) // 'Expired two months ago'
+            : 'will expire in ' + formatDistanceStrict(expiresAt, Date.now()) // 'Will expire in two months'
```
Comment (eseliger) [inline web/src/site/LicenseExpirationAlert.tsx]: I just built something very similar using date-fns, which we already have in the bundle:
```ts
<small className="ml-2 text-muted" data-tooltip={node.createdAt}>
	{formatDistance(parseISO(node.createdAt), new Date())} ago
</small>
```
do you think that would work here as well? It would save us bundling moment, which isn't particularly small and somewhat redundant to date-fns 🙂

Comment (eseliger) [reply web/src/site/LicenseExpirationAlert.tsx]: ah nvm I was biased by the `package.json` diff 😬 in the tests, you can use `addDays(new Date(), 3)` though to not have to use moment :)

Comment (lguychard) [reply web/src/site/LicenseExpirationAlert.tsx]: Just changed it :)
