### PR TITLE
Fix race conditions in CloseCampaign by blocking

### LINKED ISSUE #12827: Unable to enqueue changeset to be reconciled while it's being reconciled
### Status quo

In order to enqueue a `changeset` to be picked up by the reconciler, we set its `reconciler_state` column to `queued`.

The reconciler then dequeues the changeset by setting the `reconciler_state` to `processing`:

https://github.com/sourcegraph/sourcegraph/blob/74ad60c5b67a800804279e036f8c849e14fc02c9/internal/workerutil/dbworker/store/store.go#L298-L315

Once it's done, it sets the `state` to `completed` or `errored`.

### Problem

We want to move the closing of changesets into the background (https://github.com/sourcegraph/sourcegraph/issues/12644) by setting a "please close this" boolean on the `changeset` and enqueuing the changeset so that the reconciler picks it up and closes it.

We also want to allow this _while a `changeset` is being processed by the reconciler_, because the reconciler could — in the future — always be processing a changeset and that shouldn't stop the user from marking a changeset as "to be closed". See https://github.com/sourcegraph/sourcegraph/pull/12782#issue-463915652 for more context.

*But here is the problem*: if we enqueue a changeset while it's being processed by setting `reconciler_state = 'queued'` then that value will simply be overwritten by the reconciler once it's done with the current processing.

In other words: we can't enqueue a changeset to be processed again while it's being processed.

That's due to the architecture of the underlying `dbworker/store`, which assumes that every job is a one-off job that ends in a terminal state and is not re-enqueued again.

### Possible Solution 1

We split the `reconciler_state` up into two fields:

- `enqueued: bool`
- `processing_state: string`

In order to enqueue a changeset, we set `enqueued = TRUE`.

We then need to change the `dbworker/store` so that the `selectCandidateQuery` allows us to set these fields, like this (see the `selectCandidateQuery` above):

```sql

WITH candidate AS (
  SELECT {id} FROM %s
  WHERE
    -- This is new
    ({state} = 'queued' OR (enqueued IS TRUE)) AND
    ({process_after} IS NULL OR {process_after} <= NOW())
    %s
  ORDER BY %s
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
UPDATE %s
SET
  -- This is new
  enqueued = FALSE,
  {state} = 'processing',
  {started_at} = NOW()
WHERE {id} IN (SELECT {id} FROM candidate)
RETURNING {id}
```

We could then compute the `Changeset.ReconcilerState()` by looking at both fields.

And we could always set the `enqueued`, even while a changeset is being processed, because the field acts like a dirty bit that's only cleared when dequeued. If we set it to `true` again, while it's being processed, the reconciler will pick it up again after it's done processing.

### Possible Solution 2

We could switch away from using the `changesets` table as re-usable jobs that are re-executed again and again and instead create a new `reconciler_job` whenever we want the reconciler to look at the changeset.

That would require another table, of course, and that we need to fetch the jobs whenever we want to check the status of a changeset. We could make that easier with a database view, though, in which we always join the changesets against the `reconciler_jobs`.

But then we'd have the problem that we create a new job while the old one is being processed and both would try to modify the changeset, so we'd need to lock the changeset.

---

I'm leaning towards solution 1.

### PR DESCRIPTION
**Pull request by mrnugget**
This is one of the PRs to fix #12827.

Yesterday [we found out][1] that there were race conditions in the old `CloseCampaign` code:

- Changesets could switch from "queued" to "processing" between our "count all processing changesets" call and the "return if count is > 0" check.
- Changesets could switch from "unpublished" to "published & open" after we did the "list all open changesets" call

On top of that the `UpdateChangeset` calls would block if a changeset was processing.

So what we do now instead is cleaner and more consistent.

We mark _all_ changesets associated with the campaign as to-be-closed and enqueue them. That avoids the race conditions of changesets currently being published while we try to close the campaign.

And it works because the set of changesets doesn't change while we do this, since we close the campaign in a transaction and hold the row lock on it, meaning that another user cannot `ApplyCampaign` while we're in this code path and add/remove changesets. 

Each `UpdateChangeset` call will then block again, if one of the changesets is currently being processed. That's good, because it leaves us in a consistent state where we don't overwrite data the reconciler wants to write. 

That means that the `CloseCampaign` mutation might block until all currently processing changesets are done being processed, *if* there are processing changesets.

We lose the "cannot close currently processing campaign" error, but that wouldn't work anyway with the new model. This here is far more consistent.

~We just need to make sure that we show a spinner on the "close campaign" confirmation button, maybe.~ We do have a spinner.

[1]: https://github.com/sourcegraph/sourcegraph/issues/12827#issuecomment-684936536

### CODE REVIEW

File: enterprise/internal/campaigns/service.go [hunk 1]
```diff
@@ -281,76 +277,70 @@ func (s *Service) CloseCampaign(ctx context.Context, id int64, closeChangesets b
...
+	tx, err := s.store.Transact(ctx)
+	if err != nil {
+		return nil, err
+	}
+	defer func() { err = tx.Done(err) }()
 
-		if !closeChangesets {
-			return nil
-		}
+	campaign.ClosedAt = time.Now().UTC()
```
Comment (eseliger) [inline enterprise/internal/campaigns/service.go:299]: should this use the store clock, so tests are easier to write?

File: enterprise/internal/campaigns/service.go [hunk 2]
```diff
@@ -281,76 +277,70 @@ func (s *Service) CloseCampaign(ctx context.Context, id int64, closeChangesets b
...
 
-		return nil
+	// Since the UpdateChangeset call might block if a changeset is
+	// currently being processes, we update them concurrently to avoid
+	// being slowed down by one of the first changesets in the slice being
+	// processed.
+	results := make(chan error)
+	for _, c := range cs {
+		go enqueueClose(tx, c, results)
 	}
```
Comment (eseliger) [inline enterprise/internal/campaigns/service.go:333]: to protect us from overloading, I think we should add a waitgroup here to only run a limited number of them in parallel

Comment (eseliger) [reply enterprise/internal/campaigns/service.go:333]: or, just add a function to the store `UpdateChangesets`

```go
type UpdateChangesetsOpts {
// Fields that should be updatable, for now
Closing *bool
ReconcilerState *campaigns.ReconcilerState

ChangesetIDs []int64
}

func (s *Store) UpdateChangesets(ctx context.Context, opts UpdateChangesetsOpts)
```
That would combine all the error handling and probably be even faster than iterating over and calling out to PG a couple hundred times? Maybe I'm missing something here that prevents us from doing that though

File: enterprise/internal/campaigns/service.go [hunk 3]
```diff
@@ -281,76 +277,70 @@ func (s *Service) CloseCampaign(ctx context.Context, id int64, closeChangesets b
...
-			}
-		}
+		err := tx.UpdateChangeset(ctx, c)
+		ch <- err
+	}
 
-		return nil
+	// Since the UpdateChangeset call might block if a changeset is
+	// currently being processes, we update them concurrently to avoid
+	// being slowed down by one of the first changesets in the slice being
```
Comment (eseliger) [inline enterprise/internal/campaigns/service.go:328]: I am a bit worried that this still might make the `closeCampaign` mutation call become very lengthy, it's probably unexpected if a request takes 20+s, I might be tempted to reload, try again and so

**Review by eseliger — COMMENTED** [review]
I like the approach, but have somewhat mixed feelings about the close mutation becoming potentially slow again, let's add to today's sync agenda

File: enterprise/internal/campaigns/service.go (hunk 1 above)
Comment (mrnugget) [reply enterprise/internal/campaigns/service.go:299]: Yeah, good idea!

File: enterprise/internal/campaigns/service.go (hunk 3 above)
Comment (mrnugget) [reply enterprise/internal/campaigns/service.go:328]: Well, we could show a warning in the UI if there are any processing changesets, right?

That's why I wrote in the PR description:

> We just need to make sure that we show a spinner on the "close campaign" confirmation button, maybe.

If I see "Warning: There are still changesets processing, result might be inconsistent" in the UI before I click the button, but then go ahead and click the button and get a spinner, I wouldn't be surprised.

File: enterprise/internal/campaigns/service.go (hunk 2 above)
Comment (mrnugget) [reply enterprise/internal/campaigns/service.go:333]: > to protect us from overloading, I think we should add a waitgroup here to only run a limited number of them in parallel

We do have a connection pool for the Postgres connections, so we can't spawn an endless list of connections. We're limited by that.



> That would combine all the error handling and probably be even faster than iterating over and calling out to PG a couple hundred times?

Yeah, probably. I'll try that.

Comment (eseliger) [reply enterprise/internal/campaigns/service.go:333]: > We do have a connection pool for the Postgres connections, so we can't spawn an endless list of connections. We're limited by that.

Since this is running in one transaction, it needs to be the same connection for all, no?

**Comment by efritz** [comment]
*Idea*: What if when this operations are being applied and we don't want to block we can send a message to the reconciler functions handling changesets for that particular campaign, which would be equivalent to a context cancel? This could possibly be done with postgres's LISTEN/NOTIFY.

**Comment by mrnugget** [comment]
> _Idea_: What if when this operations are being applied and we don't want to block we can send a message to the reconciler functions handling changesets for that particular campaign, which would be equivalent to a context cancel? This could possibly be done with postgres's LISTEN/NOTIFY.

See my comment here https://github.com/sourcegraph/sourcegraph/pull/13600#discussion_r482132236. I don't think it's worth it. We'd save a little spinner, but we'd add a ton of complexity only to end up with inconsistent state. What if we cancel the reconciler right after we pushed the commit, but before we opened the PR?

File: enterprise/internal/campaigns/service.go (hunk 2 above)
Comment (mrnugget) [reply enterprise/internal/campaigns/service.go:333]: Ahh, good catch. My brain is fried today. I'll try your single query approach tomorrow.

Comment (mrnugget) [reply enterprise/internal/campaigns/service.go]: Done!
