### PR TITLE
codeintel: fix git log ambiguous refname when branch and tag share name but different commit

### LINKED ISSUE #31098: codeintel: ambiguous refname warning in configuration policy matcher
From a customer issue, we've observed errors in the form of `t=2022-02-11T18:56:18+0000 lvl=eror msg=codeintel.gitserver.CommitsUniqueToBranch error=“unexpected output from git log (bad date format) \“c88d32fd58c68c98167dfa4212d9586c4e238224:2020-12-22T02:17:01+00:00warning: refname ‘sampletext’ is ambiguous.\“” count=1.000 elapsed=0.069 repositoryID=3 branchName=sampletext isDefaultBranch=false`, which originates in the [policy matcher](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6fd4eccb2839c8b7ad185fe6f0d829cc8361ca4b/-/blob/enterprise/internal/codeintel/policies/matcher.go?L201). 

This error was causing uploads to not be marked as expired in the [upload expirer](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6fd4eccb2839c8b7ad185fe6f0d829cc8361ca4b/-/blob/enterprise/cmd/worker/internal/codeintel/janitor/upload_expirer.go?L188) worker job, as confirmed by the expired column in `lsif_uploads` not being set to `true` for uploads that should have been deleted. The current suspect cause is that there are both branches and tags with the same name, which was confirmed as a possible cause in an isolated test case, awaiting confirmation from the customer.

A possible mitigation is to use the objhash instead of the branch name when calling `gitserverClient.CommitsUniqueToBranch`. This gave the correct output in the isolated test case and we will create a fix and run the code-intel Q/A against the fix to make sure it has no side-effects.

### PR DESCRIPTION
**Pull request by Strum355**
This PR closes #31098 by using the commit hash of the branch's HEAD for which we are requesting the unique commits of. As the commit hash is unambiguous in the face of refnames (tags + branches) having the same name, and `git log` accepts both object hashes as well as ref names, this change results in the exact same behaviour while also addressing ambiguity cases. 

In the test repository, theres both a branch and a tag called `testy` but both pointing towards different commits. The previous behaviour of passing the branch name to CommitsUniqueToBranch surfaces the "refname is ambiguous" case, while passing the commit hash instead gives us the correct behaviour. The correctness of the output is confirmed by the output of the same commands on the `testx` branch, which shares the same HEAD commit while not being an ambiguous refname.

### Git Graph

```
                        refs/heads/{testx,testy}
           1---------------------2
refs/heads/main
refs/tags/testy
```

image

## Test plan

1. Tested git cli invocation behaviour on a test repository with a branch and tag having the same name
2. Ran the existing unit tests, with mock behaviour changed in accordance with CommitsUniqueToBranch taking in the branch HEAD's commit hash
3. Ran the full dry-run CI pipeline before creating the pull request. Link: https://buildkite.com/sourcegraph/sourcegraph/builds/131027

### CODE REVIEW

File: enterprise/internal/codeintel/policies/matcher.go [hunk 1]
```diff
@@ -127,6 +127,7 @@ type matcherContext struct {
 
 type branchRequestMeta struct {
 	isDefaultBranch     bool
+	commitHash          string // commit hash of the tip of the branch
```
Comment (mrnugget) [inline enterprise/internal/codeintel/policies/matcher.go:130]: Nitpick: we [usually](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+CommitID+file:api+lang:go&patternType=literal) refer to this as `commitID`, not hash. To be nitpicky _and_ pedantic I could say "the fact that the ID of the commit is a hash is an implementation detail".

**Review by mrnugget — APPROVED** [review]
Nice catch!
