### PR TITLE
graphql: lazy load commit information in search results

### LINKED ISSUE #5335: Error fetching commit author info from GraphQL API
- **Sourcegraph version:** sgdev

(Not entirely sure who to assign this to, so I just grabbed the core team. Feel free to reassign.)

Reported by a customer:
* https://app.hubspot.com/contacts/2762526/company/814799425

Any ideas about potential workaround to get this data on search results until a fix is live?

#### Steps to reproduce:

1. Run the query at https://sourcegraph.sgdev.org/api/console#%7B%22query%22%3A%22query%20(%24query%3A%20String!)%20%7B%5Cn%20%20search(query%3A%20%24query)%20%7B%5Cn%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20%20%20...%20on%20FileMatch%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20file%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20commit%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20author%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20person%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20email%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22sourcegraph%2Fsourcegraph%5C%22%5Cn%7D%22%7D

2. See error:

image

The same issue exists for all fields within the `person` object, but does not occur for other fields in the `author` object one level above that.

#### Expected behavior:

Author information should be available

#### Actual behavior:

`"json: error calling MarshalJSON for type json.RawMessage: invalid character '}' looking for beginning of value\n"`

Looks like an unexpected empty string/nil error. Like the search API isn't populating that field for some reason?

### PR DESCRIPTION
**Pull request by kzh**
This PR lazy loads in commit information in search results in the graphql API. This fixes #5335.

I chose to implement the lazy method instead of making the `author` field optional for API feature parity. It made more sense to have `author` remain as a required field of `GitCommit`.

### CODE REVIEW

File: cmd/frontend/graphqlbackend/git_commit.go [hunk 1]
```diff
@@ -34,27 +36,56 @@ type GitCommitResolver struct {
...
 		oid: GitObjectID(commit.ID),
 
-		author:    *authorResolver,
-		committer: toSignatureResolver(commit.Committer),
+		author:    *toSignatureResolver(&commit.Author, true),
+		committer: toSignatureResolver(commit.Committer, true),
 		message:   commit.Message,
 		parents:   commit.Parents,
 	}
+	res.once.Do(func() {})
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/git_commit.go]: This line looks strange, could you explain it?

File: cmd/frontend/graphqlbackend/git_commit.go [hunk 2]
```diff
@@ -34,27 +36,56 @@ type GitCommitResolver struct {
 	// to avoid redirecting a user browsing a revision "mybranch" to the absolute commit ID as they follow links in the UI.
 	inputRev *string
 
+	// fetch + serve sourcegraph stored user information
+	long bool
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/git_commit.go]: nit: I think it's more obvious to name it `includeUserInfo`.

File: cmd/frontend/graphqlbackend/git_commit.go (hunk 1 above)
Comment (kzh) [reply cmd/frontend/graphqlbackend/git_commit.go]: `once` ensures that the fetching of commit information from a commit id happens only once. In this method, the commit information is already provided through the parameters. Thus, we make it run an empty function to indicate this.

Comment (unknwon) [reply cmd/frontend/graphqlbackend/git_commit.go]: Gotcha, thanks!

Compare how it's done in the `resolveCommit` method, I suggest the following:

```go
res.once.Do(func() {
	res.consumeCommit(commit)
})
```

Otherwise, it would be good to put a line of comment to explain the intent.

Comment (kzh) [reply cmd/frontend/graphqlbackend/git_commit.go]: This is much better. Thanks!

File: cmd/frontend/graphqlbackend/git_commit.go [hunk 3]
```diff
@@ -34,27 +36,56 @@ type GitCommitResolver struct {
...
+		var commit *git.Commit
+		commit, err = git.GetCommit(ctx, *cachedRepo, nil, api.CommitID(r.oid))
+		if err != nil {
+			return
+		}
 
-		oid: GitObjectID(commit.ID),
+		r.consumeCommit(commit)
+	})
+	return
```
Comment (keegancsmith) [inline cmd/frontend/graphqlbackend/git_commit.go]: you need to cache the error returned.

File: cmd/frontend/graphqlbackend/git_commit.go [hunk 4]
```diff
@@ -85,19 +116,41 @@ func (r *GitCommitResolver) OID() GitObjectID { return r.oid }
...
 	return string(r.oid)[:7]
 }
-func (r *GitCommitResolver) Author() *signatureResolver    { return &r.author }
-func (r *GitCommitResolver) Committer() *signatureResolver { return r.committer }
-func (r *GitCommitResolver) Message() string               { return r.message }
-func (r *GitCommitResolver) Subject() string               { return gitCommitSubject(r.message) }
-func (r *GitCommitResolver) Body() *string {
+func (r *GitCommitResolver) Author(ctx context.Context) (*signatureResolver, error) {
+	err := r.resolveCommit(ctx)
+	return &r.author, err
```
Comment (keegancsmith) [inline cmd/frontend/graphqlbackend/git_commit.go]: if this fails author will be nil, and taking the address of it will panic.

Comment (kzh) [reply cmd/frontend/graphqlbackend/git_commit.go]: Thanks for catching this!
