### PR TITLE
[bug] Fix syncUserPerms creating user repo permissions with NULL external account IDs

### LINKED ISSUE #57418: User appears twice in repo permissions list
Image

/cc @sourcegraph/source

### PR DESCRIPTION
**Pull request by pjlast**
Closes #57418 

UserExternalAccountsStore operations that add a user external account now returns the created external account.
This fixes an issue in the permissions syncer where, for providers that implement `FetchAccount`, the created external account is used without an external account ID in the first sync, which leads to entries in the `user_repo_permissions` table where the external account ID is `NULL`.

## Test plan

Unit test adjusted to assert that the user repo permissions inserted does not have an external account ID of 0.

### CODE REVIEW

File: cmd/repo-updater/internal/authz/perms_syncer.go [hunk 1]
```diff
@@ -458,7 +458,7 @@ func (s *PermsSyncer) fetchUserPermsViaExternalAccounts(ctx context.Context, use
 		}
 		providerLogger.Debug("account found for provider", log.String("provider_urn", provider.URN()), log.Int32("user_id", user.ID), log.Int32("account_id", acct.ID))
 
-		err = accounts.AssociateUserAndSave(ctx, user.ID, acct.AccountSpec, acct.AccountData)
+		acct, err = accounts.AssociateUserAndSave(ctx, user.ID, acct.AccountSpec, acct.AccountData)
```
Comment (pjlast) [inline cmd/repo-updater/internal/authz/perms_syncer.go:461]: This is the actual fix from the ticket. `acct` is assigned the return value from `AssociateUserAndSave`, which means it has a valid `ID` now.

File: cmd/repo-updater/internal/authz/perms_syncer_test.go [hunk 2]
```diff
@@ -814,7 +814,12 @@ func TestPermsSyncer_syncUserPerms_subRepoPermissions(t *testing.T) {
 	reposStore.ExternalServiceStoreFunc.SetDefaultReturn(externalServices)
 
 	perms := dbmocks.NewMockPermsStore()
-	perms.SetUserExternalAccountPermsFunc.SetDefaultReturn(&database.SetPermissionsResult{}, nil)
+	perms.SetUserExternalAccountPermsFunc.PushHook(func(ctx context.Context, uieai authz.UserIDWithExternalAccountID, i []int32, ps authz.PermsSource) (*database.SetPermissionsResult, error) {
```
Comment (mrnugget) [inline cmd/repo-updater/internal/authz/perms_syncer_test.go:817]: > `uieai`

... is what I said out loud when I saw that variable name.

File: cmd/repo-updater/internal/authz/perms_syncer_test.go [hunk 3]
```diff
@@ -814,7 +814,12 @@ func TestPermsSyncer_syncUserPerms_subRepoPermissions(t *testing.T) {
...
+		if uieai.ExternalAccountID == 0 {
+			t.Fatal("ExternalAccountID should not be 0")
+		}
+		return &database.SetPermissionsResult{}, nil
+	})
```
Comment (mrnugget) [inline cmd/repo-updater/internal/authz/perms_syncer_test.go:822]: Just to be sure: this test fails when you remove your fix, right?

File: internal/database/external_accounts.go [hunk 4]
```diff
@@ -302,23 +308,39 @@ func (s *userExternalAccountsStore) CreateUserAndSave(ctx context.Context, newUs
...
+	err = res.Err()
+	if err != nil {
+		return nil, err
+	}
+	acct := &extsvc.Account{
+		UserID:      userID,
+		AccountSpec: spec,
+		AccountData: data,
+	}
+	if err := res.Scan(&acct.ID, &acct.UpdatedAt, &acct.CreatedAt); err != nil {
```
Comment (mrnugget) [inline internal/database/external_accounts.go:339]: This change makes me wonder whether this whole method shouldn't accept an `*extsvc.Account` that's then modified. We use that pattern a lot in other stores, i.e.:

```go
animal := &types.Animal{Name: "Bob the Goat"}
err := animalStore.Create(ctx, animal)
if err != nil {
   // ...
}
animal.ID == 1
animal.CreatedAt.IsZero() == false
```

**Review by mrnugget — APPROVED** [review]

File: cmd/repo-updater/internal/authz/perms_syncer_test.go (hunk 3 above)
Comment (pjlast) [reply cmd/repo-updater/internal/authz/perms_syncer_test.go:822]: Yep! Modified the test on `main` first

File: internal/database/external_accounts.go (hunk 4 above)
Comment (pjlast) [reply internal/database/external_accounts.go:339]: Yep, I like this suggestion. Accepting Spec and Data separately feels a bit odd

Comment (mrnugget) [reply internal/database/external_accounts.go:339]: I think there's a few more methods on that store and I'm not sure whether it makes sense for all of them, but handing around two bits of data only for them to be combined anyway makes me think we could probably simplify things :)

Comment (pjlast) [reply internal/database/external_accounts.go:339]: I made a follow-up ticket here: https://github.com/sourcegraph/sourcegraph/issues/57508

I think it's well worth its own ticket and reworking this store a bit, as it touches quite a bit of contrived bits of code (user creation on sign-in for example)
