### PR TITLE
search: Fix `contains` not allowing file and content

### LINKED ISSUE #19588: support multiple params in `contains` predicate or add friendlier message
Screen Shot 2021-03-30 at 5 47 00 PM

Could do: `query.ToBasicQuery(nodes)` and if error, then it cannot be partitioned into flat Parameter and Pattern. There isn't a nice interface for iterating over a parameter list yet though.

### PR DESCRIPTION
**Pull request by camdencheek**
Previously, parsing `repo:contains(file:a content:b)` would fail with a
cryptic error. This fixes the precicate params parsing so that this
syntax is allowed.

Fixes #19588

### CODE REVIEW

File: internal/search/query/predicate.go [hunk 1]
```diff
@@ -81,36 +81,52 @@ func (f *RepoContainsPredicate) ParseParams(params string) error {
...
+	case Pattern:
+		if f.Content != "" {
+			return errors.New("cannot specify content multiple times")
+		}
+		f.Content = v.Value
+	case Operator:
+		if v.Kind == Or {
+			return errors.New("predicates do not currently support or queries")
+		}
+		for _, operand := range v.Operands {
```
Comment (camdencheek) [inline internal/search/query/predicate.go:122]: The crux of this is here. Parsing `file:a content:b` as a query was nesting the nodes inside an AND operator, so we need to recurse into operators of type AND to access those nodes.

File: internal/search/query/predicate.go [hunk 2]
```diff
@@ -81,36 +81,52 @@ func (f *RepoContainsPredicate) ParseParams(params string) error {
...
+			return fmt.Errorf("unsupported option %q", v.Field)
 		}
+	case Pattern:
+		if f.Content != "" {
+			return errors.New("cannot specify content multiple times")
+		}
+		f.Content = v.Value
+	case Operator:
+		if v.Kind == Or {
+			return errors.New("predicates do not currently support or queries")
```
Comment (rvantonder) [inline internal/search/query/predicate.go:120]:
```suggestion
			return errors.New("predicates do not currently support 'or' queries")
```

We don't support `not` either right? Can we add a cases for that (check `v.Negated` for Parameter, Content, and `v.Kind == Not`).

**Review by rvantonder — APPROVED** [review]
Looks goood :-)
