### PR TITLE
search: fix indexed search match count

### LINKED ISSUE #11236: Search results count now shows number of file matches, rather than number of text matches
Reported by https://app.hubspot.com/contacts/2762526/company/732945850

>For example, a user noticed that the count of results were different between the two instances. I did some investigating and it appears that in 3.12.6 the count was counting the number of instances of the search string. In 3.15.1 it appears the count is counting the number of files in which the search string occurred. So we'd see 27 in the older version and 23 in the newer version

I assumed that the former behavior was the "correct" one, but I'm not sure if that's the case. What is the desired behavior here?

### PR DESCRIPTION
**Pull request by rvantonder**
This fixes #11236, a regression introduced by https://github.com/sourcegraph/sourcegraph/pull/9541. The `MatchCount` value should be set on the Zoekt path.

While investigating this I discovered an interesting match count discrepancy. Irrespective of the regression, and prior to the bug I introduced, we had been calculating the number of matches returned by Zoekt by counting the number of _lines_. This stems from returning `lines` [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d11e4dc7567c7f453ffd46cdabe1d6c58a2ebf06/-/blob/cmd/frontend/graphqlbackend/zoekt.go#L250) on the Zoekt path, and using [`len(fm.LinesMatches)` prior to using the `MatchCount` member that I introduced](https://github.com/sourcegraph/sourcegraph/pull/9541/files#diff-4c0e5adb9c777d181fac5c74474f820cL150). 

So three matches of `foo` on a line like `foo foo foo` would only count as one match on the indexed search path. To count the three separate `foo`s, we need to calculate the number based off of [`offsets`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d11e4dc7567c7f453ffd46cdabe1d6c58a2ebf06/-/blob/cmd/frontend/graphqlbackend/zoekt.go#L243) AKA fragments (which is what this PR does). Now this prompted the question of whether we intended to report the number of line matches, or the number of fragments. I believe we really do mean to report the number of fragments (since that seems reasonable), but also because that's what the [unindexed search part did before the change](https://github.com/sourcegraph/sourcegraph/pull/9541/files#diff-12aa12435865df936cc98d2d3dd0d510R292) (and this behavior is preserved, with `MatchCount`) _but only because the logic in the unindexed search path always adds only one fragment per line match_, as you can see [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d11e4dc7567c7f453ffd46cdabe1d6c58a2ebf06/-/blob/cmd/searcher/search/search_regex.go#L271).

So, there is/was a discrepancy of match count in the indexed/unindexed search paths before the regression, and this PR addresses that bug as well. If we really mean to report the number of lines, and not fragments, then it implies that the unindexed search part contains a bug (reports more matches than number of lines). I do think we mean to report the number of fragments. 

But there's another interesting tidbit: Zoekt returns a `MatchCount` member, for example, we access it here: [`resp.MatchCount`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d11e4dc7567c7f453ffd46cdabe1d6c58a2ebf06/-/blob/cmd/frontend/graphqlbackend/zoekt.go#L146-150). I thought that I could use that `MatchCount` value to return the number of matches, because the docstring says:

> // Number of non-overlapping matches [ref](https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/api.go#L135)

And from this description I assumed it meant it counts multiple matches on a line, since I'm not sure what "non-overlapping matches" would mean if they are separated by lines, which are already discrete, non-overlapping data. Maybe it means something entirely different, because this `MatchCount` only counts the number of lines, not the number of matches in a line. It's also possible that's a bug, but I am not familiar enough with what this data member of Zoekt is trying to say, so CC @keegancsmith, take from it what you will.

---

It took me ~15 minutes to verify a fix, and 1.5+ hours to write the test, and that's really frustrating. I had to keep adding data to the test case so the function wouldn't nil panic all over the place until finally I wound up with a ~60 line struct :/. This would be better as an integration test, but the infra isn't ready yet. CC @unknwon I'm just pointing out this is important and a real pain point, I'm hoping it comes soon 🤞

### CODE REVIEW

File: cmd/frontend/graphqlbackend/textsearch_test.go [hunk 1]
```diff
@@ -616,15 +684,25 @@ func TestZoektSearchHEAD(t *testing.T) {
 				t.Errorf("zoektSearchHEAD() error = %v, wantErr = %v", err, tt.wantErr)
 				return
 			}
-			if !reflect.DeepEqual(gotFm, tt.wantFm) {
-				t.Errorf("zoektSearchHEAD() gotFm = %v, want %v", gotFm, tt.wantFm)
+			if tt.wantFm != nil {
```
Comment (rvantonder) [inline cmd/frontend/graphqlbackend/textsearch_test.go:687]: I think if this value is `nil` for the other test cases, we can skip the structural equality check. If it _has_ to be on, then I have to fill in a huge struct corresponding to the `Searcher.result` values I need to test against :'(

File: CHANGELOG.md [hunk 2]
```diff
@@ -30,6 +30,7 @@ All notable changes to Sourcegraph are documented in this file.
 - Links to AWS Code Commit repositories have been fixed after the URL schema has been changed. [#11019](https://github.com/sourcegraph/sourcegraph/pull/11019)
 - A link to view all repositories will now always appear on the Explore page. [#11113](https://github.com/sourcegraph/sourcegraph/pull/11113)
 - The Site-admin > Pings page no longer incorrectly indicates that pings are disabled when they aren't. [#11229](https://github.com/sourcegraph/sourcegraph/pull/11229)
+- Match counts are now accurately reported for indexed search [#11242](https://github.com/sourcegraph/sourcegraph/pull/11242)
```
Comment (rvantonder) [inline CHANGELOG.md:33]:
```suggestion
- Match counts are now accurately reported for indexed search. [#11242](https://github.com/sourcegraph/sourcegraph/pull/11242)
```

File: cmd/frontend/graphqlbackend/textsearch_test.go [hunk 3]
```diff
@@ -616,15 +684,25 @@ func TestZoektSearchHEAD(t *testing.T) {
...
+				if !reflect.DeepEqual(gotFm, tt.wantFm) {
```
Comment (ryanslade) [inline cmd/frontend/graphqlbackend/textsearch_test.go:688]: Did you consider using `cmp.Diff` instead of `reflect.DeepEqual`? It also does a deep compare and produces a diff when they don't match

```go
if diff := cmp.Diff(tt.wantFm, gotFm); diff != "" {
  t.Error(diff)
}
```

Comment (rvantonder) [reply cmd/frontend/graphqlbackend/textsearch_test.go:688]: I'm just using what the tests already do. If we switch to cmp.Diff this should happen in a separate PR
