### PR TITLE
search: Make predicate parsing more robust

### LINKED ISSUE #19075: search: Generalize parsing of predicate values
To support parameter values like `contains(file:test)`, we had to add an exception to the parsing rules to continue parsing through parantheses in the case that we are parsing one of the reserved predicate keywords. This should be generalized to allow for multiple predicate names, and also re-thought to make sure this is the correct place to do this check.

Related to #18584

### PR DESCRIPTION
**Pull request by camdencheek**
This adds specific scanners for predicates so we can more robustly
determine whether trailing paranthesis groups should be interpreted as
predicate params, regex groups, or subqueries.

Fixes #19075

### CODE REVIEW

File: internal/search/query/parser.go [hunk 1]
```diff
@@ -407,6 +401,104 @@ loop:
...
+	return predicateName, advance, true
+}
+
+// ScanBalancedParens will return the full string including
+// and inside the parantheses that start with the first character.
+// This is different from ScanBalancedPattern because that attempts
+// to take into account whether the content looks like other filters.
+// In the case of predicates, we offload the job of parsing parameters
+// onto the predicates themselves, so we just want the full content
+// of the parameters, whatever it contains.
```
Comment (rvantonder) [inline internal/search/query/parser.go:459]: I appreciate this description, thank you.

File: internal/search/query/parser.go [hunk 2]
```diff
@@ -407,6 +401,104 @@ loop:
...
+		r, advance := utf8.DecodeRune(buf)
+		count += advance
+		buf = buf[advance:]
+		result = append(result, r)
+		return r
+	}
+
+	r = next()
+	if r != '(' {
+		panic(fmt.Sprintf("ScanDelimited expects the input buffer to start with delimiter (, but it starts with %s.", string(r)))
```
Comment (rvantonder) [inline internal/search/query/parser.go:475]:
```suggestion
		panic(fmt.Sprintf("ScanBalancedParens expects the input buffer to start with delimiter (, but it starts with %s.", string(r)))
```

File: internal/search/query/parser_test.go [hunk 3]
```diff
@@ -175,6 +175,15 @@ func TestParseParameterList(t *testing.T) {
...
 
+	autogold.Want("Repo contains not predicate", value{
+		Result:      `{"field":"repo","value":"contains","negated":false}`,
+		ResultRange: `{"start":{"line":0,"column":0},"end":{"line":0,"column":13}}`,
+	}).Equal(t, test(`repo:contains`))
+
+	autogold.Want("Repo with something that looks kinda like predicate", value{
+		Result: `{"Kind":1,"Operands":[{"field":"repo","value":"nopredicate","negated":false},{"value":"(file:foo","negated":false}],"Annotation":{"labels":0,"range":{"start":{"line":0,"column":0},"end":{"line":0,"column":0}}}}`,
+	}).Equal(t, test(`repo:nopredicate(file:foo or file:bar)`))
+
```
Comment (rvantonder) [inline internal/search/query/parser_test.go:186]: Adding one test case to cover escaping behavior in side parens would be nice:

`test('repo:contains(\(sup)'`

**Review by rvantonder — APPROVED** [review]
nicely done
