### PR TITLE
insights: fix transactionality for add / remove view to dashboard mut…

### LINKED ISSUE #27451: insights: AddInsightViewToDashboard race condition
The `AddInsightViewToDashboard` mutation currently does not operate in a transaction and has a race condition between validations and DB modifications.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/resolvers/dashboard_resolvers.go?utm_product_name=GoLand&utm_product_version=GoLand&utm_source=JetBrains-v1.2.1#L363:28

### PR DESCRIPTION
**Pull request by coury-clark**
Fixes #27451

Fixes transactionality in the add / remove view to dashboard mutations.
1. Adds transaction support to permissions validator
2. Fixes a bug in the mutations where an empty dashboard response violated the nullability constraint in the GraphQL API (apparently `errors.Wrap` returns nil if the passed `err` is also nil

### CODE REVIEW

File: enterprise/internal/insights/resolvers/dashboard_resolvers.go [hunk 1]
```diff
@@ -341,26 +341,34 @@ func (r *Resolver) DeleteInsightsDashboard(ctx context.Context, args *graphqlbac
...
-	err = r.permissionsValidator.validateUserAccessForDashboard(ctx, int(dashboardID.Arg))
+
+	tx, err := r.dashboardStore.Transact(ctx)
+	if err != nil {
+		return nil, err
+	}
+	defer func() { err = tx.Done(err) }()
+
+	txValidator := r.permissionsValidator.WithBaseStore(tx.Store)
+	err = txValidator.validateUserAccessForDashboard(ctx, int(dashboardID.Arg))
```
Comment (CristinaBirkel) [inline enterprise/internal/insights/resolvers/dashboard_resolvers.go:362]: I'm not sure I understand why this needs to be part of the same transaction, since it's not modifying anything.

The case I can see would be checking if a view is already on a dashboard, and then adding the view in the same transaction to prevent a race condition where the check returns false, but then the call to `AddViewsToDashboard` fails because the state changed in between the check and the update. (Although, does a transaction prevent that with locking? Or does it just make sure that everything gets rolled back in case of a failure?)

We have a bunch of other validation happening outside of transactions. Do all of these need to be updated, or just some? Probably my lack of understanding here, but just to clarify.

Comment (coury-clark) [reply enterprise/internal/insights/resolvers/dashboard_resolvers.go:362]: > prevent a race condition

Right, the point is that we are reading both dashboards and grants in order to determine eligibility, we need to propagate the same transaction context to mutation otherwise we could end up with various kinds of constraint violations (or logic violations, such as modifying a dashboard you don't have access to).

The level of which this is enforced depends on the [isolation of the transaction](https://www.postgresql.org/docs/9.5/transaction-iso.html)

> We have a bunch of other validation happening outside of transactions. Do all of these need to be updated, or just some?

Any time we split this into two operations (read + read or read + write), yeah we should fix this.

Comment (CristinaBirkel) [reply enterprise/internal/insights/resolvers/dashboard_resolvers.go:362]: Okay, I think we're doing this in a handful more places then; all of our update/delete methods basically. I can open an issue for that to fix it: https://github.com/sourcegraph/sourcegraph/issues/27469

**Review by CristinaBirkel — APPROVED** [review]
Looks good!
