### PR TITLE
Fix new campaign label

### LINKED ISSUE #8937: New campaign screen says "New manual campaign" even if campaign created with plan
How to reproduce: Open form to create a new campaign from a plan: `http://localhost:3080/campaigns/new?plan=<PLAN_ID>`

UI says "New manual campaign"

Screen Shot 2020-03-11 at 13 58 29

### PR DESCRIPTION
**Pull request by eseliger**
Closes #8937

### CODE REVIEW

File: web/src/enterprise/campaigns/detail/CampaignActionsBar.tsx [hunk 1]
```diff
@@ -50,7 +50,7 @@ export const CampaignActionsBar: React.FunctionComponent<Props> = ({
                     <Link to="/campaigns">Campaigns</Link>
                 </span>
                 <span className="text-muted d-inline-block mx-2">/</span>
-                <span>{campaign?.name ?? 'New manual campaign'}</span>
+                <span>{campaign?.name ?? (previewingCampaignPlan ? 'New campaign' : 'New manual campaign')}</span>
```
Comment (mrnugget) [inline web/src/enterprise/campaigns/detail/CampaignActionsBar.tsx]: That's a lot of conditions on one line now, I think we should pull this out to the other booleans up top.

```js
const creatingCampaign = !campaign;
const creatingManualCampaign = creatingCampaign && !previewingCampaignPlan;

const newCampaignHeader = previewingCampaignPlan ? 'New campaign' : 'New manual campaign'
const header = creatingCampaign ? newCampaignHeader : campaign.name;
```

Bit verbose, yes, but I think it's easier to read and to extend than another nested ternary :)
```
