### PR TITLE
Render blob panel even if the highlighting request failed

### LINKED ISSUE #10999: No Git file history for binary files
Requested by https://app.hubspot.com/contacts/2762526/company/578600789

Sourcegraph doesn't render binary files (https://github.com/sourcegraph/sourcegraph/issues/8387), but apparently it also isn't able to show Git history:

image

Related:

* https://github.com/sourcegraph/sourcegraph/issues/10998
* https://github.com/sourcegraph/sourcegraph/issues/8387

Not urgent, but if a quick fix, would be a nice customer win!

### PR DESCRIPTION
**Pull request by eseliger**
This caused #10999 where no git history would show up, because the
request for the highlighted content fails, as the file is binary.

The Blob panel should be rendered independently of the blob content. That way
- it's possible to still show the history when the render failed
- the fetch for the history data can happen earlier, before the blob is done highlighting

Closes #10999

### CODE REVIEW

File: web/src/repo/blob/BlobPage.tsx [hunk 1]
```diff
@@ -240,6 +240,14 @@ export class BlobPage extends React.PureComponent<Props, State> {
                     }
                     repoHeaderContributionsLifecycleProps={this.props.repoHeaderContributionsLifecycleProps}
                 />
+                <BlobPanel
```
Comment (felixfbecker) [inline web/src/repo/blob/BlobPage.tsx:243]: Does it make no difference that this is now in the top of the DOM (before the file content) and not at the end?

Wish this component had screenshot tests...

Comment (eseliger) [reply web/src/repo/blob/BlobPage.tsx:243]: It actually renders nothing, it's just a view provider wrapper. If that sounds safe enough, wanna approve? :)

Comment (felixfbecker) [reply web/src/repo/blob/BlobPage.tsx:243]: Very weird

**Comment by keegancsmith** [comment]
Changelog entry pls :)
