### PR TITLE
blob: correct handling of syntax highlighting timeouts

### LINKED ISSUE #4267: webapp regression: "Syntax-highlighting this file took too long." is not falling back to plaintext rendering mode
When the syntax highlighter bails out because highlighting is taking too long (e.g. on large files or files it can't handle well for whatever reason), we *always* return a plaintext version of the document to be rendered.

However, it appears there has been a regression where the webapp / TS code is incorrectly ignoring the plaintext form it got instead of rendering it as it should be:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@cdedd0e83a68a314f67d53e261209e272d787735/-/blob/web/src/repo/blob/BlobPage.tsx#L275

Reported by https://app.hubspot.com/contacts/2762526/company/407948923

### PR DESCRIPTION
**Pull request by slimsag**
A regression (which apparently must've occurred awfully long ago, like around 8mo ago)
means that today when syntax highlighting takes too long (which can happen for
multiple reasons: due to very large files, bugs in the language grammar, or
bugs in syntect itself) we are incorrectly _just_ displaying the message and action:

> Syntax-highlighting this file took too long. [Try again]

Despite the fact that the server returned an unhighlighted version of the
file, we're just discarding it instead of presenting it to the user as this
was originally designed / intended to work.

What this means in practice is that today Sourcegraph is very unusable on large
files because as soon as you view them you get the above error and have to hit
`Try again` and wait a very long time.

Instead, we now once again properly show the above error and action (for users
who are willing to wait longer for syntax highlighting on these files) AND the
actual plaintext version of the file.

How it looks:

image

Fixes #4267

See also #4364 which adds something that will allow us to e2e test this in the future.

Test plan: Manually tested using #4364, in the future we will e2e test it.

### CODE REVIEW

File: web/src/repo/blob/BlobPage.tsx [hunk 1]
```diff
@@ -292,6 +282,16 @@ export class BlobPage extends React.PureComponent<Props, State> {
                         </div>
                     </div>
                 )}
+                {renderMode === 'code' && (
```
Comment (felixfbecker) [inline web/src/repo/blob/BlobPage.tsx]:
```suggestion
                {/* Render the (unhighlighted) blob also in the case highlighting timed out */}
                {renderMode === 'code' && (
```
Prevents someone accidentally breaking this in the future
