### PR TITLE
insights: add oob migration for recording times back with fix

### LINKED ISSUE #43496: insights: write migration to save recording times for existing insights
part of the 0-value issue

1. try and generate time sequence through psql's internals and compare to BuildFrames output; if satisfactory we could do this using an in-band migration
2. if this isn't; we can do this using an oob migration:
* construct the recording times for the historical data according to BuildFrames (12 points only)
* fetch unique recording times for series points (additional points)
* add this data to insight_series_recording_times

/cc @joelkw @felixfbecker @vovakulikov

### PR DESCRIPTION
**Pull request by leonore**
closes #43496 (again)

the (second) bug was that on second iteration through sql rows I iterated through `rows.Next()` rather than `recordingRows.Next()`, which meant we would _always_ reuse generated recording times rather than any existing timestamps.

## Test plan

Manually stepped through all the logic. Wrote a unit test. Manually ran the migration again on a local instance.

### CODE REVIEW

File: enterprise/internal/oobmigration/migrations/insights/recording_times_migrator.go [hunk 1]
```diff
@@ -0,0 +1,185 @@
...
+			id,
+		)); err != nil {
+			return err
+		}
+	}
+
+	return nil
+}
+
+func selectSeriesMetadata(ctx context.Context, tx *basestore.Store, batchSize int) (map[int]seriesMetadata, error) {
```
Comment (leonore) [inline enterprise/internal/oobmigration/migrations/insights/recording_times_migrator.go:99]: this is the main change: I've pulled out the logic here into helper functions. but the only change is really
```go
for rows.Next()
```
is now correct for both functions

File: enterprise/internal/oobmigration/migrations/insights/recording_times.go [hunk 2]
```diff
@@ -0,0 +1,145 @@
...
+	referenceTimes := buildRecordingTimes(12, interval, createdAt.Truncate(time.Hour*24))
+	if !lastRecordedAt.IsZero() {
+		// If we've had recordings since we need to step through them.
+		referenceTimes = append(referenceTimes, buildRecordingTimesBetween(createdAt.Truncate(time.Hour*24), lastRecordedAt, interval)[1:]...)
+	}
+
+	if len(existingPoints) == 0 {
+		return referenceTimes
+	}
+
```
Comment (leonore) [inline enterprise/internal/oobmigration/migrations/insights/recording_times.go:18]: I removed the logic to early exit on len(existingPoints) = len(recordingTimes).

**Review by coury-clark — APPROVED** [review]
