### PR TITLE
Integrate new reference panel into existing `BlobPanel`

### LINKED ISSUE #32307: New reference panel: integrate panel with existing panels
Right now the experimental reference panel doesn't work well with the existing panels, the history panel & extension contributed panels.

The goal of this ticket is to find a way to allow users to view the history panel, extension panels and the new experimental panel if the feature flag is on. If it's off, we fallback to old panel.

I think the most likely solution (which I've investigated) is to make the new panel one of the builtin panel views here (https://github.com/sourcegraph/sourcegraph/blob/main/client/web/src/repo/blob/panel/BlobPanel.tsx#L152).

Challenges:

- It's the first panel that "listens" to 3+ different actions/IDs: `definition`, `references,` `implementations_*`. 
- In a first spike it looks like navigating inside the new panel triggers reloading of extension-contributed panels, leading to new panel names showing up in the list of tabs
- CSS needs to be changed so that we can scroll inside the mini code blob.

### PR DESCRIPTION
**Pull request by mrnugget**
This fixes #32307 by integrating the new reference panel into the existing `BlobPanel` as another `BuiltinPanelView`.

There's three interesting bits here:

* I made the `PanelViews` dynamic so that they can match different tab IDs in the URL (`#tab=<ID>`), since the new reference panel needs to be backward compatible and react to `#tab=def`, `#tab=references`, `#tab=implementations_$LANGUAGE`, which are hardcoded into the extensions.
* Depending on whether the feature flag `coolCodeIntel` is enabled, the new panel or the old def/ref/implementations panels are used. The `def` and `ref` panels are easily deactivated, but the `implementations_$LANGUAGE` panels come from extensions, so I had to dynamically filter them.
* I had to essentially move the styling of the panels. They still look the same, but I had to move some styling and optionally disable a wrapper element so I can get the `overflow: scroll` working correctly for the two panes inside the new panel.

The rest is essentially cleanup and restructuring of the existing components and removal of those that we don't need anymore. I also thought about moving components but that would've made the diff unreadable. So I'll save that for a follow-up PR.

## Test plan

- Tested this locally by enabling/disabling the flag, checking whether the new panel reacts to all URLs, testing that dynamic matching works, etc. See video.

https://user-images.githubusercontent.com/1185253/157863497-65eecf67-5e4c-4a1e-88e6-7b2073eaaedb.mp4

### CODE REVIEW

File: client/web/src/repo/RepoRevisionContainer.tsx [hunk 1]
```diff
@@ -183,13 +182,6 @@ export const RepoRevisionContainer: React.FunctionComponent<RepoRevisionContaine
     useBreadcrumb,
     ...props
 }) => {
-    // Experimental reference panel
```
Comment (efritz) [inline client/web/src/repo/RepoRevisionContainer.tsx:186]: No longer experimental 😎

Comment (mrnugget) [reply client/web/src/repo/RepoRevisionContainer.tsx:186]: It still is! I even called that variable `experimental...` in the other place.

Comment (efritz) [reply client/web/src/repo/RepoRevisionContainer.tsx:186]: No longer cool 😎

File: client/branded/src/components/panel/Panel.tsx [hunk 2]
```diff
@@ -169,6 +193,13 @@ export const Panel = React.memo<Props>(props => {
                                     .filter(panelView =>
                                         panelView.selector !== null ? match(panelView.selector, document) : true
                                     )
+                                    .filter(panelView =>
+                                        // If we use the new reference panel we don't want to display additional
+                                        // 'implementations_' panels
```
Comment (efritz) [inline client/branded/src/components/panel/Panel.tsx:198]: Is this the only one that is prefixed instead of exact match we need to worry about?

**Review by efritz — APPROVED** [review]

File: client/web/src/repo/RepoRevisionContainer.tsx (hunk 1 above)
Comment (mrnugget) [reply client/web/src/repo/RepoRevisionContainer.tsx:186]: KetchupPanel 🍅

Comment (efritz) [reply client/web/src/repo/RepoRevisionContainer.tsx:186]: `background-color: tomato`

File: client/branded/src/components/panel/Panel.tsx (hunk 2 above)
Comment (mrnugget) [reply client/branded/src/components/panel/Panel.tsx:195]: I haven't found a way to reliably see all possible extension actions (there's an enum in here that's outdated and useless), but yes, these are the 3+ actions that are contained in the new panel. Everything else should get a separate panel/tab.

https://github.com/sourcegraph/code-intel-extensions/blob/1b78262e538b5bb1c31ecf9d249060fad5915016/template/package.json#L82
