### PR TITLE
Fix issue with file filters causing invalid diff results

### LINKED ISSUE #21031: Adding `lang:` to `type:diff` search causes results to ignore `after:` filter
Compare:
- [Search with `lang:`](https://sourcegraph.com/search?q=context:global+lang:yaml+type:diff+after:%228+days+ago%22+repo:github.com/sourcegraph/sourcegraph%24&patternType=regexp)
- [Search without `lang:`](https://sourcegraph.com/search?q=context:global+type:diff+after:%228+days+ago%22+repo:github.com/sourcegraph/sourcegraph%24&patternType=regexp)

Note that, by adding `lang`, results go back past 8 days ago.

### PR DESCRIPTION
**Pull request by camdencheek**
This commit fixes an issue where adding a `lang:` filter to a diff
search would cause non-matching commits to show up in the results.

This was ultimately caused by the `--max-count` flag on `git show`,
which, very unintuitively, ends up causing `git show` to ignore the
passed-in commit hashes and just list up to the number of commits
specified to `--max-count`. Additionally, I could not find any
references to using `--max-count` with `git show`, so my guess is it's
just not a supported argument for `git show`.

Really, though, we just don't need to be appending the `logDiffCommonArgs` to
the `git show` command at all, since we are just getting more
information for a specific set of commits. So, this commit removes those
args entirely.

Fixes #21031 
Fixes sourcegraph/customer#355

### CODE REVIEW

**Review by rvantonder — APPROVED** [review]
Also changelog :-) Looks good so pre-approving

File: internal/vcs/git/diff_search.go [hunk 1]
```diff
@@ -372,7 +372,6 @@ func rawShowSearch(ctx context.Context, repo api.RepoName, opt RawLogDiffSearchO
 	if hasPathFilters {
 		showArgs = append(showArgs, "--patch")
 	}
-	showArgs = append(showArgs, logDiffCommonArgs(opt)...)
```
Comment (keegancsmith) [inline internal/vcs/git/diff_search.go:375]: amazing fix :D

**Review by keegancsmith — APPROVED** [review]
