### PR TITLE
JetBrains: fix UI of the cody prompt input

### LINKED ISSUE #53465: JetBrains: Chat: Fix message field for long prompts
If I enter a longer prompt, it looks like this:

My problems with it:

- [x] Textbox height grows indefinitely. Solution: Give it a reasonable max height, such as "25% or 300px, whichever is less". (If that's too difficult to do with Swing, do either.)
- [x] Text is broken at random places and is difficult to read. Break text at word boundaries rather than at character boundaries
- [ ] This font is not easily readable and is perhaps a bit too large. Use the default UI font instead (usually a sans-serif).
- [x] After submitting the long prompt, it appears squashed in the chat: 
    
    It's because line breaks are not retained. Suggested solution: retain line breaks in user input.

### PR DESCRIPTION
**Pull request by szymonprz**
- limit prompt input height to 4 rows, for bigger input scroll appears
- break text by words instead of characters
- use standard label font

closes #53465 

## Test plan
- Height of the input should not grow
- text should break by words
- font should be the same as in the chat messages

image

### CODE REVIEW

File: client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java [hunk 1]
```diff
@@ -214,9 +221,11 @@ private JButton createSendButton(@NotNull Project project) {
   @NotNull
   private JBTextArea createPromptInput(@NotNull Project project) {
     JBTextArea promptInput = new RoundedJBTextArea(4, 0, 10);
+    promptInput.setFont(UIUtil.getLabelFont());
```
Comment (vdavid) [inline client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java:224]: This line doesn't seem to do anything. Both in your screenshot and when I run locally, the prompt text is rendered in a fixed-width font.

**Review by vdavid — APPROVED** [review]
The prompt textbox font is not fixed, the rest are fine. I'll go ahead and merge this.
