### PR TITLE
Cody: Fix IME composition, reply in the IDE/browser's language

### LINKED ISSUE #50445: Cody chat input doesn't work with Japanese/input method editor (IME) languages
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** Chrome/Edge 111 on OS X Ventura but probably every desktop OS

#### Steps to reproduce:

0. Install a Japanese input method
1. Open a Cody chat in VScode or on the website
2. Switch to Japanese, start composing a message, hit enter to commit a conversion

#### Expected behavior:

Enter commits the conversion, but doesn't send the message to Cody because I'm still composing a message.

#### Actual behavior:

The "enter" key, commits an IME conversion but *also* sends the message. This makes it practically impossible to compose a message in Japanese (or any language using an IME.)

### PR DESCRIPTION
**Pull request by dominiccooney**
Cody chat prematurely submits chat messages when composing with an input method editor. Wait for IME composition to be finished. Fixes #50445.

## Test plan

Manual test plan:

- Install Japanese as an input method
- VScode, Tool Palette & > Configure Display Language, Japanese, Tool Palette & > Reload Window
- Run vscode extension, open Cody chat
- Switch input method to Japanese (kana/あ)
- Type k-o-n-n-n-i-c-h-i-h-a, press space, press enter
- Verify Japanese text like こんにちは or 今日は (details depend on your IME) are inserted into the text area but the message is *not* sent to Cody
- Hit enter again, verify the message *is* sent to Cody
- Cody should respond in Japanese
- Switch the input method to English, type hello, hit enter, verify the message is sent to Cody after the first enter press

Automated testing of this change is involved, but TL;DR is it is blocked on Issue #50118. After that we need the integration test harness to [make the webviews debuggable,](https://github.com/microsoft/vscode/issues/101320#issue-647701245) connect to them with Puppeteer, and then dip into Chrome DevTools protocol to set `Input.setImeComposing` to generate authentic input events. Testing this with Puppeteer on cody-web would be easier but I'm unsure how to generate synthetic IME composition events with Firefox.

## App preview:

- [Web](https://sg-web-dpc-multilingual-cody.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.03 kb) | 0.00% (+0.03 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/dpc/multilingual-cody/compare-report.html;tab=live_object) for a full comparison between the commits 05db4d3 and 4c2117b or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by almeidapaulooliveira — APPROVED** [review]

File: client/cody/src/extension.ts [hunk 1]
```diff
@@ -1,11 +1,15 @@
 import * as vscode from 'vscode'
 
+import { PromptMixin, languagePromptMixin } from '@sourcegraph/cody-shared/src/chat/recipes/prompt-mixin'
```
Comment (novoselrok) [inline client/cody/src/extension.ts:3]: Are you missing the `prompt-mixin` folder in this PR? I checked `main` and I can't seem to find it.

File: client/cody-shared/src/chat/transcript/interaction.ts [hunk 2]
```diff
@@ -38,11 +39,17 @@ export class Interaction {
     }
 
     public async toPrompt(includeContext: boolean): Promise<Message[]> {
+        const messages: (ContextMessage | InteractionMessage)[] = [this.humanMessage, this.assistantMessage]
```
Comment (novoselrok) [inline client/cody-shared/src/chat/transcript/interaction.ts:42]: What do you think about the following implementation?

```ts
const messages = [PromptMixin.getMessage(this.humanMessage), this.assistantMessage]
```

The `getMessage` function would augment the message with mixins or return the original message if no mixins were registered.

I find it easier to think about if we move the conditionals and the string munging to the PromptMixin class.

File: client/cody/src/extension.ts (hunk 1 above)
Comment (dominiccooney) [reply client/cody/src/extension.ts:3]: 🤡  ...yep. Sorry for the clowntown.
