### PR TITLE
Use radio buttons to toggle retention & indexing in policy

### LINKED ISSUE #29096: "Enabled / disabled" label for toggles in code intel configuration is confusing
- **Sourcegraph version:** main

#### Steps to reproduce:

1. Click "Create new policy" under the Code Intel > Configuration as a site admin.

#### Expected behavior:

There should be no text (because most people are likely already familiar with toggles), or the text should match the button position.

#### Actual behavior:

Left = greyed out / Disabled, Right = colored / Enabled.

However, the button has a label next to it which says "Enabled / disabled" which makes it a little confusing: does left = enabled and right = disabled?

Screenshot showing toggle with confusing label

It's not a big deal, but seems like an unnecessary bit of friction.

### PR DESCRIPTION
**Pull request by mrnugget**
This fixes #29096 and #29095.

screenshot_2022-01-04_13 41 15

@efritz I couldn't easily find an answer in the code, so let me ask you here: if this is toggled to `false`, does that mean no data will be kept or that it will be kept forever? I'd love to add half a sentence next to the button.

### CODE REVIEW

File: client/web/src/components/RadioButtons.tsx [hunk 1]
```diff
@@ -50,19 +50,25 @@ interface Props {
      * id of the currently selected RadioButtonNode.
      */
     selected?: string
+
+    /**
+     * name of the field that these radio buttons select. Use a unique name for
+     * each group of radio buttons in a form.
+     */
+    name?: string
```
Comment (pdubroy) [inline client/web/src/components/RadioButtons.tsx:58]: Seems to me that this should be a required prop.
```suggestion
    name: string
```

File: client/web/src/components/RadioButtons.tsx [hunk 2]
```diff
@@ -50,19 +50,25 @@ interface Props {
...
-export const RadioButtons: React.FunctionComponent<Props> = ({ nodes, onChange, selected, className }) => (
+export const RadioButtons: React.FunctionComponent<Props> = ({ nodes, onChange, selected, className, name }) => (
     <div className={classNames(styles.radioButtons, className)}>
         {nodes.map(node => (
             <RadioButton
                 key={node.key ? node.key : node.id.toString()}
                 id={node.id.toString()}
                 title={node.tooltip}
-                name="filter"
+                name={name || 'filtered'}
```
Comment (pdubroy) [inline client/web/src/components/RadioButtons.tsx:71]:
```suggestion
                name={name}
```

File: client/web/src/components/RadioButtons.tsx (hunk 1 above)
Comment (mrnugget) [reply client/web/src/components/RadioButtons.tsx:58]: Yeah, I was unsure whether to do that in this PR or not, since I'll have to update the other places as well, but that should be quick. I'll do that.

Comment (pdubroy) [reply client/web/src/components/RadioButtons.tsx:58]: Looks like only two places, surprisingly 🤔

Comment (mrnugget) [reply client/web/src/components/RadioButtons.tsx]: Fixed in 728bacb

**Review by pdubroy — COMMENTED** [review]
`RadioButtons` change lgtm 👍

File: client/web/src/enterprise/codeintel/configuration/components/IndexSettings.tsx [hunk 3]
```diff
@@ -2,10 +2,13 @@ import React, { FunctionComponent } from 'react'
 
 import { Toggle } from '@sourcegraph/branded/src/components/Toggle'
 
+import { RadioButtons } from '../../../../components/RadioButtons'
 import { CodeIntelligenceConfigurationPolicyFields, GitObjectType } from '../../../../graphql-operations'
 import { nullPolicy } from '../hooks/types'
 
 import { DurationSelect } from './DurationSelect'
+// This uses the same styles as the RetentionSettings component to style radio buttons
+import styles from './RetentionSettings.module.scss'
```
Comment (efritz) [inline client/web/src/enterprise/codeintel/configuration/components/IndexSettings.tsx:11]: Should this instead be moved inot a shared scss (or copy it into an IndexSettings scss module?

**Review by efritz — APPROVED** [review]

File: client/web/src/enterprise/codeintel/configuration/components/IndexSettings.tsx (hunk 3 above)
Comment (mrnugget) [reply client/web/src/enterprise/codeintel/configuration/components/IndexSettings.tsx:11]: Yeah, I was unsure about that, maybe @pdubroy can answer that? I wanted to create a `RadioButtons.module.scss` in that folder but had the suspicion that it might break some conventions. I also didn't want to copy it, because that felt weird here?

Comment (pdubroy) [reply client/web/src/enterprise/codeintel/configuration/components/IndexSettings.tsx:11]: Are these styles that should be applied to all uses of `RadioButtons`? If so, yes, they should be in `RadioButtons.module.scss`. See https://docs.sourcegraph.com/dev/background-information/web/styling#css-modules

Comment (mrnugget) [reply client/web/src/enterprise/codeintel/configuration/components/IndexSettings.tsx:11]: No, I think they should only apply to the RadioButtons added in this PR.

**Review by macraig — APPROVED** [review]
Nice!

File: client/web/src/enterprise/codeintel/configuration/components/IndexSettings.tsx (hunk 3 above)
Comment (pdubroy) [reply client/web/src/enterprise/codeintel/configuration/components/IndexSettings.tsx:11]: I see. I'm not sure if we have a strong convention for that case yet. @valerybugakov would be the best one to ask, but he's OO this week.

What you've done here seems reasonable to me.

**Review by pdubroy — APPROVED** [review]
