### PR TITLE
search: Fix structural search not respecting file filters

### LINKED ISSUE #17568: search: New structural search path to zoekt does not respect file filters
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

The following query will hit the new structural search code path (once #17539) is merged, and will fail to filter results by file: `repo:^github\.com/kubernetes/kubernetes$ Eventf(cj, :[1]) rule:'where "zoekt" == "zoekt"' file:cronjob_controllerv2.go`

#### Expected behavior:

Only results from `cronjob_controllerv2.go` are returned.

#### Actual behavior:

Results from both `cronjob_controllerv2.go` and `cronjob_controller.go` are returned

### PR DESCRIPTION
**Pull request by camdencheek**
This fixes an issue where the new structural search code path wouldn't
respect file filters added to the query.

Fixes #17568 
Depends on #17539

### CODE REVIEW

File: cmd/frontend/graphqlbackend/textsearch.go [hunk 1]
```diff
@@ -597,7 +597,24 @@ func searchFilesInRepos(ctx context.Context, args *search.TextParameters, stream
...
+			}
+
+			err := callSearcherOverRepos(repos, nil)
+			if err != nil {
+				mu.Lock()
+				searchErr = err
+				mu.Unlock()
+			}
+		}()
+	} else if isStructuralSearch {
```
Comment (rvantonder) [inline cmd/frontend/graphqlbackend/textsearch.go:617]: I don't know how/if GH figures out this is already in the main branch and wont' conflict, but we should keep the changes in the commit and PR clean, so please rebase this branch on top of the merged changes in main.

Roughly:

```
git checkout main
git pull main
git checkout cc/frontend-zoekt-include
git merge main # make sure it merges cleanly
git force push origin cc/frontend-zoekt-include 
```

**Review by rvantonder — APPROVED** [review]
