### PR TITLE
internal/vcs: Allow @ in repo URL

### LINKED ISSUE #20257: Sourcegraph fails to fetch/update gitolite repos that have @ in their name
- **Sourcegraph version:** 3.26

#### Steps to reproduce:

For repos that contain `@` symbol in their name Sourcegraph adds `?` before `@` symbol when fetching. 

0. Suspected code https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/vcs/url.go#L80-107
1. Go playground example https://play.golang.org/p/f5fn4p64LLn
2. Regex playground https://regex101.com/r/DAuCaS/1

#### Expected behavior:

Sourcegraph should no add `?` before `@` to repo name when fetching from gitolite.

### PR DESCRIPTION
**Pull request by indradhanush**
Fixes #20257.

### CODE REVIEW

File: internal/vcs/url.go [hunk 1]
```diff
@@ -78,7 +78,17 @@ func parseScheme(rawurl string) (*url.URL, error) {
...
-var scpSyntax = regexp.MustCompile(`^([a-zA-Z0-9-._~]+@)?([a-zA-Z0-9._-]+):([a-zA-Z0-9./._-]+)(?:\?||$)(.*)$`)
+
+// usernameRe is the regexp for the username part in a repo URL. Eg: sourcegraph@
+var usernameRe = "([a-zA-Z0-9-._~]+@)"
+
+// urlRe is the regexp for the url part in a repo URL. Eg: github.com
+var urlRe = "([a-zA-Z0-9._-]+)"
+
+// repoRe is the regexp for the repo in a repo URL. Eg: sourcegraph/sourcegraph
+var repoRe = `([a-zA-Z0-9\@./._-]+)(?:\?||$)(.*)`
```
Comment (unknwon) [inline internal/vcs/url.go:89]: Why not just use `const`s 😁

File: internal/vcs/url_test.go [hunk 2]
```diff
@@ -187,6 +187,11 @@ func TestParseURL(t *testing.T) {
 			"ssh", "user-1234", "host.xz", "path/to/repo.git/",
 			"ssh://user-1234@host.xz/path/to/repo.git/", "",
 		),
+		newParseURLTest(
+			"user@host.xz:path/to/repo@domain.git/",
+			"ssh", "user", "host.xz", "path/to/repo@domain.git/",
+			"ssh://user@host.xz/path/to/repo@domain.git/", "",
+		),
```
Comment (aisbaa) [inline internal/vcs/url_test.go:194]: Suggest adding this test case as well:

```go
        newParseURLTest(
            "sourcegraph@gitolite.company.internal:service-config/runtime@east-cluster/action@test-5524",
            "ssh", "sourcegraph", "gitolite.company.internal", "runtime@east-cluster/action@test-5524",
            "ssh://sourcegraph@gitolite.company.internal:service-config/runtime@east-cluster/action@test-5524", "",
        ),
```

**Review by ryanslade — APPROVED** [review]
LGTM 👍
