### PR TITLE
a8n: Sort JSON lines returned by replacer service

### LINKED ISSUE #6910: a8n: Generated diff has not a deterministic order
## Steps to reproduce:

1. Generate a campaign preview
2. Generate a campaign preview with the exact same parameters again (need to reload between, if using UI)

#### Expected behavior:

The output looks exactly the same, also the files are sorted by a natural order

ie. not 
File1
File3
File2

#### Actual behavior:

The output order changes sometimes, and the order is random.

---

Note: this causes flackiness on the current e2e test. If this takes longer to fix lmk and I will revert the commit for now

### PR DESCRIPTION
**Pull request by mrnugget**
This fixes #6910 by sorting the diffs according to their filenames before putting them in the database. The exact order is actually not that important. It's important that the order is stable and doesn't break our E2E tests.

### CODE REVIEW

File: enterprise/internal/a8n/campaign_type.go [hunk 1]
```diff
@@ -150,15 +157,25 @@ func (c *comby) generateDiff(ctx context.Context, repo api.RepoName, commit api.
 			log15.Error("parsing diff failed", "err", err)
 			continue
 		}
+		diffs = append(diffs, fileDiffRaw{diff: parsed, raw: &raw.Diff})
+	}
+
+	sort.Slice(diffs, func(i, j int) bool {
+		return diffs[i].diff.OrigName < diffs[j].diff.OrigName &&
+			diffs[i].diff.NewName < diffs[j].diff.NewName
```
Comment (keegancsmith) [inline enterprise/internal/a8n/campaign_type.go]: this behaves a bit strangely, since you can quite easily get into a circumstances where `!(diffs[i] < diffs[j])` and `!(diffs[j] < diffs[i])`, even if `diffs[j] != diffs[i]`. IE when `!(diffs[i] < diffs[j]) && !(diffs[j] < diffs[i])` that usually implies (to the ordering) that `diffs[i] == diffs[j]` so within "equal" elements the order will be up to the algorithm and input order.

That was a long and round about way of me suggesting this diff :) :

```go
if diffs[i].diff.OrigName != diffs[j].diff.OrigName {
  return diffs[i].diff.OrigName < diffs[j].diff.OrigName
}
return diffs[i].diff.NewName < diffs[j].diff.NewName
```

Comment (mrnugget) [reply enterprise/internal/a8n/campaign_type.go]: Nice! Thanks for this!

(I just said to @tsenart: "I have to admit, I didn't put 100% into the sorting and kinda opened the PR with the hopes that you and @keegancsmith will chime in. And it looks like this went totally according to plan.")
