### PR TITLE
search backend: interpret content: value as regexp when set

### LINKED ISSUE #15638: regression: new parser does not respect regexp patterns for content:
Even when regexp is toggled the value of `content` will be treated literally. This only affects regular expression search, not literal or structural search.

Since `content` is often used to work around syntax collisions with `:`, an interim workaround for something like:

`content:^a-regexp:to:match` is omit `content`, and specify the pattern with escape the colons, e.g., `^a-regexp\:to\:match`.

I'll update affected versions after I get a fix out.

### PR DESCRIPTION
**Pull request by rvantonder**
Fixes #15638.

Unit test is sufficient to fix it. I will add ~a regression test~ an integration test in a follow up PR.

### CODE REVIEW

File: internal/search/query/transformer.go [hunk 1]
```diff
@@ -24,15 +24,24 @@ func SubstituteAliases(nodes []Node) []Node {
...
-		return Parameter{Field: field, Value: value, Negated: negated, Annotation: annotation}
-	})
+	var mapper func(nodes []Node) []Node
+	mapper = func(nodes []Node) []Node {
+		return MapParameter(nodes, func(field, value string, negated bool, annotation Annotation) Node {
+			if field == "content" {
+				if searchType == SearchTypeRegex {
+					annotation.Labels.set(Regexp)
+				} else {
+					annotation.Labels.set(Literal)
```
Comment (rvantonder) [inline internal/search/query/transformer.go:34]: Key change: when we substitute `content:` param for a pattern, we set what kind of pattern it should be interpreted as.

File: internal/search/query/transformer_test.go [hunk 2]
```diff
@@ -1,13 +1,79 @@
...
 import (
+	"encoding/json"
 	"regexp"
 	"strings"
 	"testing"
 
 	"github.com/google/go-cmp/cmp"
 )
 
+func toJSON(node Node) interface{} {
```
Comment (rvantonder) [inline internal/search/query/transformer_test.go:12]: This is just a pretty print function.

**Review by keegancsmith — APPROVED** [review]
