### PR TITLE
authz: ignore 404 API error for GitHub

### LINKED ISSUE #11007: Detect GitHub 404 errors during background permissions syncing
During background permissions syncing, 404 usually means 403 for GitHub. We need to detect and swallow such errors so we don't spam logs with "404 not found".

>15:43:32                      repo-updater | WARN Failed to sync permissions, type: 1, id: 1428, err: fetch repository permissions: request to http://127.0.0.1:3180/repos/sourcegraph/<REDACTED\>/collaborators?&page=1&per_page=100 returned status 404: Not Found

### PR DESCRIPTION
**Pull request by unknwon**
- Detects and ignores 404 API error returned by GitHub client. 
- Also adds an additional debugging argument "count" to indicate how many users are actually found during the permissions syncing, will be useful to spot token problems.

Fixes #11007

### CODE REVIEW

File: enterprise/cmd/repo-updater/authz/perms_syncer.go [hunk 1]
```diff
@@ -260,10 +263,22 @@ func (s *PermsSyncer) syncRepoPerms(ctx context.Context, repoID api.RepoID, noPe
 		return errors.Wrap(err, "wait for rate limiter")
 	}
 
-	extAccountIDs, err := provider.FetchRepoPerms(ctx, &extsvc.Repository{
-		URI:              repo.URI,
-		ExternalRepoSpec: repo.ExternalRepo,
-	})
+	extAccountIDs, err := func() ([]extsvc.AccountID, error) {
```
Comment (keegancsmith) [inline enterprise/cmd/repo-updater/authz/perms_syncer.go:266]: not really sure why the function enclosure is necessary? Can't you just special case the error and set it to nil?
