### PR TITLE
insights: minor finishing touches to make historical insights better

### LINKED ISSUE #18961: insights: data backfilling woes
Very much not happy with this and want to fix it ASAP. Something is clearly wrong here with the numbers being reported by the backfiller - from k8s.sgdev.org and sourcegraph.com:

image

image

### LINKED ISSUE #19089: Code Insights historicalEnqueuer takes a long time (maybe does not complete), takes up CPU usage running Git operations constantly
After debugging some high CPU usage bugs from gitserver on my local instance, @mrnugget & i noticed that it seems as though code insights is always reprocessing all frames in an infinite loop. I noticed that i could leave my instance idle for hours or even overnight, and i'd still see high gitserver utilisation. below is copied from PR #19088 

it seems like the enqueuer never stops re-enqueueing all frames, eg once a full 52 weeks are processed, it loops back to the beginning and starts again. 

you can see this below where 2020 loops back to 2021 and we start processing frames again.

Screenshot 2021-03-12 at 09 08 41

right now this is manifesting as gitserver spawning git log & git rev-list commands in a tight loop permanently, eating a CPU core and spending a lot of time doing GC. I'll also raise this in a separate issue & ref here.

https://user-images.githubusercontent.com/5236823/110919270-f7351300-8313-11eb-8cba-db6d067534ba.mov

### PR DESCRIPTION
**Pull request by slimsag**
This PR contains a few minor adjustments to make historical data generation for insights a bit nicer:

1. Adds tuning knobs that we can adjust through the site configuration, e.g. to make historical data generation go faster in deployments where this is desirable.
2. Caches `git.FirstEverCommit` and disables the historical insights enqueuer by default in dev environments, due to some complaints it uses a lot of resources (expected) and is annoying in dev environments.
3. Makes historical data generation 8x faster, by reducing precision: we now produce 1 data point per month for the last 6 months, instead of 1 data point per week for the last 52 weeks.
4. Wipes existing DBs clean, to reduce confusion with the historical data generation timeframe change above.

Fixes #19089
Fixes #18961

### CODE REVIEW

File: enterprise/internal/insights/background/historical_enqueuer.go [hunk 1]
```diff
@@ -77,13 +81,26 @@ func newInsightHistoricalEnqueuer(ctx context.Context, workerBaseStore *basestor
...
+		gitFirstEverCommit:   (&cachedGitFirstEverCommit{impl: git.FirstEverCommit}).gitFirstEverCommit,
 		gitFindNearestCommit: git.FindNearestCommit,
 
-		// Fill the last 52 weeks of data, recording 1 point per week.
-		//
-		framesToBackfill: 52,
-		frameLength:      7 * 24 * time.Hour,
+		// Fill e.g. the last 52 weeks of data, recording 1 point per week.
+		framesToBackfill: func() int {
+			if frames := conf.Get().InsightsHistoricalFrames; frames != 0 {
```
Comment (efritz) [inline enterprise/internal/insights/background/historical_enqueuer.go:89]: Just to check, conf.Get() is cached and calling this will only get the most recent value and not actually trigger anything, right? Because these methods are called a LOT in the iteration below.

**Review by efritz — APPROVED** [review]

File: enterprise/internal/insights/background/historical_enqueuer.go (hunk 1 above)
Comment (slimsag) [reply enterprise/internal/insights/background/historical_enqueuer.go:89]: Yes, `conf.Get()` is extremely cheap and just returns a pointer to the most recent copy of the data structure - it was intentionally designed for use exactly like this.
