### PR TITLE
fix syntax highlighting not being registered

### LINKED ISSUE #1418: Hover syntax highlighting is not working, produces error
```
Error syntax-highlighting hover markdown code block Error: Unknown language: "python"
```

### PR DESCRIPTION
**Pull request by sqs**
- prevents the contributions file (which contains no exported definitions and only has side effects) from being tree-shaked out of the production build
- imports the syntax highlighting contributions in the browser extension

fix #1418

### CODE REVIEW

File: web/src/main.tsx [hunk 1]
```diff
@@ -5,8 +5,6 @@
 
 import './polyfills'
```
Comment (felixfbecker) [inline web/src/main.tsx]: I’m confused how this could happen. Normally a plain import should never be tree shaken. Does this mean this polyfills import is tree shaken too?

Comment (felixfbecker) [reply web/src/main.tsx]: Ha, I know why: shared/package.json declares sideEffects: false, which was obviously not true
