### PR TITLE
Make ErrPublishSameBranch a terminal error and don't retry

### LINKED ISSUE #15373: ErrPublishSameBranch in reconciler should hard fail changesets
Currently we retry this 60 times, with the same result each time. I think we should not retry and do the same we do for actionImport.

### PR DESCRIPTION
**Pull request by mrnugget**
This fixes #15373 by making ErrPublishSameBranch a terminal error that
causes the reconciler to not dequeue the changeset again.

It also adds the tiny helper function `errcode.IsTerminal` (that mirrors
other functions in there) and changes the `repos.ChangesetNotFoundError`
to also be a terminal error.

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
Cool, error magic

File: enterprise/internal/campaigns/reconciler.go [hunk 1]
```diff
@@ -98,12 +99,33 @@ func (r *Reconciler) process(ctx context.Context, tx *Store, ch *campaigns.Chang
...
+		// from this function and set the NumFailures so high that the changeset is
+		// not dequeued up again.
+		msg := err.Error()
+		e.ch.FailureMessage = &msg
+		e.ch.ReconcilerState = campaigns.ReconcilerStateErrored
+		e.ch.NumFailures = ReconcilerMaxNumRetries + 999
+		return tx.UpdateChangeset(ctx, ch)
+	}
+
+	return err
```
Comment (mrnugget) [inline enterprise/internal/campaigns/reconciler.go:114]: @eseliger and I discussed that this is not _ideal_ (which everybody can tell when they see the 999 here) and came up with a possible follow-up idea: https://github.com/sourcegraph/sourcegraph/issues/15532

Comment (chrispine) [reply enterprise/internal/campaigns/reconciler.go:114]: Yep, I don't love it, either, but as long as we have the follow-up ticket, I'm fine with merging this.

**Review by chrispine — COMMENTED** [review]
👍
