### PR TITLE
search frontend: fix regex query highlighting for Firefox

### LINKED ISSUE #22937: incorrect regex pattern highlighting in Firefox
It's bizarre to me that this is only happening in Firefox, they work fine in Chrome. Broken examples:

- [`file:.*instrument.ts$ this fails for some browsers`](https://sourcegraph.com/search?q=context:global+repo:^github\.com/)
- [file:(foo|bar)](https://sourcegraph.com/search?q=context:global+file:%28foo%7Cbar%29&patternType=literal)

Screen Shot 2021-07-16 at 12 54 42 PM

### PR DESCRIPTION
**Pull request by rvantonder**
Fixes #22937

### CODE REVIEW

File: client/shared/src/search/query/decoratedToken.ts [hunk 1]
```diff
@@ -429,12 +429,7 @@ const mapRegexpMeta = (pattern: Pattern): DecoratedToken[] | undefined => {
     }
     // The AST is not necessarily traversed in increasing range. We need
     // to sort by increasing range because the ordering is significant to Monaco.
-    tokens.sort((left, right) => {
-        if (left.range.start < right.range.start) {
-            return -1
-        }
-        return 0
-    })
```
Comment (rvantonder) [inline client/shared/src/search/query/decoratedToken.ts:437]: `left` and `right` may be nondeterministically traversed/compared and Browser-dependent.

Comment (limitedmage) [reply client/shared/src/search/query/decoratedToken.ts:437]: 🤦‍♀️

**Review by limitedmage — APPROVED** [review]
