### PR TITLE
search: Fix matcher not set for comby

### LINKED ISSUE #17569: search: Not all results are returned under new structural search path
#### Steps to reproduce:
Compare the results of `repo:^github\.com/kubernetes/kubernetes$ Eventf(cj, :[1]) rule:'where "zoekt" == "zoekt"'` to `repo:^github\.com/kubernetes/kubernetes$ Eventf(cj, :[1])`. The first triggers the new code path, and returns fewer results.

This appears to be because the `Matcher` arg is not set, so comby must use the generic matcher. Setting `lang:go` in the query fixes the issue, but it's unclear yet how the current structural code path is getting the lang.

### PR DESCRIPTION
**Pull request by camdencheek**
Fixes an issue where the new code path for structural search wasn't populating the `Matcher` arg for comby, so some structural search results weren't being returned. 

Depends on #17539

### CODE REVIEW

File: cmd/searcher/search/search_structural.go [hunk 1]
```diff
@@ -266,7 +266,12 @@ func structuralSearchWithZoekt(ctx context.Context, p *protocol.Request) (matche
 		return nil, false, false, err
 	}
 
-	matches, limitHit, err = structuralSearch(ctx, zipFile.Name(), p.Pattern, p.CombyRule, p.Languages, nil, p.Repo)
+	includePatterns := make([]string, len(zoektMatches))
+	for i, match := range zoektMatches {
+		includePatterns[i] = match.FileName
+	}
```
Comment (rvantonder) [inline cmd/searcher/search/search_structural.go:272]: It's unfortunate that we're populating the `includePatterns` list just to get comby to guess the right matcher. This can be large and the work will add up, and largely avoidable. As per [comment](https://github.com/sourcegraph/sourcegraph/issues/17569#issuecomment-765610246), we can avoid it by taking a shortcut, but will need more code:

Solution Sourcegraph side:

- Look at a file name until we find one with an extension. Use that extension as the `matcher` argument and don't populate `includePatterns` at all. We don't look further than the first file we see (this is what Comby does inside).

I think you realize this, but unfortunately, for the change above, we can't just say "take only the first FileName for includePatterns" because includePatterns will restrict the file set we search in the zip. If we specify includePatterns at all, it better be all of the file paths that we've written to the zip.

Alternative solution comby-side:

At run time when finding files on disk, if there is no language matcher or file paths on CLI, use the extension of the first file path it finds.

**Review by rvantonder — APPROVED** [review]
I'm OK with merging this until we can make the improvements. Let's leave the parent issue open?
