### PR TITLE
db: Validate GitHub and GitLab authz config with enterprise/cmd/frontend/authz package

### LINKED ISSUE #2227: Config errors in external services no longer appear to show up in admin UI
~~Configuration errors in external services no longer appear in admin UI.~~

Repro:
* Add an external service with the following config:
```
{
  "authorization": {
    "ttl": "1s",
    "identityProvider": {
      "type": "oauth"
    }
  },
  "token": "$TOKEN",
  "url": "https://gitlab2.sgdev.org"
}
```
* View site admin UI (http://localhost:3080/site-admin). No error shows up, but logs show "Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe.". If you add a `log.Printf("%+v", seriousProblems)` to [this line](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/authz/init.go#L103:0), you can see the actual error (the GitLab URL doesn't exist in the `auth.providers` list in the critical site config).

This is a high-priority bug fix, because without the error, the code host configuration will fail silently, leading to unexpected behavior.

### PR DESCRIPTION
**Pull request by tsenart**
This PR fixes #2227 which was a regression introduced in #2017. Depends on #2665 being merged first.

### CODE REVIEW

**Comment by tsenart** [comment]
@beyang: Please take a look.

**Comment by beyang** [comment]
Could this use the validation logic in [`providersFromConfig`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@26136cd63585320cc69ba355bc1fbcce6498dfd6/-/blob/enterprise/cmd/frontend/internal/authz/init.go#L93:6)?

This adds additional validation code to the `db` package, but my initial reaction is (1) the validation logic already exists and it is a matter of surfacing validation errors to the UI rather than adding new validation code and (2) validation logic should live in the package that it's validating instead of a separate package, because the package itself knows best how to validate its inputs. Do either of these clash with the way we're thinking about external services / config validation?

**Comment by tsenart** [comment]
I copied the validation logic from that internal package because it’s internal. What’s the best way for us to export a validation function?

Sent via Superhuman iOS ( https://sprh.mn/?vip=tomas@sourcegraph.com )

**Comment by beyang** [comment]
I would propose exposing a registration function that lets other packages register their own validators. That way the validation logic can live in the package that requires the validation and the `cmd/frontend/db` package can remain agnostic of other packages that may depend on it as a configuration source (otherwise, it would be hard to prevent circular package import dependencies). An example of this is the [`ContributeValidator`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@26136cd/-/blob/pkg/conf/validate_custom.go#L15:6-15:25) function for the site config.

**Comment by tsenart** [comment]
> An example of this is the ContributeValidator function for the site config.

I would prefer to avoid this sort of registration pattern that requires mutation of shared global state.

What I have in mind is to export a function `ValidateGitLabAuthz(a *schema.GitLabAuthorization) error` which can be used directly by the `db` package. I'll find my way out of circular dependencies if I run into them.

**Comment by tsenart** [comment]
I opened a separate PR that untangles the internal enterprise authz package from the db package. This PR now depends on that one as it builds upon it.

**Comment by tsenart** [comment]
@beyang: CI is telling me this:

```
[2019-03-09T13:46:09Z] + echo 'Error: OSS is not allowed to import enterprise'
```

I don't think I understand why this check is in place. The dependency between OSS and Enterprise has just been made explicit through imports whereas before it was inversed using this [registration pattern](https://github.com/sourcegraph/sourcegraph/pull/2017/files#diff-e4690e26caa9d3d0aeee747eadcd526bL26) you mentioned.

File: cmd/frontend/db/external_services.go [hunk 1]
```diff
@@ -16,6 +16,8 @@ import (
 	"github.com/lib/pq"
 	"github.com/pkg/errors"
 	"github.com/sourcegraph/sourcegraph/cmd/frontend/types"
+	"github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/authz"
```
Comment (slimsag) [inline cmd/frontend/db/external_services.go]: CI is giving you the warning because this package `cmd/frontend/db` is importing our non-open-source code located in the `enterprise` directory. We strictly forbid this with the CI check because we always want people to be able to build a purely open-source version of Sourcegraph if they desire. i.e., code in `enterprise/` is not open source but all code outside that directory is.

Comment (tsenart) [reply cmd/frontend/db/external_services.go]: OK, thanks for the context. Is this the reason why we're subject to this run-time registration pattern everywhere?

Comment (beyang) [reply cmd/frontend/db/external_services.go]: Not sure if it's responsible 100%, but I think it's a major factor. It's not strictly necessary, though. I imagine we could replace every registration instance with dependency injection.

Comment (tsenart) [reply cmd/frontend/db/external_services.go]: > I imagine we could replace every registration instance with dependency injection.

YES! Lots of refactoring work to get there, but very much yes.
