### PR TITLE
batches: make the preview and detail pages more resilient

### LINKED ISSUE #29859: Better handling of Failed to Fetch error on Batch Change views
- **Sourcegraph version:** 3.35.1
- **Platform information:** I don't have this info readily available, but it's on our new Workiva deploy and I can have someone get this info or help debug if needed. 

#### Steps to reproduce:

1. Open a Batch Change (either a preview or an applied, active one)
2. Leave the tab open for a while (not sure how long it actually takes)
3. Come back to this error:

Batch Change failed to fetch error

```
Failed to load resource: net::ERR_NETWORK_CHANGED
react-dom.production.min.js:209 TypeError: Failed to fetch
    at u._subscribe (app.d26f27176a7c70acd5cc.bundle.js:1236:746118)
    at u._trySubscribe (app.d26f27176a7c70acd5cc.bundle.js:1236:732734)
    at u.subscribe (app.d26f27176a7c70acd5cc.bundle.js:1236:732542)
    at i.call (app.d26f27176a7c70acd5cc.bundle.js:1236:758018)
    at u.subscribe (app.d26f27176a7c70acd5cc.bundle.js:1236:732413)
    at i.call (app.d26f27176a7c70acd5cc.bundle.js:1236:758018)
    at u.subscribe (app.d26f27176a7c70acd5cc.bundle.js:1236:732413)
    at a.notifyNext (app.d26f27176a7c70acd5cc.bundle.js:1236:763901)
    at s._next (app.d26f27176a7c70acd5cc.bundle.js:1236:743567)
    at s.next (app.d26f27176a7c70acd5cc.bundle.js:1236:738683)
no @ react-dom.production.min.js:209
/.api/graphql?GetTemporarySettings:1 Failed to load resource: net::ERR_NETWORK_CHANGED
hostReportError.ts:7 Uncaught Error: Failed to fetch
    at new t (app.d26f27176a7c70acd5cc.bundle.js:1236:55558)
    at app.d26f27176a7c70acd5cc.bundle.js:1236:45220
    at n (app.d26f27176a7c70acd5cc.bundle.js:1236:13237)
    at app.d26f27176a7c70acd5cc.bundle.js:1236:13162
    at new Promise (<anonymous>)
    at Object.then (app.d26f27176a7c70acd5cc.bundle.js:1236:13128)
    at Object.error (app.d26f27176a7c70acd5cc.bundle.js:1236:13247)
    at w (app.d26f27176a7c70acd5cc.bundle.js:1236:837879)
    at E (app.d26f27176a7c70acd5cc.bundle.js:1236:838336)
    at e.t.error (app.d26f27176a7c70acd5cc.bundle.js:1236:838921)
```

#### Expected behavior:
I'm guessing this happens as the batch change is trying to fetch updated info periodically, and something causes it to fail.

When fetching updated batch change data/state fails, I'd expect:
- At least one retry before showing me the error, if possible.
- A more graceful handling of the error. I'd likely still want to know that something failed and that what I'm seeing may be outdated, but I don't want the entire batch change UI to be replaced by this UI. I'd much rather have a slightly outdated view still available since I often just use it as a launching point to open the individual changesets. At the very least, I should still be able to see _which_ Batch Change I was viewing.
- If enough information about the fetch failure is known, provide a more useful/immediate call-to-action. For example, if it's auth-related (session expired), provide a button to re-authenticate and then redirect me back to the page I was on (similar to GitHub's reauthentication flow).

#### Actual behavior:
After having a Batch Change open for a while, it's almost a guarantee that when I return to the tab, it will have this "Failed to Fetch" error with no other info. I'm unable to see which Batch Change I had open and I have to refresh the page.

### PR DESCRIPTION
**Pull request by LawnGnome**
This changes the default refetch mode of the detail page to be `cache-and-network`, which means that Apollo will fall back on its local cache when a network request fails. It also changes the polling query on the preview page to use Apollo with the same policy.

Fixes #29859.

## Test plan

This is well covered by our storybook, and I've manually tested the behaviour by adding this code block to the `frontend` external service handler to generate errors at will:

```go
	// Mount handlers and assets.
	sm := http.NewServeMux()
	sm.HandleFunc("/", func(rw http.ResponseWriter, r *http.Request) {
		rw.Header().Set("Content-Type", "text/plain")
		rw.WriteHeader(503)
		rw.Write([]byte("server unavailable"))
	})
	return sm, nil
```

### CODE REVIEW

File: client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.tsx [hunk 1]
```diff
@@ -70,7 +70,7 @@ export const BatchChangeDetailsPage: React.FunctionComponent<BatchChangeDetailsP
             // For subsequent requests while this page is open, make additional network
             // requests; this is necessary for `refetch` to actually use the network. (see
             // https://github.com/apollographql/apollo-client/issues/5515)
-            nextFetchPolicy: 'network-only',
+            nextFetchPolicy: 'cache-and-network',
```
Comment (LawnGnome) [inline client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.tsx:73]: I believe this is still a valid option given the bug above, and should get us the behaviour we want. (I left the comment because it's still valid with `cache-and-network`.)

Comment (eseliger) [reply client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.tsx:73]: Somehow I don't see a behavior change over what's on k8s. Does this really make a difference here?

**Review by eseliger — APPROVED** [review]

File: client/web/src/enterprise/batches/detail/changesets/ChangesetLastSynced.tsx [hunk 2]
```diff
@@ -88,14 +80,29 @@ export const ChangesetLastSynced: React.FunctionComponent<Props> = ({ changeset,
...
+                    lastUpdatedAt={lastUpdatedAt}
+                    onEnqueueChangeset={enqueueChangeset}
+                    viewerCanAdminister={viewerCanAdminister}
                 />
             </span>
         </small>
     )
 }
+
+const UpdateLoaderIcon: React.FunctionComponent<{
```
Comment (eseliger) [inline client/web/src/enterprise/batches/detail/changesets/ChangesetLastSynced.tsx:93]: Updated this because it threw a lot of logs which made it hard to fixup the integration tests

File: client/web/src/enterprise/batches/preview/BatchChangePreviewPage.story.tsx [hunk 3]
```diff
@@ -52,35 +59,63 @@ const batchSpec = (): BatchSpecFields => ({
...
+            },
+            nMatches: Number.POSITIVE_INFINITY,
+        },
+    ])
+
+const fetchBatchSpecCreate = () => batchSpecByIDLink(batchSpec())
 
-const fetchBatchSpecMissingCredentials: typeof fetchBatchSpecById = () =>
-    of({
+const fetchBatchSpecMissingCredentials = () =>
```
Comment (eseliger) [inline client/web/src/enterprise/batches/preview/BatchChangePreviewPage.story.tsx:114]: had to update this, there was a race condition in chromatic where the knobs would have outdated state because they are generated outside of a component. Very nasty bug.

File: client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.tsx (hunk 1 above)
Comment (courier-new) [reply client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.tsx:73]: So this particular change for `nextFetchPolicy` only impacts the network policy of the `refetch` method, not the polling requests (which is fine, this particular query already had `fetchPolicy: 'cache-and-network'` specified here a couple lines further up). We use `refetch` to re-request the batch change immediately after a bulk operations mutation succeeds, in order to get the latest active bulk operations. So seeing a transient network/server error here would be a super edge case; you'd have to successfully send a request to queue up a bulk operation, and then hit a network/server error instantly after that on this refetch request. But if it did happen, we wouldn't throw the big error screen anymore. The user just wouldn't see the "active bulk operation" banner.

More generally, making this change in the other places in this PR _does_ seem to have the effect I was expecting to see locally, at least. Before this, the polling would stop and the error boundary would be shown. After this, the polling does not stop and the page does not jump to the error boundary. I tested using the suggestion from Adam's PR description:

https://user-images.githubusercontent.com/8942601/155389976-08c0eaeb-35bc-42e4-9a85-081d90385264.mov

Is this not what you were observing in behavior?

**Review by courier-new — APPROVED** [review]
Thanks for troubleshooting the storybook/integration test issues. 🙏

**Comment by eseliger** [comment]
I am seeing that behavior, but I wasn't seeing a change over the previous behavior for the details page 😬 But makes sense to me now, it's not the polling but explicit refetches, got it!
