### PR TITLE
fix(buildchecker): do not consider cron builds

### LINKED ISSUE #34470: buildchecker: do not include cron job builds
Over the weekend we had a branch lock because the release branch healthcheck failed 3x

### PR DESCRIPTION
**Pull request by burmudar**
Builchecker should not lock the main branch when scheduled/cron builds failed consequtively

Closes  #34470
## Test plan
Ran unit tests

### CODE REVIEW

File: dev/buildchecker/failures.go [hunk 1]
```diff
@@ -23,6 +23,10 @@ func findConsecutiveFailures(
 	var consecutiveFailures int
 	var build buildkite.Build
 	for buildsScanned, build = range builds {
+		if isBuildScheduled(build) {
+			// we do not consider scheduled builds like Healthcheck
```
Comment (jhchabran) [inline dev/buildchecker/failures.go:27]: nit: can we provide a link there? it'll really help future readers to understand what the heck are we talking about (healthcheck is really generic as a name).

File: dev/buildchecker/checker.go [hunk 2]
```diff
@@ -44,6 +44,11 @@ func CheckBuilds(ctx context.Context, branch BranchLocker, teammates team.Teamma
 	// Scan for first build with a meaningful state
 	var firstFailedBuildIndex int
 	for i, b := range builds {
+		if isBuildScheduled(b) {
+			// a Scheduled build like Healtcheck should not be considered as part of the set that determines whether
+			// main is locked
```
Comment (jhchabran) [inline dev/buildchecker/checker.go:49]:
```suggestion
			// main is locked.
```

**Review by jhchabran — APPROVED** [review]
Nice, this is going to save a few locks each week 🙏

File: dev/buildchecker/failures.go (hunk 1 above)
Comment (burmudar) [reply dev/buildchecker/failures.go:27]: Good point 💯  Lemme add it

File: dev/buildchecker/checker.go [hunk 3]
```diff
@@ -103,6 +110,10 @@ func CheckBuilds(ctx context.Context, branch BranchLocker, teammates team.Teamma
 	return
 }
 
+func isBuildScheduled(build buildkite.Build) bool {
+	return build.Source != nil && *build.Source == "scheduled"
+}
```
Comment (bobheadxi) [inline dev/buildchecker/checker.go:115]: THANK YOU
