### PR TITLE
Fix GitLab code intelligence on merge requests

### LINKED ISSUE #8134: Code views are not detected on merge requests on gitlab.com
No code intelligence on code views, eg. https://gitlab.com/gitlab-org/gitlab/-/merge_requests/22932/diffs?view=inline

This is because we detect a `GitLabPageKind.Other`:

image

We [expect](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b12f5679e669363e27c74f5dcb8b818478a412a0/-/blob/browser/src/libs/gitlab/scrape.ts#L46-55) the pathname to match `${owner}/${projectName}/merge_requests`, but it's `${owner}/${projectName}/-/merge_requests`. This appears to be a recent change.

### PR DESCRIPTION
**Pull request by lguychard**
Fixes #8134

More recent DOM changes broke code intelligence on GitLab MRs again:
- The `.js-source-branch` link, from which we parsed the base repo name, is no longer present on the `/diffs` page of merge requests.
    - Fixed this by removing `getDiffPageInfo()`, and resolving repo names and commit IDs solely through the API. This is simpler and more robust.
- The file path, originally contained in the dataset of the `.file-title-name` element, is now only in the `title`.
    - Changed `getFilePathsFromCodeView()`to handle this case.

### CODE REVIEW

**Comment by felixfbecker** [comment]
> The file path, originally contained in the dataset of the .file-title-name element, is now only in the title.

This sounds like something we could make an MR to Gitlab for to add back, with an inline comment "The Sourcegraph integration reads this" so that it doesn't get removed accidentally. While the API is the most reliable, A `dataset` seems much more reliable to me than a `title`.

File: browser/src/libs/gitlab/api.ts [hunk 1]
```diff
@@ -43,24 +44,73 @@ const get = <T>(url: string): Observable<T> =>
...
+    > =>
+        diffID
+            ? get<DiffVersionsResponse>(
+                  buildURL(owner, projectName, `/merge_requests/${mergeRequestID}/versions/${diffID}`)
+              ).pipe(
+                  tap(resp => console.log('diff ' + diffID, resp)),
+                  map(({ base_commit_sha }) => base_commit_sha)
+              )
+            : of(undefined),
+    params => JSON.stringify(params)
```
Comment (felixfbecker) [inline browser/src/libs/gitlab/api.ts]: `JSON.stringify()` ordering depends on the order of object properties, so this is not safe (needs to use a manual function, or `object-hash`)

**Comment by felixfbecker** [comment]
Actually, just realised that the `dataset` attribute is also just `data-title`, so not safer in any way.

File: browser/src/libs/gitlab/api.ts [hunk 2]
```diff
@@ -43,24 +44,74 @@ const get = <T>(url: string): Observable<T> =>
         switchMap(response => response.json())
     )
 
+const getRepoNameFromProjecID = memoizeObservable(
```
Comment (attfarhan) [inline browser/src/libs/gitlab/api.ts]:
```suggestion
const getRepoNameFromProjectID = memoizeObservable(
```

File: browser/src/libs/gitlab/api.ts [hunk 3]
```diff
@@ -43,24 +44,74 @@ const get = <T>(url: string): Observable<T> =>
...
+    }: Pick<GitLabInfo, 'owner' | 'projectName' | 'rawRepoName'> & {
+        mergeRequestID: string
+        diffID?: string
+    }): Observable<Omit<FileInfo, 'filePath' | 'baseFilePath'>> =>
+        zip(
+            get<MergeRequestResponse>(buildURL(owner, projectName, `/merge_requests/${mergeRequestID}`)),
+            getBaseCommitIDFromDiffID({ owner, projectName, mergeRequestID, diffID })
+        ).pipe(
+            switchMap(([{ diff_refs, source_project_id }, baseCommitIDFromDiffID]) =>
+                getRepoNameFromProjecID(source_project_id).pipe(
```
Comment (attfarhan) [inline browser/src/libs/gitlab/api.ts]:
```suggestion
                getRepoNameFromProjectID(source_project_id).pipe(
```

File: browser/src/libs/gitlab/api.ts (hunk 2 above)
Comment (felixfbecker) [reply browser/src/libs/gitlab/api.ts]: image

File: browser/src/libs/gitlab/api.ts [hunk 4]
```diff
@@ -43,24 +44,74 @@ const get = <T>(url: string): Observable<T> =>
...
+        mergeRequestID,
+        diffID,
+    }: Pick<GitLabInfo, 'owner' | 'projectName'> & { mergeRequestID: string; diffID?: string }): Observable<
+        string | undefined
+    > =>
+        diffID
+            ? get<DiffVersionsResponse>(
+                  buildURL(owner, projectName, `/merge_requests/${mergeRequestID}/versions/${diffID}`)
+              ).pipe(
+                  tap(resp => console.log('diff ' + diffID, resp)),
```
Comment (attfarhan) [inline browser/src/libs/gitlab/api.ts]: Is this log intentional?

Comment (lguychard) [reply browser/src/libs/gitlab/api.ts]: Oops, no, good catch. Thanks!
