### PR TITLE
JetBrains: Add a more advanced result list

### LINKED ISSUE #34367: JetBrains: Basic search results list
In the current prototype, this is just a plain list that often crashes. For next iteration we want to:

- Have basic styling that resembles the rough layout of our first design sketches
- Allows basic keyboard navigations (arrow up/down)
- Efficiently handles larger amounts of data (pagination?)
- Doesn't break if the search result is of type `repo`.

### PR DESCRIPTION
**Pull request by philipp-spiess**
Closes #34367

This PR adds an advanced result list. It can already do the following:

- Render the search results as one row per match
- Show information about the line number, repo name, and file name, file name
- Allow keyboard navigation via arrow up/arrow down navigation and clicks
- Render the search highlights inside the text
- Wire up some callbacks that we can later use to instruct the Java side to render and open the file

## Test plan

Verified manually, here's an example video:

https://user-images.githubusercontent.com/458591/166227137-43895e1f-7df0-468c-9149-bf5e8ba72b2f.mov

## App preview:

- [Web](https://sg-web-ps-jetbrains-result-list.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-acjtnzucmn.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

File: client/jetbrains/webview/src/search/results/SearchResultList.tsx [hunk 1]
```diff
@@ -0,0 +1,148 @@
...
+
+    useEffect(() => {
+        document.addEventListener('keydown', onKeyDown, { capture: true })
+        return () => document.removeEventListener('keydown', onKeyDown, { capture: true })
+    })
+
+    return (
+        <div className={styles.list} ref={scrollViewReference}>
+            {results.map((match: SearchMatch) =>
+                match.type === 'content' ? (
```
Comment (philipp-spiess) [inline client/jetbrains/webview/src/search/results/SearchResultList.tsx:137]: We currently _only_ render file content matches. This will need some more work later.

File: client/jetbrains/webview/src/search/results/utils.ts [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+    const [matchId, lineId] = id.split('-#-')
+    return [matchId, parseInt(lineId, 10)]
+}
+
+export function getElementFromId(id: string): null | Element {
+    // eslint-disable-next-line unicorn/prefer-query-selector
+    return document.getElementById(`search-result-list-item-${id}`)
+}
+
+export function getNextResult(currentElement: Element): null | string {
```
Comment (vdavid) [inline client/jetbrains/webview/src/search/results/utils.ts:31]: Not a huge deal, but maybe DRYer to use this for both next and previous?

```ts
export function getNextResult(currentElement: Element, reverse: boolean = false): null | string {
    const next = !reverse ? currentElement.nextElementSibling : currentElement.previousElementSibling
    if (next) {
        if (next.id) {
            return next.id.replace('search-result-list-item-', '')
        }
        return getNextResult(next)
    }
    return null
}
```

File: client/jetbrains/webview/src/search/results/FileSearchResult.tsx [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+            >
+                <div className={styles.lineCode}>
+                    <TrimmedCodeLineWithHighlights line={line} />
+                </div>
+                <div className={classNames(styles.lineLineNumber, 'text-muted')}>{line.lineNumber}</div>
+            </div>
+        )
+    })
+
+    const repoDisplayName = result.repository
```
Comment (vdavid) [inline client/jetbrains/webview/src/search/results/FileSearchResult.tsx:54]: (I wanted to nitpick on the mixed use of "repo" and "repository" but the duality actually comes from other parts of our repo(sitory) :D)

**Review by vdavid — APPROVED** [review]
Looks great to me! Result caching is a great idea, we'll definitely need that later.
This is very cool overall! :)
I've left a few very minor comments, feel free to change or leave any of them.

File: client/jetbrains/webview/src/search/App.tsx [hunk 4]
```diff
@@ -33,74 +55,70 @@ export const App: React.FunctionComponent = () => {
...
-                        authenticatedUser={null}
-                        searchContextsEnabled={true}
-                        showSearchContext={true}
-                        showSearchContextManagement={false}
-                        defaultSearchContextSpec="global"
-                        setSelectedSearchContextSpec={setSelectedSearchContextSpec}
-                        selectedSearchContextSpec={undefined}
-                        fetchSearchContexts={() => {
-                            throw new Error('fetchSearchContexts')
+            <div className={classNames('theme-dark', styles.root)}>
```
[the remark this answers is not in the document]
Comment (philipp-spiess) [reply client/jetbrains/webview/src/search/App.tsx:66]: Oh thanks for spotting. I'll remove this :)
