### PR TITLE
Fix error in reading config

### LINKED ISSUE #7866: Log spam in e2e tests: Discarding contributions: evaluating expressions or templates failed.
The root cause should be investigated.

https://buildkite.com/sourcegraph/sourcegraph-e2e/builds/3845#0296dbab-5587-411f-ba21-5ad70dfdcd3d/157-176

### PR DESCRIPTION
**Pull request by eseliger**
Closes #7866

This is a fix for the root cause of the noise reported in #7866 
When reading a config value here: 
`{ action: ACTION_ID, when: 'get(config.experimentalFeatures, "searchStats")' },`
the parser did not account for experimentalFeatures being not an object (here `null`). For properties on objects that don't exist, we return undefined instead now and the errors are gone

### CODE REVIEW

**Comment by felixfbecker** [comment]
Nice find! I am a bit puzzled what the purpose of `get()` is if we support property access. @sqs?
This would make property access basically always mirror `?.` behavior.
Pros: No `&&` needed
Cons: Might hide a typo as there's no error which property was wrong

**Comment by felixfbecker** [comment]
While waiting for @sqs's response: @efritz it seems like this was introduced with your check for the feature flag of badges. Could you do the simple fix to check for the presence of the object first in the expression? I believe `&&` should work.

**Comment by sqs** [comment]
@felixfbecker It is for dynamic property access, similar to the difference between `a.b` and `a[b]` in JavaScript.

File: shared/src/api/client/context/expr/evaluator.ts [hunk 1]
```diff
@@ -46,7 +46,7 @@ export const EMPTY_COMPUTED_CONTEXT: ComputedContext = {
 }
 
 const FUNCS: { [name: string]: (...args: any[]) => any } = {
-    get: (obj: any, key: string): any => obj[key],
+    get: (obj: any, key: string): any => obj?.[key] ?? undefined,
```
Comment (felixfbecker) [inline shared/src/api/client/context/expr/evaluator.ts]: Does the `?? undefined` serve a purpose?

Comment (eseliger) [reply shared/src/api/client/context/expr/evaluator.ts]: I wanted to always fall back to `undefined`, never `null`, since `null` makes a statement imo, and the value itself was not found(`undefined`), not `null` 
if that sentence is somewhat understandable 😁

Comment (felixfbecker) [reply shared/src/api/client/context/expr/evaluator.ts]: I see. I would have made it behave the same as `?.`. But doesn't really matter
