### PR TITLE
fix flash of unstyled content in browser extension

### LINKED ISSUE #4033: Chrome extension flashes your logo for a brief moment
- **Sourcegraph version:** Sourcegraph extension 19.4.26.1859
- **Platform information:** Chrome 74 on Mac

#### Steps to reproduce:

1. Install the Sourcegraph extension
2. Load a GitHub PR

#### Expected behavior:

Your logo not being flashed for a brief moment

#### Actual behavior:

Your logo flashes into view for a brief moment

Apologies for the .zip instead of a .gif, Github doesn't support video uploads and I didn't want to downsample to a gif. It's between seconds 7 and 8.

image

[Screen Recording 2019-05-15 at 9.16.19 AM.zip](https://github.com/sourcegraph/sourcegraph/files/3182658/Screen.Recording.2019-05-15.at.9.16.19.AM.zip)

### PR DESCRIPTION
**Pull request by sqs**
The elements were being injected before the stylesheet finished loading (even though it is a local stylesheet, it still takes a brief moment to load). This fixes it so that the injection waits until the styles are loaded.

fix #4033

### before and after videos

- [BEFORE (video)](https://drive.google.com/file/d/19Vf-mX12DSUbgSxhJaXH_UE4HORsIrdM/view?usp=sharing): Watch for the jitter in the top navbar of Bitbucket Server and GitHub.
- [AFTER (video)](https://drive.google.com/file/d/1GfLz0y43BCIEMlUSPnyV2jtoxSisRiWA/view?usp=sharing): No jitter!

### CODE REVIEW

File: browser/src/extension/scripts/inject.tsx [hunk 1]
```diff
@@ -73,19 +73,17 @@ async function main(): Promise<void> {
...
     // annoying flash/jitter when the stylesheet loads shortly thereafter).
-    await new Promise(resolve => {
-        if (!isSourcegraphServer && !document.getElementById('ext-style-sheet')) {
-            const styleSheet = document.createElement('link')
-            styleSheet.id = 'ext-style-sheet'
-            styleSheet.rel = 'stylesheet'
-            styleSheet.type = 'text/css'
-            styleSheet.href = browser.extension.getURL('css/style.bundle.css')
-            styleSheet.onload = () => resolve()
+    if (!isSourcegraphServer && !document.getElementById('ext-style-sheet')) {
```
Comment (sqs) [inline browser/src/extension/scripts/inject.tsx]: Would it ever happen that the `#ext-style-sheet` element exists BUT the stylesheet has not been loaded? For example, if you quickly navigate to a new PJAX page? Or some other more common case? If so, this change reintroduces the flash/jitter in those cases because it makes it only wait if the element doesn't exist.

Comment (sqs) [reply browser/src/extension/scripts/inject.tsx]: Actually, that bug exists in my original code too.

Comment (sqs) [reply browser/src/extension/scripts/inject.tsx]: (Probably not worth fixing right now, since it is a rare case and tricky to handle, unless you can think of a good fix.)

Comment (felixfbecker) [reply browser/src/extension/scripts/inject.tsx]: Good point, I think that is likely to happen on GitHub. It's not hard to fix

**Comment by sqs** [comment]
@felixfbecker 	I don't know if/how it needs to be fixed for Phabricator. Can you look into that? Filed https://github.com/sourcegraph/sourcegraph/issues/4549.

**Comment by felixfbecker** [comment]
Phabricator's inject script is in browser/src/libs/phabricator/extension.tsx

File: browser/src/extension/scripts/inject.tsx (hunk 1 above)
Comment (felixfbecker) [reply browser/src/extension/scripts/inject.tsx]: Pushed, please take a look

**Comment by sqs** [comment]
nice technique @felixfbecker!
