### PR TITLE
Prevent native integration & bext conflict

### LINKED ISSUE #4900: Browser extension & native integration conflicting on Bitbucket Server
- **Sourcegraph version:** 3.6.0-rc.1

#### Steps to reproduce:

1. Point your Sourcegraph extension to https://k8s.sgdev.org
1. Go to https://bitbucket.sgdev.org/projects/SOUR/repos/vegeta/browse/encode.go?at=master#88
2. Hover over the `NewCSVEncoder` symbol and move the pointer horizontally over the symbol until two tooltips pop-up.

#### Expected behavior:

Only one tooltip shows up.

#### Actual behavior:

Two tooltips are shown, although with different content (note how the one in the back has the type of the argument as `io.Writer` and the one in the front only `Writer`).

image

### PR DESCRIPTION
**Pull request by lguychard**
Fixes #4900 (release bocker for 3.6)

The execution order of the [callback passed to `AJS.toInit()`](https://sourcegraph.com/github.com/sourcegraph/bitbucket-server-plugin/-/blob/src/main/resources/js/sourcegraph-bitbucket.js#L1-25) by the Bitbucket Server plugin and the browser extension content script can be racy, leading to conflicts between the browser extension and the Bitbucket Server native integration.

This fixes these conflicts by introducing a custom event sent by the native integration upon activation, signaling that browser extension resources should be cleaned up.

**Test plan**: I verified that there were no conflicts when:
- The native integration is activated before the browser extension.
- The native integration is activated later during the lifetime of the content script.

### CODE REVIEW

File: browser/src/integration/integration.tsx [hunk 1]
```diff
@@ -30,6 +31,7 @@ async function init(): Promise<void> {
     injectExtensionMarker()
     // TODO handle subscription
     await injectCodeIntelligence(IS_EXTENSION)
+    document.dispatchEvent(new CustomEvent<{}>(NATIVE_INTEGRATION_ACTIVATED))
```
Comment (felixfbecker) [inline browser/src/integration/integration.tsx]: Is there a reason why we would dispatch this at the end of the function? Wouldn't that delay notifying the bext, especially since there is an `await`?

File: browser/src/libs/sourcegraph/inject.tsx [hunk 2]
```diff
@@ -1,5 +1,12 @@
 export const EXTENSION_MARKER_ID = 'sourcegraph-app-background'
 
+/**
+ * A custom native integration <-> browser extension event used to free
+ * browser extension subscriptions when the native integration gets activated
+ * on the page, so as to avoid conflicts such as duplicate UI elements.
+ */
+export const NATIVE_INTEGRATION_ACTIVATED = 'sourcegraph:native-integration-activated'
```
Comment (felixfbecker) [inline browser/src/libs/sourcegraph/inject.tsx]: What is the difference between this and `dispatchSourcegraphEvents()`/`signalBrowserExtensionInstalled()`? The mechanism introduced in this PR seems very similar to what we do between the Sourcegraph web app and the bext for notification, except those are not based on unsubscription but on giving some time to report and else assuming no bext is installed. However, in both mechanisms a `CustomEvent` is dispatched to get notified.

Another difference I notice is that `signalBrowserExtensionInstalled()` waits for the DOM to be ready, which I guess may otherwise make the event go into the void?

Since this one does not use any delay/timeout, can there be a situation where for a short period of time both integrations add buttons or show loading tooltips, only for one of them to (hopefully) then remove them again?

File: browser/src/extension/scripts/inject.tsx [hunk 3]
```diff
@@ -43,14 +48,24 @@ async function main(): Promise<void> {
...
+    const nativeIntegrationActivationEventReceived = new Promise<boolean>(resolve =>
+        document.addEventListener(
+            NATIVE_INTEGRATION_ACTIVATED,
+            () => {
+                console.log('Native integration activation event received')
+                resolve()
+            },
+            { once: true }
+        )
+    )
```
Comment (felixfbecker) [inline browser/src/extension/scripts/inject.tsx]: You could also write this as
```ts
subscriptions.add(fromEvent(document, NATIVE_INTEGRATION_ACTIVATED).pipe(first()).subscribe(() => subscriptions.unsubscribe()))
```
or with `.toPromise()` if you like the `await` way

File: browser/src/extension/scripts/inject.tsx [hunk 4]
```diff
@@ -43,14 +48,24 @@ async function main(): Promise<void> {
...
-    if (document.getElementById(EXTENSION_MARKER_ID)) {
+    // If the native integration was activated before the content script, we can
+    // synchronously check for the presence of the extension marker.
+    if (document.getElementById(EXTENSION_MARKER_ID) !== null) {
         console.log('Sourcegraph native integration is already running')
         return
     }
+    // If the extension marker isn't present, listen for a custom event sent by the native
+    // integration to signal its activation.
+    const nativeIntegrationActivationEventReceived = new Promise<boolean>(resolve =>
```
Comment (felixfbecker) [inline browser/src/extension/scripts/inject.tsx]:
```suggestion
    const nativeIntegrationActivationEventReceived = new Promise<void>(resolve =>
```

File: browser/src/integration/integration.tsx (hunk 1 above)
Comment (lguychard) [reply browser/src/integration/integration.tsx]: My thinking was to only dispatch this if the native integration was *successfully* activated (eg `injectCodeIntelligence()` didn't throw), to avoid a broken state where neither works.

Comment (felixfbecker) [reply browser/src/integration/integration.tsx]: Hmm I don't think that's a good idea, because:
- Falling back to the other kind of integration is unlikely to avoid whatever unexpected error occurred in the first integration (e.g. if it's a bug in the integration)
- If it throws, it can still be partially initialised, resulting in one integration fully active and the other partially active. I'd rather have none working and the primary one in a clear failure state, for example I would rather have no buttons and hovers than double buttons and double hovers
- With added delay, there is a larger window of time where both are potentially active at the same and could break each other

File: browser/src/libs/sourcegraph/inject.tsx (hunk 2 above)
Comment (lguychard) [reply browser/src/libs/sourcegraph/inject.tsx]: You're right that this is a similar mechanism to `dispatchSourcegraphEvents()`, except with `dispatchSourcegraphEvents()`.

Please see my latest changes:
- Since the native integration only dispatches `NATIVE_INTEGRATION_ACTIVATED` if `#sourcegraph-app-background` doesn't exist, and the browser extension registers an event listener synchronously after injecting `#sourcegraph-app-background`, the event is guaranteed to never "go into the void".
- The event is dispatched synchronously before calling `injectCodeIntelligence()`, the browser extension subscription is cleaned up before the native integration starts adding hovers / UI elements, which means there is no short period of time where both are contributing UI elements.

I don't see the need for a delay/timeout here. In the webapp it's simply used to assume that the browser extension isn't installed if it hasn't sent an event after 500ms. Here, we *always* want to clean up browser extension subscriptions when the native integration gets activated.
