### PR TITLE
extensibility: make workspace roots observable

### LINKED ISSUE #19225: Workspace URI is not updated in repo page when commit is changed
#### Steps to reproduce:

1. Navigate to a repo page (e.g. https://sourcegraph.com/github.com/sourcegraph/sourcegraph)
2. Change commit in dropdown menu

#### Expected behavior:

Repo page re-renders, code insights are updated

#### Actual behavior:

Code insights disappear

<details>
<summary>GIF</summary>

</details>

### PR DESCRIPTION
**Pull request by tjkandala**
Fixes #19225

<details>
<summary>After GIF</summary>

</details>

### CODE REVIEW

File: client/shared/src/hover/actions.ts [hunk 1]
```diff
@@ -63,7 +63,7 @@ export function getHoverActions(
                 ),
             getWorkspaceRoots: () =>
                 from(extensionsController.extHostAPI).pipe(
-                    switchMap(extensionHostAPI => extensionHostAPI.getWorkspaceRoots())
+                    switchMap(extensionHostAPI => wrapRemoteObservable(extensionHostAPI.getWorkspaceRoots()))
```
Comment (tjkandala) [inline client/shared/src/hover/actions.ts:66]: Should we only take the first emission for finding definition URL? I don't think there's risk of triggering and cancelling a lot of requests at the moment, since there's only one workspace root at a time in the webapp, and usually 2 at most on code hosts (base and head)

Comment (felixfbecker) [reply client/shared/src/hover/actions.ts:66]: Is there the possibility of triggering go to definition before any workspace root was registered? If so then it would need to subscribe I think

**Review by felixfbecker — APPROVED** [review]

**Review by muratsu — APPROVED** [review]

File: client/shared/src/hover/actions.ts (hunk 1 above)
Comment (tjkandala) [reply client/shared/src/hover/actions.ts:66]: It shouldn't be possible in the web app, but it is a good consideration since that's a possible regression
