### PR TITLE
sg: redesign checks functionality

### LINKED ISSUE #31039: sg "docker" check doesn't seem to work
`sg` seems to think Docker is running, but then minio fails because it's not:

```
$ sg start enterprise-codeintel
✅ Check "docker" success!
...
--------------------------------------------------------------------------------
Failed to build minio: 'bash -c mkdir -p $MINIO_LOGS
mkdir -p $MINIO_DISK
CACHE=true ./docker-images/minio/build.sh >$MINIO_LOG_FILE 2>&1' failed: : exit status 1
--------------------------------------------------------------------------------

$ cat $HOME/.sourcegraph-dev/logs/minio/minio.log
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### PR DESCRIPTION
**Pull request by mrnugget**
This does multiple things to fix https://github.com/sourcegraph/sourcegraph/issues/31043

- Move Sourcegraph-independent check functionality into `internal/check` (including helpers like `check.Version`, `check.Any`, etc.)
- Remove the previous `run.Check` and removes the distinction between built-in and config checks
- Remove all checks from `sg.config.yaml`. Old `sg` versions will run into "WARNING: check not found" messages, so it's kinda backwards-compatible
- Moves all Sourcegraph and sg-related check code into a single file, `checks.go`
- Adds a helper to safely get a check by name
- Fixes #31039 by checking that Docker is running, but _only_ in `sg doctor`, not in `setup`.
- Changes output of `sg doctor` to be more readable
- Move some functionality into `usershell` so the code is in a leaf package

## Test plan

- Run `go run . doctor` locally with Redis/Postgres/Docker on and off
- Run `go run . setup` locally with Redis/Postgres/Docker on and off

### CODE REVIEW

File: dev/sg/checks.go [hunk 1]
```diff
@@ -0,0 +1,321 @@
...
+
+			failed = append(failed, name)
+		} else {
+			p.Complete(output.Linef(output.EmojiSuccess, output.StyleSuccess, "Check %q success!", name))
+		}
+	}
+
+	if len(failed) == 0 {
+		return nil
+
```
Comment (jhchabran) [inline dev/sg/checks.go:99]:
```suggestion
```

File: dev/sg/internal/usershell/usershell.go [hunk 2]
```diff
@@ -64,3 +66,17 @@ func Context(ctx context.Context) (context.Context, error) {
 	}
 	return context.WithValue(ctx, key{}, userCtx), nil
 }
+
+// Cmd returns a command wrapped in a new shell process, enabling
+// changes added by various checks to be run. This negates the new to ask the
+// user to restart sg for many checks.
+func Cmd(ctx context.Context, cmd string) *exec.Cmd {
```
Comment (jhchabran) [inline dev/sg/internal/usershell/usershell.go:73]: Neat, thanks!

**Review by jhchabran — APPROVED** [review]
LGTM!
