### PR TITLE
batches: temporarily hide global stats bar for namespaced list

### LINKED ISSUE #45075: Batch Changes stat bar shows incorrect data for organizations
The batch changes stat bar is meant to display batch changes usage applicable to the user or organization. Right now, we display the global list, which is incorrect for non-site administrators since they don't have visibility into all Batch Changes.

This was particularly confusing for me when I creating a new organization and I noticed that the stats bar was showing 8 batch changes instead of zero.

[Context](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1670001603822349)

### PR DESCRIPTION
**Pull request by adeola-ak**
Closes #45075

Temporarily hiding the global batch change stats bar on the namespaced list as the resolver currently does not support computing these stats in a specific namespace.

## Test plan
ensured the stats bar is only shown on global list

## App preview:

- [Web](https://sg-web-aa-remove-global-stats-bar.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

File: client/web/src/enterprise/batches/list/BatchChangeStatsBar.tsx [hunk 1]
```diff
@@ -40,7 +43,7 @@ export const BatchChangeStatsBar: React.FunctionComponent<React.PropsWithChildre
         return null
```
Comment (eseliger) [inline client/web/src/enterprise/batches/list/BatchChangeStatsBar.tsx:43]: It would be great if we wouldn't be loading the stats at all, if we're not going to render them then anyways.

File: client/web/src/enterprise/batches/list/BatchChangeListPage.tsx [hunk 2]
```diff
@@ -192,7 +192,7 @@ export const BatchChangeListPage: React.FunctionComponent<React.PropsWithChildre
             )}
             {selectedTab === 'batchChanges' && (
                 <>
-                    <BatchChangeStatsBar className="mb-4" />
+                    <BatchChangeStatsBar className="mb-4" namespaceID={namespaceID} />
```
Comment (eseliger) [inline client/web/src/enterprise/batches/list/BatchChangeListPage.tsx:195]:
```suggestion
                    {!namespaceID && <BatchChangeStatsBar className="mb-4" />}
```

See comment further down, this would get around that problem.

File: client/web/src/enterprise/batches/list/BatchChangeStatsBar.tsx [hunk 3]
```diff
@@ -18,9 +18,12 @@ import styles from './BatchChangeStatsBar.module.scss'
 
 interface BatchChangeStatsBarProps {
     className?: string
+    namespaceID?: string
 }
 
-export const BatchChangeStatsBar: React.FunctionComponent<React.PropsWithChildren<BatchChangeStatsBarProps>> = () => {
+export const BatchChangeStatsBar: React.FunctionComponent<React.PropsWithChildren<BatchChangeStatsBarProps>> = ({
+    namespaceID,
```
Comment (BolajiOlajide) [inline client/web/src/enterprise/batches/list/BatchChangeStatsBar.tsx:25]: We don't need this prop anymore? It's safe to remove it and also the L21.

**Review by BolajiOlajide — APPROVED** [review]

File: client/web/src/enterprise/batches/list/BatchChangeStatsBar.tsx [hunk 4]
```diff
@@ -20,7 +20,7 @@ interface BatchChangeStatsBarProps {
     className?: string
 }
 
-export const BatchChangeStatsBar: React.FunctionComponent<React.PropsWithChildren<BatchChangeStatsBarProps>> = () => {
+export const BatchChangeStatsBar: React.FunctionComponent<React.PropsWithChildren<BatchChangeStatsBarProps>> = ({}) => {
```
Comment (BolajiOlajide) [inline client/web/src/enterprise/batches/list/BatchChangeStatsBar.tsx:23]:
```suggestion
export const BatchChangeStatsBar: React.FunctionComponent<React.PropsWithChildren<BatchChangeStatsBarProps>> = () => {
```

File: client/web/src/enterprise/batches/list/BatchChangeStatsBar.tsx [hunk 5]
```diff
@@ -40,7 +40,7 @@ export const BatchChangeStatsBar: React.FunctionComponent<React.PropsWithChildre
         return null
     }
 
-    return (
+    return !namespaceID ? (
```
Comment (BolajiOlajide) [inline client/web/src/enterprise/batches/list/BatchChangeStatsBar.tsx:43]:
```suggestion
    return (
```

File: client/web/src/enterprise/batches/list/BatchChangeStatsBar.tsx [hunk 6]
```diff
@@ -106,5 +106,5 @@ export const BatchChangeStatsBar: React.FunctionComponent<React.PropsWithChildre
                 </div>
             </div>
         </div>
-    )
+    ) : null
```
Comment (BolajiOlajide) [inline client/web/src/enterprise/batches/list/BatchChangeStatsBar.tsx:109]:
```suggestion
    )
```

File: client/web/src/enterprise/batches/list/BatchChangeStatsBar.tsx (hunk 4 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/list/BatchChangeStatsBar.tsx:23]: We do not need to make any change to this component, since we aren't rendering at all and you've removed the `namespaceID` prop.

**Review by courier-new — APPROVED** [review]
