### PR TITLE
Fix history display/clear, add history load in VSCode

### LINKED ISSUE #51101: cody bug: vsce chat history UI is broken
The UI was working previously with the old chat layout: https://github.com/sourcegraph/sourcegraph/pull/50036

Image

Currently looks broken after we have removed the bubble chat layout:

Image

### PR DESCRIPTION
**Pull request by SuperAuguste**
Closes #51101 

## Test plan

Tested all sorts of variations (empty and save, loading and saving different sessions over and over again, etc.) locally in VSCode and everything seems fine.

### CODE REVIEW

File: client/cody/src/chat/ChatViewProvider.ts [hunk 1]
```diff
@@ -84,14 +84,37 @@ export class ChatViewProvider implements vscode.WebviewViewProvider, vscode.Disp
         this.configurationChangeEvent.fire()
     }
 
-    public clearAndRestartSession(): void {
+    public async clearAndRestartSession(): Promise<void> {
```
Comment (abeatrix) [inline client/cody/src/chat/ChatViewProvider.ts:87]: There are a few places giving type errors after changing this into an async function.

File: client/cody/src/chat/ChatViewProvider.ts [hunk 2]
```diff
@@ -84,14 +84,37 @@ export class ChatViewProvider implements vscode.WebviewViewProvider, vscode.Disp
...
+        await this.saveChatHistory()
```
Comment (abeatrix) [inline client/cody/src/chat/ChatViewProvider.ts:88]: Do we need to saveChatHistory on every steps since we have already performed `save` on each Completion End? 🤔 
https://github.com/sourcegraph/sourcegraph/blob/f46f23ca57afb79705f1a90a9e797284c4be8c1f/client/cody/src/chat/ChatViewProvider.ts#L252-L257

**Review by abeatrix — CHANGES_REQUESTED** [review]
Left some comments but overall lgtm, love that we can pick up an old convo!

Requesting change due to type errors.

File: client/cody/src/command/LocalStorageProvider.ts [hunk 3]
```diff
@@ -5,7 +5,8 @@ import { Memento } from 'vscode'
 import { UserLocalHistory } from '@sourcegraph/cody-shared/src/chat/transcript/messages'
 
 export class LocalStorage {
-    private KEY_LOCAL_HISTORY = 'cody-local-chatHistory'
+    // Bump this on storage changes so we don't handle incorrectly formatted data
+    private KEY_LOCAL_HISTORY = 'cody-local-chatHistory-v2'
```
Comment (abeatrix) [inline client/cody/src/command/LocalStorageProvider.ts:9]: Hmmm this case users won't have access to remove the items stored in `'cody-local-chatHistory'` anymore. Maybe instead of changing this, we can add a step to perform the migration?

File: client/cody/src/chat/ChatViewProvider.ts [hunk 4]
```diff
@@ -289,8 +315,8 @@ export class ChatViewProvider implements vscode.WebviewViewProvider, vscode.Disp
      * Save chat history
      */
     private async saveChatHistory(): Promise<void> {
-        if (this.transcript) {
-            this.chatHistory[this.currentChatID] = this.transcript.toChat()
+        if (this.transcript && !this.transcript.isEmpty) {
```
Comment (abeatrix) [inline client/cody/src/chat/ChatViewProvider.ts:318]:
```suggestion
        if (!this.transcript.isEmpty) {
```

File: client/cody/src/chat/ChatViewProvider.ts (hunk 2 above)
Comment (SuperAuguste) [reply client/cody/src/chat/ChatViewProvider.ts:88]: I saw this too but observed inconsistent behavior without saving chat history first :(

File: client/cody/src/chat/ChatViewProvider.ts [hunk 5]
```diff
@@ -84,14 +84,37 @@ export class ChatViewProvider implements vscode.WebviewViewProvider, vscode.Disp
...
+    public async restoreSession(chatID: string): Promise<void> {
+        this.saveChatHistory()
+        this.cancelCompletion()
+
+        this.currentChatID = chatID
+        this.transcript = Transcript.fromJSON(this.chatHistory[chatID])
+        delete this.chatHistory[chatID]
+
+        this.sendTranscript()
+        await this.localStorage.setChatHistory({
```
Comment (abeatrix) [inline client/cody/src/chat/ChatViewProvider.ts:111]:
```suggestion
        await this.saveChatHistory()
```
Seems like this code is doing the same thing as `this.saveChatHistory()`?

**Review by abeatrix — CHANGES_REQUESTED** [review]

File: client/cody/src/chat/ChatViewProvider.ts (hunk 5 above)
Comment (SuperAuguste) [reply client/cody/src/chat/ChatViewProvider.ts:111]: There's actually a subtle difference - `saveChatHistory` performs a `this.chatHistory[this.currentChatID] = await this.transcript.toJSON()` which I don't want as we don't want the current chat session to also be in the history. I can probably make that assignment its own function?

File: client/cody/package.json [hunk 6]
```diff
@@ -170,6 +170,13 @@
         "group": "Cody",
         "icon": "$(clear-all)",
         "when": "cody.activated"
+      },
+      {
+        "command": "cody.history",
+        "title": "Chat History",
```
[the remark this answers is not in the document]
Comment (SuperAuguste) [reply client/cody/package.json:176]: This command isn't under `menus.commandPalette` so it won't appear in the command palette (which was my intention). The label has no "Cody" prefix as this is the result I want:
Screenshot 2023-04-26 at 1 24 06 PM

[the remark this answers is not in the document]
Comment (abeatrix) [reply client/cody/package.json:176]: It shows up in CommandPalette by default unless you hide it: 
image

[the remark this answers is not in the document]
Comment (SuperAuguste) [reply client/cody/package.json:176]: Wow I totally missed that, thank you so much! I'll fix this and the other entries too :)

File: client/cody/package.json [hunk 7]
```diff
@@ -154,7 +154,7 @@
       },
       {
         "command": "cody.settings",
-        "title": "Settings",
+        "title": "Cody: Settings",
```
Comment (abeatrix) [inline client/cody/package.json:157]: Thanks for cleaning this up! ❤️

**Review by abeatrix — APPROVED** [review]
Make some minor changes and did some clean up. This looks great to me thank you so much for working on it!!
