### PR TITLE
extensibility: fix browser extension for private code on Cloud

### LINKED ISSUE #22444: Browser extensions + native integrations should support private code on dotcom (yay!)
The sourcegraph browser extension seems to block private code on dotcom with a `PrivateRepoPublicSourcegraphError` on the backend and a modal (attached) on the frontend. We should update this so: 

1. Private code isn't blocked automatically with the error
2. The modal instead instructs you how to connect private code to Sourcegraph (which you can do now!) instead of instructing you to set up a private sourcegraph instance

This should be updated and released before the Cloud Launch, so by July 14 (to account for review delays). We should update our native integrations as well as all browsers' extensions. 

(Note for some reason in my tests eventually the hovertooltip goes away and I do get some basic code intel hovers from Sourcegraph. I'm not sure why this is and see no console output, but we should test our updates thoroughly.) 

image

### PR DESCRIPTION
**Pull request by tjkandala**
Closes #22444.

"Private code" hover alert only appears when we _know_ that the repo isn't on Cloud, native tooltips aren't disabled.
Screenshot from 2021-07-08 12-36-44

Browser extension works with private code that has been added to Cloud.
Screenshot from 2021-07-08 12-36-15

Notes:
- Potential risk: we can longer block all GraphQL requests from extensions to Cloud on the basis that the currently viewed repository is private.
- Testing: we will start with manual testing, then add integration tests for this use case as part of our DX project around automating browser extension testing.

TODO:
- [x] Don't show popup private repo alert when the repo has been added to Cloud
- [x] Update popup private repo alert copy (no action for now, we've added a link to "how to add public repos to Cloud" on the hover alert that hints at private code coming to Cloud)

### CODE REVIEW

File: client/browser/src/shared/code-hosts/shared/util/fileInfo.ts [hunk 1]
```diff
@@ -31,7 +34,10 @@ const resolveRepoNameForFileInfo = (
             // without having pointed his browser extension to a self-hosted Sourcegraph instance that
             // has access to that code. In that case, it's impossible to resolve the repo names,
             // so we keep the repo names inferred from the code host's DOM.
-            if (isPrivateRepoPublicSourcegraphComErrorLike(error)) {
+            // if (isPrivateRepoPublicSourcegraphComErrorLike(error)) {
+
+            // TODO(tj)
+            if (isRepoNotFoundErrorLike(error)) {
                 return of(useRawRepoNameAsFallback(fileInfo))
```
Comment (tjkandala) [inline client/browser/src/shared/code-hosts/shared/util/fileInfo.ts:41]: Should only fallback when we know that the repo is private as well

**Comment by muratsu** [comment]
* As we've discussed on slack, let's change the link to https://docs.sourcegraph.com/code_search/how-to/adding_repositories_to_cloud
image

* This blurb keeps appearing/dissappearing for me when I'm manually testing.
image

**Comment by vovakulikov** [comment]
@tjkandala sorry, didn't have time to test this locally and dive deep in the logic. I will review this properly till Monday (US timezone).

**Comment by muratsu** [comment]
Thanks @vovakulikov will merge on monday & release browser extensions if no blocking issues.

File: client/browser/src/browser-extension/scripts/backgroundPage.main.ts [hunk 2]
```diff
@@ -234,19 +235,20 @@ async function main(): Promise<void> {
...
+        async notifyPrivateCloudError(
+            hasPrivateCloudError: boolean,
             sender: browser.runtime.MessageSender
         ): Promise<void> {
             const tabId = sender.tab?.id
             if (tabId !== undefined) {
-                tabPrivateRepositoryCache.setTabIsPrivateRepository(tabId, isPrivateRepository)
+                tabPrivateCloudErrorCache.setTabHasPrivateCloudError(tabId, hasPrivateCloudError)
             }
+            console.log({ hasPrivateCloudError, sender })
```
Comment (vovakulikov) [inline client/browser/src/browser-extension/scripts/backgroundPage.main.ts:246]: Is it debug log or is it something that we want to have in prod? In case of a second maybe we can and some description line about this logged info?

File: client/browser/src/shared/code-hosts/shared/codeHost.tsx [hunk 3]
```diff
@@ -1018,10 +1061,10 @@ export function handleCodeHost({
                 } else if (diffOrFileInfoWithEditor.base) {
                     scopeEditor = diffOrFileInfoWithEditor.base.editor
                 } else {
-                    scopeEditor = diffOrFileInfoWithEditor.head.editor
+                    scopeEditor = diffOrFileInfoWithEditor.head?.editor
```
Comment (vovakulikov) [inline client/browser/src/shared/code-hosts/shared/codeHost.tsx:1064]: 🤔 TS lang serve says that the editor always must be non-nullable here. I've seen this problem before but that was in TS migration PR (version update to TS 4.3.4). Just out of curiosity what is the reason for these changes in this PR?

**Review by vovakulikov — APPROVED** [review]
LGTM. Good job TJ. I left a small question and minor comment.

File: client/browser/src/shared/code-hosts/shared/codeHost.tsx (hunk 3 above)
Comment (tjkandala) [reply client/browser/src/shared/code-hosts/shared/codeHost.tsx]: I was using TS version 4.3.5 in VS Code 🤦‍♀️️
