### PR TITLE
JetBrains: Force hide the material UI overlay when the Sourcegraph window is hidden

### LINKED ISSUE #36479: JetBrains: Hiding the popup the way we do it now doesn’t work well with some themes
## Context

We keep our popup open in the background (we just hide it) when the user “closes” it.
We need this behavior because the JCEF browser has glitches with off-screen rendering on Mac, and we can’t reliably close and reopen it.

## Problem

Some themes define a gray overlay over the whole editor when a popover is opened.
Since we keep our popover alive, it does not go away when we press Escape.

The IDE looks faded, like this:

image

This can be reproduced with the [Material UI theme](https://plugins.jetbrains.com/plugin/8006-material-theme-ui)

## Solution ideas

- Figure out what aspect of the popup these themes watch, and try to imitate it being closed.
- Close the popup, and “save” the JCEF browser in some other, visible area of the IDE by making it 1x1px and putting it somewhere
- Think about more solutions? :)

### PR DESCRIPTION
**Pull request by philipp-spiess**
Closes #36479

Another attempt at fixing #36479. This time it does not bring back the web view issues on macOS.

We now manually emit an action defined by the material UI theme to hide the overlay it opens whenever a popover is
created. This third-party plugin does not work with our approach of keeping the popover alive and thus, when the
Sourcegraph popover is closed, their custom overlay stays active.

Background on how we came up with the solution can be found here: https://github.com/mallowigi/material-theme-issues/issues/179#issuecomment-1151169850

_Note: This is not an ideal fix yet as the overlay does not re-appear when the window is re-opened. Given that this is not the only issue with the overlay and the fact that I was able to find more by using this theme myself for a bit, I am not super worried about this._

## Test plan

https://user-images.githubusercontent.com/458591/172866469-3e0af482-1e5e-499c-b720-5394974a4c80.mov

## App preview:

- [Web](https://sg-web-ps-jetbrains-material-ui-overlay.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-kuxinijazj.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

File: client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java [hunk 1]
```diff
@@ -190,4 +193,29 @@ public void dispose() {
...
+
+    // We manually emit an action defined by the material UI theme to hide the overlay it opens whenever a popover is
+    // created. This third-party plugin does not work with our approach of keeping the popover alive and thus, when the
+    // Sourcegraph popover is closed, their custom overlay stays active.
+    //
+    //   - https://github.com/sourcegraph/sourcegraph/issues/36479
+    //   - https://github.com/mallowigi/material-theme-issues/issues/179
+    private void hideMaterialUiOverlay() {
+        AnAction materialAction = ActionManager.getInstance().getAction("MTToggleOverlaysAction");
+        if (materialAction != null) {
```
Comment (philipp-spiess) [inline client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java:206]: This will be `null` if the action is not defined so it will no-op for most of our users.

File: client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java [hunk 2]
```diff
@@ -190,4 +193,29 @@ public void dispose() {
...
+            try {
+                materialAction.actionPerformed(
+                    new AnActionEvent(
+                        null,
+                        DataManager.getInstance().getDataContextFromFocusAsync().blockingGet(10),
```
Comment (philipp-spiess) [inline client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java:211]: The sync API for that is deprecated so 🤷

**Review by vdavid — APPROVED** [review]
Looks good!

Question: Not sure how we were missing `popup.setUiVisible(true);` earlier. Is that implicitly called somehow? If so, how come that we need it now?

**Comment by philipp-spiess** [comment]
> Question: Not sure how we were missing popup.setUiVisible(true); earlier. Is that implicitly called somehow? If so, how come that we need it now?

We weren't missing it I was just moving it into the else clause instead of running it when the modal is new as well since I figured it would be easier to read that way 🙈  It no-ops if we create a new dialog as it that is visible by default.
