### PR TITLE
Disable unwanted Monaco keybindings

### LINKED ISSUE #8736: search bar: Ctrl-f on website cut off
uhhhh-ctrl-f

Suddenly Hit ctrl-f on a sourcegraph.com search page and I see the above. Can't search in the web page. Don't know if I need to do anything extra to reproduce.

Update: this is if the cursor _focus_ is in the search bar!

### LINKED ISSUE #8738: Newline possible in new search UI
- **Sourcegraph version:** master
- **Platform information:** sourcegraph.com

#### Steps to reproduce:

1. Enter something in the search input
2. Hit cmd + return
3. See the feld "get cleared out" making me thing my query is gone
4. Navigate with arrow up
5. See query and realize it's a newline

#### Expected behavior:
No newline is inserted

#### Actual behavior:
It is and it might confuse people because the query still contains the first part

### PR DESCRIPTION
**Pull request by lguychard**
Fixes #8736
Fixes #8738

### CODE REVIEW

File: web/src/search/input/MonacoQueryInput.tsx [hunk 1]
```diff
@@ -275,6 +278,12 @@ export class MonacoQueryInput extends React.PureComponent<MonacoQueryInputProps>
                 })
             )
         )
+
+        // Disable some default Monaco keybindings
+        for (const keybinding of NOOP_KEYBINDINGS) {
+            editor.addCommand(keybinding, noop)
+        }
+
         // Prevent inserting newlines.
```
Comment (felixfbecker) [inline web/src/search/input/MonacoQueryInput.tsx]: Is there a reason the keybindings need different approaches to be ignored?

Comment (lguychard) [reply web/src/search/input/MonacoQueryInput.tsx]: We're disabling some existing keybindings altogether, and replacing the keybinding for `Enter` to submit search when the suggestions widget isn't showing (but not to add a newline).

That being said, this `prevent inserting newlines` block predated the `Submit on enter when not showing suggestions` stuff, and doesn't appear to be necessary, so I just removed it in 5f1eb63.
