### PR TITLE
case sensitive drilldowns

### LINKED ISSUE #41018: Aggregations by capture group are case-sensitive even when queries are not
When the query is case-insensitive, the aggregation by capture group is not:

image

This leads to the unexpected case that when drilling down into a bar, it matches more results than the count of the bar, because it will also match other cases.

The expected behavior would be (I think) that the aggregation is also case-insensitive, i.e. collects all matches into a single bar `test`.

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

### PR DESCRIPTION
**Pull request by coury-clark**
Closes #41018
Closes https://github.com/sourcegraph/sourcegraph/issues/41442

I also added some tests around building the drilldown query that were missing from a previous PR. You'll notice these don't include scenarios for regexp without capture groups, and that is because there seems to be a bug that needs to be fixed (issue tbd).

You'll also notice that when drilldown queries are placed into the search box they have an extra space now. This is because the search box pulls out the `case` field to toggle the case button, but leaves behind an extra whitespace. https://github.com/sourcegraph/sourcegraph/issues/41452

## Test plan

`insights type:commit` -> 
`type:commit author:(^Vova Kulikov$)  insights` Case sensitivity is turned on (but not visible in the search box)

`insights type:commit` ->
`type:commit author:^coury-clark$  insights`

### CODE REVIEW

File: enterprise/internal/insights/resolvers/aggregates_resolvers.go [hunk 1]
```diff
@@ -530,5 +530,9 @@ func buildDrilldownQuery(mode types.SearchAggregationMode, originalQuery string,
 	}
 
 	newQuery, err := modifierFunc(querybuilder.BasicQuery(originalQuery), drilldown)
-	return string(newQuery), err
+	if err != nil {
+		return "", err
+	}
+	caseSensitive, err := querybuilder.SetCaseSensitivity(newQuery, true)
```
Comment (chwarwick) [inline enterprise/internal/insights/resolvers/aggregates_resolvers.go:536]: I feel like we would _only_ want to do this in the capture group replacement because that is the only time we are changing the search pattern any other time it's adding additional filters.

So for repo/file/author etc.. this would not act as a filter on the search results but change the original search and apply another filter.

Comment (coury-clark) [reply enterprise/internal/insights/resolvers/aggregates_resolvers.go:536]: Gah, I even mentioned the same thing [here](https://github.com/sourcegraph/sourcegraph/issues/41018#issuecomment-1238479546) and just completely forgot on implementation. Quick fix coming up.

Comment (coury-clark) [reply enterprise/internal/insights/resolvers/aggregates_resolvers.go]: Fixed, and added tests for the same.

**Review by chwarwick — APPROVED** [review]
