### PR TITLE
JetBrains: Cody: Fix random tool panel refreshing 

### LINKED ISSUE #56494: JetBrains: no way to disable auto-scroll for chat
Currently, the scroll behavior of the chat window feels annoying. My expectation is:

* Auto-scroll when the window is scrolled to the bottom or I send a new message
* Don't auto-scroll if I scroll up the window. Even if Cody is streaming new messages, I want to be able to disable auto-scroll

### LINKED ISSUE #57062: JetBrains: weird scroll behavior for onboarding guide
In a clean install on a fresh IDE, sign in, make window small, and try to scroll down the onboarding screen

Image

### PR DESCRIPTION
**Pull request by Gedochao**
Fixes #57062

https://github.com/sourcegraph/sourcegraph/assets/18601388/10bd7c3d-a053-4bfd-85f3-ba079d943111

The onboarding panel changes are mostly just refactoring, the actual fix is disabling random tool panel refreshes coming from `RefreshCodyAppDetection`.

## Context

So just to highlight some stuff: this bug is a lot nastier than it seems.
`RefreshCodyAppDetection` has been refreshing the tool panel on every action update. 
This means it was running on almost every direct interaction with the panel.
We may have been relying on the panel refreshing randomly in some cases, while we should've refreshed it with an explicit call.
In fact, I am fixing one such case in this PR, where a successful account login was relying on the random refresh for the login onboarding message to go away.
We may have other such spots I didn't manage to catch, so please do test for it.

Now, the biggest merit of this fix is that we may have eliminated some random behaviours along with it.
For example, I suspect #56494 might now be possible (or at least it's worth a try after these changes, as this would also possibly mess with chat scrolling)

## Test plan
- the onboarding scroll panel flicker should no longer be replicable
- the tool panel should refresh correctly when it should (i.e. after first logging in)
- the tool panel should generally work correctly (that's a lot of edge cases to test for manually, I am well aware)

### CODE REVIEW

**Comment by Gedochao** [comment]
Adjusted this after the changes from #57073.

File: client/jetbrains/src/main/kotlin/com/sourcegraph/cody/chat/CodyOnboardingGuidancePanel.kt [hunk 1]
```diff
@@ -13,13 +13,7 @@ import com.sourcegraph.cody.ui.HtmlViewer.createHtmlViewer
...
 import java.awt.Dimension
 import java.awt.event.ActionListener
-import javax.swing.BorderFactory
-import javax.swing.BoxLayout
-import javax.swing.Icon
-import javax.swing.JButton
-import javax.swing.JComponent
-import javax.swing.JEditorPane
-import javax.swing.JPanel
+import javax.swing.*
```
Comment (szymonprz) [inline client/jetbrains/src/main/kotlin/com/sourcegraph/cody/chat/CodyOnboardingGuidancePanel.kt:16]: could you adjust your ide settings to not merge the imports?

File: client/jetbrains/src/main/kotlin/com/sourcegraph/cody/chat/CodyOnboardingGuidancePanel.kt [hunk 2]
```diff
@@ -30,46 +24,11 @@ class CodyOnboardingGuidancePanel(val originalDisplayName: String?) : JPanel() {
...
-    contentPanel.add(autocompletionsPanel)
-
-    val exploreCommandsPanel =
-        createSectionWithTextAndImage(
-            "<html><body><h3>Explore the Commands</h3>" +
-                "<p>Use <b>commands</b> to execute useful tasks on your code, like generating unit tests, docstrings and more</p>" +
-                "</body></html>",
-            Icons.Onboarding.Commands)
-    contentPanel.add(exploreCommandsPanel)
+    contentPanel.add(createChatWithCodyPanel())
```
Comment (szymonprz) [inline client/jetbrains/src/main/kotlin/com/sourcegraph/cody/chat/CodyOnboardingGuidancePanel.kt:29]: <3

**Review by szymonprz — APPROVED** [review]
