### PR TITLE
Fix query state getting erased on location changes

### LINKED ISSUE #13805: Search bar doesn't populate with repo filter
Screen Recording 2020-09-14 at 07 07 41 PM

Reproduce:
1. Go here: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/actions/toolkit%24%40main+startGroup&patternType=literal
2. Click on `export function startGroup` result
3. See filter flash in search bar and then disappear.

Expected repo filter to remain in search bar.

@lguychard can you triage to web or search team?

### PR DESCRIPTION
**Pull request by lguychard**
Fixes #13805

#13679 moved the logic that updates the navbar query from [`<GlobalNavbar/>`'s `constructor`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@62f73fa98a321bb0a78134dd837c93293692a068/-/blob/web/src/nav/GlobalNavbar.tsx?subtree=true#L91-107) (admittedly not a great place to have it) to a `useEffect()` block, with `location` as a dependency.

As a result, every time the `location` was updated, for example when clicking on tokens in a code view, any query state that wasn't persisted to the URL (a partially edited query, or the scoped query added automatically when navigating to a repo/file) would be erased.

~~The immediate fix I saw was to narrow the dependency array of the `useEffect()` block, to avoid running it on every `location` change. But I'm wondering if there isn't still an issue left: the scoped query randomly can get randomly erased on page load (race condition), depending on which of the `useEffect()` blocks in `<GlobalNavbar/>` and [`<RepoContainer/>`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a0d822fd03932f93423866784bfa0d5ea820ff3f/-/blob/web/src/repo/RepoContainer.tsx?subtree=true#L266-306) executes first.~~

I've simplified the `useEffect()` block in `<GlobalNavbar/>` (which could end up calling `onNavbarQueryChange()` multiple times, had some comments implying that it wouldn't update the query in interactive mode but still did it further down...), fixing the issue as a result, by restricting the cases in which we update the query state.

### CODE REVIEW

File: web/src/nav/GlobalNavbar.tsx [hunk 1]
```diff
@@ -106,39 +106,29 @@ export const GlobalNavbar: React.FunctionComponent<Props> = ({
...
+            let filtersInQuery: FiltersToTypeAndValue = {}
+            const { filtersInQuery: newFiltersInQuery, navbarQuery } = convertPlainTextToInteractiveQuery(query)
+            filtersInQuery = { ...filtersInQuery, ...newFiltersInQuery }
+            onNavbarQueryChange({ query: navbarQuery, cursorPosition: navbarQuery.length })
+            onFiltersInQueryChange(filtersInQuery)
+        } else {
+            onNavbarQueryChange({ query, cursorPosition: query.length })
         }
-    }, [interactiveSearchMode, isSearchRelatedPage, location, onFiltersInQueryChange, onNavbarQueryChange, query])
+    }, [interactiveSearchMode, isSearchRelatedPage, onFiltersInQueryChange, onNavbarQueryChange, query, location])
```
Comment (lguychard) [inline web/src/nav/GlobalNavbar.tsx:131]:
```suggestion
    }, [interactiveSearchMode, isSearchRelatedPage, location, onFiltersInQueryChange, onNavbarQueryChange, query])
```

**Comment by lguychard** [comment]
Update: I've simplified the `useEffect()` block in `<GlobalNavbar/>` (which could end up calling `onNavbarQueryChange()` multiple times, had some comments implying that it wouldn't update the query in interactive mode but still did it further down...), fixing the issue as a result, by restricting the cases in which we update the query state.

**Comment by tjkandala** [comment]
I was about to say that this reminds me of the problem that hamstrung the new breadcrumbs. I should add a warning in our [refactoring guide](https://about.sourcegraph.com/handbook/engineering/languages/typescript#converting-react-class-components-to-function-components) that we cannot expect logic from constructors to work in `useEffect`.

However, is the conclusion that the logic itself was the problem? No race conditions from `useEffect` + dynamic imports?

**Comment by lguychard** [comment]
The problem was indeed that part of the logic that was ported from the constructor made no sense in a `useEffect()` block (the "if we have no component state..." bit, which did a weird carryover of `location.state`, and that is the part that would be problematic in a race condition scenario). AFAICT the new logic updates the query correctly in all cases that we care about.

**Review by attfarhan — APPROVED** [review]

**Comment by sqs** [comment]
Thanks for fixing and for cleaning up the cod!
