### PR TITLE
[fix] only send unlock account email once per locked session

### LINKED ISSUE #45223: User lockout email is sent many times, resulting in email storm to the user
If the user account is locked, we send the email on every login attempt from what I can see (not great): https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/cmd/frontend/internal/auth/userpasswd/handlers.go?L303

More details in slack thread: https://sourcegraph.slack.com/archives/C01N83PS4TU/p1669899214086099?thread_ts=1669895194.211889&cid=C01N83PS4TU

Image

/cc @sourcegraph/iam

### PR DESCRIPTION
**Pull request by kopancek**
Fixes #45223
- #45223

## Test plan

Added/modified unit tests that check new behavior

### CODE REVIEW

**Review by ferozsalam — APPROVED** [review]

File: cmd/frontend/internal/auth/userpasswd/lockout.go [hunk 1]
```diff
@@ -111,33 +124,61 @@ func (s *lockoutStore) GenerateUnlockAccountURL(userID int32) (string, string, e
...
 	if err != nil {
 		return err
 	}
 
-	return txemail.Send(ctx, "account_unlock", txemail.Message{
+	emailF := txemail.Send
+	if MockSendEmail != nil {
+		emailF = MockSendEmail
+	}
+	err = emailF(ctx, "account_unlock", txemail.Message{
```
Comment (mrnugget) [inline cmd/frontend/internal/auth/userpasswd/lockout.go:161]: Instead of a global mock, why not have `sendEmail func(context.Context, string, txemail.Message)` on `*lockoutStore`?

We're trying since years now to get away from global mocks and just setting this on the lockoutStore would give you same testability but no global lock.

File: cmd/frontend/internal/auth/userpasswd/lockout.go [hunk 2]
```diff
@@ -111,33 +124,61 @@ func (s *lockoutStore) GenerateUnlockAccountURL(userID int32) (string, string, e
...
-			ExpiryMinutes:    conf.SiteConfig().AuthUnlockAccountLinkExpiry,
+			ExpiryTime:       formatExpiryTime(ttl),
 		},
 	})
+	if err == nil {
+		s.unlockEmailSent.SetWithTTL(key, []byte("sent"), ttl)
+	}
+
+	return err
+}
```
Comment (mrnugget) [inline cmd/frontend/internal/auth/userpasswd/lockout.go:177]: This is Go, baby, where `if err != nil` rules!

```suggestion
	if err != nil {
		return err
	}
	s.unlockEmailSent.SetWithTTL(key, []byte("sent"), ttl)
}
```

File: internal/rcache/rcache.go [hunk 3]
```diff
@@ -171,6 +175,25 @@ func (r *Cache) Increase(key string) {
...
+	ttl, err := redis.Int(c.Do("TTL", r.rkeyPrefix()+key))
+	if err != nil {
+		log15.Warn("failed to execute redis command", "cmd", "TTL", "error", err)
+		return -1, false
+	}
+	if ttl == -2 {
+		return -1, false
+	}
+	if r.ttlSeconds <= 0 || ttl == -1 {
+		return -1, true
```
Comment (mrnugget) [inline internal/rcache/rcache.go:191]: Is that really `true` here?

Also: what if you use `SetWithTTL` before with `r.ttlSeconds == 0`. In that case this would return `-1, true`, even though there is a TTL set on the key, right?

File: internal/rcache/rcache_test.go [hunk 4]
```diff
@@ -208,6 +208,52 @@ func TestCache_Increase(t *testing.T) {
...
+	assert.Eventually(t, func() bool {
+		_, ok = c.KeyTTL("a")
+		return !ok
+	}, 5*time.Second, 50*time.Millisecond, "rcache.ketttl did not respect expiration")
+}
+
+func TestCache_SetWithTTL(t *testing.T) {
+	SetupForTest(t)
+
+	c := NewWithTTL("some_prefix", 60)
```
Comment (mrnugget) [inline internal/rcache/rcache_test.go:233]: See comment above: I think this test would break if you use `NewWithTTL("some_prefix", 0)` here.

File: internal/version/upgradestore/store.go [hunk 5]
```diff
@@ -58,13 +59,15 @@ SELECT version FROM versions WHERE service = %s
 // ValidateUpgrade enforces our documented upgrade policy and will return an error (performing no side-effects)
 // if the upgrade is between two unsupported versions. See https://docs.sourcegraph.com/#upgrading-sourcegraph.
 func (s *store) ValidateUpgrade(ctx context.Context, service, version string) error {
+	fmt.Printf("================ ValidateUpgrade %s %s ================", service, version)
```
Comment (mrnugget) [inline internal/version/upgradestore/store.go:62]: Remove

File: internal/version/upgradestore/store.go [hunk 6]
```diff
@@ -58,13 +59,15 @@ SELECT version FROM versions WHERE service = %s
...
 	return s.updateServiceVersion(ctx, service, version, false)
 }
 
 // UpdateServiceVersion updates the latest version for the given Sourcegraph service. This method also enforces
 // our documented upgrade policy and will return an error (performing no side-effects) if the upgrade is between
 // two unsupported versions. See https://docs.sourcegraph.com/#upgrading-sourcegraph.
 func (s *store) UpdateServiceVersion(ctx context.Context, service, version string) error {
+	fmt.Printf("================ Updating service version %s %s ================", service, version)
```
Comment (mrnugget) [inline internal/version/upgradestore/store.go:70]: remove

File: internal/rcache/rcache.go (hunk 3 above)
Comment (kopancek) [reply internal/rcache/rcache.go:191]: Yes, it should be `true`. `ttl` -1 means that there is no `ttl` set on the key. But the boolean represents if the key exists in the cache at the time of calling the method.

It's not a bug. If `SetWithTTL` is called with `0` as TTL, since the TTL is already expired, it would be immediately deleted. By the time`KeyTTL` method is called, it should fail to find the key in the cache. See the [documentation for the `EXPIRE` command](https://redis.io/commands/expire/). I can add this as a test case though, so that it is clear how it should behave.

File: cmd/frontend/internal/auth/userpasswd/lockout.go (hunk 2 above)
Comment (kopancek) [reply cmd/frontend/internal/auth/userpasswd/lockout.go:177]: I mean, both things do the same, but I understand the convention wins here :)

File: internal/rcache/rcache.go (hunk 3 above)
Comment (kopancek) [reply internal/rcache/rcache.go:191]: Hmm, I stand corrected. The `TTL` command returns a key even if it is expired, which I did not count with 😢 Fixing...

File: internal/rcache/rcache.go [hunk 7]
```diff
@@ -171,6 +182,22 @@ func (r *Cache) Increase(key string) {
...
+	ttl, err := redis.Int(c.Do("TTL", r.rkeyPrefix()+key))
+	if err != nil {
+		log15.Warn("failed to execute redis command", "cmd", "TTL", "error", err)
+		return -1, false
+	}
+	if ttl < 0 {
+		return -1, false
+	}
+
+	return ttl, true
```
Comment (mrnugget) [inline internal/rcache/rcache.go:198]:
```suggestion
	return ttl, ttl >= 0
```

File: cmd/frontend/internal/auth/userpasswd/lockout.go [hunk 8]
```diff
@@ -18,6 +18,8 @@ import (
 	"github.com/sourcegraph/sourcegraph/lib/errors"
 )
 
+var MockSendEmail func(context.Context, string, txemail.Message) (err error)
+
```
Comment (mrnugget) [inline cmd/frontend/internal/auth/userpasswd/lockout.go:22]:
```suggestion
```

**Review by mrnugget — APPROVED** [review]
