### PR TITLE
campaigns: Attempt to republish failed changesets

### LINKED ISSUE #10795: Trying to publish a failed changeset again is noop
- **Sourcegraph version:** master
- **Platform information:** macOS 10.15.4, Chrome 81

#### Steps to reproduce:

1. Have a draft campaign (publishing needs to fail to repro, try no privilege token or so)
2. Click publish on one single changeset
3. It should fail, check the error messages in the campaign status
4. Click publish on the changeset again
5. See the spinner indicate something would happen

#### Expected behavior:
6. It is tried again

#### Actual behavior:
7. It only spins, no actual retry attempt is made. This piece of code just returns when a job exists (even if failed) https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/campaigns/service.go#L428-431

### PR DESCRIPTION
**Pull request by LawnGnome**
A couple of random thoughts that occurred while I was working on this that I'd appreciate feedback on:

1. `CreateChangesetJobForPatch` arguably doesn't capture what the function now does, but I'm not sure what verb is more appropriate. `QueueChangesetJobForPatch`, maybe? _I've updated it to `Queue...`, but would still welcome feedback on this._
2. More broadly, I'm not sure that having [a unique constraint on `changeset_jobs` over `campaign_id, patch_id`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@24ce1ba7e95836a05aa85ff49f1dd4d52fb55282/-/blob/cmd/frontend/db/schema.md#L100:55) makes total sense — is there any value to retaining failed jobs and their associated errors, or is this transient enough that we're OK with the "reset the fields and try again" approach in this PR?

Fixes #10795.

### CODE REVIEW

**Comment by eseliger** [comment]
> CreateChangesetJobForPatch arguably doesn't capture what the function now does, but I'm not sure what verb is more appropriate. QueueChangesetJobForPatch, maybe?

Agree that name is more precise.

> More broadly, I'm not sure that having a unique constraint on changeset_jobs over campaign_id, patch_id makes total sense — is there any value to retaining failed jobs and their associated errors, or is this transient enough that we're OK with the "reset the fields and try again" approach in this PR?

The idea is that we always only have 0..1 changeset_jobs for a patch in a campaign. We do the reset also in retry, and your approach basically makes the `publish` a "try or retry" - which I think is correct behavior.
In the future, once we have errors associated to patches, I would imagine the UI even can show not only "Publish" but "Retry" in exactly this case. At this point though, we don't expose enough information to make that distinction in the frontend, but that should make it even more evident that your approach makes sense :)

File: enterprise/internal/campaigns/service.go [hunk 1]
```diff
@@ -550,12 +550,12 @@ func (s *Service) RetryPublishCampaign(ctx context.Context, id int64) (campaign
...
 }
 
-// CreateChangesetJobForPatch creates a ChangesetJob for the
-// Patch with the given ID. The Patch has to belong to a
-// PatchSet that was attached to a Campaign.
-func (s *Service) CreateChangesetJobForPatch(ctx context.Context, patchID int64) (err error) {
+// QueueChangesetJobForPatch queues a ChangesetJob for the Patch with the given
+// ID, creating it if necessary. The Patch has to belong to a PatchSet that was
+// attached to a Campaign.
+func (s *Service) QueueChangesetJobForPatch(ctx context.Context, patchID int64) (err error) {
```
Comment (mrnugget) [inline enterprise/internal/campaigns/service.go:556]: 👍 on the name change. I debated with myself whether to change it or not while moving it to the Service, but couldn't come up with something better. Glad to see you did change it 🙂

Another option might be `EnqueueChangesetJobForPatch`. But... that's probably the biggest nitpick I can come up with here.

Comment (LawnGnome) [reply enterprise/internal/campaigns/service.go:556]: Yeah, I think I like `Enqueue` just a tiny bit more too. I'll update accordingly.
