### PR TITLE
show "Reload required" error if app JS is redeployed after user's initial page load

### LINKED ISSUE #1760: sourcegraph.com experiencing unexpected error every now and then
I've been seeing this error every now and then when using Sourcegraph.com . It will randomly appear when I'm switching from one page to another. It resolves by reloading the page.

image

The console shows this error:
```Failed to load resource: the server responded with a status of 404 ()``` originating from a `https://sourcegraph.com/.assets/scripts/27-43007cc1aa014fb8b79e.chunk.js`

I'll keep the network tab open from now on so I can get that error too, next time this happens.

### PR DESCRIPTION
**Pull request by sqs**
- fix #1760
- also other commits to fix other related issues

In https://github.com/sourcegraph/sourcegraph/issues/1760#issuecomment-453235933 @nicksnyder recommended just removing chunking altogether. I found an easy way to retain chunking (which improves page load times significantly) without the problems I worried about at https://github.com/sourcegraph/sourcegraph/issues/1760#issuecomment-453224286. Plus, this is a more comprehensive solution. Reverting to our previous situation (with 1 main chunk and then chunks for GraphiQL (API console) and Monaco) would still cause this problem to exhibit itself after a redeploy if the user tried to navigate to the API console or the Monaco editor. Now they will be prompted to reload in all cases when it is necessary.

screenshot from 2019-01-11 11-45-53

### CODE REVIEW

File: web/src/components/ErrorBoundary.tsx [hunk 1]
```diff
@@ -44,4 +81,8 @@ export class ErrorBoundary extends React.PureComponent<{}, State> {
 
         return this.props.children
     }
+
+    private onReloadClick: React.MouseEventHandler<HTMLElement> = e => {
+        window.location.reload() // hard page reload
```
Comment (felixfbecker) [inline web/src/components/ErrorBoundary.tsx]: Shouldn't this pass `true` to make sure the cache is not used?

File: web/src/components/ErrorBoundary.tsx [hunk 2]
```diff
@@ -14,15 +24,42 @@ interface State {
...
+        if (prevProps.location !== this.props.location) {
+            // Reset error state when location changes, so that the user can try navigating to a different page to
+            // clear the error.
+            this.setState({ error: undefined })
+        }
+    }
+
     public render(): React.ReactNode | null {
         if (this.state.error !== undefined) {
+            if (this.state.error.message.startsWith('Loading chunk')) {
```
Comment (felixfbecker) [inline web/src/components/ErrorBoundary.tsx]: Error message assertion is hacky. Are you sure this error has no programmatically inspectable code/type? A code search indicates it does: https://sourcegraph.com/github.com/webpack/webpack/-/blob/examples/chunkhash/README.md#L195:40
If not, I'd add a comment to explain it doesn't so this doesn't become accepted practice.

File: web/src/components/ErrorBoundary.tsx [hunk 3]
```diff
@@ -14,15 +24,42 @@ interface State {
...
  */
-export class ErrorBoundary extends React.PureComponent<{}, State> {
+export class ErrorBoundary extends React.PureComponent<Props, State> {
     public state: State = {}
 
     public static getDerivedStateFromError(error: any): Pick<State, 'error'> {
         return { error: asError(error) }
     }
 
+    public componentDidUpdate(prevProps: Props): void {
```
Comment (felixfbecker) [inline web/src/components/ErrorBoundary.tsx]: Should this be `getDerivedStateFromProps()`?

Comment (sqs) [reply web/src/components/ErrorBoundary.tsx]: No, why?

File: web/src/components/ErrorBoundary.tsx (hunk 2 above)
Comment (sqs) [reply web/src/components/ErrorBoundary.tsx]: At runtime, the `type` property is `"error"`, but there is a `request` property. I modified it to make it check that as well as the message.

File: web/src/components/ErrorBoundary.tsx (hunk 3 above)
Comment (felixfbecker) [reply web/src/components/ErrorBoundary.tsx]: I thought in general if `componentDidUpdate()` contains a `setState()` it should be `getDerivedStateFromProps()`, which saves one render cycle as `componentDidUpdate()` is called _after_ a rerender, and then triggers a new render because of the `setState()`. Any reason why it shouldn't be it?

Comment (sqs) [reply web/src/components/ErrorBoundary.tsx]: Oh, I didn’t know that. This is not performance sensitive, so I will make that change later.

**Comment by felixfbecker** [comment]
Should we add a reason _why_ the reload is required? For example, Facebook messenger says "A new version of messenger is available"

**Comment by felixfbecker** [comment]
https://github.com/webpack/webpack/pull/8615

**Comment by sqs** [comment]
> Should we add a reason why the reload is required? For example, Facebook messenger says "A new version of messenger is available"

Yeah, I like that. I'll update it. Thanks!

File: web/src/components/ErrorBoundary.tsx (hunk 3 above)
Comment (sqs) [reply web/src/components/ErrorBoundary.tsx]: I don't think I can use getDerivedStateFromProps here because it must reset `state.error` ONLY when the location changes. And getDerivedStateFromProps is static and therefore can't compare the new vs old props.

**Comment by sqs** [comment]
screenshot from 2019-01-11 11-45-53
