### PR TITLE
fix go-to-gitlab link to branch, commit range and line

### LINKED ISSUE #484: Go-To-Gitlab button doesn't link correctly to line number or commit range, similar to #294
#### Steps to reproduce:

1. Open https://sourcegraph.com/gitlab.com/gitlab-org/gitlab-runner@add-failure-reason-for-execution-timeout/-/blob/.codeclimate.yml#L10 . 
2. Click on the 'Open on GitLab' icon

#### Expected behavior: 
Opens https://gitlab.com/gitlab-org/gitlab-runner/blob/add-failure-reason-for-execution-timeout/.codeclimate.yml#L10

#### Actual behavior: 
Opens https://gitlab.com/gitlab-org/gitlab-runner/blob/add-failure-reason-for-execution-timeout/.codeclimate.yml, so doesn't link to the line.

With the commit range: 
#### Steps to reproduce:

1. Open https://sourcegraph.com/gitlab.com/gitlab-org/gitlab-runner/-/compare/...refactor-app-initialization
2. Click on the 'Open on GitLab' icon

#### Expected behavior: 
Opens https://gitlab.com/gitlab-org/gitlab-runner/compare/master...refactor-app-initialization

#### Actual behavior: 
Opens https://gitlab.com/gitlab-org/gitlab-runner

### PR DESCRIPTION
**Pull request by vanesa**
Similar to https://github.com/sourcegraph/sourcegraph/issues/294, Go-To-Gitlab buttons were not linking correctly to branches, commit ranges and lines. 

Checking for `externalURL.serviceType === 'gitlab'` and applying the same solution as with GitHub fixes #484 .

> This PR updates the CHANGELOG.md file to describe any user-facing changes.

### CODE REVIEW

File: src/repo/actions/GoToCodeHostAction.tsx [hunk 1]
```diff
@@ -108,18 +108,18 @@ export class GoToCodeHostAction extends React.PureComponent<Props, State> {
         const { displayName, icon } = serviceTypeDisplayNameAndIcon(externalURL.serviceType)
         const Icon = icon || ExportIcon
 
-        // Special-case for GitHub: add branch and line numbers to URL.
+        // Extract url to add branch, line numbers or commit range.
         let url = externalURL.url
-        if (externalURL.serviceType === 'github') {
-            // If in a branch, add branch path to the GitHub URL.
+        if (externalURL.serviceType === 'github' || 'gitlab') {
```
Comment (felixfbecker) [inline src/repo/actions/GoToCodeHostAction.tsx]: This condition is not doing what you intended. It is evaluated as:
```ts
if ((externalURL.serviceType === 'github') || ('gitlab'))
```
which is the same as
```ts
if ((externalURL.serviceType === 'github') || true)
```
which is the same as
```ts
if (true)
```

Comment (vanesa) [reply src/repo/actions/GoToCodeHostAction.tsx]: Oh good catch! Thanks!
