### PR TITLE
[a11y] web: hierarchical symbols sidebar is now rendered as nested lists

### LINKED ISSUE #44125: New hierarchical symbols sidebar show hierarchy visually but not through markup to screenreaders
The new hierarchical symbols achieve a tree by using increasing padding, but are still marked up as a list (`<ul>`/`<li>`). A screen reader user has no way to know the hierarchy.

This is a regression to before because previously, the container name of each symbol was available after the symbol name. Now however, it is only available in the list as a list item, with the fact of it being a container for the following items only communicated visually.

/cc @felixfbecker

### PR DESCRIPTION
**Pull request by limitedmage**
Closes #44125

The new hierarchical symbols sidebar is now rendered using nested lists. Eventually, we want to convert this to an aria tree, but this is an OK stopgap for now since we don't have a tree component readily available. I have change the data processing in a way where I think it will be easy to convert easily to a tree component.

Additionally, symbols are now ordered by locale rules instead of codepoint order, so they are now case-insensitive.

(Inverting the logic of `hierarchyOf` felt like a coding interview question 💀)

image

## Test plan

Verify with Go and TypeScript files that all previously-rendered symbols are still rendered. Also verify that using the search functionality on the sidebar still renders all symbols with the right hierarchy.

Note that this work exposes an issue rendering certain symbols with the same name: https://sourcegraph.slack.com/archives/CHXHX7XAS/p1668209277601099

## App preview:

- [Web](https://sg-web-jp-a11yhierarchicalsymbols.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | -0.00% (-0.33 kb) | -0.00% (-0.33 kb) | -0.14% (-1) 🔽 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/jp/a11yhierarchicalsymbols/compare-report.html;tab=live_object) for a full comparison between the commits 476129d and d1c014a or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

File: client/web/src/repo/RepoRevisionSidebarSymbols.tsx [hunk 1]
```diff
@@ -232,74 +231,76 @@ export const RepoRevisionSidebarSymbols: React.FunctionComponent<
...
 )
 
-interface IntermediateSymbol {
-    __typename: 'IntermediateSymbol'
-    name: string
-    language: string
-}
-
-type Sym = (SymbolNodeFields | IntermediateSymbol) & { containers: string[] }
+type Sym = SymbolNodeFields & { children: Sym[] }
```
Comment (felixfbecker) [inline client/web/src/repo/RepoRevisionSidebarSymbols.tsx:251]: (not blocking) Maybe a better name for this would be `UISymbolNode` or `SymbolWithChildren` or something like that? I find it very confusing that there are the terms "sym" and "symbol" both used in the function below but they mean different types where "sym" contains the children but "symbol" doesn't

**Review by felixfbecker — APPROVED** [review]
Awesome!!

File: client/web/src/repo/RepoRevisionSidebarSymbols.tsx (hunk 1 above)
Comment (limitedmage) [reply client/web/src/repo/RepoRevisionSidebarSymbols.tsx:251]: 100% agree, will do
