### PR TITLE
web: keep diff line decorations on same line if possible

### LINKED ISSUE #24469: Line decorators show up on a new line on diff view
#### Steps to reproduce:

1. Enable codecov / gitblame
2. Navigate to [link](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/57e8474ee570ac53f78dc6550b0083693369f89c?visible=1)

#### Expected behavior:
Line decorators to show up on the same lies as code

#### Actual behavior:
They show up on a new line:
image

### PR DESCRIPTION
**Pull request by tjkandala**
fix #24469.

#### Line wrapping

Screenshot from 2021-09-08 17-07-26

#### Unified

Screenshot from 2021-09-08 17-07-11

#### Split

Screenshot from 2021-09-08 17-06-56

### CODE REVIEW

File: client/web/src/components/diff/DiffHunk.tsx [hunk 1]
```diff
@@ -118,7 +118,7 @@ export const DiffHunk: React.FunctionComponent<DiffHunkProps> = ({
                             style={lineStyle}
                             data-diff-marker={diffHunkTypeIndicators[line.kind]}
                         >
-                            <div className="d-inline" dangerouslySetInnerHTML={{ __html: line.html }} />
+                            <div className="d-inline-block" dangerouslySetInnerHTML={{ __html: line.html }} />
```
Comment (tjkandala) [inline client/web/src/components/diff/DiffHunk.tsx:121]: @5h1rU Do you know why this was `d-inline` to begin with? Also, @erzhtor and I are confused as to why changing it to `display: inline-block;` would fix this; our expectation is that `inline` should behave as desired. Any CSS gurus know what's happening?

**Comment by 5h1rU** [comment]
Did you activate the git blame option to make sure everything still working?

**Comment by tjkandala** [comment]
@5h1rU good idea! looks like it works:

Screenshot from 2021-09-08 19-25-01

**Review by erzhtor — APPROVED** [review]

File: client/web/src/components/diff/DiffHunk.tsx (hunk 1 above)
Comment (5h1rU) [reply client/web/src/components/diff/DiffHunk.tsx:121]: @tjkandala I think a [regression was made](https://sourcegraph.slack.com/archives/C0W2E592M/p1631796312166600) by this change

Comment (tjkandala) [reply client/web/src/components/diff/DiffHunk.tsx:121]: @5h1rU I interpreted that feedback as the user wanting long lines on diff search results to wrap like this diff view does, not that long lines on diff views do not wrap anymore. Let me know if I'm wrong, I wasn't able to reproduce any diff view wrapping error

Comment (5h1rU) [reply client/web/src/components/diff/DiffHunk.tsx:121]: You are right; I misread those lines, sorry.

Still, we have an issue there. The `:before` pseudo-selector is being affected by the `white-space` parent property. The line below (now with inline-block) generates a breaking line, meaning that in long hunks, we have the - or + above the code.

If we transfer the CSS rule from the `td` to the first `div`, getting rid of the `inline-block this would fit in all our scenarios.



**Current status**
Screen Shot 2021-09-16 at 11 47 25 AM

**Expected status**
Screen Shot 2021-09-16 at 11 46 47 AM

[Example](https://sourcegraph.com/github.com/sourcegraph/about/-/commit/f2ff8760cf7e70ea7b5d208dff6843fab7344855?visible=1)
