### PR TITLE
in symbol searches, show the number of symbol matches rather than file matches

### LINKED ISSUE #4578: type:symbol search counts incorrect
- **Sourcegraph version:** 3.5.0-rc.1 and sourcegraph.com

#### Steps to reproduce:

1. Visit https://sourcegraph.com/search?q=repo:%5Egithub.com/sourcegraph/sourcegraph%24+ListRepos+type:symbol
2. See that it says "15 results"

image

There are many more than 15 matching symbol results... There appear to be 15 _files_ that have symbols that match the result in them. 

#### Expected behavior:

It shows the number of symbol results.

#### Actual behavior:

It shows the number of file results (15)

### PR DESCRIPTION
**Pull request by ijt**
Fixes #4578 

Test plan: unit test

After:
Screen Shot 2019-07-11 at 15 20 28

Before:
Screen Shot 2019-07-11 at 15 12 59

### CODE REVIEW

File: cmd/frontend/graphqlbackend/search_results.go [hunk 1]
```diff
@@ -158,14 +158,32 @@ func (sr *searchResultsResolver) MatchCount() int32 {
 	return totalResults
 }
 
-func (sr *searchResultsResolver) ResultCount() int32 { return sr.MatchCount() }
+func (sr *searchResultsResolver) ResultCount() int32 {
+	nsym := sr.countSymbols()
+	if nsym > 0 {
+		return nsym
+	}
+	return sr.MatchCount()
```
Comment (slimsag) [inline cmd/frontend/graphqlbackend/search_results.go]: Adding special logic here is not right because `ResultCount` is deprecated, look at the GraphQL schema to see this:

https://github.com/sourcegraph/sourcegraph/blob/bda1907d5d979b5d0f829b7f608cc44fd91c33cd/cmd/frontend/graphqlbackend/schema.graphql#L928-L929

Additionally, having result-type-dependent code here is not a good idea because the code would quickly balloon in size (we would need to have code here for handling file matches, commit matches, etc.)

Instead you should implement this as part of `MatchCount`. After you look at that method, you will notice it essentially just sums up `result.resultCount()`, meaning this logic should be placed here instead:

https://github.com/sourcegraph/sourcegraph/blob/bda1907d5d979b5d0f829b7f608cc44fd91c33cd/cmd/frontend/graphqlbackend/textsearch.go#L129-L134

Comment (ijt) [reply cmd/frontend/graphqlbackend/search_results.go]: Done.

**Comment by ijt** [comment]
Updated. PTAL.

File: cmd/frontend/graphqlbackend/search_results.go [hunk 2]
```diff
@@ -158,14 +158,16 @@ func (sr *searchResultsResolver) MatchCount() int32 {
...
 
 func (sr *searchResultsResolver) ApproximateResultCount() string {
-	count := sr.ResultCount()
+	s := strconv.Itoa(int(sr.ResultCount()))
 	if sr.LimitHit() || len(sr.cloning) > 0 || len(sr.timedout) > 0 {
-		return fmt.Sprintf("%d+", count)
+		s += "+"
 	}
-	return strconv.Itoa(int(count))
+	return s
```
Comment (keegancsmith) [inline cmd/frontend/graphqlbackend/search_results.go]: why did you change this function? Functionally it is the same, but personally I prefer the older version from a readability point of view.

File: cmd/frontend/graphqlbackend/textsearch.go [hunk 3]
```diff
@@ -127,6 +127,9 @@ func (fm *fileMatchResolver) searchResultURIs() (string, string) {
 }
 
 func (fm *fileMatchResolver) resultCount() int32 {
+	if s := len(fm.symbols); s > 0 {
+		return int32(s)
+	}
 	if l := len(fm.LineMatches()); l > 0 {
 		return int32(l)
 	}
```
Comment (keegancsmith) [inline cmd/frontend/graphqlbackend/textsearch.go]: is it possible to have both linematches and symbols? If so, we should add the two.

Comment (ijt) [reply cmd/frontend/graphqlbackend/textsearch.go]: I don't know but I suppose it doesn't hurt to just return their sum if that's greater than zero. Changed it.

File: cmd/frontend/graphqlbackend/search_results.go (hunk 2 above)
Comment (ijt) [reply cmd/frontend/graphqlbackend/search_results.go]: I originally made the change on this function before @slimsag's feedback.

The old version seems less readable to me but I'll revert anyway since changing this function isn't logically part of this PR anymore.

Comment (slimsag) [reply cmd/frontend/graphqlbackend/search_results.go]: I similarly prefer the sprintf version from a readability POV 👍

File: cmd/frontend/graphqlbackend/search_results.go [hunk 4]
```diff
@@ -158,7 +158,9 @@ func (sr *searchResultsResolver) MatchCount() int32 {
 	return totalResults
 }
 
-func (sr *searchResultsResolver) ResultCount() int32 { return sr.MatchCount() }
+func (sr *searchResultsResolver) ResultCount() int32 {
+	return sr.MatchCount()
+}
```
Comment (slimsag) [inline cmd/frontend/graphqlbackend/search_results.go]: These lines shouldn't change, right?

Comment (ijt) [reply cmd/frontend/graphqlbackend/search_results.go]: Done.
