### PR TITLE
Fix flaky scheduler.ticker test by checking channel is closed

### LINKED ISSUE #20350: Intermittent test failure in `TestTickerRateLimited`
The following test failure was seen [here](https://buildkite.com/sourcegraph/sourcegraph/builds/94042#6a2db5d8-a37e-442f-83ed-e003f41e2616/213) which was fixed on a retry. 

```
FAIL: TestTickerRateLimited (0.02s)
    ticker_test.go:82: unexpected non-nil channel: 0xc000356300
```

### PR DESCRIPTION
**Pull request by mrnugget**
This should fix #20350.

Since closing a channel (which is what's happening under the hood of
`ticket.stop()`) is *not* a blocking operation, it's possible that the
goroutine of the test closes the channel and then immediately reads from
`ticker.C`. The ticker goroutine then sees the read from `t.C` before
the closing of `done` first.

The fix here leaks a bit of internals by checking `ticker.done`
explicitly. Another way to make this non-flaky would be to always  make
two reads of `ticker.C` and only check the second value.

### CODE REVIEW

File: enterprise/internal/batches/scheduler/ticker.go [hunk 1]
```diff
@@ -64,8 +64,6 @@ func newTicker(schedule *window.Schedule) *ticker {
 			} else if err != nil {
 				log15.Warn("error taking from schedule", "schedule", t.schedule, "err", err)
 				close(t.C)
-				// Ensure we drain done so that there isn't a panic if and when
-				// stop() is called.
 				return
```
Comment (eseliger) [inline enterprise/internal/batches/scheduler/ticker.go:67]: you really hated that comment, right?

**Review by eseliger — APPROVED** [review]

File: enterprise/internal/batches/scheduler/ticker.go (hunk 1 above)
Comment (mrnugget) [reply enterprise/internal/batches/scheduler/ticker.go:67]: IT WAS OUTDATED!

**Comment by mrnugget** [comment]
@LawnGnome I'm going ahead and merge this, but feel free to revert/remove/overwrite-with-your-name/whatever. Only reason I'm merging is to fix the CI issue ASAP (and maybe, if this doesn't fix it, get more data for another fix)

**Comment by LawnGnome** [comment]
LGTM. Thanks for following up on this before I woke up!
