### PR TITLE
Fix commit ID detection on Bitbucket Server single file code views

### LINKED ISSUE #4593: codenav: Wrong jump to definition line
**Sourcegraph version:** insiders

#### Steps to reproduce:

1. Ensure your Sourcegraph extension is configured to use https://k8s.sgdev.org
1. Go to https://bitbucket.sgdev.org/projects/SOUR/repos/vegeta/browse/dump.go#8
1. Authenticate with credentials in 1 Password.
1. Click on `command` and then "Go to definition"

#### Expected behavior:

Jumps to line 114: https://k8s.sgdev.org/bitbucket.sgdev.org/SOUR/vegeta@master/-/blob/main.go#L114:6

#### Actual behavior:

Jumps to line 110: https://k8s.sgdev.org/bitbucket.sgdev.org/SOUR/vegeta@master/-/blob/main.go#L110:6

### PR DESCRIPTION
**Pull request by lguychard**
Fixes #4593

This unfortunately relies on inspecting the document's context (vs. just the code view context). It was the case before this fix as well (`getCommitIDFromLink()` uses `document.querySelector()`). The alternative would be to resolve single file code views to an element that encompasses the repo header:

image

### CODE REVIEW

File: browser/src/libs/bitbucket/scrape.ts [hunk 1]
```diff
@@ -87,14 +87,27 @@ export const getCommitIDFromLink = (selector = 'a.commitid'): string => {
...
+const getCommitIDFromRevisionSelector = (): string => {
+    const revisionSelectorSpan = document.querySelector<HTMLElement>('span[data-revision-ref]')
+    if (!revisionSelectorSpan) {
+        throw new Error('Could not find span[data-revision-ref] element')
+    }
+    try {
+        const { latestCommit }: { latestCommit: string } = JSON.parse(revisionSelectorSpan.dataset.revisionRef!)
+        return latestCommit
+    } catch (err) {
+        throw new Error(`Could not determine commitID from revision selector: ${err}`)
```
Comment (felixfbecker) [inline browser/src/libs/bitbucket/scrape.ts]: This would `err.toString()`, which would include the whole stack trace (which is almost the same). The only error this can be is SyntaxError.
```suggestion
        throw new Error('Could not parse JSON from revision selector')
```
