### PR TITLE
insights: fix FirstEverCommit returning wrong commit

### LINKED ISSUE #30433: insights: gitFirstEverCommit can return any commit without a head instead of simply oldest
Unfortunately, there is another bug that caused the first search to be pre-empted as well. As an optimization we preemptively r[emove any queries that would fall before the earliest commit in the repo](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@master/-/blob/internal/vcs/git/commits.go?utm_product_name=GoLand&utm_product_version=GoLand&utm_source=JetBrains-v1.2.1#L420:8). We load the oldest commit; however, [the code that finds the oldest commit in the repo](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@master/-/blob/internal/vcs/git/commits.go?utm_product_name=GoLand&utm_product_version=GoLand&utm_source=JetBrains-v1.2.1#L420:8) can return a commit that isn't the oldest commit, but is just a commit that has no parent commit.

In this case there are 5 commits that can be "no parent", and only one of them would have triggered a search on the first data point.

_Originally posted by @coury-clark in https://github.com/sourcegraph/sourcegraph/issues/30255#issuecomment-1026190792_

The end result is that any repo with multiple HEAD revisions can queue up an incorrect backfill depending on how `rev-list` returns.

### PR DESCRIPTION
**Pull request by coury-clark**
Fixes #30433

The behavior of `FirstEverCommit` would return the wrong commit if there were multiple parent-less commits. This modifies the behavior to always return the `oldest` commit. Note: we can't use `--max-count=1` in combination with `--reverse`, since git performs the reverse after the count filter.

To test this I created a fake repository locally, served it with `src-cli`, and did the following:
1. Created an initial commit
2. Created an orphan branch, and committed a different file (to simulate divergent histories)
3. Merged the branches together

The result in logs (over a backfill) is:
```
[enterprise-worker] INFO FirstEverCommit, lines: 521a8294b0f1ec5ebd8ba9b5922d83a556ac4a09
[enterprise-worker] 40c237ff816691e28a26202854c99bd0e023c14b, first: 521a8294b0f1ec5ebd8ba9b5922d83a556ac4a09

```
And you can see from the history page that this is indeed the oldest commit.

CleanShot 2022-01-31 at 15 46 46@2x

### CODE REVIEW

File: internal/vcs/git/commits.go [hunk 1]
```diff
@@ -417,14 +417,20 @@ func FirstEverCommit(ctx context.Context, repo api.RepoName, checker authz.SubRe
...
 	if err != nil {
 		return nil, errors.WithMessage(err, fmt.Sprintf("git command %v failed (output: %q)", args, out))
 	}
-	id := api.CommitID(bytes.TrimSpace(out))
+	lines := string(bytes.TrimSpace(out))
+	tokens := strings.Split(lines, "\n")
+	if len(tokens) == 0 {
+		return nil, errors.New("FirstEverCommit returned no revisions")
+	}
+	first := tokens[0]
```
Comment (slimsag) [inline internal/vcs/git/commits.go:432]: Why in the Sourcegraph repo does this return an Aug 7 commit before Aug 1? Am I reading this wrong?:

image

**Review by slimsag — APPROVED** [review]

File: internal/vcs/git/commits.go [hunk 2]
```diff
@@ -417,14 +417,20 @@ func FirstEverCommit(ctx context.Context, repo api.RepoName, checker authz.SubRe
...
+	args := []string{"rev-list", "--reverse", "--date-order", "--max-parents=0", "HEAD"}
 	cmd := gitserver.DefaultClient.Command("git", args...)
 	cmd.Repo = repo
 	out, err := cmd.Output(ctx)
 	if err != nil {
 		return nil, errors.WithMessage(err, fmt.Sprintf("git command %v failed (output: %q)", args, out))
 	}
-	id := api.CommitID(bytes.TrimSpace(out))
+	lines := string(bytes.TrimSpace(out))
+	tokens := strings.Split(lines, "\n")
```
Comment (slimsag) [inline internal/vcs/git/commits.go:428]: strings are not very optimal for this. Ideally, you use the `bytes` package (`lines` should be `[][]byte`, `tokens` should be `[][]byte`, use `bytes.Split`, etc.) up until you get the final result and convert to an `api.CommitID`.

File: internal/vcs/git/commits.go (hunk 1 above)
Comment (coury-clark) [reply internal/vcs/git/commits.go:432]: `rev-list` is ordering by `committer date`, you've got author date there. Here is the full display of that commit:
image

File: internal/vcs/git/commits.go (hunk 2 above)
Comment (coury-clark) [reply internal/vcs/git/commits.go]: Ah cool, thanks for that! I didn't realize Go had such a useful byte package. Latest commit has this change.

Comment (slimsag) [reply internal/vcs/git/commits.go]: yeah, for more context Go strings are immutable and so the string approach involved a lot of copying compared to the byte slice approach
