### PR TITLE
web: enable cross-theme screenshots in Chromatic

### LINKED ISSUE #19955: design-refresh: enable dark mode and theme-redesign screenshot testing in Storybook
We need to screenshot test all themes in our stories to catch more regressions. Dark theme and theme redesign are not covered by Chromatic tests at the moment.

### PR DESCRIPTION
**Pull request by valerybugakov**
## Changes

Added three more variants of each existing story to test cross-theme visual regressions:

1. Default theme + Dark mode.
2. Redesign theme + Light mode.
3. Redesign theme + Dark mode.

They are not displayed in the deployed version of Storybook. It's possible to explore how components look with different themes by using toolbar toggles. Stories added are meant for Chromatic snapshots only.

Closes #19955.

## Approach

1. Additional story file `Chromatic.story` is added along with a separate story glob specific to this file.
2. Logic in `Chromatic.story` is wrapped in `isChromatic()` check to avoid applying it in other environments.
3. When Storybook executes this file, all our stories are already added to the Storybook internal store. We create three more variations of each of the stories by wrapping them into a decorator function which takes care of CSS classes toggling based on received theme options.

As a result, we have four variants of each story which are different only by CSS classes applied to `<body>`. Any new story added to the Storybook will be captured in Chromatic in all these variants.

### Alternatives

I've explored ways to achieve the same result by adding a custom decorator or addon. 

1. With a global decorator, it's possible to receive all the stories and add variations to the store on the first render call. Still, then the decorator will be executed for each story without any value. 
2. With a custom addon, it wasn't possible to reliably receive all the decorated stories. `StoryStore` is not available on `window` for addons. Channels/events usage allows receiving only serialized info about added stories, which means that we would need to create `storyFn` from it manually, which is error-prone. 

## Pricing 

This PR quadruples the number of snapshots we take in Chromatic. It's temporary; after the redesign release, we will cut this number by half, but still, even without cross-theme screenshots, we exceed the number of screenshots per month by five times.

>  Sourcegraph has used 824,335 snapshots so far this month. Sourcegraph's plan includes 150,000 snapshots a month.

We're already on the most expensive plan publicly available. Is it time to explore enterprise options that Chromatic can offer to us? 

### Pricing breakdown

This month we created 850k snapshots:

- 649$ for 150k snapshots included;
- 5600$ for 700k extra snapshots, each for 0.008$;

After the PR, we will have around 3400k snapshots per month:

- 649$ for 150k snapshots included;
- 26000$ for 3250k extra snapshots, each for 0.008$;

After the redesign release in June, we will cut the number of snapshots by half:

- 649$ for 150k snapshots included;
- 12400$ for 1550k extra snapshots, each for 0.008$;

### CODE REVIEW

File: client/shared/src/util/useRedesignToggle.ts [hunk 1]
```diff
@@ -8,6 +8,12 @@ export const REDESIGN_CLASS_NAME = 'theme-redesign'
 
 export const getIsRedesignEnabled = (): boolean => localStorage.getItem(REDESIGN_TOGGLE_KEY) === 'true'
 
+export const toggleIsRedesignEnabled = (isEnabled: boolean, element: HTMLElement = document.body): void => {
+    element.classList.toggle(REDESIGN_CLASS_NAME, isEnabled)
+    localStorage.setItem(REDESIGN_TOGGLE_KEY, String(isEnabled))
+    window.dispatchEvent(new StorageEvent('storage', { key: REDESIGN_TOGGLE_KEY, newValue: String(isEnabled) }))
+}
```
Comment (valerybugakov) [inline client/shared/src/util/useRedesignToggle.ts:15]: @limitedmage, maybe you know a way to reuse this function in `integration/utils.ts`? 

I've found only one approach to use the function defined in another module in `page.evaluate()`: `page.expose('myFunc', myFunc)`, which looks strange. I left `integration/utils.ts` untouched for now.

Comment (limitedmage) [reply client/shared/src/util/useRedesignToggle.ts:15]: I personally don't like this function living here as it should only be used by test framework, not by other product code. I recommend moving it to a different, test-only utility file (eg. in `client/storybook/src/chromatic-story/create-chromatic-story.tsx` since it's the only place where it is used anyway), or adding a comment that this should only be used by tests.

File: client/storybook/src/chromatic-story/create-chromatic-story.tsx [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+
+export const createChromaticStory = (options: CreateChromaticStoryOptions): StoryFn => () => {
+    const { storyFn, isRedesignEnabled, isDarkModeEnabled } = options
+    // The storyFn is retrieved from the StoryStore, so it already has a StoryContext.
+    const Story = storyFn as React.ComponentType
+
+    const isDarkModeEnabledInitially = useDarkMode()
+
+    useEffect(() => {
+        toggleIsRedesignEnabled(isRedesignEnabled)
```
Comment (limitedmage) [inline client/storybook/src/chromatic-story/create-chromatic-story.tsx:23]: Why not use `useRedesignToggle` instead?

Comment (valerybugakov) [reply client/storybook/src/chromatic-story/create-chromatic-story.tsx:23]: Right, I wanted to change it to `useRedesignToggle`. `toggleIsRedesignEnabled` was required for other approaches that I explored which didn't involve story decoration. After refactoring, `toggleIsRedesignEnabled` logic will be used only it test utils which makes my question above obsolete 👍

Comment (valerybugakov) [reply client/storybook/src/chromatic-story/create-chromatic-story.tsx]: Right, I wanted to change it to `useRedesignToggle`. `toggleIsRedesignEnabled` was required for other approaches that I explored which didn't involve story decoration. After refactoring, toggleIsRedesignEnabled logic will be used only it test utils which makes my question above obsolete 👍

**Review by eseliger — APPROVED** [review]
Awesome work, that's a pretty neat way of doing this.

**Review by umpox — APPROVED** [review]

File: client/storybook/src/preview.ts [hunk 3]
```diff
@@ -35,6 +36,10 @@ if (!document.body.classList.contains('theme-dark')) {
     document.body.classList.add('theme-light')
 }
 
+if (getIsRedesignEnabled()) {
+    document.body.classList.add(REDESIGN_CLASS_NAME)
+}
```
[the remark this answers is not in the document]
Comment (valerybugakov) [reply client/storybook/src/preview.ts]: With the improved Storybook API knowledge, I've solved it inside of the `RedesignToggleStorybook.tsx` `useEffect` callback. Thanks for the suggestion!

[the remark this answers is not in the document]
Comment (eseliger) [reply client/storybook/src/preview.ts]: Even better!

File: package.json [hunk 4]
```diff
@@ -122,6 +122,7 @@
     "@storybook/addons": "^6.1.11",
     "@storybook/components": "^6.1.11",
     "@storybook/core": "^6.1.11",
+    "@storybook/client-api": "6.1.11",
```
Comment (eseliger) [inline package.json:125]: Unpin :) 

```suggestion
    "@storybook/client-api": "^6.1.11",
```

File: client/shared/src/util/addRedesignVariants.tsx [hunk 5]
```diff
@@ -1,27 +0,0 @@
...
- *
- * @example
- * const { add } = storiesOf('wildcard/PageSelector', module).addDecorator(story => (
- *  <BrandedStory styles={webStyles}>
- *      {() => addRedesignVariants(<div className="container web-content mt-3">{story()}</div>)}
- *  </BrandedStory>
- * ))
- *
- */
-export const addRedesignVariants = (story: ReactElement): ReactElement => (
```
Comment (valerybugakov) [inline client/shared/src/util/addRedesignVariants.tsx:18]: Heads up: @5h1rU, @umpox, I'm removing this helper because it will be redundant after this PR lands.

File: package.json (hunk 4 above)
Comment (valerybugakov) [reply package.json:125]: Unpinning installs `@storybook/api@6.2.9` in addition to the existing versions. And we already have a couple of versions of `@storybook/client-api` installed: `6.1.11` and `6.2.21`. I've found it because of the small inconsistency in types between those versions. 

It seems that we should have all dependencies from the Storybook family pinned to one version to avoid this. But I don't want to address it in this PR. What do you think about it?

Comment (eseliger) [reply package.json:125]: actually upstream is on 6.2 now so after a merge this should be solved :)

Comment (valerybugakov) [reply package.json:125]: Yep, here everything works with unpinned version. Thanks for merging it 👍

File: client/branded/src/global-styles/colors-redesign.scss [hunk 6]
```diff
@@ -35,9 +35,7 @@ $theme-colors-redesign: (
     merged: $redesign-purple,
 );
 
-:root.theme-redesign,
-// Descendant selector is required for Storybook `addRedesignVariants` helper.
-:root .theme-redesign {
+:root.theme-redesign {
```
Comment (felixfbecker) [inline client/branded/src/global-styles/colors-redesign.scss:38]: Is it important that it's the `<html>` element? 
```suggestion
.theme-redesign {
```

**Review by felixfbecker — APPROVED** [review]
This is an awesome approach and great to have this!

Some thoughts on the cost aspect:
- For Chromatic, you can control whether a story should be included in the screenshots through a boolean parameter on the story. Maybe we could have a parameter like that for the themes too? Probably not every story needs to be screenshotted 3x. For example, for HoverOverlays, we have multiple stories showcasing different content layouts. But the colors won't change, only the layout, so it would probably be enough to just screenshot one of the layouts. We also have one screenshot that actually uses the Bitbucket styles to show that off - but we don't also have screenshots for Bitbucket with each layout, just one, and we wouldn't need to multiply that screenshot by the available themes either. Essentially instead of _(n layouts) x (m different styles) x (k themes)_, which is a lot, it would probably often be enough to do _(n layouts) + (m different styles) + (k themes)_, which would be _a lot_ less.
- One lever (one multiplier) to reduce snapshots is reducing number of builds that run Chromatic.
  - We have some code in place to run subset of the pipelines depending on the files that were changed, e.g. only Go files. It doesn't always catch everything though, e.g. if a database migration, markdown file or GraphQL schema was also changed.
  - Renovate is responsible for 6.8% of builds (checked on a sample of the last 3000 builds over the last month)
    - We could reduce the schedule from monthly to bi-monthly in renovate.json
    - We could disable automatic rebases in renovate.json (rebases can still be triggered manually through a checkbox on the PR)

File: client/branded/src/global-styles/colors-redesign.scss (hunk 6 above)
Comment (umpox) [reply client/branded/src/global-styles/colors-redesign.scss:38]: That should be fine to change I believe, I think we would need the descendant selector here otherwise as these classes are set on the `<body>` in Storybook

File: client/storybook/src/chromatic-story/Chromatic.story.tsx [hunk 7]
```diff
@@ -0,0 +1,35 @@
...
+
+import { addStory } from './add-story'
+
+if (isChromatic()) {
+    // Get an array of all stories which are already added to the StoryStore.
+    const stories = raw() as PublishedStoreItem[]
+
+    // Add three more versions of each story to test visual regressions.
+    // In other environments, these themes can be explored by a user via toolbar toggles.
+    stories.map(storeItem => {
```
[the remark this answers is not in the document]
Comment (valerybugakov) [reply client/storybook/src/chromatic-story/Chromatic.story.tsx:15]: @felixfbecker curious, why do we have `Array.forEach()` banned? 
Is it because of the edge case with ignoring array holes.

[the remark this answers is not in the document]
Comment (felixfbecker) [reply client/storybook/src/chromatic-story/Chromatic.story.tsx]: No, it's more because `for of` is more flexible and has less footguns. `forEach()` was added to the language in ES5, before `for of` existed. There's also a consistency benefit in not having to convert the two when you need a feature that only works in `forEach()` (or not even running into the issue in the first place).
- `for of` can be stepped through with "Step over" in a debugger, `forEach()` requires an extra breakpoint
- `for of` supports `await`, async functions will _not_ work as expected in `forEach()` (footgun)
- `for of` works with any iterable, not just arrays
- `for of` will correctly maintain control-flow type analysis context in TypeScript within the loop for variables referenced outside the loop. `forEach()` will lose context, because TypeScript cannot know that the callback is guaranteed to be called synchronously, so by the time it could theoretically be called the variable may have changed and the narrow type is no longer accurate.
- `for of` supports `continue` and `break`, `forEach()` only `continue` (`return`). `break` in `forEach()` requires abuse of exceptions. When converting between the two, the `return` changes semantics, which can be a hard to catch bug.
- `for of` can support nested loops with labels, `forEach()` needs abuse of exceptions to make that work.

[the remark this answers is not in the document]
Comment (valerybugakov) [reply client/storybook/src/chromatic-story/Chromatic.story.tsx]: Thanks for the details response 👍

**Comment by valerybugakov** [comment]
@felixfbecker @sourcegraph/frontend-platform, I've wrapped the Chromatic CI command into an additional check that should omit it if no related files were changed in the PR. Tested in [this PR](https://github.com/sourcegraph/sourcegraph/pull/20483). Link to [our discussion in Slack](https://sourcegraph.slack.com/archives/C01LTKUHRL3/p1619596316233400) for context.

Also, disabled automatic rebases in `renovate.json`. As @felixfbecker pointed out, we can always trigger them with a checkbox from the PR description.

I went through stories, and I agree that some of them might be excluded it I think we can do that in a separate PR later because the impact is smaller comparing to the overall number of builds. I've created [an issue](#20484) to keep this task on our radar.

File: enterprise/dev/ci/internal/ci/is-storybook-affected.go [hunk 8]
```diff
@@ -0,0 +1,64 @@
...
+}
+
+func isNotIgnoredRootFile(p string) bool {
+	return filepath.Dir(p) == "." && !contains(ignoredRootFiles, p)
+}
+
+// Run Storybook workflow only if related files were changed.
+func (c Config) isStorybookAffected() bool {
+	for _, p := range c.changedFiles {
+		if !strings.HasSuffix(p, ".md") && (strings.HasPrefix(p, "client/") || isNotIgnoredRootFile(p)) {
```
Comment (umpox) [inline enterprise/dev/ci/internal/ci/is-storybook-affected.go:59]: nit: remove the double negative to make it easier to read

```suggestion
func isAllowedRootFile(p string) bool {
	return filepath.Dir(p) == "." && !contains(ignoredRootFiles, p)
}

// Run Storybook workflow only if related files were changed.
func (c Config) isStorybookAffected() bool {
	for _, p := range c.changedFiles {
		if !strings.HasSuffix(p, ".md") && (strings.HasPrefix(p, "client/") || isAllowedRootFile(p)) {
```

**Review by umpox — APPROVED** [review]

File: enterprise/dev/ci/internal/ci/pipeline-steps.go [hunk 9]
```diff
@@ -90,17 +90,19 @@ func addSharedTests(c Config) func(pipeline *bk.Pipeline) {
 			bk.Cmd("dev/ci/codecov.sh -c -F typescript -F integration"),
 			bk.ArtifactPaths("./puppeteer/*.png"))
 
-		// Upload storybook to Chromatic
-		chromaticCommand := "yarn chromatic --exit-zero-on-changes --exit-once-uploaded"
-		if !c.isPR() {
-			chromaticCommand += " --auto-accept-changes"
+		if c.isStorybookAffected() {
```
Comment (eseliger) [inline enterprise/dev/ci/internal/ci/pipeline-steps.go:93]: I think for a master-dry-run this should also be run `c.isMasterDryRun`

File: enterprise/dev/ci/internal/ci/is-storybook-affected.go [hunk 10]
```diff
@@ -0,0 +1,64 @@
+package ci
+
+import (
+	"path/filepath"
+	"strings"
+)
+
+// Changes in the files below will be ignored by the Storybook workflow.
+var ignoredRootFiles []string = []string{
```
Comment (eseliger) [inline enterprise/dev/ci/internal/ci/is-storybook-affected.go:9]: A change in the graphql schema files should also trigger a run here - we use it to generate enums in TS and I iterate over enums to create one story per valid state.

**Review by eseliger — APPROVED** [review]

File: enterprise/dev/ci/internal/ci/is-storybook-affected.go (hunk 10 above)
Comment (valerybugakov) [reply enterprise/dev/ci/internal/ci/is-storybook-affected.go:9]: Interesting, thanks for the context.

File: enterprise/dev/ci/internal/ci/is-storybook-affected.go [hunk 11]
```diff
@@ -26,7 +26,6 @@ var ignoredRootFiles []string = []string{
 	".prettierignore",
 	".editorconfig",
 	"prettier.config.js",
-	".graphqlrc.yml",
```
Comment (eseliger) [inline enterprise/dev/ci/internal/ci/is-storybook-affected.go]: Oh pardon this was unclear and I didn't check in here earlier, `cmd/frontend/graphqlbackend/*.graphql` needs to trigger this run too.
