### PR TITLE
insights: #22079 fixing incorrect settings deserialization for code insights telemetry

### LINKED ISSUE #22079: insights: Code insights pings do not properly deserialize settings for insight counts telemetry
Settings that are deserialized for insight count telemetry are not deserializing properly in all scenarios and are causing code insights telemetry to fail.

See [here](
https://cloudlogging.app.goo.gl/2g3mTY9Za4N8Vu616) for dot-com logs

### PR DESCRIPTION
**Pull request by coury-clark**
Closes #22079 

Settings that are loaded for code insights telemetry are deserialized incorrectly causing code insights pings to fail. This PR fixes the deserialization to occur on the correct JSON object by filtering on the JSON keys, as well as absorb errors that occur during this telemetry so that valid telemetry can still serialize.

### CODE REVIEW

File: internal/usagestats/code_insights_test.go [hunk 1]
```diff
@@ -148,3 +153,228 @@ func TestWithCreationPings(t *testing.T) {
 		t.Fatal(fmt.Sprintf("want: %v got: %v", want, got))
 	}
 }
+
+func TestFilterSettingJson(t *testing.T) {
+
```
Comment (efritz) [inline internal/usagestats/code_insights_test.go:158]: lol what's with all these empty lines?

File: internal/usagestats/code_insights.go [hunk 2]
```diff
@@ -355,26 +364,47 @@ func GetSettings(ctx context.Context, db dbutil.DB, filter SettingFilter, prefix
...
+	if err := jsonc.Unmarshal(settingJson, &raw); err != nil {
+		return map[string]json.RawMessage{}, err
+	}
 
-	settings, err := GetSettings(ctx, db, filter, "searchInsights.")
+	for key := range raw {
+		if !strings.HasPrefix(key, prefix) {
+			delete(raw, key)
+		}
+	}
```
Comment (efritz) [inline internal/usagestats/code_insights.go:379]: A few questions: (1) is `raw` very large, and (2) is the return value the significantly smaller relative to the decoded settings? If so, it may be advantageous to create a new empty map and resize it until it fits rather than keeping the excess capacity.

If this is not a hot path then completely forget that suggestion, though.

File: internal/usagestats/code_insights.go [hunk 3]
```diff
@@ -355,26 +364,47 @@ func GetSettings(ctx context.Context, db dbutil.DB, filter SettingFilter, prefix
...
 		}
+
 		var temp SearchInsight
 
 		for id, body := range raw {
 			temp.ID = id
 			if err := json.Unmarshal(body, &temp); err != nil {
-				return []SearchInsight{}, err
+				// We would prefer to report some metrics if at all possible, so skip any deserialization errors
+				log15.Error(errors.Wrapf(err, "parsing error in setting body for setting key: %\n", id).Error())
```
Comment (efritz) [inline internal/usagestats/code_insights.go:406]:
```suggestion
				log15.Error("parsing error in setting body", "id", id, "error", err)
```

**Review by efritz — APPROVED** [review]

File: internal/usagestats/code_insights.go [hunk 4]
```diff
@@ -116,15 +121,19 @@ func GetCodeInsightsUsageStatistics(ctx context.Context, db dbutil.DB) (*types.C
 	}
 	stats.WeeklyAggregatedUsage = weeklyUsage
 
+	// These two pings are slightly more fragile than the others because they deserialize json from settings. They are
+	// also less important. So, in the case of any errors here we will not fail the entire ping for code insights.
 	timeIntervals, err := GetTimeStepCounts(ctx, db)
 	if err != nil {
-		return nil, err
+		log15.Error(fmt.Sprintf("code-insights/GetTimeStepCounts: %v", err))
```
Comment (efritz) [inline internal/usagestats/code_insights.go:128]: Same suggestion as below on the log call. Since log15 can do structured logging we should try to minimize the amount of Sprintf calls to the actual message (and instead just supply the information as key/value pairs so we can search/sort/slice in our log ingestion/storage infra).

File: internal/usagestats/code_insights_test.go (hunk 1 above)
Comment (coury-clark) [reply internal/usagestats/code_insights_test.go:158]: Partly a badly configured formatter and partly habits from a different code base. Not entirely sure why these empty lines keep appearing below method names.

Comment (slimsag) [reply internal/usagestats/code_insights_test.go:158]: I wish gofmt would just sort these out for us :)

**Review by slimsag — APPROVED** [review]
LGTM aside from Eric's comments
