### PR TITLE
Search suggestions: remove type:code, add type:file

### LINKED ISSUE #8741: type:file missing in smartSearchField
`type:file` is valid, but I get the squiggles. `file` should be whitelisted.

Screen Shot 2020-03-02 at 2 45 09 PM

### LINKED ISSUE #8742: type:code doesn't work in smartSearchField
I get no results when I do `type:code`. `code` isn't a documented option, or supported in the backend. I think we should add it and this is a good thing to have. It's not super straightforward, because we will currently return results for both file content and file paths by default, and restricting it to just file contents isn't we allow right now (we'd have to filter things from Zoekt). So, for now, I suggest we remove `type:code`. 

Screen Shot 2020-03-02 at 2 46 01 PM

### PR DESCRIPTION
**Pull request by lguychard**
Fixes #8742

Removed `type:code` as a valid value, also removed it from "legacy" suggestions, where we had the issue as well.

image

Fixes #8741

Added `type:file` as a valid value, also added it to "legacy" suggestions, where we had the issue as well.

image

### CODE REVIEW

**Comment by lguychard** [comment]
Added https://github.com/sourcegraph/sourcegraph/pull/8754/commits/54b9767cc2c64b5bda02176ac6ea075f96316409 to this PR, cc @attfarhan if you want to vet this significant additional change 😬

File: web/src/search/searchFilterSuggestions.ts [hunk 1]
```diff
@@ -102,8 +102,7 @@ export const searchFilterSuggestions: SearchFilterSuggestions = {
         ),
     },
     type: {
-        default: 'code',
-        values: [{ value: 'code' }, { value: 'diff' }, { value: 'commit' }, { value: 'symbol' }].map(
+        values: [{ value: 'diff' }, { value: 'commit' }, { value: 'symbol' }, { value: 'file' }].map(
```
Comment (attfarhan) [inline web/src/search/searchFilterSuggestions.ts]: This should include `path` too

```suggestion
        values: [{ value: 'diff' }, { value: 'commit' }, { value: 'symbol' }, { value: 'file' }, { value: 'path' }].map(
```
