### PR TITLE
ensure we have commits locally before finding common merge-base

### LINKED ISSUE #12584: Changeset diff render can fail when gitserver hasn't synced yet
When I update a changesets branch, the webhook updates the metadata. Hence, the head oid changes.
When a changeset fetch occurs with an expanded changeset the diff fails when there’s a new commit, because gitserver doesn’t have the commit yet

```
Git command [git merge-base -- 0440892751ca39eb2cdbf88ca2e4e42ea9252cb4 d3647d131ff88f2fe3393d1cb20b6de208f39c5c] failed (output: "fatal: Not a valid commit name d3647d131ff88f2fe3393d1cb20b6de208f39c5c"): exit status 128
```

I think we should ensure the revision exists before we return the diff for it.

### PR DESCRIPTION
**Pull request by chrispine**
Make sure we call `ResolveRevision` before we find the common merge-base, in case the commits don't exist locally.

I tested it by creating this campaign:

```
name: test-3487562349
description: just a random test

importChangesets:
- repository: github.com/sourcegraph/test
  externalIDs: [7]
```

I then added a commit to that PR, went to the campaigns UI, and pressed the "refresh" button. Before this fix, I got [the error](https://github.com/sourcegraph/sourcegraph/issues/12584). After the fix, it correctly refreshed the diff.

Closes #12584.

### CODE REVIEW

**Comment by chrispine** [comment]
There's a failing test; looking into it.

File: cmd/frontend/graphqlbackend/repository_comparison.go [hunk 1]
```diff
@@ -104,37 +104,31 @@ func NewRepositoryComparison(ctx context.Context, r *RepositoryResolver, args *R
...
-		return nil, baseErr
-	}
-	if headErr != nil {
-		return nil, headErr
+	// Make sure we call ResolveRevision before we find the common merge-base, in case
+	// the commits don't exist locally.
+	_, err = git.ResolveRevision(ctx, *grepo, nil, baseRevspec, git.ResolveRevisionOptions{NoEnsureRevision: false})
+	if err != nil {
+		return nil, err
+	}
```
Comment (eseliger) [inline cmd/frontend/graphqlbackend/repository_comparison.go:117]: I think we can parallelize getCommit for the head and ResolveRevision here to reduce the wait time when we actually need to fetch the repo

**Review by eseliger — APPROVED** [review]
Cool, I expected this to be much harder 🤯 

For the failing test: I think a test is missing a mock of `git.ResolveRevision` now.

File: cmd/frontend/graphqlbackend/repository_comparison.go [hunk 2]
```diff
@@ -104,37 +104,31 @@ func NewRepositoryComparison(ctx context.Context, r *RepositoryResolver, args *R
...
-	}()
-	wg.Wait()
-	if baseErr != nil {
-		return nil, baseErr
-	}
-	if headErr != nil {
-		return nil, headErr
+	// Make sure we call ResolveRevision before we find the common merge-base, in case
+	// the commits don't exist locally.
+	_, err = git.ResolveRevision(ctx, *grepo, nil, baseRevspec, git.ResolveRevisionOptions{NoEnsureRevision: false})
```
Comment (mrnugget) [inline cmd/frontend/graphqlbackend/repository_comparison.go:114]: The default value of a boolean in a struct in Go is `false` so there's no need to initialise it. Exception: often helps readability to make a value explicitly false. But since we _do_ want to ensure that the revision exists locally, it's more confusing to read the double-negative than not.

```suggestion
	_, err = git.ResolveRevision(ctx, *grepo, nil, baseRevspec, git.ResolveRevisionOptions{})
```

**Review by mrnugget — COMMENTED** [review]
Can you explain why this solves the issue?

I assumed that it's the head commit that's missing, because the original error in https://github.com/sourcegraph/sourcegraph/issues/12584 complains about the _second_ parameter in `git merge-base` to be missing:

```
Git command [git merge-base -- 0440892751ca39eb2cdbf88ca2e4e42ea9252cb4 d3647d131ff88f2fe3393d1cb20b6de208f39c5c] failed (output: "fatal: Not a valid commit name d3647d131ff88f2fe3393d1cb20b6de208f39c5c"): exit status 128
```

And here's how we call it here:

```go
git.MergeBase(ctx, *grepo, api.CommitID(baseRevspec), api.CommitID(headRevspec))
```

So, how does fetching the base revspec (which didn't change when you pushed a new commit) fix this?

---

Another note: we already call `ResolveRevision` for the `headRevspec` in the `getCommit` function:

https://github.com/sourcegraph/sourcegraph/blob/ed54dbd7fe6c789972e697be3a1daffc87e0123a/cmd/frontend/graphqlbackend/repository_comparison.go#L88-L93

And that uses `EnsureRevision` except when `FetchMissing` is false, which it isn't in our case:

https://github.com/sourcegraph/sourcegraph/blob/ed54dbd7fe6c789972e697be3a1daffc87e0123a/enterprise/internal/campaigns/resolvers/changeset.go#L451-L455

File: cmd/frontend/graphqlbackend/repository_comparison.go (hunk 1 above)
Comment (mrnugget) [reply cmd/frontend/graphqlbackend/repository_comparison.go:117]: Agree with that. I think we should keep the waitgroup.

**Comment by eseliger** [comment]
> Edit: Is it possible that the fix is to simply run head, err := getCommit(ctx, *grepo, headRevspec) before the call to git.MergeBase so that headRevSpec is ensured to be there, instead of running both in parallel? Because I just checked out this branch, commented out the new call to git.ResolveRevision and it still works.

That was the idea of this fix (we paired on this briefly). It first runs the logic for the head, which gets ensured thereby. Then, for the case where baseOid was updated from a webhook, ensures the baserev as well. Then, we can safely run merge-base and finally resolve the merge-base to a commit.

I think the head call and the EnsureRevision for the base can run in parallel though.

**Comment by mrnugget** [comment]
> I think the head call and the EnsureRevision for the base can run in parallel though.

But wouldn't it be better if the `MergeBase` call uses the correct head OID (vs. the revspec)?

**Comment by eseliger** [comment]
> But wouldn't it be better if the MergeBase call uses the correct head OID (vs. the revspec)?

Since merge-base is just the last common ancestor, I think it won't make much of a difference, but not sure.

**Comment by chrispine** [comment]
@eseliger and I did some experiments, and it looks like we don't fetch the new base revision when a new commit is pushed onto the base branch. So removing the call to `ResolveRevision()` is just fine (as @mrnugget predicted/discovered).

Because of this, I don't think there's nothing left to parallelize: we have to get the head commit before the call to `MergeBase()`.

File: cmd/frontend/graphqlbackend/repository_comparison.go (hunk 1 above)
Comment (chrispine) [reply cmd/frontend/graphqlbackend/repository_comparison.go]: As I commented below, we deleted the call to `ResolveRevision()`, so no need for the waitgroup.

**Review by mrnugget — APPROVED** [review]
