### PR TITLE
Fix requests with long retry times failing

### LINKED ISSUE #49300: Investigate GitHub content length body length error
The Starburst code host connection sync on sourcegraph.com sometimes fails with:

Image

It would be good to know if this is GitHub's API returning an incorrect response, or if it is caused by `github-proxy` restarting, or something else entirely. We need to know if we could possibly do something, like retry the request, if this happens, because it fails the entire job.

### PR DESCRIPTION
**Pull request by pjlast**
Closes #49300 

Go's `http.Client` keeps connections alive by default. This caches the body of the request.
However, when retrying a request after a long time (~90 seconds), reading the body again will fail as the body is no longer cached once the connection is no longer alive.

This PR changes or clients so that the body is stored before requests are done that can be retried. This way we can reset the body before retrying a request.

## Test plan

Some unit tests added, current ones still passing

### CODE REVIEW

File: internal/extsvc/azuredevops/client.go [hunk 1]
```diff
@@ -107,9 +108,15 @@ func (c *client) do(ctx context.Context, req *http.Request, urlOverride string,
 	queryParams.Set("api-version", apiVersion)
 	req.URL.RawQuery = queryParams.Encode()
 	req.URL = u.ResolveReference(req.URL)
+	var reqBody []byte
 	if req.Body != nil {
 		req.Header.Set("Content-Type", "application/json")
+		reqBody, err = io.ReadAll(req.Body)
+		if err != nil {
+			return "", nil
```
Comment (cbart) [inline internal/extsvc/azuredevops/client.go:116]:
```suggestion
			return "", err
```

Don't we want to return the err if body cannot be read?

File: internal/extsvc/github/v4.go [hunk 2]
```diff
@@ -173,6 +174,7 @@ func (c *V4Client) requestGraphQL(ctx context.Context, query string, vars map[st
 
 	for c.waitForRateLimit && err != nil && numRetries < c.maxRateLimitRetries &&
 		errors.As(err, &apiError) && apiError.Code == http.StatusForbidden {
+		req.Body = io.NopCloser(bytes.NewBuffer(reqBody))
```
Comment (cbart) [inline internal/extsvc/github/v4.go:177]: In line 144, I see that the body is initialized to bytes.NewBuffer(reqBody) anyways. Why overwrite the Body here rather than just wrapping it in io.NopCloser there (if needed?)

**Review by cbart — APPROVED** [review]

**Review by sashaostrikov — APPROVED** [review]
LGTM! I'd also create `main-dry-run` branch just in case

File: internal/extsvc/github/v4.go (hunk 2 above)
Comment (pjlast) [reply internal/extsvc/github/v4.go:177]: You have to create a new `NopCloser`. After the first request, the Reader will read until the end of the body. If you try to use the same reader again, it will return an empty body, so you need to recreate it.

The body on line 144 is passed into the `http.NewRequest` function, which wraps the body in a `NopCloser` in there.

File: internal/extsvc/azuredevops/client.go (hunk 1 above)
Comment (pjlast) [reply internal/extsvc/azuredevops/client.go:116]: Woops! Thanks
