### PR TITLE
search: Add repo: filter if necessary when a revision filter is clicked

### LINKED ISSUE #24841: Revisions sidebar section: Add `repo:` filter if not already present to avoid broken queries
It's possible that the revisions section is shown (results only from a single repository) without a `repo:` filter in the query. In that case clicking on a revision will fail:

The corresponding `repo:` filter should be added if necessary.

### PR DESCRIPTION
**Pull request by fkling**
Fixes #24841

This PR builds on top of #24996 and changes the `submitQuery` action to accept multiple modifications instead. This is certainly not the final structure of the API, but it shows the direction this could go.

https://user-images.githubusercontent.com/179026/133821911-7bb551f8-352f-4efc-bdab-3c51357d4116.mp4

### CODE REVIEW

File: client/web/src/search/navbarSearchQueryState.ts [hunk 1]
```diff
@@ -5,21 +5,64 @@
...
+      }
+    | {
+          type: 'updateOrAppendFilter'
+          field: FilterType
+          value: string
+      }
+    // Only exists for the filters from the serach sidebar since they come in
+    // filter:value form. Should not be used elsewhere.
+    | {
+          type: 'toggleSubstring'
```
Comment (limitedmage) [inline client/web/src/search/navbarSearchQueryState.ts:35]:
```suggestion
          type: 'toggleFilter'
```

**Review by limitedmage — APPROVED** [review]

File: client/web/src/search/navbarSearchQueryState.ts [hunk 2]
```diff
@@ -5,21 +5,64 @@
...
 type QueryStateUpdate = QueryState | ((queryState: QueryState) => QueryState)
 
+export type QueryUpdate =
+    | {
+          type: 'appendFilter'
+          field: FilterType
+          value: string
+          /**
+           * If true, the filter will only be appended a filter with the same name
+           * doesn't already exist in the query.
```
Comment (rvantonder) [inline client/web/src/search/navbarSearchQueryState.ts:23]:
```suggestion
           * If true, append the value only when the filter doesn't already exist in the query.
```

just a suggestion to fix a bit of word salad in the comment

File: client/web/src/search/navbarSearchQueryState.ts [hunk 3]
```diff
@@ -5,21 +5,64 @@
...
+           */
+          unique?: true
+      }
+    | {
+          type: 'updateOrAppendFilter'
+          field: FilterType
+          value: string
+      }
+    // Only exists for the filters from the serach sidebar since they come in
```
Comment (rvantonder) [inline client/web/src/search/navbarSearchQueryState.ts:32]:
```suggestion
    // Only exists for the filters from the search sidebar since they come in
```

I make this typo all the time :3

File: client/web/src/search/navbarSearchQueryState.ts [hunk 4]
```diff
@@ -5,21 +5,64 @@
...
+                break
+            case 'updateOrAppendFilter':
+                query = updateFilter(query, update.field, update.value)
+                break
+            case 'toggleSubstring':
+                query = toggleSearchFilter(query, update.value)
+                break
+        }
+    }
+    return query
```
Comment (rvantonder) [inline client/web/src/search/navbarSearchQueryState.ts:55]: I'd probably `updates.reduce(...)` here but I hear reduce AKA fold is not popular in JS/TS.

**Review by rvantonder — APPROVED** [review]

File: client/web/src/search/navbarSearchQueryState.ts (hunk 1 above)
Comment (fkling) [reply client/web/src/search/navbarSearchQueryState.ts:35]: My intention was to express that this update action doesn't take the "usual" filter name and value as argument (but a combination of the two). Do you think it's unnecessary?

File: client/web/src/search/navbarSearchQueryState.ts (hunk 4 above)
Comment (fkling) [reply client/web/src/search/navbarSearchQueryState.ts:54]: I think that's because it's often used in a way where a loop would make more sense, but I agree that this is a good use case.

File: client/web/src/search/navbarSearchQueryState.ts (hunk 1 above)
Comment (limitedmage) [reply client/web/src/search/navbarSearchQueryState.ts:35]: Ah I see, because this one doesn't take a `FilterType`. So with this one you can have multiples of the same filter, right? And toggling will remove the exact substring if it exists. In this case, I think renaming this instead to `'toggleSubquery'` and the function  in `helpers.ts` to `toggleSubquery` makes the most sense. This is not exactly a substring match because the subquery needs to be bound by whitespace.

Comment (fkling) [reply client/web/src/search/navbarSearchQueryState.ts:35]: Great suggestion, thank you!
