### PR TITLE
batches: Changeset Spec Exceeds Database Limit

### LINKED ISSUE #39242: Changeset Spec Exceeds Database Limit
The table `changeset_specs` has a column `spec` of type `jsonb`. PostgreSQL limits `jsonb` to 255 MB. If a changeset exceeds this limit, the following error occurs,

```text
ERROR: string too long to represent as jsonb string (SQLSTATE 54000)
```

## Possible Fixes

* Prevent and changesets from exceeding the 255 MB limit by adding "guards"
    * If a changeset surpasses the limit, maybe point the user to docs to decrease changeset sizes (for example, [transformchanges](https://docs.sourcegraph.com/batch_changes/references/batch_spec_yaml_reference#transformchanges))
* Rethink storing the `spec` in the `jsonb` column in the `chageset_specs` table.
    * This will probably be a larger effort and may need a follow up Issue for long term 

## Scenarios

Logging GraphQL requests impacts the behavior of the errors (simple `502` vs actual error message). But, the backing error is the same.

### Environment Variables

* `NO_GRAPHQL_LOG=true`

#### Batch Spec

```yaml
# Generates 676.3 MB changeset spec
name: large-changeset
description: Add Hello World to READMEs

on:
  - repositoriesMatchingQuery: file:README.md repo:^github.com/odoo/odoo$

steps:
  - run: find . -name "*.po" -exec sed -i 's/b/c/g' {} \;
    container: alpine:3

changesetTemplate:
  title: Hello World
  body: My first batch change!
  branch: hello-world-1 # Push the commit to this branch.
  commit:
    message: Append Hello World to all README.md files
  published: false # Do not publish any changes to the code hosts yet
```

#### Response

```json
{
  "message": "inserter.Flush: ERROR: string too long to represent as jsonb string (SQLSTATE 54000)",
  "path": [
    "createChangesetSpec"
  ]
}
```

#### Logs

```text
[       frontend] ERROR Inserter.database.batch.Flush batch/batch.go:224 operation.error {"batchSize": 14, "payloadSize": 24, "tableName": "changeset_specs", "columnNames": "rand_id,spec,batch_spec_id,repo_id,user_id,diff_stat_added,diff_stat_changed,diff_stat_deleted,created_at,updated_at,fork_namespace,external_id,head_ref,title", "numColumns": 14, "maxBatchSize": 32760, "count": 1, "elapsed": 4.235910458, "error": "ERROR: string too long to represent as jsonb string (SQLSTATE 54000)"}
[       frontend] ERROR enterprise.batches.dbstore.CreateChangesetSpec store/changeset_specs.go:128 operation.error {"Count": 1, "count": 1, "elapsed": 32.111408542, "error": "inserter.Flush: ERROR: string too long to represent as jsonb string (SQLSTATE 54000)"}
[       frontend] ERROR enterprise.batches.service.CreateChangesetSpec service/service.go:758 operation.error {"count": 1, "elapsed": 61.167864, "error": "inserter.Flush: ERROR: string too long to represent as jsonb string (SQLSTATE 54000)"}
```

### Environment Variables

N/A

#### Batch Spec

```yaml
# Generates 1.0 GB changeset spec
name: large-changeset
description: Add Hello World to READMEs

on:
  - repositoriesMatchingQuery: file:README.md repo:^github.com/odoo/odoo$

steps:
  - run: find . -name "*.po" -exec sed -i 's/a/b/g' {} \;
    container: alpine:3

changesetTemplate:
  title: Hello World
  body: My first batch change!
  branch: hello-world-1 # Push the commit to this branch.
  commit:
    message: Append Hello World to all README.md files
  published: false # Do not publish any changes to the code hosts yet
```

#### Response

```text
error: 502 Bad Gateway
```

#### Logs

```text
[       frontend] ERROR Inserter.database.batch.Flush batch/batch.go:224 operation.error {"batchSize": 14, "payloadSize": 24, "tableName": "changeset_specs", "columnNames": "rand_id,spec,batch_spec_id,repo_id,user_id,diff_stat_added,diff_stat_changed,diff_stat_deleted,created_at,updated_at,fork_namespace,external_id,head_ref,title", "numColumns": 14, "maxBatchSize": 32760, "count": 1, "elapsed": 4.927489625, "error": "ERROR: string too long to represent as jsonb string (SQLSTATE 54000)"}
[       frontend] ERROR enterprise.batches.dbstore.CreateChangesetSpec store/changeset_specs.go:128 operation.error {"Count": 1, "count": 1, "elapsed": 32.148294167, "error": "inserter.Flush: ERROR: string too long to represent as jsonb string (SQLSTATE 54000)"}
[       frontend] ERROR enterprise.batches.service.CreateChangesetSpec service/service.go:758 operation.error {"count": 1, "elapsed": 63.868031875, "error": "inserter.Flush: ERROR: string too long to represent as jsonb string (SQLSTATE 54000)"}
```

### PR DESCRIPTION
**Pull request by BolajiOlajide**
Closes #39242

## Test plan

Before #39471, we ran into an edge case where a batch change that generated a large changeset couldn't be saved in the database. The error gotten was

```txt
ERROR: string too long to represent as jsonb string (SQLSTATE 54000)
```

This happened because the size limit for the `jsonb` field in the `changeset_specs` table was around 256MB, so running a batch spec (example attached below) would return an error.

```txt
# Generates 676.3 MB changeset spec
name: large-changeset
description: Add Hello World to READMEs

on:
  - repositoriesMatchingQuery: file:README.md repo:^github.com/odoo/odoo$

steps:
  - run: find . -name "*.po" -exec sed -i 's/b/c/g' {} \;
    container: alpine:3

changesetTemplate:
  title: Hello World
  body: My first batch change!
  branch: hello-world-1 # Push the commit to this branch.
  commit:
    message: Append Hello World to all README.md files
  published: false # Do not publish any changes to the code hosts yet
```

This PR adds a check to inform the user to make use of [transformChanges](https://docs.sourcegraph.com/batch_changes/references/batch_spec_yaml_reference#transformchanges) if the size of the changeset gets too large. Since #39471, that limit has increased to 1G.

### CODE REVIEW

File: enterprise/internal/batches/store/changeset_specs.go [hunk 1]
```diff
@@ -129,6 +130,11 @@ func (s *Store) CreateChangesetSpec(ctx context.Context, cs ...*btypes.Changeset
 				dbutil.NewNullString(c.CommitAuthorEmail),
 				c.Type,
 			); err != nil {
+				// We check if the resulting error is because the changeset is too large
+				if strings.Contains(err.Error(), "string too long to represent as jsonb string") {
```
[the remark this answers is not in the document]
Comment (BolajiOlajide) [reply enterprise/internal/batches/store/changeset_specs.go:134]: Oh crap! I missed that.
I'll update this. I tested with a very large changeset but then after rebasing against `main` I didn't test extensively, I'll do it again and update. 
Thanks

Comment (courier-new) [inline enterprise/internal/batches/store/changeset_specs.go:134]: No strong feelings, but is it possible to proactively check for the size of the changeset before attempting the insert, rather than just reacting to the error? Feels a bit more explicit.

File: enterprise/internal/batches/store/changeset_specs.go [hunk 2]
```diff
@@ -107,6 +109,13 @@ func (s *Store) CreateChangesetSpec(ctx context.Context, cs ...*btypes.Changeset
 				}
 			}
 
+			// We check if the resulting diff is greater than 1GB, since the limit
+			// for the diff column (which is bytea) is 1GB
+			if len(c.Diff) > OneGigabyte {
+				link := "https://docs.sourcegraph.com/batch_changes/references/batch_spec_yaml_reference#transformchanges"
+				return errors.Errorf("The changeset generated is over the size limit. You can make use of [transformChanges](%s) to break down the changesets into smaller pieces.", link)
+			}
```
Comment (BolajiOlajide) [inline enterprise/internal/batches/store/changeset_specs.go:117]: Is this a better approach to this?

We proactively check the size of the `diff` before inserting it into the database.

Comment (BolajiOlajide) [reply enterprise/internal/batches/store/changeset_specs.go:117]: @courier-new @eseliger

File: enterprise/internal/batches/store/changeset_specs.go [hunk 3]
```diff
@@ -107,6 +109,13 @@ func (s *Store) CreateChangesetSpec(ctx context.Context, cs ...*btypes.Changeset
 				}
 			}
 
+			// We check if the resulting diff is greater than 1GB, since the limit
+			// for the diff column (which is bytea) is 1GB
+			if len(c.Diff) > OneGigabyte {
+				link := "https://docs.sourcegraph.com/batch_changes/references/batch_spec_yaml_reference#transformchanges"
+				return errors.Errorf("The changeset generated is over the size limit. You can make use of [transformChanges](%s) to break down the changesets into smaller pieces.", link)
```
Comment (eseliger) [inline enterprise/internal/batches/store/changeset_specs.go:116]:
```suggestion
				return errors.Errorf("The changeset patch generated is over the size limit. You can make use of [transformChanges](%s) to break down the changesets into smaller pieces.", link)
```
Maybe? Might make it a little clearer that it's explicitly the diff being troublesome here.

File: enterprise/internal/batches/store/changeset_specs.go (hunk 2 above)
Comment (eseliger) [reply enterprise/internal/batches/store/changeset_specs.go:117]: Works for me!

**Review by eseliger — APPROVED** [review]
Thank you!

File: enterprise/internal/batches/store/changeset_specs.go [hunk 4]
```diff
@@ -76,6 +76,8 @@ var changesetSpecColumns = SQLColumns{
 	"changeset_specs.type",
 }
 
+var OneGigabyte = 1000000000
```
Comment (eseliger) [inline enterprise/internal/batches/store/changeset_specs.go:79]: nit: I don't think this need to be exported (uppercased)

Comment (BolajiOlajide) [reply enterprise/internal/batches/store/changeset_specs.go:79]: Gotcha!

File: enterprise/internal/batches/store/changeset_specs.go (hunk 2 above)
Comment (courier-new) [reply enterprise/internal/batches/store/changeset_specs.go]: That's perfect, thanks Bolaji!!
