### PR TITLE
fix(a11y): Add aria-label to `DiffStat`, use Tooltip

### LINKED ISSUE #35535: [Accessibility]: Compare page: Diff overview is difficult to undestand
### Audit type

Screen reader navigation

### User journey audit issue

https://github.com/sourcegraph/sourcegraph/issues/34426

### Problem description

image

The colored dots aren't red out by the screen reader, which would be fine - except that only "28" is read out with no real context.

### Expected behavior

We should instead provide a text overview of the colored dots (e.g. 28 lines changed, 20 additions, 8 deletions)

### Additional details

_No response_

### Assigning labels

- [X] Please give this issue an estimate by applying a label like `estimate/Xd`, where X is the estimated number of days it will take to complete.
- [X] If this issue is specific to a specific Sourcegraph product, please assign the appropriate team label to this issue.
- [ ] If this issue will require input from designers in order to complete, please assign the label `needs-design`.
- [ ] If you are confident that this issue should be fixed by GitStart, please assign the label `gitstart`.

### Owner

This issue will be fixed by my team, I have assigned a relevant member to it, or I will do so in the near future.

### PR DESCRIPTION
**Pull request by plibither8**
This PR:
1. Adds an `aria-label` to the diff stats' `<div>` containing the diff line summary
2. Refactors `data-tooltip` to `Tooltip` in the same component

I chose to have the entire summary be read out instead of the just `"29 lines changed"` to supply information at par with what a non-visually-impaired person would understand by seeing the diff squares too.

Closes #35535

## Test plan

* Tested using a screen reader, focussing on the diff header now properly reads out the entire summary (`"16 additions, 3 changes, 7 deletions"`) before reading the file name.
* The Jest snapshots have been updated to reflect the changes.

## App preview:

- [Web](https://sg-web-mihir-35535-diff-overview-screen.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-wgajciqmzr.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

File: client/web/src/components/diff/DiffStat.tsx [hunk 1]
```diff
@@ -47,23 +48,29 @@ export const DiffStat: React.FunctionComponent<React.PropsWithChildren<DiffStatP
         labels.push(`${numberWithCommas(deleted)} ${pluralize('deletion', deleted)}`)
     }
     return (
-        <div className={classNames(styles.diffStat, className)} data-tooltip={labels.join(', ')}>
```
Comment (jasongornall) [inline client/web/src/components/diff/DiffStat.tsx:50]: what does the end result looks like here? is it human readable? Also what happens (or can this happen?) that added changed and deleted are all zero?

**Review by jasongornall — APPROVED** [review]

File: client/web/src/components/diff/DiffStat.tsx (hunk 1 above)
Comment (plibither8) [reply client/web/src/components/diff/DiffStat.tsx:50]: @jasongornall Hmm not sure what you mean by this - where here are we accommodating for added changed and deleted to be all zero?

File: client/web/src/components/diff/DiffStat.tsx [hunk 2]
```diff
@@ -47,24 +48,26 @@ export const DiffStat: React.FunctionComponent<React.PropsWithChildren<DiffStatP
...
-                        <strong className="a11y-ignore text-warning mr-1">&bull;{numberWithCommas(changed)}</strong>
-                    )}
-                    <strong className="a11y-ignore text-danger">&minus;{numberWithCommas(deleted)}</strong>
-                </>
-            ) : (
-                <small>{numberWithCommas(total + changed)}</small>
-            )}
-        </div>
+        <Tooltip content={labels.join(', ')}>
+            <div className={classNames(styles.diffStat, className)} aria-label={labels.join(', ')}>
```
Comment (courier-new) [inline client/web/src/components/diff/DiffStat.tsx:52]: Hey Mihir!! Thanks for making the a11y fix and updating this to the new `Tooltip` component!

I think this line breaks the usage of the diff stat in a Batch Changes component, though:

Before:
Screen Shot 2022-06-15 at 8 37 22 AM


After:
Screen Shot 2022-06-15 at 8 37 29 AM

We rely on being able to pass the `className` to the outermost element rendered by `DiffStat`, which used to be this `<div />`, but now that's wrapped by the extra level of `<span />` generated by `Tooltip`. Would `Tooltip` still work if the order of elements is flipped? Like:

```tsx
<div className={classNames(style.diffStat, className)} aria-label={labels.join(', ')}>
  <Tooltip content={labels.join(', ')}>
    {/* ... */}
```

Or if not, could we have an additional `<div />` wrapper as the outermost element to take the `className` prop instead? Like:

```tsx
<div className={className}>
  <Tooltip content={labels.join(', ')}>
    <div className={styles.diffStat} aria-label={labels.join(', ')}>
      {/* ... */}
```

Sorry for the inconvenience. 🙁 We used to have more Percy/Chromatic coverage of this component but we had to turn it off. This part of our UI is also brand new.

Comment (courier-new) [reply client/web/src/components/diff/DiffStat.tsx:52]: (Opened a PR for that part!!)

Comment (plibither8) [reply client/web/src/components/diff/DiffStat.tsx:52]: @courier-new thanks so much for the suggestions and feedback! :D

Chromatic had found a similar regression in the batch changes' repo page which I fixed in this line: https://github.com/sourcegraph/sourcegraph/pull/37089/files#diff-250aca42b7a9cf239d9b53b1e882c68f1fb4c66902847acd109eaf55414ac9a8R70, by wrapping the `DiffStat` in a new `<div />` like how you suggested. I'll experiment with doing this wrapping inside the `DiffStat` component itself and let you know! :))

> (Opened a PR for that part!!)

Awesome! 😄

Comment (plibither8) [reply client/web/src/components/diff/DiffStat.tsx]: @courier-new just pushed a commit that wraps the `Tooltip` in a `<div />` and passes the classname into it, as you suggested :)). Along with that, also fixed some issues where the tooltip was not showing because of the `Collapsible` components `stretched-link` class.

A UI review seems to be pending but I'm pretty sure that's a flake from the looks of it.

Comment (courier-new) [reply client/web/src/components/diff/DiffStat.tsx]: > A UI review seems to be pending but I'm pretty sure that's a flake from the looks of it.

Yeah I think it'll go away if you update this branch from `main` -- looks like the reverse of a change from a PR I merged yesterday. 🙂

**Review by courier-new — APPROVED** [review]
Thanks so much!! Approving to unblock if you want to get this in before branch cut, but left a couple small comments. 😄 I'm out on PTO tomorrow, but feel free to loop in someone else from the team if you want to double-check anything!

File: client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspaceDetails.tsx [hunk 3]
```diff
@@ -392,7 +392,11 @@ const ChangesetSpecNode: React.FunctionComponent<React.PropsWithChildren<Changes
                         {node.description.headRef}
                     </span>
                 </div>
-                <DiffStat {...node.description.diffStat} expandedCounts={true} className="ml-3" />
+                <DiffStat
+                    {...node.description.diffStat}
+                    expandedCounts={true}
+                    className={classNames(styles.stepDiffStat, 'ml-3')}
```
[the remark this answers is not in the document]
Comment (courier-new) [reply client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspaceDetails.tsx:398]: (Sorry, this apparently isn't checked by Percy/Chromatic either 🙃)

File: client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspaceDetails.module.scss [hunk 4]
```diff
@@ -65,6 +65,8 @@
 }
 
 .step-diff-stat {
+    // Bringing the element above the button so the tooltip is triggered on-hover
+    z-index: 1;
```
[the remark this answers is not in the document]
Comment (plibither8) [reply client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspaceDetails.module.scss:69]: Ahh yep, I saw that warning too, but interestingly it does make a difference! Nevertheless, I've added the `isolation: isolate` rule too, so the warning's gone :)

File: client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspaceDetails.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (plibither8) [reply client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspaceDetails.tsx:398]: > adding that may change the padding/margin and border rules?

I had checked this before adding those styles, and nope, it doesn't change the element visually. The `&:last-child` rules override and remove the applied paddings and margins. I added this classname here so the `z-index` rule is applied to this `DiffStat` too! 🙂

File: client/web/src/enterprise/batches/repo/BatchChangeRepoPage.tsx [hunk 5]
```diff
@@ -65,9 +65,9 @@ export const BatchChangeRepoPage: React.FunctionComponent<React.PropsWithChildre
                 }
             />
             {hasChangesets && stats?.batchChangesDiffStat && stats?.changesetsStats ? (
-                <div className="d-flex align-items-center mt-4 mb-3">
-                    <H2 className="mb-0 pb-1">{repoDisplayName}</H2>
-                    <DiffStat className="d-flex flex-1 ml-2" expandedCounts={true} {...stats.batchChangesDiffStat} />
+                <div className="mt-4 mb-3 d-flex align-items-center">
+                    <H2 className="pb-1 mb-0">{repoDisplayName}</H2>
+                    <DiffStat className="flex-1 ml-2 d-flex" expandedCounts={true} {...stats.batchChangesDiffStat} />
```
[the remark this answers is not in the document]
Comment (plibither8) [reply client/web/src/enterprise/batches/repo/BatchChangeRepoPage.tsx:70]: Whoops, my bad! I was using Tailwind for a project earlier and the "Headwind" extension sorts the class names :P. Will change it back :))

**Comment by plibither8** [comment]
Merging this now, thanks @courier-new @jasongornall!
