### PR TITLE
batches: fix credential migration progress

### LINKED ISSUE #22277: Batch Changes OOB migrations can appear stuck when encryption is disabled
At present, the Batch Changes credential tables use a field called `encryption_key_id` to distinguish between encrypted and unencrypted credentials. During development of the OOB migrations that underpin this functionality, unmigrated records were also distinguished by having a `credential_enc` field set to NULL.

Late in the development process, the separate `credential_enc` was removed, as I believed the state could be inferred from `encryption_key_id`. On encrypted instances, this is true. On unencrypted instances, however, this introduced an ambiguity between unencrypted and unmigrated records.

The net effect of this was that, on unencrypted Sourcegraph instances, the user and site credential migrations will always appear to be stuck at 0% progress if there are a non-zero number of records. (As a special case, if there are no records of that type, the migration will complete.) This is mostly harmless, but it does mean that the OOB migrator will be woken up every few seconds to do nothing, successfully, and it means that the migration site admin UI will always indicate that the migration is stuck, despite the lack of errors.

### PR DESCRIPTION
**Pull request by LawnGnome**
Fixes #22277. (See that issue for the write up of _what_ is being fixed; I'll describe the _how_ below.)

Basically, we need to be able to distinguish unmigrated credential records from unencrypted ones in order for our out-of-band migrations to succeed in unencrypted environments; right now they're collapsed together because we (well, OK, I) overloaded the `encryption_key_id` field shortly before merging the encryption support. This PR uses an in-band migration to set all ambiguous fields to an `unmigrated` sentinel value, and then the out-of-band migrations have been slightly adjusted to look for that instead of an empty key.

This will work fine even for users who haven't yet upgraded to 3.28 **as long as they run all migrations in order**. (It doesn't matter if the OOB migrators aren't run between the 3.28 in-band migrations and the one in this PR.) If they don't, all bets are off. But that's normal and documented anyway.

### CODE REVIEW

File: enterprise/internal/batches/background/user_credential_migrator_test.go [hunk 1]
```diff
@@ -195,7 +195,7 @@ func createUnencryptedUserCredential(
 	if err := store.Exec(
 		ctx,
 		sqlf.Sprintf(
-			"UPDATE user_credentials SET credential = %s, encryption_key_id = '' WHERE id = %s",
+			"UPDATE user_credentials SET credential = %s, encryption_key_id = 'unmigrated' WHERE id = %s",
```
Comment (courier-new) [inline enterprise/internal/batches/background/user_credential_migrator_test.go:198]: Any particular reason this time the key value is hard-coded?

**Review by courier-new — APPROVED** [review]
Looks good to me, great job uncovering this one. 🙂

File: enterprise/internal/batches/background/user_credential_migrator_test.go (hunk 1 above)
Comment (LawnGnome) [reply enterprise/internal/batches/background/user_credential_migrator_test.go:198]: Nope, brainfart on my part. I'll fix that, thanks!
