### PR TITLE
graphqlbackend: Propagate context deadline exceeded error from syncExternalService

### LINKED ISSUE #18740: GitHub code host doesn't report problems when adding invalid tokens
### Problem

When adding invalid tokens (think `bla-bla-42`) for GitHub code host, backend reports code host as successfully added.
GraphQL mutation is `AddExternalService`.
____
Based on the architecture, I'd guess this happens due to indirection and throttling @ [github-proxy](https://github.com/sourcegraph/sourcegraph/tree/main/cmd/github-proxy) and the errors will be eventually reported when code hosts starts to sync. 

### Steps to reproduce

0. Make sure your user has `allowUserExternalServicePublic` tag set
1. Navigate to code host connections page `https://sourcegraph.com/users/<your user>/settings/code-hosts`
2. Open Browser DevTools and monitor network
2. Add `bad-token` personal access token to GitHub code host connection
3. Examine `200` response from https://sourcegraph.com/.api/graphql?AddExternalService, it will have `warning` and `lastSyncError ` set as `null`
4. ⚠️   Instead we should have `warning` or `lastSyncError` have an error message. 

### Screenshots

Screen Shot 2021-03-01 at 11 33 32 AM

### PR DESCRIPTION
**Pull request by indradhanush**
Blocked by #19655 

Closes #18740.

Related to #19439 

This covers an edge case where we ignore the error returned from the context in the `syncExternalService` function.

Co-authored-by: Asdine El Hrychy <asdine.elhrychy@gmail.com>

### CODE REVIEW

**Review by arussellsaw — COMMENTED** [review]
i'm not sure we need this... the context cancellation doesn't capture an actual error. We would only want to do this if we wanted to bail out of the function to avoid doing expensive work, but here we're exiting anyway.

**Comment by indradhanush** [comment]
@arussellsaw Thank you for the review. While trying to create a PoC I found a bug in my code and I've fixed it in a fixup commit. The PoC is here: https://play.golang.org/p/hEfyjDSQn1Y and might help me to explain my thought process better (unless I did not understand your review right).

> We would only want to do this if we wanted to bail out of the function to avoid doing expensive work, but here we're exiting anyway.

With this change I am hoping that in the rare case that `repoupdater.DefaultClient.SyncExternalService` takes longer than the predefined timeout of `5 seconds`, instead of returning nil we can propagate the error out to the call stack. Would that be the better approach here?

**Comment by arussellsaw** [comment]
i think we're handling this at the wrong level here, what we're actually doing is passing a context to the http request to repo updater, and cancelling that context should close the connection & abort the request, i think what you're seeing here is behaviour that is only exhibited in mocks. 

At the point at which we're asserting ctx.Err, we've already finished the request and received a nil error, so it must have been successful. If the context was cancelled then we would have received a non-nil error from the request indicating as such.

**Comment by arussellsaw** [comment]
if our http requests aren't returning an error after context cancellation then we should be fixing that, rather than adding manual context timeout checks wherever we make requests

**Comment by indradhanush** [comment]
Heads up: I forced pushed because the original commit needed to be amended with an updated message based on the scope as discussed over our call earlier today. Also my branch was lagging a lot behind `main`.

File: cmd/frontend/graphqlbackend/external_services.go [hunk 1]
```diff
@@ -176,11 +181,11 @@ func syncExternalService(ctx context.Context, svc *types.ExternalService) error
...
 		NamespaceUserID: svc.NamespaceUserID,
 	})
-	if err != nil && ctx.Err() == nil {
-		return err
-	}
 
-	return nil
+	// err is either nil or contains an actual error from the API
+	// call. And we return it nonetheless.
+	// TODO: Maybe we want to wrap this error?
```
Comment (indradhanush) [inline cmd/frontend/graphqlbackend/external_services.go:187]: What do you feel about this? Should we wrap this error into something more meaningful? I'm not sure which way to go as this more of an internal helper function than a top level public API call. Maybe if anyone should wrap the error it should be the callers of `syncExternalService`?

File: cmd/frontend/graphqlbackend/external_services.go [hunk 2]
```diff
@@ -176,11 +181,11 @@ func syncExternalService(ctx context.Context, svc *types.ExternalService) error
...
+	return err
```
Comment (indradhanush) [inline cmd/frontend/graphqlbackend/external_services.go:188]: What do you feel about this? Should we wrap this error into something more meaningful? I'm not sure which way to go as this more of an internal helper function than a top level public API call. Maybe if anyone should wrap the error it should be the callers of `syncExternalService`?

**Comment by indradhanush** [comment]
Hmm. Test failed on buildkite. It passes locally. But 
image

File: cmd/frontend/graphqlbackend/external_services.go [hunk 3]
```diff
@@ -157,11 +157,16 @@ func (r *schemaResolver) UpdateExternalService(ctx context.Context, args *update
 	return res, nil
 }
 
+// syncExternalServiceTimeout dictates how long should the syncExternalService
+// timeout be allowed to run. This is used in tests to set the variable to a
+// much smaller number than the default 5 seconds for faster tests.
+var syncExternalServiceTimeout = 5 * time.Second
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/external_services.go:163]: If it is only for testing, call it `mockSyncExternalServiceTimeout` and default to zero value.

Then within `syncExternalService` function, we only use this mock value when it is set.

Otherwise, the variable can be easily repurposed.

Also see my comment below for an alternative.

File: cmd/frontend/graphqlbackend/external_services.go [hunk 4]
```diff
@@ -157,11 +157,16 @@ func (r *schemaResolver) UpdateExternalService(ctx context.Context, args *update
...
+
 // Eagerly trigger a repo-updater sync.
 func syncExternalService(ctx context.Context, svc *types.ExternalService) error {
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/external_services.go:166]: For a proper design, we should accept timeout as a function argument, instead of adding a package-level variable.

File: cmd/frontend/graphqlbackend/external_services.go (hunk 2 above)
Comment (unknwon) [reply cmd/frontend/graphqlbackend/external_services.go:188]: `errors.Warp(err, ...` returns `nil` if the `err` is `nil`. If this is what you were wondering?

Comment (indradhanush) [reply cmd/frontend/graphqlbackend/external_services.go:188]: Yes, precisely!

File: cmd/frontend/graphqlbackend/external_services.go [hunk 5]
```diff
@@ -150,21 +150,23 @@ func (r *schemaResolver) UpdateExternalService(ctx context.Context, args *update
...
 
-// Eagerly trigger a repo-updater sync.
-func syncExternalService(ctx context.Context, svc *types.ExternalService) error {
-	// Only give 5s to validate external service sync. Usually if there is a
-	// problem it fails sooner.
-	ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
+// syncExternalService will eagerly trigger a repo-updater sync. It accepts a
+// timeout as an argument which is recommended to be 5 seconds unless the caller
+// has special requirements for it to be larger or smaller.
+func syncExternalService(ctx context.Context, svc *types.ExternalService, timeout time.Duration, client *repoupdater.Client) error {
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/external_services.go:163]:
```go
type repoupdaterClient interface {
	SyncExternalService(ctx Context, svc ExternalService) (*ExternalServiceSyncResult, error)
}

func syncExternalService(ctx context.Context, svc *types.ExternalService, timeout time.Duration, client repoupdaterClient) error {
```

This is the "interface" I was talking about, it helps decouple the design, but just a suggestion.

**Review by unknwon — APPROVED** [review]
