### PR TITLE
Gate extensions registry (GraphQL and download APIs)

### LINKED ISSUE #39043: Remove publish script in src cli that allows you to create new extensions

### LINKED ISSUE #39044: Make sure that the “copy” command in src cli fails against a post-4.0 instance

### LINKED ISSUE #40434: Disable extension registry unless enableLegacyExtension is true or we're on dot-com
We need to keep the registry running for sourcegraph.com since all <4.0 instances will depend on it. For other instances we do not want to expose it (=the private extension registry) _unless_ `enableLegacyExtension` is true.

/cc @muratsu @jjinnii @ryankscott

### PR DESCRIPTION
**Pull request by philipp-spiess**
Fixes #40434
Fixes #39044
Fixes #39043

This is an audit of the extension registry (GraphQL and content download) APIs. Here's a list of all commands that have been audited:

- CLI:
  - `copy` (This uses the same GQL API as `publish`)
  - `list`
  - `get`
  - `delete`
- Web:
  -  Download URL e.g. `https://sourcegraph.test:3443/-/static/extension/1-sourcegraph-test-3443-philippspiess-lisp.js`
- GraphQL:
  - `query extension`
  - `query extensions`
  - `mutation createExtension`
  - `mutation updateExtension`
  - `mutation publishExtension`
  - `mutation deleteExtension`

GraphQL APIs that were not changed (these seemed relatively harmless):

- `query viewerPublishers`
- `query publishers`
- `query featuredExtensions`

The new gating that was added has a special case for dotcom which needs to be stay in read-only mode even after 4.0 and the `enableLegacyExtensions` flag is set to false.

Note: We can't make the gating dynamic yet because we're still waiting for #40085. The change after we have a fix for #40085 is trivial though, I'll create a follow-up issue for that.

## Test plan

Here's a bunch of screenshots that show that the error is properly propagated:

Screenshot 2022-08-17 at 13 10 30
Screenshot 2022-08-17 at 12 22 34
Screenshot 2022-08-17 at 12 22 05
Screenshot 2022-08-17 at 12 13 47
Screenshot 2022-08-17 at 11 45 39
Screenshot 2022-08-17 at 11 45 27
Screenshot 2022-08-17 at 13 28 25
Screenshot 2022-08-17 at 13 27 16

### CODE REVIEW

**Review by taras-yemets — APPROVED** [review]
🚀

File: cmd/frontend/registry/api/gating.go [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+}
+
+func ExtensionRegistryWriteEnabled() error {
+	// @TODO(@philipp-spiess): Enable this once we shipped a fix for #40085 and make the flag dynamic
+	// cfg := conf.Get()
+	// if cfg.ExperimentalFeatures != nil && cfg.ExperimentalFeatures.EnableLegacyExtensions == false {
+	// 	return errors.Errorf("Extensions are disabled. See https://docs.sourcegraph.com/extensions/deprecation")
+	// }
+
+	// @TODO(@philipp-spiess): Change the default when we roll out 4.0
```
Comment (philipp-spiess) [inline cmd/frontend/registry/api/gating.go:24]: cc #40460

**Review by vdavid — APPROVED** [review]
Nice!
