### PR TITLE
extensibility: add patternType to search bar action items

### LINKED ISSUE #21569: CSV export does not respect search mode
When we export search results as a CSV (using the csv export extension), we always treat the search query as literal. This causes unexpected results when customers are using other search modes (structural & regex).

### PR DESCRIPTION
**Pull request by tjkandala**
Closes #21569 (sibling PR of sourcegraph/sourcegraph-search-export#6).

Add `patternType` to search toolbar context so that extensions can read it through context key expression interpolation.

### CODE REVIEW

File: client/web/src/search/results/SearchResultsInfoBar.tsx [hunk 1]
```diff
@@ -144,7 +144,10 @@ export const SearchResultsInfoBar: React.FunctionComponent<SearchResultsInfoBarP
         )
     }, [buttonClass, props.authenticatedUser, props.onSaveQueryClick, props.showSavedQueryButton])
 
-    const extraContext = useMemo(() => ({ searchQuery: props.query || null }), [props.query])
+    const extraContext = useMemo(() => ({ searchQuery: props.query || null, patternType: props.patternType }), [
+        props.query,
+        props.patternType,
+    ])
```
Comment (limitedmage) [inline client/web/src/search/results/SearchResultsInfoBar.tsx:150]: What about other properties such as case sensitivity, search context, and version context?

**Review by limitedmage — APPROVED** [review]

File: client/web/src/search/results/SearchResultsInfoBar.tsx (hunk 1 above)
Comment (tjkandala) [reply client/web/src/search/results/SearchResultsInfoBar.tsx:150]: Thanks for the suggestion, it's definitely worth making all relevant search bar properties available to extensions. Search context and version context are part of the [`workspace` ](https://unpkg.com/sourcegraph@25.3.0/dist/docs/modules/_sourcegraph_.workspace.html) namespace since they're used for e.g. code intel as well, but there's no way for extensions to know case sensitivity. I should add it to `extraContext` for search toolbar actions
