### PR TITLE
Fix nil panic in concurrentFind

### LINKED ISSUE #5246: searcher: nil pointer panic presence
in Sourcegraph 3.6 users are [reporting nil pointer panics](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1565982055097100). The source of these appears to be here (in the 3.6 branch) in `(*readerGrep).Find`:

https://github.com/sourcegraph/sourcegraph/blob/d15fd35a0af2f052af1e4868b04c44694b87d68b/cmd/searcher/search/matcher.go#L214

In the above, `rg.re` can be `nil`, according to the docstring:

https://github.com/sourcegraph/sourcegraph/blob/d15fd35a0af2f052af1e4868b04c44694b87d68b/cmd/searcher/search/matcher.go#L65-L66

That is called by `(*readerGrep).FindZip`:

https://github.com/sourcegraph/sourcegraph/blob/d15fd35a0af2f052af1e4868b04c44694b87d68b/cmd/searcher/search/matcher.go#L278-L280

Which is called by `concurrentFind`:

https://github.com/sourcegraph/sourcegraph/blob/d15fd35a0af2f052af1e4868b04c44694b87d68b/cmd/searcher/search/matcher.go#L387-L396

Which appears to perform no checks about when `rg.re` is `nil`, except in a fast-path case:

https://github.com/sourcegraph/sourcegraph/blob/d15fd35a0af2f052af1e4868b04c44694b87d68b/cmd/searcher/search/matcher.go#L331-L333

I don't know under what circumstances we should be checking for `rg.re == nil` but it is clear we're missing one here.

### PR DESCRIPTION
**Pull request by ijt**
Fixes #5246 

This PR makes sure that if the `re` field of the `readerGrep` is `nil` in `concurrentFind` then `FindZip` will not be called, preventing the nil panic reported in the issue.

Test plan: Added a unit test that reproduces the nil panic.

### CODE REVIEW

File: cmd/searcher/search/matcher.go [hunk 1]
```diff
@@ -303,6 +303,12 @@ func appendMatches(matches []protocol.LineMatch, fileBuf []byte, matchLineBuf []
 
 // FindZip is a convenience function to run Find on f.
 func (rg *readerGrep) FindZip(zf *store.ZipFile, f *store.SrcFile) (protocol.FileMatch, error) {
+	if rg.re == nil {
+		return protocol.FileMatch{
+			Path:     f.Name,
```
Comment (slimsag) [inline cmd/searcher/search/matcher.go]: I agree that this would produce the right _result_ from a user POV, but this is not the right place to solve this. We already handle this exact case here:

https://github.com/sourcegraph/sourcegraph/blob/9874f3f29b2a61691120d59f7a0a1e42debe89b8/cmd/searcher/search/matcher.go#L357-L371

It would be odd to handle this case in two locations independently.

Comment (slimsag) [reply cmd/searcher/search/matcher.go]: See also https://github.com/sourcegraph/sourcegraph/issues/5246#issuecomment-522142355 where I pointed to this earlier & what logic change I think might work

Comment (ijt) [reply cmd/searcher/search/matcher.go]: I'm not sure I follow. `FindZip` is called here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/searcher/search/matcher.go#L415:1. Can you say a bit more about how the section you're pointing to is connected to `FindZip`?

Comment (ijt) [reply cmd/searcher/search/matcher.go]: Oh, never mind. I see what you're saying.

File: cmd/searcher/search/matcher_test.go [hunk 2]
```diff
@@ -552,3 +553,68 @@ func init() {
...
+			args: args{
+				ctx: context.Background(),
+				rg: &readerGrep{
+					// Check this case specifically.
+					re:        nil,
+					matchPath: match,
+				},
+				zf: &store.ZipFile{
+					Data: []byte("the quick brown fox"),
+					Files: []store.SrcFile{
```
Comment (slimsag) [inline cmd/searcher/search/matcher_test.go]: could also add a file that doesn't match the pattern here, for completeness sake

File: CHANGELOG.md [hunk 3]
```diff
@@ -17,6 +17,8 @@ All notable changes to Sourcegraph are documented in this file.
 
 ### Fixed
 
+- Fix some logic to prevent a nil panic. [#5246](https://github.com/sourcegraph/sourcegraph/issues/5246)
```
Comment (slimsag) [inline CHANGELOG.md]:
```suggestion
- Fixed an issue where search would sometimes crash with a panic due to a nil pointer. [#5246](https://github.com/sourcegraph/sourcegraph/issues/5246)
```

File: cmd/searcher/search/matcher_test.go (hunk 2 above)
Comment (ijt) [reply cmd/searcher/search/matcher_test.go]: The data field is a red herring, not needed. Removing it.

File: cmd/searcher/search/matcher_test.go [hunk 4]
```diff
@@ -552,3 +553,66 @@ func init() {
 	// Clear out store so we pick up changes in our store writing code.
 	os.RemoveAll(githubStore.Path)
 }
+
+func Test_concurrentFind(t *testing.T) {
```
Comment (keegancsmith) [inline cmd/searcher/search/matcher_test.go]: @ijt FYI we have a bunch of tests in `TestSearch` that would of been an easier way to add a test case.

**Comment by attfarhan** [comment]
@slimsag @ijt should this be cherry-picked onto 3.7?

**Comment by keegancsmith** [comment]
> @slimsag @ijt should this be cherry-picked onto 3.7?

yes
