### PR TITLE
API docs: LSIF: adjust definition ranges / fix incorrect references

### LINKED ISSUE #23376: API docs: some usage examples are wrong
e.g.

image

### PR DESCRIPTION
**Pull request by slimsag**
Some usage examples / references were incorrectly reporting other random symbols:

image

After investigating, the `DocumentationDefinition` request definitely produces the right location for the definition - exactly the same location that we send in a regular `graphql?References` request - which introduced the question "why are our references wrong, then?"

The only difference is that in the definition resolution code in `DocumentationReferences`, I did not previously `adjustLocations`. That seems obviously wrong, and a likely cause - so here I fix that.

I suspect it'll fix the issue, but I don't have confirmation yet.

Fixes #23376

Signed-off-by: Stephen Gutekanst <stephen@sourcegraph.com>

### CODE REVIEW

File: enterprise/cmd/frontend/internal/codeintel/resolvers/documentation_query_references.go [hunk 1]
```diff
@@ -38,47 +39,58 @@ func (r *queryResolver) DocumentationReferences(ctx context.Context, pathID stri
...
 		if err != nil {
 			return nil, "", errors.Wrap(err, "lsifStore.DocumentationDefinitions")
 		}
-		if len(locations) > 0 {
-			location := locations[0]
-			r.path = location.Path
+		if len(locations) == 0 {
+			continue
+		}
+		r.path = locations[0].Path
```
Comment (efritz) [inline enterprise/cmd/frontend/internal/codeintel/resolvers/documentation_query_references.go:52]: I may have missed this earlier: why are you updating the resolver path?

Comment (slimsag) [reply enterprise/cmd/frontend/internal/codeintel/resolvers/documentation_query_references.go:52]: `r.adjustLocations` (and `r.References` below) both depend on this context in order to do their work. That is because they are blob-level, but this is tree-level (there is no `r.path`) -- I want to clean this up soon along with the splitting up of the blob/tree resolvers. It's a bit nasty.

Comment (efritz) [reply enterprise/cmd/frontend/internal/codeintel/resolvers/documentation_query_references.go:52]: Ok, if there's a plan for the future I'm good with it :)

**Review by efritz — APPROVED** [review]

File: enterprise/cmd/frontend/internal/codeintel/resolvers/documentation_query_references.go (hunk 1 above)
Comment (slimsag) [reply enterprise/cmd/frontend/internal/codeintel/resolvers/documentation_query_references.go:52]: Yeah, I'll do this in the next 2 weeks on my workation :)
