### PR TITLE
Fix commit view resolution when using Refined GitHub

### LINKED ISSUE #3572: No codeintel on GH commit pages when using Refined GitHub (error "Cannot determine delta info")
Go to https://github.com/sourcegraph/sourcegraph/commit/932e6f4d27cdbb17e238139a431a145c35147eaf
Notice no codeintel and error in console:

```
Uncaught Error: cannot determine delta info
    at t.project (inject.bundle.js:1)
    at t._next (inject.bundle.js:1)
    at t.next (inject.bundle.js:1)
    at t._next (inject.bundle.js:1)
    at t.next (inject.bundle.js:1)
    at t._next (inject.bundle.js:1)
    at t.next (inject.bundle.js:1)
    at e._subscribe (inject.bundle.js:1)
    at e._trySubscribe (inject.bundle.js:1)
    at e.subscribe (inject.bundle.js:1)
    at e.call (inject.bundle.js:1)
    at e.subscribe (inject.bundle.js:1)
    at e.call (inject.bundle.js:1)
    at e.subscribe (inject.bundle.js:1)
    at e.call (inject.bundle.js:1)
    at e.subscribe (inject.bundle.js:1)
    at e.call (inject.bundle.js:1)
    at e.subscribe (inject.bundle.js:1)
    at e.call (inject.bundle.js:1)
    at e.subscribe (inject.bundle.js:1)
    at e.call (inject.bundle.js:1)
    at e.subscribe (inject.bundle.js:1)
    at inject.bundle.js:1
    at r (inject.bundle.js:1)
    at t._innerSub (inject.bundle.js:1)
    at t._tryNext (inject.bundle.js:1)
    at t._next (inject.bundle.js:1)
    at t.next (inject.bundle.js:1)
    at t.notifyNext (inject.bundle.js:1)
    at t._next (inject.bundle.js:1)
    at t.next (inject.bundle.js:1)
    at t.notifyNext (inject.bundle.js:1)
    at t._next (inject.bundle.js:1)
    at t.next (inject.bundle.js:1)
    at t.notifyNext (inject.bundle.js:1)
    at t._next (inject.bundle.js:1)
    at t.next (inject.bundle.js:1)
    at t.notifyNext (inject.bundle.js:1)
    at t._next (inject.bundle.js:1)
    at t.next (inject.bundle.js:1)
    at inject.bundle.js:1
    at r (inject.bundle.js:1)
    at t._innerSub (inject.bundle.js:1)
    at t._tryNext (inject.bundle.js:1)
    at t._next (inject.bundle.js:1)
    at t.next (inject.bundle.js:1)
    at e._subscribe (inject.bundle.js:1)
    at e._trySubscribe (inject.bundle.js:1)
    at e.subscribe (inject.bundle.js:1)
    at e.call (inject.bundle.js:1)
```

### PR DESCRIPTION
**Pull request by lguychard**
Fixes #3572

##### Code Hosts

- [x] GitHub
- [ ] GitHub Enterprise
- [x] Refined GitHub
- [ ] Phabricator
- [ ] Phabricator integration
- [ ] Bitbucket
- [ ] Gitlab

##### Browsers

- [x] Chrome
- [ ] Firefox

### CODE REVIEW

File: browser/src/libs/github/util.tsx [hunk 1]
```diff
@@ -95,14 +95,15 @@ export function getDiffResolvedRev(codeView: HTMLElement): DiffResolvedRevSpec |
             }
         }
     } else if (isCommit) {
-        const shaContainer = document.querySelectorAll('.sha-block')
-        if (shaContainer && shaContainer.length === 2) {
-            const baseShaEl = shaContainer[0].querySelector('a')
+        // Refined GitHub adds a `.patch-diff-links` element
+        const shaContainers = document.querySelectorAll('.sha-block:not(.patch-diff-links)')
```
Comment (felixfbecker) [inline browser/src/libs/github/util.tsx]: A `:not()` selector (basically a blacklist) seems a little brittle in case another `.sha-block` gets added or Refined GitHub changes the class name.

How about we query for `.sha-block .sha` directly? The Refined GitHub links do not contain a `.sha` element since they don't point to a SHA

Comment (lguychard) [reply browser/src/libs/github/util.tsx]: The Refined GitHub links contain two `.sha` elements.

image
