### PR TITLE
Obvious all-repos-out filters return errors

### LINKED ISSUE #39980: totalCount is missing from repositories statuses "Needs index", "Failed fetch/clone"
- **Sourcegraph version:** 3.42

#### Steps to reproduce:

1.  Invoke API 
```
query{
	repositories(first:1000, notIndexed: true, indexed:false){
		totalCount
	}
}
```
or
```
query{
	repositories(first:1000, failedFetch:false, notCloned:false){
		totalCount
	}
}
```

Response:
```
{
  "data": {
    "repositories": {
      "totalCount": null
    }
  }
}
```

#### Expected behavior:

`totalCount` has a value when looking for status "Needs index" and "Failed fetch/clone".

#### Actual behavior:

`totalCount` is `null`

#### Additional Details
- [Internal Slack discussion](https://sourcegraph.slack.com/archives/C02EDAQAJQZ/p1659556145900659)
- Customers: https://github.com/sourcegraph/accounts/issues/6716, https://github.com/sourcegraph/accounts/issues/3

/cc @jplahn @ryphil

### PR DESCRIPTION
**Pull request by cbart**
In GraphQL repo queries, filtering out all repos in form of `cloned: false, notCloned: false` or `indexed: false, notIndexed: false` results in an error as the query does not serve any use case and is probably an error.

Closes #39980 

## Test plan

Amend the small and large tests to reflect the behavior change.

👉 Prefer `errors.New` to `errors.Errorf` when no string formatting is used.

### CODE REVIEW

File: cmd/frontend/graphqlbackend/repositories.go [hunk 1]
```diff
@@ -74,15 +75,22 @@ func (args *repositoryArgs) toReposListOptions() (database.ReposListOptions, err
 
 	opt.FailedFetch = args.FailedFetch
 
+	if !args.Cloned && !args.NotCloned {
```
Comment (ryanslade) [inline cmd/frontend/graphqlbackend/repositories.go:78]: What about setting both true? That would also conflict right?

File: cmd/frontend/graphqlbackend/repositories.go [hunk 2]
```diff
@@ -74,15 +75,22 @@ func (args *repositoryArgs) toReposListOptions() (database.ReposListOptions, err
...
-	} else if !args.NotCloned {
+	}
+	if !args.NotCloned {
 		// notCloned is true by default.
 		// this condition is valid only if it has been
 		// explicitly set to false by the client.
 		opt.OnlyCloned = true
 	}
 
+	if !args.Indexed && !args.NotIndexed {
```
Comment (ryanslade) [inline cmd/frontend/graphqlbackend/repositories.go:91]: Same as other comment. If we set both to true it also doesn't make sense.

File: cmd/frontend/graphqlbackend/repositories.go (hunk 1 above)
Comment (mrnugget) [reply cmd/frontend/graphqlbackend/repositories.go:78]: No. Take a look at the `schema.graphql`:
screenshot_2022-12-06_11 30 28@2x

**Review by mrnugget — APPROVED** [review]

File: cmd/frontend/graphqlbackend/repositories.go (hunk 2 above)
Comment (cbart) [reply cmd/frontend/graphqlbackend/repositories.go:91]: Both true is the default, and it's including everything.
