### PR TITLE
in gitserver cleanup, target a percent, not a fixed amount of free space

### LINKED ISSUE #5059: gitserver deletes all repositories if the disk size is ~= SRC_REPOS_DESIRED_FREE_GB
https://github.com/sourcegraph/sourcegraph/blob/1ed7c5fbd6300aff6436478d1ebd91d02764c8e7/cmd/gitserver/main.go#L27

Gitserver periodically runs a cleanup job so that it always keeps a certain amount of disk space free (default 10GB). However, if the actual disk size is ~= `SRC_REPOS_DESIRED_FREE_GB`, then gitsever will delete _all_ of the repos on the instance as part of the cleanup process. This forces gitserver to reclone all those repos again, which results in bad/broken UX. 

One way of fixing this is to make the cleanup threshold percentage-based instead of a fixed number. 

cc @sourcegraph/core-services

### PR DESCRIPTION
**Pull request by ijt**
Fixes #5059 

Test plan: 
* refactor to use an interface for the filesystem
* add a unit test

### CODE REVIEW

**Comment by ijt** [comment]
This is still a WIP. I'm refactoring the code so I can add a unit test.

**Comment by ijt** [comment]
@ggilmore, tests have been added, PTAL.

File: cmd/gitserver/main.go [hunk 1]
```diff
@@ -24,7 +24,7 @@ import (
 var (
 	reposDir          = env.Get("SRC_REPOS_DIR", "/data/repos", "Root dir containing repos.")
 	runRepoCleanup, _ = strconv.ParseBool(env.Get("SRC_RUN_REPO_CLEANUP", "", "Periodically remove inactive repositories."))
-	wantFreeG         = env.Get("SRC_REPOS_DESIRED_FREE_GB", "10", "How many gigabytes of space to keep free on the disk with the repos")
+	wantPctFree       = env.Get("SRC_REPOS_DESIRED_PERCENT_FREE", "90", "Target percentage of free space on disk.")
```
Comment (ggilmore) [inline cmd/gitserver/main.go]: Am I reading this correctly that gitserver will try to ensure 90% of the disk space is free? If so, then 90% seems aggressive. Why not just 10%?

File: cmd/gitserver/server/cleanup.go [hunk 2]
```diff
@@ -194,44 +194,75 @@ func (s *Server) cleanupRepos() {
...
-	actualFreeBytes, err := s.bytesFreeOnDisk()
-	if err != nil {
-		log15.Error("cleanup: finding the amount of space free on disk", "error", err)
-		return
+	if s.DiskSizer == nil {
+		s.DiskSizer = &StatDiskSizer{}
 	}
-	G := float64(1024 * 1024 * 1024)
-	mount, err := findMountPoint(s.ReposDir)
+	btf, err := s.howManyBytesToFree()
```
Comment (ggilmore) [inline cmd/gitserver/server/cleanup.go]: https://github.com/sourcegraph/sourcegraph/blob/master/doc/dev/code_style_guide.md#use-pronounceable-names

nit: Why not simply `b` instead of `btf` (especially since this value is immediately used)?

File: cmd/gitserver/server/cleanup_test.go [hunk 3]
```diff
@@ -313,6 +313,69 @@ func TestRemoveRepoDirectory_Empty(t *testing.T) {
 	)
 }
 
+func Test_howManyBytesToFree(t *testing.T) {
+	const G = 1024 * 1024 * 1024
+	s := &Server{
+		DesiredPercentFree: 90,
+	}
+
+	t.Run("if there is already enough space, no space is freed", func(t *testing.T) {
```
Comment (ggilmore) [inline cmd/gitserver/server/cleanup_test.go]: I don't know if we have a convention around this, but this test's structure lends itself to https://github.com/golang/go/wiki/TableDrivenTests quite well

File: cmd/gitserver/main.go [hunk 4]
```diff
@@ -40,14 +40,14 @@ func main() {
 		log.Fatalf("failed to create SRC_REPOS_DIR: %s", err)
 	}
 
-	wantFreeG2, err := strconv.Atoi(wantFreeG)
+	wantPctFree2, err := strconv.Atoi(wantPctFree)
```
Comment (ggilmore) [inline cmd/gitserver/main.go]: Is there any validation on what wantPctFree's values are? Examples: (-4, 0, 300, ...)

File: cmd/gitserver/server/cleanup.go [hunk 5]
```diff
@@ -312,7 +339,14 @@ func (s *Server) freeUpSpace(howManyBytesToFree int64) error {
 
 	// Remove repos until howManyBytesToFree is met or exceeded.
 	var spaceFreed int64
+	mountPoint, err := findMountPoint(s.ReposDir)
+	if err != nil {
+		return errors.Wrap(err, "finding mount point")
+	}
```
Comment (ggilmore) [inline cmd/gitserver/server/cleanup.go]:
```suggestion
	}
	
```
nit: https://github.com/sourcegraph/sourcegraph/blob/master/doc/dev/code_style_guide.md#use-new-lines-intentionally

File: cmd/gitserver/server/cleanup.go [hunk 6]
```diff
@@ -312,7 +339,14 @@ func (s *Server) freeUpSpace(howManyBytesToFree int64) error {
...
 	for _, d := range gitDirs {
+		if spaceFreed >= howManyBytesToFree {
+			return nil
+		}
```
Comment (ggilmore) [inline cmd/gitserver/server/cleanup.go]:
```suggestion
		}
		
```
nit: https://github.com/sourcegraph/sourcegraph/blob/master/doc/dev/code_style_guide.md#use-new-lines-intentionally

File: cmd/gitserver/server/cleanup.go [hunk 7]
```diff
@@ -194,44 +194,75 @@ func (s *Server) cleanupRepos() {
...
+func (s *Server) howManyBytesToFree() (int64, error) {
+	// Check how much disk space is available.
+	mountPoint, err := findMountPoint(s.ReposDir)
 	if err != nil {
 		return 0, errors.Wrap(err, "finding mount point for dir containing repos")
 	}
-	if err := syscall.Statfs(mount, &fs); err != nil {
+	actualFreeBytes, err := s.DiskSizer.BytesFreeOnDisk(mountPoint)
+	if err != nil {
+		return 0, errors.Wrap(err, "cleanup: finding the amount of space free on disk")
```
Comment (ggilmore) [inline cmd/gitserver/server/cleanup.go]:
```suggestion
		return 0, errors.Wrap(err, "finding the amount of space free on disk")
```

nit: This error message is assuming that the cleanup function is this function's caller. At this point, the only thing the function knows is that it failed when it was trying to calculate the amount of free disk space - no other context.

File: cmd/gitserver/server/cleanup.go [hunk 8]
```diff
@@ -194,44 +194,75 @@ func (s *Server) cleanupRepos() {
...
+	}
+	// Free up space if necessary.
```
Comment (ggilmore) [inline cmd/gitserver/server/cleanup.go]:
```suggestion

	// Free up space if necessary.
```

nit: I made similar comments elsewhere in this PR, but I find this code to be a bit dense to read since it lacks newlines to separate logically distinct sections. 

Could you read through the advice in https://github.com/sourcegraph/sourcegraph/blob/master/doc/dev/code_style_guide.md#use-new-lines-intentionally and adapt your code accordingly? (Example: newlines after early `return` statements)

File: cmd/gitserver/server/cleanup.go [hunk 9]
```diff
@@ -194,44 +194,75 @@ func (s *Server) cleanupRepos() {
...
+	diskSizeBytes, err := s.DiskSizer.DiskSizeBytes(mountPoint)
+	if err != nil {
+		return 0, errors.Wrap(err, "getting disk size")
+	}
+	desiredFreeBytes := uint64(float64(s.DesiredPercentFree) / 100.0 * float64(diskSizeBytes))
```
Comment (ggilmore) [inline cmd/gitserver/server/cleanup.go]: What happens if diskSizeBytes is ~= 0?

File: cmd/gitserver/server/cleanup.go [hunk 10]
```diff
@@ -194,44 +194,75 @@ func (s *Server) cleanupRepos() {
...
+	}
+	return howManyBytesToFree, nil
+}
+
+type StatDiskSizer struct{}
+
+func (s *StatDiskSizer) BytesFreeOnDisk(mountPoint string) (uint64, error) {
+	var fs syscall.Statfs_t
+	if err := syscall.Statfs(mountPoint, &fs); err != nil {
 		return 0, errors.Wrap(err, "finding out how much disk space is free")
```
Comment (ggilmore) [inline cmd/gitserver/server/cleanup.go]: nit: it seems like the error message here should be consistent with the error in DiskSizeBytes (and vice-versa)

File: cmd/gitserver/server/cleanup.go [hunk 11]
```diff
@@ -332,13 +366,9 @@ func (s *Server) freeUpSpace(howManyBytesToFree int64) error {
 			"repo", d,
 			"how old", time.Since(dirModTimes[d]),
 			"free space in GiB", float64(actualFreeBytes)/G,
-			"desired free space in GiB", float64(s.DesiredFreeDiskSpace)/G,
+			"desired free space in GiB", float64(s.DesiredPercentFree)/G,
```
Comment (ggilmore) [inline cmd/gitserver/server/cleanup.go]: So, the free disk space changed from gigs to a percentage here. Is the "desired free space in GiB" log description still accurate?

File: cmd/gitserver/main.go (hunk 1 above)
Comment (ijt) [reply cmd/gitserver/main.go]: You're so right. It got inverted in my mind for some reason. Will flip it to 10%.

File: cmd/gitserver/server/cleanup.go (hunk 2 above)
Comment (ijt) [reply cmd/gitserver/server/cleanup.go]: Done.

File: cmd/gitserver/server/cleanup_test.go (hunk 3 above)
Comment (ijt) [reply cmd/gitserver/server/cleanup_test.go]: Done.

File: cmd/gitserver/main.go (hunk 4 above)
Comment (ijt) [reply cmd/gitserver/main.go]: Done.

File: cmd/gitserver/server/cleanup.go (hunk 5 above)
Comment (ijt) [reply cmd/gitserver/server/cleanup.go]: I want to keep that block of code contiguous because there is a comment above it that describes what the whole thing is doing. Adding a line break would give the idea that the comment doesn't talk about some code that it is meant to talk about.

Comment (ijt) [reply cmd/gitserver/server/cleanup.go]: I found another place where I can add a newline to make it more readable. Thanks for the suggestion.

File: cmd/gitserver/server/cleanup.go (hunk 8 above)
Comment (ijt) [reply cmd/gitserver/server/cleanup.go]: Done.

Comment (ijt) [reply cmd/gitserver/server/cleanup.go]: I'm less sure about adding newlines after early return statements. Happy to chat about it if it's affecting the readability.

File: cmd/gitserver/server/cleanup.go (hunk 9 above)
Comment (ijt) [reply cmd/gitserver/server/cleanup.go]: I think the whole system will fail then. Am I missing a real use case here?

File: cmd/gitserver/server/cleanup.go (hunk 10 above)
Comment (ijt) [reply cmd/gitserver/server/cleanup.go]: Done.

File: cmd/gitserver/server/cleanup.go (hunk 11 above)
Comment (ijt) [reply cmd/gitserver/server/cleanup.go]: Done.
