### PR TITLE
Fix GetPublicExternalAccountData panicing with empty fields

### LINKED ISSUE #55602: own: panic on Ownership page on S2
The issue was [reported](https://sourcegraph.slack.com/archives/C04EM0VMAKZ/p1691284356396739) in #job-fair-own channel.

`FetchTreeOwnership` GraphQL query returns this error:
```
{
    "errors": [
        {
            "message": "panic occurred: runtime error: invalid memory address or nil pointer dereference",
            "path": [
                "node",
                "commit",
                "tree",
                "ownership"
            ]
        }
    ],
    "data": {
        "node": {
            "commit": {
                "tree": null,
                "__typename": "GitCommit"
            },
            "__typename": "Repository"
        },
        "currentUser": {
            "permissions": {
                "nodes": [
                    {
                        "displayName": "REPO_METADATA#WRITE",
                        "__typename": "Permission"
                    },
                    {
                        "displayName": "OWNERSHIP#ASSIGN",
                        "__typename": "Permission"
                    },
                    {
                        "displayName": "BATCH_CHANGES#WRITE",
                        "__typename": "Permission"
                    },
                    {
                        "displayName": "BATCH_CHANGES#READ",
                        "__typename": "Permission"
                    }
                ],
                "__typename": "PermissionConnection"
            },
            "__typename": "User"
        }
    }
}
```

/cc @sourcegraph/source

### PR DESCRIPTION
**Pull request by pjlast**
Closes #55602 

The default sourcegraph-operator user gets created with `account_data` that does not contain `userInfo` or `userClaims`, which causes panics in Own when it tries to get the external account data for that account.

This PR removes a bunch of pointer fields so that these can default to sensible zero values, instead of nil pointers. Pointers to base types like `string` should be cause for concern anyways.

## Test plan

Added unit test for OpenIDConnect specific case that was causing production panics. Removed a lot of unnecessary pointers in other providers as well, and their tests should still pass.

### CODE REVIEW

File: cmd/frontend/graphqlbackend/external_account_data_resolver.go [hunk 1]
```diff
@@ -33,14 +33,14 @@ func publicAccountDataFromJSON(ctx context.Context, account extsvc.Account) (*ex
...
 
-func (r *externalAccountDataResolver) Login() *string {
+func (r *externalAccountDataResolver) Login() string {
 	return r.data.Login
 }
 
-func (r *externalAccountDataResolver) URL() *string {
+func (r *externalAccountDataResolver) URL() string {
 	return r.data.URL
 }
```
Comment (eseliger) [inline cmd/frontend/graphqlbackend/external_account_data_resolver.go:46]: these are typed as `String` (no `!`) in GQL, so I think we should map an empty string to `nil` in the return here, otherwise we'll get `""` now vs `null` in the response

Comment (pjlast) [reply cmd/frontend/graphqlbackend/external_account_data_resolver.go:46]: Hmm is that a problem though 🤔

Comment (eseliger) [reply cmd/frontend/graphqlbackend/external_account_data_resolver.go:46]: it can be, the typescript type indicates that the empty value will be specified as `null`, and if we don't return `null` but an empty string, we might render something that we don't expect to. In general, returning `null` is more idiomatic, too, IMO.
