### PR TITLE
Fix bitbucket server getCommandPaletteMount idempotency

### LINKED ISSUE #2977: browser ext. Bitbucket Server integration sometimes gives multiple hamburgers
Navigating between pages, the chrome extension sometimes gives multiple hamburgers on Bitbucket Server instances (version 6). Unclear yet what exact action causes this.

### PR DESCRIPTION
**Pull request by lguychard**
Fixes #2977

`bitbucketServerCodeHost.getCommandPaletteMount()` would check for a broken selector when looking for a previously injected command palette mount.

### CODE REVIEW

File: client/browser/src/libs/bitbucket/code_intelligence.tsx [hunk 1]
```diff
@@ -102,17 +102,17 @@ function getCommandPaletteMount(): HTMLElement {
...
         const commandListElem = document.createElement('li')
-        commandListElem.className = commandListClass
+        commandListElem.className = commandListClasses.join(' ')
         headerElem!.insertAdjacentElement('beforeend', commandListElem)
 
         return commandListElem
     }
 
-    return document.querySelector<HTMLElement>('.' + commandListClass) || createCommandList()
+    return document.querySelector<HTMLElement>(commandListClasses.map(c => `.${c}`).join('')) || createCommandList()
```
Comment (felixfbecker) [inline client/browser/src/libs/bitbucket/code_intelligence.tsx]: Shouldn't it be enough to only search for one of these classes, since the element will have both?
