### PR TITLE
Fix Phabricator convertToDetails()

### LINKED ISSUE #8275: Browser extension doesn't work in Phabricator
- **Sourcegraph version:** 3.12.5
- **Platform information:** Docker version

#### Steps to reproduce:

1. install and launch Docker version of Sourcegraph
2. add Phabricator-hosted git repository via the "Generic Git host" option
3. add Phabricator connection
4. install Chrome browser extension
5. browse to a Differential revision in Phabricator

#### Expected behavior:
Code intel to show up.

#### Actual behavior:
Nothing happens. An error is logged in the Chrome console "Uncaught Error: could not parse repo details"

This appears to be happening because of the check [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@7ac3ada581c2704aa3f6a06d6bbae48156a0b4db/-/blob/browser/src/libs/phabricator/backend.tsx#L365). The repository I'm trying to use is hosted on Phabricator, so the uri for the repository has the same host as the Phabricator webpage, and convertToDetails is never able to find a valid uri for this repository.

I was able to fix this locally by editing the javascript for the Chrome extension and removing the check against window.location.host.

Separately, it appears the logic in convertToDetails iterates through all returned uris, and uses the first one that doesn't match window.location.host. My set up had 2 disabled uris that had an older, deprecated location which appear first in the list or returned uris. I had to edit those to be the same as the current uri because Sourcegraph doesn't check the disabled field on the uri. Perhaps convertToDetails should check and skip disabled uris?

### PR DESCRIPTION
**Pull request by lguychard**
Fixes #8275

convertToDetails() had two issues:
- It failed to account for the fact that some repositories are hosted on the Phabricator instance, _not_ remotely.
- It didn't ignore disabled URIs.

### CODE REVIEW

File: browser/src/libs/phabricator/backend.tsx [hunk 1]
```diff
@@ -359,19 +360,18 @@ async function convertConduitRepoToRepoDetails(repo: ConduitRepo): Promise<Phabr
...
-    }
-    if (!uri) {
+    const enabledURIs = repo.attachments.uris.uris
+        // Filter out disabled URIs
+        .filter(({fields}) => !fields.uri.disabled)
+        .map(({ fields }) => ({
+            isExternalURI: !fields.uri.normalized.replace('\\', '').startsWith(window.location.host + '/'),
+            rawURI: fields.uri.raw
+        }))
+    if (!enabledURIs.length) {
```
Comment (eseliger) [inline browser/src/libs/phabricator/backend.tsx]: just a legibility thing, feel free to ignore if you don't like it

```suggestion
    if (enabledURIs.length === 0) {
```

File: browser/src/libs/phabricator/backend.tsx [hunk 2]
```diff
@@ -359,19 +360,18 @@ async function convertConduitRepoToRepoDetails(repo: ConduitRepo): Promise<Phabr
...
-        }
-        uri = u
-        break
-    }
-    if (!uri) {
+    const enabledURIs = repo.attachments.uris.uris
+        // Filter out disabled URIs
+        .filter(({fields}) => !fields.uri.disabled)
+        .map(({ fields }) => ({
+            isExternalURI: !fields.uri.normalized.replace('\\', '').startsWith(window.location.host + '/'),
```
Comment (felixfbecker) [inline browser/src/libs/phabricator/backend.tsx]: In the comment on `uri.normalized` I see no mention of backslashes. How do these occur? Did you mean to replace multiple occurences (the code doesn't do that right now), or just the first?

File: browser/src/libs/phabricator/backend.tsx [hunk 3]
```diff
@@ -359,19 +360,18 @@ async function convertConduitRepoToRepoDetails(repo: ConduitRepo): Promise<Phabr
...
+            rawURI: fields.uri.raw
+        }))
+    if (!enabledURIs.length) {
         return null
     }
-    const rawURI = uri.fields.uri.raw
+    // Use the external URI if there is one, otherwise use the first enabled URI.
+    const { rawURI } = enabledURIs.find(({ isExternalURI }) => isExternalURI) || enabledURIs[0]
```
Comment (felixfbecker) [inline browser/src/libs/phabricator/backend.tsx]:
```suggestion
    const { rawURI } = enabledURIs.find(({ isExternalURI }) => isExternalURI) ?? enabledURIs[0]
```

Comment (felixfbecker) [reply browser/src/libs/phabricator/backend.tsx]: Is `enabledURIs` guaranteed to have at least one element? (Else this would throw)

File: browser/src/libs/phabricator/file_info.test.ts [hunk 4]
```diff
@@ -195,6 +195,103 @@ describe('Phabricator file info', () => {
                 rawRepoName: 'github.com/gorilla/mux',
             })
         })
+
+        test('Diffusion - single file code view - ignores disabled URIs', async () => {
```
Comment (felixfbecker) [inline browser/src/libs/phabricator/file_info.test.ts]: The parts separated with `-` could be better structured as nested `describe()`s (I realise it was used before, but now there are multiple, so it actually makes a difference imo)

File: browser/src/libs/phabricator/backend.tsx (hunk 3 above)
Comment (eseliger) [reply browser/src/libs/phabricator/backend.tsx]: https://github.com/sourcegraph/sourcegraph/pull/8286/files/21feeef6123102b27bddc1d1f919dd13ba54cc41#diff-caf571f7be0b06ea4414281cadaa9181R370 :)

File: browser/src/libs/phabricator/backend.tsx (hunk 2 above)
Comment (lguychard) [reply browser/src/libs/phabricator/backend.tsx]: This is ported from the [existing code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@7ac3ada581c2704aa3f6a06d6bbae48156a0b4db/-/blob/browser/src/libs/phabricator/backend.tsx#L365). I have to admit that when testing this, I never saw a backslash in the `uri.normalized` field (and unfortunately the Conduit API reference doesn't document this field). It may be useless.

File: browser/src/libs/phabricator/file_info.test.ts (hunk 4 above)
Comment (lguychard) [reply browser/src/libs/phabricator/file_info.test.ts]: The tests are all nested under a `describe('resolveDiffusionFileInfo()')`, so `Diffusion - single file code view` was actually a bit redundant (since this function only works on single file code views). Gave the tests better names.
