### PR TITLE
search redesign: add monaco themes for redesign

### LINKED ISSUE #20280: Fix background color for monaco query input when redesign theme is enabled
With redesign enabled, query input has the wrong background color.

image

### PR DESCRIPTION
**Pull request by limitedmage**
Fixes #20280 where Monaco background color in dark mode was incorrect for the redesign.

This only changes the background color in dark mode to fix the bug, but also adds the infrastructure to customize Monaco colors later on.

### CODE REVIEW

**Review by rvantonder — APPROVED** [review]
https://media0.giphy.com/media/H7F0zSaC9ZHZC/200w.gif?cid=5a38a5a2xth7hfzh7nv5fq0k8bxjg82v447nrviijwpbrszd&rid=200w.gif&ct=g

File: client/web/src/components/MonacoEditor.tsx [hunk 1]
```diff
@@ -9,134 +9,164 @@ import { KeyboardShortcut } from '@sourcegraph/shared/src/keyboardShortcuts'
...
+    { token: 'metaRevisionReferencePath', foreground: '#f2f4f8' },
+    { token: 'metaRevisionWildcard', foreground: '#3bc9db' },
+    // Path-like highlighting
+    { token: 'metaPathSeparator', foreground: '#868e96' },
+]
+
+const lightColors: monaco.editor.IColors = {
+    background: '#ffffff',
+    'editor.background': '#ffffff',
+    'editor.foreground': '#2b3750',
```
Comment (umpox) [inline client/web/src/components/MonacoEditor.tsx:81]: I think there might be some more colors we should change here, e.g. this is `$gray-01` in the current design, but in the redesign `$gray-01` is set to a different value.

Can these reference CSS variables? That might be useful to map these over and keep it resilient to change

Comment (limitedmage) [reply client/web/src/components/MonacoEditor.tsx:81]: Unfortunately these cannot be CSS variables. See https://github.com/microsoft/monaco-editor/issues/2427 . Colors must be hex codes.

Comment (limitedmage) [reply client/web/src/components/MonacoEditor.tsx:81]: As mentioned in the description, there are definitely more colors we could change here, but I decided to only fix the background for now as it's a very glaring bug.
