### PR TITLE
search jobs: compute aggregate state in db

### LINKED ISSUE #56935: Jobs shouldn't be in state "FAILED" while they are still running

### LINKED ISSUE #56937: Filter by search status and Sort by Status are broken

### PR DESCRIPTION
**Pull request by stefanhengl**
Closes #56937
Closes #56935

This PR moves the logic for computing the aggregate state from the resolver to the store.

Why?

To filter and sort by the aggregate state and make use of the paging helpers, we have to return the aggregate state from db instead of computing it in the resolver. 

Note:

There is a bit of awkwardness because only `ListSearchJobs` computes the aggregate state, but not `GetSearchJob`. I don't want to set `AggState` in `GetSearchJob` because it is fairly expensive to calculate, and we call `GetSearchJob` a lot as part of the security checks, so I wanted to keep it as lean as possible. 

In the future we should have a dedicated call to the db for security checks and use `GetSearchJob` only when we create a search job. Then we can calculate the aggregate state on GetSearchJob, too, and remove the special casing in the code. 

Test plan:
- New unit test
- manual testing: I ran a couple of search jobs locally to confirm whether the aggregate state properly reflect the state of the underlying jobs.

### CODE REVIEW

**Comment by keegancsmith** [comment]
@stefanhengl

> To filter and sort by the aggregate state and make use of the paging helpers, we have to return the aggregate state from db instead of computing it in the resolver.

Should we only be doing this more expensive calculation if sorting by state?

> There is a bit of awkwardness because only `ListSearchJobs` computes the aggregate state, but not `GetSearchJob`. I don't want to set `AggState` in `GetSearchJob` because it is fairly expensive to calculate, and we call `GetSearchJob` a lot as part of the security checks, so I wanted to keep it as lean as possible.

I'm slightly worried about the implication here since ListSearchJobs could have a lot of jobs to calculate this for. Obviously in our EAP stage this is an acceptable trade off (we want stuff correct and then invest in perf if we validate).

> In the future we should have a dedicated call to the db for security checks and use `GetSearchJob` only when we create a search job. Then we can calculate the aggregate state on GetSearchJob, too, and remove the special casing in the code.

Should we not just remove the aggregate information from being part of the GetSearchJob and ListSearchJobs, it only sometimes being present feels very wrong. If we need the aggregate state you hydrate it in. This feels like a foot gun (which is acceptable if you make it obvious in code and we fix up if we find validation).

File: internal/search/exhaustive/store/exhaustive_search_jobs.go [hunk 1]
```diff
@@ -189,6 +189,52 @@ func (s *Store) GetExhaustiveSearchJob(ctx context.Context, id int64) (_ *types.
...
+			    -- transpose the table
+				max( CASE WHEN state = 'failed' THEN count END) AS failed,
+				max( CASE WHEN state = 'processing' THEN count END) AS processing,
+				max( CASE WHEN state = 'completed' THEN count END) AS completed,
+				max( CASE WHEN state = 'queued' THEN count END) AS queued,
+				max( CASE WHEN state = 'canceled' THEN count END) AS canceled,
+				max( CASE WHEN state = 'errored' THEN count END) AS errored
+			FROM (
+				-- getAggregateStateTable
+				%s) AS state_histogram) AS transposed_state_histogram
```
Comment (keegancsmith) [inline internal/search/exhaustive/store/exhaustive_search_jobs.go:235]: I trust this works. But it would be intersesting after code freeze to see if we can simplify this. Ideas:
- Use a postgres view to make this easier to wrangle / understand
- don't compute aggregate states. You only need to know if there is 1 canceled job to make the aggregate state canceled, etc.
- if we do want to keep these aggregate state counts, then use https://www.postgresql.org/docs/current/tablefunc.html to simplify. We can add this extension since it is regarded as trusted so is builtin

File: internal/search/exhaustive/types/exhaustive_search_job.go [hunk 2]
```diff
@@ -20,6 +20,11 @@ type ExhaustiveSearchJob struct {
 
 	CreatedAt time.Time
 	UpdatedAt time.Time
+
+	// The aggregate state of the job. This is only set when the job is returned
+	// from ListSearchJobs. This state is different from WorkerJob.State, because it
+	// reflects the combined state of all jobs created as part of the search job.
+	AggState JobState
```
Comment (keegancsmith) [inline internal/search/exhaustive/types/exhaustive_search_job.go:27]: should we just use a different type for the list call? Alternatively explicitly have a call to ask for it.

**Review by keegancsmith — APPROVED** [review]
This doesn't feel great, but indeed we are in a tricky space. There is likely some beautiful postgres feature (something like materialized views?) to make this less painful. But this works so lets land it :) You can now add SQL to your CV!

File: cmd/frontend/internal/search/resolvers/search_job.go [hunk 3]
```diff
@@ -53,23 +47,11 @@ func (r *searchJobResolver) Query() string {
...
-		}
-
-		return types.JobStateCompleted.ToGraphQL()
-	} else {
-		return r.Job.State.ToGraphQL()
+	// We don't set the AggState during job creation
+	if r.Job.AggState != "" {
+		return r.Job.AggState.ToGraphQL()
 	}
+	return r.Job.State.ToGraphQL()
```
[the remark this answers is not in the document]
Comment (mrnugget) [reply cmd/frontend/internal/search/resolvers/search_job.go:54]: I personally think that's fine. Lots of other fields do it too: https://sourcegraph.sourcegraph.com/search?q=context:sourcegraph+ToGraphQL%28%29&patternType=standard&sm=0&groupBy=repo

It's a nice forcing function to update that method to when changing the underlying data type.

[the remark this answers is not in the document]
Comment (mrnugget) [reply cmd/frontend/internal/search/resolvers/search_job.go:54]: Or did you mean the whole `if/else`?

File: internal/search/exhaustive/store/exhaustive_search_jobs.go (hunk 1 above)
Comment (stefanhengl) [reply internal/search/exhaustive/store/exhaustive_search_jobs.go:235]: > if we do want to keep these aggregate state counts, then use https://www.postgresql.org/docs/current/tablefunc.html to simplify. We can add this extension since it is regarded as trusted so is builtin

Does that mean we can assume all our deployment types have it or can easily enable it?

**Comment by stefanhengl** [comment]
> Should we not just remove the aggregate information from being part of the GetSearchJob and ListSearchJobs, it only sometimes being present feels very wrong. If we need the aggregate state you hydrate it in. This feels like a foot gun (which is acceptable if you make it obvious in code and we fix up if we find validation).

We always need the aggregate state, not just when we filter or order. With this PR it becomes "the" state of the search job. Hydration is an issue, because we need to be able to page over it. 

If you look in the code for uses of `GetExhaustiveSearchJob`, then there are really only 2 calls there. The majority of calls are security checks. 

I think we should migrate the security checks to a dedicated store method and let GetSearchJob return the aggregate state.

After that we should find a better way to do the aggregation.

**Comment by stefanhengl** [comment]
> I'm slightly worried about the implication here since ListSearchJobs could have a lot of jobs to calculate this for. Obviously in our EAP stage this is an acceptable trade off (we want stuff correct and then invest in perf if we validate).

I will follow up with a PR to remove the distinction between `GetSearchJob` and `ListSearchJob`.

File: internal/search/exhaustive/types/exhaustive_search_job.go (hunk 2 above)
Comment (stefanhengl) [reply internal/search/exhaustive/types/exhaustive_search_job.go:27]: Is the intention to better reflect the difference between `GetSearchJob` and `ListSearchJob`?

File: cmd/frontend/internal/search/resolvers/search_job.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (keegancsmith) [reply cmd/frontend/internal/search/resolvers/search_job.go:54]: whole if/else

File: internal/search/exhaustive/store/exhaustive_search_jobs.go (hunk 1 above)
Comment (keegancsmith) [reply internal/search/exhaustive/store/exhaustive_search_jobs.go:235]: Yup, we already do this for a few other trusted extensions https://sourcegraph.com/search?q=context:global+r:%5Egithub%5C.com/sourcegraph/sourcegraph%24+content:%22CREATE+EXTENSION+IF+NOT+EXISTS%22+lang:sql&patternType=standard&sm=0&groupBy=path

File: internal/search/exhaustive/types/exhaustive_search_job.go (hunk 2 above)
Comment (keegancsmith) [reply internal/search/exhaustive/types/exhaustive_search_job.go:27]: yeah to encode in the types this gotcha.
