### PR TITLE
ssbc: Build changeset specs server side from cache entries

### LINKED ISSUE #26142: SSBC-EM2.3: Creating 1,000 changesets is practical
#### Outcome

- we can confidently run batch changes with 1,000 changesets in SSBC
- iterating over large batch changes is at least as efficient as in the CLI

We want to test/validate:

**✅ Batch spec with 500 changesets is practical**:

We want to run multiple batch specs that involve 500 or more workspaces. It should be possible to feasibly get them into a state where they become applicable.

**✅ Batch spec with 1000 changesets is practical**

We want to run multiple batch specs that involve 1000 or more workspaces. It should be possible to feasibly get them into a state where they become applicable. The API and UI should still be responsive at that scale.

**✅ Batch spec with 5000 changesets works (executed at least once)**

We want to run a batch spec that involves 5000 or more workspaces. It should not crash and with a little handholding be possible to get it into an applicable state. This is the last item in this milestone and will be done once everything in here is ticked off. If it doesn't work _at all_, we will create follow-up items that we'll eventually address, at latest in EM3.2.

#### Scope

- [x] Bug bash day @mrnugget @eseliger
- [x] Fix bugs/problems that were discovered while testing **(no estimate)**
- [x] Implement `retryBatchSpecWorkspaceExecution` mutation: https://github.com/sourcegraph/sourcegraph/pull/26937 (without that a 5000 changeset batch change is nearly impossible if you run into network problems) - **`1d`**
- [x] Implement really good server-side caching (**`~21d`**)
   - [x] https://github.com/sourcegraph/sourcegraph/issues/26929 (**`~11d`**) (_Thorsten: `6d`, Erik: `4d`_)
   - [x] https://github.com/sourcegraph/sourcegraph/issues/26932 (**`~5d`**)
   - [x] https://github.com/sourcegraph/sourcegraph/issues/26933 (**`~0.5d`** remaining)
   - [x] **Bonus stretch goal, extra points**: `src batch exec` doesn't upload changeset specs anymore and server uses cache entries to build changeset spec (**`~1.5d`**)
      - [x] src-cli: disable building and uploading changeset specs in `src batch exec` **`0.5d`**
      - [x] In `MarkComplete`: find cache entry for result, check if `result.Diff != ""`, pass into `createChangesetSpecs`, persist resulting `changesetSpecs` **`1d`**
- [x] MVP "Create" (Editor) page (**`~5d`**)
  - [x] #24942 @courier-new 
  - [x] Get YAML JSONSchema support to work in monaco (for validation and hover tips) @eseliger 
  - [x] Better 3-column layout #26768 @courier-new
  - [x] Editor resizes to remaining window height @courier-new **`0.5d`**
  - [x] Minimal examples/references left menu pane @courier-new **`0.5d`**
  - [x] Prefill editor with "Hello World" example template @courier-new **`<0.5d`**
  - [x] Hide "Create" button from user batch changes page if you are not that user @courier-new **`0.5d`** 
  - [x] Fix up workspaces preview scrollbar @courier-new **`0.5d`**
  - [x] Make workspaces preview look better (more details, visuals, making the `allowUnsupported` look clean) @courier-new **`1d`**
  - [x] Manually trigger workspaces preview (as opposed to auto-saving) [Figma](https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/SSBC?node-id=1175%3A41849) @courier-new **`2d`**
- [x] MVP "Execution" page (**`~4d`**)
  - [x] Fix up workspaces list scrollbar @eseliger
  - [x] Better 2-column layout **`1d` timebox**
  - [x] Make workspaces list look better **`1d` timebox**
  - [x] If only whitespace was produced, display "This step did not produce output" **`0.5d`**
  - [x] If the command exits with status 0 and only whitespace are produced, display "Command exited with status 0" **`0.5d`**
  - [x] Clean up code (less fetching, etc.) **`1d`**

### PR DESCRIPTION
**Pull request by eseliger**
Requires https://github.com/sourcegraph/src-cli/pull/661

This PR closes the bonus goal in EM2.3 to move changeset spec generation into the backend.

After this change, src-cli doesn't need to build the changeset specs anymore and also doesn't need to create them via the API. We will just extract the cache entries from the logs and build the changeset specs based on those, which is 100% equivalent and, besides repo archive fetching, removes the need of src in executors to talk to the API at all. 

Closes #26142

### CODE REVIEW

File: enterprise/cmd/executor/internal/apiclient/baseclient.go [hunk 1]
```diff
@@ -80,7 +80,7 @@ func (c *BaseClient) Do(ctx context.Context, req *http.Request) (hasContent bool
 		if content, err := io.ReadAll(resp.Body); err != nil {
 			log15.Error("Failed to read response body", "error", err)
 		} else {
-			log15.Error("apiclient got unexpected status code", "code", resp.StatusCode, "body", content)
+			log15.Error("apiclient got unexpected status code", "code", resp.StatusCode, "body", string(content))
```
Comment (eseliger) [inline enterprise/cmd/executor/internal/apiclient/baseclient.go:83]: Printed byte slice before.

File: lib/batches/workspaces_execution_input.go [hunk 2]
```diff
@@ -1,8 +1,8 @@
 package batches
 
 type WorkspacesExecutionInput struct {
-	RawSpec   string    `json:"rawSpec"`
-	Workspace Workspace `json:"workspace"`
+	Spec      *BatchSpec `json:"spec"`
+	Workspace Workspace  `json:"workspace"`
```
Comment (eseliger) [inline lib/batches/workspaces_execution_input.go:5]: Saves double marshal/unmarshal

File: enterprise/internal/batches/store/worker_workspace_execution.go [hunk 3]
```diff
@@ -0,0 +1,404 @@
+package store
```
Comment (eseliger) [inline enterprise/internal/batches/store/worker_workspace_execution.go:1]: Moved worker stores into the store package from background to prevent a circular import.

File: enterprise/internal/batches/background/cache_entry_cleaner.go [hunk 4]
```diff
@@ -2,19 +2,18 @@ package background
...
-	"strconv"
 	"time"
 
 	"github.com/sourcegraph/sourcegraph/enterprise/internal/batches/store"
 	"github.com/sourcegraph/sourcegraph/internal/env"
 	"github.com/sourcegraph/sourcegraph/internal/goroutine"
 )
 
-var maxCacheEntriesSize, _ = strconv.Atoi(env.Get(
+var maxCacheEntriesSize = env.MustGetInt(
```
Comment (eseliger) [inline enterprise/internal/batches/background/cache_entry_cleaner.go:12]: Found this to be safer

File: lib/batches/changeset_specs.go [hunk 5]
```diff
@@ -16,23 +16,20 @@ import (
 
 var errOptionalPublishedUnsupported = NewValidationError(errors.New(`This Sourcegraph version requires the "published" field to be specified in the batch spec; upgrade to version 3.30.0 or later to be able to omit the published field and control publication from the UI.`))
 
-type ChangesetSpecRepository struct {
+// Repository is a repository in which the steps of a batch spec are executed.
+//
+// It is part of the cache.ExecutionKey, so changes to the names of fields here
+// will lead to cache busts.
+type Repository struct {
```
Comment (eseliger) [inline lib/batches/changeset_specs.go:23]: 1 repo type less!

File: lib/batches/execution/results.go [hunk 6]
```diff
@@ -54,11 +54,11 @@ type AfterStepResult struct {
 	// StepIndex is the index of the step in the list of steps.
 	StepIndex int `json:"stepIndex"`
 	// Diff is the cumulative `git diff` after executing the Step.
-	Diff []byte `json:"diff"`
```
Comment (eseliger) [inline lib/batches/execution/results.go:57]: On the fence about this one. It breaks old cache results but is inconsistent.

File: lib/batches/execution/results.go [hunk 7]
```diff
@@ -76,5 +76,5 @@ type Result struct {
 	// Path relative to the repository's root directory in which the steps
 	// have been executed.
 	// No leading slashes. Root directory is blank string.
-	Path string
+	Path string `json:"path"`
```
Comment (eseliger) [inline lib/batches/execution/results.go:79]: same here

File: lib/batches/workspaces_execution_input.go (hunk 2 above)
Comment (mrnugget) [reply lib/batches/workspaces_execution_input.go:5]: Nice

File: lib/batches/execution/results.go (hunk 6 above)
Comment (mrnugget) [reply lib/batches/execution/results.go:57]: As we said on Slack: I think it's fine to break the cache with an update like this. It should be pretty rare that someone runs a batch spec, then upgrades Sourcegraph (or src-cli), and retries it _without the base branch of the repository having been updated_.

File: lib/batches/execution/cache/cache.go [hunk 8]
```diff
@@ -169,3 +170,36 @@ func marshalAndHashStepsCacheKey(key StepsCacheKey, globalEnv []string) (string,
 	}
 	return fmt.Sprintf("%s-step-%d", hash, key.StepIndex), err
 }
+
+func KeyForWorkspace(batchChangeAttributes *template.BatchChangeAttributes, r batches.Repository, path string, onlyFetchWorkspace bool, steps []batches.Step) ExecutionKey {
```
Comment (mrnugget) [inline lib/batches/execution/cache/cache.go:174]: I know I wrote something similar in a previous PR, so forgive me if I'm missing something, but can we change the signature of this function to take in a batch spec, a repo and a workspace? That way we don't have to set all of these fields on the caller-side whenever we create a cache key and knowledge is a bit more localised.

File: lib/batches/changeset_specs.go [hunk 9]
```diff
@@ -16,23 +16,20 @@ import (
...
 type ChangesetSpecInput struct {
-	// BaseRepositoryID is the GraphQL ID of the base repository.
-	BaseRepositoryID string
-	// HeadRepositoryID is the GraphQL ID of the head repository. Until we
-	// support forks it always needs to be the same as BaseRepositoryID.
-	HeadRepositoryID string
-
-	// Repository contains information about the repository in which the changes were made.
-	Repository ChangesetSpecRepository
+	Repository Repository
```
Comment (mrnugget) [inline lib/batches/changeset_specs.go:32]: Good stuff 👍

File: enterprise/internal/batches/store/worker_workspace_execution_test.go [hunk 10]
```diff
@@ -75,16 +58,14 @@ func TestBatchSpecWorkspaceExecutionWorkerStore_MarkComplete(t *testing.T) {
...
...ep-4","value":{"stepIndex":4,"diff":"ZGlmZiAtLWdpdCBSRUFETUUubWQgUkVBRE1FLm1kCmluZGV4IDE5MTQ0OTEuLmQ2NzgyZDMgMTAwNjQ0Ci0tLSBSRUFETUUubWQKKysrIFJFQURNRS5tZApAQCAtMyw0ICszLDcgQEAgVGhpcyByZXBvc2l0b3J5IGlzIHVzZWQgdG8gdGVzdCBvcGVuaW5nIGFuZCBjbG9zaW5nIHB1bGwgcmVxdWVzdCB3aXRoIEF1dG9tYXRpb24KIAogKGMpIENvcHlyaWdodCBTb3VyY2VncmFwaCAyMDEzLTIwMjAuCiAoYykgQ29weXJpZ2h0IFNvdXJjZWdyYXBoIDIwMTMtMjAyMC4KLShjKSBDb3B5cmlnaHQgU291cmNlZ3JhcGggMjAxMy0yMDIwLgpcIE5vIG5ld2xpbmUgYXQgZW5kIG9mIGZpbGUKKyhjKSBDb3B5cmlnaHQgU291cmNlZ3JhcGggMjAxMy0yMDIwLnRoaXMgaXMgc3RlcCAyCit0aGlzIGlzIHN0ZXAgMwordGhpcyBpcyBzdGVwIDQKK3ByZXZpb3VzX3N0ZXAubW9kaWZpZWRfZmlsZXM9W1JFQURNRS5tZF0KZGlmZiAtLWdpdCBSRUFETUUudHh0IFJFQURNRS50eHQKbmV3IGZpbGUgbW9kZSAxMDA2NDQKaW5kZXggMDAwMDAwMC4uODg4ZTFlYwotLS0gL2Rldi9udWxsCisrKyBSRUFETUUudHh0CkBAIC0wLDAgKzEgQEAKK3RoaXMgaXMgc3RlcCAxCmRpZmYgLS1naXQgbXktb3V0cHV0LnR4dCBteS1vdXRwdXQudHh0Cm5ldyBmaWxlIG1vZGUgMTAwNjQ0CmluZGV4IDAwMDAwMDAuLjI1N2FlOGUKLS0tIC9kZXYvbnVsbAorKysgbXktb3V0cHV0LnR4dApAQCAtMCwwICsxIEBACit0aGlzIGlzIHN0ZXAgNQo=","outputs":{"myOutput":"my-output.txt"},"previousStepResult":{"Files":{"modified":["README.md"],"added":["README.txt"],"deleted":null,"renamed":null},"Stdout":{},"Stderr":{}}}}}`
```
Comment (mrnugget) [inline enterprise/internal/batches/store/worker_workspace_execution_test.go:68]: Pretty cool to see that this test still works without a lot of changes.

File: enterprise/internal/batches/store/worker_workspace_execution.go [hunk 11]
```diff
@@ -0,0 +1,406 @@
...
+	events, err := logEventsFromLogEntries(job.ExecutionLogs)
+	if err != nil {
+		return false, err
+	}
+
+	executionResults, stepResults, err := extractCacheEntries(ctx, events)
+	if err != nil {
+		// Rollback transaction but ignore rollback errors
+		tx.Done(err)
+		return s.Store.MarkFailed(ctx, id, fmt.Sprintf("failed to extract cache entries: %s", err), options)
```
Comment (mrnugget) [inline enterprise/internal/batches/store/worker_workspace_execution.go:215]: Should we put these two lines in a little closure?

```go
rollbackAndMarkFailed := func(err error, fmtStr string, args ...interface{}) (bool, error) {		
	tx.Done(err)
	return s.Store.MarkFailed(ctx, id, fmt.Sprintf(fmtStr, args...), options)
}
```

and then from here you can do this in all the `if err != nil` 

```go
if err != nil {
	return rollbackAndMarkFailed(err, "failed to extract cache entries: %s", err)
}

File: enterprise/internal/batches/store/worker_workspace_execution.go (hunk 3 above)
Comment (mrnugget) [reply enterprise/internal/batches/store/worker_workspace_execution.go:1]: Idea (non-blocking): would it make sense to have a `workers` package in `batches`? I always have a hard time finding the workers...

File: enterprise/internal/batches/store/batch_spec_execution_cache_entry.go [hunk 12]
```diff
@@ -175,8 +181,20 @@ candidates AS (
   ) t
   WHERE
     ((SELECT total FROM total_size) - t.running_size) >= %s
+),
+outdated AS (
+	SELECT
+		id
+	FROM batch_spec_execution_cache_entries
+	WHERE
+		version < %s
```
Comment (mrnugget) [inline enterprise/internal/batches/store/batch_spec_execution_cache_entry.go:190]: Nice. I was about to comment that we should do this.

**Review by mrnugget — APPROVED** [review]
Good stuff!! :) Pleasantly surprised by how little code it actually is when you ignore the moved code.
