### PR TITLE
Fix SavedQueryForm bug (sourcegraph#3628)

### LINKED ISSUE #3628: Search: Save this search query
- **Sourcegraph version:** Sourcegraph.com

- **Platform information:** Debian GNU/Linux 8 x86_64, with any of the following web browsers: Firefox 66.0.3, Google Chrome 74.0.3729.108, Opera 60.0.3255.59

#### Steps to reproduce:

1. Log into [sourcegraph.com](https://sourcegraph.com) and do this search:

https://sourcegraph.com/search?q=repo:github.com/Yaoir+time%5C.NewTicker+lang:go+case:yes+

2. Click on the `Save this search query` link (on right, near top). The `Add a new search` dialog opens.

3. Type something into the `Description of this search` field.

4. When I do this, I see only one radio button under `Save location`, with a label that looks like this:

_my_username_ `(user settings)`

**Do not click on it.**

5. Click on the `Create` button.

#### Expected behavior:

The dialog closes and a search query is added.

#### Actual behavior:

The `Create` button changes to a lighter shade of blue and nothing more happens. The dialog remains. It can be closed by clicking on the `X` button in the upper right, but no new search query is added.

### PR DESCRIPTION
**Pull request by carloslfu**
Fixed bug when submitting SavedQueryForm without selecting the location. Fixes #3628.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Hi @carloslfu, thanks for the PR. Could you describe what the issue was?

**Comment by carloslfu** [comment]
Hi @felixfbecker, the issue was that [here](https://github.com/sourcegraph/sourcegraph/blob/master/web/src/search/saved-queries/SavedQueryForm.tsx#L178) the `subjectOptions` are filtered, so the radio buttons can be only of types `Org` or `User`, but the default checked radio button is set [here](https://github.com/sourcegraph/sourcegraph/blob/master/web/src/search/saved-queries/SavedQueryForm.tsx#L80) and isn't filtered, so the default checked radio button is set to a `subject` of type "Site", and no radio button is checked by default, and then the form is sent to the GraphQL API with that id that throws a "viewer is not allowed to edit these settings" error.

File: web/src/search/saved-queries/SavedQueryForm.tsx [hunk 1]
```diff
@@ -77,7 +77,11 @@ export class SavedQueryForm extends React.Component<Props, State> {
                     filter(isSettingsValid)
                 )
                 .subscribe(settingsCascade => {
-                    const subject = settingsCascade.subjects.find(s => !!s.subject.id)
+                    const subject = settingsCascade.subjects.find(
+                        s =>
+                          !!s.subject.id &&
+                          (s.subject.__typename === "Org" || s.subject.__typename === "User")
```
Comment (attfarhan) [inline web/src/search/saved-queries/SavedQueryForm.tsx]:
```suggestion
                          s.subject.viewerCanAdminister
```

This should be changed to check whether the current user is able to edit the subject by checking the `viewerCanAdminister` property of the subject.  Users that are site admins are actually able to create global saved queries by not selecting any save location, so we don't want to filter for only Org and User settings (This is bad UI that is changing soon).

Comment (carloslfu) [reply web/src/search/saved-queries/SavedQueryForm.tsx]: I get it! Thanks, @attfarhan.

File: CHANGELOG.md [hunk 2]
```diff
@@ -19,6 +19,8 @@ All notable changes to Sourcegraph are documented in this file.
 
 ### Fixed
 
+- Fixed bug when submitting SavedQueryForm without selecting the location. (#3628)
```
Comment (attfarhan) [inline CHANGELOG.md]:
```suggestion
- Fixed a bug where submitting a saved query without selecting the location would fail for non-site admins (#3628).
```

Comment (attfarhan) [reply CHANGELOG.md]: @carloslfu could you commit this update ^, then should be good to merge
