### PR TITLE
Fix unicode lowercasing bug in search highlighting

### LINKED ISSUE #4791: highlightMatches calls ToLower, may be a bug
See https://github.com/sourcegraph/sourcegraph/pull/4680#discussion_r299811837.

### PR DESCRIPTION
**Pull request by ijt**
Fixes #4791 

Test plan: Added a unit test case.

### CODE REVIEW

File: cmd/frontend/graphqlbackend/search_commits.go [hunk 1]
```diff
@@ -422,7 +422,7 @@ func highlightMatches(pattern *regexp.Regexp, data []byte) *highlightedString {
 	const maxMatchesPerLine = 25 // arbitrary
 
 	var highlights []*highlightedRange
-	for i, line := range bytes.Split(bytes.ToLower(data), []byte("\n")) {
+	for i, line := range bytes.Split(data, []byte("\n")) {
```
Comment (keegancsmith) [inline cmd/frontend/graphqlbackend/search_commits.go]: Nice. I think I commented on another about this ToLower likely being an issue? :)

Comment (ijt) [reply cmd/frontend/graphqlbackend/search_commits.go]: Yep, that's how it started.
