### PR TITLE
search frontend: update Monaco colors

### LINKED ISSUE #21981: Incorrect hover color in light mode
image

If there is not already a semantic color created for this, the hover color should be color-bg-3 for compatibility in both light and dark mode:

image

If there is a semantic color created and the values for light and dark mode do not have to be paired, then we should choose color-bg-2 for the light mode color.

### PR DESCRIPTION
**Pull request by limitedmage**
- Fix incorrect hover color in light mode (fixes #21981)
- Remove redesign themes and merge new redesign colors into the default theme (part of #20847)
- Added comments with the CSS variable names for all the colors. Some colors without a corresponding CSS variable have been modified to match a close-enough color. Some colors have been modified to match a more fitting semantic color (eg. borders updated to use `--border-color`)

## Light mode

image
image

## Dark mode

image
image

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
Nice 💥 

I wonder if we could use some magic to get the computed value of these colors in hex, instead of replicating the hex codes here. But not important for this PR.

**Review by rrhyne — APPROVED** [review]
Awesome, thanks!

**Review by novoselrok — APPROVED** [review]

File: client/web/src/components/MonacoEditor.tsx [hunk 1]
```diff
@@ -280,7 +201,7 @@ export class MonacoEditor extends React.PureComponent<Props, State> {
         const editor = monaco.editor.create(element, {
             value: this.props.value,
             language: this.props.language,
-            theme: this.getTheme(this.props.isLightTheme, this.props.isRedesignEnabled),
+            theme: this.getTheme(this.props.isLightTheme),
```
Comment (felixfbecker) [inline client/web/src/components/MonacoEditor.tsx:204]: **suggestion**: could we reuse the CSS variables and prevent them going out of sync in the future again by querying them from JS? E.g. the theme object could be wrapped in a factory  function that takes an HTMLElement, and uses `getComputedStyle(element).getPropertyValue('--border-color')` to reference colors (the style can be stored in a variable for less verbosity). The element passed can be the `element` here (or could even be `document.documentElement` since we set all variables on the root, but `element` seems cleaner).

Comment (limitedmage) [reply client/web/src/components/MonacoEditor.tsx:204]: I really like this idea. This is more work because it’s not as straight forward as calling `getComputedStyle` since we’ll essentially have to swap themes on page load to get the value of variables in both dark and light mode to create the themes. Or define a single Monaco theme and update it when `isLightTheme` changes.

I’ll leave this for future work: https://github.com/sourcegraph/sourcegraph/issues/22016

Comment (felixfbecker) [reply client/web/src/components/MonacoEditor.tsx:204]: Yeah I was thinking of a single theme

Comment (eseliger) [reply client/web/src/components/MonacoEditor.tsx:204]: Can't you do something like `document.createElement` and give it `className="theme-light"`, read all variables for light and then do the same with `theme-dark`?

Comment (felixfbecker) [reply client/web/src/components/MonacoEditor.tsx:204]: oooohh that's an interesting idea!
