### PR TITLE
web: add more error boundaries for repo pages

### LINKED ISSUE #19280: Codecov Icicle insight causes `Cannot read property 'map' of undefined` page error
When enabling `codecov.insight.icicle` and looking at https://sourcegraph.com/github.com/sourcegraph/sourcegraph, the CodeCov API returns a 500 (not our fault), which results in the `ViewContent` component to fail with `TypeError: Cannot read property 'map' of undefined` (unusual because usually this stuff should be type safe).

Given this seems new and we've just seen a similar error, I'd guess this is another regression from the RFC155 refactor @tjkandala.
Do you know a solution to make this type-safe?

image

image

It would also be good if we had an ErrorBoundary around the content side so the file tree still gets rendered.

### PR DESCRIPTION
**Pull request by tjkandala**
(and code insights)

Prevent errors in directory viewers or code editors from making the repo header or file tree inaccessible.

Also modify `<ErrorBoundary>` to allow us to use it more granularly (with classnames to reduce padding) and add extra context to help with debugging. 

Fix #19280. I'm not sure which conditions led to an invalid view making it to `<ViewContent>`. I tried to reproduce by throwing an error in the Codecov extension, but `<ViewContent>` recognized the view as `ErrorLike`. This PR should hopefully prevent breaking repo pages for individual insight errors and provide us with the info necessary to debug extension insight errors.

#### Insight error

Screenshot from 2021-03-18 18-41-55

#### Directory viewer error

Screenshot from 2021-03-18 18-00-20

### CODE REVIEW

File: client/web/src/repo/tree/ViewGrid.tsx [hunk 1]
```diff
@@ -82,25 +83,36 @@ export const ViewGrid: React.FunctionComponent<ViewGridProps> = props => {
...
-                                <ViewContent
-                                    {...props}
-                                    settingsCascade={props.settingsCascade}
-                                    viewContent={view.content}
-                                    viewID={id}
-                                    containerClassName="view-grid__item"
-                                />
-                            </>
-                        )}
+                        <ErrorBoundary
```
Comment (felixfbecker) [inline client/web/src/repo/tree/ViewGrid.tsx:86]: **thought**: I think using the "hero page" as an error boundary in this context is not fitting design-wise. Ideally we would refactor `ErrorBoundary` to accept an arbitrary fallback content/render function/component so that it could render a simple `<ErrorAlert />` too like below.

File: client/web/src/repo/routes.tsx [hunk 2]
```diff
@@ -154,20 +155,22 @@ export const repoRevisionContainerRoutes: readonly RepoRevisionContainerRoute[]
...
-                                    repoName={repo.name}
-                                    mode={mode}
-                                    repoHeaderContributionsLifecycleProps={
-                                        context.repoHeaderContributionsLifecycleProps
-                                    }
-                                />
-                            ) : (
-                                <TreePage {...context} {...repoRevisionProps} repo={repo} />
-                            )}
+                            <ErrorBoundary location={context.location}>
```
Comment (felixfbecker) [inline client/web/src/repo/routes.tsx:158]: 👍🏻

**Review by felixfbecker — APPROVED** [review]

File: client/web/src/repo/tree/ViewGrid.tsx (hunk 1 above)
Comment (tjkandala) [reply client/web/src/repo/tree/ViewGrid.tsx:86]: Good thought, I opened #19302 so we can address this later
