### PR TITLE
search home: don't break if recent searches has invalid log entries

### LINKED ISSUE #22740: Error: Cannot read property '0' of undefined
- **Sourcegraph version:** 3.29.0
- **Platform information:** N/A

#### Steps to reproduce:

We don't know exactly how to reproduce the problem. A small subset of our users encounter this when they:
1. Go to https://sourcegraph.example.com
2. Get redirected to https://sourcegraph.example.com/search
2. Get unlucky.

#### Expected behavior:
The user should see the home page with a search box.

#### Actual behavior:
The user sees the following React error:
```
Cannot read property '0' of undefined
```

Here is a screenshot:
image-2021-07-09-08-26-21-161

And here is the stack trace from the Developer Console on Chrome:
```
TypeError: Cannot read property '0' of undefined
    at scanner.ts:72
    at T (scanner.ts:494)
    at SyntaxHighlightedSearchQuery.tsx:8
    at Object.useMemo (react-dom.production.min.js:165)
    at t.useMemo (react.production.min.js:25)
    at a (SyntaxHighlightedSearchQuery.tsx:7)
    at Qo (react-dom.production.min.js:153)
    at ws (react-dom.production.min.js:261)
    at bc (react-dom.production.min.js:246)
    at hc (react-dom.production.min.js:246)
rs @ react-dom.production.min.js:209
n.payload @ react-dom.production.min.js:227
ho @ react-dom.production.min.js:129
Ua @ react-dom.production.min.js:179
ws @ react-dom.production.min.js:263
bc @ react-dom.production.min.js:246
hc @ react-dom.production.min.js:246
ac @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
$i @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
_c @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
$i @ react-dom.production.min.js:122
Ec @ react-dom.production.min.js:257
R @ react-dom.production.min.js:287
Jt @ react-dom.production.min.js:68
selectionchange (async)
setSelectionRange @ textAreaInput.js:599
writeToTextArea @ textAreaState.js:32
_setAndWriteTextAreaState @ textAreaInput.js:433
writeScreenReaderContent @ textAreaInput.js:441
_setHasFocus @ textAreaInput.js:420
focusTextArea @ textAreaInput.js:387
focusTextArea @ textAreaHandler.js:383
focus @ viewImpl.js:355
focus @ codeEditorWidget.js:897
(anonymous) @ MonacoQueryInput.tsx:284
ss @ react-dom.production.min.js:211
_c @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
$i @ react-dom.production.min.js:122
Ec @ react-dom.production.min.js:257
(anonymous) @ react-dom.production.min.js:256
F @ scheduler.production.min.js:17
_.port1.onmessage @ scheduler.production.min.js:14
```

#### Workaround
Users can workaround this problem by providing a non-empty query, _e.g._ https://sourcegraph.example.com/search?q=foo. We think this is a bug in the syntax highlighter for the input field.

### PR DESCRIPTION
**Pull request by limitedmage**
Fixes #22740

If the event logs don't contain a valid query for a recent search, skip it.

### CODE REVIEW

File: client/web/src/search/panels/RecentSearchesPanel.tsx [hunk 1]
```diff
@@ -192,16 +192,18 @@ function processRecentSearches(eventLogResult?: EventLogResult): RecentSearch[]
...
-                recentSearches[recentSearches.length - 1].count += 1
-            } else {
-                const parsedUrl = new URL(node.url)
-                recentSearches.push({
-                    count: 1,
-                    url: parsedUrl.pathname + parsedUrl.search, // Strip domain from URL so clicking on it doesn't reload page
-                    searchText,
-                    timestamp: node.timestamp,
-                })
+            if (searchText) {
```
Comment (rvantonder) [inline client/web/src/search/panels/RecentSearchesPanel.tsx:195]: Question, looking at the previous line:

> const searchText: string = parsedArguments?.code_search?.query_data?.combined

`searchText` is annotated as `string`, but this check implies it can be `undefined` right? Is the right thing to do to update the annotation here?

**Review by rvantonder — APPROVED** [review]
Changelog entry?

File: client/web/src/search/panels/RecentSearchesPanel.tsx (hunk 1 above)
Comment (limitedmage) [reply client/web/src/search/panels/RecentSearchesPanel.tsx:195]: Good point, updated to `string | undefined`
