### PR TITLE
search: fix nil deref panic

### LINKED ISSUE #3579: search panic: runtime error: invalid memory address or nil pointer dereference
Reported by https://app.hubspot.com/contacts/2762526/company/561806411 

```go
22:53:26           frontend | panic: runtime error: invalid memory address or nil pointer dereference
22:53:26           frontend | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xf8008d]
22:53:26           frontend | goroutine 2353373 [running]:
22:53:26           frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.zoektSearchHEAD(0x2116900, 0xc005de1b00, 0xc00099dda0, 0xc00f5f5800, 0x7a7, 0x900, 0x4e2c00, 0x2116bc0, 0xc0022be740, 0x0, ...)
22:53:26           frontend |     /buildkite/builds/buildkite-agent-59b9b57b47-w4jzx-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/textsearch.go:471 +0x63d
22:53:26           frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.searchFilesInRepos.func4(0xc00f32a894, 0xc005de1920, 0xc00f5f5800, 0x7a7, 0x900, 0xc00b16f110, 0xc00f32a8a0, 0xc00948f300, 0xc005de1a10, 0xc00b16f120, ...)
22:53:26           frontend |     /buildkite/builds/buildkite-agent-59b9b57b47-w4jzx-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/textsearch.go:857 +0x2a7
22:53:26           frontend | created by github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.searchFilesInRepos
22:53:26           frontend |     /buildkite/builds/buildkite-agent-59b9b57b47-w4jzx-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/textsearch.go:851 +0x960
22:53:26            symbols | received error during background config update, err: unable to fetch new configuration: Post http://127.0.0.1:3090/.internal/configuration: EOF
22:53:26           frontend | Terminating frontend
frontend died. Shutting down...
22:53:26              nginx | Terminating nginx
```

### PR DESCRIPTION
**Pull request by ijt**
Fixes #3579.
May help with #3594.

Test plan: A regression test has been added.

### CODE REVIEW

File: cmd/frontend/graphqlbackend/textsearch_test.go [hunk 1]
```diff
@@ -305,6 +316,24 @@ func Test_zoektSearchHEAD(t *testing.T) {
...
+		{
+			name: "returns error if searcher returns an error",
+			args: args{
+				ctx:   context.Background(),
+				query: &search.PatternInfo{PathPatternsAreRegExps: true},
+				repos: []*search.RepositoryRevisions{
+					{Repo: &types.Repo{}},
+				},
+				useFullDeadline: true,
+				searcher:        &errorSearcher{err: errors.New("womp womp")},
```
Comment (tsenart) [inline cmd/frontend/graphqlbackend/textsearch_test.go]: Best error evah
