### PR TITLE
JetBrains: Manually emit window closing/open events to fix third-party modules that rely on those to render overlays

### LINKED ISSUE #36479: JetBrains: Hiding the popup the way we do it now doesn’t work well with some themes
## Context

We keep our popup open in the background (we just hide it) when the user “closes” it.
We need this behavior because the JCEF browser has glitches with off-screen rendering on Mac, and we can’t reliably close and reopen it.

## Problem

Some themes define a gray overlay over the whole editor when a popover is opened.
Since we keep our popover alive, it does not go away when we press Escape.

The IDE looks faded, like this:

image

This can be reproduced with the [Material UI theme](https://plugins.jetbrains.com/plugin/8006-material-theme-ui)

## Solution ideas

- Figure out what aspect of the popup these themes watch, and try to imitate it being closed.
- Close the popup, and “save” the JCEF browser in some other, visible area of the IDE by making it 1x1px and putting it somewhere
- Think about more solutions? :)

### PR DESCRIPTION
**Pull request by philipp-spiess**
Closes #36479

Manually emit WINDOW_OPENED and WINDOW_CLOSING events if we change the visibility of the Sourcegraph popup. This works around issues with third-party extensions like the material UI theme that uses these events to display overlays.

## Test plan

https://user-images.githubusercontent.com/458591/172343541-0701fa2c-687d-4d5e-af92-1ef2c6ef1f01.mov

## App preview:

- [Web](https://sg-web-ps-jetbrains-fix-material-ui-bug.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-kxqhvdfgsx.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by philipp-spiess** [comment]
Big thanks to @mallowigi for helping me with this workaround! 🙂

**Comment by mallowigi** [comment]
LGTM

File: client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java [hunk 1]
```diff
@@ -43,9 +44,17 @@ synchronized public void showPopup() {
...
             registerOutsideClickListener();
+
+            if (popup instanceof AbstractPopup) {
+                window = ((AbstractPopup) popup).getPopupWindow();
+            }
+        } else {
+            popup.setUiVisible(true);
+            // Manually emit a WINDOW_OPENED event if we change the popup to make it visible again. This works around
+            // issues with third-party extensions like the material UI theme that uses these events to display overlays.
+            window.dispatchEvent(new WindowEvent(window, WindowEvent.WINDOW_OPENED));
```
Comment (vdavid) [inline client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java:55]: Hmm, I think, theoretically, if the popup creation above fails (the above condition `(popup instanceof AbstractPopup)` returns false) then `window` might be `null`. But IntelliJ doesn't mark this as a warning, so maybe I'm missing something and this is fine.

File: client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java [hunk 2]
```diff
@@ -155,12 +167,8 @@ public void eventDispatched(AWTEvent event) {
                     }
```
Comment (vdavid) [inline client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java:167]: Btw, this listener creation can be simplified with two clicks: https://www.loom.com/share/29da2b45feb64b3483c358abb75dc381
I think the result is easier to read.
Not part of this PR, but if you're in that area, might be worth doing this refactor.

**Review by vdavid — APPROVED** [review]
Nice, great job for reaching out to them and doing this fix! :)

File: client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java (hunk 1 above)
Comment (philipp-spiess) [reply client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java]: `window` was not properly set up as nullable, fixed this now!

File: client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java (hunk 2 above)
Comment (philipp-spiess) [reply client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java]: 👍  ty! I often overlook those warnings unfortunately :(

Comment (vdavid) [reply client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java]: I wonder how other devs do this who use IntelliJ for development but the CLI for Git. I bet there are a lot of people who do this because as you said, using a GUI feels weird if you're used to the CLI. Creating Git hooks for the JetBrains warnings seems to be an excellent solution, but I imagine that few people do that in practice. So I wonder what's their workflow.
