### PR TITLE
siteAdmin: include alerts data in bug report page

### LINKED ISSUE #7657: The report-a-bug page should include a list of alerts that fired in the last 7 days, queried from existing Prometheus data
https://k8s.sgdev.org/site-admin/report-bug

This page should include a JSON entry which indicates over the last 7 days which alerts fired in Grafana and when, to let us easily see which alerts may be firing intermittently or constantly on a customer instance:

```json
"alerts": [
  {"timestamp": "...", "service_name": "gitserver", "name": "low_disk_space", value: "0"},
  {"timestamp": "...", "service_name": "gitserver", "name": "low_disk_space", value: "1"},
]
```

I believe this data could be easily acquired from [here](https://k8s.sgdev.org/-/debug/grafana/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22sum%20by%20(service_name,name)(alert_count%7Bname!%3D%5C%22%5C%22%7D)%22,%22format%22:%22table%22,%22instant%22:true,%22legendFormat%22:%22%22,%22context%22:%22explore%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D) and just using Go to hit the Prometheus admin API.

I would want to know:

1. That their instance has the alerts defined (i.e. when the value is zero, don't exclude it)
2. When the alert count changed, if at all. Do not include repeated information (e.g. I want to be able to read the JSON in an editor and make sense of it)

This is important because it gives us a way to get this information from customers without going through a "screenshot the home dashboard and then if any alerts fired I'll ask you again to screenshot another page to tell me what alert that actually was" -- and because these alerts are going to be more and more important going forward.

This is easier to add than the packaging of a full metrics dump, and easier to add than broadcasting this information up to sourcegraph.com 24/7 AND we would need this anyway for more privacy-conscious customers who disable pings and would refuse to send us a full metrics dump.

### PR DESCRIPTION
**Pull request by bobheadxi**
Closes #7657 

This PR implements:

* a new GQL endpoint, `site.monitoringStatistics`
    * just returns alerts for now
* render monitoring statistics in bug report page
* adjust wording in bug report page and link directly to bug report template

Remaining TODOs:

* [x] fallback behaviour if prometheus admin API is not available
* [x] update deploy-sourcegraph (https://github.com/sourcegraph/deploy-sourcegraph/pull/697)
* [x] update  deploy-sourcegraph-docker (https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/108)
* [x] fix CI complaints

image

image

### CODE REVIEW

**Comment by slimsag** [comment]
Apologies this wasn't clear in the original issue (or on the page itself..) but the first panel you see here is actually **the entire bug report**:

image

We want users to just be able to copy+paste that to us, basically, so having two separate panels here will not work. The idea is that in the first JSON blog, much like how there is a `"site": {...}` key today there would also be an `"alerts": {...}` key with the information you have under `Monitoring data` in your screenshot

Does this make sense?

File: cmd/frontend/graphqlbackend/prometheus.go [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+	"errors"
+	"fmt"
+
+	prometheusAPI "github.com/prometheus/client_golang/api"
+	prometheus "github.com/prometheus/client_golang/api/prometheus/v1"
+	"github.com/prometheus/common/model"
+	"github.com/sourcegraph/sourcegraph/internal/env"
+)
+
+var prometheusURL = env.Get("PROMETHEUS_SERVER_URL", "http://prometheus:9090", "prometheus server URL")
```
Comment (slimsag) [inline cmd/frontend/graphqlbackend/prometheus.go:14]: On your dev laptop, setup kubectl access to our `sourcegraph.com` cluster (see [here](https://about.sourcegraph.com/handbook/engineering/deployments#how-to-setup-access-to-kubernetes)) and port-forward access to Prometheus using this in a new terminal:

```
kubectl --namespace=prod port-forward 30090:30090
```

Once you do this, set `PROMETHEUS_SERVER_URL` here to `http://localhost:30090` and you can test your code here directly against the Sourcegraph.com Prometheus instance and compare what you get in your JSON against what is shown on https://sourcegraph.com/-/debug/grafana to make sure the alerts match up in a way that makes sense. Let me know if you need any help!

**Comment by bobheadxi** [comment]
@slimsag gotcha! updated in ee50ca359013c869de339d92a024adf801575db6

image

File: cmd/frontend/graphqlbackend/prometheus.go (hunk 1 above)
Comment (bobheadxi) [reply cmd/frontend/graphqlbackend/prometheus.go:14]: It seems about right, but looks pretty bad - likely because I've got the intervals set up to 1 hour. A bit unsure about what you mean here:

> When the alert count changed, if at all. Do not include repeated information (e.g. I want to be able to read the JSON in an editor and make sense of it)

Should I condense repeated `0` values?

Comment (bobheadxi) [reply cmd/frontend/graphqlbackend/prometheus.go:14]: it seems to roughly align with Grafana, but Grafana uses auto steps while I just set it to an hour - is this too broad?

File: dev/start.sh [hunk 2]
```diff
@@ -64,6 +64,7 @@ export CTAGS_COMMAND="${CTAGS_COMMAND:=cmd/symbols/universal-ctags-dev}"
 export ZOEKT_HOST=localhost:3070
 export USE_ENHANCED_LANGUAGE_DETECTION=${USE_ENHANCED_LANGUAGE_DETECTION:-1}
 export GRAFANA_SERVER_URL=http://localhost:3370
+export PROMETHEUS_SERVER_URL="${PROMETHEUS_SERVER_URL:'http://localhost:9090'}"
```
Comment (slimsag) [inline dev/start.sh:67]: Can we rename `PROMETHEUS_SERVER_URL` to just `PROMETHEUS_URL`? I see you did it to match `GRAFANA_SERVER_URL` -- I'm not sure why we added server there but I think it was a mistake / not a good idea as it makes our env vars longer than they need to be :)

File: cmd/frontend/graphqlbackend/schema.graphql [hunk 3]
```diff
@@ -3638,6 +3643,24 @@ type DeploymentConfiguration {
     siteID: String
 }
 
+# Monitoring overview.
+type MonitoringStatistics {
+    # Alerts fired in this time span.
+    alerts: [MonitoringAlert!]!
```
Comment (slimsag) [inline cmd/frontend/graphqlbackend/schema.graphql:3649]: There is one additional case we will need to handle: Some Sourcegraph instances have admins that are opposed to running our Prometheus server and will refuse to set `PROMETHEUS_URL` on the `frontend` container.

In this case, could you make `alerts` be `null`?

File: cmd/frontend/graphqlbackend/prometheus.go (hunk 1 above)
Comment (slimsag) [reply cmd/frontend/graphqlbackend/prometheus.go:14]: Got it, makes sense.

If an alert fires e.g. twice in the same hour with the way you have it set up now (should be straightforward to test this with port-forwarding above), does it show up on the report-a-bug page as firing twice or only once? (I am hoping it'll show `occurrences: 2` so we know it happened twice in that window)

If that works, then I would say we should even make it a larger window like 12 hours so the data is not _too_ verbose in case someone wants to quickly scan through it to see if it includes any secret data of theirs before sending it to us. That way we should end up getting at max 14 entries (one for each 12h window in the past 7d) per alert, as an example.

**Comment by slimsag** [comment]
image

Two asks:

1. Make sure these timestamps are in UTC (so they match up with other monitoring tools etc).
2. Is it easily possible to have it just include the year-month-date-hour instead of year-month-date-hour-minute-second-timezone ? Since it will be us reading them, and we will be aggregating by at least an hour (or 12) this would make it more legible.

**Comment by slimsag** [comment]
Or, would it make more sense to structure the data like:

```
"alerts": {
  "2020/05/11": [
    "09:02": [
      ... all the alerts that happened for 12h before 9:02 on 5/11 ...
    ],
    "21:02": [
      ... all the alerts that happened for 12h between 9:02 and 21:02 on 5/11 ...
    ],
  ],
  "2020/05/12": [
    ...
  ],
  "2020/05/13": [
    ...
  ]
},
```

Or something like that? i.e. instead of a flat list, broken down by date so it's easier to read which alerts happened on which days (in case we get a report like "the site went down on 05/12")

File: cmd/frontend/graphqlbackend/schema.graphql (hunk 3 above)
Comment (bobheadxi) [reply cmd/frontend/graphqlbackend/schema.graphql:3649]: I took a (possibly incorrect) approach to this - at the moment, if the prometheus URL is unset the frontend will return a specific error that is caught in the query:

https://github.com/sourcegraph/sourcegraph/pull/10704/files#diff-8da5e48b3e77eea6f2c70d95abea5970R646

I thought this would be more clear from an API perspective, but if you thinking just leaving it as `null` is better to indicate a lack of access to prometheus I'll make that change!

**Comment by bobheadxi** [comment]
> i.e. instead of a flat list, broken down by date so it's easier to read which alerts happened on which days (in case we get a report like "the site went down on 05/12")

Can do this too! It depends on how this will be used I suppose - if one of the use cases is to take this data and pop it into a chart, a flat list might make more sense, but if it's purely meant to be worked with by hand then a more human-friendly nested format like your example would make sense 🤔

File: dev/start.sh (hunk 2 above)
Comment (bobheadxi) [reply dev/start.sh]: yep, 
faaa903 !

**Comment by slimsag** [comment]
I don't think we have any good way to plot this into a chart today, so for the next 3-6 months at least I suspect this will be read by hand.

In the future, I could imagine wanting to build some really simple tooling for visualizing this -- so ideally the format would be (1) human readable and (2) possible to plug into a visualizer tool down the road without too much effort. I think as long as it's sortable by date like I proposed in my comment above, it should achieve both of these. What do you think?

File: cmd/frontend/graphqlbackend/schema.graphql (hunk 3 above)
Comment (slimsag) [reply cmd/frontend/graphqlbackend/schema.graphql:3649]: Oh nice, that's great

**Comment by bobheadxi** [comment]
Quick hack with existing data:

```py
df = pd.DataFrame(data)  # [ ... ] data from gql
df['timestamp'] = pd.to_datetime(df['timestamp'], infer_datetime_format=True)

plt.figure(figsize=(9, 3))
alerts = df['name'].unique()
for a in alerts:
    alert_data = df.loc[df['name'] == a]
    service = alert_data.iloc[0]['serviceName']
    plt.plot(alert_data['timestamp'],
             alert_data['occurrences'], label=f'{service}::{a}')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)
plt.show()
```

image

**Comment by slimsag** [comment]
Got it, makes sense, I am convinced then. Flat format it is 👍

File: cmd/frontend/graphqlbackend/prometheus.go (hunk 1 above)
Comment (bobheadxi) [reply cmd/frontend/graphqlbackend/prometheus.go]: @slimsag yes, I think so - taking a peek now on dotcom `gitserver` has ~4 errors in the past hour, and the graphql query returns >1 occurrences for a variety of `gitserver` errors in the same window

File: cmd/frontend/graphqlbackend/site_monitoring.go [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+		span.Finish()
+	}()
+
+	results, warn, err := r.prom.QueryRange(ctx, "sum by (service_name,name)(alert_count{name!=\"\"})",
+		prometheus.Range{
+			Start: time.Now().Add(-r.timespan),
+			End:   time.Now(),
+			Step:  alertsResolution,
+		})
+	if errors.Is(err, context.Canceled) {
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/site_monitoring.go:72]: We use `errors.Wrap` from `github.com/pkg/errors` almost everywhere (we're not taking uses of Go 1.13 Errors feature). Using [`errors.Cause`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40f4b43d0+errors.Cause&patternType=literal) is likely a better choice.

File: cmd/frontend/graphqlbackend/site_monitoring.go [hunk 5]
```diff
@@ -0,0 +1,112 @@
...
+	}
+	return &siteMonitoringStatisticsResolver{
+		ctx:      ctx,
+		prom:     prom,
+		timespan: time.Duration(*args.Days) * 24 * time.Hour,
+	}, nil
+}
+
+type siteMonitoringStatisticsResolver struct {
+	ctx      context.Context
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/site_monitoring.go:45]: I'm not sure `context` is something we would need to declare as a field in order to use it. I think make it as the first argument in methods (e.g. `Alerts(ctx context.Context)`) just works: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Ecmd/frontend/graphqlbackend/+%28ctx+context.Context&patternType=literal.

Any concerns you have that you want to explicitly pass "context"?

File: cmd/frontend/graphqlbackend/site_monitoring.go [hunk 6]
```diff
@@ -0,0 +1,112 @@
...
+			Step:  alertsResolution,
+		})
+	if errors.Is(err, context.Canceled) {
+		return nil, errPrometheusUnavailable
+	}
+	if err != nil {
+		return nil, fmt.Errorf("prometheus query failed: %w", err)
+	}
+	if len(warn) > 0 {
+		log.Printf("site.monitoring.alerts: warnings encountered on prometheus query (%s): [ %s ]",
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/site_monitoring.go:79]: You probably want to use [`log15.Warn`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+log15.Warn&patternType=literal) here.

File: cmd/frontend/graphqlbackend/site_monitoring.go [hunk 7]
```diff
@@ -0,0 +1,112 @@
...
+			r.timespan.String(), strings.Join(warn, ","))
+	}
+	if results.Type() != model.ValMatrix {
+		return nil, fmt.Errorf("received unexpected result type '%s' from prometheus", results.Type())
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/site_monitoring.go:83]: nit:
```suggestion
		return nil, fmt.Errorf("received unexpected result type %q from prometheus", results.Type())
```

File: cmd/frontend/graphqlbackend/site_monitoring.go [hunk 8]
```diff
@@ -0,0 +1,112 @@
...
+	data := results.(model.Matrix)
+	alerts := make([]*MonitoringAlert, 0)
+	for _, sample := range data {
+		var (
+			name        = string(sample.Metric["name"])
+			serviceName = string(sample.Metric["service_name"])
+			prevVal     *model.SampleValue
+		)
+		for _, p := range sample.Values {
+			// don't ignore first
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/site_monitoring.go:95]: I'm a bit confused by this comment, could you explain?

File: cmd/frontend/graphqlbackend/site_monitoring_test.go [hunk 9]
```diff
@@ -0,0 +1,96 @@
...
+				&model.SampleStream{
+					Metric: model.Metric{"name": "hello", "service_name": "world"},
+					Values: []model.SamplePair{{Timestamp: sampleT, Value: model.SampleValue(0)}}},
+			},
+		}, []*MonitoringAlert{{
+			TimestampValue:   DateTime{sampleT.Time().Truncate(time.Hour)},
+			NameValue:        "hello",
+			ServiceNameValue: "world",
+			OccurrencesValue: 0,
+		}}, nil},
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/site_monitoring_test.go:40]: Our current practice is to spell out field names for test structs, which would be much easier to reason when the number of test cases becomes very long, and more readable:
```suggestion
		{
			name: "includes alerts with no occurrences", 
			fields: fields{
			queryValue: model.Matrix{
				&model.SampleStream{
					Metric: model.Metric{"name": "hello", "service_name": "world"},
					Values: []model.SamplePair{{Timestamp: sampleT, Value: model.SampleValue(0)}}},
				},
			}, 
			want: []*MonitoringAlert{{
				TimestampValue:   DateTime{sampleT.Time().Truncate(time.Hour)},
				NameValue:        "hello",
				ServiceNameValue: "world",
				OccurrencesValue: 0,
			}}, 
			wantErr : nil,
		},
```

File: cmd/frontend/graphqlbackend/site_monitoring_test.go [hunk 10]
```diff
@@ -0,0 +1,96 @@
...
+			r := &siteMonitoringStatisticsResolver{
+				ctx:      context.Background(),
+				prom:     mock,
+				timespan: 24 * time.Hour,
+			}
+			alerts, err := r.Alerts()
+			if err != nil {
+				if tt.wantErr == nil {
+					t.Errorf("expected no error, got %v", err)
+				} else if !errors.Is(err, tt.wantErr) {
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/site_monitoring_test.go:87]: Same concern as in the other place, `errors.Cause` feels a better choice.

File: cmd/frontend/graphqlbackend/prometheus.go [hunk 11]
```diff
@@ -0,0 +1,41 @@
...
+	"errors"
+	"fmt"
+
+	prometheusAPI "github.com/prometheus/client_golang/api"
+	prometheus "github.com/prometheus/client_golang/api/prometheus/v1"
+	"github.com/prometheus/common/model"
+	"github.com/sourcegraph/sourcegraph/internal/env"
+)
+
+var prometheusURL = env.Get("PROMETHEUS_URL", "http://prometheus:9090", "prometheus server URL")
```
[the remark this answers is not in the document]
Comment (bobheadxi) [reply cmd/frontend/graphqlbackend/prometheus.go:14]: This variable will be set on deploy using the default methods (sourcegraph/deploy-sourcegraph#697, sourcegraph/deploy-sourcegraph-docker#108) but from #7657 the main way to determine if it's down is:

* on timeout
* variable is unset

File: cmd/frontend/graphqlbackend/prometheus.go [hunk 12]
```diff
@@ -0,0 +1,41 @@
...
+// errPrometheusUnavailable is raised specifically when prometheusURL is unset or when
+// prometheus API access times out, both of which indicate that the server API has likely
+// been configured to explicitly disallow access to prometheus, or that prometheus is not
+// deployed at all. The website checks for this error in `fetchMonitoringStats`, for example.
+var errPrometheusUnavailable = errors.New("prometheus API is unavailable")
+
+func newPrometheusQuerier() (prometheusQuerier, error) {
+	if prometheusURL == "" {
+		return nil, errPrometheusUnavailable
+	}
```
[the remark this answers is not in the document]
Comment (bobheadxi) [reply cmd/frontend/graphqlbackend/prometheus.go:33]: Yep, I was able to verify the fallback behaviour by unsetting the variable. Though I wonder if it's better to make this more explicitly opt-in-y by having the default be `""` - what do you think @slimsag ?

File: cmd/frontend/graphqlbackend/site_monitoring.go (hunk 4 above)
Comment (bobheadxi) [reply cmd/frontend/graphqlbackend/site_monitoring.go:72]: Took a look and sad to see `github.com/pkg/errors` won't be made compatible with the new errors :'(

That said, since prometheus is a third-party library that does not seem to use `pkg/errors` and the error i'm specifically looking for here originates from the go standard library, would it still make sense to use `pkg/errors` here? Or is this primarily for consistency's sake?

File: cmd/frontend/graphqlbackend/prometheus.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (unknwon) [reply cmd/frontend/graphqlbackend/prometheus.go:14]: Cool, thanks for links!

Side note: Originally I was also thinking put this file into another package (but don't know where) because it feels like will be useful outside the `graphqlbackend` package, and it will be very hard to realize we have this file that can be used to determine Prometheus endpoint. Anyway, up to you!

File: cmd/frontend/graphqlbackend/site_monitoring.go (hunk 4 above)
Comment (unknwon) [reply cmd/frontend/graphqlbackend/site_monitoring.go:72]: > Took a look and sad to see `github.com/pkg/errors` won't be made compatible with the new errors :'(

Yeah... that's another sad story.



> would it still make sense to use `pkg/errors` here? Or is this primarily for consistency's sake?

I would say both, 1) we can't alway be sure we won't do some wrapping in the future and didn't realize we need to change this line 2) for consistency

File: cmd/frontend/graphqlbackend/site_monitoring.go (hunk 8 above)
Comment (bobheadxi) [reply cmd/frontend/graphqlbackend/site_monitoring.go]: I've added some clarification here: 03db000

File: cmd/frontend/graphqlbackend/site_monitoring.go (hunk 6 above)
Comment (bobheadxi) [reply cmd/frontend/graphqlbackend/site_monitoring.go]: gotcha! 0f83d54

File: cmd/frontend/graphqlbackend/gen.go [hunk 13]
```diff
@@ -1,3 +1,4 @@
 package graphqlbackend
 
 //go:generate env GO111MODULE=on go run gen/schema_generate.go
+//go:generate env GOBIN=$PWD/.bin GO111MODULE=on go install github.com/efritz/go-mockgen
```
[the remark this answers is not in the document]
Comment (bobheadxi) [reply cmd/frontend/graphqlbackend/gen.go:4]: I've moved them to this file: 647e5ad

File: cmd/frontend/graphqlbackend/site_monitoring.go (hunk 5 above)
Comment (bobheadxi) [reply cmd/frontend/graphqlbackend/site_monitoring.go]: Ah, didnt know I could, thanks!

File: cmd/frontend/graphqlbackend/site_monitoring.go (hunk 4 above)
Comment (bobheadxi) [reply cmd/frontend/graphqlbackend/site_monitoring.go:70]: I've switched these to use `pkg/errors` in 2d8d9b0 . That said I see that `pkg/errors` actually exposes the standard library's `Is()`, `As()`, etc. and am now very confused about what level of compatibility the library offers 🤔

File: cmd/frontend/graphqlbackend/prometheus.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (bobheadxi) [reply cmd/frontend/graphqlbackend/prometheus.go:14]: Even if it is only used in `graphqlbackend` I still think that it might be good to have this elsewhere, but I wasn't sure either 🙃 would `cmd/frontend/prometheus` make sense?

File: cmd/frontend/graphqlbackend/site_monitoring.go (hunk 4 above)
Comment (unknwon) [reply cmd/frontend/graphqlbackend/site_monitoring.go:70]: > That said I see that `pkg/errors` actually exposes the standard library's `Is()`, `As()`, etc. and am now very confused about what level of compatibility the library offers 🤔

I think `pkg/errors` has `Is()` and `As()` is the exact reason why it is not compatible with stdlib. So far we only use `Wrap` and `Cause` so we're mostly fine :D

File: cmd/frontend/graphqlbackend/gen.go [hunk 14]
```diff
@@ -1,3 +1,6 @@
...
+
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/gen.go:5]: nit:
```suggestion
```

File: cmd/frontend/graphqlbackend/site_monitoring.go [hunk 15]
```diff
@@ -0,0 +1,114 @@
...
+	defer func() {
+		if err != nil {
+			ext.Error.Set(span, true)
+			span.SetTag("err", err.Error())
+		}
+		cancel()
+		span.Finish()
+	}()
+
+	results, warn, err := r.prom.QueryRange(ctx, "sum by (service_name,name)(alert_count{name!=\"\"})",
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/site_monitoring.go:64]: nit: the following is easier to read IMO
```suggestion
	results, warn, err := r.prom.QueryRange(ctx, `sum by (service_name,name)(alert_count{name!=""})`,
```

File: cmd/frontend/graphqlbackend/site_monitoring.go (hunk 4 above)
Comment (bobheadxi) [reply cmd/frontend/graphqlbackend/site_monitoring.go:70]: After some digging, I think:

* `Is`, `As`, `Unwrap` is fully compatible with `%w` and `pkg/errors` stuff (https://github.com/pkg/errors/blob/master/go113_test.go)
*  reverted `Cause` support seems to imply the incompatability is specifically with using `Cause` on `%w` errors: https://github.com/pkg/errors/commit/614d223910a179a466c1767a985424175c39b465

It doesn't say so anywhere but this seems to imply a migration path is to always use `Is` and `As`?

File: cmd/frontend/graphqlbackend/prometheus.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (unknwon) [reply cmd/frontend/graphqlbackend/prometheus.go:14]: If I have to pick a place, I would choice `internal/promeutil` (or `internal/prometheusutil`).

File: cmd/frontend/graphqlbackend/site_monitoring.go (hunk 4 above)
Comment (unknwon) [reply cmd/frontend/graphqlbackend/site_monitoring.go:70]: Ah, turns out `pkg/errors`'s `Is`, `As` and `Unwrap` are just wrappers of stdlib's functions: https://github.com/pkg/errors/blob/master/go113.go#L16.

We probably should stop spending more time on this and work on other things to land this PR 😂 I agree using `errors.Is` is OK here, make sure we have a test for it.

**Comment by bobheadxi** [comment]
@slimsag I've made one additional change to what's described in #7657 - originally you say to check for timeouts to check if the prometheus API is not set up, but in most cases the error is a bit more immediate:

Screen Shot 2020-05-20 at 10 23 02 AM

a0c9275282a1b71ec306f769dd697d167a7c7c33 shuffles things around so that the prometheus client itself checks for syscall errors as well, and if we get a `ECONNREFUSED` or `EHOSTUNREACH` we raise an `ErrPrometheusUnavailable`

File: cmd/frontend/graphqlbackend/prometheus.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (bobheadxi) [reply cmd/frontend/graphqlbackend/prometheus.go]: moved in 423ddde

**Comment by bobheadxi** [comment]
argh I swear I removed it earlier

File: cmd/frontend/graphqlbackend/prometheus.go (hunk 1 above)
Comment (slimsag) [reply cmd/frontend/graphqlbackend/prometheus.go]: Great!

File: cmd/frontend/graphqlbackend/prometheus.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (slimsag) [reply cmd/frontend/graphqlbackend/prometheus.go]: Great!

File: cmd/frontend/graphqlbackend/prometheus.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (slimsag) [reply cmd/frontend/graphqlbackend/prometheus.go]: Yeah, this is a good point. The "default" environment variables in our codebase today are in many cases are a bad combination of "the default for just kubernetes deployments, overridden by other deployments explicitly" and "the default for just dev environments".

I am massively in favor of making this more explicit, making `PROMETHEUS_URL` `""` by default is a great start! You'll just need to add this env var to our dev environments e.g. right here:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@fa568d9f9bc00cec6d0f4542aa6ab5b406160f10/-/blob/dev/start.sh#L66

**Comment by slimsag** [comment]
> I've made one additional change to what's described in #7657 - originally you say to check for timeouts to check if the prometheus API is not set up, but in most cases it seems the error is a bit more immediate:

That's great!

**Comment by slimsag** [comment]
I pushed up some very minor wording changes, also:

- One small change to make `alerts: null` show up when Prometheus is unavailable (so that we have an easy way to know "they are running a version with this capability, it's just Prometheus is not available or configured properly"):

image

**Comment by slimsag** [comment]
I ran this locally to check and make sure the data made sense (the prometheus QL is a little tricky), unfortunately I think we'll need to tweak some more things here to get the right data.

I notice for example when I visit [this page](https://sourcegraph.com/-/debug/grafana/d/precise-code-intel-bundle-manager/precise-code-intel-bundle-manager?orgId=1&from=now-7d&to=now) we get many little peaks where this alert fired:

image

This tells me the alert fired _a lot_ between 5/14 00:00 and 12:00.

Similarly, if I run the Prometheus `kubectl port-forward` command and visit [this Prometheus page](http://localhost:30090/graph?g0.range_input=1w&g0.expr=sum(alert_count%7Bname%3D%2299th_percentile_bundle_database_duration%22%2Cservice_name%3D%22precise-code-intel-bundle-manager%22%7D)&g0.tab=0)  and let it do auto-stepping I see this:

image

It's obviously less than what Grafana is showing -- but it still shows it fired many times. I realized if I put `300` seconds in the step field (5 minutes) it ([i.e. this url](http://localhost:30090/graph?g0.range_input=1w&g0.step_input=300&g0.expr=sum(alert_count%7Bname%3D%2299th_percentile_bundle_database_duration%22%2Cservice_name%3D%22precise-code-intel-bundle-manager%22%7D)&g0.tab=0)) it gives me more precision:

image

But if I plug in a step value of 12h (like we're doing in your code here) I get this, which doesn't tell me how much it fired in that 12h window, just that "it did once" due to the lesser precision:

image

Similarly, the report-a-bug page shows me just:

```json
    {
      "serviceName": "precise-code-intel-bundle-manager",
      "name": "99th_percentile_bundle_database_duration",
      "timestamp": "2020-05-14T10:00:00Z",
      "occurrences": 1
    },
```

If we changed the step to `300` that would indeed show the same data, but it would produce *many* more JSON entries (one for every 5 minutes / 300 seconds / the step) -- far too many.

Ideally I want the same number of JSON entries that we have currently (i.e. one per alert per 12h), but `occurrences` should show a much larger number than 1.

To solve this we could of course aggregate on the Go side, but that's not ideal for perf and maintainability sake -- I think we need to solve it in the Prometheus query itself but it's a little tricky because Prometheus QL itself (and, in specific, our usage of it in this way) is a little tricky.

**Comment by slimsag** [comment]
Since it is quite tricky & I didn't want to leave you stuck with that, I played around with it for a bit and came up with [this query](http://localhost:30090/graph?g0.range_input=1w&g0.step_input=43200&g0.expr=sum_over_time(alert_count%7Bname%3D%2299th_percentile_bundle_database_duration%22%2Cservice_name%3D%22precise-code-intel-bundle-manager%22%7D%5B12h%5D)&g0.tab=0) which it looks like does the job if we supply a 12h step (as we are now) and returns us that the alert fired `840` times.

This got me thinking about the data we're actually collecting here, though: Yeah, the alert fired 840 times.. but was that in the first 30m of that 12h window? Or was that 840 times spread out pretty evenly over 12h? I guess "was it firing most of the time" is what is most valuable to answer here. So I came up with these two queries:

- [this one](http://localhost:30090/graph?g0.range_input=1w&g0.step_input=43200&g0.expr=max%20by%20(level%2Cname%2Cservice_name)(sum_over_time(alert_count%7Bname!%3D%22%22%7D%5B12h%5D))&g0.tab=0) gives us the total number of alerts that fired in the last last 12h.
- [this one](http://localhost:30090/graph?g0.range_input=1w&g0.step_input=43200&g0.expr=max%20by%20(level%2Cname%2Cservice_name)(avg_over_time(alert_count%7Bname!%3D%22%22%7D%5B12h%5D))&g0.tab=0) gives us a number between [0, 1] that indicates the average number firing over the 12h window. So if it says 1.0, it was firing 100% of the time during that 12h window, if it says 0.5 it was firing 50% of the time, etc., on average.

So for the same alert we can see:

- It fired 836 times in total:

image

- It was firing 99% of the time on average:

image

Then I was thinking: "Is there a way to combine these so we have both?" but the more I thought about it the more I realized "total times fired" is actually not useful at all, it's just a poor proxy for "was it firing a lot in this timeframe" which the average describes perfectly.

**Comment by slimsag** [comment]
So, I plugged that into the code, PTAL, we now get:

```
    {
      "serviceName": "precise-code-intel-bundle-manager",
      "name": "99th_percentile_bundle_database_duration",
      "timestamp": "2020-05-14T01:00:00Z",
      "average": 0.9082568807339452
    },
    {
      "serviceName": "precise-code-intel-bundle-manager",
      "name": "99th_percentile_bundle_database_duration",
      "timestamp": "2020-05-14T13:00:00Z",
      "average": 0.9913366336633663
    },
    {
      "serviceName": "precise-code-intel-bundle-manager",
      "name": "99th_percentile_bundle_database_duration",
      "timestamp": "2020-05-15T01:00:00Z",
      "average": 0.9397163120567364
    },
    {
      "serviceName": "precise-code-intel-bundle-manager",
      "name": "99th_percentile_bundle_database_duration",
      "timestamp": "2020-05-15T13:00:00Z",
      "average": 0.050687907313540746
    },
    {
      "serviceName": "precise-code-intel-bundle-manager",
      "name": "99th_percentile_bundle_database_duration",
      "timestamp": "2020-05-16T01:00:00Z",
      "average": 0
    },
```

**Comment by slimsag** [comment]
I also made one more minor change just now to include the alert level in the name, so we include the breakdown of critical and warning alerts:

```
    {
      "serviceName": "zoekt-indexserver",
      "name": "critical: average_resolve_revision_duration",
      "timestamp": "2020-05-14T01:00:00Z",
      "average": 0
    },
    {
      "serviceName": "zoekt-indexserver",
      "name": "warning: average_resolve_revision_duration",
      "timestamp": "2020-05-14T01:00:00Z",
      "average": 0
    },
```

**Comment by bobheadxi** [comment]
Thanks @slimsag for the detailed review and additional work on the PR 🤯 really appreciate it, and your writeup of making the metric more usable!

I've added sorting in 2db8399f3e9241fd2b1ed3ac4bb157a1233471cb
