### PR TITLE
indexed: Fix settings page for indexed tags and deduplicate main branches

### LINKED ISSUE #13787: indexed: settings page expects git ref, we return git rev
https://github.com/sourcegraph/sourcegraph/blob/d119b3456933e94aefc845d471b4dd91f979d8a5/cmd/frontend/graphqlbackend/repository_text_search_index.go#L128

We use ref resolvers in our GraphQL API for indexed search branches. However, we will pass in revs like `v1.0` or `dev` instead of `refs/tags/v1.0` or `refs/heads/dev`. This can lead to weird issues on the settings page for indexed search on a repo. Notably when returning the status of a tag resolving the ref fails. This manifests as us saying the index is not up to date (indexed commit != what we think the latest commit is since we can't resolve it).

The fix here is either updating the GraphQL schema to be rev based, or resolving the rev into a ref.

### PR DESCRIPTION
**Pull request by novoselrok**
Fixes #13787.

### CODE REVIEW

File: cmd/frontend/graphqlbackend/repository_text_search_index.go [hunk 1]
```diff
@@ -117,15 +119,22 @@ func (r *repositoryTextSearchIndexResolver) Refs(ctx context.Context) ([]*reposi
 	for i, refName := range refNames {
 		refs[i] = &repositoryTextSearchIndexedRef{ref: &GitRefResolver{name: refName, repo: r.repo}}
 	}
-	refByName := func(refName string) *repositoryTextSearchIndexedRef {
+	refByName := func(name string) *repositoryTextSearchIndexedRef {
+		possibleRefNames := []string{"refs/heads/" + name, "refs/tags/" + name, name}
```
Comment (keegancsmith) [inline cmd/frontend/graphqlbackend/repository_text_search_index.go:123]: I suppose you don't need to do te final `name` check since we will fallback to that (since you will never update name)

**Review by keegancsmith — APPROVED** [review]

**Review by keegancsmith — APPROVED** [review]
LGTM!
