### PR TITLE
site-admin: Add commented-out repositoryQuery to default configs

### LINKED ISSUE #3656: Documentation for `repositoryQuery` in GitHub default configuration is wrong
The current `defaultConfig` for GitHub contains this documentation and default value for `repositoryQuery`:

https://github.com/sourcegraph/sourcegraph/blob/5632b59b90bd7de7430ca91d0de7e9ca0ea33423/web/src/site-admin/externalServices.tsx#L197-L200

The problem is that the documentation (`An array of strings specifying [...]`) describes the `repos` attribute documented here: https://docs.sourcegraph.com/admin/external_service/github#configuration

If you follow the documentation (as I did) and put in, for example, `["sourcegraph/sourcegraph"]` you end up with something completely different than expected.

This default configuration is the result of multiple commits. https://github.com/sourcegraph/sourcegraph/commit/da3743ece358fbe6709f07e95d5fd97bd554e047 by @tsenart and https://github.com/sourcegraph/sourcegraph/commit/d2b0714b293d0e916dd7ae0bb06f8dc59d1d606e by @sqs. The last commit that touched this part and removed the `repos` attribute from the default configuration is [this one](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/67264581ebe82d22d0cce169207004518087ea1e) by @tsenart.

What are your opinions on this? I'm not sure I get all of the reasons for the changes and why things have been added/removed.

But since the default configuration is rather unhelpful (documentation is misleading and you don't have any examples included) I think we now have two options:

1. Change the documentation to correctly describe `repositoryQuery`
2. Re-add `repos` so users know how to add single repos to the configuration

Opinions? :)

### PR DESCRIPTION
**Pull request by mrnugget**
This commit adds commented-out examples for `repositoryQuery` values in the default configurations to make clear to users — at first glance! — that `repositoryQuery` is not a list of repository names.

Fixes #3656

### CODE REVIEW

**Comment by tsenart** [comment]
Looks good! Let's update `projectQuery` of Gitlab too though.

File: web/src/site-admin/externalServices.tsx [hunk 1]
```diff
@@ -280,6 +281,7 @@ export const ALL_EXTERNAL_SERVICES: Record<GQL.ExternalServiceKind, ExternalServ
   // Here's the official Bitbucket Server documentation about which query string parameters are valid:
   // https://docs.atlassian.com/bitbucket-server/rest/6.1.2/bitbucket-rest.html#idp355
   "repositoryQuery": [
+    // "?name=sourcegraph&projectname=sourcegraph"
```
Comment (tsenart) [inline web/src/site-admin/externalServices.tsx]: It may be confusing that the name and project are the same. Perhaps we keep it consistent with Github and exclude the name argument (leaving only the project)?

Comment (mrnugget) [reply web/src/site-admin/externalServices.tsx]: Good point! Had the same thing in mind, glad to have some confirmation :)

**Comment by mrnugget** [comment]
@tsenart I've added a `projectQuery` example for GitLab that should also make clear that this is not a simple list of repositories. Good to merge then?

**Comment by tsenart** [comment]
>  Good to merge then?

Yep, it's approved!
