### PR TITLE
Fixing: UX when viewing a commit blocked by sub-repo permissions could be better

### LINKED ISSUE #30751: UX when viewing a commit blocked by sub-repo permissions could be better
When directly navigating to the page for a commit that is blocked by sub-repo permissions we see an ugly error page.

Screenshot 2022-02-02 at 11 46 42

Instead we should probably display something similar to a "commit not found" screen, for example:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/f6c10b3b575d89aedaa9087cf64e0a1107a70761

### PR DESCRIPTION
**Pull request by varsanojidan**
Closes #30751

## Test plan

Tested using the local development environment, accessed both a commit that was and a commit thats wasn't blocked by sub-repo permissions and validated that they behaved the same after the changes.

Before Change:

image

After Change:

image

### CODE REVIEW

**Comment by indradhanush** [comment]
@cla-bot check

**Comment by varsanojidan** [comment]
@cla-bot check

File: client/web/src/repo/commit/RepositoryCommitPage.tsx [hunk 1]
```diff
@@ -85,7 +85,14 @@ const queryCommit = memoizeObservable(
...
                 if (!data.node.commit) {
-                    throw createAggregateError(errors || [new Error('Commit not found')])
+                    if (errors) {
+                        errors = errors.filter(error => !error.message.includes('revision not found'))
+                    }
+                    if (!errors || errors?.length === 0) {
+                        throw new Error('Commit not found')
+                    }
+                    // Aggregating all the 'revision not found' errors into one Commit not found, appending it to any other errors"
+                    throw createAggregateError([new Error('Commit not found'), ...errors])
```
Comment (umpox) [inline client/web/src/repo/commit/RepositoryCommitPage.tsx:95]: I think we should try to avoid reassigning `errors` if possible. I think this is the same functionality?

```
                    const errorsWithoutRevisionError = errors?.filter(
                        error => !error.message.includes('revision not found')
                    )

                    // If we have no errors that we care about, throw generic not found error
                    if (!errorsWithoutRevisionError || errorsWithoutRevisionError.length === 0) {
                        throw new Error('Commit not found')
                    }

                    // Aggregating all the 'revision not found' errors into one Commit not found, appending it to any other errors"
                    throw createAggregateError([new Error('Commit not found'), ...errorsWithoutRevisionError])
```

**Review by umpox — COMMENTED** [review]
I don't have much context on the original issue so it'd be useful to see a screenshot of what the errors now look like in the UI

File: client/web/src/repo/commit/RepositoryCommitPage.tsx (hunk 1 above)
Comment (umpox) [reply client/web/src/repo/commit/RepositoryCommitPage.tsx:95]: Although I'm not sure - as `errors` can be in 3 different states here I think? automated tests + comments here would be useful to help explain the code

Comment (varsanojidan) [reply client/web/src/repo/commit/RepositoryCommitPage.tsx]: I added a before and after change comparison to the PR body so you can see what it was like before/after the change. Added some comments as well that hopefully makes it a bit more clear.

Comment (varsanojidan) [reply client/web/src/repo/commit/RepositoryCommitPage.tsx]: Ill also look into automated testing as well, do you know of any place in the codebase we test graphql requests?

**Review by umpox — APPROVED** [review]
