### PR TITLE
Removed extra "}" (fixed #9083)

### LINKED ISSUE #9083: Canceling new access token creation throws 404
- **Sourcegraph version:** 58360_2020-03-17_da29d70
- **Platform information:** Chrome 80.0.3987.132  on macOS 10.15.1

#### Steps to reproduce:

1. Go to User account settings –> Access tokens
2. Click on "Generate new token"
3. Click on "Cancel"

#### Expected behavior:

The link goes to `.../settings/tokens`

#### Actual behavior:

The link goes to `.../settings/tokens%7D` and shows a 404 Error

### PR DESCRIPTION
**Pull request by AnandChowdhary**
This PR fixes the issue #9083 I opened a few minutes ago.

### CODE REVIEW

File: web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenPage.tsx [hunk 1]
```diff
@@ -193,7 +193,7 @@ export class UserSettingsCreateAccessTokenPage extends React.PureComponent<Props
                     </button>
                     <Link
                         className="btn btn-secondary ml-1 e2e-create-access-token-cancel"
-                        to={`${this.props.match.url.replace(/\/new$/, '')}}`}
+                        to={`${this.props.match.url.replace(/\/new$/, '')}`}
```
Comment (eseliger) [inline web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenPage.tsx]: Thanks! Looking at it, I think it can be even simpler: 

```suggestion
                        to={this.props.match.url.replace(/\/new$/, '')}
```

**Comment by unknwon** [comment]
Triggered a build for this PR.
