### PR TITLE
Fix observing/parsing local storage client settings

### LINKED ISSUE #15088: Fix Gitlab Native Integration
**[Bug Thread on Gitlab](https://gitlab.com/gitlab-org/gitlab/-/issues/233447#note_436315915)** 

There's a bug with our gitlab integration that breaks code intelligence on gitlab. 

This thread is long, so here is the [specific open bug](https://gitlab.com/gitlab-org/gitlab/-/issues/233447#note_436355170).

### PR DESCRIPTION
**Pull request by marekweb**
**Background**

Fix #15088 

`LocalStorageSubject` is used in the native integration to observe updates to `localStorage` for the value of `sourcegraphClientSettings` but it automatically parses the values as JSON.

This is a mismatch with the behavior of the other observer we use, `observeStorageKey` for extension storage. In `createStorageSettingsCascade` we switch between these two storage locations as if they were equivalent, based on whether we're in a browser extension or a native integration (using `isInPage`)

This caused the bug in the native integration in which we double-parse values that are coming from `LocalStorageSubject` and it throws a `e.charCodeAt is not a function` error.

**Implementation**

This change drops the usage of `LocalStorageSubject` in this particular instance, in favor of `observeLocalStorageKey` which mirrors the behavior of `observeStorageKey`.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Great find. Another way to frame this problem would be that while we use `LocalStorageSubject` to _read_ client settings, which parses/serializes JS values similar to how `browser.storage` stores raw JS values (and to how `useLocalStorage()` does it too), where we _write_ to client settings we write JSONC strings directly using the low-level `localStorage.setItem()`: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/browser/src/shared/platform/settings.ts#L173
A structural problem here could also be that those two, the read and write cases, are not colocated (don't go through the same abstraction).

It worries me a bit that we now introduce another local function that behaves different than e.g. `useLocalStorage()` in the web app, but given that users will already have raw JSONC values in their settings it's likely best to go this route than change the format.
It would just be good to add comments to the code explaining _why_ we can't use `LocalStorageSubject` here, and that the Observable is an Observable of JSONC.

File: client/browser/src/shared/platform/settings.ts [hunk 1]
```diff
@@ -13,15 +13,29 @@ import {
...
+        filter(event => event.key === key),
+        map(event => event.newValue),
+        startWith(initialValue),
+        map(value => value ?? defaultValue),
+        distinctUntilChanged()
+    )
+}
+
 const createStorageSettingsCascade: () => Observable<SettingsCascade> = () => {
     const storageSubject = isInPage
```
Comment (felixfbecker) [inline client/browser/src/shared/platform/settings.ts:37]:
```suggestion
    /** Observable of the JSONC string of the settings. */
    const storageObservable = isInPage
```

File: client/browser/src/shared/platform/settings.ts [hunk 2]
```diff
@@ -13,15 +13,29 @@ import {
...
 } from '../../../../shared/src/settings/settings'
 import { isErrorLike } from '../../../../shared/src/util/errors'
-import { LocalStorageSubject } from '../../../../shared/src/util/LocalStorageSubject'
 import { observeStorageKey, storage } from '../../browser-extension/web-extension-api/storage'
 import { isInPage } from '../context'
 
 const inPageClientSettingsKey = 'sourcegraphClientSettings'
 
+/**
+ * Returns an observable that emits the localStorage value for the given key on
```
Comment (felixfbecker) [inline client/browser/src/shared/platform/settings.ts:22]:
```suggestion
 * Returns an observable that emits the localStorage value (as a raw string) for the given key on
```

File: client/browser/src/shared/platform/settings.ts [hunk 3]
```diff
@@ -13,15 +13,29 @@ import {
...
+        startWith(initialValue),
+        map(value => value ?? defaultValue),
+        distinctUntilChanged()
+    )
+}
+
 const createStorageSettingsCascade: () => Observable<SettingsCascade> = () => {
     const storageSubject = isInPage
-        ? new LocalStorageSubject<string>(inPageClientSettingsKey, '{}')
+        ? observeLocalStorageKey(inPageClientSettingsKey, '{}')
```
Comment (felixfbecker) [inline client/browser/src/shared/platform/settings.ts:38]:
```suggestion
        // NOTE: We can't use LocalStorageSubject here because the JSONC string is stored raw in localStorage and LocalStorageSubject also does parsing.
        // This could be changed, but users already have settings stored, so it would need a migration for little benefit.
        ? observeLocalStorageKey(inPageClientSettingsKey, '{}')
```

**Review by felixfbecker — APPROVED** [review]

**Comment by marekweb** [comment]
>  Instead of having if (isInPage) sprinkled everywhere, there should have been an interface passed around for interacting with storage which can have two different implementations instantiated at the top level, branching by abstraction.

I agree, the storage service could handle reading, writing and observing changes in one interface.

> It would just be good to add comments to the code explaining why we can't use LocalStorageSubject here, and that the Observable is an Observable of JSONC.

Just want write down a couple notes here: the only other usage of `LocalStorageSubject` is for `sideloadedExtensionUrl` storage. `LocalStorageSubject` has some interesting ideas:

- it's a more granular abstraction, since you instantiate it for a particular key and then it acts as a setter/observable for that key. I just don't like the name of the setter method which is `next(newValue)` because it conflates the observer semantic with the setter semantic.
- as a setter, circumvents the limitation in which `localStorage` only emits update events for updates that came from a different page, not updates in the current page. That's a useful abstraction.
- it gets instantiated for a particular storage **key** so we could take that idea further, and have per-key storage instances 

> It worries me a bit that we now introduce another function that behaves different than e.g. useLocalStorage() in the web app

I guess it's settings data which is the outlier, since it must support JSONC and not plain JSON, right? And `useLocalStorage` has the unique aspects that designed to be a React hook and it parses only plain JSON. Also I want to better understand your worry: is it the very fact that it behaves differently in terms of parsing JSON/JSONC vs not parsing, or is it overall that we have multiple ways of using local storage instead of it being abstracted/unified somewhere?

**Comment by marekweb** [comment]
I've done manual testing on this and I think it can be shipped. Additionally, automated tests would be good here, we would need to solve:

- how to mock localStorage, with emitting storage events
- how to test the fact that localStorage events are emitted across pages

I think we can keep that outside of the scope of this fix PR.
