### PR TITLE
a8n: Fix listing all ChangesetEvents resulting in empty results

### LINKED ISSUE #6011: changesetCountsOverTime panics
Run this query on latest master: [GraphQL query](http://localhost:3080/api/console#%7B%22query%22%3A%22query%20CampaignByID(%24campaign%3A%20ID!)%20%7B%5Cn%20%20%20%20node(id%3A%20%24campaign)%20%7B%5Cn%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%20%20...%20on%20Campaign%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20...CampaignFields%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20CampaignFields%20on%20Campaign%20%7B%5Cn%20%20%20%20id%5Cn%20%20%20%20namespace%20%7B%5Cn%20%20%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20%20%20namespaceName%5Cn%20%20%20%20%7D%5Cn%20%20%20%20author%20%7B%5Cn%20%20%20%20%20%20%20%20username%5Cn%20%20%20%20%20%20%20%20avatarURL%5Cn%20%20%20%20%7D%5Cn%20%20%20%20name%5Cn%20%20%20%20description%5Cn%20%20%20%20createdAt%5Cn%20%20%20%20updatedAt%5Cn%20%20%20%20url%5Cn%20%20%20%20changesets%20%7B%5Cn%20%20%20%20%20%20%20%20nodes%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20%20%20%20%20%20%20title%5Cn%20%20%20%20%20%20%20%20%20%20%20%20body%5Cn%20%20%20%20%20%20%20%20%20%20%20%20state%5Cn%20%20%20%20%20%20%20%20%20%20%20%20reviewState%5Cn%20%20%20%20%20%20%20%20%20%20%20%20repository%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20externalURL%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20createdAt%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%20%20%23%20TODO%20move%20to%20separate%20query%20and%20configure%20from%2Fto%5Cn%20%20%20%20changesetCountsOverTime%20%7B%5Cn%20%20%20%20%20%20%20%20date%5Cn%20%20%20%20%20%20%20%20merged%5Cn%20%20%20%20%20%20%20%20closed%5Cn%20%20%20%20%20%20%20%20openApproved%5Cn%20%20%20%20%20%20%20%20openChangesRequested%5Cn%20%20%20%20%20%20%20%20openPending%5Cn%20%20%20%20%7D%5Cn%7D%5Cn%5Cn%20%20%20%20%20%20%20%20%22%2C%22operationName%22%3A%22CampaignByID%22%2C%22variables%22%3A%22%7B%5C%22campaign%5C%22%3A%20%5C%22Q2FtcGFpZ246MQ%3D%3D%5C%22%7D%22%7D)
Replace `campaignID` by an existing ID, or use my [DB dump](https://sourcegraph.slack.com/archives/GPF0CGQSK/p1571093169000100).

```graphql
query CampaignByID($campaign: ID!) {
    node(id: $campaign) {
        __typename
        ... on Campaign {
            ...CampaignFields
        }
    }
}

fragment CampaignFields on Campaign {
    id
    namespace {
        id
        namespaceName
    }
    author {
        username
        avatarURL
    }
    name
    description
    createdAt
    updatedAt
    url
    changesets {
        nodes {
            id
            title
            body
            state
            reviewState
            repository {
                name
                url
            }
            externalURL {
                url
            }
            createdAt
        }
    }
    # TODO move to separate query and configure from/to
    changesetCountsOverTime {
        date
        merged
        closed
        openApproved
        openChangesRequested
        openPending
    }
}
```

### PR DESCRIPTION
**Pull request by mrnugget**
This fixes #6011.

The panic in the bug report was caused by `len(cs)` being `0` and
trying to access `cs[:-1]`, leading to an index-out-of-range panic.

This happens only when `Limit` has been set to `-1` before (it's
incremented to `0` in the function that constructs the query) to list
all changeset events and the query resulting in an empty result set.

### CODE REVIEW

File: enterprise/pkg/a8n/store.go [hunk 1]
```diff
@@ -522,7 +522,7 @@ func (s *Store) ListChangesetEvents(ctx context.Context, opts ListChangesetEvent
 		return int64(c.ID), 1, err
 	})
 
-	if len(cs) == opts.Limit {
+	if opts.Limit != 0 && len(cs) == opts.Limit {
```
Comment (tsenart) [inline enterprise/pkg/a8n/store.go]: Can we apply this same fix to the other store `ListXXX` methods?

Comment (mrnugget) [reply enterprise/pkg/a8n/store.go]: We don't support the `Limit: -1` feature there yet and in the scope of this fix, I didn't want to port the feature.
