### PR TITLE
Fixing repo-updater sync alerts

### LINKED ISSUE #20911: Repo-updater Sync Jobs - Inaccurate Alert - Grafana/Prometheus Metrics Out Of Sync
- **Sourcegraph version:** v3.26.0 
- **Platform information:** This is an issue in standard Kubernetes SG deployments, and possibly other deployments. 

#### Steps to reproduce:

1. Observe the following alerts:
```
repo-updater: less than 0 repositories synced for 9h0m0s
repo-updater: less than 0 sync was started for 9h0m0s
```
2. Run the following query in `pgsql` to verify that sync jobs are being scheduled:
```sql
select
  ej.external_service_id, es.display_name, state, num_failures,
  started_at, finished_at, log_contents, execution_logs
from external_service_sync_jobs ej
join external_services es on es.id = ej.external_service_id
order by finished_at desc
limit 10;
```
#### Expected behavior: 
The following warnings should fire after 9 hours of the `repo-updater` not scheduling new synch jobs for the gitserver:
```
repo-updater: less than 0 repositories synced for 9h0m0s
repo-updater: less than 0 sync was started for 9h0m0s
```

These alerts are associated to the `Sync was started` and `Repositories Synced` charts.

Running the grafana query `sum by (state)(rate(src_repoupdater_syncer_synced_repos_total[1m]))` in Sourcegraph clouds monitoring suite we observe expected behavior:
Screen Shot 2021-05-12 at 9 41 45 AM

#### Actual behavior:
These warnings are firing despite the `repo-updater` scheduling sync jobs in both dogfood, and user instances.

The same grafana query from above `sum by (state)(rate(src_repoupdater_syncer_synced_repos_total[1m]))` in our internal dogfood Sourcegraph (note the 0 values for all state columns, frequent rollouts prevent alerts from firing in our dogfood instance, which may have allowed this to go undetected):
Screen Shot 2021-05-12 at 9 47 25 AM

Cross-referencing this with our internal metrics reveals that syncs are indeed being scheduled and occuring:
Screen Shot 2021-05-12 at 9 54 29 AM

The grafana charts appear to be out of sync with the actual behavior of the `repo-updater` hence flagging this as a bug.

Metric [code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1f755b97b5e6fc0b222478b5307270a1f53473f7/-/blob/internal/repos/syncer.go#L835-852) for reference.

### PR DESCRIPTION
**Pull request by varsanojidan**
Fixes #20911

The previous query would return back that it isnt performing a sync if any of the 4 sync states were reporting 0, therefore the alert would be fired even if there are syncs happening.

image

image

Fix:
image

## Test plan

Ran the updated query against my local environment.

### CODE REVIEW

File: monitoring/definitions/repo_updater.go [hunk 1]
```diff
@@ -112,7 +112,7 @@ func RepoUpdater() *monitoring.Container {
 						{
 							Name:        "syncer_synced_repos",
 							Description: "repositories synced",
-							Query:       `max by (state) (rate(src_repoupdater_syncer_synced_repos_total[1m]))`,
+							Query:       `max(max by (state) (rate(src_repoupdater_syncer_synced_repos_total[1m])))`,
```
Comment (bobheadxi) [inline monitoring/definitions/repo_updater.go:115]: isn't this already handled by the alert aggregator on line 117?

Comment (varsanojidan) [reply monitoring/definitions/repo_updater.go:115]: From my understanding the query before the changes ends up being:

`max((max by (state) (rate(src_repoupdater_syncer_synced_repos_total[1m])))<= 0)
`

Im trying to change it to:

`max(max(max by (state) (rate(src_repoupdater_syncer_synced_repos_total[1m])))<= 0)
`

the reason for this was because the max by state would evaluate to 4 different maxes for the 4 different states (added, deleted, modified, unmodified). If one of these 4 states evaluated to 0, the <=0 would return true for that states, and the max surrounding it would evaluate that as no sync happening, when in reality it may only be 1 of the 4 states that isnt currently happening.

By wrapping the max around the max by state it would change the <=0 to only evaluate to true when all 4 of the states are reporting 0.

Though I'm still quite new here so maybe I missed something 😅

Comment (bobheadxi) [reply monitoring/definitions/repo_updater.go:115]: No, I think your desired behaviour is correct, the question was more "shouldn't `AggregateBy(monitoring.AggregatorMax)` give Idan the behaviour he wants?

I wonder if the correct patch is to have the generator create:

```diff
- max((max by (state) (rate(src_repoupdater_syncer_synced_repos_total[1m])))<= 0)
+ max((max by (state) (rate(src_repoupdater_syncer_synced_repos_total[1m])))) <= 0
```

This appears to have the same behaviour as the query you are trying to create:

image

Comment (bobheadxi) [reply monitoring/definitions/repo_updater.go:115]: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/monitoring/monitoring/monitoring.go?L298%3A1-300%3A56=

Comment (bobheadxi) [reply monitoring/definitions/repo_updater.go:115]: The rule is `alertQuery must contribute a query that returns true when it should be firing.`. If we take a single max of the `query`, and check if the overall max returns a true on exceeding the threshold, is that the better behaviour here?

Comment (varsanojidan) [reply monitoring/definitions/repo_updater.go:115]: Ahh I think I see what you mean, I totally agree it would be a lot nicer to be able to cut out the extra surrounding max() in the query because it doesn't technically do anything but from my understanding  of the design (feel free to correct me if wrong) of how the query is assembled, it doesn't let you leave the comparator outside of the aggregate (i.e. <=0 is inside of the aggregate max)

image

So if my understanding is correct, I don't think you can get the desired query:
max((max by (state) (rate(src_repoupdater_syncer_synced_repos_total[1m])))) <= 0
with the way the generator is structured.

Comment (bobheadxi) [reply monitoring/definitions/repo_updater.go:115]: I think we should change it, I feel like the current implementation isn't correct, though this might require a closer look. Something like:

```diff
-					alertQuery := fmt.Sprintf("%s((%s) %s %v)",
+					alertQuery := fmt.Sprintf("%s((%s)) %s %v",
						a.aggregator, o.Query, a.comparator, a.threshold)
```

Comment (varsanojidan) [reply monitoring/definitions/repo_updater.go:115]: I agree I think the queries make a lot more sense like that, my only concern would be breaking a lot of other queries that were written around the previous query format and may not work the same with the new formatting

Comment (bobheadxi) [reply monitoring/definitions/repo_updater.go:115]: Hmm okay, nevermind 😁 After toying around with this I think the original intention is, indeed, to have alerts fire if _any_ series goes off. e.g. if you create an alert on CPU usage per instance, if any of the instances meet the threshold we _should_ fire an alert, so the behaviour is right here and you probably do want to change the metric here

**Review by bobheadxi — APPROVED** [review]

File: monitoring/definitions/repo_updater.go (hunk 1 above)
Comment (bobheadxi) [reply monitoring/definitions/repo_updater.go:115]: Sorry for the confusion!

Comment (varsanojidan) [reply monitoring/definitions/repo_updater.go:115]: No worries learning a lot from these discussions, appreciate all the feedback, thanks Robert!
