### PR TITLE
insights: Fix pagination for insights in GetAll

### LINKED ISSUE #29576: insights: insightViews query pagination doesn't return the correct number of results
When providing a `first:` argument into the `insightViews` query, seemingly incorrect results return:

``` gql
query insightviews {
  insightViews (first:1) {
    nodes {
      id
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
```
``` json
{
  "data": {
    "insightViews": {
      "nodes": [],
      "pageInfo": {
        "hasNextPage": false,
        "endCursor": null
      }
    }
  }
} 
```

This doesn't work for both `first:1` and `first:2`, but starts working after `frist:3`, but returns the wrong count:
``` gql
query insightviews {
  insightViews (first:3) {
    nodes {
      id
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
```
``` json
{
  "data": {
    "insightViews": {
      "nodes": [
        {
          "id": "aW5zaWdodF92aWV3OiIyMkVIR2pXOTFkSzNOanpmM2hyWnU3WDJwMlgi"
        }
      ],
      "pageInfo": {
        "hasNextPage": true,
        "endCursor": "aW5zaWdodF92aWV3OiIyMkVIR2pXOTFkSzNOanpmM2hyWnU3WDJwMlgi"
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by CristinaBirkel**
Closes #29576

## Description
I believe there were a few issues here:
- The `LIMIT` clause in the query was limiting results before filtering by permissions. This resulted in fewer results than expected, depending on ordering and permissions.
- The issue with simply moving the `LIMIT` clause to the end was that this query is returning `insight_series`, not `insight_views`, so it would have limited the wrong thing there as well. So what I did was to first select `insight_views`, and then join with the other tables necessary to return all the columns we wanted.
- The `pageInfo` wasn't working well for the last page because it returned a cursor whenever there were results.
- `GroupByView` was ordering by id instead of unique_id as well, which needs to be consistent for this to work.

Ideally I would like to refactor this more, but given the scope of the bug as I did what felt like the minimum viable change.

## Testing Steps
- I tested this out via the API. I made sure to include a lot of "permissions gaps" in the data, (lots of insights my user doesn't have permissions to view locally,) and then tested the paginated results against what I expected.
- Also added some unit tests for `GetAll` which focus on pagination

Let me know if you see anything unexpected! I am a bit concerned modifying this complex query, but it all seems to be working from what I tested.

### CODE REVIEW

File: enterprise/internal/insights/store/insight_store.go [hunk 1]
```diff
@@ -866,16 +870,23 @@ SELECT iv.id, 0 as dashboard_insight_id, iv.unique_id, iv.title, iv.description,
        i.next_recording_after, i.backfill_queued_at, i.last_snapshot_at, i.next_snapshot_after, i.repositories,
        i.sample_interval_unit, i.sample_interval_value, iv.default_filter_include_repo_regex, iv.default_filter_exclude_repo_regex,
 	   iv.other_threshold, iv.presentation_type, i.generated_from_capture_groups, i.just_in_time, i.generation_method
-FROM (%s) iv
+FROM insight_view iv
```
Comment (coury-clark) [inline enterprise/internal/insights/store/insight_store.go:873]: I fear this query is getting difficult to understand (or already was, since this bug existed). I wonder if we should reconsider how this data is loaded and instead of trying to load all of the series at the same time, separate that into two different queries. Load all of the views, then load all of the series and map those back to the views. This still doesn't become n+1, just one additional round trip.

In pseudocode:
``` pseudocode
select * from insight view where visible;
```

``` pseudocode
select * from insight_view_series
join insight_series
 where insight_view_id in (from above)
```

File: enterprise/internal/insights/resolvers/insight_view_resolvers.go [hunk 2]
```diff
@@ -789,7 +789,7 @@ func (r *InsightViewQueryConnectionResolver) computeViews(ctx context.Context) (
 
 		r.views = r.insightStore.GroupByView(ctx, viewSeries)
 
-		if len(r.views) > 0 {
+		if len(r.views) > 0 && len(r.views) == args.Limit {
```
Comment (coury-clark) [inline enterprise/internal/insights/resolvers/insight_view_resolvers.go:792]: We can actually get a more accurate version of this by selecting `limit+1` from the DB. If we get back `len() == limit+1` then we have another page, otherwise this is the last page. It's up to you if you want to implement that.

File: enterprise/internal/insights/store/insight_store.go [hunk 3]
```diff
@@ -96,33 +96,37 @@ func (s *InsightStore) Get(ctx context.Context, args InsightQueryArgs) ([]types.
...
 	if len(args.UniqueID) > 0 {
-		viewConditions = append(viewConditions, sqlf.Sprintf("unique_id = %s", args.UniqueID))
+		preds = append(preds, sqlf.Sprintf("iv.unique_id = %s", args.UniqueID))
 	}
 	if args.DashboardID > 0 {
-		viewConditions = append(viewConditions, sqlf.Sprintf("id in (select insight_view_id from dashboard_insight_view where dashboard_id = %s)", args.DashboardID))
+		preds = append(preds, sqlf.Sprintf("iv.id in (select insight_view_id from dashboard_insight_view where dashboard_id = %s)", args.DashboardID))
+	}
+	if args.After != "" {
+		preds = append(preds, sqlf.Sprintf("iv.unique_id > %s", args.After))
```
Comment (coury-clark) [inline enterprise/internal/insights/store/insight_store.go:116]: Technically we have another bug here in that if a `unique_id` were to be inserted that falls lexigraphically before `After` we would never iterate over it. Maybe that is more of a reason to consider refactoring this to a 2 phase load, and page over `id`. No need for you to fix this, it's not related to your PR - just an observation for us to figure out what to do next.

**Review by coury-clark — APPROVED** [review]

File: enterprise/internal/insights/store/insight_store.go (hunk 1 above)
Comment (CristinaBirkel) [reply enterprise/internal/insights/store/insight_store.go:873]: I agree in general. I'm not sure it's worth refactoring it in this PR, but I'm going to work on creating some refactoring tickets and I will keep this in mind there.

File: enterprise/internal/insights/resolvers/insight_view_resolvers.go (hunk 2 above)
Comment (CristinaBirkel) [reply enterprise/internal/insights/resolvers/insight_view_resolvers.go:792]: Good point, this seems pretty simple to do actually and I'll add that in!

File: enterprise/internal/insights/store/insight_store.go (hunk 3 above)
Comment (CristinaBirkel) [reply enterprise/internal/insights/store/insight_store.go:116]: Yeah I went down the path of changing everything to be ordering by `id` and using `id` as the cursor and all that comes with it, but I think it started to spiral out a bit farther than I wanted to do with this bug fix. But I agree that it definitely makes more sense to use `id`. I'm going to open a refactoring issue (unless one already exists?) to remove `unique_id` in general because I think we both agreed that it's redundant now, and I believe it will clean things up significantly.

File: enterprise/internal/insights/store/insight_store.go (hunk 1 above)
Comment (coury-clark) [reply enterprise/internal/insights/store/insight_store.go:873]: Sounds reasonable to me!

File: enterprise/internal/insights/store/insight_store.go (hunk 3 above)
Comment (coury-clark) [reply enterprise/internal/insights/store/insight_store.go:116]: Yeah sounds good, lets attach this to the other refactor ticket above.

File: enterprise/internal/insights/store/insight_store.go [hunk 4]
```diff
@@ -867,23 +899,33 @@ from insight_series
 WHERE %s
 `
 
-const getInsightsVisibleToUserSql = `
+const getInsightIdsVisibleToUserSql = `
+SELECT DISTINCT iv.unique_id
+FROM insight_view iv
+JOIN insight_view_series ivs ON iv.id = ivs.insight_view_id
```
Comment (coury-clark) [inline enterprise/internal/insights/store/insight_store.go:905]: Maybe I'm missing something - but my impression is that this query would only select from `insight_view` (filtering for permissions) with limit. With this join here, how can we expect to page across this list in order - doesn't this pose the same challenge as the previous version?

I also don't follow, because the next query below does the same join.

Comment (CristinaBirkel) [reply enterprise/internal/insights/store/insight_store.go:905]: Hmm, let me know if it's not working for you, but I think it's ordering by `iv.unique_id` then limiting based on that. The joins are needed just for the `AND %s` part on line 912 because it could contain `i.deleted_at IS NULL`. Does that make sense?

Comment (coury-clark) [reply enterprise/internal/insights/store/insight_store.go:905]: Ah - I didn't notice the `DISTINCT` clause. So a few thoughts:

I hate to worry about performance at the moment, but I think this is just a situation where we are probably writing a query to do more work than is necessary. Just a quick comparison of the query plans of a simplified version of this shows roughly 3x cost for a distinct query (which isn't terribly surprising, it's not very efficient in Postgres).

[Here are some notes from this test](https://sourcegraph.slite.com/api/s/note/FPVcI_1Cjhu44k2WFd1fRH/Insight-View-paging-test)


My next question would be - do we actually need to filter out views by deleted series? I realize our API has some not-null constraints around return types, but are those liable to be violated here?

Comment (CristinaBirkel) [reply enterprise/internal/insights/store/insight_store.go:905]: This method basically returns series rather than views. I think if we don't filter out views with 0 series, we could end up with a case where:
1. The first query (to get the view ids) returns 5 views. Two of those don't have any series attached. (Or rather, have deleted series.) 
2. The second query won't return those views because they don't have any series. So you'll only get 3 results.

Not sure we'll ever end up with views without series? We may have a small bug actually with the `createLineChartSearchInsight` mutation.. looks like if I pass in `[]` for series it comes back with a SQL error instead of a helpful error message. Same with the update. I'll create an issue for that. But yeah I think if there will never be a case where a view doesn't have at least one series we should be okay. Otherwise I would be worried about returning the wrong number of results in rare cases. What do you think?

**Review by coury-clark — APPROVED** [review]
