### PR TITLE
Don't add an extra slash in toAbsoluteBlobURL()

### LINKED ISSUE #2673: Double forward slash in Find references link in the Browser Extensions
#### Steps to reproduce:

1. Hover a function with the browser extension activated
2. The link generated contains 2 forward slashes after the domain name ( https://sourcegraph.com//github.com/sourcegraph/sourcegraph@5b9362940c84ca79c2ca277b9b1d5bbbccb47d3b/-/blob/shared/src/util/url.ts#L455:17&tab=references )

It works on the sourcegraph server but not on my own as the official sourcegraph server probably rewrites the URL to ignore the duplicate slash.

The issue is that we concatenate two '/' in the toAbsoluteBlobURL function, as the toPrettyBlobURL always returns a string begining with a '/' : https://github.com/sourcegraph/sourcegraph/blob/5b9362940c84ca79c2ca277b9b1d5bbbccb47d3b/client/browser/src/shared/util/url.tsx#L18
and 
https://github.com/sourcegraph/sourcegraph/blob/5b9362940c84ca79c2ca277b9b1d5bbbccb47d3b/shared/src/util/url.ts#L458

#### Expected behavior:
Have a valid URL (https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5b9362940c84ca79c2ca277b9b1d5bbbccb47d3b/-/blob/shared/src/util/url.ts#L455:17&tab=references)

#### Actual behavior:
The link is invalid and sourcegraph doesnt find the file.

### PR DESCRIPTION
**Pull request by lguychard**
Fixes #2673 

##### Code Hosts

- [x] GitHub
- [ ] GitHub Enterprise
- [ ] Refined GitHub
- [ ] Phabricator
- [ ] Phabricator integration
- [ ] Bitbucket
- [ ] Gitlab

##### Browsers

- [x] Chrome
- [ ] Firefox

### CODE REVIEW

File: client/browser/src/shared/util/url.ts [hunk 1]
```diff
@@ -12,8 +12,11 @@ import { repoUrlCache, sourcegraphUrl } from './context'
...
-    ctx: RepoSpec & RevSpec & FileSpec & Partial<PositionSpec> & Partial<ViewStateSpec>
+    ctx: RepoSpec & RevSpec & FileSpec & Partial<PositionSpec> & Partial<ViewStateSpec>,
+    cache = repoUrlCache
 ): string {
-    const url = repoUrlCache[ctx.repoName] || sourcegraphUrl
-    return `${url.replace(/\/$/, '')}/${toPrettyBlobURL(ctx)}`
+    const url = cache[ctx.repoName] || sourcegraphUrl
+    // toPrettyBlobURL() always returns an URL starting with a forward slash,
+    // no need to add one here
+    return `${url.replace(/\/$/, '')}${toPrettyBlobURL(ctx)}`
```
Comment (chrismwendt) [inline client/browser/src/shared/util/url.ts]: `path.join()` might work nicely here.
