### PR TITLE
a8n: support creating campaign plans from API only, not UI

### LINKED ISSUE #6627: automation should not construct searchResolver itself
automation is currently constructing the search resolver itself in the GraphQL package:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@676a10a3370362d070f6bf3fea83c40c8de88652/-/blob/cmd/frontend/graphqlbackend/search.go#L773-798

This is brittle because it is only used by a8n and bypasses all of the other logic we execute before initializing a search resolver for regular GraphQL search queries:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@676a10a/-/blob/cmd/frontend/graphqlbackend/search.go#L77-125

I suggest you modify `SearchRepos` to call into `(&schemaResolver).Search(...)` because:

- It is easy for someone to add code to `(*schemaResolver).Search` that would break `SearchRepos` today.
- By not reusing `(*schemaResolver).Search`, it would be harder to adopt paginated search in a8n in the future.
- You are currently missing out on proper defaults like literal search and validation of your search queries due to this.

@mrnugget I am assigning you but unsure if you are the right owner, feel free to reassign

### LINKED ISSUE #7112: Add campaign form UI instead of Monaco editor
Having to double-escape regexps in the JSON is a big UX problem.
In addition, providing real inputs opens the door for reusing our search autocompletion.

Investigate generating the form from JSON schema.

- [ ] Update docs (https://docs.sourcegraph.com/user/automation) to mention the new UI instead of the JSON schema for campaign types

### LINKED ISSUE #7279: a8n: Backend stuck on npm campaign creation
- **Sourcegraph version:** 3.11, master
- **Platform information:** Local Enterprise Dev, macOS Catalina

#### Steps to reproduce:

1. Create a new campaign, input
	```json
	{
	    "scopeQuery": "repo:github.com/sourcegraph/automation-testing",
	    "matchers": [{ "type": "npm" }]
	}
	```
2. Create preview
3. Hit "Create"
4. Wait forever

#### Expected behavior:
It finishes at some point creating the PR on GH.com

#### Actual behavior:
It never finishes, and the backend seems to be busy, not creating any other previews and so forth either, this could only be solved by restarting the server

### LINKED ISSUE #7558: a8n: Upgrading Guava in a Gradle project
From [RFC 36](https://docs.google.com/document/d/1DKWy2zC6_rDZzoPS7ASUpvnVDK3Zj6cf_I9Riq9KNu0/edit)

Upgrading Guava in a Gradle project and rewriting call sites using Comby syntax

### LINKED ISSUE #7559: a8n: Campaign permission model
From [RFC 36](https://docs.google.com/document/d/1DKWy2zC6_rDZzoPS7ASUpvnVDK3Zj6cf_I9Riq9KNu0/edit)

See the [Permission Model](https://docs.google.com/document/d/1DKWy2zC6_rDZzoPS7ASUpvnVDK3Zj6cf_I9Riq9KNu0/edit#heading=h.vikdh9q69nm8) section in the above RFC

### LINKED ISSUE #7561: a8n: Support more than just NPM credentials
From [RFC 73](https://docs.google.com/document/d/143FIe1Tak4_YPPuOuEzuobTQW09ZU85WfOCdZkNwIVQ/edit#heading=h.b5eblutsndzz)

See the list of other possible credential types here:
https://docs.google.com/document/d/143FIe1Tak4_YPPuOuEzuobTQW09ZU85WfOCdZkNwIVQ/edit#bookmark=id.o2rmxw4xn7qp

### LINKED ISSUE #7562: a8n: Option to delete .npmrc files
From [RFC 73](https://docs.google.com/document/d/143FIe1Tak4_YPPuOuEzuobTQW09ZU85WfOCdZkNwIVQ/edit#heading=h.b5eblutsndzz)

Support deleting and gitignoring .npmrc files as an option instead of always just removing the portion that is a token.

### LINKED ISSUE #7563: a8n: Automatically revoke found credentials / tokens
From [RFC 73](https://docs.google.com/document/d/143FIe1Tak4_YPPuOuEzuobTQW09ZU85WfOCdZkNwIVQ/edit#heading=h.b5eblutsndzz)

A way to automatically revoke tokens that are found (similar to GitHub's token scanning for public repositories).

### LINKED ISSUE #7564: a8n: Report additional information about found tokens / credentials
From [RFC 73](https://docs.google.com/document/d/143FIe1Tak4_YPPuOuEzuobTQW09ZU85WfOCdZkNwIVQ/edit#heading=h.b5eblutsndzz)

A way to include additional information about the token in the changeset description, such as when the token was created, who created it, what its scope is, where it is used, etc. This information would be helpful to assess the severity of the leak.

### LINKED ISSUE #7566: a8n: Proactivley detect leaked tokens
From [RFC 73](https://docs.google.com/document/d/143FIe1Tak4_YPPuOuEzuobTQW09ZU85WfOCdZkNwIVQ/edit#heading=h.b5eblutsndzz)

A way to detect tokens proactively (e.g., pre-push).

### LINKED ISSUE #7725: a8n: Move "default branch" check to execution of CampaignJob
Current state when creating a new CampaignPlan ("Preview changes"):

* We open a transaction
* For each repo the `scopeQuery` yields we create a `CampaignJob`
* For each `CampaignJob` we ask `gitserver` for its default branch
* If `gitserver` cannot determine a default branch the transaction is rolled back
* Otherwise: transaction is committed

[Here is the code](https://github.com/sourcegraph/sourcegraph/blob/9c41958efbd5ba9bb43c426137d219e935d6ce23/enterprise/internal/a8n/runner.go#L158-L213).

That means the transaction is open for the duration of time it takes to
ask `gitserver` for _all_ default branches.

That's not a problem per se, but it is bad UX since it might take a
while until the user sees _something_ after hitting the `"Preview
changes"` button.

I propose that we move the determination of a `CampaignJob`s `BaseRef`
and `Rev` out of the transaction and set those when actually running the
job [here](https://github.com/sourcegraph/sourcegraph/blob/9c41958efbd5ba9bb43c426137d219e935d6ce23/enterprise/internal/a8n/runner.go#L280-L283).

That would require making `rev` and `base_ref` nullable fields in the
database and since we have a database unique constraint on
`(campaign_plan_id, repo_id, rev)` we have to find out how that works
with `NULL` fields.

The upsides:

1. We don't hammer `gitserver` with possibly hundreds of requests in a tight loop
2. One request failing won't fail the whole `CampaignPlan` but instead result in a single errored `CampaignJob`
3. The user will get faster feedback when previewing changes because the transaction will be much faster since it's not bound to `gitserver` anymore

### LINKED ISSUE #7853: a8n/web: "Preview changes" button shifts layout to right and flickers spinner and is not disabled
The "Preview changes" button shifts the whole layout on click to the right, because it flickers a "spinner" for a split-second.

And, while the changes are computed async in the background, the button is also not disabled but could potentially be clicked.

See:

button_shift

### LINKED ISSUE #7861: Automation should never miss search results
In its current state Automation campaigns might miss search results because of the way it interacts with our search infrastructure. See [this comment chain](https://github.com/sourcegraph/sourcegraph/pull/7790#discussion_r367736633) for the full context. Below are a few excerpts

---

@rvantonder in https://github.com/sourcegraph/sourcegraph/pull/7790#discussion_r367736633:

> Here's a breakdown of things:
> 
> - for the repo question: this  (to me) is a problem where we don't have the possibility of two things at the same time: (1) a clean way to operate on a repo given we know what the repo is already and (2) a filtering mechanism to only run on certain files, or with certain constraints. The nice thing about replacer is that it actually solves (1) as far as the API is concerned: just give it the repo, it'll do the fetching, and it'll run comby on all the files (there is a way to filter files, but it is not _exactly_ the same as what we support in the query). But the point is there's no danger of fiddling with queries/escaping. The problem: the replacer interface is too rudimentary to understand/implement the full spectrum of our search query. The frontend/search interface (2) _does_ understand the full query and can perform the filtering mechanism (useful!) but the problem is that we need to mess around with the query to do that properly. I agree this is the best possible option right now, but there is another danger hidden in (2). Next point.
> 
> - Any time we ever call `newSearch`, we are never guaranteed to find all matches. For search/replace, it is imperative that we (a) always try our hardest to replace every instance (i.e., we will wait!) or (b) if we don't get everything, we need to know about what was missed. It would be great if there was a knob to say 'search and replace this, just guarantee me that you found every single instance', but there is a ton of search functionality across concerns (index/searcher/...) that make adding such a knob very very hard IMO, and it would be easier to build such a "guaranteed searcher" 'from scratch in replacer than try layer it onto search. The alternative is that we are cognizant of the limitations of search and monitor it when it tells us 'there were more results, but I didn't return them'. If we go this route, we will need to add a lot of (TBH probably annoying) logic that checks the state of returned results, refetches, and all that. I'm not even sure how we can guarantee that pans out, since search can skip repos _or_ files. It is brittle for this purpose brittle. Pagination gives me some hope that we can do finer accounting and do 'retry' operations in a much easier way (right now we'd have to do the accounting ourselves, somehow).
> 
> So we have bigger problems than that repo issue. Just for this regex campaign mode, I realized that since this is using searcher, partial results will return quickly, and so I basically will add `count:10000` with no real guarantee that all of the matches are covered. 
> 
> For example, when I create these campaigns locally:
> 
> ```
> {
>     "scopeQuery": "repo:github.com/sourcegraph/sourcegraph file:.*",
>     "regexMatch": "func",
>     "textReplace": "foo"
> }
> ```
> 
> will have 1048 matches (and returns quickly) while
> 
> ```
> {
>     "scopeQuery": "repo:github.com/sourcegraph/sourcegraph file:.* count:10000",
>     "regexMatch": "func",
>     "textReplace": "foo"
> }
> ```
> 
> will have 10647.
> 
> But there's an even bigger problem than the number of matches getting cut off by `count` or `timer`: it is that when we filter using, e.g., `file`, the list of files can _also_ be cut off. So for example, the query
> 
> ```
> {
>     "scopeQuery": "repo:github.com/torvalds/linux index:no file:.* count:10000",
>     "regexMatch": "TODO",
>     "textReplace": "DONE"
> }
> ```
> 
> on my machine will return only 15 matches. That's because we return some number of files (I think 1000 and `count` doesn't appear to do anything) and there are only 15 matches in those files. If I want to force search to try harder, I actually have to use the `regexMatch` value in the `scopeQuery`:
> 
> ```
> {
>     "scopeQuery": "repo:github.com/torvalds/linux TODO index:no file:.* count:10000",
>     "regexMatch": "TODO",
>     "textReplace": "yo"
> }
> ```
> 
> This finds 1776 matches. Does this find all the matches? _I still don't know_ and that's the problem. Long term we'll have to think about how to either rearchitect search code or queries to handle this issue, or build up a dedicated replacer service. There's contention in designing for 'time-to-first-result' and 'match-and-replace-all-instances-at-almost-any-cost'.

---

@rvantonder in https://github.com/sourcegraph/sourcegraph/pull/7790#discussion_r367868835:

> To be clear, what I mean is that we need to do (possibly significant) extra work compared to what the current search code is geared towards, not that it's at odds.
> 
> @keegancsmith probably has better insight, but my gut reaction is that using indexed search results/Zoekt is a no go. It is a black box and takes lots of shortcuts in ways that's hard to guarantee that it returns all matches, whether content or files (issue in #7709 may be indicative). Which implies using searcher logic. But searcher doesn't do repo filtering, that happens in the frontend. So there is an interface to cut out here.

---

@mrnugget in https://github.com/sourcegraph/sourcegraph/pull/7790#discussion_r367877914:

> There's two problems we have to address:
> 
>   1. We need to reliably come up with a list of repositories over which to run Automation campaigns.
>   2. We need to find every search result in each one of these repositories.
> 
> With our current state of campaign types and our roadmpa, I think (1) is already (or can be made) reliable by restricting scopeQuery to only accept repo:. That should always give us the full list of repositories that match the scopeQuery.
> 
> The problem is that once you do that, you start to come up with a lot of false positives. Example: you run a NPM credentials campaign with "scopeQuery": "repo:github". That returns 200 repos, but only 3 of those have an .npmrc file. So I decided to add file:.npmrc to the scopeQuery. Problem is that, apparently, we're now not reliable anymore without adding count:99999 to it. For regex-search-replace the problem is even bigger, because it can yield more hits.
> 
> Problem (2) is what we're discussing this in this comment chain and now becomes more important with regex-search-and-replace and future campaigns that will run in the background and proactively scan/search repositories.
> 
> I hope that we, builders of code search, can up with a way that allows us to make use of the search infrastructure we already have in a reliable way 😄
> 
>  [... comment by @rvantonder ...]
> 
> This comment combined with your earlier comment makes me think again of the idea of combining searcher/replacer into a single service with added "run code over git repo" functionality.

### LINKED ISSUE #8003: `scopeQuery` does not filter down repository results
Reported by https://app.hubspot.com/contacts/2762526/contact/17877751 that the `scopeQuery` for a8n campaigns was not matching the number of search results when using `repohasfile` filter.

[Slack thread](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1579711776061700) notes:
> Ohh, boy. I think I've got it: I need to call `.Results()` again on the `results` here: https://github.com/sourcegraph/sourcegraph/blob/11b5ebbe3458c01d9d35a766fbfa4b07b3472be6/cmd/frontend/graphqlbackend/search.go#L756-L760

### LINKED ISSUE #8004: Support running campaigns on > 200 repositories
Customers who ran into issues with this: 
- https://app.hubspot.com/contacts/2762526/contact/17877751
- https://app.hubspot.com/contacts/2762526/company/608245740

I couldn't find where we are tracking this functionality - perhaps it is implicit with the introduction of the CLI as the main way to create campaigns, but I'd like to ensure we're watching and addressing this.

### PR DESCRIPTION
**Pull request by sqs**
Based on customer feedback, we are focusing on campaigns that require running external tools (such as a code formatter, linter, and/or package manager) to produce the diff, instead of the simple regexp/comby campaigns that Sourcegraph could run from the web UI. The `src` CLI will expose strictly more customizability to campaign authors.

This was discussed on Slack in https://sourcegraph.slack.com/archives/CMMTWQQ49/p1579746146079200. Summary: very few customer problems can be solved by regexp/comby alone; it is also almost always necessary to run a code formatter, package manager, etc., to ensure the diff is correct. The new `src actions exec` subcommand in https://github.com/sourcegraph/src-cli/pull/80 will support creating campaigns whose diffs come from any external tools. We want to focus on the CLI-first workflow for creating campaigns (which solves customer problems much better), and not have a confusing alternative way of creating some campaigns in the web UI.

(We plan to support running external tools on Sourcegraph itself in the future, which means we can bring back the web UI that exposes complete power for creating campaigns. But we don't have that capability yet in just the web UI.)

Closes many issues related to features that we were planning to expose in the web UI. These features will still (mostly) be planned in the future, but only after we support them in the `src` CLI.

- closes #8003
- closes #7861
- closes #7853
- closes #7279
- closes #8004
- closes #7725
- closes #7566
- closes #7561
- closes #7562
- closes #7563
- closes #7564
- closes #7558
- closes #7559
- closes #7112
- closes #6627

### CODE REVIEW

File: enterprise/internal/a8n/runner.go [hunk 1]
```diff
@@ -2,62 +2,32 @@ package a8n
...
 
-// ErrTooManyResults is returned by the Runner's CreatePlanAndJobs method when the
-// CampaignType's searchQuery produced more than maxRepositories number of
-// repositories.
-var ErrTooManyResults = errors.New("search yielded too many results. You can narrow down results using `scopeQuery`")
-
-// A Runner executes a CampaignPlan by creating and persisting CampaignJobs
-// according to the CampaignPlan's Arguments and CampaignType.
+// A Runner executes a CampaignPlan.
 type Runner struct {
```
Comment (mrnugget) [inline enterprise/internal/a8n/runner.go]: We don't need a `Runner` anymore if we remove everything else, I think

**Comment by sqs** [comment]
@mrnugget Thanks for that list of issues. I added them all to this PR so they are closed upon merging.

**Comment by sqs** [comment]
@eseliger @felixfbecker Can one of you please review and approve this? Thank you!
