### PR TITLE
Fix error handling

### LINKED ISSUE #7599: Browser extension silently breaks instead of saying "repo not on your sourcegraph instance"
I observed a user try to use the browser extension on some private repositories they had not added to their Sourcegraph instance yet. Instead of being told anything, the browser extension just "did not work" and it was not clear at all why.

If we can make requests to the instance but the repository doesn't exist, we should probably indicate that to users?

### LINKED ISSUE #9411: "Clone in progress" errors are not properly handled
The function `retryWhenCloneInProgressError()`, for example used by the "open on Sourcegraph" button, does not properly detect the error if it comes from the background page (which is always the case in the browser extension).

This surfaced because I recently changed the button to show errors instead of swallowing them:

Screen Shot 2020-03-28 at 17 37 00

It happens because it checks for the error's `code`, but that is not cloned through the page boundary, see https://github.com/mozilla/webextension-polyfill/issues/210.
For a workaround, we can check the error message like we do for `HTTPStatusError`. This bug applies to _all_ errors.

### PR DESCRIPTION
**Pull request by felixfbecker**
Fixes #9411, fixes #7599

Until #9693 and #9697 are fixed we unfortunately have no alternative than to assert error message strings.

I overhauled the "Open on Sourcegraph" logic, and decided to link to the integration docs if we can't open the options menu (in native integrations). In the case where the repo is simply not found (but not because it is private + instance is sourcegraph.com), I show that in the button but still link to the repo on the instance, where it will get the 404 page that could have more instructions or a button to configure external services depending on the site admin status of the user etc.

Example:

image

### CODE REVIEW

File: browser/src/shared/backend/server.ts [hunk 1]
```diff
@@ -19,8 +19,5 @@ export const fetchSite = (requestGraphQL: PlatformContext['requestGraphQL']): Ob
         mightContainPrivateInfo: false,
     }).pipe(
         map(dataOrThrowErrors),
-        map(
-            ({ site }) => site,
-            catchError((err, caught) => caught)
```
Comment (felixfbecker) [inline browser/src/shared/backend/server.ts:24]: Note how this passed an operator as the `thisArg` to `map`...

File: web/src/repo/index.tsx [hunk 2]
```diff
@@ -6,7 +6,6 @@ export function redirectToExternalHost(externalRedirectURL: string): void {
     const redirectURL = new URL(window.location.href)
     // Preserve the path of the current URL and redirect to the repo on the external host.
     redirectURL.host = externalHostURL.host
-    redirectURL.port = externalHostURL.port
```
Comment (felixfbecker) [inline web/src/repo/index.tsx:9]: `host` already includes the `port`.

File: browser/src/libs/options/OptionsContainer.tsx [hunk 3]
```diff
@@ -86,10 +86,9 @@ export class OptionsContainer extends React.Component<OptionsContainerProps, Opt
                 if (isErrorLike(res)) {
                     this.setState({
                         status: 'error',
-                        connectionError:
-                            res.name === AUTH_REQUIRED_ERROR_NAME
```
Comment (felixfbecker) [inline browser/src/libs/options/OptionsContainer.tsx:90]: This error name was not "produced" anywhere.

File: browser/src/libs/code_intelligence/external_links.tsx [hunk 4]
```diff
@@ -74,14 +74,26 @@ export const ViewOnSourcegraphButton: React.FunctionComponent<ViewOnSourcegraphB
...
+        // user to configure Sourcegraph.
+        if (sourcegraphURL === DEFAULT_SOURCEGRAPH_URL && onConfigureSourcegraphClick) {
+            return (
+                <SourcegraphIconButton
+                    label="Configure Sourcegraph"
+                    title="Install Sourcegraph for search and code intelligence on private instance"
+                    ariaLabel="Install Sourcegraph for search and code intelligence on private instance"
+                    className={className}
+                    iconClassName={classNames('open-on-sourcegraph__icon--muted', iconClassName)}
+                    onClick={onConfigureSourcegraphClick}
```
[the remark this answers is not in the document]
Comment (felixfbecker) [reply browser/src/libs/code_intelligence/external_links.tsx]: This was actually wrong. I took another pass to overhaul the logic completely, and decided to link to the integration docs if we can't open the options menu (in native integrations). In the case where the repo is simply not found (but not because it is private + instance is sourcegraph.com), I show that in the button but still link to the repo on the instance, where it will get the 404 page that could have more instructions or a button to configure external services depending on the site admin status of the user etc.

**Comment by felixfbecker** [comment]
I wanted to give you the opportunity to object to the changes to under which conditions we show the button or link to the docs page 😄

File: browser/src/libs/code_intelligence/external_links.tsx [hunk 5]
```diff
@@ -39,65 +42,98 @@ export const ViewOnSourcegraphButton: React.FunctionComponent<ViewOnSourcegraphB
...
+                    title="Setup Sourcegraph for search and code intelligence on private repositories"
+                    ariaLabel="Setup Sourcegraph for search and code intelligence on private repositories"
+                />
+            )
+        }
+
+        // If there was an unexpected error, show it in the tooltip.
+        // Still link to the Sourcegraph instance in native integrations
+        // as that might explain the error (e.g. not reachable).
+        // In the browser extension, let the onConfigureSourcegraphClick handler can handle this.
```
Comment (lguychard) [inline browser/src/libs/code_intelligence/external_links.tsx:99]: Thanks for all the comments here!
