### PR TITLE
web: Fix hiding suggestions on search submit

### LINKED ISSUE #6748: Search autocomplete: lang selection persists even after specifying the language via keyboard
I expected that once I hit return in the search to specify the lang, that the language selection list would disappear.

ScreenFlow

### PR DESCRIPTION
**Pull request by hadrian-git**
- ~Wrap search input with `<form>` and hide suggestions on submit event~
- Hides suggestions on <kbd>Enter</kbd> `keydown` in search input

Fix #6748

### CODE REVIEW

File: web/src/search/input/QueryInput.tsx [hunk 1]
```diff
@@ -345,7 +346,7 @@ export class QueryInput extends React.Component<Props, State> {
                     const { onChange: downshiftChange, onKeyDown } = getInputProps()
                     return (
                         <div className="query-input2">
-                            <div ref={this.containerElement}>
+                            <Form onSubmit={this.onSubmit}>
```
Comment (felixfbecker) [inline web/src/search/input/QueryInput.tsx]: Shouldn't the form enclose the submit button too? Otherwise clicking the button and submitting with enter goes through different code paths

File: web/src/search/input/QueryInput.tsx [hunk 2]
```diff
@@ -245,7 +243,10 @@ export class QueryInput extends React.Component<Props, State> {
                 )
                 .subscribe(
                     state => {
-                        this.setState(state)
+                        this.setState({
+                            ...state,
+                            showSuggestions: true,
```
Comment (felixfbecker) [inline web/src/search/input/QueryInput.tsx]: So this is set to `true` based on prop updates, delayed by debouncing and fetching. `onSubmit` is triggered immediately on submission. How is the case prevented where `onSubmit` sets it to `false` but then the delayed handling here sets it to `true`?

File: web/src/search/input/QueryInput.tsx (hunk 1 above)
Comment (hadrian-git) [reply web/src/search/input/QueryInput.tsx]: The `onInputBlur` event should emit when the search button is clicked, but to improve the encapsulation and for any future handling of search submits, I've moved the search button into the `QueryInput` component (as all of `QueryInput`'s usage had `SearchButton` as its sibling).

File: web/src/search/input/QueryInput.tsx (hunk 2 above)
Comment (hadrian-git) [reply web/src/search/input/QueryInput.tsx]: I forgot to emit `this.suggestionsHidden.next()`. In the last commit it's now being emitted through `setShowSuggestions()`

File: web/src/search/input/QueryInput.tsx (hunk 1 above)
Comment (felixfbecker) [reply web/src/search/input/QueryInput.tsx]: Hmm that actually seems like it would be a problem very soon. We want to use the QueryInput in the campaigns UI to get autocompletion for search queries, but we don't want the search button there (nor the ability to submit the search at all)

Comment (hadrian-git) [reply web/src/search/input/QueryInput.tsx]: Would a `withSubmitButton` solve that issue?

Comment (felixfbecker) [reply web/src/search/input/QueryInput.tsx]: You also shouldn't be able to submit by submitting the form

Comment (hadrian-git) [reply web/src/search/input/QueryInput.tsx]: I edited the comment a bit late, what about a `withSubmit` prop? (default to `true`)

Comment (felixfbecker) [reply web/src/search/input/QueryInput.tsx]: I guess it would

Comment (hadrian-git) [reply web/src/search/input/QueryInput.tsx]: Added `withSubmit` prop in last commit

File: web/src/search/input/QueryInput.tsx [hunk 3]
```diff
@@ -100,6 +107,10 @@ const noSuggestions: State['suggestions'] = { values: [], cursorPosition: 0 }
 const typingDebounceTime = 300
 
 export class QueryInput extends React.Component<Props, State> {
+    public static defaultProps = {
```
Comment (felixfbecker) [inline web/src/search/input/QueryInput.tsx]: Does TypeScript handle this? (we don't use it anywhere else)

File: web/src/search/input/QueryInput.tsx [hunk 4]
```diff
@@ -428,12 +440,24 @@ export class QueryInput extends React.Component<Props, State> {
...
-        this.setState({ showSuggestions: true })
+        this.setShowSuggestions(true)
+    }
+
+    private onSubmit: React.FormEventHandler = event => {
+        this.setShowSuggestions(false)
+        if (!this.props.withSubmit) {
+            event.preventDefault()
+            event.stopPropagation()
+        }
```
Comment (felixfbecker) [inline web/src/search/input/QueryInput.tsx]: What was the motivation behind these lines? Seems like this would prevent submitting an outer form (e.g. campaign edit form) which would make it inconsistent with other normal inputs in that respective form

Comment (hadrian-git) [reply web/src/search/input/QueryInput.tsx]: I didn't understand the question. This is following the comments discussed at [this comment](https://github.com/sourcegraph/sourcegraph/pull/7076#discussion_r354994621). Are you asking specifically about the event method calls? (`preventDefault` and `stopPropagation`) or about the `withSubmit` prop?

Comment (felixfbecker) [reply web/src/search/input/QueryInput.tsx]: I'm asking about L457-460, i.e. the `if` block and its contents with the event handler calls. The `withSubmit` prop in general LGTM.

File: web/src/search/input/QueryInput.tsx (hunk 3 above)
Comment (hadrian-git) [reply web/src/search/input/QueryInput.tsx]: [Yes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#support-for-defaultprops-in-jsx), I declared the prop type incorrectly, and corrected in 25f11de

File: web/src/search/input/QueryInput.tsx (hunk 4 above)
Comment (hadrian-git) [reply web/src/search/input/QueryInput.tsx]: If I understood it correctly, you expect the submit functionality, but not with the `SubmitButton` showing?

Comment (felixfbecker) [reply web/src/search/input/QueryInput.tsx]: Depends on what you mean with "the submit functionality". I'd expect no _search submit_ functionality, i.e. no side effect triggered by **this component**. But I would still expect submit functionality for any _parent form_, which would currently be prevented by the `stopPropagation()`.
Now that I look closer, it's actually prevented already by only having the `Form` component in there, because it's impossible to have nested forms in HTML. Which means just hiding the Submit button with a prop is not enough unfortunately

Comment (hadrian-git) [reply web/src/search/input/QueryInput.tsx]: In that case just hiding the `SubmitButton`, should be enough, as even with the `Form` component, the event should bubble up and be available in parent components (that's how it works now, the `QueryInput` component doesn't handle the search, it just bubbles up the submit event.

Comment (hadrian-git) [reply web/src/search/input/QueryInput.tsx]: Updated in 1227686

Comment (felixfbecker) [reply web/src/search/input/QueryInput.tsx]: I don't think it would work. `form` elements are not nestable:

> Content model:
> Flow content, but with no form element descendants.

https://html.spec.whatwg.org/multipage/forms.html#the-form-element

Even if the bubbling happened to work I'd bet it breaks form validation and other stuff (a11y?).

Comment (felixfbecker) [reply web/src/search/input/QueryInput.tsx]: This bug has been open for a while though so we can merge and follow up. I was literally just asking a question what the motivation was :)

Comment (hadrian-git) [reply web/src/search/input/QueryInput.tsx]: Good point though. I reverted the changes and updated it to hide suggestion on 'Enter' in the search input. That should fix the bug without additional complexities for this PR.

File: web/src/search/input/QueryInput.tsx [hunk 5]
```diff
@@ -416,6 +419,10 @@ export class QueryInput extends React.Component<Props, State> {
         scrollIntoView(menuNode, node)
     }
 
+    private setShowSuggestions = (showSuggestions: boolean): void => {
+        this.setState({ showSuggestions }, () => !showSuggestions && this.suggestionsHidden.next())
```
Comment (felixfbecker) [inline web/src/search/input/QueryInput.tsx]: As an aside: Seems like `this.suggestionsHidden` is directly derived from `this.componentUpdates`. Removing it would eliminate the need for this method and avoid the case where no event is triggered because `setState()` was called directly.

In general though it would be even better if the subscribers of `suggestionsHidden` do not have to wait a render cycle to apply their effects (which then likely triggers another render cycle).

File: web/src/search/input/QueryInput.tsx [hunk 6]
```diff
@@ -426,14 +433,17 @@ export class QueryInput extends React.Component<Props, State> {
                 },
             })
         }
+        if (event.key === 'Enter') {
```
Comment (felixfbecker) [inline web/src/search/input/QueryInput.tsx]: It would still be better if it was handled by the form submit handler. This would not get triggered if someone uses a screen reader and a voice command to submit the form.

File: web/src/search/input/QueryInput.tsx (hunk 2 above)
Comment (felixfbecker) [reply web/src/search/input/QueryInput.tsx]: I can't quite follow how that avoids this case, could you explain?

File: web/src/search/input/QueryInput.tsx (hunk 5 above)
Comment (hadrian-git) [reply web/src/search/input/QueryInput.tsx]: I'll send a separate PR to refactor `QueryInput` after RFC14 features are done
