### PR TITLE
fix(ui): Traverse left-to-right also when finding line number in cell

### LINKED ISSUE #36253: Diff View frontend Crash when hovering over green area
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:
https://sourcegraph.slack.com/archives/C03BV5AKHL6/p1653931960223449
Observe video.

1.  Click[ this diff view](https://sourcegraph.com/github.com/sourcegraph/sourcegraph-code-discussions/-/commit/37873123e6fdf7706e6404f66d6a151e7d9a0cfa?visible=1#diff-b0678b51723ef8450026fa0f6967216fR22) and hover over green area
2. Notice crash in console and code intelligence stops working

#### Expected behavior:
no Crash

#### Actual behavior:

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

### PR DESCRIPTION
**Pull request by plibither8**
With this PR, the search for the cell containing the line-number also traverses left-to-right through the elements, relative to the hovered cell. The crash-causing bug happened when the cursor would hover over the left-most cells, to the left of the "add"/"green" lines. Since the original traversal was only right-to-left, no line number would be found to the left of the hovered cells, which would invoke the error.

Google Chrome 2022-06-09 at 23 26 33 000089@2x

Closes #36253

## Test plan

- Click [this diff view](https://sourcegraph.com/github.com/sourcegraph/sourcegraph-code-discussions/-/commit/37873123e6fdf7706e6404f66d6a151e7d9a0cfa?visible=1#diff-b0678b51723ef8450026fa0f6967216fR22) and hover over the green area marked by the rectangle in the above image
- No crash this time

## App preview:

- [Web](https://sg-web-mihir-diff-line-number-hover-bug.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-qmawzkkvhs.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

File: client/web/src/repo/compare/dom-functions.ts [hunk 1]
```diff
@@ -19,12 +19,20 @@ export const diffDomFunctions: DOMFunctions = {
...
     getLineNumberFromCodeElement: (codeCell: HTMLElement): number => {
-        let cell = codeCell.closest('td')!.previousElementSibling as HTMLTableCellElement
-        while (cell) {
-            if (cell.dataset.line) {
-                return parseInt(cell.dataset.line, 10)
+        const closestTd = codeCell.closest('td')
+        if (closestTd) {
+            // First search right-to-left for a line number using `previousElementSibling`
+            // If not found, search left-to-right for a line number using `nextElementSibling`
+            const siblings = ['previousElementSibling', 'nextElementSibling'] as const
```
Comment (jasongornall) [inline client/web/src/repo/compare/dom-functions.ts:26]: this feels fairly brittle we literally just try to grab next or previous dom nodes?

Comment (jasongornall) [reply client/web/src/repo/compare/dom-functions.ts:26]: I wonder if we can not do the hover flow at all if you are not on a line number.

Comment (jasongornall) [reply client/web/src/repo/compare/dom-functions.ts:26]: I would float this in #design or ask @taylorsperry for thoughts on the user experience. My thought is if you hover over a non number it should just not do anything. The act of hovering over an empty green scare causing UI elements to appear might cause confusion in the world of accessibility.

Comment (jasongornall) [reply client/web/src/repo/compare/dom-functions.ts:26]: Also don't [forget unit tests](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=LM-branchesTagsCommitsLabels&file=client%2Fbrowser%2Fsrc%2Fshared%2Fcode-hosts%2Fshared%2FcodeHostTestUtils.ts&editor=VSCode&version=2.2.4&start_row=211&start_col=31&end_row=211&end_col=31&utm_campaign=vscode-extension&utm_medium=direct_traffic&utm_source=vscode-extension&utm_content=vsce-commands)

**Comment by taylorsperry** [comment]
I'm probably missing something, but I don't understand what happens when you hover over an empty cell. My instinct, though, is the same as Jason's (nothing should happen).

**Comment by plibither8** [comment]
@jasongornall @taylorsperry As I understand, the calls to `getLineNumberFromCodeElement()` are being performed by the [`locateTarget` function](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/codeintellify/src/tokenPosition.ts?L433%3A1=), and the comment describing the function gives a decent overview of the purpose of the function. In essence, the line number is required to determine and position the code intel dialog.

There is possible potential for improvement here, especially in the [`getCodeElementFromTarget` function](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/repo/compare/dom-functions.ts?L6%3A1=) so as to return `null` when encountering a blank cell (particularly the ones demarcated by the green box in the PR description).

Additionally, I've made a change to the `getLineNumberFromCodeElement` to make it "less brittle" and hacky, and one that doesn't rely on a for/while loop :P. So it would be great if you could give that a review too! :)

File: client/web/src/repo/compare/dom-functions.ts (hunk 1 above)
Comment (plibither8) [reply client/web/src/repo/compare/dom-functions.ts]: @jasongornall I don't think there's anything to add to unit tests here. They're passing so that's good!

**Review by umpox — APPROVED** [review]
👍  Logic makes sense!

Agree it would be great to have some tests here, but I think it's out of scope for this fix. The current tests are very old and I think we'd great more value out of some high level tests that check basic functionality.

@plibither8 WDYT about creating an issue to address this in future (the tests) (esp given our focus on improved testing soon). We just want:
- React testing library, black box tests
- Testing basic functionality driven by user actions (e.g. simulate a hover on a token).

This would be a big improvement over our current tests for these functions, as it would actually match what the user experiences rather than our understanding of the code.

**Comment by plibither8** [comment]
> @plibither8 WDYT about creating an issue to address this in future (the tests) (esp given our focus on improved testing soon).

@umpox sounds like a great idea, will do! 👍
