### PR TITLE
Replace react-scroll-manager with useScrollManager hook

### LINKED ISSUE #32302: Scroll position not preserved after clicking "Show more" on a filtered connection list
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Most major browsers (Chrome, Firefox, Safari, Brave tested)

This is easiest to reproduce with the Batch Changes list view but happens anywhere there's a filtered connection with more results than are initially displayed.

#### Steps to reproduce:

1. Visit https://k8s.sgdev.org/batch-changes (signed in to an account in the Sourcegraph org)
2. Scroll the list to the bottom and click "Show more"
3. Wait for query to complete

#### Expected behavior:

URL updates with new `?visible=30` parameter and scroll position on the page does not change.

#### Actual behavior:

URL updates with new `?visible=30` parameter and scroll position is reset to the top of the page.

I believe this is an unintended consequence of https://github.com/sourcegraph/sourcegraph/pull/29178. Since react-scroll-manager caches scroll position against the path, when the filtered connection components change the URL parameter with `history.replace`, the resultant path is not found in the cache. Since there's no scroll position associated with it, then, it defaults to 0, 0 instead, causing the unexpected jump.

The problematic behavior ceases if either:
- `FilteredConnection.useURLQuery` (or `UseConnectionConfig.useURL` for the new hook variation) is set to `false`
- `ScrollManager` is removed from the root rendering tree of `SourcegraphWebApp`

The ideal solution would be to instruct react-scroll-manager to ignore the URL parameter when caching scroll position on routes with filtered connections where changing the parameter does not change what page the user is on.

Here is a screen recording of behavior. Pay attention to the URL when the scroll jump happens (they correspond).

https://user-images.githubusercontent.com/8942601/157168698-509aaf53-d962-40e7-a30a-9eff234cb5d9.mov

### PR DESCRIPTION
**Pull request by lrhacker**
- Fixes #32302.
- Also supports the specific case mentioned in #24758, and more generically should support the request to have this feature available anywhere in the application (and already adds it to many more pages with this change). So, this should close that issue as well! @limitedmage could you confirm?

Replaces the dependency on `react-scroll-manager` with a local implementation of a scroll manager as a hook. Since `react-scroll-manager` preserved/restored scroll for all URL changes, including the search portion of the URL being treated as a unique location (e.g. `?visible=1`), it was causes the buggy behavior noted in the first issue above.

Our new implementation _only_ preserves/restores scroll position for the `pathname` portion of the location, ignoring any changes to the `hash` or `search`, fixing the undesirable behavior. It does not appear to interfere with any pages that might make use of hashes, such as in Notebooks, so navigating to header elements in those should still work as expected!

This also moved the current use of scroll management to the `main` element container of the application, so by default many more pages are supporting scroll restoration automatically (like Code Insights dashboards)! 😎

Since this is now its own hook that can be added to any container, it might even work to support scroll saving/restoration in blob views, as well!

## Test plan

- Manually testing by navigating around the application, scrolling down on pages, and using back/forward navigation to confirm the scroll position is restored. Also confirm it is _not_ restored when navigating directly to the path from a link (since it would be confusing to have the scroll jump when you clicked to visit a path you had been on 5 minutes ago 😄).
- Unit tests added to check the hook behavior

## App preview:

- [Web](https://sg-web-lrh-fix-scroll-manager.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-rqgixvkdds.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

File: client/web/src/hooks/useScrollManager.ts [hunk 1]
```diff
@@ -0,0 +1,164 @@
...
+    // Set up the maps for this containerKey if they haven't been created yet
+    useEffect(() => {
+        if (!SAVED_SCROLL_POSITIONS[containerKey]) {
+            SAVED_SCROLL_POSITIONS[containerKey] = new Map<string, number>()
+        }
+
+        if (!CACHED_SCROLL_ATTEMPTS[containerKey]) {
+            CACHED_SCROLL_ATTEMPTS[containerKey] = new Map<string, MutationObserverPromise>()
+        }
+    })
```
Comment (umpox) [inline client/web/src/hooks/useScrollManager.ts:33]:
```suggestion
    }, [containerKey])
```

This should only run on initial mount / if the key changes, right?

File: client/web/src/hooks/useScrollManager.ts [hunk 2]
```diff
@@ -0,0 +1,164 @@
...
+    useEffect(() => {
+        // Cancel any existing cached scroll attempts for this pathname
+        if (CACHED_SCROLL_ATTEMPTS[containerKey].has(pathname)) {
+            CACHED_SCROLL_ATTEMPTS[containerKey].get(pathname)?.cancel()
+            CACHED_SCROLL_ATTEMPTS[containerKey].delete(pathname)
+        }
+
+        // Attempt a scroll if we have a saved position for the pathname; if the scroll doesn't work, set up an observer to
+        // retry up until a given timeout
+        if (SAVED_SCROLL_POSITIONS[containerKey].has(pathname)) {
```
Comment (umpox) [inline client/web/src/hooks/useScrollManager.ts:61]: I think we only want to do this if the user is actively navigating history. It might be a bit confusing if users click a link and get auto-scrolled because they were on that same like 5 mins ago.

I think we should just be able to use `useHistory` and change this line to:

```suggestion
        if (history.action === 'POP' && SAVED_SCROLL_POSITIONS[containerKey].has(pathname)) {
```

**Review by umpox — COMMENTED** [review]
Looking good! Added some small comments, from my testing everything works great 👍

File: client/web/src/hooks/useScrollManager.ts (hunk 2 above)
Comment (umpox) [reply client/web/src/hooks/useScrollManager.ts]: Pushed this up with my change to add tests, keeping open for discussion!

File: client/web/src/hooks/useScrollManager.ts (hunk 1 above)
Comment (umpox) [reply client/web/src/hooks/useScrollManager.ts]: Pushed this up with my change, feel free to revert if I missed anything :)

File: client/web/src/hooks/useScrollManager/mutationObserverWithTimeout.ts [hunk 3]
```diff
@@ -0,0 +1,85 @@
+/**
+ * The following code was adapted from react-scroll-manager: https://github.com/trevorr/react-scroll-manager/blob/master/src/timedMutationObserver.js
+ *
+ * react-scroll-manager is availabe under the ISC License:
```
Comment (umpox) [inline client/web/src/hooks/useScrollManager/mutationObserverWithTimeout.ts:4]:
```suggestion
 * react-scroll-manager is available under the ISC License:
```

**Review by umpox — APPROVED** [review]
🚀

File: client/web/src/hooks/useScrollManager/mutationObserverWithTimeout.ts (hunk 3 above)
Comment (lrhacker) [reply client/web/src/hooks/useScrollManager/mutationObserverWithTimeout.ts:4]: Doh 🤦‍♀️

**Comment by vovakulikov** [comment]
@lrhacker, I think I found something; as you can see on the video, there is a small delay after I click history back button and render the search result page and actual restore the scroll position

I think it comes from the async nature of the code about scroll restoring. (But I thought since we use there mutation observer all should happens before paint and therefore there should be no jumps or flashes) 

https://user-images.githubusercontent.com/18492575/189390812-d83e8c33-6329-4f99-bb9b-ed8bc6bee02e.mov

**Review by courier-new — COMMENTED** [review]
YOU ARE MY HERO THANK YOU FOR THIS BEAUTIFUL CONTRIBUTION. 💙💙💙
