### PR TITLE
Proposal PR: Remove the management console (🦄unicorns and 🌈rainbows here)

### LINKED ISSUE #1432: Management console should indicate license status
Today, the license status is indicated via the site config area, but it is configured through the management console. This is a bad UX but not too bad.

Customers:

- https://app.hubspot.com/contacts/2762526/company/419771425

### LINKED ISSUE #1435: Validation errors for critical config are only displayed in the site config area
When there are validation errors in the critical config, the management console should show them. In general there is some question about how to present validation errors (does the mgmt console show BOTH site and critical validation errors? Only one? What about the site config area? etc.)

### LINKED ISSUE #1685: management console UI should ask for password instead of using browser's built in basic auth form
The basic auth form feels janky, we should just have the react app ask for the password when you visit the page instead. Then it would feel more integrated into the app, etc.

cc @francisschmaltz who suggested this + for designing how this form would look.

The form should only ask for the password (not username), and have a link to management console documentation (so the user can figure out where to get the password). No other information is needed on this page, but we could e.g. include the Sourcegraph logo etc.

### LINKED ISSUE #1731: Give immediate feedback in mgmt console for invalid license key
For step 12 of the [test plan](https://github.com/sourcegraph/sourcegraph/issues/1689) it is a bit unclear to me why putting in an invalid value for the licenseKey would cause the instance to display a roadblock page when a missing license key doesn't behave that way.

image

### LINKED ISSUE #1822: management console: TODO: Better 'loading' state styling
Currently it does not indicate well through the UX that the save operation is happening when you click Save (it only displays some "Saving..." text). A spinner of some sort would be better.

This is especially true because some connections to clusters can be a bit flaky, it is hard to know the save is still occurring.

### LINKED ISSUE #1934: Management console URL should link to the management console not the doc page
It's really hard as a first time user to navigate to the management console. The below closely resembles the first time I tried to access it.

screenflow

I would propose that we link to what the management console URL is likely to be (host:2633) and add a (?) help element, the contents of which could be:
 - Mentions the username can be anything
 - Mentions to copy the management console password 
 - Links to the docs

One of my on-boarding videos will include using the management console to set the external url and it would a lot nicer if I could just click a link to be taken there.

### LINKED ISSUE #2090: Hitting escape at the management console log-in prompt breaks the page
If you hit escape at the username/password prompt of the management console, you'll see this error:

image

I would expect a message more like "Incorrect username or password.".

If you hit escape again, the prompt disappears and the page doesn't load. You have to refresh to bring the prompt back.

### LINKED ISSUE #2095: management-console doesn't pick up settings from dev-private
- **Sourcegraph version:** https://github.com/sourcegraph/sourcegraph/commit/36dbe5794521f612ea77ffb33b32f0ab53febb69
- **Platform information:**

```
Hardware Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro13,2
  Processor Name:	Intel Core i7
  Processor Speed:	3.3 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	16 GB
```

#### Steps to reproduce:

1. Clone https://github.com/sourcegraph/sourcegraph/ to `$GOPATH/src/github.com/sourcegraph/sourcegraph`
1. Clone https://github.com/sourcegraph/dev-private/ to `$GOPATH/src/github.com/sourcegraph/dev-private`
1. Visit management console at `https://localhost:2633`

#### Expected behavior:

Management console has settings copied over from https://github.com/sourcegraph/dev-private/blob/master/enterprise/dev/critical-config.json

#### Actual behavior:

The management console only has the default config:

```js
// The Sourcegraph critical configuration for development servers.
{
  "externalURL": "http://localhost:3080",
  "update.channel": "release",
  "auth.providers": [
    {
      "type": "builtin",
      "allowSignup": true
    }
  ]
}
```

I can still see that the `frontend` binary is picking up `lightstep` settings (from `dev-private`?) due to this log line:

```
13:59:02               frontend | INFO Distributed tracing enabled, tracer: Lightstep
```

But the `lighstepProject` field in my traces are incorrect (see https://sourcegraph.slack.com/archives/C07KZF47K/p1548971461561900?thread_ts=1548969611.558900&cid=C07KZF47K). 

Maybe there is a race condition happening somewhere?

---

Also (related), the management console seems to throw away any edits I make to the critical configuration between restarts (all I see is the default config).

### LINKED ISSUE #2322: Site should not have to be initialized before accessing management console
If you start a sourcegraph instance, it is impossible to access the management console until you create an admin account. In some situations, this is confusing and unexpected (e.g. if you are going through the steps a second time to set up your real instance).

Additionally, the `global_state` table is weird because despite representing one consistent state, only the last entry in the table is the current site state which is odd and leads to the table sometimes having hundreds of rows and various different site IDs. It is unclear to me why it was written this way (performance?) or if this is a bug.

### LINKED ISSUE #2404: log all management console requests
When the management console receives a request of any sort, we should log it. This is helpful when debugging.

### LINKED ISSUE #2478: Unclear how to expose access to management console (GCP)
After following the [Install Sourcegraph with Docker on Google Cloud](https://docs.sourcegraph.com/admin/install/docker/google_cloud) documentation and setting up SSL/TLS - https://github.com/sourcegraph/sourcegraph/issues/2475 it's not obvious to users how to access the management console.

By default, `2633` is not exposed and users need to expose the port so that it can be accessible.

You can do so by running:
```
gcloud compute firewall-rules create management-console --allow tcp:2633,icmp
```

@slimsag is this how users should expose access to the management console?

Also should users update their certificate to a signed certificate when going through the SSL/TLS configuration?

### LINKED ISSUE #2759: Document how to set up management console behind reverse proxy
#### Question description

How should we configure an Apache proxy to work with the management console.

#### Is your question related to a problem? If so, please describe or link to another issue.

We configured a proxy in front on Sourcegraph, but after the upgrade to 3.X we have to configure access to the management console as well, which uses basic auth.

The problem is that the configuration update does not happen due to `Unexpected HTTP 401: Unauthorized `

The request does not send any cookie or basic auth as a parameter/header.

### LINKED ISSUE #4213: Management console: long descriptions are clipped
1. Visit the management console
2. Hover over eg. `allowSignup` if you still have the builtin `auth.provider` configured
3. Witness description tooltip is clipped:

image

### LINKED ISSUE #4235: management console bundle is 6mb and not being minified, takes 1-4s to load
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6ca56ce896094b13245a55ab9a9e91ffd9b11f1c/-/blob/cmd/management-console/web/package.json#L10-11

To fix, we would need to turn on minification (easy) and build a server image to confirm that source maps are being served properly so that if customers run into issues we can debug them.

### LINKED ISSUE #5186: Create a troubleshooting section for how to reset the admin user password
Create a troubleshooting section similar to what the [management console](https://docs.sourcegraph.com/admin/management_console#how-can-i-reset-my-management-console-password) has.

[This Gist](https://gist.github.com/ryan-blunden/01742140f4a1418067ce5b4f850055af) was created to help a user reset the admin password for a local instance and could be useful in creating this section.

### LINKED ISSUE #5350: Management console is not typechecked and eslinted in CI (contains many type errors)
Just noticed that the management console contains tons of TypeScript and eslint errors that are not checked in CI

### LINKED ISSUE #5760: Quick config buttons broke critical configuration
- **Sourcegraph version:** 3.8
- **Platform information:** Docker image

Reported by: 
* https://app.hubspot.com/contacts/2762526/company/2155791964

>We accidentally made a change to our SourceGraph configuration last night and despite our efforts to put the config back to its original state, the service will not fire up anymore.
>
>The change that was accidentally made was pressing the “Add OneLogin SAML” button on the management console. This inserted and changed fields in the config, including removing the license key field. After recovering the license key and manually reconstructing the management config back to its original state, we just get 502s when we try to use sourcegraph.

### LINKED ISSUE #6070: Docs claim that management console can be accessed despite TLS error, but that is not true
A fresh Docker instance is telling me that I must go to the management console and set `externalURL`.

The docs say:

> You must click the Advanced option in your browser and continue anyway (Proceed to localhost (unsafe)).

https://docs.sourcegraph.com/@v3.9.0-rc.4/admin/management_console#what-is-the-password-to-my-management-console

That option does not exist (Chrome 77.0.3865.120) and it is therefor impossible to access the management console, unless I use Safari.

image

### PR DESCRIPTION
**Pull request by slimsag**
The management console today is the single most significant barrier that site admins encounter when trying to configure their Sourcegraph instance, which is a major blocker for customer onboarding and ARR growth. This (fully-functioning) PR proposes removing it, making the user experience better, reducing technical complexity (-8k LOC) and closing 18 open issues in the process.

From admins not saving their password (#5186), confusing browser TLS warnings prompts (#6070), it being difficult to access (#1934), complexity poking firewall holes properly (#2478), a general lack of maintenance and significant technical complexity for us (#5760, #5350, #4235, #4213, #2759, #2404, #2322, #2095, #2090, #1822, #1731, #1685, #1435, #1432), even slowing down our CI builds (#6770) -- **the management console overall is a massive source of problems for our users and complexity for us from Engineering, Sales, and overall Business standpoint.**

But before we go around suggesting we remove things willy-nilly, why did we add it in the first place and why does it make sense to remove now?

### Management console: a brief history

In November of last year in PR #966 we introduced the management console. At the time, Sourcegraph configuration was provided through a JSON configuration file mounted into the container and this presented challenges for site admins going through our onboarding / trial process:

- Admins needed to not only figure out the right properties to plug in for e.g. their auth provider and code host (which can be quite complex), but also needed to do so in their editor without any autocomplete or helpful tooltips to guide them.
- After making some edits, it required they restart all containers for the changes to take effect.

All in all, this was a tedious process and made configuration very difficult. To resolve this, we made all configuration dynamic so that restarting services was not required. However, some configuration properties such as authentication if misconfigured could lock the site admin out of their instance and prevent them from fixing their configuration after. To resolve this, we took inspiration from other similar tools and created the management console.

Our hope was that the management console and overall configuration UI would eventually become more intuitive, UI-based / beginner-friendly (instead of just a JSON editor), and more. In practice, this work was de-prioritized in favor of other more important work.

Additionally, the management console introduced security concerns which meant we had to lock it down heavily with a self-signed TLS cert on new instances and a strong auto-generated basic auth password in order for it to be sufficiently secure. You can read more about this in my prior proposal [RFC 63 REVIEW: Authless management console access](https://docs.google.com/document/d/1RkOS4EehLtAXhunTazkjCI4yKi5Hc8eRcHZ_v1Fz_QU/edit?ts=5db76618#heading=h.g2cr8neesagy).

**The management console succeeded in lowering the barrier to onboarding at the time we added it, because it meant we could make a majority of the options (site configuration) editable easily at runtime.**

### What has changed?

We can do better.

We understand our product and the configuration options it must provide more intimately than anyone else. When we added it last year, we closely mimicked best-practices in similar software -- and in the meantime, we have grown to make our product more resilient towards configuration. Nearly every single configuration option since has been made dynamic (editable at runtime without requiring a restart), we have paid more close attention to configuration issues, and most important we have learned what the problems are with the configuration of Sourcegraph on its own merits without mimicking other products.

Before starting this change, I wanted to ensure I had a full grasp on the entire situation from a technical point of view. To do this, I compiled a complete list of all existing critical configuration / management console options and determined whether or not they fit the original criteria for what belongs in the management console (things that, if misconfigured, could lead to the admin being locked out). You can find this [document here](https://docs.google.com/document/d/1IMi3UYQCnxXO8LnP14qUB1HpkRlPHf3k7gdGGOYy7tE/edit).

Once this was written, two things became clear to me:

1. **Not a single critical configuration option can prevent the frontend from starting.** This was not true when we added the management console originally and has important implications I will get to later.
2. **Only 5 configuration options could lock an admin out of the instance:**
    - One, the `licenseKey`, I resolved last night in #7181
    - The remaining 4 would need to be set to ridiculously stupid values in order to lock an admin out in practice. _Removing all auth providers_, _setting session expiry to a very low value_, _adding custom HTML which bricks the frontend web UI_, etc.
    - This is not to say these cases are impossible, but that they are **very unlikely in practice and I have not once heard of an admin ever doing this by mistake.**

Given this data, we can shift around our tradeoffs from what they are today:

- 95% of admins onboarding must go through the painful escape hatch (the management console)
- 5% of admins needing an escape hatch have a nice/friendly UI.

To something more amicable to our goals such as:

- 0% of admins onboarding must go through the painful escape hatch.
- 5% of admins needing an escape hatch still have one, and it's MUCH friendlier than the management console in its current form.

### Solution

1. The management console is removed - gone.
2. All configuration options previously found in the management console are automatically migrated into the site configuration.
3. We no longer have both "critical" and "site" configuration: we now have just "site" configuration and one editor / schema.
4. In 95% of cases, admins can make all configuration edits through the regular web UI without any trouble.
5. In 5% of cases where an admin messed up bad and needs an escape hatch, we provide them a command to edit a file in the Docker container using e.g. `vi` or `nano`. This file has your current site configuration contents, and any edits made to it are synchronized with the database. The file is otherwise ephemeral (i.e. DB remains the source of truth for configuration, the file just allows edits as an escape hatch). How this looks:

> ### Editing your site configuration if you cannot access the web UI
>
> If you are having trouble accessing the web UI, you can make edits to your site configuration by editing a file in the container using the following commands:
>
> #### Single-container Docker instances
>
> ```sh
> docker exec -it $CONTAINER -- nano /site-config.json
> ```
>
> #### Kubernetes cluster instances
>
> ```sh
> kubectl exec -it $FRONTEND_POD -- nano /site-config.json
> ```
>
> Perform your edits, type <kbd>ctrl+x</kbd> and <kbd>y</kbd> to save the changes. They will be applied immediately just as if made through the web UI. If you prefer `vi`, simply replace `nano` in the commands above.

### Next steps

100% of what I described above is already implemented in this PR. This could not have been written as an RFC because the solution was inherently tied to the constraints we have in our product -- which could not be uncovered without implementing this.

If this proposal is accepted, we can land this in 3.11 easily.

- [x] Get feedback from Product to confirm they believe this is a good step forward. cc @sqs @christinaforney 
- [x] Get help from @beyang to resolve issues in the regression test suite -- it relied on the management console API for configuration and must now go through the app itself instead.
- [x] Write and update both documentation and in-product documentation/links.
- [x] Write paired changes for deploy-sourcegraph and deploy-sourcegraph-docker to remove the management console.

### Fixes

- Fixes #5186
- Fixes #6070
- Fixes #1934
- Fixes #2478
- Fixes #5760
- Fixes #5350
- Fixes #4235
- Fixes #4213
- Fixes #2759
- Fixes #2404
- Fixes #2322
- Fixes #2095
- Fixes #2090
- Fixes #1822
- Fixes #1731
- Fixes #1685
- Fixes #1435
- Fixes #1432
- Helps #6770

### CODE REVIEW

**Comment by beyang** [comment]
- [ ] 1 immediate thing that comes to mind: need to update the onboarding widget so that it links to site config, rather than documentation about how to access the mgt console

image

File: enterprise/cmd/frontend/pre-build.sh [hunk 1]
```diff
@@ -14,6 +14,7 @@ parallel_run() {
 echo "--- yarn root"
 # mutex is necessary since frontend and the management-console can
 # run concurrent "yarn" installs
+# TODO: This is no longer needed since the management console was removed.
```
Comment (beyang) [inline enterprise/cmd/frontend/pre-build.sh]: remove if not needed?

File: internal/conf/conf.go [hunk 2]
```diff
@@ -162,9 +164,93 @@ func InitConfigurationServerFrontendOnly(source ConfigurationSource) *Server {
...
+
+	startSiteConfigEscapeHatchWorker(source)
 	return server
 }
 
 // FormatOptions is the default format options that should be used for jsonx
 // edit computation.
 var FormatOptions = jsonx.FormatOptions{InsertSpaces: true, TabSize: 2, EOL: "\n"}
+
+var siteConfigEscapeHatchPath = env.Get("SITE_CONFIG_ESCAPE_HATCH_PATH", "/site-config.json", "Path where the site-config.json escape-hatch file will be written.")
```
Comment (beyang) [inline internal/conf/conf.go]: Does this interact in a sane manner with the `SITE_CONFIG_FILE` env variable?

File: internal/conf/conf.go [hunk 3]
```diff
@@ -162,9 +164,93 @@ func InitConfigurationServerFrontendOnly(source ConfigurationSource) *Server {
 
 	go defaultClient.continuouslyUpdate(nil)
 	close(configurationServerFrontendOnlyInitialized)
+
+	startSiteConfigEscapeHatchWorker(source)
```
Comment (beyang) [inline internal/conf/conf.go]: Does this mean every `frontend` instance will sync config to its local FS? How does this work in a Kubernetes cluster where there are multiple `frontend` instances?

More broadly, this package could get imported by any service in Sourcegraph, so we should be cautious about what we introduce to the `init` function here. Any way to scope this so that it *only* runs in exactly 1 process per Sourcegraph installation?

File: internal/conf/conf.go [hunk 4]
```diff
@@ -162,9 +164,93 @@ func InitConfigurationServerFrontendOnly(source ConfigurationSource) *Server {
...
+
+// startSiteConfigEscapeHatchWorker handles ensuring that edits to the ephemeral on-disk
+// site-config.json file are propagated to the persistent DB and vice-versa. This acts as
+// an escape hatch such that if a site admin configures their instance in a way that they
+// cannot access the UI (for example by configuring auth in a way that locks them out)
+// they can simply edit this file in any of the frontend containers to undo the change.
+func startSiteConfigEscapeHatchWorker(c ConfigurationSource) {
+	var (
+		ctx                                        = context.Background()
+		lastKnownFileContents, lastKnownDBContents string
```
Comment (beyang) [inline internal/conf/conf.go]: Might be cleaner to encapsulate this state in a struct

File: internal/db/confdb/confdb.go [hunk 5]
```diff
@@ -5,16 +5,104 @@ import (
...
 	"github.com/keegancsmith/sqlf"
 	"github.com/sourcegraph/jsonx"
 	"github.com/sourcegraph/sourcegraph/internal/conf/confdefaults"
 	"github.com/sourcegraph/sourcegraph/internal/db/dbconn"
+	"github.com/sourcegraph/sourcegraph/internal/jsonc"
+	"github.com/sourcegraph/sourcegraph/schema/critical"
 )
 
+// RunMigrations runs configuration DB table migrations.
+func RunMigrations(ctx context.Context) error {
```
Comment (beyang) [inline internal/db/confdb/confdb.go]: - [ ] TODO(@beyang): test this migration runs properly.

**Comment by beyang** [comment]
My understanding is that the backup config file is written to a file within the Docker container (the single Docker container in the single node deployment, or each of the frontend Docker containers in the clustered deployment). What happens if the container fails to start? I understand that we don't think config changes will cause the container to fail to start, but containers may fail to start for some other reason.

A counter-proposal that occurred to me (not yet fully fleshed out): what if we provided a CLI one-liner to extract the config from the database and then instructed the site admin to use `SITE_CONFIG_FILE` and `SITE_CONFIG_ALLOW_EDITS=true`?

File: enterprise/cmd/frontend/pre-build.sh (hunk 1 above)
Comment (slimsag) [reply enterprise/cmd/frontend/pre-build.sh]: Prefer to do this in a separate PR with a lot of cleanup

**Comment by felixfbecker** [comment]
This is a great analysis @slimsag and every proposal to remove/replace/change something should look like this! I.e. why was this added in the first place ➡️ do these reasons still apply. 👏🏻

UX should be the deciding factor here, but I would it would certainly remove code maintenance headaches for me.

File: internal/conf/conf.go (hunk 2 above)
Comment (slimsag) [reply internal/conf/conf.go]: It does. There is no change in how `SITE_CONFIG_FILE` or `CRITICAL_CONFIG_FILE` behave, and this environment variable will remain undocumented. In practice nobody will set this because the default `/site-config.json` is perfect in all deployments except dev environments where writing to the root FS is not possible due to permissions.

File: internal/conf/conf.go (hunk 4 above)
Comment (slimsag) [reply internal/conf/conf.go]: If it's okay with you, I'd like to do this in a follow-up (there are also more pressing things to cleanup here)

**Comment by beyang** [comment]
@slimsag a note for later: the docs should clearly mention that all this is not necessary if the admin is using `SITE_CONFIG_FILE` (because then the source of config truth is outside the DB).

**Comment by slimsag** [comment]
> What migration, if any, is required by existing customers?

I will add documentation before merging this PR which explains the change to site admins and any manual steps that are needed. The migration is already mentioned in the CHANGELOG somewhat effectively: it is automatic and no manual migration is needed.

There is a small caveat to this which is that users of `SITE_CONFIG_FILE` should copy their config from Sourcegraph back into the file so that we can remove this migration code in the future (but nothing bad will happen if they upgrade without doing that, until we remove this migration code down the line). This is mentioned in the CHANGELOG, and will be mentioned in the docs before merging.

> Does this impact @uwedeportivo's work on metrics (or is that completely separate from the management console)?

There is zero relationship with metrics here., I'm not sure what you might be thinking of with this question. It does supersede the work he did in #6696 though.

**Comment by slimsag** [comment]
Me and Beyang went over his questions in a call, responding here for transparency sake:

> Does this mean every frontend instance will sync config to its local FS? How does this work in a Kubernetes cluster where there are multiple frontend instances?

The best way to mentally model / reason about the behavior is this: There is no difference between what we do here with the escape hatch file and with what we do in the web UI in terms of handling conflicts.

In the case of the web UI, we sync the DB contents to the web UI, the admin makes an edit, and we sync that edit to the DB.

In the case of the escape-hatch file, we sync the DB contents to the (ephemeral) file on disk, the admin makes an edit, and we sync that edit to the DB.

The file itself only acts as a mechanism for admins to easily make edits without a web UI.

In terms of conflicting edits, we have the same risks as the web UI:  if two admins edit the site config through the web UI at once, one of their changes would be rejected (they would receive an error). In the case of this approach, the error would appear in the frontend container logs whether the conflict is with someone editing the config through a file on another frontend container or through the web UI.

**Comment by slimsag** [comment]
> My understanding is that the backup config file is written to a file within the Docker container (the single Docker container in the single node deployment, or each of the frontend Docker containers in the clustered deployment).

This is correct, it is over-written on startup with the current DB contents (which remains the authoritative source of configuration) and is ephemeral.

> What happens if the container fails to start? I understand that we don't think config changes will cause the container to fail to start, but containers may fail to start for some other reason.

There is an implicit assumption that the frontend will always be accessible and not go down due to invalid configuration changes. I have vetted the code and this holds true today for all configuration, even e.g. borking your auth provider config, etc.

In the ultra rare event the frontend would not start at all (e.g. due to a critical bug or regression we introduce), a site admin could load a blank-slate configuration by setting `SITE_CONFIG_FILE` on the container and it would be loaded into the DB on startup.

> A counter-proposal that occurred to me (not yet fully fleshed out): what if we provided a CLI one-liner to extract the config from the database and then instructed the site admin to use `SITE_CONFIG_FILE` and `SITE_CONFIG_ALLOW_EDITS=true`?

The main reason not to rely on `SITE_CONFIG_FILE` alone is because edits become very tedious, and doing it through an editable file on disk is a nicer UX. Instead of using `SITE_CONFIG_FILE` which involves:

1. Providing the right credentials to your psql DB
2. Downloading & running some script to pull the current file from DB
3. Making your edits in your editor
4. Setting `SITE_CONFIG_FILE` on the container, adding a k8s file mount if in k8s
5. Restarting the containers
6. Undoing your SITE_CONFIG_FILE change once it is fixed (if you don't like loading from a file forever).
7. Done!

We can just:

1. Provide a simple command to SSH into the container and open an editor all at once
2. Make your edits and save
3. Done!

File: internal/conf/conf.go (hunk 3 above)
Comment (slimsag) [reply internal/conf/conf.go]: > More broadly, this package could get imported by any service in Sourcegraph, so we should be cautious about what we introduce to the init function here. Any way to scope this so that it only runs in exactly 1 process per Sourcegraph installation?

You probably just noticed `Init` in the function name, but this is actually in the _InitConfigurationServer**FrontendOnly**_ function which is only invoked once on server startup and only by the frontend, guaranteeing there is exactly one per frontend process and no more.

**Comment by slimsag** [comment]
>  need to update the onboarding widget so that the last item ("Configure SSO") links to site config, rather than documentation about how to access the mgt console. Should be a quick fix.

Yes, there are multiple other places of in-product docs that link to the management console. I will update these before merging and ask for re-review from you.

File: cmd/frontend/internal/app/jscontext/jscontext.go [hunk 6]
```diff
@@ -60,10 +60,10 @@ type JSContext struct {
 	ShowOnboarding bool    `json:"showOnboarding"`
 	EmailEnabled   bool    `json:"emailEnabled"`
 
-	Critical          schema.CriticalConfiguration `json:"critical"` // public subset of critical configuration
-	LikelyDockerOnMac bool                         `json:"likelyDockerOnMac"`
-	NeedServerRestart bool                         `json:"needServerRestart"`
-	DeployType        string                       `json:"deployType"`
+	Critical          schema.SiteConfiguration `json:"critical"` // public subset of critical configuration
```
Comment (unknwon) [inline cmd/frontend/internal/app/jscontext/jscontext.go]: 1. Is there any concern to expose all of the configuration? (the comment suggests "public subset")
2. Should `Critical` be renamed to `PublicConfig`?

File: cmd/frontend/graphqlbackend/site_alerts.go [hunk 7]
```diff
@@ -62,8 +62,8 @@ func (r *siteResolver) Alerts(ctx context.Context) ([]*Alert, error) {
 
 func init() {
 	conf.ContributeWarning(func(c conf.Unified) (problems conf.Problems) {
-		if c.Critical.ExternalURL == "" {
-			problems = append(problems, conf.NewCriticalProblem("`externalURL` is required to be set for many features of Sourcegraph to work correctly."))
+		if c.ExternalURL == "" {
+			problems = append(problems, conf.NewSiteProblem("`externalURL` is required to be set for many features of Sourcegraph to work correctly."))
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/site_alerts.go]: I was going to ask if do we still need [critical type problems](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@487d0d24c0e8ed1c1e8cd8e20ce9c30905dd17dd/-/blob/internal/conf/validate.go#L53), but on a second thought, critical problems are still useful because some configurations if not correct could cause Sourcegraph not working properly. 

Therefore, I would revert back to use `NewCriticalProblem` on this line.

File: dev/Procfile [hunk 8]
```diff
@@ -5,7 +5,7 @@ searcher: searcher
 replacer: replacer
 symbols: ./cmd/symbols/build.sh execute
 github-proxy: github-proxy
-frontend: env CONFIGURATION_MODE=server frontend
+frontend: env CONFIGURATION_MODE=server SITE_CONFIG_ESCAPE_HATCH_PATH=$HOME/.sourcegraph/site-config.json frontend
```
[the remark this answers is not in the document]
Comment (slimsag) [reply dev/Procfile]: No, this file is written on server startup.

File: enterprise/cmd/frontend/authz_test.go [hunk 9]
```diff
@@ -134,12 +134,12 @@ func Test_authzProvidersFromConfig(t *testing.T) {
 				},
 			},
 			expAuthzAllowAccessByDefault: false,
-			expSeriousProblems:           []string{"Did not find authentication provider matching \"https://gitlab.mine\". Check the [management console](https://docs.sourcegraph.com/admin/management_console) to verify an entry in [`auth.providers`](https://docs.sourcegraph.com/admin/auth) exists for https://gitlab.mine."},
+			expSeriousProblems:           []string{"Did not find authentication provider matching \"https://gitlab.mine\". Check the [site configuration](https://docs.sourcegraph.com/admin/config/site_config) to verify an entry in [`auth.providers`](https://docs.sourcegraph.com/admin/auth) exists for https://gitlab.mine."},
```
[the remark this answers is not in the document]
Comment (slimsag) [reply enterprise/cmd/frontend/authz_test.go]: Good point!

File: cmd/frontend/internal/app/jscontext/jscontext.go (hunk 6 above)
Comment (slimsag) [reply cmd/frontend/internal/app/jscontext/jscontext.go]: 1. No, there is no risk, this is only the data type in use. You can see where we construct the actual value in the `publicCriticalConfiguration` function below here (https://github.com/sourcegraph/sourcegraph/pull/7197/files/4be74b77c2ef3367a76c4a6eff5724201a28cda3#diff-507fb3079e6d8fde51150a299cb10c54L184).
2. Yes, it should be renamed / cleaned up. There is much more cleanup that can be done but this PR is quite large so I am hoping to merge it and do this cleanup in a subsequent PR which is less risky.

File: cmd/frontend/graphqlbackend/site_alerts.go (hunk 7 above)
Comment (slimsag) [reply cmd/frontend/graphqlbackend/site_alerts.go]: We don't need critical type problems anymore, we actually do not need anything with "critical" in the name anymore -- critical configuration is 100% gone after this change and we only have site configuration now.

Some code for "critical" things still remains in this PR because there is _a lot of it_ and I hope to remove this code in a subsequent PR to avoid this one becoming even bigger (which I think is more risky).

> critical problems are still useful because some configurations if not correct could cause Sourcegraph not working properly (wording of site alerts would be changed too, e.g. "some problems in site configuration", "critical problems in site configuration").

Previously we treated these problems as "severe" in any case: if site config is messed up, it can be equally as bad for your Sourcegraph instance as if "critical" config is messed up. I think we always want to display config problems as equal severity because no site admin should ignore config problems (e.g. we should not have "warning" and "error" problem levels, just "problems")

**Comment by slimsag** [comment]
> Do we provide or is it necessary to provide downgrade migration if user wants to downgrade from 3.11 to 3.10 for example?

Good question, I will update the migration documentation to reflect this.

The answer: If a user wants to downgrade, they can indeed do so just fine, but after downgrading the critical configuration will be just `{"migrated": true}` and they will need to copy the relevant configuration from their site configuration back into the management console. I think this is acceptable but I will ponder it some more.

File: cmd/frontend/graphqlbackend/site_alerts.go (hunk 7 above)
Comment (unknwon) [reply cmd/frontend/graphqlbackend/site_alerts.go]: Make senses, thanks!

File: enterprise/cmd/frontend/authz_test.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (slimsag) [reply enterprise/cmd/frontend/authz_test.go]: Done

File: shared/gulpfile.js [hunk 10]
```diff
@@ -78,7 +78,10 @@ async function schema() {
   const schemaDir = path.join(__dirname, '..', 'schema')
   await Promise.all(
     ['json-schema-draft-07', 'settings', 'critical', 'site'].map(async file => {
-      let schema = await readFile(path.join(schemaDir, `${file}.schema.json`), 'utf8')
+      let schema = await readFile(
+        path.join(schemaDir, `${file === 'critical' ? 'critical/critical' : file}.schema.json`),
```
Comment (felixfbecker) [inline shared/gulpfile.js]: This looks like a hack to me - why is it needed?

File: .vscode/settings.json [hunk 11]
```diff
@@ -19,7 +18,7 @@
   "json.schemas": [
     {
       "fileMatch": ["dev/critical-config.json"],
-      "url": "/schema/critical.schema.json",
+      "url": "/schema/critical/critical.schema.json",
```
[the remark this answers is not in the document]
Comment (slimsag) [reply .vscode/settings.json]: I will address this in a follow-up PR. The reason we need a sub-folder is kind of stupid: the Go JSON schema generator we use generates duplicate type signatures because the definitions in the schema have also been added to the `site.schema.json` which makes the Go file invalid. We can't remove them from one and share them because the schema generator also does not allow that, and renaming the type definitions in either schema would make doing the migration difficult on the Go side.

In 2 versions we can remove the critical.schema.json entirely, which will make this and many other things here a LOT cleaner.

File: shared/gulpfile.js (hunk 10 above)
Comment (slimsag) [reply shared/gulpfile.js]: This is definitely a hack, I will clean this up in a follow-up PR.

File: .vscode/settings.json (hunk 11 above)
[the remark this answers is not in the document]
Comment (tsenart) [reply .vscode/settings.json]: You can define the name of the generated Go type explicitly with the title attribute. Would that help here?

[the remark this answers is not in the document]
Comment (slimsag) [reply .vscode/settings.json]: As I understand, no. For example `site.schema.json` has a definition `Foobar` and `critical.schema.json` also has a definition `Foobar`, and I need them to refer to the same Go type `Foobar` (because they are the same type, and I need to easily copy one to the other in Go)

**Comment by beyang** [comment]
@slimsag I've pushed my commits updating the regression tests to this branch

File: .vscode/settings.json (hunk 11 above)
[the remark this answers is not in the document]
Comment (tsenart) [reply .vscode/settings.json]: You could name them differently and then create a [type alias](https://yourbasic.org/golang/type-alias/). Would that work perhaps?

**Comment by christinaforney** [comment]
This looks great! Approving from product side (though I would like to test it out). 

Is there any risk pushing this in too close to branch cut and creating problems with the release?

File: .vscode/settings.json (hunk 11 above)
[the remark this answers is not in the document]
Comment (slimsag) [reply .vscode/settings.json]: Fixed in c0c48c9967f4442c64c585d9d89eb49b3beb9475 by moving the web codebase to using the site config instead of the (now deprecated) critical config.

File: shared/gulpfile.js (hunk 10 above)
Comment (slimsag) [reply shared/gulpfile.js]: Fixed in this PR via c0c48c9967f4442c64c585d9d89eb49b3beb9475

**Comment by slimsag** [comment]
I am going to merge this. I think this change will be a MASSIVE improvement for our users and is unlikely to cause us any issues in the release. We have multiple escape options if I turn out to be wrong (reversion, patch releases, the documented `SITE_CONFIG_FILE` backup escape hatch, etc.)

(I've addressed all feedback (including feedback from the web team about the critical config requiring a gulpfile hack), and am committed to following up on any additional feedback anyone leaves here or in issues filed on me. There is more cleanup I can and will do to this part of our codebase overall, but this PR is too large and making those changes in it would be risky.)

There are always risks with landing large changes like this, and even more-so with this change in particular given it has not had a significant amount of time to bake (i.e. it has gone from conception -> implementation in just three days!) but I think the value we gain and risks of _not_ merging this in 3.11 greatly outweigh the risks of merging it.

Potential risks of merging this include:

- Migration trouble -> The migration is automatic so there should be no issues, and there are clear migration notes called out in the CHANGELOG, documentation in several locations, and k8s migration documentation. The risk here is minimal.
- Product change oversight (we learn we don't like the new behavior for some reason) -> this seems incredibly unlikely, as I have heard very positive feedback from multiple people on the team.
- Something falling through the cracks (this is a big change) -> It is certainly possible, and this is likely the greatest risk with this change, but I feel confident enough to merge this now. Release captain (Beyang) will also assess independently whether or not this change makes the 3.11 branch cut (along with some other things) which makes this a "two people must turn the nuclear launch key" kind of action.

The (quite large) values we gain are outlined in the PR description already, and there are large risks of this not landing in 3.11 in my view from what I have seen in our current onboarding flow and given our renewed targets for the new year.

**Comment by slimsag** [comment]
Important note: the e2e test failure is unrelated and is passing locally, please see discussion here: https://sourcegraph.slack.com/archives/C07KZF47K/p1576555658027900?thread_ts=1576387614.018200&cid=C07KZF47K
