### PR TITLE
[fix] set permissions return proper statistics

### LINKED ISSUE #49327: Permissions added count for sync job not calculated as expected.
https://sourcegraph.slack.com/archives/C03GMM0F2BA/p1678801538268549

### PR DESCRIPTION
**Pull request by kopancek**
## Description

Fixes the calculation of added/removed permissions for both unified and legacy permissions tables.

The problem with legacy path - [we define added and removed as variables here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@1fc50a2878c17dd0199a44acbe521726c425b449/-/blob/enterprise/internal/database/perms_store.go?L652-666), but then those slices are modified in the upsert method

The problem with unified path - no calculation made at all :)

## Related issue
fixes #49327
- https://github.com/sourcegraph/sourcegraph/issues/49327

## Test plan

Tested locally + unit tests

### CODE REVIEW

**Review by thenamankumar — APPROVED** [review]

File: enterprise/cmd/repo-updater/internal/authz/perms_syncer.go [hunk 1]
```diff
@@ -628,12 +628,20 @@ func (s *PermsSyncer) syncUserPerms(ctx context.Context, userID int32, noPerms b
 		IDs:    map[int32]struct{}{},
 	}
 
+	unifiedResult := &database.SetPermissionsResult{
+		Added:   0,
+		Found:   0,
+		Removed: 0,
+	}
```
Comment (mrnugget) [inline enterprise/cmd/repo-updater/internal/authz/perms_syncer.go:635]:
```suggestion
	unifiedResult := &database.SetPermissionsResult{}
```

You can use the default values :)

**Review by mrnugget — APPROVED** [review]
