### PR TITLE
insights: surface error information from global queries that are terminally failed

### LINKED ISSUE #44371: insights: emit timeout error for global query
When a global query for an insight recording times out, record a timeout alert

/cc @joelkw @felixfbecker @vovakulikov

### PR DESCRIPTION
**Pull request by coury-clark**
Closes #44371

Write an incomplete row for global queries that terminally fail.

## Test plan

Tested a query with `timeout:2s`

Here is the queue row after it moved to the failed state:
| state | finished\_at | num\_failures |
| :--- | :--- | :--- |
| failed | 2022-12-06 18:26:29.840695 +00:00 | 10 |

Here is the incomplete row that was written
| id | series\_id | reason | time | repo\_id |
| :--- | :--- | :--- | :--- | :--- |
| 162 | 46 | timeout | 2022-12-06 18:26:27.808281 | null |

### CODE REVIEW

File: enterprise/internal/insights/background/queryrunner/worker.go [hunk 1]
```diff
@@ -105,7 +106,20 @@ func CreateDBWorkerStore(observationCtx *observation.Context, s *basestore.Store
 		MaxNumRetries:     10,
 		MaxNumResets:      10,
 		OrderByExpression: sqlf.Sprintf("priority, id"),
-	})
+	}
+	inner := dbworkerstore.New(observationContext, s.Handle(), options)
+	return &workerStoreExtra{Store: inner, options: options}
+}
+
+type workerStoreExtra struct {
```
[the remark this answers is not in the document]
Comment (chwarwick) [reply enterprise/internal/insights/background/queryrunner/worker.go:114]: I get it because the number of retries are on the options of the job

File: enterprise/internal/insights/background/queryrunner/work_handler.go [hunk 2]
```diff
@@ -119,7 +124,30 @@ func (r *workHandler) Handle(ctx context.Context, logger log.Logger, record *Job
...
+				log.Int("seriesId", series.ID), log.String("seriesUniqueId", series.SeriesID),
+				log.Error(err),
+				log.String("reason", string(reason)))
+
+			if err := r.insightsStore.AddIncompleteDatapoint(ctx, store.AddIncompleteDatapointInput{
+				SeriesID: series.ID,
+				Reason:   reason,
+				Time:     recordTime,
+			}); err != nil {
+				return errors.Wrap(err, "workHandler.AddIncompleteDatapoint")
```
Comment (chwarwick) [inline enterprise/internal/insights/background/queryrunner/work_handler.go:139]: We should probably return the original err from the job execution so that it is captured with the queue record.  If we want this err too we could make it a multi error or something.

**Review by chwarwick — APPROVED** [review]
Just a note about capturing the real failure reason for persistence/debugging.

File: enterprise/internal/insights/background/queryrunner/work_handler.go (hunk 2 above)
Comment (coury-clark) [reply enterprise/internal/insights/background/queryrunner/work_handler.go]: Yep, see https://github.com/sourcegraph/sourcegraph/pull/45282/commits/0b7d4ca01da77ece54e8676ef5647c5a650ec711

**Comment by coury-clark** [comment]
Latest commit just adds tests around this behavior and fixes some bugs

**Comment by coury-clark** [comment]
@chwarwick argh sorry, the tests are broken - will fix

**Comment by coury-clark** [comment]
@chwarwick ok, had to fix some jank but all the tests make sense and are passing now

**Review by chwarwick — APPROVED** [review]
