### PR TITLE
search: significantly improve the performance of file search suggestions

### LINKED ISSUE #2089: file: search operator could be better optimized to reduce gitserver IO load
Steps to reproduce:

1. Be on a Sourcegraph instance with a large number of repositories.
2. Ensure the Sourcegraph instance has a high `maxReposToSearch` value (i.e. any large Sourcegraph instance).
3. In the search field, type just `file:a`, then quickly in succession hit backspace to erase `a` and type `b`, then `c`, and so on.
4. You will notice the search suggestions rapidly getting slower. Press enter after a while (e.g. after reaching `file:h` in the alphabet).
5. Enter a search query like `file:h error` which will turn up results. The results will quickly appear, but the code inside of them will take a LONG time to load:

image

Gitserver logs will indicate:

```
WARN Long exec request [...]
```

### PR DESCRIPTION
**Pull request by slimsag**
This change significantly improves the performance and code quality of the
implementation providing file search _suggestions_.

It reduces IO load on gitserver, but primarily removes load from repo-updater and redis which occurred due to a bug in the old implementation trying to update all repositories involved in the search.

Fixes #2089

### How?

Most importantly, the old implementation issued requests erroneously which caused repo-updater, redis, and gitserver more IO load than was optimal. You can read more about this in the linked issue above.

File search suggestions now also benefit from the same zoekt indexing that we do for search otherwise, because we are now using the same code path that provides actual search results.

In `sourcegraph/server` instances, which do not use indexed search by default, performance is roughly identical to before.

### Code quality gains

Prior to this change file search suggestions were provided by an entirely separate code path. This old code path was responsible for listing all files in every repository your query matched, then matching those files against your search query. In contrast, after this change:

1. File search suggestions are provided by the same code-path which provides text search results.
2. Because the code-path is the same, you no longer get different ordering in search suggestions compared to when you actually run the query.

### Change in fuzzy matching behavior / more consistent matching

Before this change, you could type `src/http.go` (internally converted to `file:src/http.go`) and get fuzzy suggestions matching `src/net/http/http.go` even though your query was missing the `net/http` part of the path.

After this change, you must type a substring match, or use regex. i.e. `src/http.go` will now not fuzzy match / provide any suggestions, but these would:

- `http.go`
- `http/http.go`
- `net/http/http.go`
- `src/net/http/http.go`
- `src.*http.go`

The prior behavior was better in some regards because it acted more like your editor quick file open panel. However, the inconsistency with the results you would get when running your query was also bad. For example:

1. Visit https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v3.0.0
2. Type `file:dev/main.go` in the search input and you will see two suggestions.
3. Actually press enter and run the query, you will recieve no results!

We now have consistency and a shared implementation. In the future, we could gain this behavior back by changing the `file:` match operator to do fuzzy editor-like matching, instead of (or in addition to) using regex. However, it is unclear to me if doing that would be worth it or if this behavior is generally good enough (I suspect it is).

### CODE REVIEW

**Comment by slimsag** [comment]
@sqs Could you please review / sign off on the behavior change (last section of PR description)?

File: cmd/frontend/graphqlbackend/search_results.go [hunk 1]
```diff
@@ -551,7 +551,12 @@ func (r *searchResolver) Stats(ctx context.Context) (stats *searchResultsStats,
 
 }
 
-func (r *searchResolver) getPatternInfo() (*search.PatternInfo, error) {
+// getPatternInfo gets the search pattern info for the query in the resolver.
+//
+// If forceFileSearch == true, the search query is treated as if every default
+// term had `file:` before it. This can be used to allow users to jump to files
+// by just typing their name.
+func (r *searchResolver) getPatternInfo(forceFileSearch bool) (*search.PatternInfo, error) {
```
Comment (ggilmore) [inline cmd/frontend/graphqlbackend/search_results.go]: IMO, having a naked boolean as a parameter here seems pretty confusing (I can't tell what the behavior of this function is / how the parameter affects it without jumping to the definition / hovering over it). I am not sure if there is a clean solution that doesn't add a bunch of code (that you might not want), but one idea could be to have a separate function `addFilesToPattern()` that takes in a `PatternInfo` and _explicitly_ adds in those `file:` terms to it.

Comment (slimsag) [reply cmd/frontend/graphqlbackend/search_results.go]: Since it's a talking point, I just added an options struct. I am usually not in favor of that as it is extra code that I find not that useful when there is only one ambiguous parameter (in contrast to multiple) but if others find it helpful I am all for it :)

**Comment by slimsag** [comment]
I am merging this now. Future improvements:

- Resolving the TODO inline.
- Just call into `doResults`, to share logic even further.
- Consider automatically setting `index:only` in the query by default so that non-indexed repositories do not contribute file suggestions (perf improvement).
