### PR TITLE
Move escape-hatch /site-config.json -> $HOME/site-config.json

### LINKED ISSUE #7873: default site config escape hatch path is only writeable by root
https://github.com/sourcegraph/sourcegraph/blob/837b3b25d94e180864c7d1b7276a235a1ed9933a/internal/conf/conf.go#L176

`SITE_CONFIG_ESCAPE_HATCH_PATH` defaults to `/site.config.json`. However, only `root` can write to this file since it lives directly underneath `/`. This happens to work in both [our k8s deployment](https://github.com/sourcegraph/deploy-sourcegraph/blob/ac23a34b9e913fbd8ce0ff42cb88d0b84b0e9156/base/frontend/sourcegraph-frontend.Deployment.yaml#L85-L86) and [sourcegraph/server (we don't use the sourcegraph/alpine image which sets the `sourcegraph` user)](https://github.com/sourcegraph/sourcegraph/blob/e0406ee92c4003fa9b7f6a84589c1ac7c2791088/cmd/server/Dockerfile#L18-L19) since they both run as `root`. However,  anyone who is using deploy-sourcegraph-docker or has otherwise modified the running user will run into this error message when running the frontend image: 

```
t=2020-01-17T17:11:50+0000 lvl=eror msg="config: failed to write site config file, trying again in 1s" error="open /site-config.json: permission denied"
```

This issue also prevents the frontend binary from starting. 

We need to change the default path to a location that's writeable for both `root` and the `sourcegraph` user?

- `/mnt/cache`?
- `/tmp/`?
- `/etc/config`?

### PR DESCRIPTION
**Pull request by slimsag**
This changes the default location of the ephemeral `site-config.json` escape hatch file from `/site-config.json` to `$HOME/site-config.json` which is compatible with running our containers as a non-root user.

Fixes #7873

Before, the file location was incompatible with non-`root` container users:

```
$ docker run -it --entrypoint=sh sourcegraph/frontend:3.11.0 -c "whoami && echo 'test' > /site-config.json"
sourcegraph
sh: can't create /site-config.json: Permission denied
```

After, it is compatible:

```
$ docker run -it --entrypoint=sh sourcegraph/server:3.11.0 -c 'whoami && cd $HOME && pwd && echo "test" > ./site-config.json'
root
/root
```

```
$ docker run -it --entrypoint=sh sourcegraph/frontend:3.11.0 -c 'whoami && cd $HOME && pwd && echo "test" > ./site-config.json'
sourcegraph
/home/sourcegraph
```

- We do not use `/etc/sourcegraph/` since configuration under `/etc` is not usually ephemeral, and because site admins of `server` instances sometimes mount their own directory for SSH configuration into there, and the presence of `site-config.json` would mislead them (they may edit it, only to have it overwritten with the DB contents).
- We do not use another location like `/mnt/cache` (suggested to me by someone else) because the owner would be different in Kubernetes and Server contexts, making the problem more complex.

### CODE REVIEW

File: internal/conf/conf.go [hunk 1]
```diff
@@ -173,14 +173,16 @@ func InitConfigurationServerFrontendOnly(source ConfigurationSource) *Server {
 // edit computation.
 var FormatOptions = jsonx.FormatOptions{InsertSpaces: true, TabSize: 2, EOL: "\n"}
 
-var siteConfigEscapeHatchPath = env.Get("SITE_CONFIG_ESCAPE_HATCH_PATH", "/site-config.json", "Path where the site-config.json escape-hatch file will be written.")
+var siteConfigEscapeHatchPath = env.Get("SITE_CONFIG_ESCAPE_HATCH_PATH", "$HOME/site-config.json", "Path where the site-config.json escape-hatch file will be written.")
```
Comment (uwedeportivo) [inline internal/conf/conf.go]: does dollar sign work here ? oh i see expand env later :-), never mind
