### PR TITLE
a8n: Only create new Changesets if they can be synced

### LINKED ISSUE #6535: a8n: Don't create changeset when ID is invalid
#### Steps to reproduce:

1. Go to campaigns
2. Add a changeset manually, using a _not_ existing ID
3. See dev stack log output

#### Expected behavior:
The error is thrown and it's forgotten about.

#### Actual behavior:
The changeset still get's created and is getting synced over and over again, logging messages like the below: 

```
repo-updater | ERROR PreSync, error: error in GraphQL response: Could not resolve to a PullRequest with the number of 65526.
```

### PR DESCRIPTION
**Pull request by mrnugget**
This fixes #6535 by extending the transaction to also include the
syncing of the to-be-created changesets.

With that, the transaction rolls back and doesn't create potentially
invalid changesets in case one of them cannot be synced.

That is much better than adding invalid state to the database which then
leads to the changesets syncer failing to sync changesets every time.

Test plan:

### CODE REVIEW

File: enterprise/pkg/a8n/resolvers/resolver.go [hunk 1]
```diff
@@ -366,11 +366,6 @@ func (r *Resolver) CreateChangesets(ctx context.Context, args *graphqlbackend.Cr
 		}
 	}
 
-	tx.Done()
-
-	// Only fetch metadata if none of these changesets existed before.
-	// We do this outside of a transaction.
-
 	store = repos.NewDBStore(r.store.DB(), sql.TxOptions{})
```
Comment (tsenart) [inline enterprise/pkg/a8n/resolvers/resolver.go]:
```suggestion
	store = repos.NewDBStore(tx.DB(), sql.TxOptions{})
```
