### PR TITLE
batches: add read only external state

### LINKED ISSUE #26820: Open batch change changesets are not updated if the repo is archived while they're open
Original source: https://sourcegraph.slack.com/archives/C02BJ8T258D/p1635458039067400

### Steps to reproduce

1. Create a batch change that publishes a changeset to repo `X` (the report is on GitHub, but I'd assume this is going to be true for all code hosts).
2. Archive `X` on the code host, making it read only. All PRs are locked at this point.
3. Observe that Batch Changes still thinks the PR is open, and the PR cannot be closed within the batch change.

### Planned solution

Add a new terminal state that behaves like `closed` but is displayed differently to avoid confusion. (Name TBC, since we already have a concept of "archiving" that's different in Batch Changes.)

We need to be able to migrate both into and out of that state as repositories are archived and unarchived.

For now, we'll only do this on changeset sync or reconciler error, but an obvious future enhancement would be to also update changeset state when `repo-updater` becomes aware of a repo being archived or unarchived. (Indeed, Batch Changes could also update the repo once if it becomes aware before `repo-updater`.) The main technical challenge here is that it crosses the open source/enterprise boundary, and would probably need some new plumbing. (Maybe a notification queue via Redis on `repo-updater` events?)

### Reconciler errors to handle

We want to detect useful errors in both the `push` and `update` operations. We'll probably have to do this the old fashioned way with string comparisons in most cases.

<table>
<thead>
<tr><th>Code host</th><th>On push</th><th>On update</th>
</thead>
<tbody>
<tr>
<td>GitHub</td>
<td>
<pre><code>ERROR: This repository was archived so it is read-only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.</code></pre>
</td>
<td><pre lang="json"><code>{
  "data": {
    "updatePullRequest": null
  },
  "errors": [
    {
      "type": "UNPROCESSABLE",
      "path": [
        "updatePullRequest"
      ],
      "locations": [
        {
          "line": 314,
          "column": 3
        }
      ],
      "message": "Repository was archived so is read-only"
    }
  ]
}
</code></pre></td>
</tr>
<tr>
<td>GitLab</td>
<td><pre><code>remote:
remote: ========================================================================
remote:
remote: ERROR: You are not allowed to push code to this project.

remote:
remote: ========================================================================
remote:
fatal: Could not read from remote repository.</code></pre></td>
<td>403 Forbidden (no other useful message to disambiguate)</td>
</tr>
<tr>
<td>Bitbucket Server</td>
<td rowspan="2" colspan="2">No concept of archiving a repo, or making it completely read only</td>
</tr>
<tr>
<td>Bitbucket Cloud</td>
</tr>
</tbody>
</table>

### PR DESCRIPTION
**Pull request by LawnGnome**
### Note for Repo Management (hello!)

I've requested a review from you because this is adding a new place that mutates the `repo` table, specifically to flip the `archived` column if Batch Changes notices that a repo is archived before `repo-updater`. Let me know how you feel about that, please!

### Actual description

This PR adds a new "read only" external state that is mostly terminal[^1] and used when the repository a changeset is open on is archived. No bulk operations can be performed on those changesets, and re-applying the batch spec will not result in any operations.

When reconciling a changeset, we will detect archived repos based on the response from the code host when updating or pushing changesets. (We can also detect this when creating changesets, and the underlying code host calls will return the right error here so the user gets a good error message, but we obviously then won't have a changeset to enter the read-only state!) This PR adds the plumbing for this with a new `errcode.IsArchived` function, but does not actually add the code host support, which are in #38332 and #38333 for GitLab and GitHub, respectively. (The Bitbuckets do not support archiving repos, and are hence out of scope for this project.)

There are a couple of interesting quirks to this implementation:

1. We ultimately have to rely on the `archived` field of the `repo` table to determine the behaviour, since the only alternative would be to burn code host quota by pinging the code host each time we want to touch a repo. This means that we're at the mercy of how often the external service syncer updates repo metadata, particularly when unarchiving.
2. It's possible that the reconciler will be the first part of Sourcegraph to learn that a repository has been archived. Because of the previous point, we need to update `repo` so that we can calculate the derived state correctly — this has been implemented, but definitely feels a little weird, since normally the only thing that will update `repo` is `repo-updater`. The other option was to force an immediate sync, but `repo-updater` doesn't support only syncing one repository on an external service, and the underlying operations are intentionally asynchronous. Performing a direct `UPDATE` felt like the lesser of the two possible evils.

Related to #26820, but the actual fix will be a subsequent PR.

### Future work

* Hook changes to the `repo.archived` field to more efficiently update the external state of changesets, since right now there's going to be a non-trivial delay between a repo being (un)archived and changesets being updated. The major problem here is that it crosses the FOSS/enterprise boundary the "wrong" way, which requires either a nullable callback or some sort of broader solution for notifying disparate parts of the codebase when an event occurs.

## Test plan

Added unit tests for basically everything that was changed or added.

Additionally:

* Attempted to publish changesets to archived repos, and ensured that we got a sensible error.
* Attempted to update changesets on repos that had been archived, and ensured that the changesets entered the read only state.
* Attempted to push a commit to repos that had been archived, and ensured that the changesets entered the read only state.
* Synced read only changesets on repos that had been unarchived, and ensured that the changesets entered the correct, non read only state.

---

[^1]: Why isn't it actually terminal? The main reason is that repositories can be unarchived, so we need to be able to revive changesets. The way this has been implemented is by allowing syncs to proceed for read only changesets only to the point where we check if the repo is archived — if it is, then that's the end of the sync; otherwise we perform a full sync, which will reset the changeset's external state.

### CODE REVIEW

**Review by Piszmog — APPROVED** [review]
Code-wise, LGTM

**Comment by ryanslade** [comment]
(Sorry, mis-click)

File: enterprise/internal/batches/state/state.go [hunk 1]
```diff
@@ -34,6 +35,15 @@ func SetDerivedState(ctx context.Context, repoStore database.RepoStore, c *btype
 	sort.Sort(events)
 
 	logger := log.Scoped("SetDerivedState", "")
+
+	// We need to use an internal actor here as the repo-updater otherwise has no
```
Comment (eseliger) [inline enterprise/internal/batches/state/state.go:39]: `repo-updater`? Did you mean repo store?

**Review by eseliger — APPROVED** [review]
nice solution, looks very clean :)

File: enterprise/internal/batches/state/state.go (hunk 1 above)
Comment (LawnGnome) [reply enterprise/internal/batches/state/state.go:39]: This was a straight cut and paste from [here](https://github.com/sourcegraph/sourcegraph/pull/38265/files#diff-c391e5ac1b95c337506be0266691dd15d0fbabe368c684415be33a9322689412L689-L690), but I suspect that comment was a bit outdated. I'll reword it.

File: client/web/src/enterprise/batches/detail/changesets/ChangesetFileDiff.tsx [hunk 2]
```diff
@@ -149,6 +149,7 @@ function commitOIDForGitRevision(revision: GitRefSpecFields): string {
 
 const DiffRenderingNotSupportedAlert: React.FunctionComponent<React.PropsWithChildren<{}>> = () => (
     <Alert className="mb-0" variant="info">
-        Diffs for processing, merged, closed and deleted changesets are currently only available on the code host.
+        Diffs for processing, merged, closed, read only, and deleted changesets are currently only available on the code
```
Comment (courier-new) [inline client/web/src/enterprise/batches/detail/changesets/ChangesetFileDiff.tsx:152]: My guess is we want "read-only" for describing this state: https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/r/read-only

I was tempted, but I won't go crazy and comment on every instance of this in your PR. 😜

Comment (courier-new) [reply client/web/src/enterprise/batches/detail/changesets/ChangesetFileDiff.tsx:152]: Also, 💙 that you added the Oxford comma.

File: enterprise/internal/batches/state/counts.go [hunk 3]
```diff
@@ -96,7 +96,10 @@ func CalcCounts(start, end time.Time, cs []*btypes.Changeset, es ...*btypes.Chan
 
 			case btypes.ChangesetExternalStateMerged:
 				c.Merged++
-			case btypes.ChangesetExternalStateClosed:
+			case btypes.ChangesetExternalStateClosed,
+				btypes.ChangesetExternalStateReadOnly:
+				// We'll lump read only into closed, rather than trying to add another
+				// state.
```
Comment (courier-new) [inline enterprise/internal/batches/state/counts.go:102]: Ought we to document this somewhere? Maybe the best approach would be to add an FAQ blurb about archived repos/read-only changesets more generally, and then this could just be part of that.

**Review by courier-new — APPROVED** [review]
Indeed, extremely clean! Gets my stamp of approval, beyond a couple documentation-related comments. 😄

File: client/web/src/enterprise/batches/detail/changesets/ChangesetStatusCell.tsx [hunk 4]
```diff
@@ -158,3 +163,16 @@ export const ChangesetStatusArchived: React.FunctionComponent<React.PropsWithChi
...
 )
+
+export const ChangesetStatusReadOnly: React.FunctionComponent<React.PropsWithChildren<ChangesetStatusIconProps>> = ({
+    label = <span>Read only</span>,
+    className,
+    ...props
+}) => (
+    <Tooltip content="This changeset is read only, and cannot be modified. This is usually caused by the repository being archived.">
+        <div className={classNames(iconClassNames, className)} {...props}>
+            <LockIcon role="presentation" />
```
[the remark this answers is not in the document]
Comment (danielmarquespt) [reply client/web/src/enterprise/batches/detail/changesets/ChangesetStatusCell.tsx:174]: I think a Lock works for communicating read-only :)

File: client/web/src/enterprise/batches/detail/changesets/ChangesetFileDiff.tsx (hunk 2 above)
Comment (LawnGnome) [reply client/web/src/enterprise/batches/detail/changesets/ChangesetFileDiff.tsx:152]: Oddly enough, my omission of the hyphen was largely because it read as more American to me. 🦅 

I will defer to your expertise on this matter. 😆

File: enterprise/internal/batches/state/counts.go (hunk 3 above)
Comment (LawnGnome) [reply enterprise/internal/batches/state/counts.go:102]: Yeah, we'll need a note for this somewhere. I'll try to remember to put it into the final cleanup PR that has the changelog entry and docs.
