### PR TITLE
Webext polyfill fixes

### LINKED ISSUE #3361: Regression (not yet published) in browser extension
@felixfbecker I think your change at https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/88537f3ebe77b32fb132bdd84a2ec5384efea207#diff-e436809213b3fca50e3bfcde92ac2fe0 broke the browser extension (not yet published though). Now `requestGraphQL`'s emission is `{result: {data, errors}}` not just `{data, errors}`, which causes all `requestGraphQL` calls to fail (because they usually pipe to a `map(({data, errors}) => ...)`.

cc @lguychard

### PR DESCRIPTION
**Pull request by lguychard**
Fixes #3361 

##### Code Hosts

- [x] GitHub
- [ ] GitHub Enterprise
- [ ] Refined GitHub
- [ ] Phabricator
- [ ] Phabricator integration
- [ ] Bitbucket
- [ ] Gitlab

##### Browsers

- [x] Chrome
- [x] Firefox

### CODE REVIEW

File: client/browser/src/extension/scripts/auto-reloading.ts [hunk 1]
```diff
@@ -1,4 +1,5 @@
 import io from 'socket.io-client'
+import '../../config/polyfill'
```
Comment (felixfbecker) [inline client/browser/src/extension/scripts/auto-reloading.ts]: Polyfills should be imported before libraries (need to add an empty new line in between)

File: client/browser/src/shared/backend/graphql.tsx [hunk 2]
```diff
@@ -57,7 +57,14 @@ export const requestGraphQL: typeof performRequest = (args: GraphQLRequestArgs)
         return performRequest(args)
     }
 
-    return from(browser.runtime.sendMessage({ type: 'requestGraphQL', payload: args }))
+    return from(browser.runtime.sendMessage({ type: 'requestGraphQL', payload: args })).pipe(
+        map(({ result, err }) => {
```
Comment (felixfbecker) [inline client/browser/src/shared/backend/graphql.tsx]: 🤦‍♂️
