### PR TITLE
extensibility: extension registry redesign

### LINKED ISSUE #15933: Un-hide language extensions on the extensions registry direct link to language extensions
https://sourcegraph.com/extensions?query=category%3A%22Programming+languages%22 takes you to 
image

But it should take you to 
image

We need to just make it so "show more extensions" doesn't hide the actual extensions if the url has the direct category query in it. 

This bug arose in #15927 and this link is useful for direct-linking interested parties to the languages supported.

### LINKED ISSUE #20779: Card redesign: standard layout
### Description

This issue changes the layout of the standard extension card.

[Figma](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/RFC-305-Next-Up-Extensions-Registry-Marketplace-Concepts-Review?node-id=714%3A8)

### Specification

- [ ] move the logo/icon to the header
- [ ] move the publisher to the separate row
- [ ] make the description two lines long
- [ ] move the toggle (add the enabled / disabled label)

New elements:
- [ ] add the header background (details about backgrounds available in the separate issue TODO)
- [ ] add number of users / installs
- [ ] Add the star rating (possibly later, as a separate project TBD)

### New design vs. current version

Screenshot 2021-05-08 at 16 04 51
Screenshot 2021-05-08 at 16 04 17

### LINKED ISSUE #20781: Card redesign: define default header colors
### Description

This issue adds default color values to extension card headers.

[Figma](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/RFC-305-Next-Up-Extensions-Registry-Marketplace-Concepts-Review?node-id=676%3A1242)

### Specification

Light theme (all 10% opacity):
- Blue: OC-indigo-3
- Yellow: OC-yellow-5
- Orange: OC-yellow-9 (not a mistake, please use yellow color here)
- Pink: OC-pink-5
- Red: OC-red-9
- Purple: OC-grape-9
- Green: OC-green-9
- Grey: OC-grey-9

Dark theme (all 15% opacity):
*The same as for the light theme except for:
- Pink: OC-pink-7
- Grey: OC-grey-7

### LINKED ISSUE #20782: Card header colors: add ability to assign color when authoring extension or assign random
### Description

This issue adds the ability to change header colors for the extension authors. Also, if the author hasn't assigned any color, we should randomly assign one from the list.
 
### Specification
Colors are listed in the issue #20781 

- [ ] Add the ability to assign the header color from the list
- [ ] Assign a random color from the list if the extension author hasn't defined it. Once assigned, color should stay the same for the extension unless the author changes it (Color shouldn't be randomly assigned every time the page loads!)
- [ ] Update the [docs](https://docs.sourcegraph.com/extensions/authoring) to inform about this new ability. Please, list the available herder colors.

### LINKED ISSUE #20784: Add 'enable for all users' toggle for the admins
### Description

This issue adds 'enable for all' toggle for the admins:
- to the extension card
- to the extension details page

### Specification
'Enable/Disable for all users' enables/diables extension for the whole org. Currently, this is being done in the settings by editing the JSON. Current settings need to be reflected by enabled/disabled extensions. This change in the interface shouldn't reset the current settings for customers (!)

The extension card:
- [design: regular](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/RFC-305-Next-Up-Extensions-Registry-Marketplace-Concepts-Review?node-id=671%3A948)
- [design: featured](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/RFC-305-Next-Up-Extensions-Registry-Marketplace-Concepts-Review?node-id=756%3A28385)
- change the other toggle label from ~~'enable/disable~~ to 'enable/disable only for me'

The extension details page
- [design](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/RFC-305-Next-Up-Extensions-Registry-Marketplace-Concepts-Review?node-id=676%3A714)
- change the big toggle to the small toggle
- add 'enable/disable for me' label

### LINKED ISSUE #20786: Card redesign: change 'WIP' label to 'EXPERIMENTAL'
### Description

This issue changes the 'WIP' label to 'EXPERIMENTAL'

[Slack conversation](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1620155953002000) for more context

### Specification

- label: EXPERIMENTAL
- Color: info (not warning as it was so far)
- [Figma](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/RFC-305-Next-Up-Extensions-Registry-Marketplace-Concepts-Review?node-id=761%3A2410)

### LINKED ISSUE #20789: Registry redesign: add left navigation
### Description

This issue adds the left navigation to the extension registry.

*This issue doesn't update the categories.

Screenshot 2021-05-09 at 22 35 32

### Specification

[Figma](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/RFC-305-Next-Up-Extensions-Registry-Marketplace-Concepts-Review?node-id=911%3A8)

- move categories and 'show all' dropdown to left navigation
- add 'Categories' header
- left navigation should have the same styles as [code monitoring](https://www.figma.com/file/Krh7HoQi0GFxtO2k399ZQ6/RFC-227-%E2%80%93-Code-monitoring-actions-and-notifications?node-id=2119%3A1059) left nav (available after creating your first monitor)
- Left nav should always have the same width (200px), leaving remaining space in the container for the search and extension cards

### LINKED ISSUE #20790: Registry redesign: update the page description
### Description

This issue changes the page description and takes it out of the header.

### Specification

[Figma](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/RFC-305-Next-Up-Extensions-Registry-Marketplace-Concepts-Review?node-id=634%3A25279)

- change the description to: _Connect all your other tools to get things like test coverage, 1-click open file in editor, custom highlighting, and information from your other favorite services all in one place on Sourcegraph.
- place it above the search bar

### LINKED ISSUE #20956: Refresh: extension registry card animation does not work
Part of #20903.

- Alert icon appears on the body since we use the `alert-success` class. Use the color directly instead of the class to fix.
- Glow no longer appears. Should re-evaluate the current animation approach.

#### Refreshed registry

Screenshot from 2021-05-13 16-22-44

#### Enabled extension

Screenshot from 2021-05-13 16-22-52

### LINKED ISSUE #21007: New styles for 'create own extension' banner
### Description

This issue changes the styles of 'create own extension banner'

### Specification

[Figma](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/RFC-305-Next-Up-Extensions-Registry-Marketplace-Concepts-Review?node-id=758%3A1010)

- remove the background
- add a divider between the extension list and the banner
- text max width 700px
- use H2 instead of H3

### New and the previous version comparison
Screenshot 2021-05-17 at 08 55 21
Screenshot 2021-05-17 at 08 55 04

### LINKED ISSUE #21011: Remove 'show all extensions' button from the registry
### Description

This issue removed the 'show all extensions' button from the registry.

### Reasoning
@muratsu raised an interesting concern: do we need the 'show more extensions' button at all? 

What it does: it shows the language extensions
Why it's there: we've hidden language extensions as we don't want users to turn them on and off. Also those are not really the 'extensions' in traditional users' understanding. They are more of 'code intel must-haves'

Decision: Remove the button
Why: It's taking up space and causes [problems in the interface](https://github.com/sourcegraph/sourcegraph/pull/20822#issuecomment-842013172) when there is a button for 'show all category' in the category above. 'Languages' is accessible as a category in the left menu, if users need it.
Please note: we should show 'Other' as the last category in the registry. Only 'Languages' should be hidden.

@Joelkw FYI since you're on vacation

### PR DESCRIPTION
**Pull request by tjkandala**
### Registry redesign

Closes #20789, closes #20790, closes #21011, closes #21007

#### #20789
- categories and 'show all' dropdown moved to left navigation
- now can only view 1 category at a time (expect on 'All')
- sync URL with category state
- append category to search query before request to improve category link performance

#### #20790 
- updated page description

#### #21011
- remove "show more extensions" button that revealed programming language extensions

#### #21007
- update "create own extension" banner styles

### Card redesign

Closes #20779, closes #20781, closes #20782, closes #20784, closes #20786

#### #20779 
- icon moved to header
- publisher moved to separate row
- description is 2 lines long
- toggle has been moved to third section
- defer number of users / installs + star ratings to future PR (likely along with featured extensions)

#### #20781 
- add set of default extension card header colors (via CSS module)

#### #20782 
- allow extension authors to select header color (add `headerColor` to extension manifest schema)
- if no (or invalid) `headerColor` is specified in the manifest, select a pseudo-random header color (stable for a given extension ID)
- docs update in seperate PR (cc @AlicjaSuska)

#### #20784
- add extra toggle for site admins to enable extension in global settings

#### #20786 
- change WIP label to EXPERIMENTAL (not yet in manifests, just for badge on extension card)

### Bonus

Fix #15933
- Category is a separate query parameter now, and the category selector component is synchronized with the URL, so new links (in the form of `"{SOURCEGRAPH_URL}/extensions?category=Programming+languages"`) to the extension registry shouldn't hide programming languages. 

Fix #20956
- Fix extension card "enabled feedback" animation for the refresh (code is a lot simpler now too!).
<details>
<summary>Animation with refresh toggled</summary>

</details>

### Current state

Screenshot from 2021-05-13 14-24-01

### Questions:
- Should we worry about left navigation for mobile? I tried to draw inspiration from code monitoring, but its left navigation doesn't have a fixed 200px width like ours.
- Should we show the extension authoring banner for all categories? Not all users will reach the bottom of 'All' (more than before though since we limit each category to 6 extensions).

### CODE REVIEW

File: client/web/src/extensions/ExtensionCard.tsx [hunk 1]
```diff
@@ -278,7 +341,33 @@ export const ExtensionCard = memo<Props>(function ExtensionCard({
...
+/**
+ * Pseudorandom header color for extensions that haven't set `headerColor` in their manifest.
+ */
+function headerColorFromExtensionID(extensionID: string): ExtensionHeaderColor {
+    const dividend = [...extensionID].reduce((sum, character) => (sum += character.charCodeAt(0)), 0)
+    const divisor = extensionHeaderColors.length
+    const remainder = dividend % divisor
+
+    return extensionHeaderColors[remainder] || 'blue' // Fallback, but should never reach this state
+}
```
Comment (tjkandala) [inline client/web/src/extensions/ExtensionCard.tsx:373]: @muratsu this is basically an even worse version of the `hashCode` function we just got rid of, but it gets the job done here

File: client/shared/src/extensions/extensionManifest.ts [hunk 2]
```diff
@@ -82,6 +84,15 @@ export function parseExtensionManifestOrError(input: string): ExtensionManifest
         if (value.icon && typeof value.icon !== 'string') {
             problems.push('"icon" property must be a string')
         }
+        if (value.iconDark && typeof value.iconDark !== 'string') {
+            problems.push('"iconDark" property must be a string')
+        }
+        if (
+            value.headerColor &&
+            (typeof value.headerColor !== 'string' || !EXTENSION_HEADER_COLORS.has(value.headerColor))
```
Comment (tjkandala) [inline client/shared/src/extensions/extensionManifest.ts:92]: @muratsu just validating new manifest fields. I didn't add validation for `iconDark` back when I added it (first extension registry refresh), so I added it now

File: client/branded/src/global-styles/colors.scss [hunk 3]
```diff
@@ -126,6 +126,7 @@ $text-muted: var(--text-muted);
     --web-content-link-color: #1c7cd6;
     --disabled-action-bg-color: #{$oc-gray-3};
     --disabled-action-text-color: #{$oc-gray-5};
+    --alert-success-text-color: #20612e;
```
Comment (tjkandala) [inline client/branded/src/global-styles/colors.scss:129]: @sourcegraph/frontend-platform Is there a better way to reach into the `.alert-success` color and opt out of the alert icon?

**Comment by muratsu** [comment]
https://user-images.githubusercontent.com/1308560/118436713-23fc0280-b696-11eb-9908-1d0825a34596.mov

1. I wish the switch had a smooth animation like this (https://material-ui.com/components/switches/)
2. Once enabled, should we multiply the header color with some green like this implementation or should we temporarily use a fixed green color?
3. The pulse animation is substantially shorter than the overall green effect. Should we shorten the total animation time? Pulse is ~2s but the card remains green much longer.

**Comment by muratsu** [comment]
Bug: Currently there doesn't seem to be a way to show all the enabled extensions on one page.

Steps: 
1. From the left menu select `Show Enabled`
2. Scroll down. 


Actual
The button under Programming Languages says `Show full category`

Expected
The button under Programming Languages says `Show more`?

**Comment by muratsu** [comment]
On the bottom of the page `show more extensions` is hard to discover.

image

File: client/web/src/extensions/ExtensionCard.tsx [hunk 4]
```diff
@@ -102,39 +122,20 @@ export const ExtensionCard = memo<Props>(function ExtensionCard({
...
+            setChange(enabled ? 'enabled' : 'disabled')
             // Common: clear possible error, queue timeout to clear change feedback
             setOptimisticFailure(null)
             optimisticFailureManager.cancelTimeout()
             feedbackManager.setTimeout(() => {
                 setChange(null)
             }, FEEDBACK_DELAY)
         },
-        [feedbackManager, startAnimationManager, endAnimationManager, optimisticFailureManager]
+        [feedbackManager, optimisticFailureManager]
```
Comment (muratsu) [inline client/web/src/extensions/ExtensionCard.tsx:138]: moving the animation to the css is a really great idea 👍

File: client/branded/src/global-styles/colors.scss (hunk 3 above)
Comment (valerybugakov) [reply client/branded/src/global-styles/colors.scss:129]: The color is used [here](https://github.com/sourcegraph/sourcegraph/pull/20822/files#diff-05fc0583cb0b237cb20ad9ffd70974be241ef29111a720839027e8a29f0011aaR63), but I cannot find a use case for it in [Figma mockups](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/RFC-305-Next-Up-Extensions-Registry-%22Marketplace%22-Concepts-%5BReview%5D?node-id=714%3A8). 
@muratsu, maybe you have an idea of where it's used in the actual UI?

File: client/web/src/extensions/ExtensionCard.tsx (hunk 1 above)
Comment (muratsu) [reply client/web/src/extensions/ExtensionCard.tsx:349]: Fun fact: The strings in JS are UTF-16 coded, meaning for some new characters we actually use surrogate pairs. Emojis are one such case.
```
var x = "👉hi😁";
for (z=0;z<x.length;z++) console.log(x.charCodeAt(z))
```
This code will print `55357 56393 104 105 55357 56833`. If you ever want to iterate chars of a string, it's best to use for..of as it will treat surrogate couples as one char

File: client/branded/src/global-styles/colors.scss (hunk 3 above)
Comment (valerybugakov) [reply client/branded/src/global-styles/colors.scss:129]: It looks like this color is used for extension description text during the `--enable` animation. Is it important here to match the `.alert-success` color?  

I would suggest either keeping text color unchanged during the animation or picking the color from the OC color palette or our own CSS variables list because:

- after the redesign, alerts will use only colors defined in our CSS variables
- colors from our design system should be preferred over custom colors if possible

Screenshot 2021-05-17 at 10 06 27

File: client/web/src/extensions/ExtensionCard.scss [hunk 5]
```diff
@@ -1,53 +1,74 @@
...
-        .theme-dark & {
-            box-shadow: 0 0 0 6px rgba($success, 0.7);
+        &--featured {
+            -webkit-line-clamp: 3;
         }
     }
 
-    &__shadow--show {
-        opacity: 1;
+    &--enabled {
```
Comment (valerybugakov) [inline client/web/src/extensions/ExtensionCard.scss:60]: For some reason, the "Enabled for me" toggle goes `on` -> `off` -> `on` for me locally. Steps to reproduce:

1. Clone this branch.
2. Run `sg run enterprise-web-standalone`.
3. Open http://sourcegraph.test:3443/extensions?category=All.
4. Disable and enable `search-insights` extension.

Let me know if I missed some configuration steps.

Screen Recording 2021-05-17 at 10 19 21

File: client/web/src/extensions/ExtensionCard.scss [hunk 6]
```diff
@@ -1,53 +1,74 @@
...
+        animation: extension-card__glow 2s ease-out;
+        background-color: rgba($success, 0.2);
```
Comment (valerybugakov) [inline client/web/src/extensions/ExtensionCard.scss:62]: The border that separates sections of the extension card is mostly invisible during the `--enabled` animation. It would be great to keep contrast high enough even during the animation.

Screenshot 2021-05-17 at 10 25 10

**Review by valerybugakov — COMMENTED** [review]
Registry redesign looks great, huge work @tjkandala 💪
Since I looked into the alert-color question, I quickly looked at the changes and left a couple of optional comments.

**Review by AlicjaSuska — CHANGES_REQUESTED** [review]
Thank you for all the changes @tjkandala . Here are my notes. I've also created the '[Design QA](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/?node-id=975%3A2591)' page in Figma to show some of the changes that need to be done.

- [x] padding in the card is not aligned with the design ([Figma](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/RFC-305-Next-Up-Extensions-Registry-Marketplace-Concepts-Review?node-id=975%3A2667))
- [x] we should use H3 for the extension name, not 'font-weight-bold’ class
- [x] Change label from ~~'not enabled for all the users'~~ to 'disabled for all the users
- [x] Remove extra 8px margin from below the search bar
- [x] Change top and bottom margin for 'create extension' banned to 48px. I've added a separate issue for the banner changes #21007 btw
- [x] When clicking on the categories in the left menu, the transition is very slow. It looks like there is some delay, should be instant. I've recorded the [loom video](https://www.loom.com/share/b76efd591f094be0aa82a923b2ab3076) to show it.
- [x] We're missing the hover state for the left nav items. It should be $bg-2 (design from code monitoring mockups):
Screenshot 2021-05-17 at 09 36 17

- [x] Animation when turning on the extension: as a quick fix, can you remove the background from the card and leave only the green border (outside of the card area)? That would already look way better.

File: client/web/src/extensions/ExtensionCard.scss (hunk 6 above)
Comment (AlicjaSuska) [reply client/web/src/extensions/ExtensionCard.scss:62]: Please, see the comment below: I'd like to remove this green background from the card area entirely and only keep the border animation :)

**Comment by AlicjaSuska** [comment]
Probably outside of the scope of this issue: there is something wrong going on with the header: button is misaligned, the icon is too small:
Screenshot 2021-05-17 at 09 20 42

**Comment by AlicjaSuska** [comment]
I agree with @muratsu - let's remove the 'show more extensions' button - full issue and reasoning here: #21011 @tjkandala @Joelkw

File: client/web/src/extensions/ExtensionCard.tsx (hunk 1 above)
Comment (tjkandala) [reply client/web/src/extensions/ExtensionCard.tsx:349]: Interesting, this was definitely going to bite me one day!

File: client/branded/src/global-styles/colors.scss (hunk 3 above)
Comment (tjkandala) [reply client/branded/src/global-styles/colors.scss:129]: Sorry, the animation was implemented during the last registry refresh and I don't think it was in Figma (ad hoc implementation). Thanks for the suggestion, looks like we're scrapping the card color changes, only keeping the "glow"

File: client/web/src/extensions/ExtensionCard.tsx [hunk 7]
```diff
@@ -143,142 +144,206 @@ export const ExtensionCard = memo<Props>(function ExtensionCard({
...
-                                            'font-weight-bold': isSourcegraphExtension,
-                                        })}
-                                    >
-                                        {publisher}
-                                    </span>
+                    <div className="mt-3 mb-2 extension-card__description mr-3">
+                        {extension.manifest ? (
+                            isErrorLike(extension.manifest) ? (
+                                <span className="text-danger small" title={extension.manifest.message}>
+                                    <WarningIcon className="icon-inline" /> Invalid manifest
```
[the remark this answers is not in the document]
Comment (tjkandala) [reply client/web/src/extensions/ExtensionCard.tsx:250]: I'll add stories to Storybook so we can check it out

File: client/web/src/extensions/ExtensionRegistrySidenav.tsx [hunk 8]
```diff
@@ -0,0 +1,79 @@
...
+ */
+export const ExtensionRegistrySidenav: React.FunctionComponent<
+    ExtensionsCategoryFiltersProps & ExtensionsEnablementDropdownProps
+> = ({ selectedCategory, onSelectCategory, enablementFilter, setEnablementFilter }) => {
+    const [isOpen, setIsOpen] = useState(false)
+    const toggleIsOpen = useCallback(() => setIsOpen(open => !open), [])
+
+    const showAll = useCallback(() => setEnablementFilter('all'), [setEnablementFilter])
+    const showEnabled = useCallback(() => setEnablementFilter('enabled'), [setEnablementFilter])
+    const showDisabled = useCallback(() => setEnablementFilter('disabled'), [setEnablementFilter])
```
[the remark this answers is not in the document]
Comment (tjkandala) [reply client/web/src/extensions/ExtensionRegistrySidenav.tsx:37]: I usually opt for `useCallback` when passing callbacks to components from external libraries since I don't want to make any assumptions about potential memoization of those components. I could read the implementation and find that it's not memoized now, but that could change over time, so I wrap callbacks with `useCallback` anyways.

In this case, even if `<DropdownItem>` is memoized, it's probably not so complex that unnecessary re-rendering would have a noticeable impact on performance.

File: client/web/src/extensions/ExtensionCard.scss (hunk 5 above)
Comment (tjkandala) [reply client/web/src/extensions/ExtensionCard.scss:62]: I haven't been able to sign in on the standalone web server, but I have a theory as to why this is happening. 

The extension toggle reflects the optimistic enabled state, but synchronizes with the actual enabled state whenever it changes (in case e.g. an admin enables the extension for all users [optimistic], then the merged settings are returned which determine that it's enabled for them as well [if not explicitly disabled in user settings]). If the settings just didn't update, it wouldn't go back to off like this, so it looks like there's a temporary settings change that reflects the optimistic state, then another settings change that rolls it back. It also doesn't seem like a network error related to the settings mutation, or else we'd show an alert.

**Comment by tjkandala** [comment]
@AlicjaSuska 

> * [ ]  we should use H3 for the extension name, not 'font-weight-bold’ class

It's already an `<h3>` (with `<a>` nested inside), but `.font-weight-bold` is redundant now, good catch

> * [ ]  Change label from ~'not enabled for all the users'~ to 'disabled for all the users

I intentionally changed the copy [here](https://github.com/sourcegraph/sourcegraph/pull/20740) since we can't guarantee that it is _disabled_ for all users, just that we haven't set it to be enabled by default because users can override those settings (user settings > site settings). Should we still change it back?

File: client/web/src/extensions/ExtensionRegistrySidenav.tsx (hunk 8 above)
[the remark this answers is not in the document]
Comment (valerybugakov) [reply client/web/src/extensions/ExtensionRegistrySidenav.tsx:37]: Is there any risk in passing the unmemoized `onClick` handler to the `<DropdownItem>` regardless of its internal implementation? 

Generally, if the component is simple enough: e.g., it's a layout with many children or a complex visual graphic, it should be ok to omit any optimizations.

File: client/web/src/extensions/ExtensionCard.scss (hunk 5 above)
Comment (valerybugakov) [reply client/web/src/extensions/ExtensionCard.scss:67]: 1. About standalone web server credentials: we have `k8s.sgdev.org admin user` in 1Password that can be used to log in to the web server. 
2. I was able to reproduce this behavior locally with our `frontend` server. The issue is visible if you enable network throttling to "Slow 3G": 
Screenshot 2021-05-18 at 10 57 45

This issue is noticeable with the standalone web server because it has native latency to reach the deployed API instance. To reproduce it: 
1. Enable network throttling.
2. Enable and disable the extension.
3. See how changes will be reflected in the UI

Screen Recording 2021-05-18 at 10 54 02

File: client/web/src/extensions/ExtensionCard.scss (hunk 6 above)
Comment (valerybugakov) [reply client/web/src/extensions/ExtensionCard.scss]: Btw, I like how enable-animation looks after the update 🙂

File: client/web/src/extensions/ExtensionCard.scss (hunk 5 above)
Comment (tjkandala) [reply client/web/src/extensions/ExtensionCard.scss:67]: Seems like it's not a good idea to try to synchronize the toggle state with settings, since it'll lead to this confusing behavior any time the user toggles before the settings from the previous mutation have been received from the API. 

I can think of two fixes here (problem: top toggle state depends on the bottom toggle, truth is computed in the backend):
1) Don't synchronize toggle state with settings, rather compute optimistic state for both toggles from previous settings.
2) Don't be optimistic, rather add a loading state to the `<Toggle>` component. 

I think 1 is unnecessarily complex, especially considering that this UI will only be seen by site admins. @AlicjaSuska what do you think about the toggle loading state? We could add this along with the

Comment (tjkandala) [reply client/web/src/extensions/ExtensionCard.scss:67]: @muratsu @AlicjaSuska @Joelkw We will tackle this issue for 3.29 as it shouldn't be a release blocker. We'll focus on featured extensions first, then return to these UX issues (#21062, #21063)

**Review by AlicjaSuska — APPROVED** [review]
Awesome work @tjkandala ! There is one thing (not a blocker) - could you remove the bottom padding from this element? It adds to the divider padding and the space is too big. Thank you!

Screenshot 2021-05-19 at 20 21 22
