### PR TITLE
Bug fix: Setup Wizard > Re route non-admin users

### LINKED ISSUE #49267: Setup Wizard: Non admin user fix
A non-admin user cannot add/remove code hosts. Therefore, should they be able to view the Setup Wizard?

We should either re-direct non-admin users, or allow a view only mode and disable all form fields. It's confusing to be able to edit form fields when the connection call fails & editing is not actually allowed.

Next button shouldn't read `Loading` when no action has taken place for non-admin users.
Screenshot 2023-03-13 at 2 05 25 PM
Screenshot 2023-03-13 at 2 05 41 PM
Screenshot 2023-03-13 at 2 18 44 PM

### PR DESCRIPTION
**Pull request by st0nebraker**
Closes #49267. Only makes Setup Wizard route available for non admin users.

### BEFORE
image

### AFTER
image

## Test plan
- Login with a non site admin user
- Ensure navigating to `/setup` redirects

## App preview:

- [Web](https://sg-web-becca-bug-fix-reroute-nonadmin-on.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (+0.03 kb) | 0.00% (+0.03 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/becca/bug-fix-reroute-nonadmin-on-setup-w/compare-report.html;tab=live_object) for a full comparison between the commits 4a21a5d and 4134830 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

File: client/web/src/LegacyLayout.tsx [hunk 1]
```diff
@@ -132,7 +132,7 @@ export const LegacyLayout: FC<LegacyLayoutProps> = props => {
         return <Navigate replace={true} to={{ ...location, pathname: location.pathname.slice(0, -1) }} />
     }
 
-    if (isSetupWizardPage) {
+    if (isSetupWizardPage && !!props.authenticatedUser?.siteAdmin) {
```
Comment (vovakulikov) [inline client/web/src/LegacyLayout.tsx:135]: I would add this to the Layout.tsx check as well (at the moment we have to support both later legacy will go away)

**Review by vovakulikov — APPROVED** [review]
Oh cool nice catch, thanks

**Comment by vovakulikov** [comment]
Wait a second I think there is a problem with redirection logic, taking a look

File: client/web/src/LegacyLayout.tsx (hunk 1 above)
Comment (vovakulikov) [reply client/web/src/LegacyLayout.tsx:135]: I think we should add this check also to the redirection logic below 

```
if (window.context.needsRepositoryConfiguration && !wasSetupWizardSkipped && props.authenticatedUser?.siteAdmin) {
        return <Navigate to={PageRoutes.SetupWizard} replace={true} />
    }
```

Comment (st0nebraker) [reply client/web/src/LegacyLayout.tsx:135]: Sure thing! Added [here](https://github.com/sourcegraph/sourcegraph/pull/49351/commits/f7f3276e2d5105daa25e0e945a516f956f20b83c)

**Review by vovakulikov — APPROVED** [review]
