### PR TITLE
References pane: fix typing on symbols return type

### LINKED ISSUE #57902: References panel error: r.symbols is not iterable
At https://sourcegraph.com/github.com/vitest-dev/vitest/-/blob/examples/react/vitest.config.ts?L5:16-5:28#tab=references the references panel has an error:

image

---

Not all references panels are erroring. For example, https://sourcegraph.com/github.com/chakra-ui/panda/-/blob/sandbox/codegen/vitest.config.ts?L10:7-10:23#tab=references works fine.

### PR DESCRIPTION
**Pull request by camdencheek**
When go marshals a `nil` slice to JSON, it marshals as `null`. However, unlike in go, null is not treated as an empty slice in javascript. This was causing type errors that showed up in the UI.

Rather than fixing this on the backend side of things (which would be fragile, since it's very conventional to use a nil slice to mean empty slice in go), this makes the field nullable in the typescript type.

Fixes #57902 

## Test plan

No longer seeing the type error in the UI. New tests feel unnecessary since this is just making a type match what the backend actually returns.

### CODE REVIEW

File: client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts [hunk 1]
```diff
@@ -400,7 +400,7 @@ const findSymbol = async (
         return
     }
 
-    for (const symbol of payload.symbols) {
+    for (const symbol of payload.symbols || []) {
```
Comment (vovakulikov) [inline client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts:403]: I don't have any objection about || operator, but I think more standard way to do the same is nullish coalescing operator `??`

```js
 for (const symbol of payload.symbols ?? []) {...
 ```

**Review by vovakulikov — APPROVED** [review]
Nice, lgtm

File: client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts (hunk 1 above)
Comment (camdencheek) [reply client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts]: done, thanks for the tip!
