### PR TITLE
search: fix query intelligence hook

### LINKED ISSUE #23539: regression: monaco query highlighting often fails and makes entire query gray
I saw this cropping up intermittently and finally have a reproducible behavior. Can reproduce on FF and Chrome

Do this:

- Go https://sourcegraph.com/search
- Copy-paste this `repo:^github\.com/sourcegraph/sourcegraph$ \bSearch\b`
- Click the regexp button (don't hit enter)

Ugly, non-highlighted query.

This behavior happens with structural search toggle too. It is not specific to the toggles, I see this often when just navigating to a different file or new search. The toggle method is just a reliable way to reproduce. 

I have bisected and the regression is introduced by https://github.com/sourcegraph/sourcegraph/commit/e2fdeb32ef50f125764e6985798a40c4b9815ff8 in https://github.com/sourcegraph/sourcegraph/pull/22784

I think it's a lazy loading / sync issue?

Vidya:

https://user-images.githubusercontent.com/888624/128118159-f77b2a73-f6db-4b22-bacb-0edecd05cc39.mp4

### PR DESCRIPTION
**Pull request by novoselrok**
Due to the global nature of Monaco (tokens, hover, completion) providers we have to create a unique
language for each editor and register the providers for the new language. This ensures that there is no cross-contamination
between different editors using the query intelligence hook. The main issue with using a single language id
is when a component using the hook gets unmounted. When navigating between pages that both contain a search box (homepage -> search results page), the unmounted useEffect hook below would trigger cleanup after the search results hook already registered its providers. This effectively removes query intelligence from all editors.

Fixes #23539

### CODE REVIEW

**Review by lguychard — APPROVED** [review]
Thank you for the fix!

**Review by eseliger — APPROVED** [review]
🚀

File: client/web/src/search/useQueryIntelligence.ts [hunk 1]
```diff
@@ -21,7 +22,15 @@ export function useQueryIntelligence(
...
     }
-): void {
+): string {
+    // Due to the global nature of Monaco (tokens, hover, completion) providers we have to create a unique
+    // language for each editor and register the providers for the new language. This ensures that there is no cross-contamination
+    // between different editors using the query intelligence hook. The main issue with using a single language id
+    // is when a component using the hook gets unmounted. When navigating between pages that both contain a search box (homepage -> search results page),
+    // the unmounted useEffect hook below would trigger cleanup after the search results hook already registered its providers. This effectively
+    // removes query intelligence from all editors.
+    const sourcegraphSearchLanguageId = useMemo(() => `${SOURCEGRAPH_SEARCH}-${uuid.v4()}`, [])
```
Comment (rvantonder) [inline client/web/src/search/useQueryIntelligence.ts:32]: So like, is this a limitation of Monaco, or our app, that would help us not get tripped up by this state? It sounds a bit like a mix of both? Honestly I'm just happy this is fixed but I'm trying to understand the long term effects / solution here.

Comment (novoselrok) [reply client/web/src/search/useQueryIntelligence.ts:32]: It's a mixture of both. If we could derive everything we need from the query string, then we could register a single set of providers when booting up the web app. But since we have mutable per-editor options like pattern type, case, fetchSuggestions, globbing, etc. that affect highlighting/parsing, we need to register the providers for each editor. And Monaco does not have good support for this. Using a unique language id allows us to simulate per-editor options without having to worry about registering and unregistering the global providers in the correct order.
