### PR TITLE
Remove in-product /help, redirect to docs.sourcegraph.com

### LINKED ISSUE #1720: Docs "note" style should have stronger highlighting
Currently, `aside.node` elements in the docs (which correspond to `> Markdown blockquotes`) are not highlighted in any way. They are indistinguishable from paragraph text. However, they often have important information that a user should notice on the page. For instance:

image

@francisschmaltz Can we highlight these things by placing them in a yellow rounded-corner box or whatever you think is best as design chief?

### LINKED ISSUE #1885: Add docs search for the help section and remove code search
I think it would be great if we could add docs search to the help section while also removing the code search component from the help section.

It was confusing to me when using the help site to have a search bar at the top of the page that wasn't for documentation. First couple of times I needed to search, I typed into the Code search element without thinking, as I presumed the search field was for the help content. I type quickly so I didn't see the `Search code...` place holder text.

In any case, the lack of docs search in the help section is frustrating, as you have to open a new window/tab, type the docs URL, then search. 

This could also cause issues if the user doesn't ensure they're looking at the right version of documentation.

### LINKED ISSUE #1912: Help docs home page displays docker run command on a single line
screen shot 2019-01-15 at 9 40 50 am

### LINKED ISSUE #2337: Remove built-in help docs, link to the docs.sourcegraph.com/@version instead
There are several issues (#1885, #1720, #1912) caused by styling or functionality differences between the in-product help and docs.sourcegraph.com

I propose removing the in-product help and instead, link to the version of the docs the instance is running.

This has the following benefits:

 - Still provides version specific docs.
 - No styling and functionality consistency issues so we can close #1885, #1720 and #1912
 - No light and dark theme styles for help docs.
 - Removes [Sourcegraph's dependency on docsite](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+docsite+).

In summary removing the in-product help still provides users with version specific docs while saving effort now, and in the future.

### LINKED ISSUE #2369: recent pkg/markdown changes are poor, dangerous, and have caused regressions
**TL;DR**: We're using docsite/markdown everywhere since Oct. and nobody realizes this, because it being in docsite kind of implies that only docs.sourcegraph.com uses it. You wouldn't expect it to be used to render every Markdown file in Sourcegraph. This package: is not subject to the same review/testing as our main app, is a security concern, and has already caused multiple regressions in our main app.

Proposal: Revert back to a state where we are not importing docsite/markdown. We will soon not need to use this package anyway, because [we intend to remove the built in docs](https://github.com/sourcegraph/sourcegraph/issues/2337).

---

Back in Oct. @sqs [made a change to move `cmd/frontend/internal/pkg/markdown` to `pkg/markdown`](https://github.com/sourcegraph/sourcegraph/pull/421/commits/0710e87f372514298374111914c1d31d801e1c61). In this change, a new dependency `github.com/sourcegraph/docsite/markdown` was added which is now responsible for markdown rendering. Unfortunately, I missed this change and failed to review it. The commit message:

> use docsite markdown package instead of github_flavored_markdown
>
> The github.com/sourcegraph/docsite/markdown package performs roughly the same formatting but uses a newer underlying blackmonday library. This commit removes external dependencies but otherwise is a noop. Removing the dependency on github_flavored_markdown is necessary for a future commit where we need the new version of blackmonday (and it can't coexist with an older version at the same import path).

This change worries me because:

1. Our main application now imports a dependency from github.com/sourcegraph/docsite and uses it heavily.
2. **It is confusing that a change to docsite/markdown also applies to the entire Sourcegraph main app**.
3. **Nobody is testing those changes against Sourcegraph** (except maybe @sqs).
4. **It has already caused multiple regressions**:
    - [Broken highlighting on commit and diff search entirely](https://github.com/sourcegraph/sourcegraph/issues/2325)
    - [Panics in the frontend when trying to send email notifications for code discussions](https://github.com/sourcegraph/sourcegraph/issues/1361#issuecomment-464872591)
    - (Yes, both of these regressions should have been caught otherwise, but that is not the point).
5. **I am worried about the security implications**. For example, @sqs added a HTML markdown function to render JSON schema files that get loaded from disk. In the context of docs.sourcegraph.com that sounds totally fine and safe because we control the markdown -- but when we are rendering user-provided markdown on sourcegraph.com that starts to sound a bit more scary. It's probably not a problem today, but what about when someone modifies this package and doesn't realize their change could regress our security?
6. **I do not feel like some choices made in the docsite/markdown package are the best for Sourcegraph the main app** (such as using bfchroma for syntax highlighting code blocks, which will produce inconsistent results with our main syntax highlighter).

### PR DESCRIPTION
**Pull request by sqs**
- Revert e5e1c2393e4c9665f14da3eea3ad667a30ebdb05
- Remove dependency on github.com/sourcegraph/docsite/markdown, revert to using previously used Markdown packages
  - Fix #2369
  - Help with #1361
- Remove in-product rendered /help pages, redirect to equivalent https://docs.sourcegraph.com page for the current product version instead
  - Close #2337
  - Fix #1720
  - Fix #1912 
  - Close #1885
  - Remove dependency on github.com/sourcegraph/docsite

### No docs for untagged releases

To redirect `/help/PATH` in-product to https://docs.sourcegraph.com/@v1.2.3/PATH, a Sourcegraph instance needs to know the `v1.2.3` (Git revspec for its current version). This is easy for true releases and release candidates, since for them `"v" + version.Version()` is a valid Git revspec. We special-case dev builds (`version.Version() == "dev"`) and Sourcegraph.com. 

However, if you are running Sourcegraph with a version string that is NOT a valid Git tag (revspec) on the remote, there is no way for the instance to perform the proper redirect. It's also not really feasible for the instance to detect this case and report it (the user would just be redirected to a 404ing https://docs.sourcegraph.com/@some-invalid-version/PATH URL).

I think this is acceptable because I am unaware of why such an untagged build would exist where the doc links would need to work. If we need to give a customer a hotpatch, we should just release a patch version normally. (In extreme, unforeseeable circumstances where we would release an untagged build, having doc links not working is probably low down on the list of concerns because something else must be extremely urgent.)

## TODO

This is ready to review.

- [x] Ensure behavior is correct on Sourcegraph.com (should link to version-less docs.sourcegraph.com URL).
- [x] Investigate whether the `version.Version()` string always corresponds to a valid Git tag in all the cases that matter (releases, release candidates, hotfix versions for customers, etc.?). (See "No docs for untagged releases above" for the answer to this.)
- [x] Make our React app handle `/help/PATH` redirects (currently these are only handled by Go, so react-router `<Link>`s to `/help/PATH` don't redirect). (This has a slight bug with the back button in dev mode only that will be addressed by adding docsite on http://localhost:5080 to Procfile, mentioned below as being planned for a future PR.)
- [x] Test that search results are syntax-highlighted correctly.
- [x] Test that Markdown is rendered correctly for `.md` files, code discussions, and saved search emails (or confirm that we have automated tests for these).

### Followup work in a future (this week) PR

- [ ] Move https://github.com/sourcegraph/docs.sourcegraph.com into this repository.
- [ ] Add `docsite` running on http://localhost:5080 to `Procfile` so devs can preview local doc changes again.
- [ ] Add lint step to ensure that `/help/PATH` links (in `<a>` and react-router `<Link>` and in text/bare URLs) refer to doc pages that actually exist in the current commit.
- [ ] Update all absolute links to https://docs.sourcegraph.com/PATH to `/help/PATH` to ensure the link goes to the docs for the current product version.

### CODE REVIEW

**Comment by felixfbecker** [comment]
If it’s not ready to review why didn’t you open a draft PR? :)

**Comment by sqs** [comment]
@felixfbecker 	Good question. :smile: I originally thought it was ready to review (with caveats), then noticed a few more things that I wanted to address before anyone else bothered looking at it. Now it's ready for review (ie review would be useful, it's not ready to merge). There is unf no way to switch back and forth between it being a draft and non-draft PR.

**Comment by felixfbecker** [comment]
Does this mean we can revert https://github.com/sourcegraph/docs.sourcegraph.com/commit/77e15cf28fd9c260f1816f1cf1f8f84422683691 and use Algolia again?

**Comment by sqs** [comment]
@felixfbecker:

> Does this mean we can revert sourcegraph/docs.sourcegraph.com@77e15cf and use Algolia again?

No. That was necessitated by having multiple versions on the doc site, which I was unable to configure to work well with Algolia (to avoid having duplicate results for each distinct version).

**Comment by ryan-blunden** [comment]
@sqs Is the redirect code for the case when someone has bookmarked a help page URL from a previous Sourcegraph version?

If we do need to handle that case, could we:

- Convert the help redirect logic into a configurable redirect package that docsite uses for re-routing to pages that have been renamed or removed?
 - Send a ping on every /`help` redirect with the path to know when redirects can be removed.

**Comment by sqs** [comment]
@ryan-blunden:

> @sqs Is the redirect code for the case when someone has bookmarked a help page URL from a previous Sourcegraph version?

Yes, AND so that existing links in our product (eg from site admin pages) to `/help/whatever` still work. The followup work mentioned in the PR description includes making it so existing links link directly to docs.sourcegraph.com without needing that redirect (but the redirect makes merging this sooner possible).

> Send a ping on every /help redirect with the path to know when redirects can be removed.

It will probably always be useful to redirect from `/help/foo` to https://docs.sourcegraph.com/foo`, so I don't see us needing to remove the redirect. Note that the redirects don't require us to list each page individually; it just redirects everything, so there isn't any manual upkeep.

File: cmd/frontend/internal/app/ui/help.go [hunk 1]
```diff
@@ -1,23 +1,61 @@
...
-	if docsite.IsContentAsset(r.URL.Path) {
-		// Serve content assets (such as images referenced in .md files).
-		docsiteHandler.ServeHTTP(w, r)
-	} else {
-		// The UI renders content pages (.md files).
-		docsitePassThru(w, r)
+	page := strings.TrimPrefix(r.URL.Path, "/help")
+	versionStr := version.Version()
+
+	// Use the version string for release builds. Don't use any version string otherwise:
```
Comment (beyang) [inline cmd/frontend/internal/app/ui/help.go]:
```suggestion
	// For release builds, use the version string. Otherwise, don't use any version string because:
```

**Comment by sqs** [comment]
@beyang:

> Backend changes LGTM. When this is merged, can you drop a note about it in #dev-announce

Yes, will do. I will wait to merge #2482 before posting that (assuming I can merge it in the next few hours), because that will change (simplify) it further.
