### PR TITLE
compute: fix match-only command to add all matches on a single line

### LINKED ISSUE #29459: compute endpoint fails to match all capture group results
**Repro**:

1. On sourcegraph.com, open up the API console.
2. Run the following query:
```
query {
  compute(query:"patterntype:regexp background-color:#([0-9]) count:all repo:^github\\.com/sourcegraph/sourcegraph$@87f96d3608db4f6c535897b90f34256cc5b093c2") {
    ... on ComputeMatchContext{
        matches {
            value
	}
    }
  }
}
```
Note that this matches groups with values `4`, `3`, and `1`. 
3. Now modify that query slightly by changing the capture group from `[0-9]` to `[0-9a-z]` and re-run the query.

**Expected**:
The initial matches should all still be there, with any additions (in this case `f`) from the newly added `a-z`

**Actual**:
`3` is missing from the results

### PR DESCRIPTION
**Pull request by rvantonder**
Fixes #29459. When multiple regex matches happened on a single line, only the first would be populated for compute results. (Previously all _subgroups_ were populated, but not all of the overall matches)

### CODE REVIEW

File: internal/compute/match_only_command.go [hunk 1]
```diff
@@ -17,50 +17,47 @@ func (c *MatchOnly) String() string {
 	return fmt.Sprintf("Match only: %s", c.MatchPattern.String())
 }
 
-func fromRegexpMatches(matches [][]int, namedGroups []string, lineValue string, lineNumber int) Match {
+func fromRegexpMatches(submatches []int, namedGroups []string, lineValue string, lineNumber int) Match {
```
Comment (rvantonder) [inline internal/compute/match_only_command.go:20]: This function stays the same, the diff is just noisy because of the indentation change, because the outer loop is extracted out.

File: internal/compute/match_only_command.go [hunk 2]
```diff
@@ -17,50 +17,47 @@ func (c *MatchOnly) String() string {
...
 	return Match{Value: firstValue, Range: firstRange, Environment: env}
 }
 
 func matchOnly(fm *result.FileMatch, r *regexp.Regexp) *MatchContext {
 	matches := make([]Match, 0, len(fm.LineMatches))
 	for _, l := range fm.LineMatches {
-		regexpMatches := r.FindAllStringSubmatchIndex(l.Preview, -1)
-		if len(regexpMatches) > 0 {
-			matches = append(matches, fromRegexpMatches(regexpMatches, r.SubexpNames(), l.Preview, int(l.LineNumber)))
+		for _, submatches := range r.FindAllStringSubmatchIndex(l.Preview, -1) {
```
Comment (rvantonder) [inline internal/compute/match_only_command.go:59]: Key change: loop over every submatch for a single line.

**Review by coury-clark — APPROVED** [review]
