### PR TITLE
batches: Debug message when namespace deleted

### LINKED ISSUE #39723: batches: error when syncing a changeset belonging to a batch change whose owner is deleted
**Steps to repro:**
- Create a new user/org
- Create a new batch change under this user/org's namespace with at least one changeset
- Publish at least one changeset for this batch change
- Delete the user/org
- Try to sync the changeset/wait for it to sync

**Expected behavior:**
- A `debug` level message is logged that the changeset will skip syncing due to the batch change belonging to a now-deleted user

**Actual behavior:**
- An `error` level message is logged, like the following:
```
"message": "t=2022-07-29T21:41:09+0000 lvl=eror msg=\"Syncing changeset\" err=\"failed to load owning batch change: batch change not found: 105\"",
```

---

Our `bstore.GetBatchChange` method excludes results where the [batch change namespace's user or org has been deleted](https://sourcegraph.com/-/editor?remote_url=https%3A%2F%2Fgithub.com%2Fsourcegraph%2Fsourcegraph.git&branch=main&file=enterprise%2Finternal%2Fbatches%2Fstore%2Fbatch_changes.go&editor=VSCode&version=2.2.7&start_row=390&start_col=1&end_row=393&end_col=2&utm_campaign=vscode-extension&utm_medium=direct_traffic&utm_source=vscode-extension&utm_content=vsce-commands). This causes us to emit an error message in the syncer when we try to [load the batch change for a changeset and cannot find it](https://sourcegraph.com/-/editor?remote_url=https%3A%2F%2Fgithub.com%2Fsourcegraph%2Fsourcegraph.git&branch=main&file=enterprise%2Finternal%2Fbatches%2Fsources%2Fsources.go&editor=VSCode&version=2.2.7&start_row=237&start_col=3&end_row=239&end_col=2&utm_campaign=vscode-extension&utm_medium=direct_traffic&utm_source=vscode-extension&utm_content=vsce-commands).

The batch change not existing is indeed a problem we want to look out for and report as an error if encountered. However, the batch change just belonging to a deleted user/org is _not_ a problem, and should _not_ be reported as an error. In order to differentiate these cases in the changeset syncer, we should probably either:

1. Not exclude batch changes with a deleted user/org namespace from `bstore.GetBatchChange`, but check for them from `loadBatchChange` instead and log the debug message if we detect the namespace is deleted.
2. Not exclude batch changes with a deleted user/org namespace from the SQL query used for `bstore.GetBatchChange`, but check and return something like `nil, ErrDeletedNamespace` from the method instead, and log the debug message if we get that error from the store.

We'll need to make sure other consumers of the `bstore.GetBatchChange` method are able to handle whatever change we make.

### PR DESCRIPTION
**Pull request by Piszmog**
Closes #39723.

When calling `GetBatchChange`, removed the requirement to that the org and user `deleted_at` be `null`. Instead, during the `scan` call, setting the `deleted_at` values into 2 variables. If these variables are not "zero," then a new error (`ErrDeletedNamespace`) is returned to signify that the namespace has been deleted.

With this error, we can now check if the error is `ErrDeletedNamespace` and log a debug message saying that the changeset is being skipped.

## Test plan

Added Go Unit Tests

### CODE REVIEW

**Review by LawnGnome — APPROVED** [review]
LGTM!

File: enterprise/internal/batches/syncer/syncer_test.go [hunk 1]
```diff
@@ -159,6 +160,63 @@ func TestSyncerRun(t *testing.T) {
 			t.Fatal("Sync not called")
 		}
 	})
+
+	t.Run("Sync due but reenqueued when no namespace deleted", func(t *testing.T) {
```
Comment (courier-new) [inline enterprise/internal/batches/syncer/syncer_test.go:164]:
```suggestion
	t.Run("Sync due but reenqueued when namespace deleted", func(t *testing.T) {
```

**Review by courier-new — APPROVED** [review]
Beautiful, thanks for all the extra test coverage. ⭐
