### PR TITLE
fix(a11y): Spread `rest` props to DropdownToggle button component

### LINKED ISSUE #35852: [Accessibility]: Non-code file view: File actions menu not read out to screen readers
### Audit type

Screen reader navigation

### User journey audit issue

https://github.com/sourcegraph/sourcegraph/issues/34432

### Problem description

image

Screen readers cannot understand what this button does

### Expected behavior

Should have a label that describes usage

### Additional details

_No response_

### Assigning labels

- [X] Please give this issue an estimate by applying a label like `estimate/Xd`, where X is the estimated number of days it will take to complete.
- [X] If this issue is specific to a specific Sourcegraph product, please assign the appropriate team label to this issue.
- [ ] If this issue will require input from designers in order to complete, please assign the label `needs-design`.
- [ ] If you are confident that this issue should be fixed by GitStart, please assign the label `gitstart`.

### Owner

This issue will be fixed by my team, I have assigned a relevant member to it, or I will do so in the near future.

### PR DESCRIPTION
**Pull request by plibither8**
This PR spreads all supplied props sent to `RepoHeaderActionDropdownToggle` component, to the `Button` component, thereby sending attributes like `aria-label` too.

Closes #35852

## Test plan

- Tested using a screen reader
- Checked via Dev Tools that the `aria-label="Repository Actions"` attribute is now present on the toggle button.

## App preview:

- [Web](https://sg-web-mihir-35852-file-actions-menu.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-eajixownyc.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

File: client/web/src/repo/components/RepoHeaderActions/RepoHeaderActions.tsx [hunk 1]
```diff
@@ -23,8 +23,9 @@ export const RepoHeaderActionButtonLink: React.FunctionComponent<
 
 export const RepoHeaderActionDropdownToggle: React.FunctionComponent<React.PropsWithChildren<unknown>> = ({
     children,
+    ...rest
 }) => (
-    <Button as={MenuButton} className={classNames('btn-icon', styles.action)}>
+    <Button as={MenuButton} className={classNames('btn-icon', styles.action)} {...rest}>
```
Comment (jasongornall) [inline client/web/src/repo/components/RepoHeaderActions/RepoHeaderActions.tsx:28]: should we pass the aria stuff explicitly here? An interesting discussion of this backfiring
see this [thread](https://sourcegraph.slack.com/archives/C01C3NCGD40/p1654769271790629)

Comment (plibither8) [reply client/web/src/repo/components/RepoHeaderActions/RepoHeaderActions.tsx:28]: @jasongornall that's a fair point! I considered spreading the props here would be OK in this scope since the `RepoHeaderActionDropdownToggle` component is only used once in the entire codebase, in which just `aria-label` is passed as an attribute/prop; and the other components defined near it are using this pattern too.

Comment (plibither8) [reply client/web/src/repo/components/RepoHeaderActions/RepoHeaderActions.tsx:28]: Gotcha, will update this.

Comment (fkling) [reply client/web/src/repo/components/RepoHeaderActions/RepoHeaderActions.tsx:28]: I think what makes spreading the props here "risky", even if it's only used in a single place, is the fact that the props are defined as `unknown` above:

    React.FunctionComponent<React.PropsWithChildren<unknown>>

Ultimately, what makes spreading dangerous is if unknown props are spread at the callsite as well.

Can't we specify the accepted `aria-` attributes, e.g.

    React.FunctionComponent<React.PropsWithChildren<Pick<AriaAttributes, 'aria-label'>>>

and explicitly pass it? That would at least provide some information about which props are really supported.

Comment (plibither8) [reply client/web/src/repo/components/RepoHeaderActions/RepoHeaderActions.tsx]: Thanks for the feedback @fkling, continuing with it! 👍

**Review by jasongornall — APPROVED** [review]

**Comment by plibither8** [comment]
All checks are passing after rebasing with `main`, so going ahead and merging this! 🙂
