### PR TITLE
graphqlbackend: add new query repositoryRedirect

### LINKED ISSUE #5125: Querying repository by name with github.com prefix always returns empty string for name
Run this GraphQL query on k8s.sgdev.org:

```graphql
query {
  repository(name:"github.com/asdasd") {
    name
  }
}
```

[API console link](https://k8s.sgdev.org/api/console#%7B%22query%22%3A%22%23%20Type%20queries%20here%2C%20with%20completion%2C%20validation%2C%20and%20hovers.%5Cn%23%5Cn%23%20Here's%20an%20example%20query%20to%20get%20you%20started%3A%5Cn%5Cnquery%20%7B%5Cn%20%20repository(name%3A%5C%22github.com%2Fasdasd%5C%22)%20%7B%5Cn%20%20%20%20name%5Cn%20%20%7D%5Cn%7D%5Cn%22%7D)

You can use any repo name, as long as it starts with `github.com/` (even just that string).

it returns this result:

```json
{
  "data": {
    "repository": {
      "name": ""
    }
  }
}
```

An empty string should never be returned. A repo with an empty name obviously doesn't exist.

Interestingly, when you add other fields, you notice you can query for its `id`, but if you add e.g. `createdAt` or `description` those fields (not the `repository` field itself) fail with a "repo not found" error:

```graphql
query {
  repository(name:"github.com/asdasd") {
    name
    id
    createdAt
    description
  }
}
```

Result:

```json
{
  "data": {
    "repository": {
      "name": "",
      "id": "UmVwb3NpdG9yeTow",
      "createdAt": "2019-08-07T15:04:24Z",
      "description": null
    }
  },
  "errors": [
    {
      "message": "repo not found",
      "path": [
        "repository",
        "description"
      ]
    }
  ]
}
```

Note that the browser extension / native integrations do this query and interprets this result as the repo existing, which breaks code intelligence.

I cannot reproduce this with sourcegraph.com, so I suspect it only happens with certain external service configurations.

### PR DESCRIPTION
**Pull request by unknwon**
This PR adds another GraphQL query `repositoryRedirect` and changes the web app to use this new query instead of the old `repository`.

- The `repository` query now consistently returns `null` when the repository not found on the local server.
- The `repositoryRedirect` query returns a redirect URL (if enabled in the site configuration) when the repository not found on the local server. Name of this new query up for debate, I chose current one because it's the most intuitive. 

Fixes #5125.

### Review Tips

The diff itself looks weird, might be easier to review if expand up and down to see the full method body.

### CODE REVIEW

File: cmd/frontend/graphqlbackend/repository.go [hunk 1]
```diff
@@ -96,10 +95,6 @@ func (r *RepositoryResolver) Description(ctx context.Context) (string, error) {
 	return r.repo.Description, nil
 }
 
-func (r *RepositoryResolver) RedirectURL() *string {
```
Comment (unknwon) [inline cmd/frontend/graphqlbackend/repository.go]: I intentionally removed this so compilation and tests of web app would fail, which helps locate bugs. LMK if I should add this back for backward compatibility.

File: web/src/repo/backend.ts [hunk 2]
```diff
@@ -45,8 +49,8 @@ export const fetchRepository = memoizeObservable(
                 if (!data) {
                     throw createAggregateError(errors)
                 }
-                if (data.repository && data.repository.redirectURL) {
-                    throw new RepoSeeOtherError(data.repository.redirectURL)
+                if (data.repositoryRedirect?.__typename === 'Redirect') {
```
Comment (unknwon) [inline web/src/repo/backend.ts]: @sourcegraph/web  I tried my best to make this code compile 😅 Please advice what's the idiomatic changes to make. As always, feel free to directly push changes to this PR!

File: cmd/frontend/graphqlbackend/schema.graphql [hunk 3]
```diff
@@ -1840,8 +1850,6 @@ type Repository implements Node & GenericSearchResultInterface {
         # Returns the first n contributors from the list.
         first: Int
     ): RepositoryContributorConnection!
-    # Link to another Sourcegraph instance location where this repository is located.
-    redirectURL: String
```
Comment (mrnugget) [inline cmd/frontend/graphqlbackend/schema.graphql]: Can we simply remove it? I'd rather use `@deprecated` here (take a look at the schema for other deprecations) with a notice that it'll be removed in 3.15.

File: cmd/frontend/graphqlbackend/schema.graphql [hunk 4]
```diff
@@ -1140,6 +1140,16 @@ type Query {
         # An alias for name. DEPRECATED: use name instead.
         uri: String
     ): Repository
+    # Looks up a repository by either name or cloneURL. If the repository does not exist on the server,
+    # it returns a Redirect to an external Sourcegraph URL that may have this repository instead.
+    repositoryRedirect(
+        # Query the repository by name, for example "github.com/gorilla/mux".
+        name: String
+        # Query the repository by a Git clone URL (format documented here: https://git-scm.com/docs/git-clone#_git_urls_a_id_urls_a)
+        # by checking if there exists a code host configuration that matches the clone URL.
```
Comment (mrnugget) [inline cmd/frontend/graphqlbackend/schema.graphql]:
```suggestion
        # by checking for a code host configuration that matches the clone URL.
```

File: cmd/frontend/graphqlbackend/repository.go (hunk 1 above)
Comment (mrnugget) [reply cmd/frontend/graphqlbackend/repository.go]: See the other comment: I don't think we can break the API yet. We need to first deprecate this field.

File: cmd/frontend/graphqlbackend/graphqlbackend.go [hunk 5]
```diff
@@ -340,11 +339,47 @@ func (r *schemaResolver) Repository(ctx context.Context, args *struct {
...
+
+type RedirectResolver struct {
+	url string
+}
+
+func (r *RedirectResolver) URL() string {
+	return r.url
+}
+
+type repositoryRedirect struct {
```
Comment (mrnugget) [inline cmd/frontend/graphqlbackend/graphqlbackend.go]: Curious: why export `RedirectResolver` but not `repositoryRedirect`?

Comment (unknwon) [reply cmd/frontend/graphqlbackend/graphqlbackend.go]: I basically followed the convention of `gitRevSpec`:

https://github.com/sourcegraph/sourcegraph/blob/17ad527a269137f1d9f76b2211bedb004d478b1c/cmd/frontend/graphqlbackend/git_revision.go#L34-L42

I think it was because it's an implementation detail that won't be any part of the actual response body?

File: cmd/frontend/graphqlbackend/schema.graphql [hunk 6]
```diff
@@ -1893,6 +1903,15 @@ type Repository implements Node & GenericSearchResultInterface {
     ): UserConnection!
 }
 
+# A redirect URL.
```
Comment (felixfbecker) [inline cmd/frontend/graphqlbackend/schema.graphql]:
```suggestion
# A reference to another Sourcegraph instance.
```

File: cmd/frontend/graphqlbackend/schema.graphql [hunk 7]
```diff
@@ -1893,6 +1903,15 @@ type Repository implements Node & GenericSearchResultInterface {
...
+type Redirect {
+    # The URL of the redirect.
```
Comment (felixfbecker) [inline cmd/frontend/graphqlbackend/schema.graphql]:
```suggestion
    # The URL of the other Sourcegraph instance.
```

File: cmd/frontend/graphqlbackend/schema.graphql [hunk 8]
```diff
@@ -1893,6 +1903,15 @@ type Repository implements Node & GenericSearchResultInterface {
...
+    url: String!
+}
+
+# A repository or a link to another Sourcegraph instance location where this repository is located.
```
Comment (felixfbecker) [inline cmd/frontend/graphqlbackend/schema.graphql]:
```suggestion
# A repository or a link to another Sourcegraph instance location where this repository may be located.
```

File: web/src/repo/backend.ts [hunk 9]
```diff
@@ -21,20 +21,24 @@ export const fetchRepository = memoizeObservable(
...
         queryGraphQL(
             gql`
-                query Repository($repoName: String!) {
-                    repository(name: $repoName) {
-                        id
-                        name
-                        url
-                        externalURLs {
+                query RepositoryRedirect($repoName: String!) {
+                    repositoryRedirect(name: $repoName) {
```
Comment (felixfbecker) [inline web/src/repo/backend.ts]: You need to include this in the query if you want to use it below
```suggestion
                    repositoryRedirect(name: $repoName) {
                        __typename
```

File: cmd/frontend/graphqlbackend/schema.graphql [hunk 10]
```diff
@@ -1134,12 +1134,22 @@ type Query {
...
         # Query the repository by a Git clone URL (format documented here: https://git-scm.com/docs/git-clone#_git_urls_a_id_urls_a)
-        # by checking if there exists a code host configuration that matches the clone URL.
+        # by checking for a code host configuration that matches the clone URL.
         # Will not actually check the code host to see if the repository actually exists.
         cloneURL: String
         # An alias for name. DEPRECATED: use name instead.
         uri: String
     ): Repository
+    # Looks up a repository by either name or cloneURL. If the repository does not exist on the server,
+    # it returns a Redirect to an external Sourcegraph URL that may have this repository instead.
```
Comment (felixfbecker) [inline cmd/frontend/graphqlbackend/schema.graphql]: This docstring says that if the repo was not found a `Redirect` is always returned, but I think that's not true, if redirects are disabled or the server does not suspect the repo to exist somewhere else it may also return `null`.

File: web/src/repo/backend.ts [hunk 11]
```diff
@@ -45,13 +49,14 @@ export const fetchRepository = memoizeObservable(
...
-                    throw new RepoSeeOtherError(data.repository.redirectURL)
-                }
-                if (!data.repository) {
+                if (!data.repositoryRedirect) {
                     throw new RepoNotFoundError(args.repoName)
                 }
-                return data.repository
+                if (data.repositoryRedirect.__typename === 'Redirect') {
+                    throw new RepoSeeOtherError(data.repositoryRedirect.url)
+                } else {
```
Comment (felixfbecker) [inline web/src/repo/backend.ts]: This is a superfluous `else` which will make `eslint` complain :)

File: web/src/repo/backend.ts [hunk 12]
```diff
@@ -101,28 +110,28 @@ export const resolveRev = memoizeObservable(
...
-                if (data.repository && data.repository.redirectURL) {
-                    throw new RepoSeeOtherError(data.repository.redirectURL)
-                }
-                if (!data.repository) {
+                if (!data.repositoryRedirect) {
                     throw new RepoNotFoundError(ctx.repoName)
                 }
-                if (data.repository.mirrorInfo.cloneInProgress) {
-                    throw new CloneInProgressError(ctx.repoName, data.repository.mirrorInfo.cloneProgress || undefined)
+                if (data.repositoryRedirect?.__typename === 'Redirect') {
```
Comment (felixfbecker) [inline web/src/repo/backend.ts]: You already checked for the presence above :)
```suggestion
                if (data.repositoryRedirect.__typename === 'Redirect') {
```

File: web/src/repo/backend.ts [hunk 13]
```diff
@@ -76,22 +81,26 @@ export const resolveRev = memoizeObservable(
...
-                            cloneInProgress
-                            cloneProgress
-                            cloned
-                        }
-                        commit(rev: $rev) {
-                            oid
-                            tree(path: "") {
-                                url
+                    repositoryRedirect(name: $repoName) {
+                        ... on Repository {
```
Comment (felixfbecker) [inline web/src/repo/backend.ts]:
```suggestion
                        __typename
                        ... on Repository {
```

**Comment by felixfbecker** [comment]
@unknwon I think you need to run `yarn run prettier` and in the web directory `yarn run eslint --fix`

File: cmd/frontend/graphqlbackend/schema.graphql (hunk 10 above)
Comment (lguychard) [reply cmd/frontend/graphqlbackend/schema.graphql]: Actually, I found out while testing this that if a repository is not found, a `Redirect` with a `null` url is returned:

image

@unknwon this isn't ideal, we should return `null` here as described by @felixfbecker above.

Comment (unknwon) [reply cmd/frontend/graphqlbackend/schema.graphql]: Gotcha, working on it.

Comment (felixfbecker) [reply cmd/frontend/graphqlbackend/schema.graphql]: @lguychard I'm confused, your screenshot doesn't show a redirect with a `null` URL, it shows the intended behavior - `repositoryRedirect` being `null`

Comment (unknwon) [reply cmd/frontend/graphqlbackend/schema.graphql]: I was just wondering after took a closer look, isn't `"data": null` an unexpected error:

```ts
if (!data) {
	throw createAggregateError(errors)
}
```

Comment (lguychard) [reply cmd/frontend/graphqlbackend/schema.graphql]: Uh, yeah, you're right. I thought I was seeing some strange things in testing but all looks good.

**Comment by unknwon** [comment]
Thanks everyone 😊 Merging!
