### PR TITLE
search: restore structural search back-compat

### LINKED ISSUE #18266: Structural search backwards compatibility broken
A search like 

[`repo:^github\.com/sourcegraph/sourcegraph$ lang:go Search(...) rule:'where "backcompat" == "backcompat"'`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+lang:go+Search%28...%29+rule:%27where+%22backcompat%22+%3D%3D+%22backcompat%22%27&patternType=structural)

turns up zero results. I bisected the cause and it's https://github.com/sourcegraph/sourcegraph/pull/17952. I see that searcher is only getting `.go` when lang is specified, instead of a list of file paths to search. Without `lang:go`, it gets an empty list (so searches every file). Haven't looked further yet, it's Friday and I'm signing off for the weekend.

### PR DESCRIPTION
**Pull request by rvantonder**
Fixes #18266.

This PR adds back the code that disappeared in https://github.com/sourcegraph/sourcegraph/pull/17952, which sets `includePatterns` for structural search (currently `searcherReposFilteredFiles` is just dead). We need it for backwards compatibility. We can delete this and the backcompat function soon: After branch cut/release or once I'm done benchmarking old versus new for complex queries / many repos on Sourcegraph.com.

### CODE REVIEW

File: cmd/frontend/graphqlbackend/textsearch.go [hunk 1]
```diff
@@ -534,6 +534,17 @@ func callSearcherOverRepos(
 				// Make a new repoRev for just the operation of searching this revspec.
 				repoRev := &search.RepositoryRevisions{Repo: repoAllRevs.Repo, Revs: []search.RevisionSpecifier{{RevSpec: rev}}}
 
+				args := *args
+				if args.PatternInfo.IsStructuralPat && searcherReposFilteredFiles != nil {
```
Comment (rvantonder) [inline cmd/frontend/graphqlbackend/textsearch.go:538]: Note we do not need to check for the `"backcompat" == "backcompat"` rule, because `searcherReposFilteredFiles` is nil except for the backcompat/old path.

**Review by camdencheek — APPROVED** [review]
