### PR TITLE
[fix] Make "internal" gitlab repos behave like private repositories

### LINKED ISSUE #41909: GitLab repositories with internal visibility is treated as public
Context from Slack thread:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/gitlab.go?L210

/cc @sourcegraph/iam

### PR DESCRIPTION
**Pull request by kopancek**
fixes #41909

## Test plan

Added unit tests.

Tested manually against gitlab.sgdev.org.

1. Created an "internal" repository
2. Added 2 users to my local sg instance
3. Connected the gitlab.sgdev.org as an OAuth source and added external service with repo permissions syncing based on OAuth
4. Verified that
  a. Site admin can see the repository (site admins are godlike and can see everything)
  b. User who did not add Gitlab in Settings -> Account Security cannot search the repository
  c. User who added Gitlab in Settings -> Account Security can search the repository

Tested the changes for sudo gitlab auth provider by adding a private repository as well and running the following queries from terminal (see the [xh tool docs here](https://github.com/ducaale/xh/blob/master/README.md)):
```
xh "https://gitlab.sgdev.org/api/v4/projects?visibility=private&min_access_level=20&per_page=100&membership=true" "PRIVATE-TOKEN: <redacted>"
xh "https://gitlab.sgdev.org/api/v4/projects?visibility=internal&min_access_level=20&per_page=100&membership=true" "PRIVATE-TOKEN: <redacted>"
``` 
And validated that I can see the repo with proper visibility based on the query param, but not without it.

### CODE REVIEW

**Comment by pjlast** [comment]
This my require a change to how we fetch user perms: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/internal/authz/gitlab/sudo.go?L227

The query only fetches Private repositories, but if internal repos are treated as Private now, they would have to be fetched as well

**Review by miveronese — APPROVED** [review]
Thanks for also sharing how you run/test if the query params are working. 🙏

File: enterprise/internal/authz/gitlab/sudo.go [hunk 1]
```diff
@@ -226,7 +226,8 @@ func (p *SudoProvider) FetchUserPermsByToken(ctx context.Context, token string,
 // whether to discard.
 func listProjects(ctx context.Context, client *gitlab.Client) (*authz.ExternalUserPermissions, error) {
 	q := make(url.Values)
-	q.Add("visibility", "private")  // This method is meant to return only private projects
+	q.Add("visibility", "private") // This method is meant to return only private or internal projects
+	q.Add("visibility", "internal")
```
Comment (pjlast) [inline enterprise/internal/authz/gitlab/sudo.go:230]: This doesn't quite work, the `visibility=internal` check overrides the `visibility=private` check. You can confirm by creating both a Private and an Internal repo. Only the Internal repo will show up with the parameters set like this. Not sure if there is an easy way that fetches both Internal and Private repos together

**Review by pjlast — CHANGES_REQUESTED** [review]

File: enterprise/internal/authz/gitlab/sudo.go (hunk 1 above)
Comment (kopancek) [reply enterprise/internal/authz/gitlab/sudo.go]: fixed in the latest commit 🤞

**Review by pjlast — APPROVED** [review]
