### PR TITLE
suggest a longer timeout if deadline is exceeded

### LINKED ISSUE #4382: "Context deadline exceeded" on Sourcegraph.com search
- **Sourcegraph version:** Sourcegraph.com

#### Steps to reproduce:

1. https://sourcegraph.com/search?q=r%3Agithub.com%2Fhashicorp+todo

#### Expected behavior:

Ideally, actual results :). If that's not possible, then perhaps some recommendation for how to adjust — e.g. add a `timeout:`? Filter my `repo:` filter more? Etc. It'd be great to see something like "This matched 1,327 repos, that's too many for us, you need to reduce to X" so I have a sense for how far off I am from it working.

#### Actual behavior:

"Context deadline exceeded" error

### PR DESCRIPTION
**Pull request by ijt**
Closes #4382. It's not a perfect solution, but it is likely to help in many cases.

Before:
Screen Shot 2019-06-13 at 12 04 38

After:
Screen Shot 2019-06-13 at 17 06 55

Test plan: unit test, local manual testing

### CODE REVIEW

**Comment by slimsag** [comment]
In practice, when a timeout parameter is not specified, what is the smallest timeout parameter we suggest?

If I've hit a timeout as a user and am willing to wait longer, our minimum timeout we suggest should be at least like 3s.

**Comment by ijt** [comment]
I changed it to always suggest at least 2s.

File: cmd/frontend/graphqlbackend/search_results.go [hunk 1]
```diff
@@ -464,13 +465,40 @@ func (r *searchResolver) Results(ctx context.Context) (*searchResultsResolver, e
...
-		log15.Debug("graphql search failed", "query", r.rawQuery(), "duration", time.Since(start), "error", err)
+		if err == context.DeadlineExceeded {
+			dt := time.Now().Sub(start)
+			N := 2
+			dt2 := longerTime(N, dt)
+			// Tidy up the original duration so it displays like 3ms rather than
+			// 3.12345ms. The user doesn't need to know the exact duration,
+			// just a rough idea and a good suggestion for something else
+			// to try for the timeout.
+			dt = dt2 / time.Duration(N)
```
Comment (slimsag) [inline cmd/frontend/graphqlbackend/search_results.go]: On a customer instance i just saw a suggestion for something like `timeout:19.99999987534s`, can we move this fix into `longerTime` so that it applies to all timeouts?

Comment (slimsag) [reply cmd/frontend/graphqlbackend/search_results.go]: Hmm, nevermind I see you've added `longerTime` it didn't already exist. This indicates we have this functionality already somewhere else and the two could be in sync. Will investigate.

Comment (slimsag) [reply cmd/frontend/graphqlbackend/search_results.go]: I take these comments back, I found the similar code but it's not similar enough to unify probably: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@4d84cd2b62888f584c514e67e46119dff43a3049/-/blob/cmd/frontend/graphqlbackend/textsearch.go#L483-490

Comment (ijt) [reply cmd/frontend/graphqlbackend/search_results.go]: Done.

**Comment by slimsag** [comment]
Ok, so only complaint I have here is that this should be communicated to the user via a proposed query and not as an error. i.e. the same way that https://sourcegraph.com/search?q=NewRouter shows:

image

This would be done by making it returned here when the timeout occurs: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@4d84cd2/-/blob/cmd/frontend/graphqlbackend/search_alert.go#L35

---

This change is clearly an improvement over the status quo, but as noted above isn't the right / optimal way to implement this.. so do we move forward with this PR or block on that? The consensus I heard was we want to strive for quality > improvement, so I think this PR is blocked on doing the above.

**Comment by slimsag** [comment]
On secondary thought, I think this falls under the category we talked about of changes we want to push through because they solve important issues even though they aren't perfect. i.e. it should be judged on:

1. How important the issue / the users it is affecting are
2. Whether or not it introduces substantial debt

For #1, Sourcegraph.com is not so important it couldn't wait another few days for this improvement. But as I noted with my inline comment I was just about to file an issue for the rough display observed in an important customer environment.

For #2 this doesn't introduce substantial technical debt (just a little because it now exists as a bad example of how to handle such cases), but does introduce UI/UX debt.

Given this, I think we can move forward with this as-is but as we discussed as a team it'll be on you to file an issue to follow up / follow through.

Posting this mostly for visibility since we already chatted on Slack and it sounds like you might just be able to make that change anyway Thanks for bearing with me as I figure out how to be more consistent here @ijt !

**Comment by ijt** [comment]
> Thanks for bearing with me as I figure out how to be more consistent here @ijt !

No problem. It wasn't too much additional work to add the "Did you mean" link, so I went ahead and added that. PTAL.

File: cmd/frontend/graphqlbackend/textsearch.go [hunk 2]
```diff
@@ -481,10 +481,7 @@ func zoektSearchHEAD(ctx context.Context, query *search.PatternInfo, repos []*se
 		return nil, false, nil, err
 	}
 	if resp.FileCount == 0 && resp.MatchCount == 0 && since(t0) >= searchOpts.MaxWallTime {
-		timeoutToTry := 2 * searchOpts.MaxWallTime
-		if timeoutToTry <= 0 {
-			timeoutToTry = 10 * time.Second
-		}
+		timeoutToTry := longer(2, searchOpts.MaxWallTime)
 		err2 := errors.Errorf("no results found before timeout in index search (try timeout:%v)", timeoutToTry)
```
Comment (slimsag) [inline cmd/frontend/graphqlbackend/textsearch.go]: ideally this would also return a suggestion

Comment (ijt) [reply cmd/frontend/graphqlbackend/textsearch.go]: I agree. It would take some restructuring of the code around it though. Filed https://github.com/sourcegraph/sourcegraph/issues/4513.
