### PR TITLE
search: fix issue preventing search patterns with @

### LINKED ISSUE #29477: search error containing `@`: parsing regex: "missing closing )"
**Repro:**

1. Run this query on `sourcegraph.com`:
```
query {
  compute(query:"patterntype:regexp TODO @([\\w]+) count:all repo:^github\\.com/sourcegraph/handbook") {
	... on ComputeMatchContext{
          matches {
              value
	  }
    }
  }
}
```

**Expected:**
Should return results. Note that if you change the `repo` to be `sourcegraph/sourcegraph` rather than `sourcegraph/handbook` it does return results.

**Actual:**
Error message:
```
"1 error occurred:\n\t* Repo search failed: bad request: error parsing regexp: missing closing ): `(TODO).*?(`\n\n"
```

### PR DESCRIPTION
**Pull request by rvantonder**
Fixes #29477.

Follow up to quick-n-dirty fix in https://github.com/sourcegraph/sourcegraph/pull/27881 (i.e., https://github.com/sourcegraph/sourcegraph/pull/27817) which needed to handle an additional special case 😑

### CODE REVIEW

File: internal/search/run/repository.go [hunk 1]
```diff
@@ -127,6 +115,41 @@ func (s *RepoSearch) Required() bool {
 	return s.IsRequired
 }
 
+// validRepoPattern returns true if the pattern part of a query can be used to
+// search repos. A problematic case we check for is when the pattern contains `@`,
+// which may confuse downstream logic to interpret it as part of `repo@rev` syntax.
+func validRepoPattern(pattern string) (string, bool) {
+	patternPrefix := strings.SplitN(pattern, "@", 2)
+	if len(patternPrefix) == 0 {
```
Comment (camdencheek) [inline internal/search/run/repository.go:123]: This doesn't look right. I don't think this condition can ever evaluate to true because `len(patternPrefix)` will always be either 1 or 2.

File: internal/search/run/repository.go [hunk 2]
```diff
@@ -127,6 +115,41 @@ func (s *RepoSearch) Required() bool {
...
+		// No "@" in pattern? We're good.
+		return pattern, true
+	}
+
+	if patternPrefix[0] != "" {
+		// Extend the repo search using the pattern value, but
+		// since the pattern contains @, only search the part
```
Comment (camdencheek) [inline internal/search/run/repository.go:130]: This comment also doesn't look right to me. It says "since the pattern contains @", but we don't know that the pattern contains `@` here.

**Review by camdencheek — CHANGES_REQUESTED** [review]

File: internal/search/run/repository.go (hunk 1 above)
Comment (rvantonder) [reply internal/search/run/repository.go]: Good eye--this was a noop before then but caught by the other logic (still didn't handle the regex issue). Should be fixed now.

**Review by camdencheek — APPROVED** [review]
