### PR TITLE
JetBrains: Make resize padding macOS-only and remove bottom padding

### LINKED ISSUE #37669: JetBrains: Make the weird popup padding nicer
Resizing a window or splitter part doesn't work in a few pixels around the JCEF component.
To make the UX better, we added 4px of padding at both sides and 5px at the bottom of the panel.
It looks ugly, though.

Solution ideas:

1. Catch the "resize started" event in Java, and add the necessary paddings only during resizing.
Pro: Solves the resize problem.
Con: It'd look a bit weird temporarily.

2. Add invisible Swing components around the JCEF to overlay it and catch mouse events when resizing.
Pro: Solves the resize problem. Has no temporary glitches on the UI.
Con: Makes some part of the browser content inaccessible with the mouse. It's just a few pixels, however: no big deal on the sides, maybe a little weird at the bottom.

@vdavid: I'd try #2 first

### PR DESCRIPTION
**Pull request by philipp-spiess**
Closes #37669

Unfortunlaty this is the best I could do. Here are a few observations:

- On Windows and Linux, the padding is not necessarily needed. Without it, there are a few fewer pixels that show the resize cursor but I still found it usable. In addition, I was not able to reproduce the issue where resizing would suddenly "stop" on those platforms. Hence I think it makes sense to not show these paddings on that platforms.
- On macOS, the left and right paddings are still necessary. Without it, the resizing would stop during the interaction. I also tried to play around with adding custom event listeners (the same way that the `StatusText` component does internally that is used by the `JBPanelWithEmptyText` component but I was not able to make it work no matter what I tried :( I did notice, however, that the bottom padding does not seem to be necessary anymore.

## Test plan

(Put a video on Google drive since it was exceeding the 100MB limit and I already recorded it via QuickTime instead of Loom. Old habits die hard 🙈)

https://drive.google.com/file/d/1uRNCQxm6bFdHBXryNAhVuHfx5f6Hosbd/view?usp=sharing

## App preview:

- [Web](https://sg-web-ps-jetbrains-resize-paddings.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ityajgkwrt.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Review by jjinnii — APPROVED** [review]
LGTM thanks for working on this Philipp! I think this is more than great for the first release (we didn't have any internal testers call this out).

File: client/jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java [hunk 1]
```diff
@@ -54,11 +55,14 @@ public FindPopupPanel(@NotNull Project project, @NotNull FindService findService
...
-        // doesn't properly pass the mouse events to Swing.
-        // 4px is the minimum amount to make it work for the window resize, and 5px for the splitter.
+
         BorderLayoutPanel topPanel = new BorderLayoutPanel();
-        topPanel.setBorder(JBUI.Borders.empty(0, 4, 5, 4));
+        // The border is needed on macOS because without it, window and splitter resize don't work because the JCEF
+        // doesn't properly pass the mouse events to Swing.
+        // 4px is the minimum amount to make it work for the window resize, the splitter works without a padding.
+        if (OS.isMacOSX()) {
+            topPanel.setBorder(JBUI.Borders.empty(0, 4, 0, 4));
```
Comment (vdavid) [inline client/jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java:64]: Unfortunately, the 5px are needed at the bottom :(
See me repro the resize bug with the splitter on your branch: https://www.loom.com/share/1bc74f5cf0b347a8ad30184abde36698

Comment (philipp-spiess) [reply client/jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java:64]: @vdavid I can not reproduce this which is scary since it means that Windows and Linux might also have issues that I can not reproduce and it means that `5px` might be enough for your computer but not enough for others. What do you suppose we do? I can add back the `5px` on the bottom for macOS and fix it for you and then we just hope it doesn't come up again?

Comment (vdavid) [reply client/jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java:64]: Hmm, that is weird indeed. I have no better idea than adding it back for macOS :/

Comment (vdavid) [inline client/jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java:64]:
```suggestion
            topPanel.setBorder(JBUI.Borders.empty(0, 4, 5, 4));
```

**Review by vdavid — APPROVED** [review]
LGTM with my suggested change
