### PR TITLE
insights: don't error on empty repo in commit indexer

### LINKED ISSUE #37151: insights: Commit Indexer returns errors on empty repos
When the insights commit indexer attempts to index commits for empty repos it logs an error 
```
error fetching commits from gitserver repo_id: {REPO_ID}: git command [git log --format=format:%H%x00%aN%x00%aE%x00%at%x00%cN%x00%cE%x00%ct%x00%B%x00%P%x00 --after=2021-06-02T08:22:43Z --date-order] failed (output: \\\"\\\"): exit status 128\"\n","stream":"stderr"
```
This should not be an error and the index metadata can be marked as up to date. In addition the error log causes confusion when attempting to debug other issues.

### PR DESCRIPTION
**Pull request by leonore**
closes #37151

instead of erroring we mark the repo as successfully last indexed in `commit_index_metadata`

## Test plan
Added unit tests for the new helper and for the function.

Tested on `enterprise-codeinsights` (before/after):
Screenshot 2022-07-01 at 13 46 51
image

and we successfully insert the metadata.
image

### CODE REVIEW

**Review by chwarwick — APPROVED** [review]
Nice!  it's unfortunate we don't get better error messages back

**Comment by leonore** [comment]
> Nice! it's unfortunate we don't get better error messages back
I was just about to ping you to say we could return nil a level above in the `getCommits` function if we see the empty error message (i.e. not assert on `errors.Is` later), I think that would remove the error log. or we could make it warning. it's done through the observation pkg which I'm not so familiar with

File: enterprise/internal/insights/compression/worker.go [hunk 1]
```diff
@@ -207,7 +239,11 @@ func getCommits(ctx context.Context, db database.DB, name api.RepoName, after ti
 		before = until.Format(time.RFC3339)
 	}
 
-	return gitserver.NewClient(db).Commits(ctx, name, gitserver.CommitsOptions{N: 0, DateOrder: true, NoEnsureRevision: true, After: after.Format(time.RFC3339), Before: before}, authz.DefaultSubRepoPermsChecker)
+	commits, err := gitserver.NewClient(db).Commits(ctx, name, gitserver.CommitsOptions{N: 0, DateOrder: true, NoEnsureRevision: true, After: after.Format(time.RFC3339), Before: before}, authz.DefaultSubRepoPermsChecker)
+	if err != nil && isCommitEmptyRepoError(err, after, until) {
+		return nil, errors.Wrap(EmptyRepoErr, err.Error())
```
Comment (chwarwick) [inline enterprise/internal/insights/compression/worker.go:244]: is returning nil here going to be an issue?

Comment (leonore) [reply enterprise/internal/insights/compression/worker.go:244]: nope, I tested this and it will just not save any commits and update the metadata table:
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/compression/commits.go?L63-71
