### PR TITLE
web: do not parse failed requests in Apollo Client

### LINKED ISSUE #39911: GraphQL client tries to parse 5xx HTML responses as JSON
Sometimes for various reasons the backend (or proxy) responds with a 5xx HTTP error like 504: Gateway Timeout and a body that is `Content-Type: text/html`.

#### Expected behavior:

When this happens, the GraphQL client in the webapp should see that the response is not a 200 OK response, and throw an error that surfaces the status and status text ("504 Gateway Timeout"). This at least gives some indication what happened, and that e.g. a reload could fix it. It should only proceed parsing a response as JSON if it has the status 200 OK.

I'm fairly certain this used to be the case before our switch to Apollo (i.e. the old `requestGraphQL()` function checked the status code before parsing).

#### Actual behavior:

The GraphQL client still tries to parse the response as JSON, resulting in the error "Unexpected token in JSON at position 0" (from the HTML's `<html>` tag). This is confusing for users and CEs trying to debug and looks like there is some kind of bug related to parsing, rather than something like a proxy timeout.

Example of this in the wild (we have seen this many times from customers):

image

/cc @taylorsperry @jasongornall

### PR DESCRIPTION
**Pull request by valerybugakov**
## Context

Throw `HTTPStatusError` on unsuccessful HTTP requests made by Apollo Client.
Closes #39911

## Test plan

1. `sg start web-standalone`.
2. Open the web application with the k8s API as a backend
3. See that 401 are thrown before Apollo Client tries to parse HTML responses as JSON.

## App preview:

- [Web](https://sg-web-vb-apollo-client-fetch.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ebnpowaqdl.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

File: client/web/src/user/settings/backend.tsx [hunk 1]
```diff
@@ -120,10 +120,8 @@ batchedEvents
             }
             return EMPTY
         }),
-        catchError(error => {
-            console.error('Error logging events:', error)
-            return []
-        })
+        // TODO: log errors to Sentry
+        catchError(() => [])
```
Comment (valerybugakov) [inline client/web/src/user/settings/backend.tsx:124]: This removes a lot of noise from the console and will be properly addressed in https://github.com/sourcegraph/sourcegraph/pull/40458

**Review by mrnugget — APPROVED** [review]
Nice!
