### PR TITLE
JetBrains: Fixed: filter out zero-width spaces from inline autocomplete

### LINKED ISSUE #53595: JetBrains: autocomplete: weird prefixes in completions
30-sec Loom demoing the problem:
https://www.loom.com/share/7a0a2c4ca9724500a60f7fea2ef170e9?sid=c6693467-977c-43df-b791-dec71a5893fd

Suggestion: make sure that char is not there in the completions.

### PR DESCRIPTION
**Pull request by Gedochao**
Fixes #53595 

Cody was returning completions with zero-width spaces for whatever reason.
I just filter them out.

## Test plan
Included a unit test.
Can double check if the bug is still replicable.

### CODE REVIEW

File: client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyCompletionsManager.java [hunk 1]
```diff
@@ -167,6 +168,14 @@ private CompletableFuture<Void> triggerCompletionAsync(
             });
   }
 
+  public static InlineCompletionItem removeUndesiredCharacters(InlineCompletionItem item) {
+    String newInsertText = item.insertText.replaceAll("\u200b", ""); // no zero-width spaces, pls
```
Comment (vdavid) [inline client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyCompletionsManager.java:172]: I also got an LSEP (`U+2028`) char in another completion. Not sure why this is happening, but I think we should also drop those.

```suggestion
    String newInsertText = item.insertText.replaceAll("[\u200b\u2028]", ""); // no zero-width spaces or line separator chars, pls
```

**Review by vdavid — APPROVED** [review]
Looks good, added a suggestion. Thanks for the test!

File: client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyCompletionsManager.java (hunk 1 above)
Comment (Gedochao) [reply client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyCompletionsManager.java]: I filled in a unit test for it as well 👌
