### PR TITLE
search: fix for negative offsets error in DeleteExcessRows

### LINKED ISSUE #3051: Error logs from search table code in dev
```
22:10:36               frontend | ERROR deleting excess rows from searches table, error: deleting excess rows in recentSearches table: pq: OFFSET must not be negative
22:10:36               frontend | ERROR error getting search suggestions: , error: Post http://localhost:3184/search: dial tcp [::1]:3184: connect: connection refused (and 5 more)
22:10:37               frontend | ERROR deleting excess rows from searches table, error: deleting excess rows in recentSearches table: pq: OFFSET must not be negative
22:10:37               frontend | ERROR error getting search suggestions: , error: Post http://localhost:3184/search: dial tcp [::1]:3184: connect: connection refused (and 5 more)
22:10:37               frontend | ERROR error getting search suggestions: , error: Post http://localhost:3184/search: dial tcp [::1]:3184: connect: connection refused (and 5 more)
22:10:37               frontend | ERROR deleting excess rows from searches table, error: deleting excess rows in recentSearches table: pq: OFFSET must not be negative
```
Seeing these whenever I do a search locally

### PR DESCRIPTION
**Pull request by ijt**
Fixes #3051 

Test plan: I added tests that reproduce the issue and got them to pass.

### CODE REVIEW

File: cmd/frontend/graphqlbackend/search.go [hunk 1]
```diff
@@ -83,6 +83,9 @@ func addQueryToSearchesTable(q string) {
 	if err := db.RecentSearches.Add(ctx, q); err != nil {
 		log15.Error("adding query to searches table", "error", err)
 	}
+	if err := db.RecentSearches.DeleteExcessRows(ctx, 1e5); err != nil {
```
Comment (slimsag) [inline cmd/frontend/graphqlbackend/search.go]: nit: I am not as smart as others so I had to look up the value of `1e5`; maybe writing `100000` is better?

**Comment by slimsag** [comment]
lgtm

File: cmd/frontend/graphqlbackend/search.go (hunk 1 above)
Comment (ijt) [reply cmd/frontend/graphqlbackend/search.go]: Hard to say. With 100000 you have to count zeros. 1e5 has them counted for you already. :D
