### PR TITLE
Bug fix: Setup Wizard > Determine no repos exist status in nav

### LINKED ISSUE #46539: Enhancement: 'Repos up to date' shouldn't be state if no repos are connected
Image
Screenshot 2023-03-01 at 2 07 25 PM

Expectation:
1. It should be clear to a new user onboarding that no repo's are connected, therefore they are not up to date. In fact, this is the first onboarding step. So this state should be flagged somehow, or at least displaying a more clear state.
2. If user is able to exit Setup Wizard without repos connected, this state & banner should be clear that there are no repos & link to the Setup Wizard.

### PR DESCRIPTION
**Pull request by st0nebraker**
Closes #46539. Determines if no repos exist and display more accurate repo status.

### BEFORE
image

### AFTER
Screenshot 2023-03-14 at 3 34 51 PM

## Test plan
- Run `EXTSVC_CONFIG_ALLOW_EDITS=1 sg start`
- Delete all connected code hosts
- Ensure nav item updates correctly
- Ensure nav item updates correctly after repos are added

## App preview:

- [Web](https://sg-web-becca-bug-fix-false-repos-up-to.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.96% (+29.70 kb) 🔺 | -0.38% (-54.84 kb) 🔽 | -0.74% (-84.54 kb) 🔽 | -1.10% (-8) 🔽 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/becca/bug-fix-false-repos-up-to-date-status/compare-report.html;tab=live_object) for a full comparison between the commits 0a497db and 4134830 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by vovakulikov — APPROVED** [review]
Probably it may be too risky to do it in this PR but I'm wondering it seems like RepositoryStats and Status messages are always used together, does it make sense to merge these two into one query and have only one network request for this 

```
 query StatusAndRepoStats {
       repositoryStats {
            __typename
            total
            notCloned
            cloned
            cloning
            failedFetch
            corrupted
            indexed
        }
        statusMessages {
            ... on GitUpdatesDisabled {
                __typename

                message
            }

            ... on CloningProgress {
                __typename

                message
            }

            ... on IndexingProgress {
                __typename

                notIndexed
                indexed
            }

            ... on SyncError {
                __typename

                message
            }

            ... on ExternalServiceSyncError {
                __typename

                externalService {
                    id
                    displayName
                }
            }
        }
    }
```

File: client/web/src/nav/StatusMessagesNavItem.tsx [hunk 1]
```diff
@@ -24,7 +24,8 @@ import {
     ErrorAlert,
 } from '@sourcegraph/wildcard'
 
-import { StatusMessagesResult } from '../graphql-operations'
+import { StatusMessagesResult, RepositoryStatsResult, RepositoryStatsVariables } from '../graphql-operations'
+import { REPOSITORY_STATS } from '../site-admin/backend'
```
Comment (vovakulikov) [inline client/web/src/nav/StatusMessagesNavItem.tsx:28]: @st0nebraker I think this import is a culprit of bundle size increasing https://github.com/sourcegraph/sourcegraph/pull/49348#issuecomment-1468892599

Probably it would be safer just create the same query in this file instead of importing (also see my comment about merging queries)

Comment (st0nebraker) [reply client/web/src/nav/StatusMessagesNavItem.tsx]: Good call, that's much cleaner too. I combined the queries in [fff0826](https://github.com/sourcegraph/sourcegraph/pull/49348/commits/fff0826a5d274057cde287cf92e6599ee27d2ec7)

**Review by vovakulikov — APPROVED** [review]
Tested locally, works as expected thanks

**Comment by vovakulikov** [comment]
@benjaminwgordon it just strikes me that you've updated queries for the progress bar, we also need to update queries name in the refetch queries in order to preserve our logic about updating progress bar when we add/update/remove code host connections 

https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+file%3A%5Eclient%2Fweb%2Fsrc%2Fsetup-wizard+++refetchQueries%3A&patternType=regexp&sm=1&groupBy=path

File: client/web/src/nav/StatusMessagesNavItemQueries.ts [hunk 2]
```diff
@@ -1,7 +1,17 @@
...
+    query StatusAndRepoStats {
+        repositoryStats {
+            __typename
+            total
+            notCloned
+            cloned
+            cloning
+            failedFetch
+            corrupted
+            indexed
```
Comment (mrnugget) [inline client/web/src/nav/StatusMessagesNavItemQueries.ts:13]: Why fetch all of these if we only need `total`?

File: client/web/src/nav/StatusMessagesNavItem.tsx [hunk 3]
```diff
@@ -191,6 +191,9 @@ export const StatusMessagesNavItem: React.FunctionComponent<React.PropsWithChild
         } else if (data.statusMessages?.some(({ __typename: type }) => type === 'IndexingProgress')) {
             codeHostMessage = 'Indexing repositories...'
             iconProps = { as: CloudSyncIconRefresh }
+        } else if (data.statusMessages.length === 0 && data.repositoryStats.total === 0) {
```
Comment (mrnugget) [inline client/web/src/nav/StatusMessagesNavItem.tsx:194]: I'm curious: why not introduce a new status message on the backend (and in GraphQL API) instead of checking for absence of message and a different attribute?

**Review by mrnugget — COMMENTED** [review]
I only discovered today that we have this new message and looked at how it's implemented. Left two non-urgent-mostly-curiosity questions :)

File: client/web/src/nav/StatusMessagesNavItemQueries.ts (hunk 2 above)
Comment (vovakulikov) [reply client/web/src/nav/StatusMessagesNavItemQueries.ts:13]: Oh, I think before this query was shared between different views and probably the site admin repositories page required these fields to render proper status icon 

@st0nebraker but since we decoupled this query we can fix status message specific query, I made a small PR here https://github.com/sourcegraph/sourcegraph/pull/49711

File: client/web/src/nav/StatusMessagesNavItem.tsx (hunk 3 above)
Comment (st0nebraker) [reply client/web/src/nav/StatusMessagesNavItem.tsx:194]: Short answer, because I'm not versed in Go and this was quick 😅 - @gl-srgr can I pair with you after starship on this small change? I'll write down & follow up next week

Comment (gl-srgr) [reply client/web/src/nav/StatusMessagesNavItem.tsx:194]: Yeah that works for me

Comment (st0nebraker) [reply client/web/src/nav/StatusMessagesNavItem.tsx:194]: #50317 is the follow up 😄
