### PR TITLE
insights: move permissionsValidator out of the global resolver and in…

### LINKED ISSUE #29055: insights: dashboard mutations are throwing user permissions error
Sometimes when making a request on a dashboard, an authorization error is returning. Looking at the trace, it seems the wrong userId is getting passed into the authorization context:
https://sourcegraph.grafana.net/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22grafanacloud-sourcegraph-traces%22,%7B%22refId%22:%22A%22,%22queryType%22:%22traceId%22,%22query%22:%223f76304056d4cad3%22%7D%5D

I suspect the `permissionsValidator` being attached globally to the `Resolver` isn't getting created on each user request, and instead is trying to share values across sessions. https://sourcegraph.grafana.net/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22grafanacloud-sourcegraph-traces%22,%7B%22refId%22:%22A%22,%22queryType%22:%22traceId%22,%22query%22:%223f76304056d4cad3%22%7D%5D

### PR DESCRIPTION
**Pull request by coury-clark**
Fixes #29055

`Resolver` is instantiated globally per `frontend`, so the `permissionsValidator` was accidentally reusing values from incorrect users.

Also added some tests for the `HasDashboardPermission` function

### CODE REVIEW

File: enterprise/internal/insights/store/dashboard_store.go [hunk 1]
```diff
@@ -372,7 +372,7 @@ SELECT * FROM dashboard_grants where dashboard_id = %s
 `
 
 const getDashboardGrantsByPermissionsSql = `
--- source: enterprise/internal/insights/store/dashboard_store.go:GetDashboardGrants
+-- source: enterprise/internal/insights/store/dashboard_store.go:HasDashboardPermission
```
Comment (CristinaBirkel) [inline enterprise/internal/insights/store/dashboard_store.go:375]: Not related to this PR, but one issue with this seems to be that if this dashboard actually doesn't exist, the this query will return that it does have permission. Which for example results in `UpdateInsightsDashboard` to return `got nil for non-null` instead of `dashboard not found`. I'll create an issue for this. I don't think it's blocking for the release.

**Review by CristinaBirkel — APPROVED** [review]
🎉 I smoke tested it locally, and I think this should fix the issues we've been seeing with randomly not having permission. Great find!! 🕵️
