### PR TITLE
streaming progress: fix low hanging fruit a11y issues

### LINKED ISSUE #18041: Text in the streaming search alerts dropdown is not selectable
The text in the streaming search alerts dropdown is not selectable. When attempting to select the text, the area acts as a button for the accordion and collapses the open warning. 

In the case of actionable information such as a list of repositories that were not searched, the user cannot select these strings and use them to modify their query. 

The hit target for closing the warning should be limited to the warning title and chevron only.

### LINKED ISSUE #18195: Streaming search dropdown is not keyboard navigable
Users can tab to the dropdown and open it, but not navigate to sub-items within it to open notices or interact with the form.

### PR DESCRIPTION
**Pull request by limitedmage**
- Fixes #18041 Text in the streaming search alerts dropdown is not selectable
- Fixes #18195 Can't expand/collapse streaming search alerts with keyboard

FYI @rrhyne  this is what the new focus ring around the search alert looks like:

image

### CODE REVIEW

File: client/web/src/search/results/streaming/progress/StreamingProgressSkippedPopover.tsx [hunk 1]
```diff
@@ -40,40 +40,54 @@ const SkippedMessage: React.FunctionComponent<{ skipped: Skipped; history: H.His
...
-                ) : (
-                    <AlertCircleIcon className="icon-inline mr-2 streaming-skipped-item__icon flex-shrink-0" />
-                )}
-                <span className="flex-grow-1 text-left">{skipped.title}</span>
-
-                {skipped.message &&
-                    (isOpen ? (
-                        <ChevronDownIcon className="icon-inline flex-shrink-0" />
+            <Button
+                className="streaming-skipped-item__button py-2 w-100"
```
Comment (5h1rU) [inline client/web/src/search/results/streaming/progress/StreamingProgressSkippedPopover.tsx:59]: ```border-0 bg-transparent```

Comment (5h1rU) [reply client/web/src/search/results/streaming/progress/StreamingProgressSkippedPopover.tsx:59]: Remember to update snapshots

**Review by 5h1rU — APPROVED** [review]

**Comment by keegancsmith** [comment]
I'm probably piggy backing on something that is unrelated, but I assume how my browser finds "targets" is using a11y APIs. See the screenshot below. It is supposed to be hinting on all inputs/links. Notice that it can't find the search input, which I am guessing is a a11y issue.

image

**Comment by limitedmage** [comment]
> I'm probably piggy backing on something that is unrelated, but I assume how my browser finds "targets" is using a11y APIs. See the screenshot below. It is supposed to be hinting on all inputs/links. Notice that it can't find the search input, which I am guessing is a a11y issue.

I can tab to the search input no problem, so not sure what the issue is in you browser. The frontend platform team is doing a much more deep dive into a11y issues ([see RFC](https://docs.google.com/document/d/1_r8aikiE-zwn0ZkWmOilynNVA3HfmF9Mglgg6ZEkkls/edit#heading=h.trqab8y0kufp)) if you're interested.

**Comment by keegancsmith** [comment]
aah, I think it is something else. It is placing the position of the input at the top left corner (`kh`). So will place it down to a bug in my browser for now since I don't know enough about the DOM :)

**Comment by rrhyne** [comment]
I am checking with Quinn Keast on how he wants to handle the focus state given that he is working on this now. My first take is that the parent of the button element, streaming-skipped-item, needs p-2 padding instead of pt-2. [Figma](https://www.figma.com/file/IyiXZIbPHK447NCXov0AvK/13928-Streaming-search?node-id=1118%3A38028)




The rest of the issues look and work great now.
