### PR TITLE
extsvc: replace `http.DefaultClient` with `httpcli.ExternalDoer`

### LINKED ISSUE #14144: Unable to log in via GitLab OAuth
- **Sourcegraph version:** 3.20.1
- **Platform information:** CentOS 7.8.2003, Docker V19.03.8

#### Steps to reproduce:

1. Connect Sourcegraph to on-premise GitLab via instructions at: https://docs.sourcegraph.com/admin/auth#gitlab
2. Attempt to login to Sourcegraph via GitLab

Note that the GitLab instance is using an https certificate signed by an internal CA.
Sourcegraph site config contains:

    ...
    "auth.providers": [
        {
            "type": "builtin",
            "allowSignup": false
        },
        {
            "type": "gitlab",
            "displayName": "GitLab",
            "url": "https://gitlab.<our-domain>",
            "clientID": "<gitlab OAuth ID>",
            "clientSecret": "<gitlab OAuth secret>"
        }
    ],
    ...
    experimentalFeatures: {
        "tls.external": {
            "certificates": ["<internal CA root certificate pem data>"]
        }
    }

#### Expected behavior:

Successful login.

#### Actual behavior:

After redirecting to GitLab (and successfully logging in if necessary), Sourcegraph responds with "github: unable to get GitLab user".

GitLab logs appear to show successful login and OAuth response.

### PR DESCRIPTION
**Pull request by unknwon**
`httpcli.ExternalDoer` respects `tls.external` settings from our site config where `http.DefaultClient` does not.

Fixes #14144

### CODE REVIEW

File: internal/extsvc/github/client.go [hunk 1]
```diff
@@ -128,7 +129,7 @@ func newRepoCache(apiURL *url.URL, token string) *rcache.Cache {
 func NewClient(apiURL *url.URL, token string, cli httpcli.Doer) *Client {
 	apiURL = canonicalizedURL(apiURL)
 	if gitHubDisable {
-		cli = disabledClient{}
+		cli = httpcli.ExternalDoer()
```
Comment (tsenart) [inline internal/extsvc/github/client.go:132]: This is a mistake I think.

**Review by tsenart — APPROVED** [review]

File: internal/extsvc/github/client.go (hunk 1 above)
Comment (unknwon) [reply internal/extsvc/github/client.go:132]: Good catch :)
