### PR TITLE
fix series status

### LINKED ISSUE #30071: insights: persisted global capture groups loading state should match normal loading state
Both of these insights have not run yet, but they show different states: 

image

Right side: capture group that hasn't run yet. Left side: normal global search insights. 

We should show the same loading state for both, that the capture group insight is processing, *not* "no data to display." This will mislead users to thinking their query was wrong because they would expect both to show the loading state. 

I realize there may be some backend complexity in how we expose loading state from compute.

### PR DESCRIPTION
**Pull request by coury-clark**
Fixes #30071 

This PR makes it so a dynamically generated series (capture group series) will always return at least one series resolver for the purposes of calculating the state. 

## Test plan

After the fix:

CleanShot 2022-02-14 at 12 15 46@2x

### CODE REVIEW

File: enterprise/internal/insights/resolvers/insight_series_resolver.go [hunk 1]
```diff
@@ -148,11 +132,25 @@ func (i insightStatusResolver) BackfillQueuedAt() *graphqlbackend.DateTime {
 	return graphqlbackend.DateTimeOrNil(i.backfillQueuedAt)
 }
 
+func NewStatusResolver(status *queryrunner.JobsStatus, queuedAt *time.Time) *insightStatusResolver {
+	return &insightStatusResolver{
+		totalPoints: 0,
```
Comment (coury-clark) [inline enterprise/internal/insights/resolvers/insight_series_resolver.go:137]: This seems like a liability, and I don't think it's really being used anywhere. It also doesn't have much meaning, so I'm just setting it to zero in this PR. I'll open an issue to deprecate this field.

Comment (coury-clark) [reply enterprise/internal/insights/resolvers/insight_series_resolver.go:137]: FWIW: I don't think we are susceptible to the code monitors count problem with this count for the following reasons:
1. It isn't possible to restrict which repos this runs over (you can't use `repo:` or `context:` filters), so this would *always* report the full value across the entire instance, and it would always be the same. Therefore there isn't a way to narrow down and perform the binary search needed to generate text values.
2. If you were to try and filter the results down to certain repos, those are filtered according to the user permissions that is viewing the chart

cc @andreeleuterio

**Review by CristinaBirkel — APPROVED** [review]
Looks good and works locally for me! 👍
