### PR TITLE
batches: fetch orgs when selecting a namespace

### LINKED ISSUE #44708: Cannot create org batch change after creating new org
Steps to reproduce:

- Create a new org
- Land on the org page
- Click on batch changes
- Click create
- The org namespace is not preselected and also not in the dropdown
- Sad

A page refresh fixes it. That is probably because we take the orgs from the authedUser object and that is never refetched.

### PR DESCRIPTION
**Pull request by BolajiOlajide**
Closes #44708

CleanShot 2022-12-02 at 16 19 09

## Test plan

Steps to reproduce:

* Create a new org
* Land on the org page
* Click on batch changes
* Click create
* The org namespace should be selected by default (previously it wasn't)

## App preview:

- [Web](https://sg-web-bo-fix-namespace-selector-new-org.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.48 kb) | 0.00% (+0.48 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/bo/fix-namespace-selector-new-org/compare-report.html;tab=live_object) for a full comparison between the commits cc6fb0f and cdf3710 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

File: client/web/src/enterprise/batches/create/backend.ts [hunk 1]
```diff
@@ -2,6 +2,21 @@ import { gql } from '@sourcegraph/http-client'
...
 import { batchSpecExecutionFieldsFragment } from '../batch-spec/execute/backend'
 
+export const GET_ORGANIZATIONS = gql`
+    query GetOrganizations {
+        organizations {
+            totalCount
+            nodes {
+                id
+                __typename
+                viewerCanAdminister
```
Comment (LawnGnome) [inline client/web/src/enterprise/batches/create/backend.ts:12]: I don't think we actually need `viewerCanAdminister`, right? May as well save a field resolver where we can.

File: client/web/src/enterprise/batches/create/backend.ts [hunk 2]
```diff
@@ -2,6 +2,21 @@ import { gql } from '@sourcegraph/http-client'
 
 import { batchSpecExecutionFieldsFragment } from '../batch-spec/execute/backend'
 
+export const GET_ORGANIZATIONS = gql`
+    query GetOrganizations {
+        organizations {
+            totalCount
```
Comment (LawnGnome) [inline client/web/src/enterprise/batches/create/backend.ts:8]: Same for `totalCount` — since we're not paginating here, I don't see that we need the count.

(Also, from the GraphQL schema documentation: `The total count of organizations in the connection. This total count may be larger than the number of nodes in this object when the result is paginated.` made me laugh because the connection isn't actually paginated!)

File: client/web/src/enterprise/batches/create/ConfigurationForm.tsx [hunk 3]
```diff
@@ -87,19 +87,23 @@ export const ConfigurationForm: React.FunctionComponent<React.PropsWithChildren<
...
 
+    const loading = batchChangeLoading || batchSpecLoading
+    const error = batchChangeError || batchSpecError || namespaceError
+
     // The namespace selected for creating the new batch change under.
     const [selectedNamespace, setSelectedNamespace] = useState<
         Pick<SettingsUserSubject, 'id'> | Pick<SettingsOrgSubject, 'id'>
     >(defaultSelectedNamespace)
 
+    useEffect(() => {
```
Comment (LawnGnome) [inline client/web/src/enterprise/batches/create/ConfigurationForm.tsx:103]: For my own learning: is the effect hook here to refresh the default after the GraphQL organisations query is complete, or for some other reason?

**Review by LawnGnome — APPROVED** [review]

File: client/web/src/enterprise/batches/create/ConfigurationForm.tsx (hunk 3 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/create/ConfigurationForm.tsx:103]: That's correct. Need the update to bubble to state when the value changes.

File: client/web/src/enterprise/batches/create/backend.ts (hunk 2 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/create/backend.ts:8]: Haha. Yeah the total count is an oversight.

For the other fields, I added it so the fields adhere to the SettingsObject field. I'll confirm again as I might have missed something also.

File: client/web/src/enterprise/batches/create/backend.ts (hunk 1 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/create/backend.ts:11]: We need the `viewerCanAdminister` field to satisfy the `SettingsOrgSubject` type.

CleanShot 2022-12-03 at 14 31 58@2x

File: client/web/src/enterprise/batches/create/backend.ts (hunk 2 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/create/backend.ts]: Removed the `totalCount`

File: client/web/src/enterprise/batches/create/ConfigurationForm.tsx [hunk 4]
```diff
@@ -87,19 +87,23 @@ export const ConfigurationForm: React.FunctionComponent<React.PropsWithChildren<
...
-    const loading = batchChangeLoading || batchSpecLoading
-    const error = batchChangeError || batchSpecError
-
-    const { namespaces, defaultSelectedNamespace } = useNamespaces(
+    const { namespaces, defaultSelectedNamespace, loading: namespaceLoading, error: namespaceError } = useNamespaces(
         settingsCascade,
         batchChange?.namespace.id || initialNamespaceID
     )
 
+    const loading = batchChangeLoading || batchSpecLoading
```
[the remark this answers is not in the document]
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/create/ConfigurationForm.tsx:95]: No, not namespaceLoading.

I'll add this as a comment also to avoid confusion.
The loading variable here is used to toggle the `Create` [button's disabled state](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=bo%2Ffix-namespace-selector-new-org&file=client%2Fweb%2Fsrc%2Fenterprise%2Fbatches%2Fcreate%2FConfigurationForm.tsx&editor=VSCode&version=2.2.14&start_row=248&start_col=20&end_row=256&end_col=29). 

I'll also update the naming to reflect this.

File: client/web/src/enterprise/batches/create/ConfigurationForm.tsx (hunk 3 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/create/ConfigurationForm.tsx:103]: Sure thing.

File: client/web/src/enterprise/batches/create/useNamespaces.ts [hunk 5]
```diff
@@ -48,10 +55,16 @@ export const useNamespaces = (
         throw new Error('No user namespace found')
```
[the remark this answers is not in the document]
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/create/useNamespaces.ts:55]: Well. we only need it to get the user's ID. If there's another way to get the User's ID we can eliminate that dependency and rely strictly on the GraphQL API to get all we need.

[the remark this answers is not in the document]
Comment (eseliger) [reply client/web/src/enterprise/batches/create/useNamespaces.ts:55]: I think we can pass down authenticatedUser.id

File: client/web/src/enterprise/batches/create/backend.ts (hunk 1 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/create/backend.ts:23]: Not for the work in this PR.
But in a broader sense, yes we [do](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/browser/src/shared/platform/settings.ts?L161%3A13-165%3A14).

**Review by Piszmog — APPROVED** [review]

File: client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.tsx [hunk 6]
```diff
@@ -94,7 +96,9 @@ export const EditBatchSpecPage: React.FunctionComponent<React.PropsWithChildren<
     )
 }
 
-interface EditBatchSpecPageContentProps extends SettingsCascadeProps<Settings>, ThemeProps {}
+interface EditBatchSpecPageContentProps extends SettingsCascadeProps<Settings>, ThemeProps {
+    authenticatedUser: AuthenticatedUser | null
```
Comment (eseliger) [inline client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.tsx:100]: shouldn't be nullable, these components are only mounted where authentication is enforced.

**Review by eseliger — APPROVED** [review]
nice! last nit: the authedUser shouldn't be nullable :)

File: client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.tsx (hunk 6 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.tsx:100]: CleanShot 2022-12-07 at 18 35 46@2x

Yes, you're correct, but since the field is being prop-drilled from the parent component `SourcegraphWebApp,` which works for both authenticated and non-authenticated, its type is nullable.

Comment (eseliger) [reply client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.tsx:100]: It shouldn't be - the GlobalBatchChangesArea is wrapped in a `withAuthenticatedUser` 🤔 https://sourcegraph.com/-/editor?remote_url=github.com%2Fsourcegraph%2Fsourcegraph&branch=es%2Fbump-node-18&file=client%2Fweb%2Fsrc%2Fenterprise%2Fbatches%2Fglobal%2FGlobalBatchChangesArea.tsx&editor=VSCode&version=2.2.14&start_row=98&start_col=27&end_row=98&end_col=27

Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.tsx:100]: That's `NamespaceBatchChange` component, the [GlobalBatchChange](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/web/src/enterprise/batches/global/GlobalBatchChangesArea.tsx?L66) component has its value set to nullable. 

The `CreateBatchChange` component is mounted from this place, hence why it doesn't have it. It seems only that component needs to have the value of `authenticatedUser` as nullable.

Comment (eseliger) [reply client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.tsx:100]: Oh weird, it should be wrapped in it. I think that's an oversight from a recent refactor. Can you wrap the create page in it?

Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.tsx:100]: Sure thing.

Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.tsx:100]: Turns out it's not an oversight; the `CreateBatchChange` and `BatchChangeList` pages are wrapped in the `GlobalBatchChange` component.

Those pages have a view that's to be displayed for unauthenticated users, especially on `sourcegraph.com`

CleanShot 2022-12-08 at 00 04 55@2x

Comment (eseliger) [reply client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.tsx:100]: Yep but we can wrap the create page, that one should not be accessible.

Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.tsx:100]: CleanShot 2022-12-08 at 09 43 44@2x

It's actually not accessible - I logged out of the `demo.sourcegraph.com` instance and tried accessing the `/batch-changes/create` page and I got redirected to the sign in page.

Comment (eseliger) [reply client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.tsx:100]: Even more reason to make it non nullable by type 🙂
