### PR TITLE
fix #1984: use popoverRef and not rootRef to hide PopoverButton on outside click

### LINKED ISSUE #1984: Clicking inside popovers causes them to close
- **Sourcegraph version:** "Sourcegraph.com"
- **Platform information:** 

#### Steps to reproduce:

1. Open any popover (e.g. extension debug popover, repo popover on a repo page) 
2. Click inside, notice they'll close

@lguychard perhaps this is due to merging https://github.com/sourcegraph/sourcegraph/commit/7d79756a3fcb7e3e9693c7260eb0fc4c35ab8b78?

### PR DESCRIPTION
**Pull request by lguychard**

### CODE REVIEW

File: shared/src/components/PopoverButton.tsx [hunk 1]
```diff
@@ -57,6 +57,7 @@ export class PopoverButton extends React.PureComponent<Props, State> {
     public state: State = { open: false }
 
     private rootRef: HTMLElement | null = null
+    private popoverRef: HTMLElement | null = null
```
Comment (felixfbecker) [inline shared/src/components/PopoverButton.tsx]: Btw you could simplify this with `React.createRef()`

Comment (lguychard) [reply shared/src/components/PopoverButton.tsx]: Thanks for the tip! I didn't know `createRef()`
