### PR TITLE
Fix match for commit and diff merged into one

### LINKED ISSUE #16899: Support merging different commit data for type:diff and type:commit
We merge commit data for queries like `type:commit (author:foo or author:bar)`. But for a query like `(type:commit or type:diff) author:foo` we merge matching commits by URL (so only a commit message or a diff content is shown, not both). A better experience would be to show both the union of commit message and diff content.

### PR DESCRIPTION
**Pull request by camdencheek**
When `(type:commit or type:diff)`, if the query matched the same commit
for both a diff and a commit message, only one result would be returned
because we merge `or` results by URL and the URL is the same for the
diff and the commit that the diff is for.

This commit merges diffs and commits separately so that if a query
matches a commit's message and a commit's diff, both will be returned.

Fixes #16899

Example result of the query `repo:^github\.com/sgtest/sourcegraph-typescript$ (type:diff or type:commit) subscription after:"june 11 2019" before:"june 13 2019"`
Screen Shot 2021-01-07 at 13 11 07

### CODE REVIEW

File: cmd/frontend/graphqlbackend/search_results.go [hunk 1]
```diff
@@ -769,7 +770,11 @@ func unionMerge(left, right *SearchResultsResolver) *SearchResultsResolver {
 			continue
 		}
 		if commitMatch, ok := r.ToCommitSearchResult(); ok {
-			rightCommitMatches[commitMatch.url] = commitMatch
+			if commitMatch.DiffPreview() != nil {
```
Comment (camdencheek) [inline cmd/frontend/graphqlbackend/search_results.go:773]: Is there a better way to determine whether something is a diff or a commit message than just by checking whether the diff preview exists?

Comment (rvantonder) [reply cmd/frontend/graphqlbackend/search_results.go:773]: Looks like this is the best (only?) current way. We need more and better types to reflect commit structures. E.g., this nested [commit definition](https://github.com/sourcegraph/sourcegraph/blob/484820dd8b5912499da29daee81f376809e5765f/internal/vcs/git/commits.go#L24) doesn't include a member for diff content (and diff contents are inextricably connected to a commit, even if it is empty, so either the definition is incomplete/underspec'ed or we are nesting types unnecessarily). 

I've been thinking about this from a query perspective recently, and we should try have our types mirror expressions in a query (just like `type:diff` should have a corresponding type definition to case on here). But our code isn't that organized yet.

**Review by rvantonder — APPROVED** [review]
