### PR TITLE
batches: replace empty changesets list view for drafts

### LINKED ISSUE #32342: SSBC: Replace empty changesets list view for drafts
It's possible to navigate to the BC details page (changesets list) before any changesets have been created. The current empty list view makes it sound like something went wrong ("your query may be too narrow... your steps may not do anything...") since pre-SSBC, this page was inaccessible until after a batch spec is applied. Instead of the current empty list view, we will show a message indicating if an execution is happening.

Design: https://github.com/sourcegraph/sourcegraph/issues/31419.
Figma: https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/SSBC?node-id=2160%3A65223

### PR DESCRIPTION
**Pull request by BolajiOlajide**
Closes #32342

Screenshot 2022-03-13 at 23 55 50

## Test plan

I verified this change by visiting the detail page for a draft batch change, and seeing the updated copy is reflected in the UI.

### CODE REVIEW

File: client/web/src/enterprise/batches/detail/changesets/EmptyChangesetListElement.tsx [hunk 1]
```diff
@@ -1,27 +1,21 @@
...
-                being made.
-            </strong>
-        </p>
-        <p>
-            Try the command on a local instance of one of the repositories returned in your search results. Run{' '}
-            <span className="text-monospace">git status</span> and ensure it produced changed files.
-        </p>
-    </div>
-)
+export const EmptyChangesetListElement: React.FunctionComponent<{}> = () => {
```
Comment (eseliger) [inline client/web/src/enterprise/batches/detail/changesets/EmptyChangesetListElement.tsx:8]: This should only be shown if the batch change is actually a draft, otherwise, we want to keep the old content. Also, we want to show this only when the feature flag for server-side execution is on.

File: client/web/src/enterprise/batches/detail/changesets/EmptyChangesetListElement.tsx [hunk 2]
```diff
@@ -1,27 +1,21 @@
...
+    const location = useLocation()
+    return (
+        <div className={styles.emptyChangesetListElementBody}>
+            <h3 className="mb-2">No changesets exist</h3>
+            <div className={styles.emptyChangesetListElementContent}>
+                <span>This batch change is a draft. A batch specification must be executed to create changesets.</span>
+                <Link to={`${location.pathname}/edit`} rel="noopener">
```
Comment (eseliger) [inline client/web/src/enterprise/batches/detail/changesets/EmptyChangesetListElement.tsx:15]: I _think_ react router actually supports relative paths like `./path`, but not 100% sure.

Comment (eseliger) [reply client/web/src/enterprise/batches/detail/changesets/EmptyChangesetListElement.tsx:15]: Also, if we don't open a new tab, we also don't need the `rel` flag I think.

**Review by eseliger — COMMENTED** [review]
Sorry this wasn't clear from the requirements, but we actually want to have both and show the new one conditionally.

File: client/web/src/enterprise/batches/detail/changesets/EmptyChangesetListElement.tsx (hunk 2 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/detail/changesets/EmptyChangesetListElement.tsx:15]: When I make use of a relative `path`, it doesn't retain the `URL params`, so 
`https://sourcegraph.test:3443/users/bolaji/batch-changes/another-batch-change` becomes `https://sourcegraph.test:3443/users/bolaji/batch-changes/edit` instead of `https://sourcegraph.test:3443/users/bolaji/batch-changes/another-batch-change/edit`

Comment (eseliger) [reply client/web/src/enterprise/batches/detail/changesets/EmptyChangesetListElement.tsx:15]: sad, alright! I think there was a way but it's not important. 😬

Comment (courier-new) [reply client/web/src/enterprise/batches/detail/changesets/EmptyChangesetListElement.tsx:15]: Funny you'd run into this, I was actually observing this on my own PR, too! It seems to treat the URL parameter as ancillary to the actual path, which is definitely a bit unexpected. react-router's docs also don't talk about this at all. In fact, they barely mention relative links. 😂

Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/detail/changesets/EmptyChangesetListElement.tsx]: Yeah! I find it weird.

File: client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx [hunk 3]
```diff
@@ -60,6 +62,8 @@ interface Props
         ExtensionsControllerProps,
         SettingsCascadeProps {
     batchChangeID: Scalars['ID']
+    batchChangeState: BatchChangeState
+    executionEnabled: boolean
```
Comment (courier-new) [inline client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx:66]: I know we're guilty of this in a number of places still, but we're trying to more consistently name our boolean variables/props with an `is` prefix, like `isExecutionEnabled`, so it's clearer that their value is a boolean even if you don't know the TS type.

 ```suggestion
    isExecutionEnabled: boolean
```

If you happen to spot other instances where we break this rule, feel free to correct them, too. 🙂

Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx:66]: No problem. I wasn't sure of the standard so thanks for clarifying.
I'll update this PR accordingly. Thanks.

File: client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx [hunk 4]
```diff
@@ -233,6 +239,22 @@ const BatchChangeChangesetsImpl: React.FunctionComponent<Props> = ({
 
     const showSelectRow = viewerCanAdminister && (selected === 'all' || selected.size > 0)
 
+    const renderEmptyElement = useCallback(() => {
```
Comment (courier-new) [inline client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx:242]: Thoughts on memoizing just the return value, rather than defining this as a callback?

```suggestion
    const emptyElement = useMemo(() => {
```

_(then, further down)_

```diff
- emptyElement={renderEmptyElement()}
+ emptyElement={emptyElement}
```

File: client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.tsx [hunk 5]
```diff
@@ -0,0 +1,19 @@
...
+import styles from './EmptyDraftChangesetListElement.module.scss'
+
+export const EmptyDraftChangesetListElement: React.FunctionComponent<{}> = () => {
+    const location = useLocation()
+    return (
+        <div className={styles.emptyDraftChangesetListElementBody}>
+            <h3 className="mb-2">No changesets exist</h3>
+            <div className={styles.emptyDraftChangesetListElementContent}>
+                <span>This batch change is a draft. A batch specification must be executed to create changesets.</span>
+                <Link to={`${location.pathname}/edit`}>View the most recent specification.</Link>
```
Comment (courier-new) [inline client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.tsx:15]: I know this is the copy from the Figma, but we keep telling Rob we don't actually call it a "batch specification" anywhere, we only call it a "batch spec." 😂 I know, I know, abbreviations are bad, but inconsistency is worse maybe? Anyway:

```suggestion
                <span>This batch change is a draft. A batch spec must be executed to create changesets.</span>
                <Link to={`${location.pathname}/edit`}>View the most recent spec.</Link>
```

File: client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx [hunk 6]
```diff
@@ -233,6 +239,22 @@ const BatchChangeChangesetsImpl: React.FunctionComponent<Props> = ({
...
+            return <EmptyChangesetSearchElement />
+        }
+
+        if (onlyArchived) {
+            return <EmptyArchivedChangesetListElement />
+        }
+
+        if (batchChangeState === BatchChangeState.DRAFT && isExecutionEnabled) {
+            return <EmptyDraftChangesetListElement />
+        }
```
Comment (courier-new) [inline client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx:253]: 👍 Perfect, love it!!

File: client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.module.scss [hunk 7]
```diff
@@ -0,0 +1,16 @@
+@import 'wildcard/src/global-styles/breakpoints';
+
+.empty-draft-changeset-list-element {
+    &__body {
+        max-width: 45rem;
```
Comment (courier-new) [inline client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.module.scss:5]: Does the `max-width` do anything here?

File: client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.story.tsx [hunk 8]
```diff
@@ -87,6 +90,8 @@ add('List of expanded changesets', () => (
                     viewerCanAdminister={boolean('viewerCanAdminister', true)}
                     expandByDefault={true}
                     settingsCascade={EMPTY_SETTINGS_CASCADE}
+                    batchChangeState={BatchChangeState.OPEN}
+                    isExecutionEnabled={false}
```
Comment (LawnGnome) [inline client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.story.tsx:94]: We might need a new storybook here with `isExecutionEnabled={true}`, since I can't find a way to trigger the new behaviour with the current storybook. (Am I missing something?)

File: client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.tsx [hunk 9]
```diff
@@ -0,0 +1,19 @@
...
+import { Link } from '@sourcegraph/wildcard'
+
+import styles from './EmptyDraftChangesetListElement.module.scss'
+
+export const EmptyDraftChangesetListElement: React.FunctionComponent<{}> = () => {
+    const location = useLocation()
+    return (
+        <div className={styles.emptyDraftChangesetListElementBody}>
+            <h3 className="mb-2">No changesets exist</h3>
+            <div className={styles.emptyDraftChangesetListElementContent}>
```
Comment (LawnGnome) [inline client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.tsx:13]: Can/should we do this with utility classes instead of a new SCSS class? (Probably more a question for @eseliger and @courier-new, because I don't know what our current frontend house style is, but in the past it seems to have tended towards utility classes.)

**Review by LawnGnome — APPROVED** [review]
I have a couple of questions, but this looks solid to me. :+1:

File: client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.tsx (hunk 5 above)
Comment (eseliger) [reply client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.tsx:15]: Thank you Kelli 😆 Now I am finally not the only one griping about this all the time :phew:

File: client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.tsx (hunk 9 above)
Comment (eseliger) [reply client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.tsx:13]: I tend to like utility classes because they make it much easier for me to get something going quickly. However the general sentiment seems to be pretty split, some like them and some say we should get rid of them ASAP. I personally don't have a strong opinion here, but it would definitely not be more inconsistent if we kept this as-is.

File: client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.module.scss [hunk 10]
```diff
@@ -0,0 +1,16 @@
+@import 'wildcard/src/global-styles/breakpoints';
```
Comment (eseliger) [inline client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.module.scss:1]: we don't use a breakpoint in here, so we can probably remove it.

File: client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx (hunk 4 above)
Comment (eseliger) [inline client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx:242]: Great job figuring out this logic! Makes a lot of sense!

**Review by eseliger — APPROVED** [review]
Great work!!

File: client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.tsx (hunk 5 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.tsx:15]: Haha! Sure I'll update this.

File: client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx (hunk 4 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx:242]: No downsides to this. I'll switch to `useMemo`.

File: client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.module.scss (hunk 7 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.module.scss:5]: I can't remember why I added it here. Tested on a wide screen and everything looks good, I guess it was an oversight. I'll remove it now.

File: client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.tsx (hunk 9 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.tsx:13]: Yes, I noticed there's a mix of both in different places. 
Following the [general guidelines for styling](https://docs.sourcegraph.com/dev/background-information/web/styling#general-guidelines), I opted for the approach to colocate the styles in a corresponding stylesheet as opposed to mixing them.

I'm happy to make the change if there's an opposing view though.

Comment (eseliger) [reply client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.tsx:13]: No, you're good. I think I am mostly an offender of that style guide here and shouldn't spread that opinion more. Thanks for sticking to the documented way!

File: client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx (hunk 4 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx:242]: Haha. Yeah.

File: client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.module.scss (hunk 10 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.module.scss:1]: Done.

File: client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.story.tsx (hunk 8 above)
Comment (BolajiOlajide) [reply client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.story.tsx:102]: I've added the storybook for that. cc @LawnGnome

File: client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.tsx (hunk 9 above)
Comment (courier-new) [reply client/web/src/enterprise/batches/detail/changesets/EmptyDraftChangesetListElement.tsx:14]: I also don't have a strong opinion on this. I personally also prefer utility classes, which means Batch Changes on the whole is probably a big offender of that style guide. 😂 But to be fair, the guide also says:

> Create utility classes for styles that should be shared horizontally between components.

as well as

> it is recommended to make use of [Bootstrap’s margin and padding utilities](https://getbootstrap.com/docs/4.5/utilities/spacing/), which are configured to align with the 8pt grid

So *technically* we're just following that piece of the guidance. 👀

**Review by courier-new — APPROVED** [review]
