### PR TITLE
fix combineLatestOrDefault for builtin panels

### LINKED ISSUE #24535: Find references broken when clicked on extension or loaded directly (...#tab=references)
visit this, references are broken: https://sourcegraph.com/github.com/grafana-tools/sdk@9b7b5661617c60dbf773f49c042e32160328a200/-/blob/panel.go?L538:17#tab=references

visit this, references work: https://sourcegraph.com/github.com/grafana-tools/sdk@9b7b5661617c60dbf773f49c042e32160328a200/-/blob/panel.go?L538:17

from @muratsu 
> This is a frontend state/race issue though. My guess is that it's hard to track but easy to fix. At least nothing is broken on backend

[more context](https://sourcegraph.slack.com/archives/C022SPMNR0W/p1630543274039400?thread_ts=1630541209.024300&cid=C022SPMNR0W) in slack thread with screenshots

### PR DESCRIPTION
**Pull request by tjkandala**
Fix #24535. 

`combineLatestOrDefault` used to create Observables with `fromArray`, but was [changed](https://github.com/sourcegraph/sourcegraph/pull/24487/files#diff-b975924c796682179c2a57625716ebd7ec2ae0f017d7ff10815617a8d616c437) in  #24487 to use `from`. At face value, this shouldn't affect anything - `from` and `fromArray` share the same implementation for arrays, after all - but this broke `combineLatestOrDefault`, which we use for our panel component.

I debugged the issue and it turns out that importing from `rxjs/internal/...` imports `node_modules/rxjs/internal/...`, whereas importing from `rxjs` imports from `node_modules/rxjs/_esm2015/internal...` for webpack. [This comment](https://github.com/sourcegraph/sourcegraph/pull/24487#issuecomment-910610320) suggests that webpack handles RxJS internal imports differently from esbuild, but that doesn't seem to be the case.

I (think) I've narrowed down the issue to the `Observable` import itself. We can recreate `fromArray` with a couple of internal imports to the `subscribeToArray` util and `Observable`, which breaks when we import `Observable` from `rxjs` (fortunately, since it means we're onto something).

---

I'm perplexed as to why importing a different variant of RxJS works, but importing from the same RxJS doesn't. I will investigate further, but for now we should revert the changes to fix this serious bug. 

I should also write an integration test to protect the "link to references panel" flow. We currently only have a test for clicking "Find references"

### CODE REVIEW

File: client/web/dev/esbuild/build.ts [hunk 1]
```diff
@@ -41,6 +41,8 @@ export const BUILD_OPTIONS: esbuild.BuildOptions = {
             // https://stackoverflow.com/questions/53758889/rxjs-subscribeto-js-observable-check-works-in-chrome-but-fails-in-chrome-incogn.
             'rxjs/internal/OuterSubscriber': require.resolve('rxjs/_esm5/internal/OuterSubscriber'),
             'rxjs/internal/util/subscribeToResult': require.resolve('rxjs/_esm5/internal/util/subscribeToResult'),
+            'rxjs/internal/util/subscribeToArray': require.resolve('rxjs/_esm5/internal/util/subscribeToArray'),
+            'rxjs/internal/Observable': require.resolve('rxjs/_esm5/internal/Observable'),
```
Comment (tjkandala) [inline client/web/dev/esbuild/build.ts:45]: I didn't test esbuild, but this bug would probably still happen given it'll import the files that break the webpack build

**Review by eseliger — APPROVED** [review]
🤯

**Comment by sqs** [comment]
Ah, sorry for the break and thank you so much for finding and fixing this (and your ideas on how to prevent this in the future).

**Comment by tjkandala** [comment]
@sqs No problem, thank you for reviewing! Do you think it could be that we use the other RxJS "instance"s [`subscribeToResult`](https://sourcegraph.com/github.com/ReactiveX/rxjs@a4bcb84bbcd59abc6c4e811b57a15124757db2f2/-/blob/src/internal/util/subscribeToResult.ts?L23), so `instanceof` causes false negatives? I think we can fix this if we reimplement this ourselves with the "real" `Observable` so as to not reach into internal exports

**Comment by sqs** [comment]
@tjkandala I don't know. If it's possible to rewrite `combineLatestOrDefault` with just standard RxJS operators, that would probably be best. It seems like it should be possible to. When I wrote the operator originally, I couldn't think of a way, but that was a long time ago.

**Comment by tjkandala** [comment]
I'll merge this for a quick fix. Filed #24568 and #24569 for follow-up.

File: client/web/dev/esbuild/build.ts (hunk 1 above)
Comment (tjkandala) [reply client/web/dev/esbuild/build.ts:45]: NVM, this looks like a potential solution for webpack as well
