### PR TITLE
postgresdsn: Dequote PGPORT

### LINKED ISSUE #31365: database: Dequote PGPORT
If you quote the PGPORT value it constructs an invalid DSN. For example, `CODEINTEL_PGPORT="5432"` constructs an illegal DNS resulting in the following dial error:

```
error: illegal Postgres DSN: postgres://sg@127.0.0.1:“5432”/sg?sslmode=disable
```

### PR DESCRIPTION
**Pull request by efritz**
Fixes #31365.

## Test plan

Added unit test cases covering this issue.

### CODE REVIEW

**Review by danieldides — APPROVED** [review]
🚀

File: internal/database/postgresdsn/postgresdsn_test.go [hunk 1]
```diff
@@ -4,84 +4,119 @@ import "testing"
...
-	}, {
-		name: "deploy-sourcegraph password",
-		env: map[string]string{
-			"PGDATABASE": "sg",
-			"PGHOST":     "pgsql",
-			"PGPASSWORD": "REDACTED",
-			"PGPORT":     "5432",
-			"PGSSLMODE":  "disable",
-			"PGUSER":     "sg",
+		{
```
Comment (keegancsmith) [inline internal/database/postgresdsn/postgresdsn_test.go:17]: your gofmt is a busy boy

**Review by keegancsmith — APPROVED** [review]

File: internal/database/postgresdsn/postgresdsn_test.go (hunk 1 above)
Comment (efritz) [reply internal/database/postgresdsn/postgresdsn_test.go:17]: Twas my mouse and enter key, sire.
