### PR TITLE
Cody: Fix error handling in chat messages

### LINKED ISSUE #54256: Cody: Chat thread error does not complete the request
> In VS Code, I have Cody App configured as my server. If I quit the Cody App, then send any message to Cody, the chat UI hangs indefinitely. 

> It looks like the completions client is not getting closed on Error (as I can see the error message shows up in UI if I abort the request manually)?

https://github.com/sourcegraph/sourcegraph/assets/458591/764db14e-6843-4a5d-91f2-58f264171b18

c.f. https://sourcegraph.slack.com/archives/C05AGQYD528/p1687818642849409

### PR DESCRIPTION
**Pull request by philipp-spiess**
Closes #54256

Fix error handling when the client <> server connection is closed when sending chat messages.

## Test plan

https://github.com/sourcegraph/sourcegraph/assets/458591/c8852225-5c1f-41ec-bb0d-1e13c6c22db2

### CODE REVIEW

File: client/cody/src/chat/ChatViewProvider.ts [hunk 1]
```diff
@@ -729,6 +733,7 @@ export class ChatViewProvider implements vscode.WebviewViewProvider, vscode.Disp
      * Send embedding connections or results error to output
      */
     private logEmbeddingsSearchErrors(): void {
+        console.log(this.int)
```
Comment (abeatrix) [inline client/cody/src/chat/ChatViewProvider.ts]:
```suggestion
```

left over?

**Review by abeatrix — APPROVED** [review]
TYSM!

File: client/cody/src/chat/ChatViewProvider.ts (hunk 1 above)
Comment (philipp-spiess) [reply client/cody/src/chat/ChatViewProvider.ts]: haha you are too fast, already removed it :)
