### PR TITLE
make "no searcher endpoints" error message more helpful

### LINKED ISSUE #4101: No searcher endpoints error when using `index:no` on k8s.sgdev
- **Sourcegraph version:** k8s.sgdev.org

#### Steps to reproduce:

1. Search for `(hunk|repository)resolver index:no` on k8s.sgdev.org
2. See that it errors out with `1 error occurred: * text search failed: failed to search gitolite.sgdev.org/13k/mpociot/vat-calculator@: No searcher endpoints` (the repo in the error message changes on retries) 

#### Expected behavior:

Search works. 

#### Actual behavior:
"No searcher endpoints" error with a different repo name each time.

### PR DESCRIPTION
**Pull request by ijt**
Before it wasn't clear what to do about the error.

Fixes #4101 in the sense that it will give users some idea what to do when they encounter that error. A better solution is incremental (a.k.a. "streaming") search #3991, but that is a larger project.

Test plan: Manually trigger #4101 again on k8s.sgdev.org by setting the search replicas back to 1 and issuing the query shown on that issue. Check that the error message looks reasonable.

### CODE REVIEW

**Comment by keegancsmith** [comment]
I feel like we need to have a better solution than just adding more searchers. Feel free to merge this in the meantime. But cc @sqs on the wording of the error message.

File: pkg/endpoint/endpoint.go [hunk 1]
```diff
@@ -174,7 +174,7 @@ func endpointsToMap(u *k8sURL, eps *corev1.Endpoints) (*hashMap, error) {
 		}
 	}
 	if len(urls) == 0 {
-		return nil, errors.Errorf("No %s endpoints", u.Service)
+		return nil, errors.Errorf("no %s endpoints could be found; possibly solvable by adding more searcher replicas (see https://github.com/sourcegraph/sourcegraph/issues/4101)", u.Service)
```
Comment (slimsag) [inline pkg/endpoint/endpoint.go]:
```suggestion
		return nil, errors.Errorf("no %s endpoints could be found (this may indicate more searcher replicas are needed, contact support@sourcegraph.com for assistance)", u.Service)
```

**Comment by slimsag** [comment]
@keegancsmith definitely agree with you, this is just something we can do immediately to help mitigate this issue a bit in the 3.4 release that goes out to major customers.

I proposed some better wording inline.

**Comment by ijt** [comment]
I also agree we need a better solution.

**Comment by slimsag** [comment]
I cherry-pick'd onto 3.4 for next patch release
