### PR TITLE
code monitoring: fix logs wrapping

### LINKED ISSUE #32848: Code monitors: UI overflow of error message block
When an error message is long, the text block overflows its container. 

image

### PR DESCRIPTION
**Pull request by limitedmage**
Fixes #32848

## Test plan

Updated test data with a long string to render in storybook tests.

## App preview:

- [Link](https://sg-web-jp-cmlogswrapping.onrender.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

File: client/web/src/enterprise/code-monitoring/testing/util.ts [hunk 1]
```diff
@@ -467,7 +467,8 @@ export const mockLogs: MonitorTriggerEventsResult = {
                                     __typename: 'MonitorTriggerEvent',
                                     id: 'd',
                                     status: EventStatus.ERROR,
-                                    message: 'Search failed',
+                                    message:
+                                        'Search failed. This is a very long error that should wrap. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
```
Comment (eseliger) [inline client/web/src/enterprise/code-monitoring/testing/util.ts:471]: https://www.youtube.com/watch?v=kkwiQmGWK4c

**Review by eseliger — APPROVED** [review]
