### PR TITLE
Restore stay-on-PR feature

### LINKED ISSUE #6547: Stay on same PR logic is broken
`part` is never passed to `urlToFile`

### PR DESCRIPTION
**Pull request by felixfbecker**
I think this is how it was _supposed_ to work. The `part` was used in GitHub's `urlToFile()`, but not actually passed anymore from anywhere (which didn't fail since it was optional).

This passes it again, and puts it into a `context` parameter because it took me a while to understand before and this clearly separates the _target_ from the _context_ of the _invocation_ (i.e. the source).

I'm not sure about how I feel about coupling this to the invocation part in general. What if the j2d was invoked by command, but the rev still matches? What if the codeintel is a fallback commit from LSIF? But maybe these are not real issues.
The alternative would be to find which part belongs to the target rev, but this would require more context information (because figuring out the rev of a code view is potentially async and we don't want to do that in `urlToFile`, and it was already done), which is actually not that easy to pipe through the code (this PR is actually a good foundation for such context information).

~~I could not test this because of https://github.com/sourcegraph/sourcegraph/issues/6539 (didn't find any MR or PR with same-PR/MR symbols yet that didn't fail)~~
Tested on Gitlab MRs and GitHub PRs.

Fixes #6547

### CODE REVIEW

File: browser/src/libs/github/code_intelligence.ts [hunk 1]
```diff
@@ -351,62 +343,55 @@ export const githubCodeHost: CodeHost = {
...
-            Partial<ViewStateSpec> & { part?: DiffPart }
-    ) => {
-        if (location.viewState) {
+    urlToFile: (sourcegraphURL, target, context) => {
+        if (target.viewState) {
             // A view state means that a panel must be shown, and panels are currently only supported on
             // Sourcegraph (not code hosts).
-            return toAbsoluteBlobURL(sourcegraphURL, {
-                ...location,
-                repoName: location.repoName || location.rawRepoName,
```
Comment (felixfbecker) [inline browser/src/libs/github/code_intelligence.ts]: 📝 **Note:** Removed the fallback to `rawRepoName` because `repoName` is always defined per type. This was a major source of confusion to understand how `rawRepoName` works.

File: browser/src/shared.scss [hunk 2]
```diff
@@ -61,6 +61,7 @@ $body-color-dark: #f2f4f8;
     position: fixed;
     right: 0;
     bottom: 0;
+    z-index: 10000;
```
Comment (felixfbecker) [inline browser/src/shared.scss]: 📝 Global debug menu was hidden on MRs on Gitlab behind the side bar.

**Comment by felixfbecker** [comment]
@sourcegraph/web one last review please :) I tested on GitHub PRs and Gitlab MRs.

**Comment by felixfbecker** [comment]
@lguychard I'll wait for you to take another look
