### PR TITLE
Correctly update UI when adding a changeset to manual campaign

### LINKED ISSUE #7713: a8n/web: Campaign detail view is not updated after adding changeset to manual Campaign
### Steps to reproduce:

1. Create manual campaign
2. Add changeset

#### Expected behavior:

Changeset is added to Campaign and displayed in the list of Changesets.

#### Actual behavior:

Spinner shows up but changeset does not show up in list of Changesets.

Page needs to be reloaded for changeset to show up.

### PR DESCRIPTION
**Pull request by eseliger**
Closes #7713 

I will add an e2e test for manual campaigns in a follow-up to prevent such regressions in the future. This can be merged to unblock beforehand.

### CODE REVIEW

File: web/src/enterprise/campaigns/detail/CampaignDetails.tsx [hunk 1]
```diff
@@ -360,6 +360,12 @@ export const CampaignDetails: React.FunctionComponent<Props> = ({
         }
     }
 
+    const onAddChangeset = (): void => {
+        // we also check the campaign.changesets.totalCount, so an update to the campaign is required as well
+        campaignUpdates.next()
+        nextChangesetUpdate()
```
Comment (felixfbecker) [inline web/src/enterprise/campaigns/detail/CampaignDetails.tsx]: Can we remove this bound function now that its not used in JSX anymore?

Comment (eseliger) [reply web/src/enterprise/campaigns/detail/CampaignDetails.tsx]: let me check for usage

Comment (eseliger) [reply web/src/enterprise/campaigns/detail/CampaignDetails.tsx]: you are right! removed it

**Comment by eseliger** [comment]
merging as e2e failure is one of the known flakes
