### PR TITLE
fix various extensions bugs to improve the basic-code-intel experience

### LINKED ISSUE #838: Error in references breaks subsequent hovers
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Windows 10, Chrome 70.0.3538.77

#### Steps to reproduce:

1. Open any C file on sourcegraph.com (I could only reproduce with C) 
2. Hover over any function
3. Click "Find references"

#### Expected behavior:
It should show the correct references. 
After that the hover features should work normally.

#### Actual behavior:
References tab says "No local references found", even though there is local references on the same file
Console throws error: 
```
An error occurred when sending LSP requests to the language server, disabling this instance of the language extension (reload the page to clear this state).  
Error: method not found at sourcegraph.commands.executeCommand.then.responses
```
After this all hovering features stop working.

### PR DESCRIPTION
**Pull request by sqs**
I made these fixes while working on https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/8.

Fixes #838

### CODE REVIEW

File: shared/src/commands/commands.ts [hunk 1]
```diff
@@ -133,14 +133,33 @@ export function urlForOpenPanel(viewID: string, urlHash: string): string {
...
-        !(args.length >= 2 && args.length <= 4) ||
-        !isArray(args[0]) ||
-        !(args[2] === undefined || args[2] === null)
-    ) {
-        throw new Error(`invalid updateConfiguration arguments: ${JSON.stringify(args)}`)
+    if (!isArray(args) || !(args.length >= 2 && args.length <= 4)) {
+        throw new Error(
+            `invalid updateConfiguration arguments: ${JSON.stringify(
+                args
+            )} (must be an array with either 2 or 4 elements)`
```
Comment (lguychard) [inline shared/src/commands/commands.ts]: Is this error user-facing (where user == extension author)?

If so, wouldn't the user write `executeCommand('updateConfiguration', arg1, ..., argN)` rather than `executeCommand('updateConfiguration', [arg1, ..., argN])`? If that's the case, this error message would be confusing for the user.

File: shared/src/api/extension/api/configuration.ts [hunk 2]
```diff
@@ -70,7 +70,7 @@ export class ExtConfiguration<C extends object> implements ExtConfigurationAPI<C
         return Object.freeze(new ExtConfigurationSection<C>(this.proxy, this.getData().value.final))
     }
 
-    public subscribe(next: () => void): sourcegraph.Unsubscribable {
-        return this.getData().subscribe(next)
+    public subscribe(...args: any[]): sourcegraph.Unsubscribable {
```
[the remark this answers is not in the document]
Comment (sqs) [reply shared/src/api/extension/api/configuration.ts]: Done, and also enhanced the sourcegraph.d.ts Subscribable interface to match that of rxjs

cc @felixfbecker

File: shared/src/commands/commands.ts (hunk 1 above)
Comment (sqs) [reply shared/src/commands/commands.ts]: It is *possible* to write that, but the `updateConfiguration` command is more often used in package.json files, like:

```json
 "contributes": {
    "actions": [
      {
        "id": "basicCodeIntel.toggle",
        "command": "updateConfiguration",
        "commandArguments": [
          [
            "basicCodeIntel.enabled"
          ],
          "${!config.basicCodeIntel.enabled}",
          null,
          "json"
        ],
        "title": "Toggle fuzzy def/ref matching",
        "category": "Basic code intel"
      },
...
```

In this case, the arg numbering makes sense.

It is rare that someone would use `sourcegraph.commands.executeCommand('updateConfiguration', ...)` since there is a facility in the Sourcegraph API for that already: `sourcegraph.configuration.get<T>().update('foo', 'bar')`. Even so, if someone uses `executeCommand('updateConfiguration')`, the [tsdoc](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9affe740ab18e0c6fa01569292a7f4993b90e95e/-/blob/packages/sourcegraph-extension-api/src/sourcegraph.d.ts#L1053:9) makes it sufficiently clear what "args" are that I think "1st arg", "2nd arg", etc., are clear.

File: shared/src/panel/views/HierarchicalLocationsView.tsx [hunk 3]
```diff
@@ -160,8 +160,13 @@ export class HierarchicalLocationsView extends React.PureComponent<Props, State>
             <div className={`hierarchical-locations-view ${this.props.className || ''}`}>
                 {selectedGroups &&
                     GROUPS.map(
-                        ({ name, defaultSize }, i) =>
-                            ((groupByFile && name === 'file') || groups[i].length > 1) && (
+                        ({ name, defaultSize, key }, i) =>
```
[the remark this answers is not in the document]
Comment (sqs) [reply shared/src/panel/views/HierarchicalLocationsView.tsx]: Good call. I will make this code much clearer.

File: web/src/nav/GlobalNavbar.scss [hunk 4]
```diff
@@ -8,7 +8,7 @@
     justify-content: space-between;
     height: 2.75rem;
     width: 100%;
-    z-index: 4;
+    z-index: 200;
```
[the remark this answers is not in the document]
Comment (sqs) [reply web/src/nav/GlobalNavbar.scss]: If I set it to 999999999, it looks weird here (when there is a modal):

screenshot from 2018-12-05 21-03-10

(On a search result page, press **Save this search query** to open this modal.)

There might be more cases, but I can't think of any.

There's possibly a better way to do this, so please open an issue if you can think of one. Otherwise I will merge this because 200 is better than 4 for sure. :smile:

[the remark this answers is not in the document]
Comment (lguychard) [reply web/src/nav/GlobalNavbar.scss]: Ah, I see - I'd wrongly assumed this css to be for injected elements and not website elements. In this case, you're def good to merge as is, my bad :)

File: shared/src/commands/commands.ts (hunk 1 above)
Comment (lguychard) [reply shared/src/commands/commands.ts]: Makes sense, thanks for clarifying.

File: shared/src/panel/views/HierarchicalLocationsView.tsx [hunk 5]
```diff
@@ -156,50 +156,74 @@ export class HierarchicalLocationsView extends React.PureComponent<Props, State>
             { uri: this.props.defaultGroup }
         )
 
+        const groupsToDisplay = GROUPS.filter(({ name, key }, i) => {
```
Comment (sqs) [inline shared/src/panel/views/HierarchicalLocationsView.tsx]: @lguychard PTAL at this much clearer code.

**Comment by sqs** [comment]
@lguychard Thanks for the review! Updated, PTAL.

File: shared/src/panel/views/HierarchicalLocationsView.tsx (hunk 5 above)
Comment (lguychard) [reply shared/src/panel/views/HierarchicalLocationsView.tsx]: definite improvement :)
