### PR TITLE
search: intersect repository matches

### LINKED ISSUE #22651: `select:repo` does not work with `and` patterns
The query [`jaeger and prometheus`](http://localhost:3080/search?q=jaeger+and+prometheus&patternType=literal) works fine on Sourcegraph.com, but when you try to do [`jaeger and prometheus select:repo`](http://localhost:3080/search?q=jaeger+and+prometheus+select:repo&patternType=literal), it fails. This seems to be because [intersectMerge](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@793bd5822d7a02ab377e01f6429fa80efe18b222/-/blob/cmd/frontend/graphqlbackend/search_results.go#L507-L534) seems to be written to only merge file matches, skipping any other result types. I haven't spent the time to figure out if this is a regression, or it just never worked

Queries like `repo:sourcegraph and repo:about` work fine, apparently because we don't use intersect for repo queries. I'm not entirely sure why -- maybe we optimize this down to a single regex pattern? I didn't see where that was happening though.

### PR DESCRIPTION
**Pull request by rvantonder**
Fixes #22651.

Previously, the intersect operation only applied to `FileMatches` and other result types would just not satisfy intersect.

Adjacent concern: we don't actually support proper intersect operations on commit results, and `type:diff (foo and bar)` does not highlight matches of both terms. We need an analogous `AppendMatches` operation for matches within commit messages/diffs for this to work. Intersect on these operations were unsupported before this PR, at least now we intersect by key, which is quite nice.

We should implement that `AppendMatches` operation for `type:diff`/`type:commit`, but I haven't looked into it. If it turns out too tricky for a quick fix, I'll add a stopgap validate `type:diff`/`type:commit` against expressions

### CODE REVIEW

**Review by tsenart — APPROVED** [review]

File: internal/search/result/merge.go [hunk 1]
```diff
@@ -14,30 +14,24 @@ func Union(left, right []Match) []Match {
...
-// for files contained in both result sets.
+// Intersect performs a merge of match results, merging line matches for files
+// contained in both result sets.
 func Intersect(left, right []Match) []Match {
-	rightFileMatches := make(map[Key]*FileMatch)
-	for _, m := range right {
-		if fileMatch, ok := m.(*FileMatch); ok {
-			rightFileMatches[fileMatch.Key()] = fileMatch
-		}
+	rightMap := make(map[Key]Match)
```
Comment (tsenart) [inline internal/search/result/merge.go:20]:
```suggestion
	rightMap := make(map[Key]Match, len(right))
```

File: internal/search/result/merge.go [hunk 2]
```diff
@@ -14,30 +14,24 @@ func Union(left, right []Match) []Match {
...
+	for _, r := range right {
+		rightMap[r.Key()] = r
 	}
 
 	var merged []Match
```
Comment (keegancsmith) [inline internal/search/result/merge.go:25]: minor perf comment: does it make sense to mutate `left` to avoid allocations. eg `merge := left[:0]`. We already mutate the values inside for append matches.

**Review by keegancsmith — APPROVED** [review]

**Review by camdencheek — APPROVED** [review]

**Comment by rvantonder** [comment]
thanks for the tips!
