### PR TITLE
Completely resolve indexed search performance regression in v3.2.0

### LINKED ISSUE #3750: gitCommitResolver should not do lazy OID resolution
Because Zoekt-produced file matches do not contain a commit ID, this is an empty string for Zoekt search results:

https://github.com/sourcegraph/sourcegraph/blob/a464200809bd8d79ef843205084f5d95b1087bfe/cmd/frontend/graphqlbackend/textsearch.go#L81

Due to this you could not fetch information about the Git commit for Zoekt-produced file match search results, as documented:

https://github.com/sourcegraph/sourcegraph/blob/a464200809bd8d79ef843205084f5d95b1087bfe/cmd/frontend/graphqlbackend/textsearch.go#L75-L77

Because customers wanted to do this via GraphQL however, we began supporting it by lazily resolving the Git commit OID when it is an empty string: https://github.com/sourcegraph/sourcegraph/pull/2318

This is not a good change for several reasons:

1. It was the source of a bad perf regression in v3.2.0: https://github.com/sourcegraph/sourcegraph/pull/3685
2. Due to the frequency at which it is called, and variety of circumstances under which it is called, it is difficult to make changes to that resolution logic without introducing perf regressions. e.g. see misconception about removing sync.Once logic here: https://github.com/sourcegraph/sourcegraph/issues/3746
3. The "lookup zoekt-indexed revision if there is none" behavior is not even always desirable, as noted by @keegancsmith  and @ijsnow in https://github.com/sourcegraph/sourcegraph/pull/2318#issuecomment-468403967
4. There is a race condition where the commit is inaccurate: Zoekt produces the results from master `revisionA`, then indexes master `revisionB` and we tell callers of `OID` the results were from master `revisionB` incorrectly.

What we should do:

1. Effectively revert back to the state we were in before https://github.com/sourcegraph/sourcegraph/pull/2318 and https://github.com/sourcegraph/sourcegraph/pull/3685 were merged, without doing on-the-fly OID resolution.
2. Refactor Zoekt codepaths so that when it produces `fileMatchResolver`s, they contain the commit ID that the result came from. Zoekt has this information already and can just pass it down to us, sparing us from major complexity and the need for many caches.

### PR DESCRIPTION
**Pull request by slimsag**
In #3685 I resolved a major indexed search performance regression that was introduced in v3.2.0.

For a search returning 100 repositories and 100 results per repository:

1. After the regression: we would do 100*100 == 10,000 Git OID resolutions (which would overload Gitserver and cause searches to timeout)

2. After my previous resolution, we would no longer do duplicate work and thus only did 100 Git OID resolutions (1 per repository).
    - This was shown in benchmarks and load tests on customer instances to be a substantial improvement.
    - On one customer instance, we've found this still hasn't been enough of an improvement.
    - On another customer instance, we've found we could be doing better.

3. After *this* resolution, we are 100% at the performance level we were at prior to v3.2.0 because we are no longer doing *any* additional Git OID resolutions. Zoekt already has this information and we already acquire this information prior to executing searches, we just weren't correctly reusing this information. Just goes to show that doing things the right way the first time around is incredibly important.

- Likely to fully resolve an outstanding issue that https://app.hubspot.com/contacts/2762526/company/464956351 is facing.
- Will help https://app.hubspot.com/contacts/2762526/company/407948923 and all other customers using indexed search.
- Fixes #3750

Test plan: Both manual testing and automated testing from existing search Go tests.

### CODE REVIEW

File: cmd/frontend/graphqlbackend/textsearch.go [hunk 1]
```diff
@@ -419,17 +419,17 @@ func zoektSearchOpts(k int, query *search.PatternInfo) zoekt.SearchOptions {
...
 	}
 
 	// Tell zoekt which repos to search
 	repoSet := &zoektquery.RepoSet{Set: make(map[string]bool, len(repos))}
-	repoMap := make(map[api.RepoName]*types.Repo, len(repos))
+	repoMap := make(map[api.RepoName]*search.RepositoryRevisions, len(repos))
 	for _, repoRev := range repos {
 		repoSet.Set[string(repoRev.Repo.Name)] = true
-		repoMap[api.RepoName(strings.ToLower(string(repoRev.Repo.Name)))] = repoRev.Repo
+		repoMap[api.RepoName(strings.ToLower(string(repoRev.Repo.Name)))] = repoRev
```
Comment (ijt) [inline cmd/frontend/graphqlbackend/textsearch.go]: Why is repoRev.Repo.Name lower-cased here?

**Comment by ijt** [comment]
Can you add a bit more detail in the description about how you measured the performance and the numbers you saw?

File: cmd/frontend/graphqlbackend/textsearch.go [hunk 2]
```diff
@@ -60,7 +60,7 @@ type fileMatchResolver struct {
 	symbols      []*searchSymbolResult
 	uri          string
 	repo         *types.Repo
-	commitID     api.CommitID // or empty for default branch
+	commitID     api.CommitID
```
[the remark this answers is not in the document]
Comment (slimsag) [reply cmd/frontend/graphqlbackend/textsearch.go]: Yes, it is illegal to provide an empty `commitID` here now (which should be the default assumption of any commitID field or variable without saying otherwise). I've made this explicitly clear in `gitCommitResolver.oid` because there are many optional fields there.

File: cmd/frontend/graphqlbackend/textsearch.go (hunk 1 above)
Comment (slimsag) [reply cmd/frontend/graphqlbackend/textsearch.go]: No clue. It was like this before so I left it. I assume that at some point we worried the input repo names may lead to cases where case-sensitivity would cause them to incorrectly map and repo names are case-insensitive (I assumed), but I don't know the history here.

**Comment by slimsag** [comment]
@ijt That's a great question. Allow me to explain:

1. I have tested that this code works as in no behavior regressions, search results all end up getting the correct revisions in their URLs etc.
2. I have *not* benchmarked the performance before and after this change.

Now I know what you are thinking: "But you also didn't do that in #3685 and the results we saw there were surprising!" and that's 100% true. In this specific change, however, I think it makes sense to move forward without benchmarks. Here's why:

1. Unlike #3685 which added additional logic (i.e. a cache backed by Redis or a custom cache implementation later), this PR doesn't add any additional logic or work, it removes work. The only potential change in performance here is that we are now allocating a map to pass the indexed revisions down the codepath, and this will be a negligible amount as it is pointer keys -> 40 character strings so for 20k repos we're looking at roughly 20,000 (repos) * 8 (pointer size) * 40 (string bytes), or around 6 MB for that map -- something that will surely be acceptable and likely outweighed by gains we get from not doing OID resolution.
2. Benchmarking this change like #3685 will take me ~2-4hr, time that I will not have until after 3.4 is released. This introduces the question: would we rather 3.4 have this change, or not have this change?

Looking at the pros (likely substantial perf wins, likely resolving multiple customer issues finally) and the cons (potential behavior regressions are minimal due to existing tests + manual testing, potential performance regressions are super unlikely as mentioned above), my impression is I would rather have this in 3.4 instead of not.

If you're worried about this, I am happy to concede and defer making this change until after 3.4 when I have time to properly benchmark this -- but I anticipate landing this without benchmarks in 3.4 is the better option for our users here.

Let me know how you think!

**Comment by ijt** [comment]
I agree. The change looks like a clear improvement so please proceed. Let's
keep our eyes on lightstep after this is deployed to see how the query
performance is affected on sourcegraph.com. I'd like to see a snapshot of
the delta.

**Comment by ijt** [comment]
One caveat: this needs to be tested before we release it. All the search
tests should be redone after you cut the new release with this change.

**Comment by slimsag** [comment]
Sounds good, let's make sure we reset those boxes in the test grid. Will fix up CI and merge tonight.
