### PR TITLE
return clone URL for Gitolite repositories

### LINKED ISSUE #3336: Repository shows up as empty when "disableAutoGitUpdates" is true
Repro steps:
• Set `"disableGitAutoUpdates": true`
• Add Gitolite external service w/ some repositories
• Visit repo on Sourcegraph, observe "Empty repository"
• Go to repo settings mirroring page, observe an error. (After merging https://github.com/sourcegraph/sourcegraph/pull/3334, you'll see the error below. Before merging that, the error you see is a JSON unmarshalling error.)

image

I can fix the issue by setting `"disableGitAutoUpdates": false`

The specific error message is the error gitserver returns, because the repo directory does not yet exist. (It's trying to cd into that directory to find the clone URL, but it doesn't exist.) In theory, gitserver would kick off a `git clone` in that scenario, but it doesn't appear to.

## Investigation

* [This](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/gitserver/client.go#L468:18&tab=references) is the method that generates the error shown in the UI. It errors because it attempts to compute the repo remote URL by cd'ing into a directory (the gitserver directory for the repo) that doesn't exist.
* [This enqueue-repo-update handler](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/gitserver/server/server.go#L377:18&tab=references) is invoked to kick off a clone on gitserver. It never fires when `disableAutoGitUpdates` is true.
* [This](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f6a6de81d2a24bb9cc14e4fae872b33bb6b35f13/-/blob/cmd/frontend/internal/app/ui/handlers.go#L188:37) is a code path that hits `enqueue-repo-update` regardless, but it only activates when the repo already exists in gitserver. It's possible that this should fire regardless of whether the repo has already been cloned.

### PR DESCRIPTION
**Pull request by beyang**
What I've learned:
• `disableAutoGitUpdates` doesn't affect the behavior of navigating directly to a repo to get it to clone
• The need for a clone URL to be set the first time gitserver clones a repository is documented in the code, but it's unclear where this clone URL actually comes from. Perhaps it would be useful for repo-updater to expose this and serve as the source of truth for such repository metadata? If that *shouldn't* be repo-updater, what should it be?
• Three code paths that might require a new repo to be cloned to gitserver are (1) repo-updater loop, (2) direct user navigation to a repo page, (3) triggering a repo-update by the `$REPO/-/refresh` endpoint. Any others we might have to cover?
• Maybe it's worth changing the interface of `EnqueueRepoUpdate` (https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/repoupdater/client.go#L145:0) to make it more explicit when the expectation is that a repo is cloned if it doesn't exist already. The current behavior of needing to set `Repo.URL` is a bit hidden. 

Fixes #3336

### CODE REVIEW

**Comment by tsenart** [comment]
@beyang: Added what you wrote on Slack to the PR description.

**Comment by tsenart** [comment]
> disableAutoGitUpdates doesn't affect the behavior of navigating directly to a repo to get it to clone

I suppose that makes some sense, if looking only at the name of the setting. Navigating to the repo isn't an automatic background action, it's a manual user action.

> Perhaps it would be useful for repo-updater to expose this and serve as the source of truth for such repository metadata? If that shouldn't be repo-updater, what should it be?

Yes! This is indeed part of the changes in #2025. We now store all repository metadata in each repo row, including clone URLs.

However, it should be the case today even that repo-updater is the source of truth for repository metadata. That's what the [repo lookup endpoint](https://github.com/sourcegraph/sourcegraph/blob/master/cmd/repo-updater/repoupdater/server.go#L42) is for (which also serves clone URLs).

The difference with the new syncer is that we don't have to contact the upstream codehost for this metadata anymore, since it's all cached in the database and updated with every background sync.

> Three code paths that might require a new repo to be cloned to gitserver are (1) repo-updater loop, (2) direct user navigation to a repo page, (3) triggering a repo-update by the $REPO/-/refresh endpoint. Any others we might have to cover?

Thanks for doing this research. We had it on our plate in 3.4 to untangle this `EnqueueRepoUpdate` mess as part of: #3345. So, we are familiar with these two first code paths, but not the last one. There seem to be [a few more](https://sourcegraph.com/search?q=EnqueueRepoUpdate+repo:%5Egithub.com/sourcegraph/sourcegraph%24+)

> Maybe it's worth changing the interface of EnqueueRepoUpdate (https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/repoupdater/client.go#L145:0) to make it more explicit when the expectation is that a repo is cloned if it doesn't exist already. The current behavior of needing to set Repo.URL is a bit hidden.

Definitely. We're changing that in #3345 to take in a simple repo ID.

**Comment by tsenart** [comment]
I'm sorry you had to go through all this pain. This `EnqueueRepoUpdate` call graph is in very poor condition as I [realised two days ago](https://github.com/sourcegraph/sourcegraph/issues/2609#issuecomment-481359238).

It's a testament that this is high-priority tech debt we must address in the next release cycle.

**Comment by tsenart** [comment]
> What are the main pieces of state that repo-updater maintains (e.g., repo queue)? Is there a way to tell what the current state is?

There's the repo metadata which is stored in Postgres by the sync loops and there's the git update scheduler which is a completely separate component that stores all its state in-memory. Whenever a sync happens, the scheduler is updated. But the git update scheduler can be updated via the repo updater HTTP API explicitly, too.

> There are a number of places where DisableAutoGitUpdates is referenced. Its documentation says "Disable periodically fetching git contents for existing repositories" but it appears it may do more than that?

It should not do any more than that. Looking at all these references confirms that. It affects only the code paths that trigger git updates due to background metadata syncs:  https://sourcegraph.com/search?q=repo:%5Egithub.com/sourcegraph/sourcegraph%24+DisableAutoGitUpdates+

> I tried repro'ing with GitHub repositories (instead of Gitolite). AFAICT, the bug exists there, but is mitigated by the fact that the GitHub repo is eventually cloned in the background. But doesn't this violate "DisableAutoGitUpdates": true?

With `DisableAutoGitUpdates` set to `true`, the automatic git update scheduler is off. This means that after a repo updater metadata sync, updating this schedule is a no-op as you can see:

1. [Here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/repo-updater/repos/util.go#L134:8) for the old metadata syncing code path.
1. And [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/repo-updater/main.go#L151) for the new metadata syncing code path.

However, the repo *can* have its metadata synced **AND THEN** be cloned via a succession of calls to `RepoLookup` and `EnqueueRepoUpdate`.

The `RepoLookup` endpoint [fetches the metadata](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/repo-updater/repoupdater/server.go#L373) from the code host and [stores it back in Postgres](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/repo-updater/repoupdater/server.go#L397) via the Internal HTTP API.

The `EnqueueRepoUpdate` endpoint, then, is usually called with the results of a `RepoLookup` via the [`backend.GitRepo`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c91cde997ed7c6b77ca0e69d0e45c8d3401e74b4/-/blob/cmd/frontend/graphqlbackend/repositories.go#L280) function.

The result of the `RepoLookup` should include the CloneURL, so it can then be passed to `EnqueueRepoUpdate` which works regardless of the value of `DisableAutoGitUpdates`, since it's considered a manual update. 

`EnqueueRepoUpdate` works without CloneURL **ONLY IF** gitserver had cloned this repo before.

**Comment by tsenart** [comment]
And finally, I have some questions to try to clarify how this issue was affecting $CUSTOMER with the new relase, but not the one they were running.

1. Has $CUSTOMER changed `disableAutoGitUpdates` in their upgrade process?
1. Did $CUSTOMER have the experimental `updateScheduler2` enabled before upgrading?

**Comment by tsenart** [comment]
@keegancsmith: Added you as a reviewer because a lot of the answers I gave here are intimately related to our upcoming work on #3345.

File: cmd/frontend/internal/httpapi/repo_refresh.go [hunk 1]
```diff
@@ -15,5 +16,8 @@ func serveRepoRefresh(w http.ResponseWriter, r *http.Request) error {
 	if err != nil {
 		return err
 	}
-	return repoupdater.DefaultClient.EnqueueRepoUpdate(context.Background(), gitserver.Repo{Name: repo.Name})
+	return repoupdater.DefaultClient.EnqueueRepoUpdate(context.Background(), gitserver.Repo{
+		Name: repo.Name,
+		URL:  gitolite.CloneURL(repo.ExternalRepo),
```
Comment (keegancsmith) [inline cmd/frontend/internal/httpapi/repo_refresh.go]: seems very strange to hardcode gitolite here, when any repo type can call this endpoint? Is this a required change? I would suspect it might break our integration with other code hosts that rely on this endpoint.

File: cmd/repo-updater/repos/gitolite.go [hunk 2]
```diff
@@ -67,6 +67,9 @@ func GetGitoliteRepository(ctx context.Context, args protocol.RepoLookupArgs) (r
 			return &protocol.RepoInfo{
 				Name:         args.Repo,
 				ExternalRepo: args.ExternalRepo,
+				VCS: protocol.VCSInfo{
+					URL: gitolite.CloneURL(args.ExternalRepo),
+				},
```
Comment (keegancsmith) [inline cmd/repo-updater/repos/gitolite.go]: :+1: this seems like the most important thing that was missing? I wonder why this wasn't set before.

**Comment by beyang** [comment]
Answers to @tsenart's questions:
> Has $CUSTOMER changed disableAutoGitUpdates in their upgrade process?
No.

> Did $CUSTOMER have the experimental updateScheduler2 enabled before upgrading?
No. Also, they are upgrading from 2.x to 3.2.

A few follow-up questions/clarifications:
* The syncer's responsibility is to collect the set of repositories from the code host. Then it should delete the outdated ones from the DB and enqueue the existing ones by calling the scheduler?
* The syncer will store the clone URL in the DB after 3.4?
* Which of the following does a repo-updater repo update cover? (1) Creating the metadata rows in the DB (2) Updating metadata in the DB (3) Syncing gitserver contents (4) Zoekt reindex. To me, [it looks like](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c91cde997ed7c6b77ca0e69d0e45c8d3401e74b4/-/blob/cmd/repo-updater/repos/scheduler.go#L177-219) it only covers (3), but maybe the syncer triggers 1 + 2? What triggers (4)?
* After `EnqueueRepoUpdate`'s interface is changed (#3345), will it still be necessary for the client to pass the clone URL or will repo-updater obtain that on its own if it is needed (i.e., if gitserver has not yet cloned the repo).

File: cmd/frontend/internal/httpapi/repo_refresh.go (hunk 1 above)
Comment (beyang) [reply cmd/frontend/internal/httpapi/repo_refresh.go]: You're right, but this means the update hook will not work until the repository has been added. And the repository won't be added until the repo-update loop (which is disabled if `disableAutoGitUpdates` is true) adds it (or if a user navigates directly to the repo).

Comment (beyang) [reply cmd/frontend/internal/httpapi/repo_refresh.go]: Fixed here: 638412ca9a73d0693c1df67fcd3f7e30bc360e68

File: cmd/repo-updater/repos/gitolite.go (hunk 2 above)
Comment (beyang) [reply cmd/repo-updater/repos/gitolite.go]: From the docstring, it looks like the method was just added a placeholder. It can't actually fully fetch Gitolite repo metadata, because it would have to invoke the gitserver endpoint, which is only necessary because currently only gitserver has the Gitolite SSH credentials. My guess is that the author didn't want to call that endpoint here, but still needed to return something to indicate the repository exists.

BTW, I think we can fix this whole issue by making the Gitolite SSH credentials be an explicit part of config, then using the golang stdlib ssh package, instead of shelling out to `ssh` to get the Gitolite repo metadata. Then we can have repo-updater hit the Gitolite API directly.

Comment (tsenart) [reply cmd/repo-updater/repos/gitolite.go]: > BTW, I think we can fix this whole issue by making the Gitolite SSH credentials be an explicit part of config, then using the golang stdlib ssh package, instead of shelling out to ssh to get the Gitolite repo metadata. Then we can have repo-updater hit the Gitolite API directly.

We should probably do that as part of integrating Gitolite external services with the new syncer.

**Comment by tsenart** [comment]
> The syncer's responsibility is to collect the set of repositories from the code host. Then it should delete the outdated ones from the DB and enqueue the existing ones by calling the scheduler?

The syncer's responsibility is to converge the set of mirrored repositories with what's defined in external service configuration and to keep their meta-data up-to-date.

The Git update scheduler [subscribes to syncs](https://github.com/sourcegraph/sourcegraph/blob/master/cmd/repo-updater/main.go#L149) and updates its own schedule with the full set of mirrored repos. Eventually, we'd like to move the Git update scheduler to git-server itself and use a unified log (e.g. using Redis Streams) for the data integration between repo-updater and git-server.

> The syncer will store the clone URL in the DB after 3.4?

Yes.

- 3.3: GiHub, GitLab, Bitbucket Server and possible "Other external service kind".
- 3.4: Gitolite and AWS Code Commit

> Which of the following does a repo-updater repo update cover? (1) Creating the metadata rows in the DB (2) Updating metadata in the DB (3) Syncing gitserver contents (4) Zoekt reindex. To me, it looks like it only covers (3), but maybe the syncer triggers 1 + 2? What triggers (4)?

The `EnqueueRepoUpdate` endpoint only covers (3), but, as written before, it's usually preceded at call site by a `RepoLookup` call which syncs metadata.

The syncer publishes diffs to a channel which the git update scheduler reads from and manages its own schedule.

As for (4), I believe Zoekt periodically polls the all existing repos. (Pull, not push). Our idea of using a unified log for data integration would also apply here. See https://brandur.org/redis-streams.

> After EnqueueRepoUpdate's interface is changed (#3345), will it still be necessary for the client to pass the clone URL or will repo-updater obtain that on its own if it is needed (i.e., if gitserver has not yet cloned the repo).

It will only be necessary to pass the repo id. Nothing else.

**Comment by keegancsmith** [comment]
Zoekt is poll based. It is pretty aggressive polling. Given the time and resources it takes to index a repo, the slight delay we get from polling is far less than the amount of indexing it does in a busy org.
