### PR TITLE
app: allow running without ctags/docker

### LINKED ISSUE #48766: SOFT LAUNCH BLOCKER: If Docker is unavailable, do not fail to start. Disable executors and educate why Docker may be useful

### PR DESCRIPTION
**Pull request by slimsag**
Prior to this change, if you ran Sourcegraph App without Docker installed or running then when you ran a search request the backend would make numerous requests to the `symbols` service, which would then spew an _endless_ stream of errors to the console complaining that `docker run` failed as the App `CTAGS_COMMAND` tried to run ctags via Docker.

**I am actively working on bundling/building ctags into the Go binary** so that it will always be present and this will not be an issue, however, I need more time to fix that proper and right now this issue is *severe* and blocks us from showing App to more people: https://github.com/sourcegraph/sourcegraph/issues/48766

This change improves the current status quo substantially by adding a few `if isSingleProgram` conditions to simply disable `symbols` (have it return no results) if you are running App and ctags cannot be started via Docker. An easy to read message is also shown to the user to tell them Docker is missing and how it would make Sourcegraph better for them:

image

Fixes #48766
Helps #47992

## Test plan

* Ran `sg start app` both with and without Docker running on my system, verified behavior of both.
* All changes are gated behind a `if isSingleProgram` conditional and so very low risk to other deployments.

### CODE REVIEW

File: internal/singleprogram/singleprogram.go [hunk 1]
```diff
@@ -134,16 +138,72 @@ func Init(logger log.Logger) {
...
+		// TODO(single-binary): stop relying on a ctags Docker image
+		if haveDocker {
+			ctagsPath = filepath.Join(cacheDir, "universal-ctags-dev")
+			writeFile(ctagsPath, []byte(universalCtagsDevScript), 0700)
+			setDefaultEnv(logger, "CTAGS_COMMAND", ctagsPath)
+		}
+	}
+}
+
+func printStatusCheckError(title, description string, details ...string) {
```
Comment (slimsag) [inline internal/singleprogram/singleprogram.go:166]: This function prints the color dialog:

image

Two notes about it:

1. It will always be used as Batch Changes requires Docker, and presumably that requirement is not going away anytime soon.
2. In another PR soon I will use this same function to print a nicer error if `src` CLI is not available

**Review by efritz — APPROVED** [review]
To beclear, this disables symbols endpoints by default for app _until_ we can bundle ctags into the Go distribution?

**Comment by slimsag** [comment]
> To be clear, this disables symbols endpoints by default for app until we can bundle ctags into the Go distribution?

This disables symbols endpoints _**IF** you do not have Docker_ for App until we can bundle ctags into the Go distribution.
