### PR TITLE
Only render direct tree children

### LINKED ISSUE #13231: Rendering of Directory Children With Single Folder Is Confusing
- **Sourcegraph version:** 3.18
- **Platform information:**

We got a complaint this AM that the way Sourcegraph 3.18 renders directories with only directory children is confusing.

For example:
https://sourcegraph.com/github.com/vanadium/core/-/tree/x

Looks like it contains lots of files / directories.

Which is an empty dir with only a ref folder.
https://github.com/vanadium/core/tree/master/x

This issue was first presented in a JIRA: https://sourcegraph.atlassian.net/jira/servicedesk/projects/SG/queues/custom/1/SG-328

#### Steps to reproduce:

1. Examine directory with single folder containing around 10 files and sub folders
2. Observe that at the single folder level when viewed within the Sourcegraph web UI, the contents of the folder are displayed along with the top level folder (see links above).

### PR DESCRIPTION
**Pull request by felixfbecker**
Fixes #13231 by making sure we ignore the pre-fetched deep children (it's still beneficial to fetch them for caching).

Moves the TreeEntriesSection component into its own file, adds tests for it and uses the new GQL types.

### CODE REVIEW

File: web/src/repo/tree/TreeEntriesSection.tsx [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+            {name}
+            {isDir && '/'}
+        </Link>
+    )
+}
+export const TreeEntriesSection: React.FunctionComponent<{
+    parentPath: string
+    entries: Pick<GQL.ITreeEntry, 'name' | 'isDirectory' | 'url' | 'path'>[]
+}> = ({ parentPath, entries }) => {
+    const directChildren = entries.filter(entry => entry.path === [parentPath, entry.name].filter(Boolean).join('/'))
```
Comment (tjkandala) [inline web/src/repo/tree/TreeEntriesSection.tsx:38]: **question** (non-blocking): What do you think about [this point](https://github.com/sourcegraph/sourcegraph/pull/12931#discussion_r469392386)? I don't feel strongly either way, but `.filter(x => !!x)` could be safer.

Comment (felixfbecker) [reply web/src/repo/tree/TreeEntriesSection.tsx:38]: I honestly don't think that's a concern, I think either way is fine. Technically everything in JS can be overriden, even `undefined`, but it's impractical or impossible to defend against all that and we generally need to trust globals to be sane.

**Comment by felixfbecker** [comment]
Thanks for the review @tjkandala !
