### PR TITLE
search: Fix reading default search pattern type from settings

### LINKED ISSUE #32989: Global config "search.defaultPatternType": "regexp" - stops working in v3.36.x
- **Sourcegraph version:** v3.36.x ->
- **Platform information:** 

#### Steps to reproduce:
1. Enable the global site config `"search.defaultPatternType": "regexp"`
2. Navigate to your `/search` homepage and observe that regex is not enabled by default

Below is a screen capture of the phenomenon --
regexp-config-bug

During testing I upgraded a docker-compose instance from `v3.31.0` to `v3.38.0` checking if regex was enabled by default after every upgrade. 

I observed that this functionality no longer worked after upgrading from `v3.35.2` ->  `v3.36.3`

I then tested this functionality against a kubernetes instance running in v3.38.0 and observed the setting wasn't working there either.

#### Expected behavior:

With this setting enabled, navigating to the homepage should by default have regex based search enabled.

#### Actual behavior:

Search is patternType literal by default.

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

### PR DESCRIPTION
**Pull request by fkling**
Fixes #32989

## Test plan

- Added unit test
- Change default pattern type to `"regexp"` in your users settings and go to the search page. The regular expression button is selected by default.

### CODE REVIEW

File: client/web/src/stores/navbarSearchQueryState.ts [hunk 1]
```diff
@@ -89,7 +89,7 @@ export function setQueryStateFromSettings(settings: SettingsCascadeOrError<Setti
     }
 
     const searchPatternType = defaultPatternTypeFromSettings(settings)
-    if (caseSensitive) {
+    if (searchPatternType) {
```
Comment (camdencheek) [inline client/web/src/stores/navbarSearchQueryState.ts:92]: 💯

**Review by camdencheek — APPROVED** [review]

**Comment by fkling** [comment]
@cla-bot check
