### PR TITLE
Fix duplicated query when using a toggle after switching search modes

### LINKED ISSUE #9407: Search pattern is duplicated when using a toggle after switching search modes
Kapture 2020-03-31 at 10 36 48

### PR DESCRIPTION
**Pull request by lguychard**
Fixes #9407 

Review by commit.

A better fix here might be to model query state in a way that would [make invalid states impossible](https://docs.sourcegraph.com/dev/typescript/patterns#making-invalid-states-impossible-through-union-types): having non-empty `filtersInQuery` state while in plain text mode is an invalid state. We could avoid this by removing the individual `interactiveSearchMode`, `filtersInQuery` state members in favour of an union like this:

```typescript
type QueryState =
    | {
          mode: 'plaintext'
          query: string
          cursorPosition: number
      }
    | {
        mode: 'interactive'
        filters: FiltersToTypeAndValue
        searchPattern: string
    }
```

This doesn't solve the pain point of nested components having to know about the search mode when they want to update the query (see https://github.com/sourcegraph/sourcegraph/pull/9225#discussion_r400034693)

cc @attfarhan

### CODE REVIEW

File: web/src/search/input/MonacoQueryInput.tsx [hunk 1]
```diff
@@ -108,6 +108,7 @@ export class MonacoQueryInput extends React.PureComponent<MonacoQueryInputProps>
     }
 
     public render(): JSX.Element {
+        console.log('MonacoQueryInput render filtersInQUery', (this.props as any).filtersInQuery)
```
Comment (eseliger) [inline web/src/search/input/MonacoQueryInput.tsx]: You probably meant to remove this?

Comment (lguychard) [reply web/src/search/input/MonacoQueryInput.tsx]: Lol. Yeah.

```suggestion
```
