### PR TITLE
a8n: Persistent queues and workers for ChangesetJob …

### LINKED ISSUE #6723: a8n: Use a persistent queue for CampaignJobs and ChangesetJobs
`Runner` executes `CampaignJobs` in goroutines, `a8n.Service` executes `ChangesetJobs` in goroutines.
 
Sooner or later, we probably want to use a "persistent queue" instead of simply scheduling goroutines.

Why? If the `frontend` crashes while `CampaignJob`s/`ChangesetJob`s are executed, progress is lost and we'd be in a state we can't get out of (at least for `previewCampaignPlan`).

By separating the enqueuing of a job (i.e. creating a `ChangesetJob`/`CampaignJob` in the database) and its execution (i.e. a separate `automation-workers` process that checks Postgres for new jobs) we could

1. offload work from frontend to another process, making it easier to scale/run
2. make it more resilient

### PR DESCRIPTION
**Pull request by ryanslade**
Fixes #6723 

Advisory locking added [here](https://github.com/sourcegraph/sourcegraph/pull/7453) was removed as the worker queue pattern we use here has the same effect.

### CODE REVIEW

File: enterprise/internal/a8n/runner.go [hunk 1]
```diff
@@ -235,6 +235,46 @@ func (r *Runner) Wait(ctx context.Context) error {
...
 }
 
+// RunChangesetJobs should run in a background goroutine and is responsible
+// for finding pending jobs and running them.
+// ctx should be canceled to terminate the function
+func RunChangesetJobs(ctx context.Context, s *Store, clock func() time.Time, gitClient GitserverClient, backoffDuration time.Duration) {
+	workerCount, err := strconv.Atoi(maxWorkers)
+	if err != nil {
+		log15.Error("Parsing max worker count, falling back to default of 8", "err", err)
+		workerCount = 8
```
Comment (mrnugget) [inline enterprise/internal/a8n/runner.go]: tiniest nitpick: Maybe pull this out and define it as a constant next to `maxWorkers`?

File: enterprise/internal/a8n/resolvers/resolver.go [hunk 2]
```diff
@@ -715,22 +680,10 @@ func (r *Resolver) PublishChangeset(ctx context.Context, args *graphqlbackend.Pu
 	}
 
 	svc := ee.NewService(r.store, gitserver.DefaultClient, nil, r.httpFactory)
-	changesetJob, campaign, err := svc.CreateChangesetJobForCampaignJob(ctx, campaignJobID)
+	_, _, err = svc.CreateChangesetJobForCampaignJob(ctx, campaignJobID)
```
Comment (mrnugget) [inline enterprise/internal/a8n/resolvers/resolver.go]: Now that we don't need the return values here anymore, this could probably be simplified and only return `changesetJob, err`

File: enterprise/internal/a8n/store.go [hunk 3]
```diff
@@ -62,6 +62,59 @@ func (s *Store) Transact(ctx context.Context) (*Store, error) {
 	return &Store{db: tx, now: s.now}, nil
 }
 
+// ProcessPendingChangesetJobs attempts to fetch one pending changeset job.
+// A pending job is one that has never been started, it's campaign is published and its plan is not cancelled.
```
Comment (mrnugget) [inline enterprise/internal/a8n/store.go]:
```suggestion
// A pending job is one that has never been started, its campaign is published and its plan is not cancelled.
```

File: enterprise/internal/a8n/store.go [hunk 4]
```diff
@@ -62,6 +62,59 @@ func (s *Store) Transact(ctx context.Context) (*Store, error) {
...
+// If found, 'process 'is called. We guarantee that if process is called it will have exclusive global access to
```
Comment (mrnugget) [inline enterprise/internal/a8n/store.go]:
```suggestion
// If found, 'process' is called. We guarantee that if process is called it will have exclusive global access to
```

File: enterprise/internal/a8n/store.go [hunk 5]
```diff
@@ -62,6 +62,59 @@ func (s *Store) Transact(ctx context.Context) (*Store, error) {
...
+	err = process(ctx, tx, job)
+	return true, err
+}
+
+const getPendingChangesetJobQuery = `
+UPDATE changeset_jobs j SET started_at = now() WHERE id = (
+	SELECT j.id FROM changeset_jobs j
+	JOIN campaigns c on c.id = j.campaign_id
+	JOIN campaign_plans p on p.id = c.campaign_plan_id
+	WHERE j.started_at is null
```
Comment (mrnugget) [inline enterprise/internal/a8n/store.go]: Whiniest of all nitpicks: I take slight offense at how you capitalize your SQL (`WHERE` vs. `is null`, `JOIN` vs `on` vs `ASC`) 😉

File: go.mod [hunk 6]
```diff
@@ -92,6 +92,7 @@ require (
 	github.com/hashicorp/go-multierror v1.0.0
 	github.com/hashicorp/go-retryablehttp v0.6.4 // indirect
 	github.com/honeycombio/libhoney-go v1.12.2
+	github.com/inconshreveable/log15 v0.0.0-20200109203555-b30bc20e4fd1
```
Comment (mrnugget) [inline go.mod]: I think you dropped this here, mister

Comment (ryanslade) [reply go.mod]: I should really find out how go modules work.. I don't know why or when it decides to make changes. It must have been something that `goimports` did

Comment (mrnugget) [reply go.mod]: Yeah. `goimports` sees that you added `log15` and then adds this package. I don't know if we can teach it to use `log15 "gopkg.in/inconshreveable/log15.v2"` instead, which is what we use in the rest of the code base.
