### PR TITLE
Prevent stopping repo-sync if querying Bitbucket projectKeys returns "fatal" error

### LINKED ISSUE #40449: A project listed in Bitbucket's projectKey list that the user/token is not authorized to see causes repository sync to stop
- **Sourcegraph version:** 3.42.0
- **Reported by:** https://github.com/sourcegraph/accounts/issues/3
- **Details:** [Slack thread](https://sourcegraph.slack.com/archives/C02EDAQAJQZ/p1660580754620209)
- **Code host affected:** Bitbucket data center

#### Description

When a projectKey is included in the `projectKeys` list that the user is not authorized to see, syncing repositories seems to stop.  This is most noticeable when a repository is deleted from one of the other projects.  Sourcegraph will continue to update it and fail until the unauthorized projectKey is removed from the `projectKeys` list.

#### Steps to reproduce:

**Prep Bitbucket Server**
1. Create multiple projects with repositories
2. Change the permissions on one (we'll refer to this project as `FOO`) such that the user you'll be using in Sourcegraph does not have access to it

**Sourcegraph**
1. Create a new Bitbucket Server code host connection
2. Use `projectKeys` to define the list of projects to sync.  
3. Include in the `projectKeys` all of the project keys including `FOO`

#### Expected behavior:

Syncing should correctly alert the user that the projectKey `FOO` is not authorized.  But, syncing for all other project keys should continue.

#### Actual behavior:

Syncing is stopped once the unauthorized key is found.   This means that deleted repos inside of the other projects will continue to be included in the update scheduler, for example.

/cc @jplahn @ryphil

### PR DESCRIPTION
**Pull request by varsanojidan**
Fixes #40449 
Currently, when looping through the [projectKeys](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/bitbucketserver.go?L281) for a BitBucket host, if we encounter a "fatal" error (i.e. unauthorized, forbidden etc...) we [stop the repo sync](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/syncer.go?L606) completely. This causes repos to become stale and excluded repos to still show up. Because this is an error related to on projectKey out of several, we shouldn't assume that if we fail on the one projectKey we will fail on all of them. Ideally there wouldn't be any unauthorized projectKeys in the list, but in the case that someone makes a mistake and adds a bad projectKey to the list, or permissions on the projectKey were changed, we don't want to have repo-syncing permanently turned off.

This implementation can be expanded to other codehosts to signify if certain requests for repos should't stop a repo-sync if they fail.

## Test plan
Tested locally using a bitbucket ACC that didn't have access to certain projects, added a sourced repo to excluded, repo was excluded now where it was not excluded before this change. Existing tests pass.

Existing tests pass

### CODE REVIEW

**Review by indradhanush — CHANGES_REQUESTED** [review]
This looks like a great PR to use `errors.Warning` that was introduced recently. https://github.com/sourcegraph/sourcegraph/blob/main/lib/errors/warning.go#L30

**Comment by varsanojidan** [comment]
> This looks like a great PR to use `errors.Warning` that was introduced recently. https://github.com/sourcegraph/sourcegraph/blob/main/lib/errors/warning.go#L30

That a great idea, thanks for pointing it out!

File: internal/repos/sources.go [hunk 1]
```diff
@@ -166,6 +166,8 @@ type SourceResult struct {
 	Repo *types.Repo
 	// Err is only set in case the Source ran into an error when listing repositories
 	Err error
+	// NonFatalError identifies that if the error is considered fatal (for example unauthorized) , it should not stop the sync
```
Comment (ryanslade) [inline internal/repos/sources.go:169]:
```suggestion
	// NonFatalError identifies that if the error is considered fatal (for example unauthorized), it should not stop the sync
```

File: internal/repos/syncer.go [hunk 2]
```diff
@@ -602,8 +602,8 @@ func (s *Syncer) SyncExternalService(
 			logger.Error("error from codehost", log.Int("seen", len(seen)), log.Error(err))
 
 			errs = errors.Append(errs, errors.Wrapf(err, "fetching from code host %s", svc.DisplayName))
-
-			if fatal(err) {
+			// Fatal error and override is not set, stop the sync.
+			if !res.NonFatalError && fatal(err) {
```
Comment (ryanslade) [inline internal/repos/syncer.go:606]: I think if we do what Indra suggested and use the warning error type then the logic can be moved into the `fatal` function.

**Comment by varsanojidan** [comment]
@indradhanush addressed the review comments

File: internal/repos/bitbucketserver.go [hunk 3]
```diff
@@ -278,7 +278,9 @@ func (s *BitbucketServerSource) listAllRepos(ctx context.Context, results chan S
 
 			repos, err := s.client.ProjectRepos(ctx, q)
 			if err != nil {
-				ch <- batch{err: errors.Wrapf(err, "bitbucketserver.projectKeys: query=%q", q)}
+				// Getting a "fatal" error on one project key is not a reason to stop the sync,
+				// so set this error as a warning so that the sync continues.
```
Comment (indradhanush) [inline internal/repos/bitbucketserver.go:282]:
```suggestion
				// Getting a "fatal" error for a single project key is not a strong 
				// enough reason to stop syncing, instead wrap this error as a warning
				// so that the sync can continue.
```

File: internal/repos/syncer.go [hunk 4]
```diff
@@ -589,6 +589,11 @@ func (s *Syncer) SyncExternalService(
 	seen := make(map[api.RepoID]struct{})
 	var errs error
 	fatal := func(err error) bool {
+		// If the error is just a warning, then it is not fatal.
+		var ref errors.Warning
+		if err != nil && errors.As(err, &ref) {
```
Comment (indradhanush) [inline internal/repos/syncer.go:594]: Nit: The check for `err != nil` is not needed. `errors.As` will take care of that already. 

I added this here: https://github.com/sourcegraph/sourcegraph/pull/40631.

File: internal/repos/syncer.go [hunk 5]
```diff
@@ -589,6 +589,11 @@ func (s *Syncer) SyncExternalService(
...
+			return false
+		}
 		return errcode.IsUnauthorized(err) ||
```
Comment (indradhanush) [inline internal/repos/syncer.go:597]: Nit: new line here should improve readability. 😀 
```suggestion

		return errcode.IsUnauthorized(err) ||
```

**Review by indradhanush — APPROVED** [review]
Looks good. Left some suggestions. Approve to unblock.

File: internal/repos/syncer.go [hunk 6]
```diff
@@ -589,6 +589,11 @@ func (s *Syncer) SyncExternalService(
 	seen := make(map[api.RepoID]struct{})
 	var errs error
 	fatal := func(err error) bool {
+		// If the error is just a warning, then it is not fatal.
+		var ref errors.Warning
```
Comment (ryanslade) [inline internal/repos/syncer.go:593]: I wonder if it's worth adding an `errors.IsWarning` method to make this easier?

Comment (ryanslade) [reply internal/repos/syncer.go:593]: Proposed here:
https://github.com/sourcegraph/sourcegraph/pull/40656

File: internal/repos/syncer.go [hunk 7]
```diff
@@ -589,6 +589,11 @@ func (s *Syncer) SyncExternalService(
 	seen := make(map[api.RepoID]struct{})
 	var errs error
 	fatal := func(err error) bool {
+		// If the error is just a warning, then it is not fatal.
+		if errors.IsWarning(err) && !errcode.IsAccountSuspended(err) {
```
Comment (ryanslade) [inline internal/repos/syncer.go:593]: Why are we checking accountSuspended here and again lower down?

Comment (indradhanush) [reply internal/repos/syncer.go:593]: My interpretation is that we want to avoid not reporting a fatal error for suspended accounts here. The check below does not have the `!` for the accountSuspended check.

Comment (varsanojidan) [reply internal/repos/syncer.go:593]: I realized I forgot to reply to this but yeah that's why
