### PR TITLE
app: better warning if src-cli is not installed

### LINKED ISSUE #46543: SOFT LAUNCH BLOCKER: If src-cli is not installed, single-binary may not start
```
[    sourcegraph] ERROR service run/util.go:40 Failed to get src-cli version {"error": "exit status 126"}
[    sourcegraph] ERROR service run/util.go:40 Failed to get src-cli version {"error": "exit status 126"}
```

More context: https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1673895116702359?thread_ts=1673750482.204729&cid=C04F9E7GUDP

Easily reproduced (`sg start sourcegraph` with a broken `src` on your PATH)

### PR DESCRIPTION
**Pull request by slimsag**
Sourcegraph already runs best-effort if `src` is not on your path. However, the errors are not very clear about the impact or how to install it. This simply adds a better error message for it:

Fixes #46543

## Test plan

Manually tested by removing `src` from my path and running `sg start app`

### CODE REVIEW

File: internal/singleprogram/singleprogram.go [hunk 1]
```diff
@@ -149,6 +149,14 @@ func Init(logger log.Logger) {
 		)
 	}
 
+	if _, err := exec.LookPath("src"); err != nil {
+		printStatusCheckError(
+			"src-cli is unavailable",
+			"Sourcegraph is better when src-cli is available; batch changes may not work.",
+			"Installation: https://github.com/sourcegraph/src-cli#sourcegraph-cli--",
```
Comment (unknwon) [inline internal/singleprogram/singleprogram.go:156]:
```suggestion
			"Installation: https://github.com/sourcegraph/src-cli",
```

Do we really need this hashtag given it is at the top of README 😂 (expscially with weird-but-correct `--` in the end

**Review by unknwon — APPROVED** [review]
