### PR TITLE
Cody: Fix hallucination detection

### LINKED ISSUE #52023: cody: partial URLs are mistakenly flagged as "hallucinated filepaths"
When Cody responds with an inline code snippet that contains a partial URL, such as a REST endpoint, it is flagged as a hallucinated filepath and then wrapped in a `<span />`, producing the following oddly formatted response contents:

image (3)

The hallucinations detector should:
- Not flag non-filepaths as filepaths
  - It currently would not be possible to achieve this with the pure regex-based approach, as a partial path such as to a directory, e.g. `/some/non-existent/directory`, is indistinguishable from a partial URL such as a REST endpoint, e.g. `/some/api/endpoint`)
- Not replace tokens contained in inline code blocks, since they will always just be rendered as pure text
  - The detector would need to consider the context of the markdown in order to achieve this

### PR DESCRIPTION
**Pull request by deepak2431**
This PR attempted to fix #52023, and #52909.

Changes done:
1. Added validation for API pattern
2. Added validation for the git refs pattern
3. Fix bug where the status of file ending with "/" was returning undefined.

## Test plan

Added tests for the changes made.

### CODE REVIEW

**Comment by deepak2431** [comment]
@philipp-spiess Can I have a review, please?

File: client/cody-shared/src/hallucinations-detector/index.ts [hunk 1]
```diff
@@ -163,6 +163,18 @@ function isFilePathLike(fullMatch: string, pathMatch: string): boolean {
         // Probably a URL.
         return false
     }
-    // TODO: we can do further validation here.
+
+    // check for API endpoints
+    const apiRegex = new RegExp('^/[^\\s]*[./:][^\\s]*$')
```
Comment (philipp-spiess) [inline client/cody-shared/src/hallucinations-detector/index.ts:168]: I don't really understand what this regex is trying to construct. Do you mind explaining the intention here?

Comment (philipp-spiess) [reply client/cody-shared/src/hallucinations-detector/index.ts:168]: I think that this might be a bit too unrestrictive for this kind of check. e.g. `/some/path` is matched by it but it might also be a valid directory?

Comment (deepak2431) [reply client/cody-shared/src/hallucinations-detector/index.ts:168]: This regex is trying to check basically for the strings starting with `/` and have `/:` and similar patterns.  So, API endpoints like `/api/product/:id` can be matched.

To your next point, I agree that `/customer/products` can also be a directory but this can also be an endpoint route if it doesn't have the `/api` keyword.

Also, I would like to mention that most directory strings in the token are of that format  `/some/path/`, so I think that won't be an issue with this test.

LMK what do you think?

Comment (philipp-spiess) [reply client/cody-shared/src/hallucinations-detector/index.ts:168]: I see but I don't think the current regex is good enough at detecting it and it has a lot of false positives, e.g. `/package.json` is matched.

Should we update the logic so that we require it to have at least one _named param_ for this rule? so we match the `/product/:id` use case but not `/product/123`? 

We can do that by updating the regex to something like this:

```
/^\/[^\s]*\/:[^\s]*$/
```

Comment (deepak2431) [reply client/cody-shared/src/hallucinations-detector/index.ts:168]: Yeah, agreed with you here. Let me update the regex. Thanks for the suggestion!

**Comment by deepak2431** [comment]
@philipp-spiess I have updated the regex to a new one, as the one you suggested was getting updated due to ESLint. Added some tests to make sure it's good.

**Comment by philipp-spiess** [comment]
@deepak2431 Yeah I think this should be good too 😎 Let's run the test on CI

**Review by philipp-spiess — APPROVED** [review]
