### PR TITLE
graphqlbackend: Ensure we use a non-negative capacity in zoektIndexedRepos

### LINKED ISSUE #4759: Search appears to bring frontend down
Repro: No deterministic repro, but this appears to be affecting k8s.sgdev.org. Notice the multiple container restarts. If you pull the logs from the previous container, you see the following:
```
panic: runtime error: makeslice: cap out of range

goroutine 56172 [running]:
github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.zoektIndexedRepos(0x23f77c0, 0xc010c002c0, 0xc0017701e0, 0xc002cd05a0, 0x13, 0x13, 0xc00dcee000, 0x0, 0x884f, 0x0, ...)
/buildkite/builds/buildkite-agent-6ffffdfcc4-9vdxd-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/textsearch.go:848 +0x1cc
github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.searchFilesInRepos(0x23f77c0, 0xc010c00280, 0xc010c00240, 0x0, 0x0, 0x0, 0xc002cd05a0, 0x13, 0x13)
/buildkite/builds/buildkite-agent-6ffffdfcc4-9vdxd-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/textsearch.go:899 +0x171e
github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.(*searchResolver).suggestFilePaths(0xc01498aae0, 0x23f7840, 0xc0134d12c0, 0x64, 0xc0134d12c0, 0xc001d4dd50, 0x0, 0x0, 0x0)
/buildkite/builds/buildkite-agent-6ffffdfcc4-9vdxd-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/search.go:571 +0x263
github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.(*searchResolver).Suggestions.func2(0x23f7840, 0xc0134d1260, 0x0, 0x0, 0x0, 0x0, 0x0)
/buildkite/builds/buildkite-agent-6ffffdfcc4-9vdxd-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/search_suggestions.go:99 +0x255
github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.(*searchResolver).Suggestions.func5(0xc010c16bc0, 0x23f7880, 0xc0129f1ce0, 0xc00bb288f8, 0xc013c2aac0, 0xc01498aae0, 0xc001c98eb0)
/buildkite/builds/buildkite-agent-6ffffdfcc4-9vdxd-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/search_suggestions.go:204 +0xdc
created by github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.(*searchResolver).Suggestions
/buildkite/builds/buildkite-agent-6ffffdfcc4-9vdxd-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/search_suggestions.go:200 +0x47c
```

I saw this happen twice within 5 minutes. The query I was attempting to search for was `sourcegraph-server-gen repo:^github.com/sourcegraph/`.

### PR DESCRIPTION
**Pull request by keegancsmith**
This is currently causing panics on our dogfood instances.

Test plan: Added a unit test which reproduces the panic. Unit test now passes.

Supersedes #4761 

Fixes #4759

### CODE REVIEW

File: cmd/frontend/graphqlbackend/textsearch.go [hunk 1]
```diff
@@ -844,8 +844,13 @@ func zoektIndexedRepos(ctx context.Context, z *searchbackend.Zoekt, revs []*sear
 		return nil, nil, err
 	}
 
-	indexed = make([]*search.RepositoryRevisions, 0, len(set))
-	unindexed = make([]*search.RepositoryRevisions, 0, len(revs)-len(set))
+	unindexedCap := len(revs) - len(set)
```
Comment (tsenart) [inline cmd/frontend/graphqlbackend/textsearch.go]: I suppose we don't need this variable anymore.

Comment (keegancsmith) [reply cmd/frontend/graphqlbackend/textsearch.go]: agreed

**Comment by ijt** [comment]
@keegancsmith, thanks for fixing this! Could you explain how it broke, and how this change fixes the problem?

@tsenart, can you post a link to the PR that caused the problem or surfaced it?

**Comment by keegancsmith** [comment]
This commit from this PR just contains a test case which reproduces the problem https://github.com/sourcegraph/sourcegraph/pull/4762/commits/bc83b51f04987076164dc14f296bbf55b07681a1

It happened due to an incorrect assumption that `set` is a subset of `revs`. We now use `len(revs) - count`, but `count` is guaranteed to be `<= len(revs)` since it is calculated via looping through revs.

**Comment by ijt** [comment]
The test changes are quite nice. Thanks for adding them.
