### PR TITLE
App: Improve Code Insights UI for App

### LINKED ISSUE #47569: Update Code Insights page
This is related to [UX: Messaging/Feedback in App](https://github.com/sourcegraph/sourcegraph/issues/48273). 

# Initial screen
When you first navigate to Insights, you see this warning. It's confusing because nothing has "expired" and a user doesn't need to contact an admin to upgrade their license. 

Image

# Insights page
On the Insights page, there should be a notice that Code Insights might be limited in the future. Designs are [here](https://www.figma.com/file/tbM21yr4k9gJNKkjNc0a4m/UX%3A-Messaging%2FFeedback-in-App?node-id=3%3A610&t=kHc5u9zhLqUYl8sD-0). 

# Insights page - Add dashboard button
When you click the "Add dashboard button," you should see the "Limited Access" warning with copy that says, "Dashboards aren't available yet for the Sourcegraph app. Start a Cloud trial to create unlimited insights and dashboards." 

# Insights page - Create insight
Users will only be able to create two insights as unauth'd app users. Right now, a user that's created two insights can still click the "Create insight" button, complete all the steps to create an insight, but then the "Create code insight" button is disabled. We should add messaging that suggests they remove an insight if they'd like to create a new one, or they sign up for a Cloud trial to create unlimited insights and dashboards. 

# Insights page - Dashboards tab
On the Dashboards tab of the Insights page, we should rethink the two "Limited Access" mentions here. It might be overkill with the warning that we're adding to the top, and we're not supporting dashboards yet in app: 
Screen Shot 2023-02-28 at 5 05 44 PM

# Insights - Getting started tab
- The "see more use cases," "documentation," and "some of the most popular use cases" links are broken

# Insights/create
- The "learn more about the use cases" link at the bottom is broken.

### PR DESCRIPTION
**Pull request by philipp-spiess**
Fixes #47569

> When you first navigate to Insights, you see this warning. It's confusing because nothing has "expired" and a user doesn't need to contact an admin to upgrade their license.

✅

> On the Insights page, t[here](https://www.figma.com/file/tbM21yr4k9gJNKkjNc0a4m/UX%3A-Messaging%2FFeedback-in-App?node-id=3%3A610&t=kHc5u9zhLqUYl8sD-0) should be a notice that Code Insights might be limited in the future. Designs are here.

✅ added to all insights pages for clarity and consistency (that’s where we also render the trial mode message)

> When you click the "Add dashboard button," you should see the "Limited Access" warning with copy that says, "Dashboards aren't available yet for the Sourcegraph app. Start a Cloud trial to create unlimited insights and dashboards."

✅ Some adjustment here: Instead of replacing the top level banner, I just updated the text. This is because we otherwise have to do additional bookkeeping to hide the top header here and replace it. I also did not include a CTA link. in the limited access text below because there’s already one on top anyways.

Screenshot 2023-03-13 at 16 58 04

> Users will only be able to create two insights as unauth'd app users. Right now, a user that's created two insights can still click the "Create insight" button, complete all the steps to create an insight, but then the "Create code insight" button is disabled. We should add messaging that suggests they remove an insight if they'd like to create a new one, or they sign up for a Cloud trial to create unlimited insights and dashboards.

✅ I think this messaging is maybe a bit too complex for this small button. Since we already render a limited access banner on that page though, I think we can get away with a tooltip like this. This is also a problem on the Enterprise version though, so I’ve enabled this change without gating it behind App code. cc @vovakulikov 

Screenshot 2023-03-13 at 17 07 22

> On the Dashboards tab of the Insights page, we should rethink the two "Limited Access" mentions here. It might be overkill with the warning that we're adding to the top, and we're not supporting dashboards yet in app:

✅ Removed the banner
 
Screenshot 2023-03-13 at 17 26 40

>	The "see more use cases," "documentation," and "some of the most popular use cases" links are broken >
> 	The "learn more about the use cases" link at the bottom is broken.

This should be fixed by now based on other work.

## Test plan

- Start with `sg start app` which now contains code monitoring
- Stub the license checks in use-license.ts
- Test locally (see screenshots above)

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.01% (+1.53 kb) | 0.01% (+1.53 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ps/app-code-insights/compare-report.html;tab=live_object) for a full comparison between the commits 866af7e and b501819 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

File: client/web/src/enterprise/insights/CodeInsightsAppRouter.tsx [hunk 1]
```diff
@@ -50,25 +51,42 @@ export const CodeInsightsAppRouter = withAuthenticatedUser<CodeInsightsAppRouter
 
     return (
         <CodeInsightsBackendContext.Provider value={api}>
-            <GaConfirmationModal />
+            <GaConfirmationModal isSourcegraphApp={props.isSourcegraphApp} />
```
Comment (vovakulikov) [inline client/web/src/enterprise/insights/CodeInsightsAppRouter.tsx:54]: Not to this PR but I think it's time to consider to share this `window.context` info with hooks as well, because this prop goes out of control I think. 

``` tsx
const { isSourcegraphApp } = useSourcegraphContext()
```

File: client/web/src/enterprise/insights/pages/CodeInsightsRootPage.tsx [hunk 2]
```diff
@@ -119,6 +126,25 @@ interface CodeInsightHeaderActionsProps extends TelemetryProps {
 const CodeInsightHeaderActions: FC<CodeInsightHeaderActionsProps> = props => {
     const { dashboardId, telemetryService } = props
 
+    const { insight } = useUiFeatures()
+    const creationPermission = useObservable(useMemo(() => insight.getCreationPermissions(), [insight]))
+
+    const available = creationPermission?.available ?? false
+
+    console.log({ available })
```
Comment (vovakulikov) [inline client/web/src/enterprise/insights/pages/CodeInsightsRootPage.tsx:134]: Hehe, console.log

File: client/web/src/enterprise/insights/pages/CodeInsightsRootPage.tsx [hunk 3]
```diff
@@ -130,14 +156,11 @@ const CodeInsightHeaderActions: FC<CodeInsightHeaderActionsProps> = props => {
...
             </Button>
-            <Button
-                as={Link}
-                to={encodeDashboardIdQueryParam('/insights/create', dashboardId)}
-                variant="primary"
-                onClick={() => telemetryService.log('InsightAddMoreClick')}
-            >
-                <Icon aria-hidden={true} svgPath={mdiPlus} /> Create insight
-            </Button>
+            {!available ? (
```
Comment (vovakulikov) [inline client/web/src/enterprise/insights/pages/CodeInsightsRootPage.tsx:159]: Hmm, I know that this is probably isn't safe at the moment to change tooltip implementation but I think we should make Tooltip rendering just children in case if content has empty string or undefined value. In this case we would be able to avoid this ternary patter here with `createInsightButton`

**Review by vovakulikov — COMMENTED** [review]
I think since we're using temporal settings for dismissible flag for rendering or not rendering limit access banner, now in this PR it causes a noticeable flash and UI jumps when you go to the insight page for the first time, @philipp-spiess we is what we discussed today on 1-1. Event that we have temporal settings in sync way through window.context it seems that useTemporalSettings work in an async way (because of useObservable hook and its useEffect setState) cc @valerybugakov 

A proper way is to dive into temporal settings and useObservable or fallaback on using useLocalStorage hook instead of useTemporal (at least for now, when we have this problem with async nature of useTemporalSetting hook)

https://user-images.githubusercontent.com/18492575/224781401-edf5dec3-3832-4803-89fc-73d5cc5ccbac.mov

Screenshot 2023-03-13 at 14 19 12

**Comment by philipp-spiess** [comment]
> I think since we're using temporal settings for dismissible flag for rendering or not rendering limit access banner, now in this PR it causes a noticeable flash and UI jumps when you go to the insight page for the first time, @philipp-spiess we is what we discussed today on 1-1. Event that we have temporal settings in sync way through window.context it seems that useTemporalSettings work in an async way (because of useObservable hook and its useEffect setState) cc @valerybugakov
> 
> A proper way is to dive into temporal settings and useObservable or fallaback on using useLocalStorage hook instead of useTemporal (at least for now, when we have this problem with async nature of useTemporalSetting hook)

Yikes, I didn't notice this, will investigate and fix tomorrow. Thanks 😢

File: client/web/src/enterprise/insights/pages/CodeInsightsRootPage.tsx (hunk 2 above)
Comment (philipp-spiess) [reply client/web/src/enterprise/insights/pages/CodeInsightsRootPage.tsx]: Whoops forgot to push the fixup 😓

**Review by vovakulikov — APPROVED** [review]
I see that the flashing UI problem will be addressed in a separate PR so it's approved
