### PR TITLE
escape slashes when converting to patternType:standard query

### LINKED ISSUE #41547: Aggregation drilldown doesn't escape slashes within the pattern
Context: https://sourcegraph.slack.com/archives/CHEKCRWKV/p1662669769229249

Simple example to reproduce:
- [Query for `<title>(.*)</title>`](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+%3Ctitle%3E%28.*%29%3C%2Ftitle%3E&patternType=regexp&groupBy=group)
- Click any aggregation bar
- Query becomes [`/<title>(?:Group)</title>/`](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24++%2F%3Ctitle%3E%28%3F%3AGroup%29%3C%2Ftitle%3E%2F&patternType=regexp&case=yes&groupBy=group), which has no results

Expected: [`/<title>(?:Group)<\/title>/`](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24++%2F%3Ctitle%3E%28%3F%3AGroup%29%3C%5C%2Ftitle%3E%2F&patternType=regexp&case=yes&groupBy=group) (slash escaped), which has results

Note: Search has some heuristics to try to allow this in most cases, but I think we should still play it safe and always escape as we cannot predict all possible queries where this might or might not work.

/cc @joelkw @felixfbecker @vovakulikov

### PR DESCRIPTION
**Pull request by coury-clark**
Closes #41547

## Test plan

Run a search with a slash in `patternType:regexp` such as
`repo:^github\.com/sourcegraph/sourcegraph$ <title>(.*)</title>`

Click on a drilldown query. The drilldown query should correctly escape `/` and produce correct results now in `patternType:standard`, example:

`repo:^github\.com/sourcegraph/sourcegraph$ /<title>(?:Group)<\/title>/`

### CODE REVIEW

File: enterprise/internal/insights/query/querybuilder/regexp.go [hunk 1]
```diff
@@ -117,7 +119,17 @@ type PatternReplacer interface {
 	HasCaptureGroups() bool
 }
 
+var ptn = regexp.MustCompile(`[^\\]\/`)
+
 func (r *regexpReplacer) replaceContent(replacement string) (BasicQuery, error) {
+	if r.needsSlashEscape {
+		log15.Info("prior", "r", replacement)
```
Comment (coury-clark) [inline enterprise/internal/insights/query/querybuilder/regexp.go:126]:
```suggestion
```

File: enterprise/internal/insights/query/querybuilder/regexp.go [hunk 2]
```diff
@@ -164,12 +171,23 @@ func NewPatternReplacer(query BasicQuery, searchType searchquery.SearchType) (Pa
 		return nil, errors.Wrap(err, "failed to parse search query")
 	}
 	var patterns []searchquery.Pattern
+	needsSlashEscape := false
 	searchquery.VisitPattern(plan.ToQ(), func(value string, negated bool, annotation searchquery.Annotation) {
+		if searchType == searchquery.SearchTypeRegex {
```
Comment (chwarwick) [inline enterprise/internal/insights/query/querybuilder/regexp.go:176]: I have a suspicion that only relying on the passed searchType may misinterpret queries that have a patterntype within the query string itself.

Comment (coury-clark) [reply enterprise/internal/insights/query/querybuilder/regexp.go:176]: Notes from sync:

After lots of testing, it seems this path is not possible to hit when submitting searches through the webapp. In the case of hitting the aggregation API directly, it isn't exactly clear what the expected behavior would be since this was ultimately designed to accept the `patternType` argument as the actual type being searched.

Given that, no additional changes are required.

**Review by chwarwick — APPROVED** [review]

File: enterprise/internal/insights/query/querybuilder/regexp_test.go [hunk 3]
```diff
@@ -212,7 +212,19 @@ func TestReplace_Valid(t *testing.T) {
 		{
 			query:       `\/insi(g)ht[s]\/`,
 			replacement: "ggg",
-			want:        autogold.Want("escaped slashes in regexp with group", BasicQuery("/\\/insi(?:ggg)ht[s]\\//")),
+			want:        autogold.Want("ensure queries from type regex to type standard with preescaped slashes", BasicQuery(`/\/insi(?:ggg)ht[s]\//`)),
+			searchType:  query.SearchTypeRegex,
+		},
+		{
+			query:       `<title>(.*)</title>`,
```
[the remark this answers is not in the document]
Comment (coury-clark) [reply enterprise/internal/insights/query/querybuilder/regexp_test.go:219]: Funnily enough adding this test case showed that it is possible to have to escape `patternType:standard` queries

input such as `/<title>(.*)<\/title>/` ends up parsing as `<title>(.*)</title>` which once we produce a drilldown query will break (the escape character is gone). 

Once I realized this I was able to simply the entire thing, so the only time we _don't_ escape is now when we detect a slash with an escape character in the pattern after parsing.

File: enterprise/internal/insights/query/querybuilder/regexp.go [hunk 4]
```diff
@@ -120,8 +121,10 @@ type PatternReplacer interface {
 var ptn = regexp.MustCompile(`[^\\]\/`)
 
 func (r *regexpReplacer) replaceContent(replacement string) (BasicQuery, error) {
+	fmt.Println(replacement)
 	if r.needsSlashEscape {
 		replacement = strings.ReplaceAll(replacement, `/`, `\/`)
+		fmt.Println(replacement)
```
Comment (chwarwick) [inline enterprise/internal/insights/query/querybuilder/regexp.go:127]: whoops

**Review by chwarwick — APPROVED** [review]

File: enterprise/internal/insights/query/querybuilder/regexp.go (hunk 4 above)
Comment (coury-clark) [reply enterprise/internal/insights/query/querybuilder/regexp.go]: fixed
