### PR TITLE
CodeMirror Blob: support fuzzy finder

### LINKED ISSUE #40509: Fuzzy finder doesn't work with CodeMirror blob view when selected
See slack thread for details --> https://sourcegraph.slack.com/archives/CHXHX7XAS/p1660764768980469?thread_ts=1660763673.578239&cid=CHXHX7XAS

### PR DESCRIPTION
**Pull request by olafurpg**
Fixes #40509

Previously, the fuzzy finder was not activated when using the `Mod-k` shortcut while the CodeMirror blob view was focused. 

This PR only moves existing code around. The diff is modestly large because we had to move the fuzzy finder state to the
toplevel `Layout` component and drill it down to the search bar and the blob view (which has a long path from the layout component). 

## Test plan

See the CI go green. I manually verified the change works as expected by triggering Cmd+k while having the CodeMirror blob view focused.

## App preview:

- [Web](https://sg-web-olafurpg-cm-fuzzy-finder.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ynbmuvlxrk.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

File: client/web/src/repo/blob/CodeMirrorBlob.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ import { isValidLineRange, offsetToUIPosition, uiPositionToOffset } from './code
 
 const staticExtensions: Extension = [
     EditorState.readOnly.of(true),
-    EditorView.editable.of(false),
+    EditorView.editable.of(true),
```
Comment (olafurpg) [inline client/web/src/repo/blob/CodeMirrorBlob.tsx:32]:
```suggestion
    EditorView.editable.of(false),
```

File: client/web/src/search/input/SearchNavbarItem.tsx [hunk 2]
```diff
@@ -36,6 +32,7 @@ interface Props
     globbing: boolean
     isSearchAutoFocusRequired?: boolean
     isRepositoryRelatedPage?: boolean
+    onHandleFuzzyFinder?: React.Dispatch<React.SetStateAction<boolean>>
```
Comment (oleggromov) [inline client/web/src/search/input/SearchNavbarItem.tsx:35]: You may also do `BlobProps['onHandleFuzzyFinder']` and import `BlobProps` as everywhere else.

File: client/web/src/repo/blob/BlobPage.tsx [hunk 3]
```diff
@@ -459,6 +460,7 @@ export const BlobPage: React.FunctionComponent<React.PropsWithChildren<Props>> =
                     role="region"
                     ariaLabel="File blob"
                     blameDecorations={blameDecorations}
+                    onHandleFuzzyFinder={props.onHandleFuzzyFinder}
```
Comment (oleggromov) [inline client/web/src/repo/blob/BlobPage.tsx:463]: Perhaps we may use context to avoid prop drilling. I'll have a look at this in the consequent PR.

**Review by oleggromov — APPROVED** [review]
