### PR TITLE
Change browser extension to use a single MutationObserver

### LINKED ISSUE #955: No codeintel in browser extension, Uncaught Error: File actions not found. Make sure you aren't trying to create a toolbar mount for a code snippet that shouldn't have one
I don't get any codeintel when reviewing https://github.com/sourcegraph/sourcegraph/pull/919/files

Version 2.0.6, Chrome, "use extensions" OFF

Error in console:
```
Uncaught Error: File actions not found. Make sure you aren't trying to create a toolbar mount for a code snippet that shouldn't have one
```

### LINKED ISSUE #2162: 'View Repository' button with Chrome(ium) extension disappearing.
- **Sourcegraph version:** N/A (Extension 19.1.29.2106)
- **Platform information:** Chromium 71.0.3578.98

#### Steps to reproduce:

1. Install the Sourcegraph extension 
2. Navigate around various pages on GitHub
3. Observe that the `View Repository` button usually next to `Watch` is missing

4. Refresh the page
5. Observe that the `View Repository` button is now visible

6. Continue to navigate around GitHub
7. Observe that the `View Repository` button disappears again

#### Expected behavior:
The `View Repository` button should remain visible and not only be visible after a page refresh.

#### Actual behavior:
The `View Repository` button disappears unless the page is refreshed, but later disappears again after continuing to browse GitHub.

### LINKED ISSUE #3103: Browser extension not working on Phabricator
Go to https://phabricator.sgdev.org/D1
There is no code intel, no view file buttons, no extension debug button, nothing.

Unclear whether native integration is affected too.

### PR DESCRIPTION
**Pull request by felixfbecker**
Refactors browser extension to use a single MutationObserver whose events are passed as an Observable to functions, instead of only injecting things once and never removing them.
Code views are then detected inside added and removed nodes. When a node with a code view got removed, its state gets properly cleaned up.

It fixes a bunch of bugs/wrong assumptions I found - for example, switchMap was used on the codeViews Observable which could race to randomly drop code views, and the selections and view components code assumed only the latest code view emitted was relevant. Hoverify was never unsubscribed from.

Also does a few renames that made things less confusing for me, e.g. `CodeView` -> `CodeViewSpec`, `CodeView.codeView` -> `CodeView.codeViewElement`

Also removes a hacky MutationObserver workaround in favor of the real fix https://github.com/sourcegraph/codeintellify/pull/100

I've not touched unit tests yet. The functions that take MutationRecords can now be unit tested.
Also not touched other code hosts than GitHub yet.

Fixes #2162 
Fixes https://github.com/sourcegraph/sourcegraph/issues/2958
Fixes #3103
Fixes #955

Tested on
- [x] GitHub
- [x] GitHub + Refined GitHub
- [x] GitHub Enterprise
- [x] Bitbucket Server
- [x] Phabricator
- [ ] Gitlab

### CODE REVIEW

File: client/browser/src/libs/code_intelligence/code_views.ts [hunk 1]
```diff
@@ -48,85 +44,70 @@ const emitWhenIntersecting = (margin: number) => {
...
+                type: 'added' as 'added',
+                ...codeView,
+            })),
+            ...findCodeViews(codeHost, mutation.removedNodes).map(codeView => ({
+                type: 'removed' as 'removed',
+                ...codeView,
+            })),
+        ])
     )
+// .pipe(emitWhenIntersecting(250))
```
Comment (lguychard) [inline client/browser/src/libs/code_intelligence/code_views.ts]: What's your thinking on doing away with `emitWithIntersecting()`? I assume it was put in place for performance reasons when we used to scrape document contents from the DOM, but now that we're fetching the file contents instead, we're probably OK without.

File: client/browser/src/libs/code_intelligence/code_intelligence.tsx [hunk 2]
```diff
@@ -156,16 +157,18 @@ export interface CodeHost {
      */
     getOverlayMount?: () => HTMLElement | null
 
+    // Code views and code view resolver form a union
```
Comment (lguychard) [inline client/browser/src/libs/code_intelligence/code_intelligence.tsx]: I know this is probably a "note to self", but it's probably worth being reworded & moved to the docstrings of `codeViewSpecs` and `codeViewSpecResolver`:

`The set of code views tracked on a page is the union of all code views found using codeViewSpecs and codeViewResolver` (or similar)

File: client/browser/src/libs/code_intelligence/code_views.ts [hunk 3]
```diff
@@ -48,85 +44,70 @@ const emitWhenIntersecting = (margin: number) => {
...
+    mutations: Observable<MutationRecordLike[]>
+): Observable<ResolvedCodeView & { type: 'added' | 'removed' }> =>
+    mutations.pipe(
+        concatAll(),
+        mergeMap(mutation => [
+            ...findCodeViews(codeHost, mutation.addedNodes).map(codeView => ({
+                type: 'added' as 'added',
+                ...codeView,
+            })),
+            ...findCodeViews(codeHost, mutation.removedNodes).map(codeView => ({
```
Comment (lguychard) [inline client/browser/src/libs/code_intelligence/code_views.ts]: Consider this hypothetical `CodeViewResolver`:

```typescript
const ancestorCheckingResolver: CodeViewSpecResolver = {
    selector: '.some-class'
    resolveCodeViewSpec: codeViewElement => {
        // code view element must have an ancestor matching some constraint
        if (!codeViewElement.closest('.some-ancestor-class')) {
            return null
        }
        // ...eventually returns a CodeViewSpec
    }
}
```

Code views from this resolver would still be "leaked" here, because nodes from `mutation.removedNodes` have no parent tree.

AFAICT this is a theoretical bug for now - we have no resolver doing this type of check, [some resolvers do `.closest()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@397cfadbe6388b77887f9b663b9ef25b96cd60e1/-/blob/client/browser/src/libs/github/code_intelligence.ts#L138-153) checks but they don't prevent a code view from being resolved.

File: client/browser/src/libs/code_intelligence/code_intelligence.tsx [hunk 4]
```diff
@@ -467,18 +471,27 @@ export function handleCodeHost({
...
+                              map(fileInfoWithContents => ({
+                                  fileInfo: fileInfoWithContents,
+                                  type,
+                                  codeViewElement,
+                                  ...rest,
+                              }))
+                          )
+                      )
+                  )
+                : [{ type, codeViewElement, resolveFileInfo, ...rest }]
```
Comment (lguychard) [inline client/browser/src/libs/code_intelligence/code_intelligence.tsx]: Does it really make sense to emit `resolveFileInfo()` here?

File: client/browser/src/libs/code_intelligence/code_intelligence.tsx [hunk 5]
```diff
@@ -487,123 +500,159 @@ export function handleCodeHost({
...
-                        />
-                    </TelemetryContext.Provider>,
-                    mount
-                )
             }
-        )
+
+            // Apply added/removed roots/visibleViewComponents
+            extensionsController.services.model.model.next({
+                roots: uniqBy([...codeViewStates.values()].flatMap(state => state.roots), root => root.uri),
```
Comment (lguychard) [inline client/browser/src/libs/code_intelligence/code_intelligence.tsx]: Open question: what would be a valid situation where two code views on the page have the same URI?

File: client/browser/src/extension/scripts/inject.tsx [hunk 6]
```diff
@@ -93,16 +99,8 @@ function injectApplication(): void {
         }
 
         if (isGitHub || isGitHubEnterprise || isPhabricator || isGitlab || isBitbucket) {
-            if (
-                isGitHub ||
-                isGitHubEnterprise ||
-                isGitlab ||
-                isBitbucket ||
-                (await featureFlags.isEnabled('newInject'))
```
[the remark this answers is not in the document]
Comment (felixfbecker) [reply client/browser/src/extension/scripts/inject.tsx]: @ijsnow had mentioned that the feature flag has been on by default for a while

[the remark this answers is not in the document]
Comment (lguychard) [reply client/browser/src/extension/scripts/inject.tsx]: It doesn't seem like it https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/browser/types.ts#L36

File: client/browser/src/libs/code_intelligence/code_intelligence.tsx [hunk 7]
```diff
@@ -487,123 +500,159 @@ export function handleCodeHost({
...
-                    // class then that element does not have any code. We
-                    // must check for "any parent element" because extensions
-                    // create their DOM changes before the blob is tokenized
-                    // into multiple elements.
-                    getCodeElementFromTarget: (target: HTMLElement): HTMLElement | null =>
-                        target.closest('.sourcegraph-extension-element') !== null
-                            ? null
-                            : originalDOM.getCodeElementFromTarget(target),
-                }
+        selectionsChanges.subscribe(selections => {
```
[the remark this answers is not in the document]
Comment (felixfbecker) [reply client/browser/src/libs/code_intelligence/code_intelligence.tsx]: But wasn't that the behaviour before too? The selections are a property of the code host, so I don't see a way to distinguish which selections belong to which code view

File: client/browser/src/libs/code_intelligence/code_intelligence.tsx [hunk 8]
```diff
@@ -438,24 +424,42 @@ export function handleCodeHost({
...
-        showGlobalDebug,
-    })
-    injectViewContextOnSourcegraph(sourcegraphUrl, codeHost, ensureRepoExists, isInPage ? undefined : openOptionsMenu)
+    subscriptions.add(
+        mutations.subscribe(mutations => {
+            // We don't need to inspect the mutations because the functions are idempotent
+            // TODO optimize
+            // Maybe getMount() would have to be replaced by a function that determines if a new mount was added from a given mutation record
+
+            // injectCommandPalette({
```
[the remark this answers is not in the document]
Comment (felixfbecker) [reply client/browser/src/libs/code_intelligence/code_intelligence.tsx]: I just commented out things I hadn't vetted for idempotency yet

File: client/browser/src/libs/code_intelligence/code_views.ts (hunk 1 above)
Comment (felixfbecker) [reply client/browser/src/libs/code_intelligence/code_views.ts]: I just commented it out to exclude it as a possible source of why code views would not be detected properly. So far I've not noticed a perf problem. Maybe @ijsnow can comment on the reasoning behind it

File: client/browser/src/libs/code_intelligence/code_intelligence.tsx (hunk 2 above)
Comment (felixfbecker) [reply client/browser/src/libs/code_intelligence/code_intelligence.tsx]: I am dissatisfied by the redundancy of `codeViewSpecs` and `codeViewSpecResolver`. It causes redundant code to handle both, but every `codeViewSpec` could be expressed by a `codeViewResolver`. However, multiple `codeViewSpecs` are allowed, but only one `codeViewSpecResolver`. I would like to unify them somehow. We could also think about the usefullness of specifying a selector vs simply having `(container: Element) => CodeViewWithoutSelector[]`

File: client/browser/src/libs/code_intelligence/code_views.ts (hunk 3 above)
Comment (felixfbecker) [reply client/browser/src/libs/code_intelligence/code_views.ts]: That's a good point, do you have an idea how to resolve it?
I think it's a good idea for these functions to only inspect the element and not rely on the element's context

File: client/browser/src/libs/code_intelligence/code_intelligence.tsx (hunk 7 above)
[the remark this answers is not in the document]
Comment (lguychard) [reply client/browser/src/libs/code_intelligence/code_intelligence.tsx]: The behaviour wasn't exactly the same before - because we only considered the latest code view as relevant, when selections changed they were only updated on the latest code view.

This _explicitly sets the same selections on all code views_, which is knowingly wrong and I'd like us to avoid that. PTAL https://github.com/sourcegraph/sourcegraph/pull/2937 which offers a solution.

File: client/browser/src/libs/code_intelligence/code_intelligence.tsx (hunk 4 above)
Comment (felixfbecker) [reply client/browser/src/libs/code_intelligence/code_intelligence.tsx]: uhm, no, but I think without it it's not a `ResolvedCodeView`.

File: client/browser/src/libs/code_intelligence/code_intelligence.tsx (hunk 5 above)
Comment (felixfbecker) [reply client/browser/src/libs/code_intelligence/code_intelligence.tsx]: Two snippets in a comment thread can have the same URI.

If you're asking about same _root_ URIs, every file in a PR has the same root URI for head/base.

File: client/browser/src/libs/code_intelligence/code_intelligence.tsx (hunk 7 above)
[the remark this answers is not in the document]
Comment (felixfbecker) [reply client/browser/src/libs/code_intelligence/code_intelligence.tsx]: But only considering the "latest" code view was not correct, since there really isn't such a thing as the "latest" code view (the order in which code views are emitted is random as it depends on MutationObserver and the API requests to fetch contents). I think the previous code would still have the previous selections on the non-"latest" code view so selections did not just apply to the latest

File: client/browser/src/extension/scripts/inject.tsx (hunk 6 above)
[the remark this answers is not in the document]
Comment (felixfbecker) [reply client/browser/src/extension/scripts/inject.tsx]: Talked to @ijsnow and @KattMingMing and the old inject uses the xlang endpoint so is not functional with 3.x instances of Sourcegraph. Any customers on older versions have the Phabricator extension built-in so they would not break from this.

File: client/browser/src/libs/code_intelligence/code_intelligence.tsx (hunk 4 above)
Comment (lguychard) [reply client/browser/src/libs/code_intelligence/code_intelligence.tsx]: But this doesn't matter unless you explicitly declare `codeViews` as `Observable<ResolvedCodeView>`. Its current inferred type is:

```typescript
const codeViews: Observable<{
    dom: DOMFunctions;
    getToolbarMount?: ((codeView: HTMLElement, part?: "base" | "head" | null | undefined) => HTMLElement) | undefined;
    adjustPosition?: PositionAdjuster<RepoSpec & RevSpec & FileSpec & ResolvedRevSpec> | undefined;
    toolbarButtonProps?: ButtonProps | undefined;
    isDiff?: boolean | undefined;
    getSelections?: ((codeViewElement: HTMLElement) => Selection[]) | undefined;
    observeSelections?: ((codeViewElement: HTMLElement) => Observable<Selection[]>) | undefined;
    fileInfo: FileInfoWithContents;
    type: "added";
    codeViewElement: HTMLElement;
} | {
    dom: DOMFunctions;
    getToolbarMount?: ((codeView: HTMLElement, part?: "base" | "head" | null | undefined) => HTMLElement) | undefined;
    adjustPosition?: PositionAdjuster<RepoSpec & RevSpec & FileSpec & ResolvedRevSpec> | undefined;
    toolbarButtonProps?: ButtonProps | undefined;
    isDiff?: boolean | undefined;
    getSelections?: ((codeViewElement: HTMLElement) => Selection[]) | undefined;
    observeSelections?: ((codeViewElement: HTMLElement) => Observable<Selection[]>) | undefined;
    type: "removed";
    codeViewElement: HTMLElement;
    resolveFileInfo: (codeView: HTMLElement) => Observable<FileInfo>;
}>
```

**Comment by felixfbecker** [comment]
> It seems like this change would be code host-agnostic. What do you have in mind?

There is a compile error in `client/browser/src/libs/phabricator/extension.tsx` since `injectCodeIntelligence()` is called but now needs the `mutations` Observable. I am not sure why this error is only in the Phab code. Maybe this is dead code?

File: client/browser/src/libs/code_intelligence/code_intelligence.tsx (hunk 2 above)
Comment (ijsnow) [reply client/browser/src/libs/code_intelligence/code_intelligence.tsx]: > We could also think about the usefullness of specifying a selector vs simply having `(container: Element) => CodeViewWithoutSelector[]`

Why would the resolve function return an array?

File: client/browser/src/libs/code_intelligence/code_intelligence.tsx (hunk 8 above)
[the remark this answers is not in the document]
Comment (ijsnow) [reply client/browser/src/libs/code_intelligence/code_intelligence.tsx]: > vetted for idempotency

IMO, idempotency should be provided by the implementor of `CodeHost`, not the user. This will allow for more logic to stay out of this file. It also seems like the correct place since the code host knows what the DOM looks like but this file should be ignorant of anything code host specific.

File: client/browser/src/libs/code_intelligence/code_views.ts (hunk 1 above)
Comment (ijsnow) [reply client/browser/src/libs/code_intelligence/code_views.ts]: Emitting only when code views are visible or about to be visible was ported over from the old way of handling code hosts. It was added by Kingy in that implementation. It was indeed for performance problems. While the need for it may be reduced, I don't think it would hurt to keep it in.

File: client/browser/src/libs/phabricator/extension.tsx [hunk 9]
```diff
@@ -1,18 +1,30 @@
...
 import { injectCodeIntelligence } from '../code_intelligence'
 import { getPhabricatorCSS, getSourcegraphURLFromConduit } from './backend'
 import { metaClickOverride } from './util'
 
-// NOTE: injectModules is idempotent, so safe to call multiple times on the same page.
+// NOT idempotent.
 async function injectModules(): Promise<void> {
+    // This is added so that the browser extension doesn't
+    // interfere with the native Phabricator integration.
+    // TODO is this racy?
```
Comment (ijsnow) [inline client/browser/src/libs/phabricator/extension.tsx]: It is not intended to be racy. The logic is that [the browser extension code runs after all other code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/extension/manifest.spec.json#L52) is parsed/ran in the document. The native integration runs via a script tag added to the document by Phabricator. However, I just realized that we don't account for async code. I believe that it generally works but we should [add the global class name that we look for to an element in the function that loads the phabricator bundle.](https://sourcegraph.com/github.com/sourcegraph/phabricator-extension/-/blob/rsrc/sourcegraph.js#L39-46)

File: client/browser/src/libs/code_intelligence/code_views.ts (hunk 3 above)
Comment (lguychard) [reply client/browser/src/libs/code_intelligence/code_views.ts]: Not running `resolveCodeViewSpec()` on resolved nodes would solve this issue, and also be OK IMO - we don't need to resolve removed nodes, we just need to account for them being removed.

I agree that it would be a good idea for these functions not to rely on the context, but since right now they do we need to account for it (or change them).

File: client/browser/src/libs/code_intelligence/code_intelligence.tsx (hunk 2 above)
Comment (felixfbecker) [reply client/browser/src/libs/code_intelligence/code_intelligence.tsx]: @ijsnow that would not be a resolve function, it would just return all the code views including their elements given a container.

File: client/browser/src/libs/code_intelligence/code_intelligence.tsx (hunk 8 above)
[the remark this answers is not in the document]
Comment (felixfbecker) [reply client/browser/src/libs/code_intelligence/code_intelligence.tsx]: @ijsnow 	could you clarify what you mean by that?
