### PR TITLE
Fix fetching private extensions from bext

### LINKED ISSUE #5185: Sourcegraph extension not loading on GHE
- **Sourcegraph version:** 3.6
- **Platform information:** Chrome extension on GHE

#### Steps to reproduce:

Reported by https://app.hubspot.com/contacts/2762526/company/768958849

A customer authored an extension and published it to their private extension registry.

It works on their internal Sourcegraph instance, but on their GitHub Enterprise instance, they see the following error in the console:

```
Error fetching extension script URL https://sourcegraph.example.com/-/static/extension/... Error: ajax error 401

extensionsService.ts:160

at a.bind.resolve (browser-polyfill.js:1118)
```

### PR DESCRIPTION
**Pull request by lguychard**
Fixes #5185

Fetching private registry extensions from the browser extension was broken. The fix is twofold:
- On the browser extension side, requests to fetch bundles from the private registry should include credentials. This fixed the 401 error that https://app.hubspot.com/contacts/2762526/company/768958849/ ran into...
- ...but replaced it with a CORS error. This is because in `extension_bundle.go`, `Access-Control` headers were set to allow cross-origin access to bundles hosted on sourcegraph.com. These lax headers caused no issues with same-origin requests made from the self-hosted sourcegraph webapp, but broke cross-origin requests from the browser extension: `The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.`. I fixed this by only downgrading these headers on sourcegraph.com.

Test plan:
- Published an extension to the private registry of my local dev instance and activated it
- Verified that the private extension bundle was correctly fetched from the browser extension on the code host.
- Verified that the private extension bundle was correctly fetched from the webapp.
- Verified that public extension bundles were correctly fetched from the browser extension & the webapp.

### CODE REVIEW

File: enterprise/cmd/frontend/internal/registry/extension_bundle.go [hunk 1]
```diff
@@ -62,9 +63,13 @@ func handleRegistryExtensionBundle(w http.ResponseWriter, r *http.Request) {
...
 
-	// Allow downstream Sourcegraph sites' clients to access this file directly.
-	w.Header().Del("Access-Control-Allow-Credentials") // credentials are not needed
-	w.Header().Set("Access-Control-Allow-Origin", "*")
+	// 🚨 SECURITY sourcegraph.com only: downstream Sourcegraph sites' clients to access this file directly.
+	// On private registries, requests to fetch extension  bundles are authenticated, and Access-Control headers
+	// should be preserved.
+	if (envvar.SourcegraphDotComMode()) {
+		w.Header().Del("Access-Control-Allow-Credentials") // credentials are not needed
+		w.Header().Set("Access-Control-Allow-Origin", "*")
```
Comment (felixfbecker) [inline enterprise/cmd/frontend/internal/registry/extension_bundle.go]: Is this header not needed for private instances too?

Comment (lguychard) [reply enterprise/cmd/frontend/internal/registry/extension_bundle.go]: These headers are set in [`secureHeadersMiddlleware()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/cli/http.go#L125-170):

image

File: enterprise/cmd/frontend/internal/registry/extension_bundle.go [hunk 2]
```diff
@@ -62,9 +63,13 @@ func handleRegistryExtensionBundle(w http.ResponseWriter, r *http.Request) {
 	w.Header().Set("X-Content-Type-Options", "nosniff")
 	w.Header().Set("X-XSS-Protection", "1; mode=block")
 
-	// Allow downstream Sourcegraph sites' clients to access this file directly.
-	w.Header().Del("Access-Control-Allow-Credentials") // credentials are not needed
-	w.Header().Set("Access-Control-Allow-Origin", "*")
+	// 🚨 SECURITY sourcegraph.com only: downstream Sourcegraph sites' clients to access this file directly.
+	// On private registries, requests to fetch extension  bundles are authenticated, and Access-Control headers
```
Comment (beyang) [inline enterprise/cmd/frontend/internal/registry/extension_bundle.go]:
```suggestion
	// On private registries, requests to fetch extension bundles are authenticated, and Access-Control headers
```
