### PR TITLE
search: better error for unsupported not queries

### LINKED ISSUE #16898: Inaccurate alert for unsupported not (...) query
`not (a or b)` gives an incorrect alert about a dangling right parenthesis, it should be saying that the query is not supported

### PR DESCRIPTION
**Pull request by rvantonder**
Fixes #16898. Surfaced today in [slack](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1612203988090800?thread_ts=1612203666.089400&cid=CHEKCRWKV)

I would much prefer doing this with diagnostics in the frontend, so this is a stopgap. I want to also rework some of the parser stuff to mirror the frontend scanner/parser separation which makes it easier to deal with detecting `not <expr>`.

Side note: Man am I happy I didn't have to update these tests manually :-)

### CODE REVIEW

File: internal/search/query/parser.go [hunk 1]
```diff
@@ -810,7 +810,7 @@ loop:
 			nodes = append(nodes, result...)
 		case p.expect(RPAREN) && !isSet(p.heuristics, allowDanglingParens):
 			if p.balanced <= 0 {
-				return nil, errors.New("unbalanced expression: unmatched closing parenthesis )")
+				return nil, errors.New("unsupported expression. The combination of parentheses in the query have an unclear meaning. Try using the content: filter to quote patterns that contain parentheses")
```
Comment (rvantonder) [inline internal/search/query/parser.go:813]: Have to change this message: it may not always be due to a dangling parenthesis at this point in the code, it's just too ambiguous or tricky to handle (i.e., is this parentheses intended to be a pattern or an expression, we just can't reliably tell).

File: internal/search/query/parser_test.go [hunk 2]
```diff
@@ -600,26 +600,27 @@ func TestParseAndOrLiteral(t *testing.T) {
...
 
 	// Fringe tests cases at the boundary of heuristics and invalid syntax.
-	autogold.Want(`)(0 )0`, "ERROR: unbalanced expression: unmatched closing parenthesis )").Equal(t, test(`)(0 )0`))
-	autogold.Want(`((R:)0))0`, "ERROR: unbalanced expression: unmatched closing parenthesis )").Equal(t, test(`((R:)0))0`))
-
+	autogold.Want(`x()(y or z)`, "ERROR: unsupported expression. The combination of parentheses in the query have an unclear meaning. Try using the content: filter to quote patterns that contain parentheses").Equal(t, test(`x()(y or z)`))
+	autogold.Want(`)(0 )0`, "ERROR: unsupported expression. The combination of parentheses in the query have an unclear meaning. Try using the content: filter to quote patterns that contain parentheses").Equal(t, test(`)(0 )0`))
+	autogold.Want(`((R:)0))0`, "ERROR: unsupported expression. The combination of parentheses in the query have an unclear meaning. Try using the content: filter to quote patterns that contain parentheses").Equal(t, test(`((R:)0))0`))
```
Comment (keegancsmith) [inline internal/search/query/parser_test.go:623]: did you have to manually update all these strings?

**Review by keegancsmith — APPROVED** [review]

File: internal/search/query/parser_test.go (hunk 2 above)
Comment (rvantonder) [reply internal/search/query/parser_test.go:623]: > Side note: Man am I happy I didn't have to update these tests manually :-)

nope I just run `go test -update`
