### PR TITLE
Editor extensions: support unknown code hosts

### LINKED ISSUE #18117: Sourcegraph open-in-editor plugins are broken due to repo/URL handling
We[ recently changed how we map names](https://github.com/sourcegraph/sourcegraph/pull/16846), which seems to have broken our open-in-editor extensions. 

We want to fix this so that it's again easy to open a file from Sourcegraph into your editor.

### PR DESCRIPTION
**Pull request by tjkandala**
Closes #18117

We refactored the editor endpoint to use `ReposourceCloneURLToRepoName` (#16846), but it only maps clone URLs for [5 different code hosts](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/cloneurls/clone_urls.go#L28-34), so the editor extensions broke for users with unsupported or generic git hosts. 

This PR adds a check for `Other` external services in `ReposourceCloneURLToRepoName`. 

#### Manual testing with a Gerrit repository

<details>
<summary>Before</summary>

</details>

<details>
<summary>After</summary>

</details>

#### Notes

I didn't implement `reposource.Reposource` for Phabricator because most customers mirror repositories from other code hosts on Phabricator. In that case, the clone URL will be handled either by a supported code host's `CloneURLToRepoName` or a user-configured `Other` code host. If the customer hosts their repositories on Phabricator, they have to add an `Other` code host to handle each repository (according to sqs in this Slack thread: [point 1](https://sourcegraph.slack.com/archives/C01JKF7KUBD/p1611784795045100?thread_ts=1611783692.045000&cid=C01JKF7KUBD), [point 2](https://sourcegraph.slack.com/archives/C01JKF7KUBD/p1611785233046400?thread_ts=1611783692.045000&cid=C01JKF7KUBD)).

### CODE REVIEW

**Comment by felixfbecker** [comment]
This doesn't feel like the ideal solution for our users to me... We made the original change because `guessReponameFromRemoteURL()` was wrong in many cases. The fact that many customers reported breakages means that many customers use those other code hosts, and are now again back to the inferior `guessRepoNameFromRemoteURL()` handling. Wouldn't the better solution be to implement `ReposourceCloneURLToRepoName()` for the other code hosts too? It seems like a major GraphQL API bug that querying a repo by clone URL will not work for multiple, widely used code hosts. If we don't feel confident making that change to the backend as a frontend team, maybe @sourcegraph/core-application can help with fixing that.

I would be fine merging this as a quick fix if we or the core team can commit to that.

**Comment by tjkandala** [comment]
Phabricator is the only code host on our [list of supported code hosts](https://docs.sourcegraph.com/admin/external_service) for which we haven't implemented [`CloneURLToRepoName`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3b5c934/-/tree/internal/conf/reposource) (we don't use Bitbucket Cloud's?), and users with generic git hosts have reported breakages as well. 

Our Phabricator integration seems to be used for repositories that are [mirrored, not hosted,](https://docs.sourcegraph.com/admin/external_service/phabricator) by Phabricator. I don't see a way to generically map such mirror URLs to repo names, but I think the core application team would have more insight there. Users that host repositories on Phabricator configure it as a generic git host, so some/many reports of breakages from Phabricator users can be attributed to not handling unsupported hosts.

I do think using `CloneURLToRepoName` for `Other` would be a better solution since it respects [`repositoryPathPattern`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3b5c934/-/blob/internal/conf/reposource/other.go#L38-73).

**Comment by arussellsaw** [comment]
👋  just picking this up for core app floater duties, just wanna check what's being asked of core app: you'd like us to implement the `reposource.RepoSource` interface for: 
* phabricator
* generic git
* probably perforce at some point?
if that sounds right i can put this into an issue to be picked up next cycle

**Comment by tjkandala** [comment]
>  just wanna check what's being asked of core app: you'd like us to implement the reposource.RepoSource interface

👍

> * phabricator
> * generic git
> * probably perforce at some point?

Exactly, but `Other` is used for generic git hosts, right? If so, then it's already implemented.

Thanks!

File: internal/conf/reposource/other.go [hunk 1]
```diff
@@ -41,7 +41,7 @@ func cloneURLToRepoName(cloneURL, baseURL, repositoryPathPattern string) (string
 		return "", err
 	}
 	if !match {
-		return "", urlMismatchErr{cloneURL: cloneURL, hostURL: baseURL}
+		return "", nil
```
Comment (tjkandala) [inline internal/conf/reposource/other.go:44]: We can't return an error on host mismatch since `ReposourceCloneURLToRepoName` [iterates over all code hosts](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@8b0fad1ba59b711f69f2d8bc8c45c206afe5cb97/-/blob/internal/cloneurls/clone_urls.go#L41-103) trying to match external service type, ultimately producing the repo name. `ReposourceCloneURLToRepoName` previously didn't check for `Other` external services

File: internal/conf/reposource/other.go [hunk 2]
```diff
@@ -52,7 +52,6 @@ func cloneURLToRepoName(cloneURL, baseURL, repositoryPathPattern string) (string
 		return "", urlMismatchErr{cloneURL: cloneURL, hostURL: baseURL}
```
Comment (tjkandala) [inline internal/conf/reposource/other.go:52]: Is there value in returning an error on prefix mismatch? I'm thinking we should remove if if this is a plausible scenario: 
- Other host 1 URL: "https://somecodehost.com/one",
- Other host 2 URL: "https://somecodehost.com/two"
User runs "Open on Sourcegraph" command on their editor for a repo hosted by "Other host 2", but we return an error since there's a host match but a path prefix mismatch with "Other host 1".

**Review by artemruts — APPROVED** [review]
👍

File: internal/conf/reposource/other.go (hunk 1 above)
Comment (unknwon) [reply internal/conf/reposource/other.go:44]: I think what you've commented here, should actually go into code comments. Otherwise, the next person might think this is a bug that we're not returning `urlMismatchErr`.
