### PR TITLE
[fix] User email deletion when sub-repo permissions are enabled

### LINKED ISSUE #57582: Cannot remove email address in user settings page
Sub repo permissions were enabled. Not sure if it plays a role

/cc @mrnugget

### PR DESCRIPTION
**Pull request by pjlast**
Closes #57582 

Fixes an issue where a user's email address could not be deleted while sub-repo permissions are enabled.

## Test plan

Same unit test still asserts that the account was deleted.

### CODE REVIEW

File: cmd/frontend/backend/user_emails.go [hunk 1]
```diff
@@ -436,11 +436,9 @@ func deleteStalePerforceExternalAccounts(ctx context.Context, db database.DB, us
 		return errors.Wrap(err, "deleting stale external account")
 	}
 
-	// Since we deleted an external account for the user we can no longer trust user
-	// based permissions, so we clear them out.
-	// This also removes the user's sub-repo permissions.
-	if err := db.Authz().RevokeUserPermissions(ctx, &database.RevokeUserPermissionsArgs{UserID: userID}); err != nil {
```
Comment (pjlast) [inline cmd/frontend/backend/user_emails.go:442]: The main reason this hangs is because the external account deletion above this already deletes all user permissions associated with that external account. Then, this function tries to delete the same user permissions within the same transaction, and the transaction just hangs. However, we can just remove this part, and replace it with the SubRepoPerms deletion, since the user permissions we would have wanted to revoke will already be revoked by the deletion of the external account deletion.

Comment (eseliger) [reply cmd/frontend/backend/user_emails.go:442]: I think I am confused a bit, where exactly does the user external account store delete the same set of data that this function deleted? Is that through DB triggers? I don't fully get how that hangs 🤔 

Generally, this blanket "revoke user permissions" thing here seems very wrong, it seems to delete much more than it should? This handler which supposedly would only remove perforce permissions for the user for the given email seems to drop ALL permissions instead? 
The new thing seems less intrusive, but would still delete sub-repo perms if the email I unverified or deleted is not the one used with Perforce, right? 
But looking at the DB schema, I guess this is the best we can do today, since the permissions have no reference back to the source that generated them. 
Maybe worth a follow-up ticket for later?

Comment (pjlast) [reply cmd/frontend/backend/user_emails.go:442]: My reasoning might be off here, but [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/backend/user_emails.go?L131) a transaction gets started. Inside that transaction you can see `deleteStalePerforceExternalAccounts` being called.

Then, inside `deleteStalePerforceExternalAccounts`, [we call](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/backend/user_emails.go?L431) `db.UserExternalAccounts().Delete`, which has a [trigger](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/migrations/frontend/1677242688_add_triggers_for_soft_deleted_perms_entities/up.sql?L27) associated with it, that deletes from `user_repo_permissions`.

This is all still in the transaction.

Then `RevokeUserPermissions` gets called, which also tries to delete all permissions from the `user_repo_permissions` table.

Now if I take out that initial wrapping transaction, it also frees up the lock, which is why I assume it's because of the same rows being deleted in the same transaction that's causing the lock in the first place.

But, as you pointed out, the blanket "revoke user permissions" thing is a bit of a nuke. It's a relic from before we had the `user_repo_permissions` table and all the permissions were stored in a single list in the DB. So it was not possible to surgically remove specific permissions, since you didn't know where which permissions came from. So the only option was to nuke everything.

Comment (eseliger) [reply cmd/frontend/backend/user_emails.go:442]: I think I get it now, I am a bit puzzled as to why that would lock up, but doesn't matter too much - I now understand how this fixes it :)

**Review by eseliger — APPROVED** [review]
