### PR TITLE
batches: add changeset cell for displaying internal state

### LINKED ISSUE #49980: Investigate wrong changeset stats bug

### PR DESCRIPTION
**Pull request by BolajiOlajide**
Closes #49980

The `BatchChangesStatsCard` currently doesn't display stats for changesets that are in internal states, such as:

* `PROCESSING`
* `SCHEDULED`
* `RETRYING`
* `FAILED`

This PR adds that cell to the component to display such stats to our customers. The stats are only displayed if at least one changeset exists in any internal state.

CleanShot 2023-04-12 at 13 50 37@2x

## Test plan

* Manually tested
* Confirm update is shown in storybook

## App preview:

- [Web](https://sg-web-bo-add-changeset-others-status.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

File: client/web/src/enterprise/batches/detail/BatchChangeStatsCard.tsx [hunk 1]
```diff
@@ -20,13 +20,17 @@ import {
...
+    ChangesetStatusOthers,
 } from './changesets/ChangesetStatusCell'
 
 import styles from './BatchChangeStatsCard.module.scss'
 
 const ARCHIVED_TOOLTIP =
     'Changesets created by an earlier version of the batch change for repos that are not in scope anymore are archived in the batch change and closed on the code host. They do not count towards the completion percentage.'
 
+const OTHERS_TOOLTIP =
+    'Changesets that are in internal states (FAILED, RETRYING, SCHEDULED, PROCESSING). These changesets do not count towards the completion percentage.'
```
Comment (courier-new) [inline client/web/src/enterprise/batches/detail/BatchChangeStatsCard.tsx:32]: Maybe to simplify a bit just:
```suggestion
    'Changesets in internal states (failed, retrying, scheduled, or processing) do not count towards the completion percentage.'
```

File: client/web/src/enterprise/batches/detail/BatchChangeStatsCard.story.tsx [hunk 2]
```diff
@@ -279,4 +343,344 @@ Closed.argTypes = {
...
+        control: { type: 'number' },
+        defaultValue: 0,
+    },
+    processing: {
+        control: { type: 'number' },
+        defaultValue: 0,
+    },
+}
+
+export const Failed: Story<MockStatsArgs> = args => {
```
Comment (courier-new) [inline client/web/src/enterprise/batches/detail/BatchChangeStatsCard.story.tsx:364]: Hahaha I admire your enthusiasm here, but I think the existing stories in this file for "open" and "closed" and the like were actually referencing the state of the parent batch change, so no need to add so many additional stories for different default values of changeset stats, especially since it's control knob. 🙂

**Review by courier-new — APPROVED** [review]
Looks great! I like the choice of the triple dot icon, and I LOVE how on mobile, the added cell now fills out the missing space on the grid of statuses! 🙌
