### PR TITLE
search contexts: fix CTA prompt when syncing public repositories

### LINKED ISSUE #22340: Connect code host prompt shouldn't be shown in the context popover when public code is added via URL
#### Steps to reproduce:

1. Sign in to an account with no code host connections.
2. Add a public repository via URL.
3. Click context button.

#### Expected behavior:

At this point, the user has added repositories, so they should see the contexts popover content with their own personal search context.

#### Actual behavior:

Connect code host prompt is shown, blocking them from using their personal search context.

CleanShot 2021-06-24 at 14 54 43@2x

### PR DESCRIPTION
**Pull request by novoselrok**
Fixes #22340

### CODE REVIEW

**Review by quinnkeast — APPROVED** [review]

File: client/web/src/SourcegraphWebApp.tsx [hunk 1]
```diff
@@ -638,6 +641,15 @@ class ColdSourcegraphWebApp extends React.Component<SourcegraphWebAppProps, Sour
         })
     }
 
+    private onSyncedPublicRepositoriesUpdate = (publicReposCount: number): void => {
+        this.setState({
+            hasUserSyncedPublicRepositories: publicReposCount > 0,
+        })
+    }
+
+    private hasUserAddedRepositories = (): boolean =>
```
Comment (vovakulikov) [inline client/web/src/SourcegraphWebApp.tsx:650]: Not related to this PR directly but I'm curious maybe we want to move this kind of selector function in a separate file to unload `SourcegraphWebApp` component.

**Review by vovakulikov — APPROVED** [review]
LGTM
