### PR TITLE
fix: avoid duplicate decorations (fixes #1231)

### LINKED ISSUE #1231: Redundant decorations are applied when navigating to the same code view multiple times
- **Sourcegraph version:** 18.12.3.2119
- **Platform information:** Browser extension

#### Preconditions:

- Activate a Sourcegraph extension that adds decoration when viewing code (eg. Git extras)

#### Steps to reproduce:

1. Navigate to a code view on github.com
2. Navigate back
3. Navigate forward to the code view again

#### Expected behavior:

Decorations are displayed only once

image

#### Actual behavior:

Decorations are displayed twice. Further navigations to the same code view will keep adding redundant decorations.

image

### PR DESCRIPTION
**Pull request by lguychard**
This fixes #1231, but the overall behaviour of decorations still leaves to be desired, notably when several extensions try to decorate the same line (eg git blame + codecov). For this to work well, we need something akin to [vscode's DecorationType](https://sourcegraph.com/github.com/Microsoft/vscode/-/blob/src/vs/vscode.d.ts#L1144:34)

Will write follow-up issues to decouple decoration merge/update logic from the DOM, and harmonize it between the website and the browser extension (currently the behaviour is different, but broken in both), and make sure adding decorations from several extensions, and toggling them, is handled gracefully. 

The code changed here is currently hard to test due to high coupling in handleCodeHost (eg. it's not trivial to "setDecorations" from one or several mocked extension in unit tests). Will also work on making this more modular/testable.

### CODE REVIEW

File: client/browser/src/libs/code_intelligence/code_intelligence.tsx [hunk 1]
```diff
@@ -491,27 +491,10 @@ function handleCodeHost(codeHost: CodeHost): Subscription {
                         }
 
                         if (extensionsController && !info.baseCommitID) {
-                            let oldDecorations: Unsubscribable[] = []
-
                             extensionsController.services.textDocumentDecoration
                                 .getDecorations(toTextDocumentIdentifier(info))
                                 .subscribe(decorations => {
-                                    for (const old of oldDecorations) {
```
Comment (lguychard) [inline client/browser/src/libs/code_intelligence/code_intelligence.tsx]: Since this emitted once per decorations provider, it was effectively impossible to have decorations from several extensions displayed on a code view (`oldDecorations` would be cleaned up when each provider emitted)

**Comment by lguychard** [comment]
@ijsnow thanks for the review.

You're right that applyDecorations is easily tested (and in fact, I should probably test it :)

What I wanted to test was more so the behavior when several extensions try to decorate the same line, and that is hard to test because of the coupling with the extensions controller.
