### PR TITLE
Insights streaming search prototype

### LINKED ISSUE #29879: insights: [spike] monorepo improvements
Code Insights currently uses the GraphQL API to perform searches, which has spotty support for large monorepos. When searches fail due to monorepo scale, Code Insights will partially populate, or fail to populate. This spike is to investigate any possible solutions in the short term to make these Code Insights more consistent.

The first avenue we should explore is how much effort it would be and what problems may arise by switching to use the streaming API for search instead of the GraphQL API (ignoring compute until it is available over stream).

### PR DESCRIPTION
**Pull request by coury-clark**
Closes #29879

Implements a new generation method `search-stream` that will utilize the streaming API over GraphQL. This will allow us to test the two in parallel prior to 3.37.

As part of this, I refactored the `work_handler` queue receiver to delegate tasks based on the `generation_method` directly, rather than ad-hoc branches.

Just from local testing the results seem really promising:
1. Queries that fail against `sgtest/megarepo` with GraphQL succeed extremely quickly
2. The results on the series I've tested so far match very well (or streaming is higher due to undercounted GraphQL queries)

Error handling is going to take some figuring out. The entire model of errors is different from the streaming API, so we will need to work out what constitutes a failure. In this PR, none of streaming queries will fail due to errors in the response, only network / infrastructural errors.

CleanShot 2022-01-19 at 13 51 30@2x

### CODE REVIEW

File: enterprise/internal/insights/background/queryrunner/work_handler.go [hunk 1]
```diff
@@ -244,6 +197,91 @@ func (r *workHandler) Handle(ctx context.Context, record workerutil.Record) (err
...
+		return err
+	}
+	job, err := dequeueJob(ctx, r.baseWorkerStore, record.RecordID())
+	if err != nil {
+		return err
+	}
+
+	series, err := r.getSeries(ctx, job.SeriesID)
+	if err != nil {
+		return err
```
Comment (slimsag) [inline enterprise/internal/insights/background/queryrunner/work_handler.go:264]: do you maybe want to wrap some of these errors? you wouldn't know if an error came frmo `limiter.Wait`, `dequeueJob`, `r.getSeries`, etc. in some cases I imagine

File: enterprise/internal/insights/background/queryrunner/work_handler.go [hunk 2]
```diff
@@ -244,6 +197,91 @@ func (r *workHandler) Handle(ctx context.Context, record workerutil.Record) (err
...
+
+	handlersByType := map[types.GenerationMethod]insightsHandler{
+		types.SearchCompute: r.computeHandler,
+		types.SearchStream:  r.searchStreamHandler,
+		types.Search:        r.searchHandler,
+	}
+
+	if executableHandler, ok := handlersByType[series.GenerationMethod]; ok {
+		return executableHandler(ctx, job, series, recordTime)
+	} else {
```
Comment (slimsag) [inline enterprise/internal/insights/background/queryrunner/work_handler.go:280]: nit: usually drop the else clause

File: enterprise/internal/insights/query/graphql.go [hunk 3]
```diff
@@ -128,6 +130,7 @@ func Search(ctx context.Context, query string) (_ *GqlSearchResponse, err error)
 	if err != nil {
 		return nil, errors.Wrap(err, "Post")
 	}
+	log15.Info("graphql search", "url", req.URL.String())
```
Comment (slimsag) [inline enterprise/internal/insights/query/graphql.go:133]: seems like it could be quite verbose :)

File: enterprise/internal/insights/query/streaming/decoder.go [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+		},
+		OnMatches: func(matches []streamhttp.EventMatch) {
+			for _, match := range matches {
+				switch match := match.(type) {
+				case *streamhttp.EventContentMatch:
+					count := 0
+					for _, lineMatch := range match.LineMatches {
+						count += len(lineMatch.OffsetAndLengths)
+					}
+					log15.Debug("EventContentMatch", "count", count)
```
Comment (slimsag) [inline enterprise/internal/insights/query/streaming/decoder.go:41]: these logs are going to make debugging any other part of sourcegraph quite hard 😛

File: enterprise/internal/insights/query/streaming/decoder.go [hunk 5]
```diff
@@ -0,0 +1,78 @@
+package streaming
```
Comment (slimsag) [inline enterprise/internal/insights/query/streaming/decoder.go:1]: maybe consider using the client from src-cli which looks pretty nice + well tested: https://github.com/sourcegraph/src-cli/tree/main/internal/streaming

**Review by slimsag — APPROVED** [review]
nice, left some thoughts/ideas inline but no blockers.

File: enterprise/internal/insights/query/graphql.go (hunk 3 above)
Comment (coury-clark) [reply enterprise/internal/insights/query/graphql.go:133]: removed! Looks like some debugging code got left around :)

File: enterprise/internal/insights/background/queryrunner/work_handler.go (hunk 2 above)
Comment (coury-clark) [reply enterprise/internal/insights/background/queryrunner/work_handler.go:280]: Refactored this

File: enterprise/internal/insights/query/streaming/decoder.go (hunk 4 above)
Comment (coury-clark) [reply enterprise/internal/insights/query/streaming/decoder.go:41]: Agreed, removed

File: enterprise/internal/insights/query/streaming/decoder.go (hunk 5 above)
Comment (coury-clark) [reply enterprise/internal/insights/query/streaming/decoder.go:1]: I looked at this - it seemed to have a few behaviors that would have required refactoring for our use case anyway, so I decided to use the one in src/src. If we need to revisit I'll take another look.
