### PR TITLE
fix unicode highlighting in commit searches

### LINKED ISSUE #4512: Unicode search results has wrong highlights on web page
It's easy to reproduce when searching non-ascii words like below
`repo:^github\.com/xingx-xx/knative-sample-app$ type:commit 加`

### PR DESCRIPTION
**Pull request by ijt**
Fixes #4512 

Test plan: unit test

After:
Screen Shot 2019-06-25 at 17 02 41

Before:
Screen Shot 2019-06-25 at 17 07 52

### CODE REVIEW

File: cmd/frontend/graphqlbackend/search_commits.go [hunk 1]
```diff
@@ -400,13 +401,24 @@ func displayRepoName(repoPath string) string {
 func highlightMatches(pattern *regexp.Regexp, data []byte) *highlightedString {
 	const maxMatchesPerLine = 25 // arbitrary
 
+	// Make map from byte positions to character positions.
+	byteToChar := make(map[int]int)
```
Comment (keegancsmith) [inline cmd/frontend/graphqlbackend/search_commits.go]: can you switch this to a slice of ints, and preallocate the size?

File: cmd/frontend/graphqlbackend/search_commits.go [hunk 2]
```diff
@@ -400,13 +401,24 @@ func displayRepoName(repoPath string) string {
...
+	byteToChar[b] = c
+
 	var highlights []*highlightedRange
 	for i, line := range bytes.Split(data, []byte("\n")) {
 		for _, match := range pattern.FindAllIndex(bytes.ToLower(line), maxMatchesPerLine) {
 			highlights = append(highlights, &highlightedRange{
 				line:      int32(i + 1),
-				character: int32(match[0]),
-				length:    int32(match[1] - match[0]),
+				character: int32(byteToChar[match[0]]),
```
Comment (keegancsmith) [inline cmd/frontend/graphqlbackend/search_commits.go]: are we guaranteed to have match align to unicode byte boundaries?

File: cmd/frontend/graphqlbackend/search_commits.go [hunk 3]
```diff
@@ -400,13 +401,24 @@ func displayRepoName(repoPath string) string {
 func highlightMatches(pattern *regexp.Regexp, data []byte) *highlightedString {
 	const maxMatchesPerLine = 25 // arbitrary
 
+	// Make map from byte positions to character positions.
+	byteToChar := make(map[int]int)
+	var b, c int
+	bytes.Map(func(r rune) rune {
+		byteToChar[b] = c
+		b += utf8.RuneLen(r)
```
Comment (keegancsmith) [inline cmd/frontend/graphqlbackend/search_commits.go]: RuneLen can return `-1`

File: cmd/frontend/graphqlbackend/search_commits.go [hunk 4]
```diff
@@ -400,13 +401,24 @@ func displayRepoName(repoPath string) string {
...
+		c++
+		return r
+	}, data)
+	byteToChar[b] = c
```
Comment (keegancsmith) [inline cmd/frontend/graphqlbackend/search_commits.go]: I think you need to move this to inside of each line?

**Comment by keegancsmith** [comment]
This likely has poor perf since it will be O(n) per match, but a simple way to support this is via `utf8.RuneCount(data[:offset])`.

File: cmd/frontend/graphqlbackend/search_commits.go (hunk 1 above)
Comment (ijt) [reply cmd/frontend/graphqlbackend/search_commits.go]: There are gaps in the domain so it doesn't make as much sense as a slice, but I'm changing it to preallocate the map.

File: cmd/frontend/graphqlbackend/search_commits.go (hunk 2 above)
Comment (ijt) [reply cmd/frontend/graphqlbackend/search_commits.go]: I didn't find anything that says that, but the regexp library does something that looks very much like what you're describing: https://golang.org/src/regexp/regexp.go?s=23994:24039#L735. Also, the doc page says regexp expects UTF-8 encoded strings. https://golang.org/pkg/regexp/

Can you think of a case that might cause the regexp library to fail at this, even though it appears to do the right thing with multibyte characters?

File: cmd/frontend/graphqlbackend/search_commits.go (hunk 3 above)
Comment (ijt) [reply cmd/frontend/graphqlbackend/search_commits.go]: Added something to handle it. `bytes.Map` sends a `utf8.RuneError` in that case.

File: cmd/frontend/graphqlbackend/search_commits.go (hunk 4 above)
Comment (ijt) [reply cmd/frontend/graphqlbackend/search_commits.go]: Fixed.

**Comment by ijt** [comment]
> This likely has poor perf since it will be O(n) per match, but a simple way to support this is via `utf8.RuneCount(data[:offset])`.

I added a benchmark and switched to `utf8.RuneCount`. It's much tidier -- thanks for the suggestion. Here's how it compares to what was there before this PR:
```
benchmark                        old ns/op     new ns/op     delta
Benchmark_highlightMatches-4     3586          3612          +0.73%
```
Seems fine.

File: cmd/frontend/graphqlbackend/search_commits.go [hunk 5]
```diff
@@ -401,19 +402,20 @@ func highlightMatches(pattern *regexp.Regexp, data []byte) *highlightedString {
 	const maxMatchesPerLine = 25 // arbitrary
 
 	var highlights []*highlightedRange
-	for i, line := range bytes.Split(data, []byte("\n")) {
-		for _, match := range pattern.FindAllIndex(bytes.ToLower(line), maxMatchesPerLine) {
+	for i, line := range bytes.Split(bytes.ToLower(data), []byte("\n")) {
```
Comment (keegancsmith) [inline cmd/frontend/graphqlbackend/search_commits.go]: unrelated to your change, but I'd suspect the bytes.ToLower is incorrect. If we want to ignore case, we should be making pattern case insensitive. Additionally, how does ToLower interact with unicode? Is it possible lowering a utf8 rune results in a shorter utf rune. That would give incorrect highlighting results.

File: cmd/frontend/graphqlbackend/search_commits.go [hunk 6]
```diff
@@ -401,19 +402,20 @@ func highlightMatches(pattern *regexp.Regexp, data []byte) *highlightedString {
...
+		for _, match := range pattern.FindAllIndex(line, maxMatchesPerLine) {
 			highlights = append(highlights, &highlightedRange{
 				line:      int32(i + 1),
-				character: int32(match[0]),
-				length:    int32(match[1] - match[0]),
+				character: int32(utf8.RuneCount(line[:match[0]])),
+				length:    int32(utf8.RuneCount(line[:match[1]]) - utf8.RuneCount(line[:match[0]])),
```
Comment (keegancsmith) [inline cmd/frontend/graphqlbackend/search_commits.go]: So this technically could be much faster, since this a `O(nk)` algorithm, where `n` is the number of matches and `k` is the length of the line. With just a little bit of book-keeping you can make it `O(k)`. However, this might be fine in practice, since we don't generally have very long lines. But you should probably benchmark a more complicated use case than your current usecase. Something like `pattern := "a"` and `data = bytes.Repeat([]byte{'a'}, 5000)`. Also validate what the longest line that can be returned. For example we have a max length in searcher. But in zoekt we might not?

File: cmd/frontend/graphqlbackend/search_commits_test.go [hunk 7]
```diff
@@ -124,3 +127,132 @@ func TestExpandUsernamesToEmails(t *testing.T) {
...
+		data    []byte
+	}
+	tests := []struct {
+		name    string
+		args    args
+		want    *highlightedString
+		wantErr bool
+	}{
+		{
+			name: "https://github.com/sourcegraph/sourcegraph/issues/4512 case 1",
```
Comment (keegancsmith) [inline cmd/frontend/graphqlbackend/search_commits_test.go]: these names are quite frustrating to match against and read in go test. Can you not give it a more succinct name. If you want to reference the issue for this, maybe just put that as a comment?

File: cmd/frontend/graphqlbackend/search_commits.go (hunk 5 above)
Comment (ijt) [reply cmd/frontend/graphqlbackend/search_commits.go]: Good point. Filed https://github.com/sourcegraph/sourcegraph/issues/4791.

File: cmd/frontend/graphqlbackend/search_commits_test.go (hunk 7 above)
Comment (ijt) [reply cmd/frontend/graphqlbackend/search_commits_test.go]: Done.

Comment (ijt) [reply cmd/frontend/graphqlbackend/search_commits_test.go]: Done.

File: cmd/frontend/graphqlbackend/search_commits.go (hunk 6 above)
Comment (ijt) [reply cmd/frontend/graphqlbackend/search_commits.go]: I updated the benchmark to highlight two long lines each with 5000 characters as you suggested. It shows the performance staying roughly the same with this change:

```
$ benchcmp old.txt runecount.txt 
benchmark                        old ns/op     new ns/op     delta
Benchmark_highlightMatches-4     81053         80321         -0.90%
```

Comment (ijt) [reply cmd/frontend/graphqlbackend/search_commits.go]: There's a hard coded `maxMatchesPerLine = 25` such that the time complexity is really `O(25 n) = O(n)`. If we later decide to remove that limit then it will make sense to add the bookkeeping you suggested.
